\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics where question_id in (1090,1116,1102);
delete from public.questions where id in (1090,1116,1102);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1102,7,'Systems','Price mechanism and resource allocation','medium','mcq','Sentinel question',
 '["A","B","C","D"]','A','Sentinel',null,true,
 'RU','UZ','Sentinel question','["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published'),
(1090,7,'PPC','Outward shift of the PPC','medium','mcq','An outward shift of the PPC is most likely caused by…',
 '["economic growth/technology","a price ceiling","a fall in demand","higher inflation"]','A',
 'An outward shift reflects increased productive capacity.',null,true,
 'RU 1090','UZ 1090','An outward shift of the PPC is most likely caused by…',
 '["economic growth/technology","a price ceiling","a fall in demand","higher inflation"]',
 '["economic growth/technology","a price ceiling","a fall in demand","higher inflation"]',
 '["economic growth/technology","a price ceiling","a fall in demand","higher inflation"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch5',60,null,'published'),
(1116,7,'PPC','Opportunity cost on a PPC','medium','input',
 'On a PPC, moving from (10, 0) to (4, 3) means giving up 6 units of X to gain 3 units of Y. What is the opportunity cost of 1 unit of Y in terms of X? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'2','The opportunity cost per unit is 6 divided by 3.',null,true,
 'RU 1116','UZ 1116',
 'On a PPC, moving from (10, 0) to (4, 3) means giving up 6 units of X to gain 3 units of Y. What is the opportunity cost of 1 unit of Y in terms of X? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch5',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1102,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Systems','Price mechanism and resource allocation','{}'::jsonb,'published');