\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1020,1021,1030,1070,1071,1072,1078,1085,1092,1093,1106);

delete from public.questions
where id in (1020,1021,1030,1070,1071,1072,1078,1085,1092,1093,1106);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1020,7,'Demand','Movement along the demand curve','medium','mcq','If the price of a good falls, ceteris paribus, what happens?',
 '["Demand curve shifts right","Quantity demanded increases (movement along the curve)","Supply curve shifts left","Quantity supplied decreases (movement along supply)"]','B','Demand law',null,true,
 'RU','UZ','If the price of a good falls, ceteris paribus, what happens?',
 '["Demand curve shifts right","Quantity demanded increases (movement along the curve)","Supply curve shifts left","Quantity supplied decreases (movement along supply)"]',
 '["Demand curve shifts right","Quantity demanded increases (movement along the curve)","Supply curve shifts left","Quantity supplied decreases (movement along supply)"]',
 '["Demand curve shifts right","Quantity demanded increases (movement along the curve)","Supply curve shifts left","Quantity supplied decreases (movement along supply)"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch7',60,null,'published'),

(1021,7,'Demand','Substitute goods','medium','mcq','If the price of coffee rises, what is most likely to happen to demand for tea (a substitute)?',
 '["Demand for tea falls","Demand for tea rises","Supply of tea falls","Quantity demanded of tea falls because its price rose"]','B','Substitute demand',null,true,
 'RU','UZ','If the price of coffee rises, what is most likely to happen to demand for tea (a substitute)?',
 '["Demand for tea falls","Demand for tea rises","Supply of tea falls","Quantity demanded of tea falls because its price rose"]',
 '["Demand for tea falls","Demand for tea rises","Supply of tea falls","Quantity demanded of tea falls because its price rose"]',
 '["Demand for tea falls","Demand for tea rises","Supply of tea falls","Quantity demanded of tea falls because its price rose"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1030,7,'Supply','Law of supply','medium','mcq','Ceteris paribus, the law of supply states that when price rises…',
 '["Quantity supplied falls","Quantity supplied rises","Supply curve shifts left","Demand curve shifts right"]','B','Supply law',null,true,
 'RU','UZ','Ceteris paribus, the law of supply states that when price rises…',
 '["Quantity supplied falls","Quantity supplied rises","Supply curve shifts left","Demand curve shifts right"]',
 '["Quantity supplied falls","Quantity supplied rises","Supply curve shifts left","Demand curve shifts right"]',
 '["Quantity supplied falls","Quantity supplied rises","Supply curve shifts left","Demand curve shifts right"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1070,7,'Demand','Demand shift: tastes and preferences','medium','mcq','A rise in consumer preference for a product will…',
 '["shift demand right","shift demand left","move along demand curve only","shift supply right"]','A','Preferences shift demand',null,true,
 'RU','UZ','A rise in consumer preference for a product will…',
 '["shift demand right","shift demand left","move along demand curve only","shift supply right"]',
 '["shift demand right","shift demand left","move along demand curve only","shift supply right"]',
 '["shift demand right","shift demand left","move along demand curve only","shift supply right"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1071,7,'Demand','Complementary goods','medium','mcq','If the price of petrol rises, demand for cars (a complement) will most likely…',
 '["decrease","increase","stay unchanged","become perfectly elastic"]','A','Complements',null,true,
 'RU','UZ','If the price of petrol rises, demand for cars (a complement) will most likely…',
 '["decrease","increase","stay unchanged","become perfectly elastic"]',
 '["decrease","increase","stay unchanged","become perfectly elastic"]',
 '["decrease","increase","stay unchanged","become perfectly elastic"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1072,7,'Supply','Supply shift: input prices','medium','mcq','If the price of key raw materials falls, supply will…',
 '["shift right","shift left","demand shifts right","does not change"]','A','Input costs',null,true,
 'RU','UZ','If the price of key raw materials falls, supply will…',
 '["shift right","shift left","demand shifts right","does not change"]',
 '["shift right","shift left","demand shifts right","does not change"]',
 '["shift right","shift left","demand shifts right","does not change"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1078,7,'Elasticity','Cross elasticity and complements','medium','mcq','If the price of A rises and demand for B falls, A and B are most likely…',
 '["complements","substitutes","unrelated","inferior goods"]','A','Cross elasticity',null,true,
 'RU','UZ','If the price of A rises and demand for B falls, A and B are most likely…',
 '["complements","substitutes","unrelated","inferior goods"]',
 '["complements","substitutes","unrelated","inferior goods"]',
 '["complements","substitutes","unrelated","inferior goods"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1085,7,'Demand','Normal goods','medium','mcq','A normal good is one for which demand…',
 '["rises when income rises","falls when income rises","never changes with income","depends only on price"]','A','Normal good',null,true,
 'RU','UZ','A normal good is one for which demand…',
 '["rises when income rises","falls when income rises","never changes with income","depends only on price"]',
 '["rises when income rises","falls when income rises","never changes with income","depends only on price"]',
 '["rises when income rises","falls when income rises","never changes with income","depends only on price"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1092,7,'Demand','Demand and expectations','medium','mcq','If consumers expect prices to fall soon, current demand will likely…',
 '["decrease","increase","stay unchanged","become perfectly inelastic"]','A','Expectations',null,true,
 'RU','UZ','If consumers expect prices to fall soon, current demand will likely…',
 '["decrease","increase","stay unchanged","become perfectly inelastic"]',
 '["decrease","increase","stay unchanged","become perfectly inelastic"]',
 '["decrease","increase","stay unchanged","become perfectly inelastic"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1093,7,'Supply','Tax and supply','medium','mcq','A higher business tax will most likely…',
 '["shift supply left","shift supply right","shift demand right","raise demand"]','A','Tax and supply',null,true,
 'RU','UZ','A higher business tax will most likely…',
 '["shift supply left","shift supply right","shift demand right","raise demand"]',
 '["shift supply left","shift supply right","shift demand right","raise demand"]',
 '["shift supply left","shift supply right","shift demand right","raise demand"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published'),

(1106,7,'Demand','Simultaneous shifts of demand and supply','medium','mcq','Demand increases and supply decreases at the same time. What is the most likely effect on equilibrium price and quantity?',
 '["Price rises; quantity is ambiguous (could rise or fall)","Price falls; quantity rises","Price rises; quantity definitely rises","Price falls; quantity is ambiguous"]','A','Simultaneous shifts',null,true,
 'RU','UZ','Demand increases and supply decreases at the same time. What is the most likely effect on equilibrium price and quantity?',
 '["Price rises; quantity is ambiguous (could rise or fall)","Price falls; quantity rises","Price rises; quantity definitely rises","Price falls; quantity is ambiguous"]',
 '["Price rises; quantity is ambiguous (could rise or fall)","Price falls; quantity rises","Price rises; quantity definitely rises","Price falls; quantity is ambiguous"]',
 '["Price rises; quantity is ambiguous (could rise or fall)","Price falls; quantity rises","Price rises; quantity definitely rises","Price falls; quantity is ambiguous"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch7',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1071,'mcq_option','A','decrease',true,null,null,
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Demand','Complementary goods','{}'::jsonb,'published');