\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1028,1029,1079,1081,1121,1133);

delete from public.questions
where id in (1028,1029,1079,1081,1121,1133);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1081,7,'Market','Allocative efficiency','medium','mcq','Sentinel',
 '["A","B","C","D"]','A','Sentinel',null,true,'RU','UZ','Sentinel',
 '["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch11',60,null,'published'),

(1028,7,'Market','Consumer surplus','medium','mcq','Consumer surplus is best defined as…',
 '["Total revenue minus total cost","Difference between what consumers are willing to pay and what they actually pay","A tax paid by consumers","Profit earned by firms"]','B','Consumer surplus',null,true,
 'RU','UZ','Consumer surplus is best defined as…',
 '["Total revenue minus total cost","Difference between what consumers are willing to pay and what they actually pay","A tax paid by consumers","Profit earned by firms"]',
 '["Total revenue minus total cost","Difference between what consumers are willing to pay and what they actually pay","A tax paid by consumers","Profit earned by firms"]',
 '["Total revenue minus total cost","Difference between what consumers are willing to pay and what they actually pay","A tax paid by consumers","Profit earned by firms"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch11',60,null,'published'),

(1029,7,'Market','Producer surplus','medium','mcq','Producer surplus is best defined as…',
 '["Difference between price received and minimum price producers are willing to accept","A government subsidy","A tax on firms","Total cost of production"]','A','Producer surplus',null,true,
 'RU','UZ','Producer surplus is best defined as…',
 '["Difference between price received and minimum price producers are willing to accept","A government subsidy","A tax on firms","Total cost of production"]',
 '["Difference between price received and minimum price producers are willing to accept","A government subsidy","A tax on firms","Total cost of production"]',
 '["Difference between price received and minimum price producers are willing to accept","A government subsidy","A tax on firms","Total cost of production"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch11',60,null,'published'),

(1079,7,'Elasticity','Total revenue and elasticity','medium','mcq','If demand is inelastic (|PED|<1), a price increase will usually…',
 '["increase total revenue","decrease total revenue","leave revenue unchanged always","make supply perfectly elastic"]','A','TR and elasticity',null,true,
 'RU','UZ','If demand is inelastic (|PED|<1), a price increase will usually…',
 '["increase total revenue","decrease total revenue","leave revenue unchanged always","make supply perfectly elastic"]',
 '["increase total revenue","decrease total revenue","leave revenue unchanged always","make supply perfectly elastic"]',
 '["increase total revenue","decrease total revenue","leave revenue unchanged always","make supply perfectly elastic"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch11',60,null,'published'),

(1121,7,'Market','Tax and consumer surplus','medium','mcq','A per-unit tax usually causes consumer surplus to:',
 '["Increase","Stay the same","Decrease","Become infinite"]','C','Tax reduces CS',null,true,
 'RU','UZ','A per-unit tax usually causes consumer surplus to:',
 '["Increase","Stay the same","Decrease","Become infinite"]','["Increase","Stay the same","Decrease","Become infinite"]','["Increase","Stay the same","Decrease","Become infinite"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch11',60,null,'published'),

(1133,7,'Market','Producer surplus','medium','mcq','Producer surplus is best described as the area:',
 '["Below the supply curve and above the market price","Above the supply curve and below the market price","Above the demand curve and below the market price","Above the market price and above the supply curve"]','B','Producer surplus area',null,true,
 'RU','UZ','Producer surplus is best described as the area:',
 '["Below the supply curve and above the market price","Above the supply curve and below the market price","Above the demand curve and below the market price","Above the market price and above the supply curve"]',
 '["Below the supply curve and above the market price","Above the supply curve and below the market price","Above the demand curve and below the market price","Above the market price and above the supply curve"]',
 '["Below the supply curve and above the market price","Above the supply curve and below the market price","Above the demand curve and below the market price","Above the market price and above the supply curve"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch11',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1081,'mcq_option','A','price equals marginal cost',true,null,null,
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Market','Allocative efficiency','{}'::jsonb,'published');