\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1083,1066,1067,1073);

delete from public.questions
where id in (1083,1066,1067,1073);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1083,7,'Basics','Microeconomics and macroeconomics','medium','mcq','Microeconomics mainly studies…',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]','A',
 'Microeconomics studies individual decision-makers and markets.',null,true,
 'RU 1083','UZ 1083','Microeconomics mainly studies…',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published'),
(1066,7,'Basics','Reward to land','medium','mcq','What is the reward to land as a factor of production?',
 '["Rent","Wages","Interest","Profit"]','A','The reward to land is rent.',null,true,
 'RU 1066','UZ 1066','What is the reward to land as a factor of production?',
 '["Rent","Wages","Interest","Profit"]','["Rent","Wages","Interest","Profit"]','["Rent","Wages","Interest","Profit"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch3',60,null,'published'),
(1067,7,'Basics','Reward to capital','medium','mcq','What is the reward to capital?',
 '["Interest","Rent","Wages","Subsidy"]','A','The reward to capital is interest.',null,true,
 'RU 1067','UZ 1067','What is the reward to capital?',
 '["Interest","Rent","Wages","Subsidy"]','["Interest","Rent","Wages","Subsidy"]','["Interest","Rent","Wages","Subsidy"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch3',60,null,'published'),
(1073,7,'Supply','Productivity and supply','medium','mcq','Higher labour productivity will most likely…',
 '["increase supply","decrease demand","cause shortage","make goods inferior"]','A',
 'Higher productivity usually increases supply.',null,true,
 'RU 1073','UZ 1073','Higher labour productivity will most likely…',
 '["increase supply","decrease demand","cause shortage","make goods inferior"]',
 '["increase supply","decrease demand","cause shortage","make goods inferior"]',
 '["increase supply","decrease demand","cause shortage","make goods inferior"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch3',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1083,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Basics','Microeconomics and macroeconomics','{}'::jsonb,'published');