\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1066,1102,1109,1122,1128,1131);
delete from public.questions
where id in (1066,1102,1109,1122,1128,1131);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1066,7,'Basics','Reward to land','medium','mcq','What is the reward to land as a factor of production?',
 '["Rent","Wages","Interest","Profit"]','A','The reward to land is rent.',null,true,
 'RU 1066','UZ 1066','What is the reward to land as a factor of production?',
 '["Rent","Wages","Interest","Profit"]','["Rent","Wages","Interest","Profit"]','["Rent","Wages","Interest","Profit"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch3',60,null,'published'),
(1102,7,'Systems','Price mechanism and resource allocation','medium','mcq','In a market economy, how does the price mechanism help allocate scarce resources?',
 '["Higher prices signal scarcity and encourage producers to supply more while reducing quantity demanded","Government sets quotas for all goods","Prices do not affect choices","Only tradition determines allocation"]','A','Prices coordinate choices through signals and incentives.',null,true,
 'RU 1102','UZ 1102','In a market economy, how does the price mechanism help allocate scarce resources?',
 '["Higher prices signal scarcity and encourage producers to supply more while reducing quantity demanded","Government sets quotas for all goods","Prices do not affect choices","Only tradition determines allocation"]',
 '["Higher prices signal scarcity and encourage producers to supply more while reducing quantity demanded","Government sets quotas for all goods","Prices do not affect choices","Only tradition determines allocation"]',
 '["Higher prices signal scarcity and encourage producers to supply more while reducing quantity demanded","Government sets quotas for all goods","Prices do not affect choices","Only tradition determines allocation"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published'),
(1109,7,'Systems','Rationing methods','medium','mcq','Which statement best compares rationing by price vs rationing by queue?',
 '["Price rations by willingness/ability to pay; queues ration by time cost","Queues always create surpluses; prices always create shortages","Both methods are identical in effects","Queues eliminate opportunity cost"]','A','Price and queue rationing impose different access costs.',null,true,
 'RU 1109','UZ 1109','Which statement best compares rationing by price vs rationing by queue?',
 '["Price rations by willingness/ability to pay; queues ration by time cost","Queues always create surpluses; prices always create shortages","Both methods are identical in effects","Queues eliminate opportunity cost"]',
 '["Price rations by willingness/ability to pay; queues ration by time cost","Queues always create surpluses; prices always create shortages","Both methods are identical in effects","Queues eliminate opportunity cost"]',
 '["Price rations by willingness/ability to pay; queues ration by time cost","Queues always create surpluses; prices always create shortages","Both methods are identical in effects","Queues eliminate opportunity cost"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published'),
(1122,7,'Systems','Rationing by queue','medium','mcq','Rationing by queue mainly allocates goods based on:',
 '["Income level","Education level","Advertising","Time cost (willingness to wait)"]','D','Queue rationing uses willingness to wait and time cost.',null,true,
 'RU 1122','UZ 1122','Rationing by queue mainly allocates goods based on:',
 '["Income level","Education level","Advertising","Time cost (willingness to wait)"]',
 '["Income level","Education level","Advertising","Time cost (willingness to wait)"]',
 '["Income level","Education level","Advertising","Time cost (willingness to wait)"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published'),
(1128,7,'Systems','Price signals and shortage','medium','mcq','If a good becomes scarce, the price mechanism tends to:',
 '["Raise price, reducing quantity demanded and encouraging supply","Lower price, increasing demand","Fix price permanently","Eliminate opportunity cost"]','A','A shortage creates upward pressure on price.',null,true,
 'RU 1128','UZ 1128','If a good becomes scarce, the price mechanism tends to:',
 '["Raise price, reducing quantity demanded and encouraging supply","Lower price, increasing demand","Fix price permanently","Eliminate opportunity cost"]',
 '["Raise price, reducing quantity demanded and encouraging supply","Lower price, increasing demand","Fix price permanently","Eliminate opportunity cost"]',
 '["Raise price, reducing quantity demanded and encouraging supply","Lower price, increasing demand","Fix price permanently","Eliminate opportunity cost"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published'),
(1131,7,'Systems','Incentives in planned and market economies','medium','mcq','In a planned economy, a common incentive problem is that firms may:',
 '["Lower quality to maximize profit","Meet quotas but with low efficiency/quality","Always innovate faster","Have perfectly accurate price signals"]','B','Quota incentives may weaken efficiency and quality incentives.',null,true,
 'RU 1131','UZ 1131','In a planned economy, a common incentive problem is that firms may:',
 '["Lower quality to maximize profit","Meet quotas but with low efficiency/quality","Always innovate faster","Have perfectly accurate price signals"]',
 '["Lower quality to maximize profit","Meet quotas but with low efficiency/quality","Always innovate faster","Have perfectly accurate price signals"]',
 '["Lower quality to maximize profit","Meet quotas but with low efficiency/quality","Always innovate faster","Have perfectly accurate price signals"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch4',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1066,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Basics','Reward to land','{}'::jsonb,'published');