\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.question_answer_diagnostics add column if not exists answer_kind text;
alter table public.question_answer_diagnostics add column if not exists answer_key text;
alter table public.question_answer_diagnostics add column if not exists answer_value text;
alter table public.question_answer_diagnostics add column if not exists weak_skill text;
alter table public.question_answer_diagnostics add column if not exists feedback_ru text;
alter table public.question_answer_diagnostics add column if not exists feedback_uz text;
alter table public.question_answer_diagnostics add column if not exists feedback_en text;
alter table public.question_answer_diagnostics add column if not exists next_action_ru text;
alter table public.question_answer_diagnostics add column if not exists next_action_uz text;
alter table public.question_answer_diagnostics add column if not exists next_action_en text;
alter table public.question_answer_diagnostics add column if not exists recommended_topic text;
alter table public.question_answer_diagnostics add column if not exists recommended_subtopic text;
alter table public.question_answer_diagnostics add column if not exists recommended_lesson_id bigint;
alter table public.question_answer_diagnostics add column if not exists rule_json jsonb default '{}'::jsonb;
alter table public.question_answer_diagnostics add column if not exists created_at timestamptz default now();
alter table public.question_answer_diagnostics add column if not exists updated_at timestamptz default now();

insert into public.subjects(id,subject_key,title,type,is_active)
values(4,'chemistry','Chemistry','main',true)
on conflict(id) do update
set subject_key=excluded.subject_key,title=excluded.title,type=excluded.type,is_active=excluded.is_active;

insert into public.practice_pools(id,subject_id,tour_no,title,is_active)
values(7400,4,1,'AI4 Chemistry Atomic diagnostics fixture',true);

delete from public.question_answer_diagnostics where question_id in (1909,1914,1916,1921,1925,1929,1933,1943,1944,1954,1959,1964,3041,3043,3044);
delete from public.questions where id in (1909,1914,1916,1921,1925,1929,1933,1943,1944,1954,1959,1964,3041,3043,3044);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1909,4,'Atomic structure','Deflection in an electric field','medium','mcq','Fixture 1909','["Protons","Neutrons","Electrons","All equally"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Protons","Neutrons","Electrons","All equally"]','["Protons","Neutrons","Electrons","All equally"]','["Protons","Neutrons","Electrons","All equally"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1914,4,'Atomic structure','Formation of positive ions','medium','mcq','Fixture 1914','["Gain of an electron","Loss of an electron","Gain of a proton","Absorption of a neutron"]','B','PRIVATE',null,true,
 'RU','UZ','EN','["Gain of an electron","Loss of an electron","Gain of a proton","Absorption of a neutron"]','["Gain of an electron","Loss of an electron","Gain of a proton","Absorption of a neutron"]','["Gain of an electron","Loss of an electron","Gain of a proton","Absorption of a neutron"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1916,4,'Atomic structure','Properties of a neutral atom','medium','mcq','Fixture 1916','["Number of protons greater than electrons","Number of electrons greater than neutrons","Number of protons equals number of electrons","Number of neutrons equals number of electrons"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Number of protons greater than electrons","Number of electrons greater than neutrons","Number of protons equals number of electrons","Number of neutrons equals number of electrons"]','["Number of protons greater than electrons","Number of electrons greater than neutrons","Number of protons equals number of electrons","Number of neutrons equals number of electrons"]','["Number of protons greater than electrons","Number of electrons greater than neutrons","Number of protons equals number of electrons","Number of neutrons equals number of electrons"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1921,4,'Atomic structure','Charge of a neutron','medium','mcq','Fixture 1921','["Positive","Negative","Zero","Variable"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Positive","Negative","Zero","Variable"]','["Positive","Negative","Zero","Variable"]','["Positive","Negative","Zero","Variable"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1925,4,'Atomic structure','Periodic table position','medium','mcq','Fixture 1925','["Number of neutrons","Number of electron shells","Number of protons","Mass number"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Number of neutrons","Number of electron shells","Number of protons","Mass number"]','["Number of neutrons","Number of electron shells","Number of protons","Mass number"]','["Number of neutrons","Number of electron shells","Number of protons","Mass number"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1929,4,'Atomic structure','Particle not deflected in an electric field','medium','mcq','Fixture 1929','["Proton","Electron","Neutron","Ion"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Proton","Electron","Neutron","Ion"]','["Proton","Electron","Neutron","Ion"]','["Proton","Electron","Neutron","Ion"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1933,4,'Atomic structure','Mass number','medium','mcq','Fixture 1933','["Equal to number of protons","Equal to number of neutrons","Equal to protons plus neutrons","Equal to number of electrons"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Equal to number of protons","Equal to number of neutrons","Equal to protons plus neutrons","Equal to number of electrons"]','["Equal to number of protons","Equal to number of neutrons","Equal to protons plus neutrons","Equal to number of electrons"]','["Equal to number of protons","Equal to number of neutrons","Equal to protons plus neutrons","Equal to number of electrons"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1943,4,'Atomic structure','Relative atomic mass (Ar)','medium','mcq','Fixture 1943','["Mass of one atom in grams","Weighted mean mass compared with 1/12 of a carbon-12 atom","Sum of masses of protons and electrons","Number of protons in the nucleus"]','B','PRIVATE',null,true,
 'RU','UZ','EN','["Mass of one atom in grams","Weighted mean mass compared with 1/12 of a carbon-12 atom","Sum of masses of protons and electrons","Number of protons in the nucleus"]','["Mass of one atom in grams","Weighted mean mass compared with 1/12 of a carbon-12 atom","Sum of masses of protons and electrons","Number of protons in the nucleus"]','["Mass of one atom in grams","Weighted mean mass compared with 1/12 of a carbon-12 atom","Sum of masses of protons and electrons","Number of protons in the nucleus"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1944,4,'Atomic structure','Electrons in Cl⁻','medium','input','Fixture 1944','[]','18','PRIVATE',null,true,
 'RU','UZ','EN','[]','[]','[]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1954,4,'Atomic structure','Neutrons in copper isotope','medium','input','Fixture 1954','[]','34','PRIVATE',null,true,
 'RU','UZ','EN','[]','[]','[]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1959,4,'Atomic structure','Smallest relative mass of subatomic particles','medium','mcq','Fixture 1959','["Proton","Neutron","Electron","Ion"]','C','PRIVATE',null,true,
 'RU','UZ','EN','["Proton","Neutron","Electron","Ion"]','["Proton","Neutron","Electron","Ion"]','["Proton","Neutron","Electron","Ion"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(1964,4,'Atomic structure','Electrons in Fe³⁺','medium','input','Fixture 1964','[]','23','PRIVATE',null,true,
 'RU','UZ','EN','[]','[]','[]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(3041,4,'Atomic structure','Rutherford scattering and the nucleus','medium','mcq','Fixture 3041','["Because the atom is completely filled with electrons","Because the positive charge and almost all the mass are concentrated in a very small nucleus","Because neutrons strongly repel alpha particles","Because electrons are heavier than alpha particles"]','B','PRIVATE',null,true,
 'RU','UZ','EN','["Because the atom is completely filled with electrons","Because the positive charge and almost all the mass are concentrated in a very small nucleus","Because neutrons strongly repel alpha particles","Because electrons are heavier than alpha particles"]','["Because the atom is completely filled with electrons","Because the positive charge and almost all the mass are concentrated in a very small nucleus","Because neutrons strongly repel alpha particles","Because electrons are heavier than alpha particles"]','["Because the atom is completely filled with electrons","Because the positive charge and almost all the mass are concentrated in a very small nucleus","Because neutrons strongly repel alpha particles","Because electrons are heavier than alpha particles"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(3043,4,'Atomic structure','Electron count in aluminium ion','medium','input','Fixture 3043','[]','10','PRIVATE',null,true,
 'RU','UZ','EN','[]','[]','[]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published'),
(3044,4,'Atomic structure','Mass and charge in the nucleus','medium','mcq','Fixture 3044','["The nucleus contains almost all of the mass of the atom and has a positive charge","The nucleus contains only electrons and has no charge","The nucleus occupies almost all of the volume of the atom","The nucleus contains only neutrons"]','A','PRIVATE',null,true,
 'RU','UZ','EN','["The nucleus contains almost all of the mass of the atom and has a positive charge","The nucleus contains only electrons and has no charge","The nucleus occupies almost all of the volume of the atom","The nucleus contains only neutrons"]','["The nucleus contains almost all of the mass of the atom and has a positive charge","The nucleus contains only electrons and has no charge","The nucleus occupies almost all of the volume of the atom","The nucleus contains only neutrons"]','["The nucleus contains almost all of the mass of the atom and has a positive charge","The nucleus contains only electrons and has no charge","The nucleus occupies almost all of the volume of the atom","The nucleus contains only neutrons"]','RU','UZ','EN','AI4 Chemistry Atomic diagnostics',60,null,'published');

insert into public.practice_pool_questions(pool_id,question_id,order_no,is_active)
values
(7400,1909,1,true),
(7400,1914,2,true),
(7400,1916,3,true),
(7400,1921,4,true),
(7400,1925,5,true),
(7400,1929,6,true),
(7400,1933,7,true),
(7400,1943,8,true),
(7400,1944,9,true),
(7400,1954,10,true),
(7400,1959,11,true),
(7400,1964,12,true),
(7400,3041,13,true),
(7400,3043,14,true),
(7400,3044,15,true);
