\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1023,1087,1095,1103,1104,1113,1119,1120,1132);

delete from public.questions
where id in (1023,1087,1095,1103,1104,1113,1119,1120,1132);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1023,7,'Elasticity','Income elasticity and inferior goods','medium','mcq','Sentinel',
 '["A","B","C","D"]','A','Sentinel',null,true,'RU','UZ','Sentinel',
 '["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]','RU','UZ','EN','Economics Book | Ch8',60,null,'published'),

(1087,7,'Elasticity','Price elasticity of supply','medium','mcq','Supply is more price elastic when…',
 '["firms can adjust output quickly","inputs are fixed forever","there is no spare capacity","time period is very short"]','A','PES determinants',null,true,
 'RU','UZ','Supply is more price elastic when…',
 '["firms can adjust output quickly","inputs are fixed forever","there is no spare capacity","time period is very short"]',
 '["firms can adjust output quickly","inputs are fixed forever","there is no spare capacity","time period is very short"]',
 '["firms can adjust output quickly","inputs are fixed forever","there is no spare capacity","time period is very short"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1095,7,'Elasticity','Calculating PES','medium','input',
 'Quantity supplied rises by 20% when price rises by 10%. What is PES? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'2','PES = 20/10 = 2.',null,true,
 'RU','UZ','Quantity supplied rises by 20% when price rises by 10%. What is PES? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1103,7,'Elasticity','Interpreting PES numerically','medium','input',
 'Price rises by 20% and quantity supplied rises by 60%. Calculate PES. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'3','PES = 60/20 = 3.',null,true,
 'RU','UZ','Price rises by 20% and quantity supplied rises by 60%. Calculate PES. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1104,7,'Elasticity','Determinants of PES','medium','mcq','Which factor tends to make supply more elastic (higher PES)?',
 '["Spare capacity and ability to store goods","Very long production time and fixed capacity","Perishable goods with no storage","No availability of extra inputs"]','A','PES determinants',null,true,
 'RU','UZ','Which factor tends to make supply more elastic (higher PES)?',
 '["Spare capacity and ability to store goods","Very long production time and fixed capacity","Perishable goods with no storage","No availability of extra inputs"]',
 '["Spare capacity and ability to store goods","Very long production time and fixed capacity","Perishable goods with no storage","No availability of extra inputs"]',
 '["Spare capacity and ability to store goods","Very long production time and fixed capacity","Perishable goods with no storage","No availability of extra inputs"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1113,7,'Elasticity','PES: short run and long run','medium','mcq','Why is price elasticity of supply (PES) usually higher in the long run than in the short run?',
 '["Firms have more time to change capacity and adjust inputs","Demand becomes perfectly elastic","Prices are fixed in the long run","Opportunity cost disappears"]','A','Long run PES',null,true,
 'RU','UZ','Why is price elasticity of supply (PES) usually higher in the long run than in the short run?',
 '["Firms have more time to change capacity and adjust inputs","Demand becomes perfectly elastic","Prices are fixed in the long run","Opportunity cost disappears"]',
 '["Firms have more time to change capacity and adjust inputs","Demand becomes perfectly elastic","Prices are fixed in the long run","Opportunity cost disappears"]',
 '["Firms have more time to change capacity and adjust inputs","Demand becomes perfectly elastic","Prices are fixed in the long run","Opportunity cost disappears"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1119,7,'Elasticity','Time and PES','medium','mcq','PES is higher when firms:',
 '["Have no spare capacity","Cannot hire extra workers","Can increase capacity and adjust inputs quickly","Face perfectly inelastic demand"]','C','PES flexibility',null,true,
 'RU','UZ','PES is higher when firms:',
 '["Have no spare capacity","Cannot hire extra workers","Can increase capacity and adjust inputs quickly","Face perfectly inelastic demand"]',
 '["Have no spare capacity","Cannot hire extra workers","Can increase capacity and adjust inputs quickly","Face perfectly inelastic demand"]',
 '["Have no spare capacity","Cannot hire extra workers","Can increase capacity and adjust inputs quickly","Face perfectly inelastic demand"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1120,7,'Elasticity','Calculating PES (input)','medium','input',
 'Price rises by 10% and quantity supplied rises by 20%. Calculate PES. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'2','PES = 20/10 = 2.',null,true,
 'RU','UZ','Price rises by 10% and quantity supplied rises by 20%. Calculate PES. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published'),

(1132,7,'Elasticity','PES in the long run','medium','mcq','Why is the supply of new housing usually more elastic in the long run?',
 '["Because demand becomes inelastic","Because firms can increase land supply instantly","Because construction capacity, planning and entry can adjust over time","Because prices stop changing"]','C','Long-run housing supply',null,true,
 'RU','UZ','Why is the supply of new housing usually more elastic in the long run?',
 '["Because demand becomes inelastic","Because firms can increase land supply instantly","Because construction capacity, planning and entry can adjust over time","Because prices stop changing"]',
 '["Because demand becomes inelastic","Because firms can increase land supply instantly","Because construction capacity, planning and entry can adjust over time","Because prices stop changing"]',
 '["Because demand becomes inelastic","Because firms can increase land supply instantly","Because construction capacity, planning and entry can adjust over time","Because prices stop changing"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch9',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1023,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Elasticity','Income elasticity and inferior goods','{}'::jsonb,'published');