\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1087,1032,1074,1075,1076,1086,1088,1096,1097,1117);

delete from public.questions
where id in (1087,1032,1074,1075,1076,1086,1088,1096,1097,1117);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1087,7,'Elasticity','Price elasticity of supply','medium','mcq','Sentinel',
 '["A","B","C","D"]','A','Sentinel',null,true,'RU','UZ','Sentinel',
 '["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]','RU','UZ','EN','Economics Book | Ch9',60,null,'published'),

(1032,7,'Equilibrium','Equilibrium price from linear demand and supply','medium','input',
 'Qd = 80 − 2P and Qs = 20 + 4P. Find the equilibrium price P. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'10','P=10',null,true,'RU','UZ',
 'Qd = 80 − 2P and Qs = 20 + 4P. Find the equilibrium price P. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1074,7,'Equilibrium','Surplus','medium','mcq','A surplus occurs when…',
 '["quantity supplied exceeds quantity demanded","quantity demanded exceeds quantity supplied","price equals zero","demand curve shifts right"]','A','Surplus definition',null,true,
 'RU','UZ','A surplus occurs when…',
 '["quantity supplied exceeds quantity demanded","quantity demanded exceeds quantity supplied","price equals zero","demand curve shifts right"]',
 '["quantity supplied exceeds quantity demanded","quantity demanded exceeds quantity supplied","price equals zero","demand curve shifts right"]',
 '["quantity supplied exceeds quantity demanded","quantity demanded exceeds quantity supplied","price equals zero","demand curve shifts right"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch10',60,null,'published'),

(1075,7,'Equilibrium','Shortage','medium','mcq','A shortage occurs when…',
 '["quantity demanded exceeds quantity supplied","quantity supplied exceeds quantity demanded","costs fall","supply shifts right"]','A','Shortage definition',null,true,
 'RU','UZ','A shortage occurs when…',
 '["quantity demanded exceeds quantity supplied","quantity supplied exceeds quantity demanded","costs fall","supply shifts right"]',
 '["quantity demanded exceeds quantity supplied","quantity supplied exceeds quantity demanded","costs fall","supply shifts right"]',
 '["quantity demanded exceeds quantity supplied","quantity supplied exceeds quantity demanded","costs fall","supply shifts right"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1076,7,'Equilibrium','Equilibrium price from linear demand and supply','medium','input',
 'Qd = 80 − 2P and Qs = 20 + 2P. Find the equilibrium price P. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'15','P=15',null,true,'RU','UZ',
 'Qd = 80 − 2P and Qs = 20 + 2P. Find the equilibrium price P. Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1086,7,'Supply','Subsidy and supply','medium','mcq','A subsidy to producers will most likely…',
 '["shift supply right","shift supply left","shift demand right","cause shortage"]','A','Subsidy supply',null,true,
 'RU','UZ','A subsidy to producers will most likely…',
 '["shift supply right","shift supply left","shift demand right","cause shortage"]',
 '["shift supply right","shift supply left","shift demand right","cause shortage"]',
 '["shift supply right","shift supply left","shift demand right","cause shortage"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1088,7,'Equilibrium','Market equilibrium','medium','mcq','At equilibrium price, the market is said to…',
 '["clear (no persistent surplus/shortage)","always have shortage","always have surplus","stop trading"]','A','Market clears',null,true,
 'RU','UZ','At equilibrium price, the market is said to…',
 '["clear (no persistent surplus/shortage)","always have shortage","always have surplus","stop trading"]',
 '["clear (no persistent surplus/shortage)","always have shortage","always have surplus","stop trading"]',
 '["clear (no persistent surplus/shortage)","always have shortage","always have surplus","stop trading"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1096,7,'Equilibrium','Price above equilibrium','medium','mcq','If market price is above equilibrium, the likely result is…',
 '["surplus","shortage","no effect","higher demand"]','A','Above equilibrium',null,true,
 'RU','UZ','If market price is above equilibrium, the likely result is…',
 '["surplus","shortage","no effect","higher demand"]','["surplus","shortage","no effect","higher demand"]','["surplus","shortage","no effect","higher demand"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1097,7,'Equilibrium','Price below equilibrium','medium','mcq','If market price is below equilibrium, the likely result is…',
 '["shortage","surplus","no effect","lower supply curve"]','A','Below equilibrium',null,true,
 'RU','UZ','If market price is below equilibrium, the likely result is…',
 '["shortage","surplus","no effect","lower supply curve"]','["shortage","surplus","no effect","lower supply curve"]','["shortage","surplus","no effect","lower supply curve"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published'),

(1117,7,'Equilibrium','Price ceiling and shortage','medium','mcq','When a binding price ceiling creates a shortage, which method is most likely to allocate the good?',
 '["Queuing / waiting in line","A higher official equilibrium price","Automatic market clearing","Perfectly elastic supply"]','A','Queue rationing',null,true,
 'RU','UZ','When a binding price ceiling creates a shortage, which method is most likely to allocate the good?',
 '["Queuing / waiting in line","A higher official equilibrium price","Automatic market clearing","Perfectly elastic supply"]',
 '["Queuing / waiting in line","A higher official equilibrium price","Automatic market clearing","Perfectly elastic supply"]',
 '["Queuing / waiting in line","A higher official equilibrium price","Automatic market clearing","Perfectly elastic supply"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch10',60,null,'published');

insert into public.question_answer_diagnostics(
 question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
 feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
 recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1087,'mcq_option','A','existing sentinel',true,null,null,
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Elasticity','Price elasticity of supply','{}'::jsonb,'published');