\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1020,1023,1024,1077,1080,1094,1127,1134);

delete from public.questions
where id in (1020,1023,1024,1077,1080,1094,1127,1134);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1020,7,'Demand','Movement along the demand curve','medium','mcq','Sentinel',
 '["A","B","C","D"]','A','Sentinel',null,true,'RU','UZ','Sentinel',
 '["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch7',60,null,'published'),

(1023,7,'Elasticity','Income elasticity and inferior goods','medium','mcq','If income rises and demand for a good falls, the good is most likely…',
 '["Normal","Inferior","A luxury","A substitute"]','B','Income elasticity',null,true,
 'RU','UZ','If income rises and demand for a good falls, the good is most likely…',
 '["Normal","Inferior","A luxury","A substitute"]','["Normal","Inferior","A luxury","A substitute"]','["Normal","Inferior","A luxury","A substitute"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch8',60,null,'published'),

(1024,7,'Elasticity','Cross elasticity and substitutes','medium','mcq','If the price of A rises and demand for B rises, A and B are most likely…',
 '["Complements","Substitutes","Unrelated","Inferior goods"]','B','Cross elasticity',null,true,
 'RU','UZ','If the price of A rises and demand for B rises, A and B are most likely…',
 '["Complements","Substitutes","Unrelated","Inferior goods"]','["Complements","Substitutes","Unrelated","Inferior goods"]','["Complements","Substitutes","Unrelated","Inferior goods"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published'),

(1077,7,'Elasticity','Perfectly inelastic demand','medium','mcq','Perfectly inelastic demand means…',
 '["quantity demanded does not change when price changes","demand shifts with price","quantity changes a lot","price always falls"]','A','Perfectly inelastic demand',null,true,
 'RU','UZ','Perfectly inelastic demand means…',
 '["quantity demanded does not change when price changes","demand shifts with price","quantity changes a lot","price always falls"]',
 '["quantity demanded does not change when price changes","demand shifts with price","quantity changes a lot","price always falls"]',
 '["quantity demanded does not change when price changes","demand shifts with price","quantity changes a lot","price always falls"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published'),

(1080,7,'Costs','Fixed cost','medium','mcq','Which is most likely a fixed cost in the short run?',
 '["factory rent","raw materials","piece-rate wages","electricity per unit"]','A','Fixed cost',null,true,
 'RU','UZ','Which is most likely a fixed cost in the short run?',
 '["factory rent","raw materials","piece-rate wages","electricity per unit"]',
 '["factory rent","raw materials","piece-rate wages","electricity per unit"]',
 '["factory rent","raw materials","piece-rate wages","electricity per unit"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published'),

(1094,7,'Elasticity','Calculating PED','medium','input',
 'Quantity demanded falls by 6% when price rises by 3%. What is |PED|? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,'2','PED = 6/3 = 2.',null,true,
 'RU','UZ','Quantity demanded falls by 6% when price rises by 3%. What is |PED|? Write only the number using ordinary digits. Do not add words, units or signs.',
 null,null,null,'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published'),

(1127,7,'Elasticity','PED and total revenue','medium','mcq','If demand is elastic (PED > 1) and price falls, total revenue will usually:',
 '["Fall","Rise","Stay the same","Become zero"]','B','Elastic demand and revenue',null,true,
 'RU','UZ','If demand is elastic (PED > 1) and price falls, total revenue will usually:',
 '["Fall","Rise","Stay the same","Become zero"]','["Fall","Rise","Stay the same","Become zero"]','["Fall","Rise","Stay the same","Become zero"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published'),

(1134,7,'Elasticity','Cross elasticity and substitutes','medium','mcq','If the cross elasticity of demand (XED) between tea and coffee is positive, tea and coffee are:',
 '["Complements","Unrelated goods","Inferior goods","Substitutes"]','D','Positive XED means substitutes.',null,true,
 'RU','UZ','If the cross elasticity of demand (XED) between tea and coffee is positive, tea and coffee are:',
 '["Complements","Unrelated goods","Inferior goods","Substitutes"]',
 '["Complements","Unrelated goods","Inferior goods","Substitutes"]',
 '["Complements","Unrelated goods","Inferior goods","Substitutes"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch8',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1020,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'Demand','Movement along the demand curve','{}'::jsonb,'published');