\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics where question_id in (1090,1100,1111,1123,1124);
delete from public.questions where id in (1090,1100,1111,1123,1124);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1090,7,'PPC','Outward shift of the PPC','medium','mcq','Sentinel',
 '["A","B","C","D"]','A','Sentinel',null,true,'RU','UZ','Sentinel',
 '["A","B","C","D"]','["A","B","C","D"]','["A","B","C","D"]','RU','UZ','EN','Economics Book | Tour 1 | Ch5',60,null,'published'),
(1100,7,'Goods','Merit goods and education','medium','mcq','Which option is the best justification for why education is often treated as a MERIT good?',
 '["It creates positive external benefits and may be under-consumed without intervention","It is non-excludable and non-rival","It always causes negative externalities","It has zero opportunity cost"]','A','Merit goods can create positive external benefits.',null,true,
 'RU','UZ','Which option is the best justification for why education is often treated as a MERIT good?',
 '["It creates positive external benefits and may be under-consumed without intervention","It is non-excludable and non-rival","It always causes negative externalities","It has zero opportunity cost"]',
 '["It creates positive external benefits and may be under-consumed without intervention","It is non-excludable and non-rival","It always causes negative externalities","It has zero opportunity cost"]',
 '["It creates positive external benefits and may be under-consumed without intervention","It is non-excludable and non-rival","It always causes negative externalities","It has zero opportunity cost"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch6',60,null,'published'),
(1111,7,'Goods','Free-rider problem','medium','mcq','A public park is open to everyone and some people do not contribute to its maintenance. This situation illustrates:',
 '["The free-rider problem","Perfect competition","Negative income elasticity","A shift along demand"]','A','This illustrates free-riding.',null,true,
 'RU','UZ','A public park is open to everyone and some people do not contribute to its maintenance. This situation illustrates:',
 '["The free-rider problem","Perfect competition","Negative income elasticity","A shift along demand"]',
 '["The free-rider problem","Perfect competition","Negative income elasticity","A shift along demand"]',
 '["The free-rider problem","Perfect competition","Negative income elasticity","A shift along demand"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch6',60,null,'published'),
(1123,7,'Goods','Features of pure public goods','medium','mcq','A pure public good is typically:',
 '["Rival and excludable","Non-rival and non-excludable","Rival and non-excludable","Non-rival and excludable"]','B','Pure public goods are non-rival and non-excludable.',null,true,
 'RU','UZ','A pure public good is typically:',
 '["Rival and excludable","Non-rival and non-excludable","Rival and non-excludable","Non-rival and excludable"]',
 '["Rival and excludable","Non-rival and non-excludable","Rival and non-excludable","Non-rival and excludable"]',
 '["Rival and excludable","Non-rival and non-excludable","Rival and non-excludable","Non-rival and excludable"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch6',60,null,'published'),
(1124,7,'Goods','Demerit goods','medium','mcq','Which is the best example of a DEMERIT good?',
 '["Cigarettes","Street lighting","A private car","A textbook"]','A','Cigarettes are a standard demerit-good example.',null,true,
 'RU','UZ','Which is the best example of a DEMERIT good?',
 '["Cigarettes","Street lighting","A private car","A textbook"]',
 '["Cigarettes","Street lighting","A private car","A textbook"]',
 '["Cigarettes","Street lighting","A private car","A textbook"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch6',60,null,'published');

insert into public.question_answer_diagnostics(
 question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
 feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
 recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1090,'mcq_option','B','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'PPC','Outward shift of the PPC','{}'::jsonb,'published');