\set ON_ERROR_STOP on

create table if not exists public.question_answer_diagnostics (
  id bigint generated by default as identity primary key,
  question_id bigint not null,
  answer_kind text not null,
  answer_key text,
  answer_value text,
  is_correct boolean not null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

delete from public.question_answer_diagnostics
where question_id in (1013,1083,1112,1118,1126,1129,1130);

delete from public.questions
where id in (1013,1083,1112,1118,1126,1129,1130);

insert into public.questions(
  id,subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,
  explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,
  explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
) values
(1013,7,'PPC','Opportunity cost','medium','mcq','Opportunity cost is best defined as…',
 '["Money spent on a product","The next best alternative foregone","Total cost of production","A tax paid to the government"]','B',
 'Opportunity cost is the value of the next best alternative that is given up.',null,true,
 'RU 1013','UZ 1013','Opportunity cost is best defined as…',
 '["Money spent on a product","The next best alternative foregone","Total cost of production","A tax paid to the government"]',
 '["Money spent on a product","The next best alternative foregone","Total cost of production","A tax paid to the government"]',
 '["Money spent on a product","The next best alternative foregone","Total cost of production","A tax paid to the government"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch1',60,null,'published'),
(1083,7,'Basics','Microeconomics and macroeconomics','medium','mcq','Microeconomics mainly studies…',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]','A',
 'Microeconomics studies individual decision-makers and markets.',null,true,
 'RU 1083','UZ 1083','Microeconomics mainly studies…',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 '["individual markets and decision-makers","the whole economy’s GDP only","only inflation","only government budgets"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published'),
(1112,7,'Intro','Correlation and causation','medium','mcq','A study finds that cities with more gyms have lower obesity. Which statement is most accurate?',
 '["This is correlation; it does not prove gyms cause lower obesity","Gyms definitely cause lower obesity","Obesity causes more gyms","There is no relationship at all"]','A',
 'Correlation alone does not prove causation.',null,true,
 'RU 1112','UZ 1112','A study finds that cities with more gyms have lower obesity. Which statement is most accurate?',
 '["This is correlation; it does not prove gyms cause lower obesity","Gyms definitely cause lower obesity","Obesity causes more gyms","There is no relationship at all"]',
 '["This is correlation; it does not prove gyms cause lower obesity","Gyms definitely cause lower obesity","Obesity causes more gyms","There is no relationship at all"]',
 '["This is correlation; it does not prove gyms cause lower obesity","Gyms definitely cause lower obesity","Obesity causes more gyms","There is no relationship at all"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published'),
(1118,7,'Intro','Meaning of ceteris paribus','medium','mcq','When economists say “ceteris paribus”, they mean:',
 '["Other relevant factors are held constant","Prices always fall","Demand never changes","Supply becomes zero"]','A',
 'Ceteris paribus means other relevant factors are held constant.',null,true,
 'RU 1118','UZ 1118','When economists say “ceteris paribus”, they mean:',
 '["Other relevant factors are held constant","Prices always fall","Demand never changes","Supply becomes zero"]',
 '["Other relevant factors are held constant","Prices always fall","Demand never changes","Supply becomes zero"]',
 '["Other relevant factors are held constant","Prices always fall","Demand never changes","Supply becomes zero"]',
 'RU','UZ','EN','Economics Book | Tour 1 | Ch2',60,null,'published'),
(1126,7,'Intro','Limits of economic models','medium','mcq','A limitation of an economic model is that it:',
 '["Always predicts perfectly","Must include every detail of reality","May omit important real-world factors","Cannot be tested"]','C',
 'Models simplify reality and may omit important factors.',null,true,
 'RU 1126','UZ 1126','A limitation of an economic model is that it:',
 '["Always predicts perfectly","Must include every detail of reality","May omit important real-world factors","Cannot be tested"]',
 '["Always predicts perfectly","Must include every detail of reality","May omit important real-world factors","Cannot be tested"]',
 '["Always predicts perfectly","Must include every detail of reality","May omit important real-world factors","Cannot be tested"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published'),
(1129,7,'Intro','Positive statements','medium','mcq','Which statement is POSITIVE (testable)?',
 '["The government should raise taxes","A rise in price reduces quantity demanded, ceteris paribus","It is unfair that some people are poor","The best policy is free education"]','B',
 'Positive statements are testable against evidence.',null,true,
 'RU 1129','UZ 1129','Which statement is POSITIVE (testable)?',
 '["The government should raise taxes","A rise in price reduces quantity demanded, ceteris paribus","It is unfair that some people are poor","The best policy is free education"]',
 '["The government should raise taxes","A rise in price reduces quantity demanded, ceteris paribus","It is unfair that some people are poor","The best policy is free education"]',
 '["The government should raise taxes","A rise in price reduces quantity demanded, ceteris paribus","It is unfair that some people are poor","The best policy is free education"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published'),
(1130,7,'Intro','Correlation and causation','medium','mcq','Ice cream sales and drowning incidents rise in summer. The best conclusion is:',
 '["There is correlation, but a third factor (hot weather) may cause both","Ice cream causes drowning","Drowning causes ice cream sales","There is no relationship at all"]','A',
 'A third factor can explain a correlation without direct causation.',null,true,
 'RU 1130','UZ 1130','Ice cream sales and drowning incidents rise in summer. The best conclusion is:',
 '["There is correlation, but a third factor (hot weather) may cause both","Ice cream causes drowning","Drowning causes ice cream sales","There is no relationship at all"]',
 '["There is correlation, but a third factor (hot weather) may cause both","Ice cream causes drowning","Drowning causes ice cream sales","There is no relationship at all"]',
 '["There is correlation, but a third factor (hot weather) may cause both","Ice cream causes drowning","Drowning causes ice cream sales","There is no relationship at all"]',
 'RU','UZ','EN','Economics Book | Practice 1 | Ch2',60,null,'published');

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1013,'mcq_option','A','existing sentinel',false,'existing_sentinel','existing_sentinel',
 'existing sentinel ru','existing sentinel uz','existing sentinel en',
 'existing sentinel ru action','existing sentinel uz action','existing sentinel en action',
 'PPC','Opportunity cost','{}'::jsonb,'published');