-- Disposable PostgreSQL fixture for Mathematics Practice v2 release rehearsal.
-- Synthetic only. Never run against production.

create schema if not exists private;

do $roles$
begin
  if not exists(select 1 from pg_roles where rolname='anon') then create role anon noinherit; end if;
  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated noinherit; end if;
  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role noinherit; end if;
end;
$roles$;

create table public.subjects(
  id bigint primary key,
  subject_key text not null unique,
  is_active boolean not null default true
);

create table public.questions(
  id bigint primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  is_active boolean not null default true,
  quality_status text not null default 'published'
);

create table public.practice_pools(
  id bigint primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  tour_no integer not null,
  is_active boolean not null default true
);

create table public.practice_pool_questions(
  id bigint generated by default as identity primary key,
  pool_id bigint not null references public.practice_pools(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  order_no integer not null,
  is_active boolean not null default true
);

create table public.practice_attempts(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  is_lab boolean not null default false
);

create table public.practice_answers(
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.practice_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  is_correct boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.practice_sessions_v4(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  status text not null default 'active'
);

create table public.practice_drill_sessions_v4(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  status text not null default 'active'
);

create table public.practice_review_events_v1(
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.practice_attempts(id) on delete cascade
);

create table public.user_answer_diagnosis(
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  practice_answer_id bigint references public.practice_answers(id) on delete cascade,
  tour_answer_id bigint,
  question_id bigint references public.questions(id) on delete restrict,
  attempt_type text
);

create table public.question_answer_diagnostics(
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  quality_status text not null default 'draft'
);

create table public.tours(
  id bigint primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  season_id bigint,
  tour_no integer,
  start_date timestamptz,
  end_date timestamptz,
  is_active boolean not null default true
);

create table public.tour_questions(
  id bigint generated by default as identity primary key,
  tour_id bigint not null references public.tours(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  order_no integer not null,
  is_active boolean not null default true
);

create table public.tour_attempts(
  id bigint generated by default as identity primary key,
  user_id uuid,
  tour_id bigint not null references public.tours(id) on delete cascade,
  score numeric,
  percent numeric,
  total_time integer,
  status text,
  created_at timestamptz not null default now()
);

create table public.tour_answers(
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.tour_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  answered boolean not null default true,
  is_correct boolean not null default false,
  time_spent integer not null default 0,
  finish_reason text,
  created_at timestamptz not null default now()
);

create table public.tour_session_answers_v4(
  attempt_id bigint not null references public.tour_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  answered boolean not null default true,
  is_correct boolean not null default false,
  time_spent integer not null default 0,
  finish_reason text,
  answered_at timestamptz not null default now(),
  primary key(attempt_id,question_id)
);

create table public.recommendations(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  source_type text not null,
  season_id bigint,
  tour_no integer,
  topic text,
  subtopic text,
  book_id bigint,
  book_reference text,
  created_at timestamptz not null default now()
);

create table public.learning_roadmaps(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  source_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.certificates(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  certificate_key text,
  created_at timestamptz not null default now()
);

create table public.ratings_cache(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint,
  score numeric
);

create table public.question_version_links(
  id bigint generated by default as identity primary key,
  old_question_id bigint references public.questions(id) on delete restrict,
  new_question_id bigint references public.questions(id) on delete restrict
);

create table private.exam_prep_legacy_evidence_references(
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete restrict,
  legacy_source text not null,
  legacy_attempt_id bigint not null
);

create table private.exam_prep_question_skill_map(
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete restrict
);

create table private.exam_prep_assessment_items(
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete restrict
);

create table private.exam_prep_session_items(
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete restrict
);

create table private.exam_prep_question_content_meta(
  id bigint generated by default as identity primary key,
  question_id bigint references public.questions(id) on delete restrict
);

-- RPC stubs reproduce only the privilege/signature boundary used by the release switch.
create or replace function public.submit_practice_attempt(bigint,integer,numeric,integer,jsonb)
returns jsonb language sql as $$ select '{}'::jsonb $$;
create or replace function public.submit_practice_answer_safe(bigint,bigint,text,integer,integer)
returns jsonb language sql as $$ select '{}'::jsonb $$;

revoke all on function public.submit_practice_attempt(bigint,integer,numeric,integer,jsonb) from public,anon,authenticated;
revoke all on function public.submit_practice_answer_safe(bigint,bigint,text,integer,integer) from public,anon,authenticated;

create or replace function public.start_practice_session_auto_safe_v4(bigint,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_practice_session_resume_safe_v4(bigint) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.finalize_practice_session_safe_v4(bigint,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.start_practice_topic_drill_safe_v4(text,text,text,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_practice_drill_resume_safe_v4(bigint) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.submit_practice_drill_answer_safe_v4(bigint,bigint,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_recent_practice_mistakes_safe_v4(text,text,text,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.start_practice_mistakes_drill_safe_v4(text,bigint[],text) returns jsonb language sql as $$select '{}'::jsonb$$;

create or replace function public.start_practice_session_auto_safe_v5(bigint,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.start_practice_topic_drill_safe_v5(text,text,text,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_recent_practice_mistakes_safe_v5(text,text,text,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.start_practice_mistakes_drill_safe_v5(text,bigint[],text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.submit_practice_session_answer_safe_v5(bigint,bigint,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.submit_practice_drill_answer_safe_v5(bigint,bigint,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.finalize_practice_session_safe_v5(bigint,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_practice_review_full_safe_v5(bigint) returns jsonb language sql as $$select '{}'::jsonb$$;

do $privileges$
declare
  sig text;
begin
  foreach sig in array array[
    'public.start_practice_session_auto_safe_v4(bigint,text)',
    'public.get_practice_session_resume_safe_v4(bigint)',
    'public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer)',
    'public.finalize_practice_session_safe_v4(bigint,integer)',
    'public.start_practice_topic_drill_safe_v4(text,text,text,text)',
    'public.get_practice_drill_resume_safe_v4(bigint)',
    'public.submit_practice_drill_answer_safe_v4(bigint,bigint,text,integer,integer)',
    'public.get_recent_practice_mistakes_safe_v4(text,text,text,integer)',
    'public.start_practice_mistakes_drill_safe_v4(text,bigint[],text)',
    'public.start_practice_session_auto_safe_v5(bigint,text)',
    'public.start_practice_topic_drill_safe_v5(text,text,text,text)',
    'public.get_recent_practice_mistakes_safe_v5(text,text,text,integer)',
    'public.start_practice_mistakes_drill_safe_v5(text,bigint[],text)',
    'public.submit_practice_session_answer_safe_v5(bigint,bigint,text,integer,integer)',
    'public.submit_practice_drill_answer_safe_v5(bigint,bigint,text,integer,integer)',
    'public.finalize_practice_session_safe_v5(bigint,integer)',
    'public.get_practice_review_full_safe_v5(bigint)'
  ] loop
    execute format('revoke all on function %s from public,anon,authenticated',sig);
    execute format('grant execute on function %s to authenticated',sig);
  end loop;
end;
$privileges$;
