-- Disposable PostgreSQL fixture for Mathematics Practice v2 runtime rehearsal.
-- Synthetic only. Never run against production.

\set ON_ERROR_STOP on

create schema if not exists private;
create schema if not exists auth;

do $roles$
begin
  if not exists(select 1 from pg_roles where rolname='anon') then create role anon noinherit; end if;
  if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated noinherit; end if;
  if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role noinherit; end if;
end;
$roles$;

create or replace function auth.uid()
returns uuid
language sql
stable
as $$
  select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid;
$$;

grant usage on schema public,auth to anon,authenticated,service_role;
grant execute on function auth.uid() to anon,authenticated,service_role;

create table public.subjects(
  id bigint primary key,
  subject_key text not null unique,
  title text,
  type text,
  is_active boolean not null default true
);

create table public.seasons(
  id bigint primary key,
  season_no integer not null unique,
  status text,
  title text
);

create table public.questions(
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  topic text,
  subtopic text,
  difficulty text,
  qtype text,
  question_text text,
  options_text text,
  correct_answer text,
  explanation text,
  image_url text,
  is_active boolean not null default true,
  question_text_ru text,
  question_text_uz text,
  question_text_en text,
  options_text_ru text,
  options_text_uz text,
  options_text_en text,
  explanation_ru text,
  explanation_uz text,
  explanation_en text,
  book_ref text,
  time_limit_sec integer,
  quality_flag text,
  quality_status text not null default 'published'
);

create table public.practice_pools(
  id bigint primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  tour_no integer not null,
  title text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.practice_pool_questions(
  id bigint generated by default as identity primary key,
  pool_id bigint not null references public.practice_pools(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  order_no integer,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(pool_id,question_id)
);

create table public.tours(
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  season_id bigint,
  tour_no integer,
  start_date date,
  end_date date,
  is_active boolean not null default true
);

create table public.practice_attempts(
  id bigint generated by default as identity primary key,
  user_id uuid,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  score integer,
  percent numeric,
  time_seconds integer,
  is_lab boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.practice_answers(
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.practice_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  is_correct boolean not null default false,
  time_spent integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.practice_sessions_v4(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  pool_id bigint,
  client_session_id text,
  question_ids bigint[] not null,
  legacy_attempt_id bigint,
  status text not null default 'in_progress',
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  unique(user_id,client_session_id)
);

create table public.practice_session_answers_v4(
  session_id bigint not null references public.practice_sessions_v4(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  picked_index integer,
  is_correct boolean not null,
  time_spent integer not null default 0,
  answered_at timestamptz not null default now(),
  primary key(session_id,question_id)
);

create table public.practice_drill_sessions_v4(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  client_session_id text,
  drill_type text not null,
  topic text,
  subtopic text,
  question_ids bigint[] not null,
  status text not null default 'in_progress',
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  unique(user_id,client_session_id)
);

create table public.practice_drill_answers_v4(
  session_id bigint not null references public.practice_drill_sessions_v4(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete restrict,
  user_answer text,
  picked_index integer,
  is_correct boolean not null,
  time_spent integer not null default 0,
  answered_at timestamptz not null default now(),
  primary key(session_id,question_id)
);

create table public.question_answer_diagnostics(
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer_kind text,
  answer_key text,
  answer_value text,
  is_correct boolean not null default false,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  recommended_topic text,
  recommended_subtopic text,
  recommended_lesson_id bigint,
  rule_json jsonb not null default '{}'::jsonb,
  quality_status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_answer_diagnosis(
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  subject_id bigint not null references public.subjects(id) on delete restrict,
  attempt_type text not null,
  attempt_id bigint not null,
  practice_answer_id bigint references public.practice_answers(id) on delete cascade,
  tour_answer_id bigint,
  question_id bigint not null references public.questions(id) on delete restrict,
  selected_answer text,
  is_correct boolean not null,
  diagnostic_id bigint references public.question_answer_diagnostics(id) on delete set null,
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  created_at timestamptz not null default now()
);

-- Tour-protection helper is intentionally conservative in production. The runtime
-- rehearsal only needs a deterministic unprotected fixture path.
create or replace function public.iclub_practice_drill_question_protected_v4(p_question_id bigint)
returns boolean
language sql
stable
as $$ select false; $$;

revoke all on function public.iclub_practice_drill_question_protected_v4(bigint)
from public,anon;
grant execute on function public.iclub_practice_drill_question_protected_v4(bigint)
to authenticated,service_role;

-- Legacy/direct RPCs start exposed so migration 03000 must actually close them.
create or replace function public.submit_practice_attempt(bigint,integer,numeric,integer,jsonb)
returns jsonb language sql as $$ select '{}'::jsonb $$;
create or replace function public.submit_practice_answer_safe(bigint,bigint,text,integer,integer)
returns jsonb language sql as $$ select '{}'::jsonb $$;
create or replace function public.get_practice_review_safe_v4(bigint)
returns jsonb language sql as $$ select '{}'::jsonb $$;

revoke all on function public.submit_practice_attempt(bigint,integer,numeric,integer,jsonb) from public,anon,authenticated;
revoke all on function public.submit_practice_answer_safe(bigint,bigint,text,integer,integer) from public,anon,authenticated;
revoke all on function public.get_practice_review_safe_v4(bigint) from public,anon,authenticated;

grant execute on function public.submit_practice_attempt(bigint,integer,numeric,integer,jsonb) to authenticated,service_role;
grant execute on function public.submit_practice_answer_safe(bigint,bigint,text,integer,integer) to authenticated,service_role;
grant execute on function public.get_practice_review_safe_v4(bigint) to authenticated,service_role;

-- Safe v4 compatibility entrypoints remain available while v5 is introduced.
create or replace function public.start_practice_session_auto_safe_v4(bigint,text) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_practice_session_resume_safe_v4(bigint) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.finalize_practice_session_safe_v4(bigint,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
create or replace function public.get_practice_review_full_safe_v4(bigint) returns jsonb language sql as $$select '{}'::jsonb$$;

revoke all on function public.start_practice_session_auto_safe_v4(bigint,text) from public,anon;
revoke all on function public.get_practice_session_resume_safe_v4(bigint) from public,anon;
revoke all on function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) from public,anon;
revoke all on function public.finalize_practice_session_safe_v4(bigint,integer) from public,anon;
revoke all on function public.get_practice_review_full_safe_v4(bigint) from public,anon;

grant execute on function public.start_practice_session_auto_safe_v4(bigint,text) to authenticated,service_role;
grant execute on function public.get_practice_session_resume_safe_v4(bigint) to authenticated,service_role;
grant execute on function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) to authenticated,service_role;
grant execute on function public.finalize_practice_session_safe_v4(bigint,integer) to authenticated,service_role;
grant execute on function public.get_practice_review_full_safe_v4(bigint) to authenticated,service_role;
