-- Disposable PostgreSQL integration fixture; never run against production.
create role anon nologin;
create role authenticated nologin;
create schema auth;
create schema private;
create function auth.uid() returns uuid language sql stable as $$
 select nullif(current_setting('app.test_uid',true),'')::uuid
$$;
create table public.subjects(id bigint primary key,subject_key text unique);
insert into public.subjects values(5,'mathematics'),(6,'biology');
create table private.practice_v2_release_switch_audit(
 release_version text,status text,subject_id bigint,completed_at timestamptz
);
insert into private.practice_v2_release_switch_audit values
('math_p1_practice_v2_2026_10_07','published',5,'2026-10-08 12:44:31.862792+00');
create table public.practice_sessions_v4(
 id bigint generated by default as identity primary key,user_id uuid,subject_id bigint,
 status text,created_at timestamptz default now()
);
create table public.practice_drill_sessions_v4(
 id bigint generated by default as identity primary key,user_id uuid,subject_id bigint,
 status text,created_at timestamptz default now()
);
create table public.practice_attempts(
 id bigint generated by default as identity primary key,user_id uuid,subject_id bigint,
 created_at timestamptz default now()
);
create table public.questions(id bigint primary key,topic text,subtopic text);
create table public.practice_session_answers_v4(session_id bigint,question_id bigint,is_correct boolean);
create table public.practice_drill_answers_v4(session_id bigint,question_id bigint,is_correct boolean);
create table public.recommendations(
 id bigint generated by default as identity primary key,user_id uuid,subject_id bigint,
 source_type text,topic text,subtopic text,book_id bigint,book_reference text,
 created_at timestamptz default now()
);
insert into public.questions values(100,'Algebra','Linear'),(101,'Geometry','Circles');
insert into public.practice_sessions_v4(id,user_id,subject_id,status,created_at) values
 (10,'11111111-1111-4111-8111-111111111111',5,'finalized','2026-10-07 11:00+00'),
 (11,'11111111-1111-4111-8111-111111111111',5,'finalized','2026-10-09 11:00+00'),
 (12,'11111111-1111-4111-8111-111111111111',6,'finalized','2026-10-09 11:00+00');
insert into public.practice_session_answers_v4 values(11,100,false),(11,101,true);
insert into public.recommendations(user_id,subject_id,source_type,topic,subtopic,created_at) values
 ('11111111-1111-4111-8111-111111111111',5,'practice','Algebra','Linear','2026-10-07 11:00+00'),
 ('11111111-1111-4111-8111-111111111111',5,'practice','Algebra','Linear','2026-10-09 11:00+00'),
 ('11111111-1111-4111-8111-111111111111',6,'practice','Algebra','Linear','2026-10-09 11:00+00'),
 ('11111111-1111-4111-8111-111111111111',5,'tour','Algebra','Linear','2026-10-07 11:00+00');
