-- AW13-16 P5 annual-reserve top-up draft v1.
-- DRAFT ONLY: no learner-visible content and no existing evidence mutation.
-- Exact delta per skill: +2 diagnostics, +2 delayed retests, +1 mixed/transfer.
begin;
set local lock_timeout='3s';
set local statement_timeout='90s';

do $preflight$
begin
  if not exists(select 1 from private.exam_prep_program_versions
    where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0' and status='active')
  then raise exception 'aw13_16_annual_reserve_p5_draft canonical program missing'; end if;

  if exists(select 1 from private.exam_prep_content_versions where id=4816 and content_version<>'p5_aw13_16_annual_reserve_topup_draft_v1')
     or exists(select 1 from private.exam_prep_question_content_meta where id between 59355 and 59389 and content_version_id<>4816)
  then raise exception 'aw13_16_annual_reserve_p5_draft reserved id collision'; end if;

  if (select count(*) from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id
      where cv.status='published' and m.lifecycle_state in ('published','reserve')
        and m.primary_skill_code in ('P5-PRO-05','P5-PRO-06','P5-DRV-01','P5-DRV-02','P5-DRV-03','P5-BIN-01','P5-GEO-01')
        and m.reserve_role='diagnostic')<>7
     or (select count(*) from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id
      where cv.status='published' and m.lifecycle_state in ('published','reserve')
        and m.primary_skill_code in ('P5-PRO-05','P5-PRO-06','P5-DRV-01','P5-DRV-02','P5-DRV-03','P5-BIN-01','P5-GEO-01')
        and m.reserve_role='retest')<>14
     or (select count(*) from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id
      where cv.status='published' and m.lifecycle_state in ('published','reserve')
        and m.primary_skill_code in ('P5-PRO-05','P5-PRO-06','P5-DRV-01','P5-DRV-02','P5-DRV-03','P5-BIN-01','P5-GEO-01')
        and m.reserve_role in ('learning','mixed'))<>49
  then raise exception 'aw13_16_annual_reserve_p5_draft baseline depth changed'; end if;
end
$preflight$;

insert into private.exam_prep_content_versions(
 id,program_version_id,content_version,component_code,release_label,status,source_policy,source_level
)
overriding system value
select 4816,pv.id,'p5_aw13_16_annual_reserve_topup_draft_v1','P5',
 'P5 AW13-16 annual reserve top-up draft v1','draft',
 'Original iClub-authored annual reserve expansion. Official Cambridge 9709 scope controls the learning objectives; Complete Probability & Statistics 1 is mapping/explanation support only. No protected Cambridge/coursebook question, solution, mark-scheme wording or diagram is copied. Independent academic, trilingual, technical, originality and reserve-isolation QA is required before publication.',
 3
from private.exam_prep_program_versions pv
where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0' and pv.status='active'
on conflict(program_version_id,content_version) do nothing;

with src(content_key,skill_code,reserve_role,difficulty,qtype,q_en,opts_en,answer,exp_en,q_ru,opts_ru,exp_ru,q_uz,opts_uz,exp_uz,time_limit) as (values
('P5PRO05-D02','P5-PRO-05','diagnostic','medium','mcq','Given P(A∩B)=0.18 and P(B)=0.45, find P(A|B).','["0.40","0.27","0.63","0.81"]','A','P(A|B)=P(A∩B)/P(B)=0.18/0.45=0.40.','Даны P(A∩B)=0,18 и P(B)=0,45. Найдите P(A|B).','["0,40","0,27","0,63","0,81"]','P(A|B)=P(A∩B)/P(B)=0,18/0,45=0,40.','P(A∩B)=0.18 va P(B)=0.45. P(A|B) ni toping.','["0.40","0.27","0.63","0.81"]','P(A|B)=P(A∩B)/P(B)=0.18/0.45=0.40.',60),
('P5PRO05-D03','P5-PRO-05','diagnostic','medium','mcq','In a club, 24 students play a sport and 10 of these also play music. A student is known to play a sport. What is the probability that the student also plays music?','["5/24","5/12","7/12","12/5"]','B','Conditioning on playing a sport restricts the sample space to 24 students. Of these, 10 also play music, so the probability is 10/24=5/12.','В клубе 24 ученика занимаются спортом, и 10 из них также занимаются музыкой. Известно, что выбранный ученик занимается спортом. Какова вероятность, что он также занимается музыкой?','["5/24","5/12","7/12","12/5"]','При условии занятия спортом рассматриваем 24 ученика. Из них 10 также занимаются музыкой, поэтому вероятность равна 10/24=5/12.','Klubda 24 o‘quvchi sport bilan shug‘ullanadi, ulardan 10 tasi musiqa bilan ham shug‘ullanadi. Tanlangan o‘quvchi sport bilan shug‘ullanishi ma’lum. Uning musiqa bilan ham shug‘ullanish ehtimoli qancha?','["5/24","5/12","7/12","12/5"]','Sport bilan shug‘ullanish sharti ostida 24 o‘quvchi ichidan qaraymiz. Ulardan 10 tasi musiqa bilan ham shug‘ullanadi, demak ehtimol 10/24=5/12.',70),
('P5PRO05-R03','P5-PRO-05','retest','medium','input','P(B|A)=0.60 and P(A)=0.50. Enter P(A∩B).','[]','0.3','P(A∩B)=P(A)P(B|A)=0.50×0.60=0.30.','P(B|A)=0,60 и P(A)=0,50. Введите P(A∩B).','[]','P(A∩B)=P(A)P(B|A)=0,50×0,60=0,30.','P(B|A)=0.60 va P(A)=0.50. P(A∩B) ni kiriting.','[]','P(A∩B)=P(A)P(B|A)=0.50×0.60=0.30.',55),
('P5PRO05-R04','P5-PRO-05','retest','hard','mcq','P(A)=0.50, P(B)=0.45 and P(A∪B)=0.80. Find P(A|B).','["1/4","1/2","1/3","2/3"]','C','P(A∩B)=0.50+0.45−0.80=0.15. Hence P(A|B)=0.15/0.45=1/3.','P(A)=0,50, P(B)=0,45 и P(A∪B)=0,80. Найдите P(A|B).','["1/4","1/2","1/3","2/3"]','P(A∩B)=0,50+0,45−0,80=0,15. Поэтому P(A|B)=0,15/0,45=1/3.','P(A)=0.50, P(B)=0.45 va P(A∪B)=0.80. P(A|B) ni toping.','["1/4","1/2","1/3","2/3"]','P(A∩B)=0.50+0.45−0.80=0.15. Demak P(A|B)=0.15/0.45=1/3.',75),
('P5PRO05-M02','P5-PRO-05','mixed','hard','input','In a class, 14 students wear glasses and 8 of those students are girls. Given that a randomly selected student wears glasses, the probability that the student is a girl is a fraction in simplest form. Enter its numerator.','[]','4','The conditional probability is 8/14=4/7, so the numerator is 4.','В классе 14 учеников носят очки, и 8 из них — девочки. При условии, что случайно выбранный ученик носит очки, вероятность того, что это девочка, записана несократимой дробью. Введите её числитель.','[]','Условная вероятность равна 8/14=4/7, поэтому числитель равен 4.','Sinfda 14 o‘quvchi ko‘zoynak taqadi, ulardan 8 tasi qiz. Tasodifiy tanlangan o‘quvchi ko‘zoynak taqishi ma’lum bo‘lsa, uning qiz bo‘lish ehtimoli qisqartirilgan kasr ko‘rinishida. Suratini kiriting.','[]','Shartli ehtimol 8/14=4/7, demak surat 4.',65),
('P5PRO06-D02','P5-PRO-06','diagnostic','medium','mcq','A bag contains 3 red and 2 blue counters. Two are drawn without replacement. Find P(blue first, then red).','["1/5","3/10","2/5","1/2"]','D','P(blue then red)=2/5×3/4=6/20=3/10.','В мешке 3 красные и 2 синие фишки. Две фишки вытаскивают без возвращения. Найдите P(сначала синяя, затем красная).','["1/5","3/10","2/5","1/2"]','P(синяя, затем красная)=2/5×3/4=6/20=3/10.','Qopda 3 qizil va 2 ko‘k jeton bor. Ikki jeton qaytarmasdan olinadi. P(avval ko‘k, keyin qizil) ni toping.','["1/5","3/10","2/5","1/2"]','P(ko‘k, keyin qizil)=2/5×3/4=6/20=3/10.',65),
('P5PRO06-D03','P5-PRO-06','diagnostic','medium','mcq','A process chooses route A with probability 0.6 and route B with probability 0.4. The success probabilities are 0.8 after A and 0.5 after B. Find the overall probability of success.','["0.68","0.56","0.48","0.80"]','A','The success branches give 0.6×0.8+0.4×0.5=0.48+0.20=0.68.','Процесс выбирает маршрут A с вероятностью 0,6 и маршрут B с вероятностью 0,4. Вероятность успеха после A равна 0,8, после B — 0,5. Найдите общую вероятность успеха.','["0,68","0,56","0,48","0,80"]','Суммируем ветви успеха: 0,6×0,8+0,4×0,5=0,48+0,20=0,68.','Jarayon A yo‘lini 0.6 ehtimol bilan, B yo‘lini 0.4 ehtimol bilan tanlaydi. A dan keyin muvaffaqiyat ehtimoli 0.8, B dan keyin 0.5. Umumiy muvaffaqiyat ehtimolini toping.','["0.68","0.56","0.48","0.80"]','Muvaffaqiyat shoxlarini qo‘shamiz: 0.6×0.8+0.4×0.5=0.48+0.20=0.68.',70),
('P5PRO06-R03','P5-PRO-06','retest','medium','input','A bag contains 4 red and 3 blue counters. Two are drawn without replacement. The probability that both are red is written in simplest form. Enter its numerator.','[]','2','P(both red)=4/7×3/6=12/42=2/7, so the numerator is 2.','В мешке 4 красные и 3 синие фишки. Две фишки вытаскивают без возвращения. Вероятность получить две красные записана несократимой дробью. Введите её числитель.','[]','P(две красные)=4/7×3/6=12/42=2/7, поэтому числитель равен 2.','Qopda 4 qizil va 3 ko‘k jeton bor. Ikki jeton qaytarmasdan olinadi. Ikkalasi ham qizil bo‘lish ehtimoli qisqartirilgan kasr ko‘rinishida. Suratini kiriting.','[]','P(ikkalasi qizil)=4/7×3/6=12/42=2/7, demak surat 2.',60),
('P5PRO06-R04','P5-PRO-06','retest','medium','mcq','A fair coin is tossed and then a fair die is rolled. Find P(tail and a number greater than 4).','["1/12","1/6","1/4","1/3"]','B','P(tail)=1/2 and P(number greater than 4)=2/6=1/3. The events are independent, so the probability is 1/2×1/3=1/6.','Подбрасывают честную монету, затем бросают честный кубик. Найдите P(решка и число больше 4).','["1/12","1/6","1/4","1/3"]','P(решка)=1/2, а P(число больше 4)=2/6=1/3. События независимы, поэтому вероятность равна 1/2×1/3=1/6.','Adolatli tanga tashlanadi, keyin adolatli kubik tashlanadi. P(raqamli tomon va 4 dan katta son) ni toping.','["1/12","1/6","1/4","1/3"]','P(raqamli tomon)=1/2 va P(4 dan katta son)=2/6=1/3. Hodisalar mustaqil, demak ehtimol 1/2×1/3=1/6.',55),
('P5PRO06-M02','P5-PRO-06','mixed','hard','input','A bag contains 3 red, 2 blue and 1 green counter. Two counters are drawn without replacement. The probability of getting exactly one green counter is written in simplest form. Enter its denominator.','[]','3','P(exactly one green)=1/6×5/5+5/6×1/5=1/6+1/6=1/3, so the denominator is 3.','В мешке 3 красные, 2 синие и 1 зелёная фишка. Две фишки вытаскивают без возвращения. Вероятность получить ровно одну зелёную записана несократимой дробью. Введите её знаменатель.','[]','P(ровно одна зелёная)=1/6×5/5+5/6×1/5=1/6+1/6=1/3, поэтому знаменатель равен 3.','Qopda 3 qizil, 2 ko‘k va 1 yashil jeton bor. Ikki jeton qaytarmasdan olinadi. Aynan bitta yashil chiqish ehtimoli qisqartirilgan kasr ko‘rinishida. Maxrajini kiriting.','[]','P(aynan bitta yashil)=1/6×5/5+5/6×1/5=1/6+1/6=1/3, demak maxraj 3.',75),
('P5DRV01-D02','P5-DRV-01','diagnostic','medium','mcq','X takes four possible values with probabilities k, k, 2k and 0.20. Find k.','["0.10","0.15","0.20","0.25"]','C','The probabilities sum to 1: 4k+0.20=1, so 4k=0.80 and k=0.20.','X принимает четыре возможных значения с вероятностями k, k, 2k и 0,20. Найдите k.','["0,10","0,15","0,20","0,25"]','Сумма вероятностей равна 1: 4k+0,20=1, поэтому 4k=0,80 и k=0,20.','X to‘rtta mumkin bo‘lgan qiymatni k, k, 2k va 0.20 ehtimollar bilan oladi. k ni toping.','["0.10","0.15","0.20","0.25"]','Ehtimollar yig‘indisi 1: 4k+0.20=1, demak 4k=0.80 va k=0.20.',60),
('P5DRV01-D03','P5-DRV-01','diagnostic','medium','mcq','Which list can be a valid set of probabilities for all possible values of a discrete random variable?','["0.10, 0.20, 0.30","0.25, 0.50, 0.40","−0.10, 0.50, 0.60","0.15, 0.25, 0.20, 0.40"]','D','A valid distribution has probabilities between 0 and 1 whose total is 1. Only 0.15+0.25+0.20+0.40=1 satisfies both conditions.','Какой набор может быть корректным набором вероятностей для всех возможных значений дискретной случайной величины?','["0,10; 0,20; 0,30","0,25; 0,50; 0,40","−0,10; 0,50; 0,60","0,15; 0,25; 0,20; 0,40"]','В корректном распределении вероятности лежат от 0 до 1 и в сумме дают 1. Только 0,15+0,25+0,20+0,40=1 удовлетворяет обоим условиям.','Diskret tasodifiy kattalikning barcha mumkin qiymatlari uchun qaysi ro‘yxat to‘g‘ri ehtimollar to‘plami bo‘la oladi?','["0.10, 0.20, 0.30","0.25, 0.50, 0.40","−0.10, 0.50, 0.60","0.15, 0.25, 0.20, 0.40"]','To‘g‘ri taqsimotda ehtimollar 0 va 1 orasida bo‘ladi va yig‘indisi 1. Faqat 0.15+0.25+0.20+0.40=1 ikkala shartga mos.',65),
('P5DRV01-R03','P5-DRV-01','retest','medium','input','X takes values 0, 1 and 2 with probabilities 0.10, 0.30 and k. Enter k.','[]','0.6','The probabilities sum to 1, so k=1−0.10−0.30=0.60.','X принимает значения 0, 1 и 2 с вероятностями 0,10, 0,30 и k. Введите k.','[]','Сумма вероятностей равна 1, поэтому k=1−0,10−0,30=0,60.','X 0, 1 va 2 qiymatlarni 0.10, 0.30 va k ehtimollar bilan oladi. k ni kiriting.','[]','Ehtimollar yig‘indisi 1, demak k=1−0.10−0.30=0.60.',50),
('P5DRV01-R04','P5-DRV-01','retest','medium','mcq','A fair die is rolled once. X=0 for scores 1 or 2, X=1 for scores 3, 4 or 5, and X=2 for score 6. Which distribution is correct?','["P(0)=1/3, P(1)=1/2, P(2)=1/6","P(0)=1/6, P(1)=1/2, P(2)=1/3","P(0)=1/3, P(1)=1/3, P(2)=1/3","P(0)=1/2, P(1)=1/3, P(2)=1/6"]','A','Two die scores give X=0, three give X=1 and one gives X=2, so the probabilities are 2/6, 3/6 and 1/6.','Честный кубик бросают один раз. X=0 при выпадении 1 или 2, X=1 при выпадении 3, 4 или 5, X=2 при выпадении 6. Какое распределение верно?','["P(0)=1/3, P(1)=1/2, P(2)=1/6","P(0)=1/6, P(1)=1/2, P(2)=1/3","P(0)=1/3, P(1)=1/3, P(2)=1/3","P(0)=1/2, P(1)=1/3, P(2)=1/6"]','Два исхода дают X=0, три исхода дают X=1 и один исход даёт X=2, поэтому вероятности равны 2/6, 3/6 и 1/6.','Adolatli kubik bir marta tashlanadi. 1 yoki 2 tushsa X=0, 3, 4 yoki 5 tushsa X=1, 6 tushsa X=2. Qaysi taqsimot to‘g‘ri?','["P(0)=1/3, P(1)=1/2, P(2)=1/6","P(0)=1/6, P(1)=1/2, P(2)=1/3","P(0)=1/3, P(1)=1/3, P(2)=1/3","P(0)=1/2, P(1)=1/3, P(2)=1/6"]','Ikki natija X=0, uchta natija X=1 va bitta natija X=2 ni beradi, demak ehtimollar 2/6, 3/6 va 1/6.',65),
('P5DRV01-M02','P5-DRV-01','mixed','hard','input','A fair die is rolled once. Let X=0 for scores 1 or 2, X=1 for scores 3, 4 or 5, and X=2 for score 6. P(X≥1) is a fraction in simplest form. Enter its numerator.','[]','2','P(X≥1)=4/6=2/3, so the numerator is 2.','Честный кубик бросают один раз. Пусть X=0 при 1 или 2, X=1 при 3, 4 или 5, X=2 при 6. P(X≥1) записана несократимой дробью. Введите её числитель.','[]','P(X≥1)=4/6=2/3, поэтому числитель равен 2.','Adolatli kubik bir marta tashlanadi. 1 yoki 2 tushsa X=0, 3, 4 yoki 5 tushsa X=1, 6 tushsa X=2. P(X≥1) qisqartirilgan kasr ko‘rinishida. Suratini kiriting.','[]','P(X≥1)=4/6=2/3, demak surat 2.',60),
('P5DRV02-D02','P5-DRV-02','diagnostic','medium','mcq','X takes values 1, 3 and 5 with probabilities 0.20, 0.50 and 0.30. Find E(X).','["2.8","3.2","3.5","4.0"]','B','E(X)=1(0.20)+3(0.50)+5(0.30)=0.20+1.50+1.50=3.20.','X принимает значения 1, 3 и 5 с вероятностями 0,20, 0,50 и 0,30. Найдите E(X).','["2,8","3,2","3,5","4,0"]','E(X)=1(0,20)+3(0,50)+5(0,30)=0,20+1,50+1,50=3,20.','X 1, 3 va 5 qiymatlarni 0.20, 0.50 va 0.30 ehtimollar bilan oladi. E(X) ni toping.','["2.8","3.2","3.5","4.0"]','E(X)=1(0.20)+3(0.50)+5(0.30)=0.20+1.50+1.50=3.20.',60),
('P5DRV02-D03','P5-DRV-02','diagnostic','medium','mcq','A game gives 10 units with probability 0.10, gives 2 units with probability 0.40, and loses 1 unit otherwise. Find the expected gain.','["0.3","0.8","1.3","1.8"]','C','The remaining probability is 0.50. E=10(0.10)+2(0.40)−1(0.50)=1+0.8−0.5=1.3.','Игра приносит 10 единиц с вероятностью 0,10, 2 единицы с вероятностью 0,40 и потерю 1 единицы в остальных случаях. Найдите ожидаемый выигрыш.','["0,3","0,8","1,3","1,8"]','Оставшаяся вероятность равна 0,50. E=10(0,10)+2(0,40)−1(0,50)=1+0,8−0,5=1,3.','O‘yin 0.10 ehtimol bilan 10 birlik, 0.40 ehtimol bilan 2 birlik yutuq beradi, qolgan hollarda 1 birlik zarar bo‘ladi. Kutiladigan yutuqni toping.','["0.3","0.8","1.3","1.8"]','Qolgan ehtimol 0.50. E=10(0.10)+2(0.40)−1(0.50)=1+0.8−0.5=1.3.',65),
('P5DRV02-R03','P5-DRV-02','retest','medium','input','X takes values −2 and 4 with probabilities 0.25 and 0.75. Enter E(X).','[]','2.5','E(X)=−2(0.25)+4(0.75)=−0.5+3=2.5.','X принимает значения −2 и 4 с вероятностями 0,25 и 0,75. Введите E(X).','[]','E(X)=−2(0,25)+4(0,75)=−0,5+3=2,5.','X −2 va 4 qiymatlarni 0.25 va 0.75 ehtimollar bilan oladi. E(X) ni kiriting.','[]','E(X)=−2(0.25)+4(0.75)=−0.5+3=2.5.',55),
('P5DRV02-R04','P5-DRV-02','retest','medium','mcq','X takes values 0, 1 and 4 with probabilities 0.50, 0.25 and 0.25. Find E(X).','["1.00","1.25","1.50","2.00"]','D','E(X)=0(0.50)+1(0.25)+4(0.25)=0.25+1=1.25.','X принимает значения 0, 1 и 4 с вероятностями 0,50, 0,25 и 0,25. Найдите E(X).','["1,00","1,25","1,50","2,00"]','E(X)=0(0,50)+1(0,25)+4(0,25)=0,25+1=1,25.','X 0, 1 va 4 qiymatlarni 0.50, 0.25 va 0.25 ehtimollar bilan oladi. E(X) ni toping.','["1.00","1.25","1.50","2.00"]','E(X)=0(0.50)+1(0.25)+4(0.25)=0.25+1=1.25.',55),
('P5DRV02-M02','P5-DRV-02','mixed','hard','input','A reward X is 0 with probability 0.50, 5 with probability 0.30 and 10 with probability 0.20. Enter E(X).','[]','3.5','E(X)=0(0.50)+5(0.30)+10(0.20)=1.5+2=3.5.','Вознаграждение X равно 0 с вероятностью 0,50, 5 с вероятностью 0,30 и 10 с вероятностью 0,20. Введите E(X).','[]','E(X)=0(0,50)+5(0,30)+10(0,20)=1,5+2=3,5.','X mukofot 0.50 ehtimol bilan 0, 0.30 ehtimol bilan 5 va 0.20 ehtimol bilan 10 ga teng. E(X) ni kiriting.','[]','E(X)=0(0.50)+5(0.30)+10(0.20)=1.5+2=3.5.',60),
('P5DRV03-D02','P5-DRV-03','diagnostic','medium','mcq','For a discrete random variable, E(X)=2 and E(X²)=7. Find Var(X).','["3","2","5","11"]','A','Var(X)=E(X²)−[E(X)]²=7−4=3.','Для дискретной случайной величины E(X)=2 и E(X²)=7. Найдите Var(X).','["3","2","5","11"]','Var(X)=E(X²)−[E(X)]²=7−4=3.','Diskret tasodifiy kattalik uchun E(X)=2 va E(X²)=7. Var(X) ni toping.','["3","2","5","11"]','Var(X)=E(X²)−[E(X)]²=7−4=3.',55),
('P5DRV03-D03','P5-DRV-03','diagnostic','medium','mcq','X takes values 1 and 3 with equal probability. What is the standard deviation of X?','["2","1","√2","1/2"]','B','E(X)=2 and E(X²)=5, so Var(X)=5−4=1 and the standard deviation is 1.','X принимает значения 1 и 3 с равными вероятностями. Каково стандартное отклонение X?','["2","1","√2","1/2"]','E(X)=2 и E(X²)=5, поэтому Var(X)=5−4=1 и стандартное отклонение равно 1.','X 1 va 3 qiymatlarni teng ehtimol bilan oladi. X ning standart og‘ishi qancha?','["2","1","√2","1/2"]','E(X)=2 va E(X²)=5, demak Var(X)=5−4=1 va standart og‘ish 1.',60),
('P5DRV03-R03','P5-DRV-03','retest','medium','input','If Var(X)=6.25, enter the standard deviation of X.','[]','2.5','The standard deviation is √6.25=2.5.','Если Var(X)=6,25, введите стандартное отклонение X.','[]','Стандартное отклонение равно √6,25=2,5.','Agar Var(X)=6.25 bo‘lsa, X ning standart og‘ishini kiriting.','[]','Standart og‘ish √6.25=2.5.',50),
('P5DRV03-R04','P5-DRV-03','retest','medium','mcq','For X, E(X)=1.5 and E(X²)=3.25. What is the standard deviation?','["0.5","√2","1","1.25"]','C','Var(X)=3.25−1.5²=3.25−2.25=1, so the standard deviation is 1.','Для X даны E(X)=1,5 и E(X²)=3,25. Каково стандартное отклонение?','["0,5","√2","1","1,25"]','Var(X)=3,25−1,5²=3,25−2,25=1, поэтому стандартное отклонение равно 1.','X uchun E(X)=1.5 va E(X²)=3.25. Standart og‘ish qancha?','["0.5","√2","1","1.25"]','Var(X)=3.25−1.5²=3.25−2.25=1, demak standart og‘ish 1.',60),
('P5DRV03-M02','P5-DRV-03','mixed','hard','input','X takes values 0, 2 and 4 with probabilities 0.25, 0.25 and 0.50. Enter Var(X).','[]','2.75','E(X)=0+0.5+2=2.5 and E(X²)=0+1+8=9. Hence Var(X)=9−2.5²=9−6.25=2.75.','X принимает значения 0, 2 и 4 с вероятностями 0,25, 0,25 и 0,50. Введите Var(X).','[]','E(X)=0+0,5+2=2,5 и E(X²)=0+1+8=9. Поэтому Var(X)=9−2,5²=9−6,25=2,75.','X 0, 2 va 4 qiymatlarni 0.25, 0.25 va 0.50 ehtimollar bilan oladi. Var(X) ni kiriting.','[]','E(X)=0+0.5+2=2.5 va E(X²)=0+1+8=9. Demak Var(X)=9−2.5²=9−6.25=2.75.',70),
('P5BIN01-D02','P5-BIN-01','diagnostic','medium','mcq','Ten independent trials each have success probability 0.20. X is the number of successes. Which model is correct?','["X~B(10,0.20)","X~Geo(0.20)","X~B(0.20,10)","No standard model"]','D','There are a fixed 10 independent two-outcome trials with constant p=0.20, so X~B(10,0.20).','В 10 независимых испытаниях вероятность успеха в каждом равна 0,20. X — число успехов. Какая модель верна?','["X~B(10,0,20)","X~Geo(0,20)","X~B(0,20,10)","Стандартная модель не подходит"]','Имеется фиксированное число 10 независимых испытаний с двумя исходами и постоянным p=0,20, поэтому X~B(10,0,20).','10 ta mustaqil sinovning har birida muvaffaqiyat ehtimoli 0.20. X — muvaffaqiyatlar soni. Qaysi model to‘g‘ri?','["X~B(10,0.20)","X~Geo(0.20)","X~B(0.20,10)","Standart model yo‘q"]','10 ta belgilangan mustaqil ikki natijali sinov va o‘zgarmas p=0.20 bor, demak X~B(10,0.20).',65),
('P5BIN01-D03','P5-BIN-01','diagnostic','medium','mcq','A player takes 8 shots, but the probability of scoring decreases after each shot because of fatigue. X is the number scored. Which binomial condition fails?','["The success probability is constant","There are two outcomes per shot","The number of shots is fixed","X counts successes"]','A','Although the number of trials is fixed and each shot has score/miss outcomes, fatigue changes the success probability, so constant p fails.','Игрок делает 8 бросков, но из-за усталости вероятность попадания уменьшается после каждого броска. X — число попаданий. Какое условие биномиальной модели нарушено?','["Вероятность успеха постоянна","В каждом броске два исхода","Число бросков фиксировано","X считает успехи"]','Число испытаний фиксировано и исходы — попадание/промах, но усталость меняет вероятность успеха, поэтому условие постоянного p нарушено.','O‘yinchi 8 ta zarba beradi, lekin charchoq sabab har bir zarbadan keyin gol urish ehtimoli kamayadi. X — gollar soni. Binomial modelning qaysi sharti buziladi?','["Muvaffaqiyat ehtimoli o‘zgarmas","Har bir zarbada ikki natija bor","Zarbalar soni belgilangan","X muvaffaqiyatlarni sanaydi"]','Sinovlar soni belgilangan va har zarbada gol/gol emas natijasi bor, lekin charchoq muvaffaqiyat ehtimolini o‘zgartiradi, demak o‘zgarmas p sharti buziladi.',70),
('P5BIN01-R03','P5-BIN-01','retest','medium','input','Thirty independent items are tested. Each item is defective with the same probability 0.02, and X is the number of defective items. Enter the binomial parameter n.','[]','30','There are 30 fixed trials, so n=30.','Проверяют 30 независимых изделий. Каждое дефектно с одинаковой вероятностью 0,02, X — число дефектных изделий. Введите биномиальный параметр n.','[]','Число испытаний фиксировано и равно 30, поэтому n=30.','30 ta mustaqil buyum tekshiriladi. Har biri bir xil 0.02 ehtimol bilan nuqsonli, X — nuqsonli buyumlar soni. Binomial n parametrini kiriting.','[]','Sinovlar soni 30 ta qilib belgilangan, demak n=30.',50),
('P5BIN01-R04','P5-BIN-01','retest','medium','mcq','A fair coin is tossed until the first head occurs. Why is the number of tosses not binomial?','["The coin has more than two outcomes","The number of trials is not fixed in advance","The success probability changes after each toss","The tosses are dependent"]','B','A binomial count needs a fixed number of trials. Here the experiment stops at the first success, so the number of trials is variable.','Честную монету подбрасывают до первого орла. Почему число бросков не имеет биномиального распределения?','["У монеты больше двух исходов","Число испытаний заранее не фиксировано","Вероятность успеха меняется после каждого броска","Броски зависимы"]','Для биномиальной модели число испытаний должно быть фиксировано. Здесь эксперимент останавливается при первом успехе, поэтому число испытаний переменно.','Adolatli tanga birinchi gerbgacha tashlanadi. Nega tashlashlar soni binomial taqsimotga ega emas?','["Tangada ikki natijadan ko‘p","Sinovlar soni oldindan belgilanmagan","Muvaffaqiyat ehtimoli har tashlashdan keyin o‘zgaradi","Tashlashlar bog‘liq"]','Binomial hisobda sinovlar soni belgilangan bo‘lishi kerak. Bu yerda tajriba birinchi muvaffaqiyatda to‘xtaydi, shuning uchun sinovlar soni o‘zgaruvchan.',60),
('P5BIN01-M02','P5-BIN-01','mixed','hard','input','Twelve independent multiple-choice questions are answered by random guessing. Each question has four options with one correct answer. X is the number answered correctly. Enter the binomial parameter p.','[]','0.25','Each question is an independent two-outcome trial for correct/incorrect, with constant success probability p=1/4=0.25.','На 12 независимых вопросах с выбором ответа ученик угадывает случайно. В каждом вопросе 4 варианта, один правильный. X — число правильных ответов. Введите биномиальный параметр p.','[]','Каждый вопрос — независимое испытание с исходами правильно/неправильно и постоянной вероятностью успеха p=1/4=0,25.','12 ta mustaqil test savoliga tasodifiy javob beriladi. Har savolda 4 variantdan bittasi to‘g‘ri. X — to‘g‘ri javoblar soni. Binomial p parametrini kiriting.','[]','Har savol to‘g‘ri/noto‘g‘ri natijali mustaqil sinov bo‘lib, o‘zgarmas muvaffaqiyat ehtimoli p=1/4=0.25.',60),
('P5GEO01-D02','P5-GEO-01','diagnostic','medium','mcq','A fair die is rolled independently until the first six occurs. Which model describes X, the roll number of the first six?','["Binomial with n=6","Normal","Geometric with p=1/6","No standard model"]','C','The trials are independent with constant success probability 1/6 and continue until the first success, so X is geometric.','Честный кубик независимо бросают до первого выпадения шестёрки. Какая модель описывает X — номер броска, на котором впервые выпала шестёрка?','["Биномиальная с n=6","Нормальная","Геометрическая с p=1/6","Стандартная модель не подходит"]','Испытания независимы, вероятность успеха постоянна и равна 1/6, а процесс продолжается до первого успеха, поэтому X имеет геометрическое распределение.','Adolatli kubik birinchi 6 tushguncha mustaqil tashlanadi. X — birinchi 6 tushgan tashlash raqami. Qaysi model X ni tavsiflaydi?','["n=6 bo‘lgan binomial","Normal","p=1/6 bo‘lgan geometrik","Standart model yo‘q"]','Sinovlar mustaqil, muvaffaqiyat ehtimoli 1/6 va o‘zgarmas, jarayon birinchi muvaffaqiyatgacha davom etadi. Demak X geometrik.',60),
('P5GEO01-D03','P5-GEO-01','diagnostic','medium','mcq','A fair die is rolled exactly 20 times and X counts the number of sixes. Why is X not geometric?','["The success probability is not constant","The trials are dependent","There are more than two outcomes after defining success","The experiment counts successes in a fixed number of trials instead of waiting for the first success"]','D','Once success is defined as rolling a six, each trial has success/failure and constant p. But X counts successes in 20 fixed trials, which is binomial structure rather than waiting time to the first success.','Честный кубик бросают ровно 20 раз, X — число выпавших шестёрок. Почему X не имеет геометрического распределения?','["Вероятность успеха непостоянна","Испытания зависимы","После определения успеха остаётся больше двух исходов","Эксперимент считает успехи в фиксированном числе испытаний, а не ждёт первого успеха"]','Если успех — выпадение шестёрки, каждый бросок имеет исход успех/неудача и постоянное p. Но X считает успехи в 20 фиксированных испытаниях, что соответствует биномиальной структуре, а не ожиданию первого успеха.','Adolatli kubik aynan 20 marta tashlanadi, X — tushgan 6 lar soni. Nega X geometrik emas?','["Muvaffaqiyat ehtimoli o‘zgarmas emas","Sinovlar bog‘liq","Muvaffaqiyat aniqlangandan keyin ikki natijadan ko‘p qoladi","Tajriba birinchi muvaffaqiyatgacha kutish o‘rniga belgilangan sondagi sinovlarda muvaffaqiyatlarni sanaydi"]','Muvaffaqiyat 6 tushishi deb olinsa, har sinov muvaffaqiyat/muvaffaqiyatsizlik va p o‘zgarmas. Lekin X 20 ta belgilangan sinovdagi muvaffaqiyatlarni sanaydi, bu geometrik emas, binomial tuzilma.',70),
('P5GEO01-R03','P5-GEO-01','retest','medium','input','Independent trials have success probability 0.30 and continue until the first success. Enter the geometric parameter p.','[]','0.3','In a geometric model, p is the constant success probability per trial, so p=0.30.','Независимые испытания имеют вероятность успеха 0,30 и продолжаются до первого успеха. Введите параметр геометрического распределения p.','[]','В геометрической модели p — постоянная вероятность успеха в каждом испытании, поэтому p=0,30.','Mustaqil sinovlarda muvaffaqiyat ehtimoli 0.30 va ular birinchi muvaffaqiyatgacha davom etadi. Geometrik p parametrini kiriting.','[]','Geometrik modelda p har bir sinovdagi o‘zgarmas muvaffaqiyat ehtimoli, demak p=0.30.',50),
('P5GEO01-R04','P5-GEO-01','retest','medium','mcq','Cards are drawn one at a time with replacement from a standard 52-card deck until the first ace appears. Which geometric parameter is correct?','["p=1/13","p=4/13","p=1/4","p=13/52"]','A','With replacement, draws are independent and the ace probability remains 4/52=1/13 on every draw.','Карты вытаскивают по одной с возвращением из стандартной колоды из 52 карт до первого туза. Какой параметр геометрического распределения верен?','["p=1/13","p=4/13","p=1/4","p=13/52"]','При возвращении вытаскивания независимы, а вероятность туза на каждом вытаскивании остаётся 4/52=1/13.','Standart 52 kartalik kolodadan kartalar birma-bir qaytarib olinadi va birinchi tuzgacha davom etadi. Qaysi geometrik parametr to‘g‘ri?','["p=1/13","p=4/13","p=1/4","p=13/52"]','Qaytarib olinganda tanlovlar mustaqil va har safar tuz ehtimoli 4/52=1/13 bo‘lib qoladi.',60),
('P5GEO01-M02','P5-GEO-01','mixed','hard','input','A fair die is rolled repeatedly until a number greater than 4 first appears. Enter the geometric parameter p as a decimal.','[]','0.3333333333','A success is rolling 5 or 6, so p=2/6=1/3≈0.3333333333.','Честный кубик многократно бросают до первого появления числа больше 4. Введите параметр геометрического распределения p в виде десятичной дроби.','[]','Успех — выпадение 5 или 6, поэтому p=2/6=1/3≈0,3333333333.','Adolatli kubik 4 dan katta son birinchi marta tushguncha qayta-qayta tashlanadi. Geometrik p parametrini o‘nli kasr sifatida kiriting.','[]','Muvaffaqiyat 5 yoki 6 tushishi, shuning uchun p=2/6=1/3≈0.3333333333.',65)
)
insert into public.questions(
 subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,
 question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,
 explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
)
select 5,'P5 annual reserve',s.skill_code,s.difficulty,s.qtype,s.q_en,s.opts_en,s.answer,s.exp_en,null,false,
 s.q_ru,s.q_uz,s.q_en,s.opts_ru,s.opts_uz,s.opts_en,s.exp_ru,s.exp_uz,s.exp_en,
 'ExamPrep:P5:p5_aw13_16_annual_reserve_topup_draft_v1:'||s.content_key,s.time_limit,null,'draft'
from src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_annual_reserve_topup_draft_v1:'||s.content_key);

with src(meta_id,content_key,skill_code,reserve_role,official_ref,book_ref) as (values
(59355,'P5PRO05-D02','P5-PRO-05','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59356,'P5PRO05-D03','P5-PRO-05','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59357,'P5PRO05-R03','P5-PRO-05','retest','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59358,'P5PRO05-R04','P5-PRO-05','retest','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59359,'P5PRO05-M02','P5-PRO-05','mixed','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59360,'P5PRO06-D02','P5-PRO-06','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59361,'P5PRO06-D03','P5-PRO-06','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59362,'P5PRO06-R03','P5-PRO-06','retest','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59363,'P5PRO06-R04','P5-PRO-06','retest','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59364,'P5PRO06-M02','P5-PRO-06','mixed','Cambridge 9709 2026-2027 v4; P5 5.3 Probability','Complete Probability & Statistics 1, Ch4 Probability pp.63-82 (mapping only)'),
(59365,'P5DRV01-D02','P5-DRV-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59366,'P5DRV01-D03','P5-DRV-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59367,'P5DRV01-R03','P5-DRV-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59368,'P5DRV01-R04','P5-DRV-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59369,'P5DRV01-M02','P5-DRV-01','mixed','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59370,'P5DRV02-D02','P5-DRV-02','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59371,'P5DRV02-D03','P5-DRV-02','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59372,'P5DRV02-R03','P5-DRV-02','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59373,'P5DRV02-R04','P5-DRV-02','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59374,'P5DRV02-M02','P5-DRV-02','mixed','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59375,'P5DRV03-D02','P5-DRV-03','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59376,'P5DRV03-D03','P5-DRV-03','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59377,'P5DRV03-R03','P5-DRV-03','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59378,'P5DRV03-R04','P5-DRV-03','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59379,'P5DRV03-M02','P5-DRV-03','mixed','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch5 Discrete random variables pp.84-96 (mapping only)'),
(59380,'P5BIN01-D02','P5-BIN-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch7 The binomial distribution pp.115-131 (mapping only)'),
(59381,'P5BIN01-D03','P5-BIN-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch7 The binomial distribution pp.115-131 (mapping only)'),
(59382,'P5BIN01-R03','P5-BIN-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch7 The binomial distribution pp.115-131 (mapping only)'),
(59383,'P5BIN01-R04','P5-BIN-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch7 The binomial distribution pp.115-131 (mapping only)'),
(59384,'P5BIN01-M02','P5-BIN-01','mixed','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch7 The binomial distribution pp.115-131 (mapping only)'),
(59385,'P5GEO01-D02','P5-GEO-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch8 The geometric distribution pp.133-145 (mapping only)'),
(59386,'P5GEO01-D03','P5-GEO-01','diagnostic','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch8 The geometric distribution pp.133-145 (mapping only)'),
(59387,'P5GEO01-R03','P5-GEO-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch8 The geometric distribution pp.133-145 (mapping only)'),
(59388,'P5GEO01-R04','P5-GEO-01','retest','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch8 The geometric distribution pp.133-145 (mapping only)'),
(59389,'P5GEO01-M02','P5-GEO-01','mixed','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1, Ch8 The geometric distribution pp.133-145 (mapping only)')
)
insert into private.exam_prep_question_content_meta(
 id,content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,
 exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,
 copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5
)
overriding system value
select s.meta_id,4816,s.content_key,q.id,s.skill_code,'{}'::text[],s.reserve_role,'withheld','draft',
 'Original iClub-authored annual-reserve item with independent stem, values, distractors, answer and explanation; no protected source wording copied.',
 'AW13-16 annual reserve top-up. Withheld role is fixed before exposure and remains separate from the released learning pack.',
 s.official_ref,s.book_ref,
 'pending','pending','pending','pending','pending',
 case when s.reserve_role='diagnostic' then 'pending' else 'not_applicable' end,
 md5(concat_ws(chr(31),
   q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),
   coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),
   coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),
   coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),
   coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),
   coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')
 ))
from src s
join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_annual_reserve_topup_draft_v1:'||s.content_key
on conflict(id) do nothing;

do $postcheck$
declare v_bad int; v_a int; v_b int; v_c int; v_d int; v_inputs int;
begin
  if (select status from private.exam_prep_content_versions where id=4816)<>'draft'
     or (select count(*) from private.exam_prep_question_content_meta where content_version_id=4816)<>35
     or (select count(*) from private.exam_prep_question_content_meta where content_version_id=4816 and reserve_role='diagnostic')<>14
     or (select count(*) from private.exam_prep_question_content_meta where content_version_id=4816 and reserve_role='retest')<>14
     or (select count(*) from private.exam_prep_question_content_meta where content_version_id=4816 and reserve_role='mixed')<>7
  then raise exception 'aw13_16_annual_reserve_p5_draft cardinality mismatch'; end if;

  select count(*) into v_bad
  from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id
  where m.content_version_id=4816 and (
    m.lifecycle_state<>'draft' or m.exposure_state<>'withheld'
    or m.copyright_status<>'pending' or m.qa_scope_status<>'pending' or m.qa_math_status<>'pending'
    or m.qa_language_status<>'pending' or m.qa_technical_status<>'pending'
    or (m.reserve_role='diagnostic' and m.diagnostic_rule_status<>'pending')
    or (m.reserve_role<>'diagnostic' and m.diagnostic_rule_status<>'not_applicable')
    or q.is_active or q.quality_status<>'draft'
    or nullif(btrim(q.question_text_en),'') is null or nullif(btrim(q.question_text_ru),'') is null or nullif(btrim(q.question_text_uz),'') is null
    or nullif(btrim(q.explanation_en),'') is null or nullif(btrim(q.explanation_ru),'') is null or nullif(btrim(q.explanation_uz),'') is null
  );
  if v_bad<>0 then raise exception 'aw13_16_annual_reserve_p5_draft QA/exposure rows=%',v_bad; end if;

  if exists(
    select 1 from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id
    join private.exam_prep_question_content_meta oldm on oldm.primary_skill_code=m.primary_skill_code and oldm.content_version_id<>4816
    join private.exam_prep_content_versions oldcv on oldcv.id=oldm.content_version_id and oldcv.status='published'
    join public.questions oldq on oldq.id=oldm.question_id
    where m.content_version_id=4816
      and lower(regexp_replace(q.question_text_en,'\s+',' ','g'))=lower(regexp_replace(oldq.question_text_en,'\s+',' ','g'))
  ) then raise exception 'aw13_16_annual_reserve_p5_draft exact published stem duplicate'; end if;

  select count(*) filter(where q.correct_answer='A'),count(*) filter(where q.correct_answer='B'),
         count(*) filter(where q.correct_answer='C'),count(*) filter(where q.correct_answer='D'),
         count(*) filter(where q.qtype='input')
  into v_a,v_b,v_c,v_d,v_inputs
  from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id
  where m.content_version_id=4816;
  if (v_a,v_b,v_c,v_d,v_inputs)<>(6,5,5,5,14) then
    raise exception 'aw13_16_annual_reserve_p5_draft answer balance drift A=% B=% C=% D=% input=%',v_a,v_b,v_c,v_d,v_inputs;
  end if;

  if exists(select 1 from private.exam_prep_sessions s join private.exam_prep_assessments a on a.id=s.assessment_id where a.content_version_id=4816)
     or exists(select 1 from public.practice_answers pa join private.exam_prep_question_content_meta m on m.question_id=pa.question_id where m.content_version_id=4816)
     or exists(select 1 from public.tour_answers ta join private.exam_prep_question_content_meta m on m.question_id=ta.question_id where m.content_version_id=4816)
  then raise exception 'aw13_16_annual_reserve_p5_draft unexpected history'; end if;
end
$postcheck$;

commit;
