-- AI-4 Chemistry Practice 1 precise source pack: Electrons in atoms.
-- Question-specific approved source cards for all 18 current questions in this topic.
-- Source-only: no diagnostics, scoring/history writes, AI enablement or entitlements.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,subtopic,qtype) as (
    values
    (1908,'Shape of the p orbital','mcq'),
    (1917,'Orbital electron capacity','mcq'),
    (1927,'Effective nuclear charge across a period','mcq'),
    (1931,'Atomic radius across a period','mcq'),
    (1937,'Group properties and outer electrons','mcq'),
    (1939,'First energy level','mcq'),
    (1941,'Atomic radius trend down a group','mcq'),
    (1945,'Electron configuration of magnesium','mcq'),
    (1953,'Ionisation energy down a group','mcq'),
    (1956,'Atomic radius across a period','mcq'),
    (1960,'Electron capacity of the p subshell','mcq'),
    (1962,'Energy levels in the same period','mcq'),
    (1968,'First ionisation energy across a period','mcq'),
    (1971,'Valence electrons and group properties','mcq'),
    (3036,'Capacity of the p sub-shell','mcq'),
    (3037,'Electron configuration of aluminium','mcq'),
    (3039,'First ionisation energy across Period 3','mcq'),
    (3046,'Large jump in successive ionisation energies','mcq')
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>4
     or q.is_active is not true
     or q.quality_status<>'published'
     or q.topic<>'Electrons in atoms'
     or q.subtopic<>e.subtopic
     or lower(coalesce(q.qtype,''))<>e.qtype;

  if v_bad<>0 then
    raise exception 'AI-4 Chemistry Electrons source batch refused: one or more target questions changed';
  end if;
end
$guard$;

insert into private.practice_ai_source_cards(
  source_card_key,subject_key,question_id,topic,subtopic,card_type,locale,source_version,
  title,body_text,approval_status,rights_status,is_runtime_allowed,content_hash,approved_at,updated_at
)
values
('practice:chemistry:p1:q1908:en:v1','chemistry',1908,'Electrons in atoms','Shape of the p orbital',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Shape of a p orbital','An s orbital is spherical, while a p orbital has two lobes and is commonly described as dumbbell-shaped. Each p subshell contains three p orbitals with different orientations.',
 'approved','original_iclub',true,encode(digest(convert_to('An s orbital is spherical, while a p orbital has two lobes and is commonly described as dumbbell-shaped. Each p subshell contains three p orbitals with different orientations.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1908:ru:v1','chemistry',1908,'Electrons in atoms','Shape of the p orbital',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Форма p-орбитали','s-орбиталь имеет сферическую форму, а p-орбиталь состоит из двух лепестков и обычно описывается как гантелеобразная. Каждый p-подуровень содержит три p-орбитали с разной ориентацией.',
 'approved','original_iclub',true,encode(digest(convert_to('s-орбиталь имеет сферическую форму, а p-орбиталь состоит из двух лепестков и обычно описывается как гантелеобразная. Каждый p-подуровень содержит три p-орбитали с разной ориентацией.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1908:uz:v1','chemistry',1908,'Electrons in atoms','Shape of the p orbital',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','p-orbital shakli','s-orbital sferik, p-orbital esa ikki bo‘lakli bo‘lib, odatda gantel shaklida tasvirlanadi. Har bir p-qavatchada turli yo‘nalgan uchta p-orbital mavjud.',
 'approved','original_iclub',true,encode(digest(convert_to('s-orbital sferik, p-orbital esa ikki bo‘lakli bo‘lib, odatda gantel shaklida tasvirlanadi. Har bir p-qavatchada turli yo‘nalgan uchta p-orbital mavjud.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1917:en:v1','chemistry',1917,'Electrons in atoms','Orbital electron capacity',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Electron capacity of subshells','Each orbital can hold a maximum of two electrons. An s subshell has one orbital and can hold 2 electrons; a p subshell has three orbitals and can hold 6; d and f subshells contain more orbitals.',
 'approved','original_iclub',true,encode(digest(convert_to('Each orbital can hold a maximum of two electrons. An s subshell has one orbital and can hold 2 electrons; a p subshell has three orbitals and can hold 6; d and f subshells contain more orbitals.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1917:ru:v1','chemistry',1917,'Electrons in atoms','Orbital electron capacity',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Вместимость электронов на подуровнях','Каждая орбиталь может содержать максимум два электрона. s-подуровень имеет одну орбиталь и вмещает 2 электрона; p-подуровень имеет три орбитали и вмещает 6; d- и f-подуровни содержат больше орбиталей.',
 'approved','original_iclub',true,encode(digest(convert_to('Каждая орбиталь может содержать максимум два электрона. s-подуровень имеет одну орбиталь и вмещает 2 электрона; p-подуровень имеет три орбитали и вмещает 6; d- и f-подуровни содержат больше орбиталей.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1917:uz:v1','chemistry',1917,'Electrons in atoms','Orbital electron capacity',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Qavatchalarning elektron sig‘imi','Har bir orbital ko‘pi bilan ikki elektron sig‘diradi. s-qavatchada bitta orbital va 2 elektron, p-qavatchada uchta orbital va 6 elektron sig‘ishi mumkin; d va f qavatchalarda orbitallar ko‘proq.',
 'approved','original_iclub',true,encode(digest(convert_to('Har bir orbital ko‘pi bilan ikki elektron sig‘diradi. s-qavatchada bitta orbital va 2 elektron, p-qavatchada uchta orbital va 6 elektron sig‘ishi mumkin; d va f qavatchalarda orbitallar ko‘proq.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1927:en:v1','chemistry',1927,'Electrons in atoms','Effective nuclear charge across a period',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Effective nuclear charge across a period','Across a period from left to right, proton number increases while added electrons enter the same main energy level, so shielding changes much less than nuclear charge. The effective attraction experienced by outer electrons therefore generally increases.',
 'approved','original_iclub',true,encode(digest(convert_to('Across a period from left to right, proton number increases while added electrons enter the same main energy level, so shielding changes much less than nuclear charge. The effective attraction experienced by outer electrons therefore generally increases.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1927:ru:v1','chemistry',1927,'Electrons in atoms','Effective nuclear charge across a period',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Эффективный заряд ядра в периоде','Слева направо в периоде число протонов растёт, а добавляемые электроны поступают на тот же основной энергетический уровень, поэтому экранирование меняется намного меньше, чем заряд ядра. Эффективное притяжение внешних электронов в целом увеличивается.',
 'approved','original_iclub',true,encode(digest(convert_to('Слева направо в периоде число протонов растёт, а добавляемые электроны поступают на тот же основной энергетический уровень, поэтому экранирование меняется намного меньше, чем заряд ядра. Эффективное притяжение внешних электронов в целом увеличивается.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1927:uz:v1','chemistry',1927,'Electrons in atoms','Effective nuclear charge across a period',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Davr bo‘ylab effektiv yadro zaryadi','Davr bo‘ylab chapdan o‘ngga protonlar soni ortadi, qo‘shilayotgan elektronlar esa bir xil asosiy energetik qavatga kiradi. Shuning uchun ekranlanish yadro zaryadiga qaraganda kamroq o‘zgaradi va tashqi elektronlar sezadigan effektiv tortish kuchi odatda ortadi.',
 'approved','original_iclub',true,encode(digest(convert_to('Davr bo‘ylab chapdan o‘ngga protonlar soni ortadi, qo‘shilayotgan elektronlar esa bir xil asosiy energetik qavatga kiradi. Shuning uchun ekranlanish yadro zaryadiga qaraganda kamroq o‘zgaradi va tashqi elektronlar sezadigan effektiv tortish kuchi odatda ortadi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1931:en:v1','chemistry',1931,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Atomic radius across a period','Atomic radius generally decreases across a period from left to right. Nuclear charge increases while electrons are added to the same main shell, so the stronger effective nuclear attraction pulls the electron cloud closer to the nucleus.',
 'approved','original_iclub',true,encode(digest(convert_to('Atomic radius generally decreases across a period from left to right. Nuclear charge increases while electrons are added to the same main shell, so the stronger effective nuclear attraction pulls the electron cloud closer to the nucleus.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1931:ru:v1','chemistry',1931,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Атомный радиус в периоде','Атомный радиус в целом уменьшается слева направо в периоде. Заряд ядра увеличивается, а электроны добавляются на тот же основной уровень, поэтому более сильное эффективное притяжение стягивает электронное облако ближе к ядру.',
 'approved','original_iclub',true,encode(digest(convert_to('Атомный радиус в целом уменьшается слева направо в периоде. Заряд ядра увеличивается, а электроны добавляются на тот же основной уровень, поэтому более сильное эффективное притяжение стягивает электронное облако ближе к ядру.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1931:uz:v1','chemistry',1931,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Davr bo‘ylab atom radiusi','Atom radiusi davr bo‘ylab chapdan o‘ngga odatda kamayadi. Yadro zaryadi ortadi, elektronlar esa bir xil asosiy qavatga qo‘shiladi; kuchliroq effektiv tortish elektron bulutini yadroga yaqinlashtiradi.',
 'approved','original_iclub',true,encode(digest(convert_to('Atom radiusi davr bo‘ylab chapdan o‘ngga odatda kamayadi. Yadro zaryadi ortadi, elektronlar esa bir xil asosiy qavatga qo‘shiladi; kuchliroq effektiv tortish elektron bulutini yadroga yaqinlashtiradi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1937:en:v1','chemistry',1937,'Electrons in atoms','Group properties and outer electrons',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Groups and outer electrons','Main-group elements in the same group have the same number of outer-shell, or valence, electrons. Because chemical reactions mainly involve these outer electrons, elements in a group often show similar chemical properties.',
 'approved','original_iclub',true,encode(digest(convert_to('Main-group elements in the same group have the same number of outer-shell, or valence, electrons. Because chemical reactions mainly involve these outer electrons, elements in a group often show similar chemical properties.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1937:ru:v1','chemistry',1937,'Electrons in atoms','Group properties and outer electrons',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Группы и внешние электроны','Элементы главных подгрупп одной группы имеют одинаковое число электронов на внешнем уровне, то есть валентных электронов. Поскольку химические реакции в основном связаны с внешними электронами, элементы одной группы часто имеют сходные химические свойства.',
 'approved','original_iclub',true,encode(digest(convert_to('Элементы главных подгрупп одной группы имеют одинаковое число электронов на внешнем уровне, то есть валентных электронов. Поскольку химические реакции в основном связаны с внешними электронами, элементы одной группы часто имеют сходные химические свойства.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1937:uz:v1','chemistry',1937,'Electrons in atoms','Group properties and outer electrons',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Guruh va tashqi elektronlar','Asosiy guruh elementlarining bir guruhdagilarida tashqi qavatdagi, ya’ni valent elektronlar soni bir xil bo‘ladi. Kimyoviy reaksiyalar asosan shu tashqi elektronlar bilan bog‘liq bo‘lgani uchun guruh elementlari ko‘pincha o‘xshash kimyoviy xossalarga ega.',
 'approved','original_iclub',true,encode(digest(convert_to('Asosiy guruh elementlarining bir guruhdagilarida tashqi qavatdagi, ya’ni valent elektronlar soni bir xil bo‘ladi. Kimyoviy reaksiyalar asosan shu tashqi elektronlar bilan bog‘liq bo‘lgani uchun guruh elementlari ko‘pincha o‘xshash kimyoviy xossalarga ega.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1939:en:v1','chemistry',1939,'Electrons in atoms','First energy level',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','First energy level','The first principal energy level, n = 1, contains only the 1s subshell and therefore only one orbital. That orbital can hold a maximum of two electrons. There are no 1p orbitals.',
 'approved','original_iclub',true,encode(digest(convert_to('The first principal energy level, n = 1, contains only the 1s subshell and therefore only one orbital. That orbital can hold a maximum of two electrons. There are no 1p orbitals.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1939:ru:v1','chemistry',1939,'Electrons in atoms','First energy level',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Первый энергетический уровень','Первый главный энергетический уровень n = 1 содержит только подуровень 1s и поэтому только одну орбиталь. Эта орбиталь может вместить максимум два электрона. Орбиталей 1p не существует.',
 'approved','original_iclub',true,encode(digest(convert_to('Первый главный энергетический уровень n = 1 содержит только подуровень 1s и поэтому только одну орбиталь. Эта орбиталь может вместить максимум два электрона. Орбиталей 1p не существует.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1939:uz:v1','chemistry',1939,'Electrons in atoms','First energy level',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Birinchi energetik qavat','Birinchi asosiy energetik qavat n = 1 faqat 1s qavatchani va bitta orbitalni o‘z ichiga oladi. Bu orbital ko‘pi bilan ikki elektron sig‘diradi. 1p orbitallar mavjud emas.',
 'approved','original_iclub',true,encode(digest(convert_to('Birinchi asosiy energetik qavat n = 1 faqat 1s qavatchani va bitta orbitalni o‘z ichiga oladi. Bu orbital ko‘pi bilan ikki elektron sig‘diradi. 1p orbitallar mavjud emas.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1941:en:v1','chemistry',1941,'Electrons in atoms','Atomic radius trend down a group',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Atomic radius down a group','Atomic radius generally increases down a group because each successive element has an additional occupied electron shell. Greater distance and shielding outweigh the increase in nuclear charge for the outer electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('Atomic radius generally increases down a group because each successive element has an additional occupied electron shell. Greater distance and shielding outweigh the increase in nuclear charge for the outer electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1941:ru:v1','chemistry',1941,'Electrons in atoms','Atomic radius trend down a group',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Атомный радиус вниз по группе','Атомный радиус в целом увеличивается вниз по группе, потому что у каждого следующего элемента появляется дополнительная занятая электронная оболочка. Увеличение расстояния и экранирования для внешних электронов перевешивает рост заряда ядра.',
 'approved','original_iclub',true,encode(digest(convert_to('Атомный радиус в целом увеличивается вниз по группе, потому что у каждого следующего элемента появляется дополнительная занятая электронная оболочка. Увеличение расстояния и экранирования для внешних электронов перевешивает рост заряда ядра.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1941:uz:v1','chemistry',1941,'Electrons in atoms','Atomic radius trend down a group',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Guruh bo‘ylab atom radiusi','Atom radiusi guruh bo‘ylab pastga odatda ortadi, chunki har bir keyingi elementda qo‘shimcha band elektron qavati paydo bo‘ladi. Tashqi elektronlar uchun masofa va ekranlanishning ortishi yadro zaryadi ortishidan ustun keladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Atom radiusi guruh bo‘ylab pastga odatda ortadi, chunki har bir keyingi elementda qo‘shimcha band elektron qavati paydo bo‘ladi. Tashqi elektronlar uchun masofa va ekranlanishning ortishi yadro zaryadi ortishidan ustun keladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1945:en:v1','chemistry',1945,'Electrons in atoms','Electron configuration of magnesium',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Electron configuration of magnesium','Magnesium has atomic number 12, so a neutral Mg atom has 12 electrons. Filling orbitals in increasing energy order gives 1s2 2s2 2p6 3s2.',
 'approved','original_iclub',true,encode(digest(convert_to('Magnesium has atomic number 12, so a neutral Mg atom has 12 electrons. Filling orbitals in increasing energy order gives 1s2 2s2 2p6 3s2.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1945:ru:v1','chemistry',1945,'Electrons in atoms','Electron configuration of magnesium',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Электронная конфигурация магния','Магний имеет атомный номер 12, поэтому нейтральный атом Mg содержит 12 электронов. При заполнении орбиталей в порядке возрастания энергии получается 1s2 2s2 2p6 3s2.',
 'approved','original_iclub',true,encode(digest(convert_to('Магний имеет атомный номер 12, поэтому нейтральный атом Mg содержит 12 электронов. При заполнении орбиталей в порядке возрастания энергии получается 1s2 2s2 2p6 3s2.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1945:uz:v1','chemistry',1945,'Electrons in atoms','Electron configuration of magnesium',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Magniyning elektron konfiguratsiyasi','Magniyning atom raqami 12, shuning uchun neytral Mg atomida 12 elektron bor. Orbitallar energiya ortib borish tartibida to‘ldirilganda 1s2 2s2 2p6 3s2 konfiguratsiya hosil bo‘ladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Magniyning atom raqami 12, shuning uchun neytral Mg atomida 12 elektron bor. Orbitallar energiya ortib borish tartibida to‘ldirilganda 1s2 2s2 2p6 3s2 konfiguratsiya hosil bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1953:en:v1','chemistry',1953,'Electrons in atoms','Ionisation energy down a group',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Ionisation energy down a group','First ionisation energy generally decreases down a group. The outer electron is farther from the nucleus and more strongly shielded by inner shells, so the attractive force holding it is weaker despite the higher nuclear charge.',
 'approved','original_iclub',true,encode(digest(convert_to('First ionisation energy generally decreases down a group. The outer electron is farther from the nucleus and more strongly shielded by inner shells, so the attractive force holding it is weaker despite the higher nuclear charge.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1953:ru:v1','chemistry',1953,'Electrons in atoms','Ionisation energy down a group',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Энергия ионизации вниз по группе','Первая энергия ионизации в целом уменьшается вниз по группе. Внешний электрон находится дальше от ядра и сильнее экранирован внутренними оболочками, поэтому удерживающее его притяжение слабее несмотря на больший заряд ядра.',
 'approved','original_iclub',true,encode(digest(convert_to('Первая энергия ионизации в целом уменьшается вниз по группе. Внешний электрон находится дальше от ядра и сильнее экранирован внутренними оболочками, поэтому удерживающее его притяжение слабее несмотря на больший заряд ядра.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1953:uz:v1','chemistry',1953,'Electrons in atoms','Ionisation energy down a group',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Guruh bo‘ylab ionlanish energiyasi','Birinchi ionlanish energiyasi guruh bo‘ylab pastga odatda kamayadi. Tashqi elektron yadrodan uzoqroq va ichki qavatlar tomonidan kuchliroq ekranlangan bo‘ladi, shu sababli yadro zaryadi kattaroq bo‘lsa ham uni ushlab turuvchi tortish kuchi zaiflashadi.',
 'approved','original_iclub',true,encode(digest(convert_to('Birinchi ionlanish energiyasi guruh bo‘ylab pastga odatda kamayadi. Tashqi elektron yadrodan uzoqroq va ichki qavatlar tomonidan kuchliroq ekranlangan bo‘ladi, shu sababli yadro zaryadi kattaroq bo‘lsa ham uni ushlab turuvchi tortish kuchi zaiflashadi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1956:en:v1','chemistry',1956,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Why atomic radius decreases across a period','Across a period, proton number increases while electrons are added to the same main energy level. Shielding therefore changes relatively little, effective nuclear charge increases, and the electron cloud is pulled closer to the nucleus.',
 'approved','original_iclub',true,encode(digest(convert_to('Across a period, proton number increases while electrons are added to the same main energy level. Shielding therefore changes relatively little, effective nuclear charge increases, and the electron cloud is pulled closer to the nucleus.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1956:ru:v1','chemistry',1956,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Почему атомный радиус уменьшается в периоде','В периоде число протонов увеличивается, а электроны добавляются на тот же основной энергетический уровень. Поэтому экранирование меняется относительно мало, эффективный заряд ядра возрастает, и электронное облако сильнее притягивается к ядру.',
 'approved','original_iclub',true,encode(digest(convert_to('В периоде число протонов увеличивается, а электроны добавляются на тот же основной энергетический уровень. Поэтому экранирование меняется относительно мало, эффективный заряд ядра возрастает, и электронное облако сильнее притягивается к ядру.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1956:uz:v1','chemistry',1956,'Electrons in atoms','Atomic radius across a period',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Nega davr bo‘ylab atom radiusi kamayadi','Davr bo‘ylab protonlar soni ortadi, elektronlar esa bir xil asosiy energetik qavatga qo‘shiladi. Shuning uchun ekranlanish nisbatan kam o‘zgaradi, effektiv yadro zaryadi ortadi va elektron buluti yadroga kuchliroq tortiladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Davr bo‘ylab protonlar soni ortadi, elektronlar esa bir xil asosiy energetik qavatga qo‘shiladi. Shuning uchun ekranlanish nisbatan kam o‘zgaradi, effektiv yadro zaryadi ortadi va elektron buluti yadroga kuchliroq tortiladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1960:en:v1','chemistry',1960,'Electrons in atoms','Electron capacity of the p subshell',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Capacity of a p subshell','A p subshell contains three orbitals. Since each orbital can hold a maximum of two electrons with opposite spins, a p subshell can hold up to 6 electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('A p subshell contains three orbitals. Since each orbital can hold a maximum of two electrons with opposite spins, a p subshell can hold up to 6 electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1960:ru:v1','chemistry',1960,'Electrons in atoms','Electron capacity of the p subshell',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Вместимость p-подуровня','p-подуровень содержит три орбитали. Поскольку каждая орбиталь может вместить максимум два электрона с противоположными спинами, p-подуровень вмещает до 6 электронов.',
 'approved','original_iclub',true,encode(digest(convert_to('p-подуровень содержит три орбитали. Поскольку каждая орбиталь может вместить максимум два электрона с противоположными спинами, p-подуровень вмещает до 6 электронов.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1960:uz:v1','chemistry',1960,'Electrons in atoms','Electron capacity of the p subshell',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','p-qavatchaning sig‘imi','p-qavatchada uchta orbital bor. Har bir orbital qarama-qarshi spinli ko‘pi bilan ikki elektron sig‘dirgani uchun p-qavatcha jami 6 elektron sig‘dira oladi.',
 'approved','original_iclub',true,encode(digest(convert_to('p-qavatchada uchta orbital bor. Har bir orbital qarama-qarshi spinli ko‘pi bilan ikki elektron sig‘dirgani uchun p-qavatcha jami 6 elektron sig‘dira oladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1962:en:v1','chemistry',1962,'Electrons in atoms','Energy levels in the same period',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Periods and occupied energy levels','Elements in the same period have electrons occupying the same number of principal energy levels in their ground-state atoms. The period number corresponds to the highest occupied principal shell for main-group elements.',
 'approved','original_iclub',true,encode(digest(convert_to('Elements in the same period have electrons occupying the same number of principal energy levels in their ground-state atoms. The period number corresponds to the highest occupied principal shell for main-group elements.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1962:ru:v1','chemistry',1962,'Electrons in atoms','Energy levels in the same period',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Периоды и занятые энергетические уровни','У элементов одного периода в основном состоянии занято одинаковое число главных энергетических уровней. Для элементов главных подгрупп номер периода соответствует наивысшей занятой главной оболочке.',
 'approved','original_iclub',true,encode(digest(convert_to('У элементов одного периода в основном состоянии занято одинаковое число главных энергетических уровней. Для элементов главных подгрупп номер периода соответствует наивысшей занятой главной оболочке.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1962:uz:v1','chemistry',1962,'Electrons in atoms','Energy levels in the same period',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Davrlar va band energetik qavatlar','Bir davrdagi elementlarning asosiy holatdagi atomlarida band asosiy energetik qavatlar soni bir xil bo‘ladi. Asosiy guruh elementlarida davr raqami eng yuqori band asosiy qavatga mos keladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Bir davrdagi elementlarning asosiy holatdagi atomlarida band asosiy energetik qavatlar soni bir xil bo‘ladi. Asosiy guruh elementlarida davr raqami eng yuqori band asosiy qavatga mos keladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1968:en:v1','chemistry',1968,'Electrons in atoms','First ionisation energy across a period',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','First ionisation energy across a period','First ionisation energy generally increases across a period because nuclear charge increases while shielding changes relatively little and atomic radius decreases. There can be small exceptions caused by subshell energies and electron pairing, so the trend is general rather than perfectly smooth.',
 'approved','original_iclub',true,encode(digest(convert_to('First ionisation energy generally increases across a period because nuclear charge increases while shielding changes relatively little and atomic radius decreases. There can be small exceptions caused by subshell energies and electron pairing, so the trend is general rather than perfectly smooth.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1968:ru:v1','chemistry',1968,'Electrons in atoms','First ionisation energy across a period',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Первая энергия ионизации в периоде','Первая энергия ионизации в целом увеличивается в периоде, потому что заряд ядра растёт, экранирование меняется относительно мало, а атомный радиус уменьшается. Возможны небольшие исключения из-за энергий подуровней и спаривания электронов, поэтому тенденция общая, а не идеально плавная.',
 'approved','original_iclub',true,encode(digest(convert_to('Первая энергия ионизации в целом увеличивается в периоде, потому что заряд ядра растёт, экранирование меняется относительно мало, а атомный радиус уменьшается. Возможны небольшие исключения из-за энергий подуровней и спаривания электронов, поэтому тенденция общая, а не идеально плавная.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1968:uz:v1','chemistry',1968,'Electrons in atoms','First ionisation energy across a period',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Davr bo‘ylab birinchi ionlanish energiyasi','Birinchi ionlanish energiyasi davr bo‘ylab odatda ortadi, chunki yadro zaryadi oshadi, ekranlanish nisbatan kam o‘zgaradi va atom radiusi kamayadi. Qavatcha energiyasi hamda elektron juftlanishi sabab kichik istisnolar bo‘lishi mumkin, shuning uchun bu umumiy tendensiya.',
 'approved','original_iclub',true,encode(digest(convert_to('Birinchi ionlanish energiyasi davr bo‘ylab odatda ortadi, chunki yadro zaryadi oshadi, ekranlanish nisbatan kam o‘zgaradi va atom radiusi kamayadi. Qavatcha energiyasi hamda elektron juftlanishi sabab kichik istisnolar bo‘lishi mumkin, shuning uchun bu umumiy tendensiya.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1971:en:v1','chemistry',1971,'Electrons in atoms','Valence electrons and group properties',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Valence electrons and chemical reactivity','Valence electrons are the outer electrons involved most directly in bond formation and chemical reactions. Elements in the same group have similar valence-electron arrangements, which is why they often show similar patterns of chemical reactivity.',
 'approved','original_iclub',true,encode(digest(convert_to('Valence electrons are the outer electrons involved most directly in bond formation and chemical reactions. Elements in the same group have similar valence-electron arrangements, which is why they often show similar patterns of chemical reactivity.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1971:ru:v1','chemistry',1971,'Electrons in atoms','Valence electrons and group properties',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Валентные электроны и химическая активность','Валентные электроны — внешние электроны, непосредственно участвующие в образовании связей и химических реакциях. Элементы одной группы имеют сходное расположение валентных электронов, поэтому часто проявляют сходную химическую активность.',
 'approved','original_iclub',true,encode(digest(convert_to('Валентные электроны — внешние электроны, непосредственно участвующие в образовании связей и химических реакциях. Элементы одной группы имеют сходное расположение валентных электронов, поэтому часто проявляют сходную химическую активность.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1971:uz:v1','chemistry',1971,'Electrons in atoms','Valence electrons and group properties',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Valent elektronlar va kimyoviy faollik','Valent elektronlar bog‘ hosil bo‘lishi va kimyoviy reaksiyalarda eng bevosita qatnashadigan tashqi elektronlardir. Bir guruh elementlarida valent elektronlar tuzilishi o‘xshash bo‘lgani uchun ularning kimyoviy faolligi ham ko‘pincha o‘xshash bo‘ladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Valent elektronlar bog‘ hosil bo‘lishi va kimyoviy reaksiyalarda eng bevosita qatnashadigan tashqi elektronlardir. Bir guruh elementlarida valent elektronlar tuzilishi o‘xshash bo‘lgani uchun ularning kimyoviy faolligi ham ko‘pincha o‘xshash bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3036:en:v1','chemistry',3036,'Electrons in atoms','Capacity of the p sub-shell',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Capacity of the 3p subshell','The 3p subshell contains three p orbitals. Each orbital can hold two electrons, so the maximum occupancy of 3p is 6 electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('The 3p subshell contains three p orbitals. Each orbital can hold two electrons, so the maximum occupancy of 3p is 6 electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3036:ru:v1','chemistry',3036,'Electrons in atoms','Capacity of the p sub-shell',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Вместимость подуровня 3p','Подуровень 3p содержит три p-орбитали. Каждая орбиталь может вместить два электрона, поэтому максимальная вместимость 3p равна 6 электронам.',
 'approved','original_iclub',true,encode(digest(convert_to('Подуровень 3p содержит три p-орбитали. Каждая орбиталь может вместить два электрона, поэтому максимальная вместимость 3p равна 6 электронам.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3036:uz:v1','chemistry',3036,'Electrons in atoms','Capacity of the p sub-shell',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','3p qavatchaning sig‘imi','3p qavatchada uchta p-orbital mavjud. Har bir orbital ikki elektron sig‘diradi, shuning uchun 3p ning maksimal sig‘imi 6 elektron.',
 'approved','original_iclub',true,encode(digest(convert_to('3p qavatchada uchta p-orbital mavjud. Har bir orbital ikki elektron sig‘diradi, shuning uchun 3p ning maksimal sig‘imi 6 elektron.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3037:en:v1','chemistry',3037,'Electrons in atoms','Electron configuration of aluminium',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Electron configuration of aluminium','Aluminium has atomic number 13, so a neutral atom has 13 electrons. Filling orbitals in increasing energy order gives 1s2 2s2 2p6 3s2 3p1.',
 'approved','original_iclub',true,encode(digest(convert_to('Aluminium has atomic number 13, so a neutral atom has 13 electrons. Filling orbitals in increasing energy order gives 1s2 2s2 2p6 3s2 3p1.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3037:ru:v1','chemistry',3037,'Electrons in atoms','Electron configuration of aluminium',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Электронная конфигурация алюминия','Алюминий имеет атомный номер 13, поэтому нейтральный атом содержит 13 электронов. При заполнении орбиталей в порядке возрастания энергии получается 1s2 2s2 2p6 3s2 3p1.',
 'approved','original_iclub',true,encode(digest(convert_to('Алюминий имеет атомный номер 13, поэтому нейтральный атом содержит 13 электронов. При заполнении орбиталей в порядке возрастания энергии получается 1s2 2s2 2p6 3s2 3p1.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3037:uz:v1','chemistry',3037,'Electrons in atoms','Electron configuration of aluminium',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Alyuminiyning elektron konfiguratsiyasi','Alyuminiyning atom raqami 13, shuning uchun neytral atomda 13 elektron bor. Orbitallar energiya ortib borish tartibida to‘ldirilganda 1s2 2s2 2p6 3s2 3p1 konfiguratsiya hosil bo‘ladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Alyuminiyning atom raqami 13, shuning uchun neytral atomda 13 elektron bor. Orbitallar energiya ortib borish tartibida to‘ldirilganda 1s2 2s2 2p6 3s2 3p1 konfiguratsiya hosil bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3039:en:v1','chemistry',3039,'Electrons in atoms','First ionisation energy across Period 3',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','First ionisation energy across Period 3','Across Period 3, nuclear charge increases while electrons are added to the same principal shell and shielding remains broadly similar. Effective attraction to the outer electron therefore generally increases, so first ionisation energy tends to rise, with small known exceptions.',
 'approved','original_iclub',true,encode(digest(convert_to('Across Period 3, nuclear charge increases while electrons are added to the same principal shell and shielding remains broadly similar. Effective attraction to the outer electron therefore generally increases, so first ionisation energy tends to rise, with small known exceptions.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3039:ru:v1','chemistry',3039,'Electrons in atoms','First ionisation energy across Period 3',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Первая энергия ионизации в третьем периоде','В третьем периоде заряд ядра увеличивается, а электроны добавляются на тот же главный уровень, при этом экранирование остаётся примерно сходным. Эффективное притяжение внешнего электрона в целом усиливается, поэтому первая энергия ионизации обычно возрастает, хотя есть небольшие известные исключения.',
 'approved','original_iclub',true,encode(digest(convert_to('В третьем периоде заряд ядра увеличивается, а электроны добавляются на тот же главный уровень, при этом экранирование остаётся примерно сходным. Эффективное притяжение внешнего электрона в целом усиливается, поэтому первая энергия ионизации обычно возрастает, хотя есть небольшие известные исключения.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3039:uz:v1','chemistry',3039,'Electrons in atoms','First ionisation energy across Period 3',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','3-davr bo‘ylab birinchi ionlanish energiyasi','3-davr bo‘ylab yadro zaryadi ortadi, elektronlar esa bir xil asosiy qavatga qo‘shiladi va ekranlanish taxminan o‘xshash qoladi. Tashqi elektronning effektiv tortilishi odatda kuchayadi, shuning uchun birinchi ionlanish energiyasi umumiy holda ortadi, ayrim kichik istisnolar mavjud.',
 'approved','original_iclub',true,encode(digest(convert_to('3-davr bo‘ylab yadro zaryadi ortadi, elektronlar esa bir xil asosiy qavatga qo‘shiladi va ekranlanish taxminan o‘xshash qoladi. Tashqi elektronning effektiv tortilishi odatda kuchayadi, shuning uchun birinchi ionlanish energiyasi umumiy holda ortadi, ayrim kichik istisnolar mavjud.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3046:en:v1','chemistry',3046,'Electrons in atoms','Large jump in successive ionisation energies',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Large jumps in successive ionisation energies','A very large jump after removing a certain number of electrons means the next electron is being removed from an inner shell. A large jump between the second and third ionisation energies therefore indicates two valence electrons, characteristic of a Group 2 element such as magnesium.',
 'approved','original_iclub',true,encode(digest(convert_to('A very large jump after removing a certain number of electrons means the next electron is being removed from an inner shell. A large jump between the second and third ionisation energies therefore indicates two valence electrons, characteristic of a Group 2 element such as magnesium.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3046:ru:v1','chemistry',3046,'Electrons in atoms','Large jump in successive ionisation energies',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Большой скачок последовательных энергий ионизации','Очень большой скачок после удаления определённого числа электронов означает, что следующий электрон уже удаляется с внутренней оболочки. Поэтому большой скачок между второй и третьей энергиями ионизации указывает на два валентных электрона, что характерно для элемента группы 2, например магния.',
 'approved','original_iclub',true,encode(digest(convert_to('Очень большой скачок после удаления определённого числа электронов означает, что следующий электрон уже удаляется с внутренней оболочки. Поэтому большой скачок между второй и третьей энергиями ионизации указывает на два валентных электрона, что характерно для элемента группы 2, например магния.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3046:uz:v1','chemistry',3046,'Electrons in atoms','Large jump in successive ionisation energies',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_electrons_precise_v1_2026_09_25','Ketma-ket ionlanish energiyalaridagi katta sakrash','Ma’lum son elektron chiqarilgandan keyingi juda katta sakrash navbatdagi elektron ichki qavatdan olinayotganini bildiradi. Ikkinchi va uchinchi ionlanish energiyalari orasidagi katta sakrash ikki valent elektronni ko‘rsatadi, bu magniy kabi 2-guruh elementiga xos.',
 'approved','original_iclub',true,encode(digest(convert_to('Ma’lum son elektron chiqarilgandan keyingi juda katta sakrash navbatdagi elektron ichki qavatdan olinayotganini bildiradi. Ikkinchi va uchinchi ionlanish energiyalari orasidagi katta sakrash ikki valent elektronni ko‘rsatadi, bu magniy kabi 2-guruh elementiga xos.','UTF8'),'sha256'),'hex'),now(),now())
on conflict(source_card_key) do update
set subject_key=excluded.subject_key,
    question_id=excluded.question_id,
    topic=excluded.topic,
    subtopic=excluded.subtopic,
    card_type=excluded.card_type,
    locale=excluded.locale,
    source_version=excluded.source_version,
    title=excluded.title,
    body_text=excluded.body_text,
    approval_status=excluded.approval_status,
    rights_status=excluded.rights_status,
    is_runtime_allowed=excluded.is_runtime_allowed,
    content_hash=excluded.content_hash,
    approved_at=coalesce(private.practice_ai_source_cards.approved_at,excluded.approved_at),
    updated_at=now();
