-- P1-02 P5 AW13-16 Probability closure: PRO-05 conditional probability, PRO-06 probability trees.
-- Original iClub content only; governed publication; legacy questions remain draft + inactive.

begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw13_16_probability_v1','P5','P5 AW13-16 Conditional probability + trees','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1' and component_code='P5' and status='draft'), src(skill,k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P5-PRO-05','P5PRO05-D01','diagnostic','medium','Given P(A∩B)=0.12 and P(A)=0.30, find P(B|A).','Дано P(A∩B)=0,12 и P(A)=0,30. Найдите P(B|A).','P(A∩B)=0.12 va P(A)=0.30. P(B|A) ni toping.','["0.40","0.036","0.18","2.50"]','A','P(B|A)=P(A∩B)/P(A)=0.12/0.30=0.40.','P(B|A)=0,12/0,30=0,40.','P(B|A)=0.12/0.30=0.40.',55),
('P5-PRO-05','P5PRO05-L01','learning','easy','P(A)=0.6 and P(B|A)=0.5. Find P(A∩B).','P(A)=0,6 и P(B|A)=0,5. Найдите P(A∩B).','P(A)=0.6 va P(B|A)=0.5. P(A∩B) ni toping.','["0.30","1.10","0.10","0.55"]','A','P(A∩B)=P(A)P(B|A)=0.6×0.5=0.30.','P(A∩B)=0,6×0,5=0,30.','P(A∩B)=0.6×0.5=0.30.',45),
('P5-PRO-05','P5PRO05-L02','learning','medium','P(A)=0.4, P(B)=0.5 and P(A∩B)=0.10. Find P(A|B).','P(A)=0,4, P(B)=0,5 и P(A∩B)=0,10. Найдите P(A|B).','P(A)=0.4, P(B)=0.5 va P(A∩B)=0.10. P(A|B) ni toping.','["0.20","0.25","0.50","0.90"]','A','P(A|B)=0.10/0.50=0.20.','P(A|B)=0,10/0,50=0,20.','P(A|B)=0.10/0.50=0.20.',50),
('P5-PRO-05','P5PRO05-L03','learning','medium','A bag has 3 red and 2 blue counters. One counter is drawn and is known to be red. Without replacement, what is the probability the second counter is red?','В мешке 3 красных и 2 синих фишки. Первая фишка оказалась красной. Без возвращения какова вероятность, что вторая тоже красная?','Xaltada 3 qizil va 2 ko‘k chip bor. Birinchi chip qizil ekani ma’lum. Qaytarmasdan ikkinchi chip ham qizil bo‘lish ehtimoli?','["1/2","3/5","2/5","1/3"]','A','After a red is removed, 2 red remain among 4 counters, so the conditional probability is 2/4=1/2.','После удаления красной остаётся 2 красных из 4, вероятность 1/2.','Bitta qizil olingach, 4 chipdan 2 tasi qizil qoladi: 1/2.',55),
('P5-PRO-05','P5PRO05-R01','retest','easy','P(A∩B)=0.18 and P(B)=0.60. Find P(A|B).','P(A∩B)=0,18 и P(B)=0,60. Найдите P(A|B).','P(A∩B)=0.18 va P(B)=0.60. P(A|B) ni toping.','["0.30","0.108","0.42","3.33"]','A','0.18/0.60=0.30.','0,18/0,60=0,30.','0.18/0.60=0.30.',40),
('P5-PRO-05','P5PRO05-R02','retest','medium','P(A|B)=0.25 and P(B)=0.8. Find P(A∩B).','P(A|B)=0,25 и P(B)=0,8. Найдите P(A∩B).','P(A|B)=0.25 va P(B)=0.8. P(A∩B) ni toping.','["0.20","0.3125","1.05","0.55"]','A','P(A∩B)=0.25×0.8=0.20.','P(A∩B)=0,25×0,8=0,20.','P(A∩B)=0.25×0.8=0.20.',45),
('P5-PRO-05','P5PRO05-M01','mixed','medium','P(A)=0.5, P(B)=0.4 and P(A∩B)=0.15. Find P(B|A).','P(A)=0,5, P(B)=0,4 и P(A∩B)=0,15. Найдите P(B|A).','P(A)=0.5, P(B)=0.4 va P(A∩B)=0.15. P(B|A) ni toping.','["0.30","0.375","0.75","0.20"]','A','P(B|A)=0.15/0.5=0.30.','P(B|A)=0,15/0,5=0,30.','P(B|A)=0.15/0.5=0.30.',50),

('P5-PRO-06','P5PRO06-D01','diagnostic','medium','A bag contains 4 red and 3 blue counters. Two counters are drawn without replacement. Find P(red then blue).','В мешке 4 красных и 3 синих фишки. Без возвращения вытягивают две. Найдите P(красная, затем синяя).','Xaltada 4 qizil va 3 ko‘k chip bor. Qaytarmasdan ikkita olinadi. P(qizil, keyin ko‘k) ni toping.','["2/7","12/49","4/7","1/2"]','A','P(R then B)=4/7×3/6=12/42=2/7.','P(R, затем B)=4/7×3/6=2/7.','P(R, keyin B)=4/7×3/6=2/7.',65),
('P5-PRO-06','P5PRO06-L01','learning','easy','Two independent trials each have success probability 0.6. What is the probability of two successes?','Два независимых испытания имеют вероятность успеха 0,6 каждое. Какова вероятность двух успехов?','Ikki mustaqil sinovning har birida muvaffaqiyat ehtimoli 0.6. Ikki muvaffaqiyat ehtimoli?','["0.36","1.20","0.60","0.24"]','A','Multiply along the tree branch: 0.6×0.6=0.36.','Перемножаем вероятности вдоль ветви: 0,6×0,6=0,36.','Daraxt shoxida ko‘paytiramiz: 0.6×0.6=0.36.',40),
('P5-PRO-06','P5PRO06-L02','learning','medium','A process starts with route A with probability 0.3 and route B with probability 0.7. Success probabilities are 0.8 after A and 0.4 after B. Find the overall probability of success.','Процесс выбирает путь A с вероятностью 0,3 и B с вероятностью 0,7. Вероятность успеха после A равна 0,8, после B — 0,4. Найдите общую вероятность успеха.','Jarayon A yo‘lini 0.3, B yo‘lini 0.7 ehtimol bilan tanlaydi. A dan keyin muvaffaqiyat 0.8, B dan keyin 0.4. Umumiy muvaffaqiyat ehtimolini toping.','["0.52","0.12","0.56","0.80"]','A','Add the two success branches: 0.3×0.8 + 0.7×0.4 = 0.24+0.28=0.52.','Складываем две успешные ветви: 0,3×0,8+0,7×0,4=0,52.','Ikki muvaffaqiyat shoxini qo‘shamiz: 0.3×0.8+0.7×0.4=0.52.',75),
('P5-PRO-06','P5PRO06-L03','learning','medium','A bag contains 5 white and 3 black balls. Two are drawn without replacement. Find the probability both are white.','В мешке 5 белых и 3 чёрных шара. Два шара выбирают без возвращения. Найдите вероятность, что оба белые.','Xaltada 5 oq va 3 qora shar bor. Qaytarmasdan 2 shar olinadi. Ikkalasi ham oq bo‘lish ehtimoli?','["5/14","25/64","5/8","1/2"]','A','5/8×4/7=20/56=5/14.','5/8×4/7=5/14.','5/8×4/7=5/14.',55),
('P5-PRO-06','P5PRO06-R01','retest','easy','A fair coin is tossed and then a fair die is rolled. Find P(head then 6).','Подбрасывают честную монету, затем честный кубик. Найдите P(орёл, затем 6).','Adolatli tanga, keyin kubik tashlanadi. P(gerb, keyin 6) ni toping.','["1/12","1/8","1/6","1/2"]','A','1/2×1/6=1/12.','1/2×1/6=1/12.','1/2×1/6=1/12.',40),
('P5-PRO-06','P5PRO06-R02','retest','medium','A bag contains 2 red and 3 blue counters. Two are drawn without replacement. Find P(blue then red).','В мешке 2 красных и 3 синих фишки. Две выбирают без возвращения. Найдите P(синяя, затем красная).','Xaltada 2 qizil va 3 ko‘k chip bor. Qaytarmasdan 2 ta olinadi. P(ko‘k, keyin qizil) ni toping.','["3/10","6/25","2/5","1/5"]','A','3/5×2/4=6/20=3/10.','3/5×2/4=3/10.','3/5×2/4=3/10.',50),
('P5-PRO-06','P5PRO06-M01','mixed','hard','A bag has 3 red and 2 blue counters. Two are drawn without replacement. What is the probability of getting exactly one red counter?','В мешке 3 красных и 2 синих фишки. Без возвращения выбирают две. Какова вероятность получить ровно одну красную?','Xaltada 3 qizil va 2 ko‘k chip bor. Qaytarmasdan 2 ta olinadi. Aynan bitta qizil chiqish ehtimoli?','["3/5","3/10","2/5","1/2"]','A','Exactly one red can be R then B or B then R: 3/5×2/4 + 2/5×3/4 = 3/10+3/10=3/5.','Ровно одна красная: R→B или B→R. Сумма 3/10+3/10=3/5.','Aynan bitta qizil: R→B yoki B→R. 3/10+3/10=3/5.',80)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Probability',s.skill,s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw13_16_probability_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_probability_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1' and status='draft'), keys(skill,k,role) as (values
('P5-PRO-05','P5PRO05-D01','diagnostic'),('P5-PRO-05','P5PRO05-L01','learning'),('P5-PRO-05','P5PRO05-L02','learning'),('P5-PRO-05','P5PRO05-L03','learning'),('P5-PRO-05','P5PRO05-R01','retest'),('P5-PRO-05','P5PRO05-R02','retest'),('P5-PRO-05','P5PRO05-M01','mixed'),
('P5-PRO-06','P5PRO06-D01','diagnostic'),('P5-PRO-06','P5PRO06-L01','learning'),('P5-PRO-06','P5PRO06-L02','learning'),('P5-PRO-06','P5PRO06-L03','learning'),('P5-PRO-06','P5PRO06-R01','retest'),('P5-PRO-06','P5PRO06-R02','retest'),('P5-PRO-06','P5PRO06-M01','mixed')
)
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw13_16_probability_v1 from canonical skill intent.','Cambridge 9709 2026-2027 v4; P5 Probability','Complete Probability & Statistics 1; Probability (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_probability_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with rules(ckey,match,dcode,mtype,skill,fen,fru,fuz,nen,nru,nuz) as (values
('P5PRO05-D01','B','multiplied_instead_divided','method','P5-PRO-05','Conditional probability divides the intersection by the conditioning event; 0.12×0.30 is not the rule.','Условная вероятность делит пересечение на вероятность условия; умножение неверно.','Shartli ehtimolda kesishma shart hodisa ehtimoliga bo‘linadi; ko‘paytirish noto‘g‘ri.','Use P(B|A)=P(A∩B)/P(A).','Используйте P(B|A)=P(A∩B)/P(A).','P(B|A)=P(A∩B)/P(A) ni ishlating.'),
('P5PRO05-D01','C','subtracted_probabilities','concept','P5-PRO-05','Subtracting 0.12 from 0.30 does not define a conditional probability.','Вычитание 0,12 из 0,30 не является формулой условной вероятности.','0.30 dan 0.12 ni ayirish shartli ehtimol formulasi emas.','Identify the conditioning event in the denominator.','Определите событие-условие в знаменателе.','Maxrajdagi shart hodisani aniqlang.'),
('P5PRO05-D01','D','inverted_conditional_ratio','method','P5-PRO-05','The ratio was inverted. A conditional probability here must be at most 1; 2.5 is impossible.','Отношение перевёрнуто. Вероятность не может быть 2,5.','Nisbat teskarilangan. Ehtimol 2.5 bo‘lishi mumkin emas.','Put P(A∩B) in the numerator and P(A) in the denominator.','В числитель поставьте P(A∩B), в знаменатель P(A).','Suratga P(A∩B), maxrajga P(A) ni qo‘ying.'),
('P5PRO06-D01','B','failed_without_replacement_update','concept','P5-PRO-06','12/49 uses 4/7×3/7, as if the total stayed 7. Without replacement the second denominator is 6.','12/49 использует 4/7×3/7, как будто всего всё ещё 7. Без возвращения второй знаменатель 6.','12/49 da 4/7×3/7 ishlatilgan, go‘yo jami 7 qoladi. Qaytarmasdan ikkinchi maxraj 6.','Update both the total and the colour count after the first draw.','После первого выбора обновите и общее число, и количество цветов.','Birinchi tanlovdan keyin jami son va rang sonini yangilang.'),
('P5PRO06-D01','C','stopped_after_first_branch','method','P5-PRO-06','4/7 is only the probability of the first red draw; the blue second draw must also occur.','4/7 — только вероятность первой красной; нужно также учесть вторую синюю.','4/7 faqat birinchi qizil ehtimoli; ikkinchi ko‘k ham sodir bo‘lishi kerak.','Multiply probabilities along the complete branch.','Перемножайте вероятности по всей ветви.','To‘liq shox bo‘ylab ehtimollarni ko‘paytiring.'),
('P5PRO06-D01','D','informal_half_guess','concept','P5-PRO-06','The branch probabilities are not both 1/2. Use the actual bag composition.','Вероятности ветви не равны обе 1/2. Используйте состав мешка.','Shox ehtimollari ikkalasi ham 1/2 emas. Xalta tarkibini ishlating.','Write 4/7 for red first, then 3/6 for blue second.','Запишите 4/7 для первой красной и 3/6 для второй синей.','Avval qizil uchun 4/7, keyin ko‘k uchun 3/6 yozing.')
), meta as (select m.id,m.content_key from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw13_16_probability_v1' and m.reserve_role='diagnostic')
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,r.skill,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from rules r join meta on meta.content_key=r.ckey on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P5PRO05-W01','P5-PRO-05','Events A and B satisfy P(A)=0.45, P(B)=0.50 and P(A∩B)=0.18. (a) Find P(B|A). (b) Find P(A|B). (c) Test whether A and B are independent. Explain why the two conditional probabilities need not be equal.','Для событий A и B: P(A)=0,45, P(B)=0,50 и P(A∩B)=0,18. (a) Найдите P(B|A). (b) Найдите P(A|B). (c) Проверьте независимость. Объясните, почему две условные вероятности не обязаны совпадать.','A va B uchun P(A)=0.45, P(B)=0.50, P(A∩B)=0.18. (a) P(B|A) ni toping. (b) P(A|B) ni toping. (c) Mustaqillikni tekshiring. Nima uchun ikki shartli ehtimol teng bo‘lishi shart emasligini tushuntiring.','{"max_marks":10,"criteria":[{"id":"b_given_a","marks":2,"rule":"Finds 0.18/0.45=0.4."},{"id":"a_given_b","marks":2,"rule":"Finds 0.18/0.50=0.36."},{"id":"independence","marks":3,"rule":"Checks 0.45×0.50=0.225≠0.18 and concludes not independent."},{"id":"reasoning","marks":3,"rule":"Explains conditioning changes the denominator/sample space, so reversing the condition generally changes the value."}]}','Write the conditioning event in the denominator each time. Test independence separately using the product rule.','Каждый раз ставьте событие-условие в знаменатель. Независимость проверяйте отдельно по правилу произведения.','Har safar shart hodisani maxrajga qo‘ying. Mustaqillikni alohida ko‘paytma qoidasi bilan tekshiring.'),
('P5PRO06-W01','P5-PRO-06','A bag has 5 red and 3 blue counters. Two are drawn without replacement. (a) Draw or describe the two-stage probability tree. (b) Find P(two red). (c) Find P(exactly one red). (d) Find P(at least one blue). Explain which branches are multiplied and which branch totals are added.','В мешке 5 красных и 3 синих фишки. Две выбирают без возвращения. (a) Постройте или опишите дерево вероятностей. (b) Найдите P(две красные). (c) P(ровно одна красная). (d) P(хотя бы одна синяя). Объясните, где вероятности умножаются, а где складываются.','Xaltada 5 qizil va 3 ko‘k chip bor. Qaytarmasdan 2 ta olinadi. (a) Ikki bosqichli ehtimol daraxtini chizing yoki tasvirlang. (b) P(ikki qizil). (c) P(aynan bitta qizil). (d) P(kamida bitta ko‘k). Qaysi shoxlarda ko‘paytirish va qaysilarini qo‘shish kerakligini tushuntiring.','{"max_marks":10,"criteria":[{"id":"tree","marks":3,"rule":"Correct first-stage 5/8,3/8 and updated second-stage 4/7,3/7 or 5/7,2/7 branches."},{"id":"two_red","marks":2,"rule":"Finds 5/8×4/7=5/14."},{"id":"one_red","marks":2,"rule":"Adds R-B and B-R to get 15/28+15/56? Correct total 15/28? Specifically 5/8×3/7 + 3/8×5/7 =30/56=15/28."},{"id":"at_least_blue","marks":2,"rule":"Uses complement 1−5/14=9/14, equivalent to branches containing blue."},{"id":"reasoning","marks":1,"rule":"Explains multiply along a branch, add mutually exclusive complete branches."}]}','After the first draw, update the denominator to 7. For exactly one red, include both possible orders.','После первого выбора знаменатель становится 7. Для ровно одной красной учтите оба порядка.','Birinchi tanlovdan keyin maxraj 7 bo‘ladi. Aynan bitta qizil uchun ikkala tartibni hisoblang.')
)
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P5',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_aw13_16_probability_diagnostic','diagnostic','P5 AW13-16 conditional/tree diagnostic','Диагностика P5 AW13–16: условная вероятность/деревья','P5 AW13–16 conditional/tree diagnostikasi'),
('p5_pro05_learning','learning','Conditional probability learning','Условная вероятность','Shartli ehtimollik'),
('p5_pro06_learning','learning','Probability trees learning','Деревья вероятностей','Ehtimol daraxtlari'),
('p5_pro05_retest','retest','Conditional probability delayed retest','Отложенный ретест: условная вероятность','Kechiktirilgan retest: shartli ehtimol'),
('p5_pro06_retest','retest','Probability trees delayed retest','Отложенный ретест: деревья','Kechiktirilgan retest: daraxtlar'),
('p5_aw13_16_probability_mixed','mixed','P5 AW13-16 probability mixed transfer','Смешанный перенос P5 AW13–16: вероятность','P5 AW13–16 probability mixed transfer')
)
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p5_aw13_16_probability_diagnostic',1,'P5PRO05-D01',null,'P5-PRO-05','diagnostic',true),('p5_aw13_16_probability_diagnostic',2,'P5PRO06-D01',null,'P5-PRO-06','diagnostic',true),
('p5_pro05_learning',1,'P5PRO05-L01',null,'P5-PRO-05','learning',false),('p5_pro05_learning',2,'P5PRO05-L02',null,'P5-PRO-05','learning',false),('p5_pro05_learning',3,'P5PRO05-L03',null,'P5-PRO-05','learning',false),('p5_pro05_learning',4,null,'P5PRO05-W01','P5-PRO-05','written',false),
('p5_pro06_learning',1,'P5PRO06-L01',null,'P5-PRO-06','learning',false),('p5_pro06_learning',2,'P5PRO06-L02',null,'P5-PRO-06','learning',false),('p5_pro06_learning',3,'P5PRO06-L03',null,'P5-PRO-06','learning',false),('p5_pro06_learning',4,null,'P5PRO06-W01','P5-PRO-06','written',false),
('p5_pro05_retest',1,'P5PRO05-R01',null,'P5-PRO-05','retest',true),('p5_pro06_retest',1,'P5PRO06-R01',null,'P5-PRO-06','retest',true),
('p5_aw13_16_probability_mixed',1,'P5PRO05-M01',null,'P5-PRO-05','mixed',true),('p5_aw13_16_probability_mixed',2,'P5PRO06-M01',null,'P5-PRO-06','mixed',true)
)
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

do $$ declare v_id bigint; v_skill text; v_bad int; begin
select id into v_id from private.exam_prep_content_versions where content_version='p5_aw13_16_probability_v1' and status='draft'; if v_id is null then raise exception 'P5 AW13 probability draft missing'; end if;
if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id)<>14 then raise exception 'P5 AW13 probability expected 14 questions'; end if;
foreach v_skill in array array['P5-PRO-05','P5-PRO-06'] loop
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='diagnostic')<>1 then raise exception '% diagnostic floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='learning')<>3 then raise exception '% learning floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='retest')<>2 then raise exception '% retest floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='mixed')<>1 then raise exception '% mixed floor',v_skill; end if;
 if (select count(*) from private.exam_prep_written_tasks where content_version_id=v_id and primary_skill_code=v_skill and lifecycle_state='approved')<>1 then raise exception '% written floor',v_skill; end if;
end loop;
select count(*) into v_bad from (select m.id from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id left join private.exam_prep_diagnostic_rules r on r.content_meta_id=m.id and r.status='approved' and r.answer_kind='mcq_option' where m.content_version_id=v_id and m.reserve_role='diagnostic' group by m.id,q.correct_answer having count(r.id)<>3 or count(r.id) filter(where r.answer_match=q.correct_answer)<>0) x; if v_bad<>0 then raise exception 'P5 AW13 probability diagnostic failures=%',v_bad; end if;
if (select count(*) from private.exam_prep_question_content_meta m where m.content_version_id=v_id and m.reserve_role='retest' and not exists(select 1 from private.exam_prep_assessment_items i where i.question_id=m.question_id))<>2 then raise exception 'P5 AW13 probability expected 2 isolated R02 holdouts'; end if;
end $$;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_probability_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw13_16_probability_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_probability_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw13_16_probability_v1' and cv.status='approved' and w.lifecycle_state='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw13_16_probability_v1' and cv.status='approved' and a.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw13_16_probability_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; v_ready int; v_cfg private.exam_prep_feature_config%rowtype; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P5-PRO-05','P5-PRO-06'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P5',v_skill) then raise exception 'P5 AW13 probability final not ready=%',v_skill; end if; end loop;
select count(*) into v_ready from private.exam_prep_content_runway_release_skills rs join private.exam_prep_content_runway_releases r on r.id=rs.release_id where r.release_key='aw13_16_core_coverage_iii' and r.component_code='P5' and rs.required_for_release and private.exam_prep_skill_content_ready_v1(v_program,'P5',rs.skill_code); if v_ready<>2 then raise exception 'P5 AW13 probability expected ready=2 got=%',v_ready; end if;
select * into v_cfg from private.exam_prep_feature_config where id=1; if v_cfg.rollout_state<>'off' or v_cfg.core_enabled or v_cfg.ai_enabled or v_cfg.mentor_enabled or not v_cfg.kill_switch then raise exception 'P5 AW13 probability feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P5 AW13 probability entitlement residue'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw13_16_probability_v1:%' and is_active) then raise exception 'P5 AW13 probability legacy activation'; end if;
end $$;
commit;
