-- AI-4 Economics Practice 1 deterministic diagnostic batch: Chapter 8.
-- Adds deterministic diagnostics for six MCQs plus one numeric-input question.
-- Server scoring remains authoritative; these rows only explain an already-checked answer.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,topic,subtopic,qtype,correct_answer,options_en) as (
    values
    (1023,'Elasticity','Income elasticity and inferior goods','mcq','B','["Normal","Inferior","A luxury","A substitute"]'::jsonb),
    (1024,'Elasticity','Cross elasticity and substitutes','mcq','B','["Complements","Substitutes","Unrelated","Inferior goods"]'::jsonb),
    (1077,'Elasticity','Perfectly inelastic demand','mcq','A','["quantity demanded does not change when price changes","demand shifts with price","quantity changes a lot","price always falls"]'::jsonb),
    (1080,'Costs','Fixed cost','mcq','A','["factory rent","raw materials","piece-rate wages","electricity per unit"]'::jsonb),
    (1094,'Elasticity','Calculating PED','input','2',null::jsonb),
    (1127,'Elasticity','PED and total revenue','mcq','B','["Fall","Rise","Stay the same","Become zero"]'::jsonb),
    (1134,'Elasticity','Cross elasticity and substitutes','mcq','D','["Complements","Unrelated goods","Inferior goods","Substitutes"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>7
     or q.is_active is not true
     or q.quality_status<>'published'
     or lower(coalesce(q.qtype,''))<>e.qtype
     or q.topic<>e.topic
     or q.subtopic<>e.subtopic
     or upper(trim(coalesce(q.correct_answer,'')))<>upper(e.correct_answer)
     or (e.qtype='mcq' and coalesce(q.options_text_en,'[]')::jsonb is distinct from e.options_en)
     or (e.qtype='input' and q.options_text_en is not null);

  if v_bad<>0 then
    raise exception 'AI-4 diagnostic batch refused: one or more Chapter 8 questions changed';
  end if;

  if exists (
    select 1 from public.question_answer_diagnostics
    where question_id in (1023,1024,1077,1080,1094,1127,1134)
      and quality_status='published'
  ) then
    raise exception 'AI-4 diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1023,'mcq_option','A','Normal',false,'yed_sign_confusion','Normal vs inferior goods',
 'Для нормального блага спрос растёт при росте дохода. Здесь спрос падает, значит товар не является нормальным.',
 'Normal tovar uchun daromad oshganda talab oshadi. Bu yerda talab kamaymoqda, demak tovar normal emas.',
 'For a normal good, demand rises as income rises. Here demand falls, so the good is not normal.',
 'Сравните знак YED для нормальных и низших благ.',
 'Normal va past toifadagi tovarlar uchun YED ishorasini solishtiring.',
 'Compare the sign of YED for normal and inferior goods.',
 'Elasticity','Income elasticity and inferior goods','{}'::jsonb,'published'),
(1023,'mcq_option','B','Inferior',true,null,null,
 'Верно: у низшего блага спрос снижается при росте дохода, при прочих равных.',
 'To‘g‘ri: past toifadagi tovar uchun daromad oshganda talab kamayadi, boshqa shartlar o‘zgarmasa.',
 'Correct: for an inferior good, demand falls as income rises, ceteris paribus.',
 'Свяжите низшие блага с отрицательной YED.',
 'Past toifadagi tovarlarni manfiy YED bilan bog‘lang.',
 'Link inferior goods to negative YED.',
 'Elasticity','Income elasticity and inferior goods','{}'::jsonb,'published'),
(1023,'mcq_option','C','A luxury',false,'luxury_inferior_confusion','Luxury vs inferior goods',
 'Предмет роскоши обычно является нормальным благом с положительной реакцией спроса на рост дохода.',
 'Hashamat tovari odatda normal tovar bo‘lib, daromad oshganda talabi oshadi.',
 'A luxury good is normally a type of normal good whose demand rises with income.',
 'Различайте luxury good и inferior good по знаку YED.',
 'Luxury good bilan inferior goodni YED ishorasi bo‘yicha farqlang.',
 'Distinguish luxury goods from inferior goods using the sign of YED.',
 'Elasticity','Income elasticity and inferior goods','{}'::jsonb,'published'),
(1023,'mcq_option','D','A substitute',false,'yed_xed_confusion','Income elasticity vs cross elasticity',
 'Заменители определяются реакцией спроса на цену другого товара, а здесь меняется доход.',
 'O‘rinbosarlar boshqa tovar narxiga talab reaksiyasi bilan aniqlanadi, bu savolda esa daromad o‘zgaradi.',
 'Substitutes are identified from demand response to another good’s price, while this question changes income.',
 'Различайте YED и XED.',
 'YED va XEDni farqlang.',
 'Distinguish YED from XED.',
 'Elasticity','Income elasticity and inferior goods','{}'::jsonb,'published'),

(1024,'mcq_option','A','Complements',false,'xed_sign_confusion','Complements vs substitutes',
 'Для комплементов рост цены A обычно снижает спрос на B. Здесь спрос на B растёт, что указывает на заменители.',
 'Komplementlarda A narxi oshsa, odatda Bga talab kamayadi. Bu yerda Bga talab oshmoqda, demak ular o‘rinbosar.',
 'For complements, a rise in A’s price usually reduces demand for B. Here demand for B rises, indicating substitutes.',
 'Повторите знак XED для комплементов и заменителей.',
 'Komplement va o‘rinbosarlar uchun XED ishorasini takrorlang.',
 'Review the sign of XED for complements and substitutes.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1024,'mcq_option','B','Substitutes',true,null,null,
 'Верно: рост цены A повышает спрос на B, значит покупатели переключаются на B как на заменитель.',
 'To‘g‘ri: A narxi oshganda Bga talab oshadi, demak iste’molchilar Bga o‘rinbosar sifatida o‘tmoqda.',
 'Correct: when A’s price rises, demand for B rises, so consumers switch toward B as a substitute.',
 'Свяжите заменители с положительной XED.',
 'O‘rinbosarlarni ijobiy XED bilan bog‘lang.',
 'Link substitutes to positive XED.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1024,'mcq_option','C','Unrelated',false,'relationship_ignored','Cross-price relationship',
 'Спрос на B систематически реагирует на цену A, поэтому товары не выглядят несвязанными.',
 'Bga talab A narxiga tizimli javob bermoqda, shuning uchun tovarlar bog‘liq emas deb bo‘lmaydi.',
 'Demand for B responds systematically to A’s price, so the goods do not appear unrelated.',
 'Следите за направлением перекрёстной реакции спроса.',
 'Talabning o‘zaro reaksiyasi yo‘nalishini kuzating.',
 'Track the direction of the cross-demand response.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1024,'mcq_option','D','Inferior goods',false,'yed_xed_confusion','Cross elasticity vs income elasticity',
 'Низшие блага определяются реакцией на доход, а не на цену другого товара.',
 'Past toifadagi tovarlar daromadga reaksiya bilan aniqlanadi, boshqa tovar narxi bilan emas.',
 'Inferior goods are classified by response to income, not to the price of another good.',
 'Разделяйте YED и XED.',
 'YED va XEDni ajrating.',
 'Separate YED from XED.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),

(1077,'mcq_option','A','quantity demanded does not change when price changes',true,null,null,
 'Верно: совершенно неэластичный спрос означает, что изменение цены не меняет объём спроса.',
 'To‘g‘ri: mutlaqo noelastik talab narx o‘zgarsa ham talab miqdori o‘zgarmasligini anglatadi.',
 'Correct: perfectly inelastic demand means quantity demanded does not change when price changes.',
 'Свяжите PED = 0 с вертикальной кривой спроса.',
 'PED = 0 ni vertikal talab egri chizig‘i bilan bog‘lang.',
 'Link PED = 0 to a vertical demand curve.',
 'Elasticity','Perfectly inelastic demand','{}'::jsonb,'published'),
(1077,'mcq_option','B','demand shifts with price',false,'movement_shift_confusion','Own-price movement vs demand shift',
 'Изменение собственной цены вызывает движение вдоль кривой, а не сдвиг спроса.',
 'Tovarning o‘z narxi o‘zgarishi talab egri chizig‘i bo‘ylab harakatni keltirib chiqaradi, siljishni emas.',
 'A change in the good’s own price causes movement along the curve, not a shift in demand.',
 'Различайте движение вдоль кривой и сдвиг спроса.',
 'Egri chiziq bo‘ylab harakat va talab siljishini farqlang.',
 'Distinguish movement along a curve from a demand shift.',
 'Elasticity','Perfectly inelastic demand','{}'::jsonb,'published'),
(1077,'mcq_option','C','quantity changes a lot',false,'elasticity_magnitude_reversal','Perfectly inelastic demand',
 'Большое изменение количества соответствует эластичному спросу, а не совершенно неэластичному.',
 'Miqdorning katta o‘zgarishi elastik talabga mos keladi, mutlaqo noelastik talabga emas.',
 'A large quantity response is associated with elastic demand, not perfectly inelastic demand.',
 'Сравните PED = 0 и высокий PED.',
 'PED = 0 bilan yuqori PEDni solishtiring.',
 'Compare PED = 0 with a high PED.',
 'Elasticity','Perfectly inelastic demand','{}'::jsonb,'published'),
(1077,'mcq_option','D','price always falls',false,'elasticity_definition_error','Meaning of perfectly inelastic demand',
 'Эластичность описывает реакцию количества на цену, а не направление, в котором цена обязана изменяться.',
 'Elastiklik miqdorning narxga reaksiyasini tasvirlaydi, narx har doim qaysi tomonga o‘zgarishini emas.',
 'Elasticity describes quantity responsiveness to price, not a direction in which price must always move.',
 'Повторите определение ценовой эластичности спроса.',
 'Talabning narx elastikligi ta’rifini takrorlang.',
 'Review the definition of price elasticity of demand.',
 'Elasticity','Perfectly inelastic demand','{}'::jsonb,'published'),

(1080,'mcq_option','A','factory rent',true,null,null,
 'Верно: арендная плата за фабрику обычно не меняется с объёмом выпуска в краткосрочном периоде.',
 'To‘g‘ri: zavod ijarasi odatda qisqa muddatda ishlab chiqarish hajmi bilan o‘zgarmaydi.',
 'Correct: factory rent usually does not vary with output in the short run.',
 'Свяжите fixed cost с затратами, не зависящими от текущего выпуска.',
 'Fixed costni joriy ishlab chiqarish hajmiga bog‘liq bo‘lmagan xarajatlar bilan bog‘lang.',
 'Link fixed cost to costs that do not vary with current output.',
 'Costs','Fixed cost','{}'::jsonb,'published'),
(1080,'mcq_option','B','raw materials',false,'fixed_variable_cost_confusion','Fixed vs variable costs',
 'Расход сырья обычно увеличивается с объёмом производства, поэтому это переменные издержки.',
 'Xomashyo sarfi odatda ishlab chiqarish hajmi bilan oshadi, shuning uchun bu o‘zgaruvchan xarajatdir.',
 'Raw-material use usually rises with output, so it is a variable cost.',
 'Спросите, меняется ли расход при выпуске ещё одной единицы.',
 'Yana bir birlik ishlab chiqarilganda xarajat o‘zgaradimi, deb tekshiring.',
 'Ask whether the cost changes when another unit is produced.',
 'Costs','Fixed cost','{}'::jsonb,'published'),
(1080,'mcq_option','C','piece-rate wages',false,'fixed_variable_cost_confusion','Piece-rate wages',
 'Сдельная оплата зависит от количества произведённых единиц, поэтому обычно является переменной издержкой.',
 'Dona hisobidagi ish haqi ishlab chiqarilgan birliklar soniga bog‘liq, shuning uchun odatda o‘zgaruvchan xarajatdir.',
 'Piece-rate wages depend on the number of units produced and are therefore usually variable costs.',
 'Различайте постоянную зарплату и оплату за единицу выпуска.',
 'Doimiy ish haqi bilan har bir birlik uchun to‘lovni farqlang.',
 'Distinguish fixed salary from pay per unit of output.',
 'Costs','Fixed cost','{}'::jsonb,'published'),
(1080,'mcq_option','D','electricity per unit',false,'fixed_variable_cost_confusion','Variable production costs',
 'Электроэнергия на единицу выпуска меняется вместе с производством и относится к переменным затратам.',
 'Har bir birlik uchun elektr energiyasi ishlab chiqarish bilan birga o‘zgaradi va o‘zgaruvchan xarajatga kiradi.',
 'Electricity used per unit varies with production and is a variable cost.',
 'Проверьте, зависит ли затрата от объёма выпуска.',
 'Xarajat ishlab chiqarish hajmiga bog‘liqmi, tekshiring.',
 'Check whether the cost depends on output.',
 'Costs','Fixed cost','{}'::jsonb,'published'),

(1094,'input_exact',null,'2',true,null,null,
 'Верно: |PED| = 6% ÷ 3% = 2.',
 'To‘g‘ri: |PED| = 6% ÷ 3% = 2.',
 'Correct: |PED| = 6% ÷ 3% = 2.',
 'Используйте |%ΔQd| ÷ |%ΔP|.',
 '|%ΔQd| ÷ |%ΔP| formulasidan foydalaning.',
 'Use |%ΔQd| ÷ |%ΔP|.',
 'Elasticity','Calculating PED','{"accepted":"2"}'::jsonb,'published'),
(1094,'fallback',null,null,false,'ped_formula_or_ratio_error','PED calculation',
 'Нужно разделить абсолютное процентное изменение количества на абсолютное процентное изменение цены: 6 ÷ 3 = 2. Ответ должен быть только числом.',
 'Talab miqdorining mutlaq foiz o‘zgarishini narxning mutlaq foiz o‘zgarishiga bo‘ling: 6 ÷ 3 = 2. Javob faqat son bo‘lishi kerak.',
 'Divide the absolute percentage change in quantity demanded by the absolute percentage change in price: 6 ÷ 3 = 2. Enter only the number.',
 'Повторите формулу PED и порядок числителя/знаменателя.',
 'PED formulasini va surat/maxraj tartibini takrorlang.',
 'Review the PED formula and numerator/denominator order.',
 'Elasticity','Calculating PED','{}'::jsonb,'published'),

(1127,'mcq_option','A','Fall',false,'ped_revenue_direction_error','PED and total revenue',
 'При эластичном спросе процентный рост количества после снижения цены больше процентного падения цены, поэтому выручка обычно растёт.',
 'Elastik talabda narx pasayganda miqdorning foiz o‘sishi narxning foiz pasayishidan katta bo‘ladi, shuning uchun tushum odatda oshadi.',
 'With elastic demand, the percentage rise in quantity after a price cut exceeds the percentage fall in price, so total revenue usually rises.',
 'Повторите правило TR для elastic demand.',
 'Elastic demand uchun TR qoidasini takrorlang.',
 'Review the total-revenue rule for elastic demand.',
 'Elasticity','PED and total revenue','{}'::jsonb,'published'),
(1127,'mcq_option','B','Rise',true,null,null,
 'Верно: при эластичном спросе снижение цены обычно увеличивает общую выручку.',
 'To‘g‘ri: elastik talabda narx pasayishi odatda jami tushumni oshiradi.',
 'Correct: when demand is elastic, a price fall usually increases total revenue.',
 'Свяжите elastic demand с противоположным движением цены и TR.',
 'Elastic demandda narx va TR qarama-qarshi yo‘nalishda harakatlanishini bog‘lang.',
 'Link elastic demand to price and total revenue moving in opposite directions.',
 'Elasticity','PED and total revenue','{}'::jsonb,'published'),
(1127,'mcq_option','C','Stay the same',false,'unit_elastic_confusion','Elastic vs unit-elastic demand',
 'Неизменная выручка характерна для единичной эластичности, а не для PED > 1.',
 'Tushumning o‘zgarmasligi birlik elastiklikka xos, PED > 1 ga emas.',
 'Unchanged total revenue is associated with unit elasticity, not PED > 1.',
 'Сравните elastic, unit elastic и inelastic demand.',
 'Elastic, unit elastic va inelastic demandni solishtiring.',
 'Compare elastic, unit-elastic and inelastic demand.',
 'Elasticity','PED and total revenue','{}'::jsonb,'published'),
(1127,'mcq_option','D','Become zero',false,'revenue_extreme_error','PED and total revenue',
 'Из эластичности спроса не следует, что выручка становится нулевой после снижения цены.',
 'Talab elastik bo‘lgani uchun narx pasayganda tushum nol bo‘lib qolmaydi.',
 'Elastic demand does not imply that total revenue becomes zero after a price cut.',
 'Используйте относительные изменения цены и количества, а не крайний вывод.',
 'Narx va miqdorning nisbiy o‘zgarishlaridan foydalaning, keskin xulosa qilmang.',
 'Use relative changes in price and quantity rather than an extreme conclusion.',
 'Elasticity','PED and total revenue','{}'::jsonb,'published'),

(1134,'mcq_option','A','Complements',false,'xed_sign_confusion','XED sign interpretation',
 'Для комплементов XED отрицательна, а не положительна.',
 'Komplementlar uchun XED manfiy bo‘ladi, ijobiy emas.',
 'Complements have negative XED, not positive XED.',
 'Повторите знаки XED для комплементов и заменителей.',
 'Komplement va o‘rinbosarlar uchun XED ishoralarini takrorlang.',
 'Review XED signs for complements and substitutes.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1134,'mcq_option','B','Unrelated goods',false,'xed_zero_confusion','XED sign interpretation',
 'Для несвязанных товаров XED обычно близка к нулю. Положительная XED указывает на заменители.',
 'Bog‘liq bo‘lmagan tovarlar uchun XED odatda nolga yaqin. Ijobiy XED o‘rinbosarlarni ko‘rsatadi.',
 'Unrelated goods usually have XED near zero. Positive XED indicates substitutes.',
 'Свяжите знак и величину XED с типом связи между товарами.',
 'XED ishorasi va kattaligini tovarlar o‘rtasidagi bog‘lanish turi bilan bog‘lang.',
 'Link the sign and size of XED to the relationship between goods.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1134,'mcq_option','C','Inferior goods',false,'yed_xed_confusion','XED vs YED',
 'Низшее благо определяется отрицательной YED, а не положительной XED.',
 'Past toifadagi tovar manfiy YED bilan aniqlanadi, ijobiy XED bilan emas.',
 'An inferior good is identified by negative YED, not positive XED.',
 'Различайте эластичность по доходу и перекрёстную эластичность.',
 'Daromad elastikligi bilan o‘zaro elastiklikni farqlang.',
 'Distinguish income elasticity from cross elasticity.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published'),
(1134,'mcq_option','D','Substitutes',true,null,null,
 'Верно: положительная XED означает, что рост цены одного товара увеличивает спрос на другой, что характерно для заменителей.',
 'To‘g‘ri: ijobiy XED bir tovar narxi oshganda boshqasiga talab oshishini bildiradi, bu o‘rinbosarlarga xos.',
 'Correct: positive XED means a rise in one good’s price increases demand for the other, which is characteristic of substitutes.',
 'Запомните: XED > 0 — substitutes; XED < 0 — complements.',
 'Eslab qoling: XED > 0 — substitutes; XED < 0 — complements.',
 'Remember: XED > 0 means substitutes; XED < 0 means complements.',
 'Elasticity','Cross elasticity and substitutes','{}'::jsonb,'published');