-- P1-02 E2 original content: P1-CIR-01 degree/radian conversion and radian measure.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1CIR01-D01','diagnostic','medium','Convert 150° to radians.','Переведите 150° в радианы.','150° ni radianlarga o‘tkazing.','["5π/6","3π/5","5π/3","6π/5"]','["5π/6","3π/5","5π/3","6π/5"]','["5π/6","3π/5","5π/3","6π/5"]','A','Multiply by π/180: 150π/180=5π/6.','Умножаем на π/180: 150π/180=5π/6.','π/180 ga ko‘paytiramiz: 150π/180=5π/6.',45),
('P1CIR01-L01','learning','easy','Convert 60° to radians.','Переведите 60° в радианы.','60° ni radianlarga o‘tkazing.','["π/6","π/3","2π/3","3π/2"]','["π/6","π/3","2π/3","3π/2"]','["π/6","π/3","2π/3","3π/2"]','B','60×π/180=π/3.','60×π/180=π/3.','60×π/180=π/3.',35),
('P1CIR01-L02','learning','medium','Convert 7π/12 radians to degrees.','Переведите 7π/12 радиан в градусы.','7π/12 radianni graduslarga o‘tkazing.','["75°","90°","105°","120°"]','["75°","90°","105°","120°"]','["75°","90°","105°","120°"]','C','Multiply by 180/π: (7π/12)(180/π)=105°.','Умножаем на 180/π: (7π/12)(180/π)=105°.','180/π ga ko‘paytiramiz: (7π/12)(180/π)=105°.',45),
('P1CIR01-L03','learning','medium','Which angle is equal to 225° in radians?','Какой угол равен 225° в радианах?','225° ga teng radian burchak qaysi?','["3π/4","4π/5","5π/4","7π/6"]','["3π/4","4π/5","5π/4","7π/6"]','["3π/4","4π/5","5π/4","7π/6"]','C','225π/180 simplifies to 5π/4.','225π/180 сокращается до 5π/4.','225π/180 qisqarib 5π/4 bo‘ladi.',45),
('P1CIR01-R01','retest','easy','Convert π/8 radians to degrees.','Переведите π/8 радиан в градусы.','π/8 radianni gradusga o‘tkazing.','["20°","22.5°","30°","45°"]','["20°","22.5°","30°","45°"]','["20°","22.5°","30°","45°"]','B','(π/8)(180/π)=22.5°.','(π/8)(180/π)=22.5°.','(π/8)(180/π)=22.5°.',35),
('P1CIR01-R02','retest','medium','Convert 315° to radians.','Переведите 315° в радианы.','315° ni radianlarga o‘tkazing.','["5π/4","7π/4","9π/5","11π/6"]','["5π/4","7π/4","9π/5","11π/6"]','["5π/4","7π/4","9π/5","11π/6"]','B','315π/180=7π/4.','315π/180=7π/4.','315π/180=7π/4.',40),
('P1CIR01-M01','mixed','hard','An angle θ is 40° more than π/6 radians. What is θ in radians?','Угол θ на 40° больше, чем π/6 радиан. Найдите θ в радианах.','θ burchak π/6 radiandan 40° ga katta. θ ni radianlarda toping.','["5π/18","7π/18","4π/9","11π/18"]','["5π/18","7π/18","4π/9","11π/18"]','["5π/18","7π/18","4π/9","11π/18"]','B','π/6=30°. Adding 40° gives 70°, and 70π/180=7π/18.','π/6=30°. Добавляем 40°: 70°, а 70π/180=7π/18.','π/6=30°. 40° qo‘shsak 70°, va 70π/180=7π/18.',65)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Circular measure','P1-CIR-01',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and status='draft'),
keys(k,role) as (values('P1CIR01-D01','diagnostic'),('P1CIR01-L01','learning'),('P1CIR01-L02','learning'),('P1CIR01-L03','learning'),('P1CIR01-R01','retest'),('P1CIR01-R02','retest'),('P1CIR01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-CIR-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored from canonical degree/radian conversion using independent values.','Cambridge 9709 2026-2027 v4; P1 1.4 Circular measure','Complete Pure Mathematics 1, Ch4 Circular measure pp.74-81 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
do $$ declare v_id bigint; begin select id into v_id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1'; if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code='P1-CIR-01')<>7 then raise exception 'P1-02 CIR-01 expected 7 question objects'; end if; end $$;
commit;
