-- AI-4 Economics Practice 1 deterministic diagnostic batch: Chapter 7.
-- Adds option-level deterministic explanations for ten currently-unmapped Chapter 7 MCQs.
-- q1071 already has published deterministic diagnostics and is intentionally left untouched.
-- Server scoring remains authoritative; these rows only explain an already-checked answer.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,topic,subtopic,correct_answer,options_en) as (
    values
    (1020,'Demand','Movement along the demand curve','B','["Demand curve shifts right","Quantity demanded increases (movement along the curve)","Supply curve shifts left","Quantity supplied decreases (movement along supply)"]'::jsonb),
    (1021,'Demand','Substitute goods','B','["Demand for tea falls","Demand for tea rises","Supply of tea falls","Quantity demanded of tea falls because its price rose"]'::jsonb),
    (1030,'Supply','Law of supply','B','["Quantity supplied falls","Quantity supplied rises","Supply curve shifts left","Demand curve shifts right"]'::jsonb),
    (1070,'Demand','Demand shift: tastes and preferences','A','["shift demand right","shift demand left","move along demand curve only","shift supply right"]'::jsonb),
    (1072,'Supply','Supply shift: input prices','A','["shift right","shift left","demand shifts right","does not change"]'::jsonb),
    (1078,'Elasticity','Cross elasticity and complements','A','["complements","substitutes","unrelated","inferior goods"]'::jsonb),
    (1085,'Demand','Normal goods','A','["rises when income rises","falls when income rises","never changes with income","depends only on price"]'::jsonb),
    (1092,'Demand','Demand and expectations','A','["decrease","increase","stay unchanged","become perfectly inelastic"]'::jsonb),
    (1093,'Supply','Tax and supply','A','["shift supply left","shift supply right","shift demand right","raise demand"]'::jsonb),
    (1106,'Demand','Simultaneous shifts of demand and supply','A','["Price rises; quantity is ambiguous (could rise or fall)","Price falls; quantity rises","Price rises; quantity definitely rises","Price falls; quantity is ambiguous"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>7
     or q.is_active is not true
     or q.quality_status<>'published'
     or lower(coalesce(q.qtype,''))<>'mcq'
     or q.topic<>e.topic
     or q.subtopic<>e.subtopic
     or upper(trim(coalesce(q.correct_answer,'')))<>e.correct_answer
     or coalesce(q.options_text_en,'[]')::jsonb<>e.options_en;

  if v_bad<>0 then
    raise exception 'AI-4 diagnostic batch refused: one or more Chapter 7 questions changed';
  end if;

  if exists (
    select 1 from public.question_answer_diagnostics
    where question_id in (1020,1021,1030,1070,1072,1078,1085,1092,1093,1106)
      and quality_status='published'
  ) then
    raise exception 'AI-4 diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1020,'mcq_option','A','Demand curve shifts right',false,'movement_shift_confusion','Movement along demand vs shift in demand',
 'Изменение собственной цены товара вызывает движение вдоль существующей кривой спроса, а не её сдвиг.',
 'Tovarning o‘z narxi o‘zgarishi talab egri chizig‘i bo‘ylab harakatni keltirib chiqaradi, egri chiziqning siljishini emas.',
 'A change in the good’s own price causes a movement along the existing demand curve, not a shift of the curve.',
 'Различайте изменение цены самого товара и неценовые факторы спроса.',
 'Tovarning o‘z narxi bilan talabning narxdan tashqari omillarini farqlang.',
 'Distinguish a change in the good’s own price from non-price demand determinants.',
 'Demand','Movement along the demand curve','{}'::jsonb,'published'),
(1020,'mcq_option','B','Quantity demanded increases (movement along the curve)',true,null,null,
 'Верно: при снижении цены, при прочих равных, объём спроса растёт — это движение вдоль кривой спроса.',
 'To‘g‘ri: narx pasayganda, boshqa shartlar o‘zgarmasa, talab miqdori oshadi — bu talab egri chizig‘i bo‘ylab harakatdir.',
 'Correct: when price falls, ceteris paribus, quantity demanded rises—a movement along the demand curve.',
 'Свяжите собственную цену с движением вдоль кривой.',
 'Tovarning o‘z narxini egri chiziq bo‘ylab harakat bilan bog‘lang.',
 'Link the good’s own price to movement along the curve.',
 'Demand','Movement along the demand curve','{}'::jsonb,'published'),
(1020,'mcq_option','C','Supply curve shifts left',false,'demand_supply_side_confusion','Demand response to own price',
 'Вопрос спрашивает о реакции спроса на изменение цены товара. Сдвиг предложения здесь не следует из условия.',
 'Savol tovar narxi o‘zgarishiga talabning reaksiyasini so‘raydi. Bu shartdan taklifning siljishi kelib chiqmaydi.',
 'The question asks about the demand response to the good’s price. A supply shift does not follow from the information given.',
 'Сначала определите, какая сторона рынка изменяется в условии.',
 'Avval shartda bozorning qaysi tomoni o‘zgarayotganini aniqlang.',
 'First identify which side of the market the question is asking about.',
 'Demand','Movement along the demand curve','{}'::jsonb,'published'),
(1020,'mcq_option','D','Quantity supplied decreases (movement along supply)',false,'demand_supply_side_confusion','Quantity demanded vs quantity supplied',
 'Снижение цены действительно может уменьшить объём предложения, но вопрос спрашивает, что происходит со спросом.',
 'Narx pasayishi taklif miqdorini kamaytirishi mumkin, ammo savol talab bilan nima bo‘lishini so‘raydi.',
 'A lower price may reduce quantity supplied, but the question asks what happens on the demand side.',
 'Следите за тем, относится ли ответ к спросу или предложению.',
 'Javob talabga yoki taklifga tegishli ekanini tekshiring.',
 'Check whether the answer refers to demand or supply.',
 'Demand','Movement along the demand curve','{}'::jsonb,'published'),

(1021,'mcq_option','A','Demand for tea falls',false,'substitute_direction_error','Substitute-goods demand direction',
 'Для товаров-заменителей рост цены одного товара обычно повышает спрос на другой, а не снижает его.',
 'O‘rinbosar tovarlarda birining narxi oshsa, odatda ikkinchisiga talab oshadi, kamaymaydi.',
 'For substitutes, a rise in the price of one good usually increases demand for the other, not decreases it.',
 'Повторите направление эффекта цены заменителя.',
 'O‘rinbosar narxining ta’sir yo‘nalishini takrorlang.',
 'Review the direction of the substitute-price effect.',
 'Demand','Substitute goods','{}'::jsonb,'published'),
(1021,'mcq_option','B','Demand for tea rises',true,null,null,
 'Верно: кофе и чай — заменители, поэтому более дорогой кофе делает чай относительно привлекательнее и повышает спрос на чай.',
 'To‘g‘ri: qahva va choy o‘rinbosar, shuning uchun qahvaning qimmatlashishi choyni nisbatan jozibador qiladi va choyga talabni oshiradi.',
 'Correct: coffee and tea are substitutes, so more expensive coffee makes tea relatively more attractive and raises demand for tea.',
 'Свяжите товары-заменители с положительной перекрёстной реакцией спроса.',
 'O‘rinbosar tovarlarni talabning ijobiy o‘zaro reaksiyasi bilan bog‘lang.',
 'Link substitute goods to a positive cross-demand response.',
 'Demand','Substitute goods','{}'::jsonb,'published'),
(1021,'mcq_option','C','Supply of tea falls',false,'demand_supply_side_confusion','Related goods affect demand',
 'Изменение цены кофе влияет на спрос на чай как на заменитель, а не напрямую на предложение чая.',
 'Qahva narxining o‘zgarishi o‘rinbosar sifatida choyga talabga ta’sir qiladi, choy taklifiga bevosita emas.',
 'A change in coffee’s price affects demand for tea as a substitute, not tea supply directly.',
 'Различайте факторы спроса и предложения.',
 'Talab va taklif omillarini farqlang.',
 'Distinguish demand determinants from supply determinants.',
 'Demand','Substitute goods','{}'::jsonb,'published'),
(1021,'mcq_option','D','Quantity demanded of tea falls because its price rose',false,'own_price_assumption_error','Substitute-goods effect vs own-price movement',
 'В условии не сказано, что цена чая выросла. Меняется цена кофе, поэтому это сдвиг спроса на чай.',
 'Shartda choy narxi oshgani aytilmagan. Qahva narxi o‘zgaradi, shuning uchun choyga talab siljiydi.',
 'The prompt does not say tea’s own price rose. Coffee’s price changes, so demand for tea shifts.',
 'Не добавляйте в условие изменение собственной цены товара.',
 'Shartga tovarning o‘z narxi o‘zgarganini qo‘shmang.',
 'Do not invent a change in the good’s own price.',
 'Demand','Substitute goods','{}'::jsonb,'published'),

(1030,'mcq_option','A','Quantity supplied falls',false,'law_of_supply_direction_error','Law of supply direction',
 'Закон предложения говорит об обратном: при росте цены объём предложения обычно растёт, при прочих равных.',
 'Taklif qonuni aksini aytadi: narx oshganda, boshqa shartlar o‘zgarmasa, taklif miqdori odatda oshadi.',
 'The law of supply says the opposite: when price rises, quantity supplied usually rises, ceteris paribus.',
 'Повторите положительную связь между ценой и объёмом предложения.',
 'Narx va taklif miqdori o‘rtasidagi ijobiy bog‘lanishni takrorlang.',
 'Review the positive relationship between price and quantity supplied.',
 'Supply','Law of supply','{}'::jsonb,'published'),
(1030,'mcq_option','B','Quantity supplied rises',true,null,null,
 'Верно: при более высокой цене производители обычно готовы предложить больше, при прочих равных.',
 'To‘g‘ri: yuqori narxda ishlab chiqaruvchilar, boshqa shartlar o‘zgarmasa, odatda ko‘proq taklif qilishga tayyor bo‘ladi.',
 'Correct: at a higher price, producers are usually willing to supply a greater quantity, ceteris paribus.',
 'Свяжите собственную цену с движением вдоль кривой предложения.',
 'Tovarning o‘z narxini taklif egri chizig‘i bo‘ylab harakat bilan bog‘lang.',
 'Link the good’s own price to movement along the supply curve.',
 'Supply','Law of supply','{}'::jsonb,'published'),
(1030,'mcq_option','C','Supply curve shifts left',false,'movement_shift_confusion','Movement along supply vs shift in supply',
 'Изменение собственной цены вызывает движение вдоль кривой предложения, а не её сдвиг.',
 'Tovarning o‘z narxi o‘zgarishi taklif egri chizig‘i bo‘ylab harakatni keltirib chiqaradi, siljishni emas.',
 'A change in the good’s own price causes movement along the supply curve, not a shift of supply.',
 'Отделяйте собственную цену от неценовых факторов предложения.',
 'Tovarning o‘z narxini taklifning narxdan tashqari omillaridan ajrating.',
 'Separate the good’s own price from non-price supply determinants.',
 'Supply','Law of supply','{}'::jsonb,'published'),
(1030,'mcq_option','D','Demand curve shifts right',false,'supply_demand_side_confusion','Law of supply',
 'Закон предложения описывает реакцию производителей, а не сдвиг спроса потребителей.',
 'Taklif qonuni ishlab chiqaruvchilar reaksiyasini tasvirlaydi, iste’molchilar talabining siljishini emas.',
 'The law of supply describes producer response, not a shift in consumer demand.',
 'Сосредоточьтесь на переменной quantity supplied.',
 'Quantity supplied o‘zgaruvchisiga e’tibor qarating.',
 'Focus on the quantity supplied variable.',
 'Supply','Law of supply','{}'::jsonb,'published'),

(1070,'mcq_option','A','shift demand right',true,null,null,
 'Верно: усиление предпочтения к товару увеличивает спрос при каждой цене и сдвигает кривую спроса вправо.',
 'To‘g‘ri: tovarga qiziqish kuchayishi har bir narxda talabni oshiradi va talab egri chizig‘ini o‘ngga siljitadi.',
 'Correct: stronger preference for a product increases demand at each price and shifts the demand curve right.',
 'Свяжите вкусы и предпочтения с неценовыми факторами спроса.',
 'Did va afzalliklarni talabning narxdan tashqari omillari bilan bog‘lang.',
 'Link tastes and preferences to non-price demand determinants.',
 'Demand','Demand shift: tastes and preferences','{}'::jsonb,'published'),
(1070,'mcq_option','B','shift demand left',false,'demand_shift_direction_error','Preference effect on demand',
 'Рост предпочтения повышает, а не снижает спрос на товар.',
 'Tovarga afzallikning oshishi talabni kamaytirmaydi, oshiradi.',
 'A rise in preference increases, rather than decreases, demand for the product.',
 'Повторите направление сдвига при росте популярности товара.',
 'Tovar mashhurligi oshganda siljish yo‘nalishini takrorlang.',
 'Review the direction of the shift when a product becomes more preferred.',
 'Demand','Demand shift: tastes and preferences','{}'::jsonb,'published'),
(1070,'mcq_option','C','move along demand curve only',false,'movement_shift_confusion','Non-price demand shifter',
 'Вкусы и предпочтения — неценовой фактор, поэтому меняется вся кривая спроса, а не происходит движение вдоль неё.',
 'Did va afzalliklar narxdan tashqari omil, shuning uchun butun talab egri chizig‘i siljiydi, egri chiziq bo‘ylab harakat emas.',
 'Tastes and preferences are a non-price determinant, so the whole demand curve shifts rather than moving along it.',
 'Запомните: собственная цена — движение; неценовой фактор — сдвиг.',
 'Eslab qoling: o‘z narxi — harakat; narxdan tashqari omil — siljish.',
 'Remember: own price causes movement; a non-price determinant causes a shift.',
 'Demand','Demand shift: tastes and preferences','{}'::jsonb,'published'),
(1070,'mcq_option','D','shift supply right',false,'demand_supply_side_confusion','Taste changes affect demand',
 'Предпочтения потребителей относятся к спросу, а не к условиям производства и предложения.',
 'Iste’molchi afzalliklari talabga tegishli, ishlab chiqarish sharoiti va taklifga emas.',
 'Consumer preferences affect demand, not production conditions and supply.',
 'Различайте потребительские и производственные факторы.',
 'Iste’molchi va ishlab chiqaruvchi omillarini farqlang.',
 'Distinguish consumer-side from producer-side determinants.',
 'Demand','Demand shift: tastes and preferences','{}'::jsonb,'published'),

(1072,'mcq_option','A','shift right',true,null,null,
 'Верно: более дешёвое сырьё снижает издержки производства и увеличивает предложение, сдвигая кривую вправо.',
 'To‘g‘ri: arzonroq xomashyo ishlab chiqarish xarajatlarini kamaytiradi va taklifni oshirib, egri chiziqni o‘ngga siljitadi.',
 'Correct: cheaper raw materials reduce production costs and increase supply, shifting the supply curve right.',
 'Свяжите более низкие издержки с ростом предложения.',
 'Pastroq xarajatlarni taklifning oshishi bilan bog‘lang.',
 'Link lower production costs to increased supply.',
 'Supply','Supply shift: input prices','{}'::jsonb,'published'),
(1072,'mcq_option','B','shift left',false,'supply_shift_direction_error','Input cost effect on supply',
 'Падение цен на сырьё снижает издержки, поэтому предложение растёт, а не сокращается.',
 'Xomashyo narxining pasayishi xarajatlarni kamaytiradi, shuning uchun taklif kamaymaydi, oshadi.',
 'A fall in raw-material prices lowers costs, so supply increases rather than decreases.',
 'Повторите связь издержек и предложения.',
 'Xarajatlar va taklif o‘rtasidagi bog‘lanishni takrorlang.',
 'Review the relationship between costs and supply.',
 'Supply','Supply shift: input prices','{}'::jsonb,'published'),
(1072,'mcq_option','C','demand shifts right',false,'supply_demand_side_confusion','Input prices as supply determinant',
 'Цена сырья — издержка производителя, поэтому она влияет на предложение, а не напрямую на спрос.',
 'Xomashyo narxi ishlab chiqaruvchi xarajati bo‘lib, taklifga ta’sir qiladi, talabga bevosita emas.',
 'Raw-material prices are production costs, so they affect supply rather than demand directly.',
 'Классифицируйте фактор как потребительский или производственный.',
 'Omilni iste’molchi yoki ishlab chiqaruvchi omili sifatida tasniflang.',
 'Classify the factor as consumer-side or producer-side.',
 'Supply','Supply shift: input prices','{}'::jsonb,'published'),
(1072,'mcq_option','D','does not change',false,'cost_effect_ignored','Production costs and supply',
 'Изменение ключевых затрат меняет рентабельность производства и поэтому обычно изменяет предложение.',
 'Muhim xarajatlarning o‘zgarishi ishlab chiqarish rentabelligini o‘zgartiradi va odatda taklifga ta’sir qiladi.',
 'A change in a key input cost changes production profitability and therefore usually affects supply.',
 'Не игнорируйте неценовые факторы предложения.',
 'Taklifning narxdan tashqari omillarini e’tiborsiz qoldirmang.',
 'Do not ignore non-price determinants of supply.',
 'Supply','Supply shift: input prices','{}'::jsonb,'published'),

(1078,'mcq_option','A','complements',true,null,null,
 'Верно: если цена A растёт и спрос на B падает, товары обычно используются вместе, то есть являются комплементами.',
 'To‘g‘ri: A narxi oshganda Bga talab kamayса, tovarlar odatda birga iste’mol qilinadi, ya’ni komplementlardir.',
 'Correct: if A’s price rises and demand for B falls, the goods are typically used together and are complements.',
 'Свяжите комплементы с отрицательной перекрёстной эластичностью спроса.',
 'Komplementlarni manfiy o‘zaro talab elastikligi bilan bog‘lang.',
 'Link complements to negative cross-price elasticity of demand.',
 'Elasticity','Cross elasticity and complements','{}'::jsonb,'published'),
(1078,'mcq_option','B','substitutes',false,'cross_elasticity_sign_error','Substitutes vs complements',
 'Для заменителей рост цены A обычно повышает спрос на B. Здесь спрос на B падает, что указывает на комплементы.',
 'O‘rinbosarlarda A narxi oshsa, odatda Bga talab oshadi. Bu yerda Bga talab kamaymoqda, demak ular komplement.',
 'For substitutes, a rise in A’s price usually increases demand for B. Here demand for B falls, indicating complements.',
 'Повторите знаки XED для заменителей и комплементов.',
 'O‘rinbosar va komplementlar uchun XED ishoralarini takrorlang.',
 'Review the signs of XED for substitutes and complements.',
 'Elasticity','Cross elasticity and complements','{}'::jsonb,'published'),
(1078,'mcq_option','C','unrelated',false,'relationship_ignored','Cross-price relationship',
 'Изменение цены A сопровождается систематическим изменением спроса на B, поэтому товары не выглядят несвязанными.',
 'A narxi o‘zgarishi Bga talabning tizimli o‘zgarishi bilan birga kelmoqda, shuning uchun tovarlar bog‘liq emas deb bo‘lmaydi.',
 'A change in A’s price is associated with a systematic change in demand for B, so the goods do not appear unrelated.',
 'Ищите направление реакции спроса на цену другого товара.',
 'Boshqa tovar narxiga talabning qanday javob berishini kuzating.',
 'Look at the direction of demand response to the other good’s price.',
 'Elasticity','Cross elasticity and complements','{}'::jsonb,'published'),
(1078,'mcq_option','D','inferior goods',false,'yed_xed_confusion','Cross elasticity vs income elasticity',
 'Низшее благо определяется реакцией спроса на доход, а здесь меняется цена другого товара.',
 'Past toifadagi tovar talabning daromadga reaksiyasi bilan aniqlanadi, bu savolda esa boshqa tovar narxi o‘zgaradi.',
 'An inferior good is classified by the demand response to income, while this question changes the price of another good.',
 'Различайте YED и XED.',
 'YED bilan XEDni farqlang.',
 'Distinguish YED from XED.',
 'Elasticity','Cross elasticity and complements','{}'::jsonb,'published'),

(1085,'mcq_option','A','rises when income rises',true,null,null,
 'Верно: для нормального блага рост дохода, при прочих равных, увеличивает спрос.',
 'To‘g‘ri: normal tovar uchun daromad oshishi, boshqa shartlar o‘zgarmasa, talabni oshiradi.',
 'Correct: for a normal good, higher income increases demand, ceteris paribus.',
 'Свяжите нормальные блага с положительной YED.',
 'Normal tovarlarni ijobiy YED bilan bog‘lang.',
 'Link normal goods to positive YED.',
 'Demand','Normal goods','{}'::jsonb,'published'),
(1085,'mcq_option','B','falls when income rises',false,'normal_inferior_confusion','Normal vs inferior goods',
 'Падение спроса при росте дохода характерно для низшего, а не нормального блага.',
 'Daromad oshganda talabning kamayishi normal emas, past toifadagi tovarga xos.',
 'Demand falling as income rises is characteristic of an inferior good, not a normal good.',
 'Сравните знак YED для нормальных и низших благ.',
 'Normal va past toifadagi tovarlar uchun YED ishorasini solishtiring.',
 'Compare the sign of YED for normal and inferior goods.',
 'Demand','Normal goods','{}'::jsonb,'published'),
(1085,'mcq_option','C','never changes with income',false,'income_effect_denial','Income as a demand determinant',
 'Классификация normal good именно означает систематическую реакцию спроса на доход.',
 'Normal good tasnifi aynan talabning daromadga tizimli reaksiyasini anglatadi.',
 'The classification “normal good” specifically means demand responds systematically to income.',
 'Повторите доход как неценовой фактор спроса.',
 'Daromadni talabning narxdan tashqari omili sifatida takrorlang.',
 'Review income as a non-price determinant of demand.',
 'Demand','Normal goods','{}'::jsonb,'published'),
(1085,'mcq_option','D','depends only on price',false,'non_price_determinants_ignored','Demand determinants',
 'Спрос зависит не только от собственной цены: доход также является важным неценовым фактором.',
 'Talab faqat tovarning o‘z narxiga bog‘liq emas: daromad ham muhim narxdan tashqari omildir.',
 'Demand does not depend only on the good’s own price; income is also an important non-price determinant.',
 'Повторите основные неценовые факторы спроса.',
 'Talabning asosiy narxdan tashqari omillarini takrorlang.',
 'Review the main non-price determinants of demand.',
 'Demand','Normal goods','{}'::jsonb,'published'),

(1092,'mcq_option','A','decrease',true,null,null,
 'Верно: если потребители ожидают более низких цен вскоре, часть покупок может быть отложена, поэтому текущий спрос снижается.',
 'To‘g‘ri: iste’molchilar tez orada narxlar pasayishini kutsa, ayrim xaridlarni kechiktiradi va joriy talab kamayadi.',
 'Correct: if consumers expect lower prices soon, some purchases may be postponed, reducing current demand.',
 'Свяжите ожидания будущих цен с переносом покупок во времени.',
 'Kelajak narxlari haqidagi kutilmalarni xaridlarni vaqt bo‘yicha ko‘chirish bilan bog‘lang.',
 'Link expectations of future prices to the timing of purchases.',
 'Demand','Demand and expectations','{}'::jsonb,'published'),
(1092,'mcq_option','B','increase',false,'expectations_direction_error','Future-price expectations and current demand',
 'Ожидание более низкой будущей цены обычно стимулирует отложить покупку, а не купить больше сейчас.',
 'Kelajakda narx pastroq bo‘lishi kutilsa, odatda hozir ko‘proq sotib olish emas, xaridni kechiktirish rag‘batlantiriladi.',
 'Expecting a lower future price usually encourages postponing purchases rather than buying more now.',
 'Спросите, выгоднее ли купить сейчас или подождать.',
 'Hozir sotib olish yaxshimi yoki kutishmi, deb o‘ylang.',
 'Ask whether it is more attractive to buy now or wait.',
 'Demand','Demand and expectations','{}'::jsonb,'published'),
(1092,'mcq_option','C','stay unchanged',false,'expectations_ignored','Expectations as demand determinant',
 'Ожидания потребителей — неценовой фактор спроса и могут изменить текущие покупки.',
 'Iste’molchi kutilmalari talabning narxdan tashqari omili bo‘lib, joriy xaridlarni o‘zgartirishi mumkin.',
 'Consumer expectations are a non-price determinant of demand and can change current purchasing.',
 'Не игнорируйте ожидания как фактор спроса.',
 'Kutilmalarni talab omili sifatida e’tiborsiz qoldirmang.',
 'Do not ignore expectations as a demand determinant.',
 'Demand','Demand and expectations','{}'::jsonb,'published'),
(1092,'mcq_option','D','become perfectly inelastic',false,'expectations_elasticity_confusion','Demand shift vs elasticity',
 'Ожидание изменения будущей цены влияет на положение спроса, но не делает текущий спрос автоматически совершенно неэластичным.',
 'Kelajak narxi haqidagi kutilma talab holatiga ta’sir qiladi, ammo joriy talabni avtomatik ravishda mutlaqo noelastik qilmaydi.',
 'Expectations about future price affect current demand but do not automatically make demand perfectly inelastic.',
 'Различайте сдвиг спроса и форму/эластичность кривой.',
 'Talab siljishi bilan egri chiziq shakli/elastikligini farqlang.',
 'Distinguish a demand shift from the elasticity of the curve.',
 'Demand','Demand and expectations','{}'::jsonb,'published'),

(1093,'mcq_option','A','shift supply left',true,null,null,
 'Верно: более высокий налог на бизнес повышает издержки и обычно сокращает предложение, сдвигая его влево.',
 'To‘g‘ri: yuqori biznes solig‘i xarajatlarni oshiradi va odatda taklifni kamaytirib, chapga siljitadi.',
 'Correct: a higher business tax raises costs and usually reduces supply, shifting the supply curve left.',
 'Свяжите налоги на производителя с ростом издержек предложения.',
 'Ishlab chiqaruvchi soliqlarini taklif xarajatlarining oshishi bilan bog‘lang.',
 'Link producer taxes to higher supply costs.',
 'Supply','Tax and supply','{}'::jsonb,'published'),
(1093,'mcq_option','B','shift supply right',false,'tax_supply_direction_error','Tax effect on supply',
 'Более высокий налог увеличивает издержки, поэтому предложение обычно сокращается, а не растёт.',
 'Yuqori soliq xarajatlarni oshiradi, shuning uchun taklif odatda oshmaydi, kamayadi.',
 'A higher tax raises costs, so supply usually decreases rather than increases.',
 'Повторите направление сдвига при росте производственных издержек.',
 'Ishlab chiqarish xarajatlari oshganda siljish yo‘nalishini takrorlang.',
 'Review the direction of a supply shift when production costs rise.',
 'Supply','Tax and supply','{}'::jsonb,'published'),
(1093,'mcq_option','C','shift demand right',false,'tax_demand_supply_confusion','Producer tax affects supply',
 'Налог на бизнес непосредственно меняет издержки производителя, поэтому первичный эффект идёт через предложение.',
 'Biznes solig‘i ishlab chiqaruvchi xarajatlarini bevosita o‘zgartiradi, shuning uchun asosiy ta’sir taklif orqali bo‘ladi.',
 'A business tax directly changes producer costs, so the primary effect is on supply.',
 'Определяйте, на кого непосредственно действует налог.',
 'Soliq kimga bevosita ta’sir qilishini aniqlang.',
 'Identify which side of the market the tax directly affects.',
 'Supply','Tax and supply','{}'::jsonb,'published'),
(1093,'mcq_option','D','raise demand',false,'tax_demand_supply_confusion','Producer tax affects supply',
 'Из условия не следует рост спроса. Более высокий налог на бизнес прежде всего повышает издержки предложения.',
 'Shartdan talab oshishi kelib chiqmaydi. Yuqori biznes solig‘i avvalo taklif xarajatlarini oshiradi.',
 'The prompt does not imply higher demand. A higher business tax primarily raises supply-side costs.',
 'Отделяйте производственные издержки от факторов спроса.',
 'Ishlab chiqarish xarajatlarini talab omillaridan ajrating.',
 'Separate production-cost changes from demand determinants.',
 'Supply','Tax and supply','{}'::jsonb,'published'),

(1106,'mcq_option','A','Price rises; quantity is ambiguous (could rise or fall)',true,null,null,
 'Верно: рост спроса и сокращение предложения оба повышают цену, но влияют на равновесное количество в противоположных направлениях.',
 'To‘g‘ri: talabning oshishi va taklifning kamayishi ikkalasi ham narxni oshiradi, ammo muvozanat miqdoriga qarama-qarshi yo‘nalishda ta’sir qiladi.',
 'Correct: higher demand and lower supply both raise price, but they push equilibrium quantity in opposite directions.',
 'При одновременных сдвигах анализируйте цену и количество отдельно.',
 'Bir vaqtdagi siljishlarda narx va miqdorni alohida tahlil qiling.',
 'With simultaneous shifts, analyse price and quantity separately.',
 'Demand','Simultaneous shifts of demand and supply','{}'::jsonb,'published'),
(1106,'mcq_option','B','Price falls; quantity rises',false,'simultaneous_shift_price_error','Combined demand and supply shifts',
 'Рост спроса повышает цену, а сокращение предложения также повышает цену, поэтому падение цены не согласуется с обоими сдвигами.',
 'Talab oshishi narxni ko‘taradi, taklif kamayishi ham narxni ko‘taradi, shuning uchun narxning tushishi ikkala siljishga mos kelmaydi.',
 'An increase in demand raises price, and a decrease in supply also raises price, so a price fall is inconsistent with both shifts.',
 'Для каждого сдвига отдельно отметьте направление влияния на цену.',
 'Har bir siljishning narxga ta’sir yo‘nalishini alohida belgilang.',
 'Mark the price effect of each shift separately.',
 'Demand','Simultaneous shifts of demand and supply','{}'::jsonb,'published'),
(1106,'mcq_option','C','Price rises; quantity definitely rises',false,'simultaneous_shift_quantity_certainty','Ambiguous equilibrium quantity',
 'Цена действительно растёт, но количество не обязано расти: спрос толкает его вверх, а сокращение предложения — вниз.',
 'Narx haqiqatan oshadi, ammo miqdor albatta oshmaydi: talab uni yuqoriga, taklifning kamayishi esa pastga itaradi.',
 'Price does rise, but quantity is not guaranteed to rise: higher demand pushes it up while lower supply pushes it down.',
 'Если два сдвига действуют на количество в разные стороны, без величины сдвигов результат неоднозначен.',
 'Agar ikki siljish miqdorga qarama-qarshi ta’sir qilsa, siljishlar kattaligisiz natija noaniq bo‘ladi.',
 'If the two shifts push quantity in opposite directions, the result is ambiguous without their relative sizes.',
 'Demand','Simultaneous shifts of demand and supply','{}'::jsonb,'published'),
(1106,'mcq_option','D','Price falls; quantity is ambiguous',false,'simultaneous_shift_price_error','Combined demand and supply shifts',
 'Количество действительно неоднозначно, но цена нет: оба сдвига оказывают повышательное давление на цену.',
 'Miqdor haqiqatan noaniq, ammo narx emas: ikkala siljish ham narxni oshirishga bosim qiladi.',
 'Quantity is indeed ambiguous, but price is not: both shifts put upward pressure on price.',
 'Разделите переменные: цена определённа, количество неоднозначно.',
 'O‘zgaruvchilarni ajrating: narx aniq, miqdor noaniq.',
 'Separate the variables: price is determinate, quantity is ambiguous.',
 'Demand','Simultaneous shifts of demand and supply','{}'::jsonb,'published');