-- P1-02 original iClub AW9-12 content: P1-FUN-03/04/05.
-- Per skill: 1 diagnostic + 3 learning + 2 delayed-retest + 1 mixed.
-- public.questions stays DRAFT + INACTIVE; only governed Exam Prep membership may expose learning rows.

begin;
with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p1_aw09_12_functions_v1' and component_code='P1' and status='draft'
), src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
-- P1-FUN-03: composition and domain/range compatibility
('P1-FUN-03','P1FUN03-D01','diagnostic','medium',
'Let f(x) = 1/(x − 2) and g(x) = x + 3. Which restriction is required for the domain of (f ∘ g)(x)?',
'Пусть f(x) = 1/(x − 2), g(x) = x + 3. Какое ограничение требуется для области определения (f ∘ g)(x)?',
'f(x) = 1/(x − 2), g(x) = x + 3 bo‘lsin. (f ∘ g)(x) aniqlanish sohasi uchun qaysi cheklov kerak?',
'["x ≠ −1","x ≠ 2","x ≠ −3","all real x"]',
'["x ≠ −1","x ≠ 2","x ≠ −3","все действительные x"]',
'["x ≠ −1","x ≠ 2","x ≠ −3","barcha haqiqiy x"]','A',
'(f ∘ g)(x) = 1/((x + 3) − 2) = 1/(x + 1). The denominator cannot be zero, so x ≠ −1.',
'(f ∘ g)(x) = 1/((x + 3) − 2) = 1/(x + 1). Знаменатель не может быть равен нулю, поэтому x ≠ −1.',
'(f ∘ g)(x) = 1/((x + 3) − 2) = 1/(x + 1). Maxraj nol bo‘la olmaydi, demak x ≠ −1.',75),
('P1-FUN-03','P1FUN03-L01','learning','easy',
'Let f(x) = 2x − 1 and g(x) = x + 4. Find (f ∘ g)(x).',
'Пусть f(x) = 2x − 1 и g(x) = x + 4. Найдите (f ∘ g)(x).',
'f(x) = 2x − 1 va g(x) = x + 4 bo‘lsin. (f ∘ g)(x) ni toping.',
'["2x + 3","2x + 7","2x − 5","x + 7"]',
'["2x + 3","2x + 7","2x − 5","x + 7"]',
'["2x + 3","2x + 7","2x − 5","x + 7"]','B',
'f(g(x)) = 2(x + 4) − 1 = 2x + 7.',
'f(g(x)) = 2(x + 4) − 1 = 2x + 7.',
'f(g(x)) = 2(x + 4) − 1 = 2x + 7.',50),
('P1-FUN-03','P1FUN03-L02','learning','easy',
'Let f(x) = x² and g(x) = x − 3. Find (f ∘ g)(2).',
'Пусть f(x) = x² и g(x) = x − 3. Найдите (f ∘ g)(2).',
'f(x) = x² va g(x) = x − 3 bo‘lsin. (f ∘ g)(2) ni toping.',
'["1","−1","25","−5"]','["1","−1","25","−5"]','["1","−1","25","−5"]','A',
'g(2) = −1, then f(−1) = (−1)² = 1.',
'g(2) = −1, затем f(−1) = (−1)² = 1.',
'g(2) = −1, keyin f(−1) = (−1)² = 1.',50),
('P1-FUN-03','P1FUN03-L03','learning','medium',
'Let f(x) = √x and g(x) = x − 5. What is the real domain of (f ∘ g)(x)?',
'Пусть f(x) = √x и g(x) = x − 5. Какова действительная область определения (f ∘ g)(x)?',
'f(x) = √x va g(x) = x − 5 bo‘lsin. (f ∘ g)(x) ning haqiqiy aniqlanish sohasi qanday?',
'["x > 5","x ≤ 5","x ≥ 5","all real x"]',
'["x > 5","x ≤ 5","x ≥ 5","все действительные x"]',
'["x > 5","x ≤ 5","x ≥ 5","barcha haqiqiy x"]','C',
'f(g(x)) = √(x − 5). For real values, x − 5 ≥ 0, so x ≥ 5.',
'f(g(x)) = √(x − 5). Для действительных значений x − 5 ≥ 0, поэтому x ≥ 5.',
'f(g(x)) = √(x − 5). Haqiqiy qiymatlar uchun x − 5 ≥ 0, demak x ≥ 5.',60),
('P1-FUN-03','P1FUN03-R01','retest','medium',
'Let f(x) = 3x + 2 and g(x) = 2x. Find (g ∘ f)(x).',
'Пусть f(x) = 3x + 2 и g(x) = 2x. Найдите (g ∘ f)(x).',
'f(x) = 3x + 2 va g(x) = 2x bo‘lsin. (g ∘ f)(x) ni toping.',
'["6x + 2","6x + 4","3x + 4","6x"]','["6x + 2","6x + 4","3x + 4","6x"]','["6x + 2","6x + 4","3x + 4","6x"]','B',
'g(f(x)) = 2(3x + 2) = 6x + 4.',
'g(f(x)) = 2(3x + 2) = 6x + 4.',
'g(f(x)) = 2(3x + 2) = 6x + 4.',55),
('P1-FUN-03','P1FUN03-R02','retest','medium',
'Let f(x) = 1/x and g(x) = x − 2. Which restriction is required for (f ∘ g)(x)?',
'Пусть f(x) = 1/x и g(x) = x − 2. Какое ограничение требуется для (f ∘ g)(x)?',
'f(x) = 1/x va g(x) = x − 2 bo‘lsin. (f ∘ g)(x) uchun qaysi cheklov kerak?',
'["x ≠ 0","x ≥ 2","x ≠ −2","x ≠ 2"]',
'["x ≠ 0","x ≥ 2","x ≠ −2","x ≠ 2"]',
'["x ≠ 0","x ≥ 2","x ≠ −2","x ≠ 2"]','D',
'f(g(x)) = 1/(x − 2), so x − 2 cannot be zero. Hence x ≠ 2.',
'f(g(x)) = 1/(x − 2), поэтому x − 2 не может быть нулём. Значит x ≠ 2.',
'f(g(x)) = 1/(x − 2), shuning uchun x − 2 nol bo‘la olmaydi. Demak x ≠ 2.',55),
('P1-FUN-03','P1FUN03-M01','mixed','medium',
'Let f(x) = x² with domain x ≥ 0 and g(x) = x − 2. Which description of (g ∘ f) is correct?',
'Пусть f(x) = x² с областью x ≥ 0, а g(x) = x − 2. Какое описание (g ∘ f) верно?',
'f(x) = x², uning sohasi x ≥ 0, g(x) = x − 2 bo‘lsin. (g ∘ f) ning qaysi tavsifi to‘g‘ri?',
'["x² + 2, domain x ≥ 0","(x − 2)², all real x","x² − 2, domain x ≥ 0","x² − 2, all real x"]',
'["x² + 2, область x ≥ 0","(x − 2)², все действительные x","x² − 2, область x ≥ 0","x² − 2, все действительные x"]',
'["x² + 2, soha x ≥ 0","(x − 2)², barcha haqiqiy x","x² − 2, soha x ≥ 0","x² − 2, barcha haqiqiy x"]','C',
'g(f(x)) = g(x²) = x² − 2. The composite inherits the stated domain of f, so x ≥ 0.',
'g(f(x)) = g(x²) = x² − 2. Композиция сохраняет заданную область f, поэтому x ≥ 0.',
'g(f(x)) = g(x²) = x² − 2. Kompozitsiya f ning berilgan sohasini saqlaydi, demak x ≥ 0.',70),

-- P1-FUN-04: one-one and inverse functions
('P1-FUN-04','P1FUN04-D01','diagnostic','medium',
'If f(x) = 2x − 3, which formula is f⁻¹(x)?',
'Если f(x) = 2x − 3, какая формула задаёт f⁻¹(x)?',
'f(x) = 2x − 3 bo‘lsa, f⁻¹(x) qaysi formula?',
'["(x + 3)/2","(x − 3)/2","2x + 3","2(x + 3)"]',
'["(x + 3)/2","(x − 3)/2","2x + 3","2(x + 3)"]',
'["(x + 3)/2","(x − 3)/2","2x + 3","2(x + 3)"]','A',
'Write y = 2x − 3, swap x and y, then solve x = 2y − 3 for y: y = (x + 3)/2.',
'Запишите y = 2x − 3, поменяйте x и y местами и решите x = 2y − 3 относительно y: y = (x + 3)/2.',
'y = 2x − 3 ni yozing, x va y ni almashtiring, so‘ng x = 2y − 3 ni y bo‘yicha yeching: y = (x + 3)/2.',65),
('P1-FUN-04','P1FUN04-L01','learning','easy',
'If f(x) = 3x + 5, find f⁻¹(x).',
'Если f(x) = 3x + 5, найдите f⁻¹(x).',
'f(x) = 3x + 5 bo‘lsa, f⁻¹(x) ni toping.',
'["(x + 5)/3","(x − 5)/3","3x − 5","(5 − x)/3"]',
'["(x + 5)/3","(x − 5)/3","3x − 5","(5 − x)/3"]',
'["(x + 5)/3","(x − 5)/3","3x − 5","(5 − x)/3"]','B',
'y = 3x + 5 gives x = (y − 5)/3, so f⁻¹(x) = (x − 5)/3.',
'y = 3x + 5 даёт x = (y − 5)/3, поэтому f⁻¹(x) = (x − 5)/3.',
'y = 3x + 5 dan x = (y − 5)/3, demak f⁻¹(x) = (x − 5)/3.',50),
('P1-FUN-04','P1FUN04-L02','learning','medium',
'Let f(x) = x² with domain x ≥ 0. Which is the inverse function?',
'Пусть f(x) = x² с областью x ≥ 0. Какая функция является обратной?',
'f(x) = x², sohasi x ≥ 0 bo‘lsin. Qaysi funksiya teskari funksiya?',
'["−√x for x ≥ 0","±√x for all real x","√x for x ≥ 0","x² for x ≥ 0"]',
'["−√x при x ≥ 0","±√x для всех действительных x","√x при x ≥ 0","x² при x ≥ 0"]',
'["−√x, x ≥ 0","±√x, barcha haqiqiy x","√x, x ≥ 0","x², x ≥ 0"]','C',
'The restriction x ≥ 0 makes f one-one. Reversing y = x² on that branch gives x = √y, so f⁻¹(x) = √x with x ≥ 0.',
'Ограничение x ≥ 0 делает f взаимно однозначной. Обращая y = x² на этой ветви, получаем x = √y, поэтому f⁻¹(x) = √x при x ≥ 0.',
'x ≥ 0 cheklovi f ni bir qiymatli teskari funksiyaga ega qiladi. Shu tarmoqda y = x² ni teskari aylantirsak x = √y, demak f⁻¹(x) = √x, x ≥ 0.',65),
('P1-FUN-04','P1FUN04-L03','learning','hard',
'Let f(x) = (x − 1)/(x + 2), x ≠ −2. Which formula and domain describe f⁻¹(x)?',
'Пусть f(x) = (x − 1)/(x + 2), x ≠ −2. Какая формула и область задают f⁻¹(x)?',
'f(x) = (x − 1)/(x + 2), x ≠ −2 bo‘lsin. f⁻¹(x) uchun qaysi formula va soha to‘g‘ri?',
'["(1 + 2x)/(1 − x), x ≠ 1","(1 − 2x)/(1 + x), x ≠ −1","(x + 2)/(x − 1), x ≠ 1","(1 + 2x)/(1 − x), x ≠ −2"]',
'["(1 + 2x)/(1 − x), x ≠ 1","(1 − 2x)/(1 + x), x ≠ −1","(x + 2)/(x − 1), x ≠ 1","(1 + 2x)/(1 − x), x ≠ −2"]',
'["(1 + 2x)/(1 − x), x ≠ 1","(1 − 2x)/(1 + x), x ≠ −1","(x + 2)/(x − 1), x ≠ 1","(1 + 2x)/(1 − x), x ≠ −2"]','A',
'From y = (x − 1)/(x + 2): yx + 2y = x − 1, so x(y − 1) = −1 − 2y and x = (1 + 2y)/(1 − y). The inverse cannot take input 1.',
'Из y = (x − 1)/(x + 2): yx + 2y = x − 1, значит x(y − 1) = −1 − 2y и x = (1 + 2y)/(1 − y). В обратную функцию нельзя подставлять 1.',
'y = (x − 1)/(x + 2) dan yx + 2y = x − 1, demak x(y − 1) = −1 − 2y va x = (1 + 2y)/(1 − y). Teskari funksiyada kirish 1 bo‘la olmaydi.',85),
('P1-FUN-04','P1FUN04-R01','retest','medium',
'If f(x) = 5 − 2x, find f⁻¹(x).',
'Если f(x) = 5 − 2x, найдите f⁻¹(x).',
'f(x) = 5 − 2x bo‘lsa, f⁻¹(x) ni toping.',
'["(x − 5)/2","2x − 5","5 − 2x","(5 − x)/2"]',
'["(x − 5)/2","2x − 5","5 − 2x","(5 − x)/2"]',
'["(x − 5)/2","2x − 5","5 − 2x","(5 − x)/2"]','D',
'x = 5 − 2y gives 2y = 5 − x, so y = (5 − x)/2.',
'x = 5 − 2y даёт 2y = 5 − x, поэтому y = (5 − x)/2.',
'x = 5 − 2y dan 2y = 5 − x, demak y = (5 − x)/2.',55),
('P1-FUN-04','P1FUN04-R02','retest','easy',
'If f(x) = (x + 4)/3, find f⁻¹(x).',
'Если f(x) = (x + 4)/3, найдите f⁻¹(x).',
'f(x) = (x + 4)/3 bo‘lsa, f⁻¹(x) ni toping.',
'["3x + 4","3x − 4","(x − 4)/3","(x + 3)/4"]',
'["3x + 4","3x − 4","(x − 4)/3","(x + 3)/4"]',
'["3x + 4","3x − 4","(x − 4)/3","(x + 3)/4"]','B',
'y = (x + 4)/3 gives x = 3y − 4, hence f⁻¹(x) = 3x − 4.',
'y = (x + 4)/3 даёт x = 3y − 4, поэтому f⁻¹(x) = 3x − 4.',
'y = (x + 4)/3 dan x = 3y − 4, demak f⁻¹(x) = 3x − 4.',50),
('P1-FUN-04','P1FUN04-M01','mixed','medium',
'For f(x) = x², which restriction gives the inverse f⁻¹(x) = √x?',
'Для f(x) = x² какое ограничение даёт обратную функцию f⁻¹(x) = √x?',
'f(x) = x² uchun qaysi cheklov f⁻¹(x) = √x teskari funksiyani beradi?',
'["x ≥ 0","x ≤ 0","x ≠ 0","all real x"]',
'["x ≥ 0","x ≤ 0","x ≠ 0","все действительные x"]',
'["x ≥ 0","x ≤ 0","x ≠ 0","barcha haqiqiy x"]','A',
'Restricting the original function to x ≥ 0 selects the positive branch, whose inverse is √x.',
'Ограничение исходной функции x ≥ 0 выбирает положительную ветвь, обратной к которой является √x.',
'Asl funksiyani x ≥ 0 bilan cheklash musbat tarmoqni tanlaydi; uning teskari funksiyasi √x.',60),

-- P1-FUN-05: graph of a function and its inverse
('P1-FUN-05','P1FUN05-D01','diagnostic','medium',
'The point (2, 5) lies on the graph of a one-one function y = f(x). Which point must lie on y = f⁻¹(x)?',
'Точка (2, 5) лежит на графике взаимно однозначной функции y = f(x). Какая точка обязана лежать на y = f⁻¹(x)?',
'(2, 5) nuqta bir qiymatli y = f(x) grafikda yotadi. y = f⁻¹(x) grafikda qaysi nuqta albatta yotadi?',
'["(5, 2)","(−2, 5)","(2, −5)","(−5, −2)"]',
'["(5, 2)","(−2, 5)","(2, −5)","(−5, −2)"]',
'["(5, 2)","(−2, 5)","(2, −5)","(−5, −2)"]','A',
'Taking an inverse swaps input and output. The point map is (x, y) → (y, x), so (2, 5) becomes (5, 2).',
'При переходе к обратной функции аргумент и значение меняются местами. Отображение точки: (x, y) → (y, x), поэтому (2, 5) переходит в (5, 2).',
'Teskari funksiyada kirish va chiqish o‘rin almashadi. Nuqta qoidasi (x, y) → (y, x), shuning uchun (2, 5) → (5, 2).',60),
('P1-FUN-05','P1FUN05-L01','learning','easy',
'If f(3) = 7 for a one-one function, what is f⁻¹(7)?',
'Если f(3) = 7 для взаимно однозначной функции, чему равно f⁻¹(7)?',
'Bir qiymatli funksiya uchun f(3) = 7 bo‘lsa, f⁻¹(7) nechaga teng?',
'["7","3","−3","1/3"]','["7","3","−3","1/3"]','["7","3","−3","1/3"]','B',
'An inverse reverses the mapping 3 → 7, so it maps 7 → 3.',
'Обратная функция обращает соответствие 3 → 7, поэтому 7 → 3.',
'Teskari funksiya 3 → 7 moslikni teskarisiga aylantiradi, demak 7 → 3.',45),
('P1-FUN-05','P1FUN05-L02','learning','easy',
'The graph of y = f⁻¹(x) is the reflection of y = f(x) in which line?',
'График y = f⁻¹(x) является отражением y = f(x) относительно какой прямой?',
'y = f⁻¹(x) grafigi y = f(x) grafigining qaysi chiziqqa nisbatan aksidir?',
'["x = 0","y = 0","y = x","y = −x"]',
'["x = 0","y = 0","y = x","y = −x"]',
'["x = 0","y = 0","y = x","y = −x"]','C',
'Swapping every point (x, y) to (y, x) is exactly reflection in the line y = x.',
'Замена каждой точки (x, y) на (y, x) является отражением относительно прямой y = x.',
'Har bir (x, y) nuqtani (y, x) ga almashtirish aynan y = x chizig‘iga nisbatan akslantirishdir.',45),
('P1-FUN-05','P1FUN05-L03','learning','medium',
'A one-one function satisfies f(4) = 4. What must be true?',
'Взаимно однозначная функция удовлетворяет f(4) = 4. Что обязательно верно?',
'Bir qiymatli funksiya f(4) = 4 ni qanoatlantiradi. Qaysi fikr albatta to‘g‘ri?',
'["f⁻¹(4) = 4","f⁻¹(4) = −4","f⁻¹(4) = 1/4","the inverse is undefined at 4"]',
'["f⁻¹(4) = 4","f⁻¹(4) = −4","f⁻¹(4) = 1/4","обратная функция не определена при 4"]',
'["f⁻¹(4) = 4","f⁻¹(4) = −4","f⁻¹(4) = 1/4","teskari funksiya 4 da aniqlanmagan"]','A',
'The mapping 4 → 4 reverses to the same mapping. The point (4,4) lies on y = x and is fixed by reflection.',
'Соответствие 4 → 4 при обращении не меняется. Точка (4,4) лежит на y = x и остаётся на месте при отражении.',
'4 → 4 moslik teskari aylantirilganda ham o‘zgarmaydi. (4,4) nuqta y = x da yotadi va akslantirishda joyida qoladi.',55),
('P1-FUN-05','P1FUN05-R01','retest','medium',
'The point (−1, 6) lies on y = f(x). Which point lies on y = f⁻¹(x)?',
'Точка (−1, 6) лежит на y = f(x). Какая точка лежит на y = f⁻¹(x)?',
'(−1, 6) nuqta y = f(x) da yotadi. y = f⁻¹(x) da qaysi nuqta yotadi?',
'["(−6, 1)","(1, −6)","(−1, 6)","(6, −1)"]',
'["(−6, 1)","(1, −6)","(−1, 6)","(6, −1)"]',
'["(−6, 1)","(1, −6)","(−1, 6)","(6, −1)"]','D',
'The inverse swaps coordinates: (−1,6) → (6,−1).',
'Обратная функция меняет координаты местами: (−1,6) → (6,−1).',
'Teskari funksiya koordinatalarni almashtiradi: (−1,6) → (6,−1).',50),
('P1-FUN-05','P1FUN05-R02','retest','medium',
'A one-one function f has range [2, ∞). What is the domain of f⁻¹?',
'Взаимно однозначная функция f имеет область значений [2, ∞). Какова область определения f⁻¹?',
'Bir qiymatli f funksiyaning qiymatlar sohasi [2, ∞). f⁻¹ ning aniqlanish sohasi qanday?',
'["(−∞, 2]","[2, ∞)","all real numbers","(2, ∞)"]',
'["(−∞, 2]","[2, ∞)","все действительные числа","(2, ∞)"]',
'["(−∞, 2]","[2, ∞)","barcha haqiqiy sonlar","(2, ∞)"]','B',
'The range of f becomes the domain of f⁻¹, so the inverse domain is [2, ∞).',
'Область значений f становится областью определения f⁻¹, поэтому это [2, ∞).',
'f ning qiymatlar sohasi f⁻¹ ning aniqlanish sohasiga aylanadi, demak [2, ∞).',55),
('P1-FUN-05','P1FUN05-M01','mixed','hard',
'For f(x) = 2x + 3, the graphs of y = f(x) and y = f⁻¹(x) intersect at which point?',
'Для f(x) = 2x + 3 графики y = f(x) и y = f⁻¹(x) пересекаются в какой точке?',
'f(x) = 2x + 3 uchun y = f(x) va y = f⁻¹(x) grafiklari qaysi nuqtada kesishadi?',
'["(3, 3)","(−3/2, −3/2)","(−3, −3)","(0, 3)"]',
'["(3, 3)","(−3/2, −3/2)","(−3, −3)","(0, 3)"]',
'["(3, 3)","(−3/2, −3/2)","(−3, −3)","(0, 3)"]','C',
'A function and its inverse are reflections in y = x, so their fixed intersection satisfies f(x) = x. Solve 2x + 3 = x to get x = −3, hence (−3,−3).',
'Функция и её обратная отражены относительно y = x, поэтому фиксированная точка пересечения удовлетворяет f(x) = x. Из 2x + 3 = x получаем x = −3, то есть (−3,−3).',
'Funksiya va uning teskarisi y = x ga nisbatan aksdir, shuning uchun o‘zgarmas kesishish nuqtasi f(x) = x ni qanoatlantiradi. 2x + 3 = x dan x = −3, demak (−3,−3).',75)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Functions',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw09_12_functions_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw09_12_functions_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw09_12_functions_v1' and component_code='P1' and status='draft'), keys(k,skill,role) as (values
('P1FUN03-D01','P1-FUN-03','diagnostic'),('P1FUN03-L01','P1-FUN-03','learning'),('P1FUN03-L02','P1-FUN-03','learning'),('P1FUN03-L03','P1-FUN-03','learning'),('P1FUN03-R01','P1-FUN-03','retest'),('P1FUN03-R02','P1-FUN-03','retest'),('P1FUN03-M01','P1-FUN-03','mixed'),
('P1FUN04-D01','P1-FUN-04','diagnostic'),('P1FUN04-L01','P1-FUN-04','learning'),('P1FUN04-L02','P1-FUN-04','learning'),('P1FUN04-L03','P1-FUN-04','learning'),('P1FUN04-R01','P1-FUN-04','retest'),('P1FUN04-R02','P1-FUN-04','retest'),('P1FUN04-M01','P1-FUN-04','mixed'),
('P1FUN05-D01','P1-FUN-05','diagnostic'),('P1FUN05-L01','P1-FUN-05','learning'),('P1FUN05-L02','P1-FUN-05','learning'),('P1FUN05-L03','P1-FUN-05','learning'),('P1FUN05-R01','P1-FUN-05','retest'),('P1FUN05-R02','P1-FUN-05','retest'),('P1FUN05-M01','P1-FUN-05','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, numbers, distractors, answer and explanation; no Cambridge/coursebook question, diagram or mark-scheme wording copied.','Authored for p1_aw09_12_functions_v1 from canonical function skill intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.2 Functions','Complete Pure Mathematics 1, Ch2 Functions pp.21-47 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw09_12_functions_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

do $$ declare v_id bigint; v_cfg private.exam_prep_feature_config%rowtype; begin
  select id into v_id from private.exam_prep_content_versions where content_version='p1_aw09_12_functions_v1';
  if v_id is null then raise exception 'P1-02 AW9-12 functions seed: content version missing'; end if;
  if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id)<>21 then raise exception 'P1-02 AW9-12 functions seed: expected 21 governed questions'; end if;
  if (select count(*) from public.questions where book_ref like 'ExamPrep:P1:p1_aw09_12_functions_v1:%')<>21 then raise exception 'P1-02 AW9-12 functions seed: expected 21 public question rows'; end if;
  select * into v_cfg from private.exam_prep_feature_config where id=1;
  if v_cfg.rollout_state<>'off' or v_cfg.core_enabled or v_cfg.ai_enabled or v_cfg.mentor_enabled or not v_cfg.kill_switch then raise exception 'P1-02 AW9-12 functions seed escaped fail-closed'; end if;
end $$;
commit;