-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 4; rows 43-56 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(43,'P1','1.8 Integration','P1-INT-03','Вычислять definite integrals, включая простой improper endpoint case из P1.','P1-INT-01; PR-CAL-01','Complete Pure Mathematics 1, Ch10 Integration','pp. 173–200','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(44,'P1','1.8 Integration','P1-INT-04','Находить area между curve, axes/lines или двумя curves, разбивая region при необходимости.','P1-INT-03; P1-COO-02; P1-QUA-03','Complete Pure Mathematics 1, Ch10 Integration','pp. 173–200','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(45,'P1','1.8 Integration','P1-INT-05','Находить volume of revolution около coordinate axis с корректными limits.','P1-INT-03; P1-FUN-01; PR-ALG-03','Complete Pure Mathematics 1, Ch10 Integration','pp. 173–200','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(1,'P5','5.1 Representation of data','P5-DAT-01','Выбирать и критиковать подходящее data representation с учётом типа данных и цели.','PR-STA-01; PR-COM-01','Complete Probability & Statistics 1, Ch2–3','pp. 14–59','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(2,'P5','5.1 Representation of data','P5-DAT-02','Строить и интерпретировать stem-and-leaf diagrams, сохраняя исходные значения.','PR-STA-01; PR-ALG-01','Complete Probability & Statistics 1, Ch3 Representation of data','pp. 34–59','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(3,'P5','5.1 Representation of data','P5-DAT-03','Строить и интерпретировать box-and-whisker plots, включая outlier-aware comparison where given.','P5-DAT-05; PR-GRF-01','Complete Probability & Statistics 1, Ch3 Representation of data','pp. 34–59','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(4,'P5','5.1 Representation of data','P5-DAT-04','Строить и интерпретировать histograms с frequency density и unequal class widths.','PR-STA-01; PR-ALG-01; PR-GRF-01','Complete Probability & Statistics 1, Ch3 Representation of data','pp. 34–59','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(5,'P5','5.1 Representation of data','P5-DAT-05','Использовать cumulative-frequency graph для quartiles, percentiles и proportions.','PR-STA-01; PR-GRF-01','Complete Probability & Statistics 1, Ch3 Representation of data','pp. 34–59','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(6,'P5','5.1 Representation of data','P5-DAT-06','Вычислять и выбирать mean, median и mode для raw/grouped data.','PR-ALG-01; PR-STA-01','Complete Probability & Statistics 1, Ch2 Measures of location and spread','pp. 14–29','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(7,'P5','5.1 Representation of data','P5-DAT-07','Вычислять и интерпретировать range, interquartile range и standard deviation.','P5-DAT-05; P5-DAT-06; PR-CAL-01','Complete Probability & Statistics 1, Ch2 Measures of location and spread','pp. 14–29','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(8,'P5','5.1 Representation of data','P5-DAT-08','Сравнивать datasets по location и spread и формулировать contextual conclusion.','P5-DAT-06; P5-DAT-07; PR-COM-01','Complete Probability & Statistics 1, Ch2–3','pp. 14–59','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(9,'P5','5.1 Representation of data','P5-DAT-09','Получать mean/standard deviation из raw, grouped или summary totals с корректными conventions.','P5-DAT-06; P5-DAT-07; PR-ALG-03','Complete Probability & Statistics 1, Ch2 Measures of location and spread','pp. 14–29','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(10,'P5','5.1 Representation of data','P5-DAT-10','Работать с coded totals и объединением/разделением двух data sets.','P5-DAT-09; PR-ALG-03','Complete Probability & Statistics 1, Ch2 Measures of location and spread','pp. 14–29','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(11,'P5','5.2 Permutations and combinations','P5-CNT-01','Различать ordered arrangements и unordered selections; применять factorial/product rule.','PR-CNT-01; PR-ALG-01','Complete Probability & Statistics 1, Ch6 Permutations and combinations','pp. 98–111','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
