-- P1-02 original iClub content: P5-DAT-02 stem-and-leaf construction/interpretation.
-- New P5 version only; p5_repr_beta_v1 is not mutated. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_dat02_runway_v1' and component_code='P5' and status='draft'),
src(k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P5DAT02-D01','diagnostic','medium','A stem-and-leaf diagram has 1 | 2 4 7 and 2 | 1 3, with key 1 | 2 = 12. Which data set does it represent?','Диаграмма «стебель-листья» содержит 1 | 2 4 7 и 2 | 1 3, ключ 1 | 2 = 12. Какой набор данных она представляет?','Poya-barg diagrammasida 1 | 2 4 7 va 2 | 1 3 berilgan, kalit 1 | 2 = 12. U qaysi ma’lumotlar to‘plamini ifodalaydi?','["12, 14, 17, 21, 23","1.2, 1.4, 1.7, 2.1, 2.3","12, 24, 27, 21, 23","2, 4, 7, 1, 3"]','A','The stem gives the tens digit and each leaf gives the units digit, so the values are 12, 14, 17, 21 and 23.','Стебель задаёт десятки, а лист — единицы, поэтому значения: 12, 14, 17, 21 и 23.','Poya o‘nlik xonasini, barg esa birlik xonasini beradi; qiymatlar 12, 14, 17, 21 va 23.',65),
('P5DAT02-L01','learning','easy','With key 2 | 3 = 23, what value is represented by leaf 3 on stem 2?','При ключе 2 | 3 = 23 какое значение представляет лист 3 у стебля 2?','Kalit 2 | 3 = 23 bo‘lsa, 2 poyadagi 3 barg qaysi qiymatni bildiradi?','["5","6","23","32"]','C','The key states directly that stem 2 and leaf 3 represent 23.','Ключ прямо показывает, что стебель 2 и лист 3 означают 23.','Kalit 2 poya va 3 barg 23 ni bildirishini to‘g‘ridan-to‘g‘ri ko‘rsatadi.',45),
('P5DAT02-L02','learning','medium','Which stem-and-leaf diagram correctly represents 31, 34, 34, 38, 42 with key 3 | 1 = 31?','Какая диаграмма «стебель-листья» правильно представляет 31, 34, 34, 38, 42 при ключе 3 | 1 = 31?','Kalit 3 | 1 = 31 bo‘lsa, qaysi poya-barg diagrammasi 31, 34, 34, 38, 42 ni to‘g‘ri ifodalaydi?','["3 | 1 4 4 8; 4 | 2","3 | 1 4 8; 4 | 2 4","3 | 1 3 4 8; 4 | 2","3 | 1 4 4; 4 | 2 8"]','A','The 30s leaves are 1, 4, 4, 8 and the 40s leaf is 2; the repeated 34 must appear twice.','Для чисел из 30-х листья 1, 4, 4, 8, а для 40-х — лист 2; повторяющееся 34 должно быть записано дважды.','30-lik qiymatlar uchun barglar 1, 4, 4, 8, 40-lik uchun barg 2; takrorlangan 34 ikki marta yoziladi.',65),
('P5DAT02-L03','learning','medium','A diagram with key 1 | 2 = 12 has 1 | 2 5 8 and 2 | 0 3 7. What is the median?','Диаграмма с ключом 1 | 2 = 12 содержит 1 | 2 5 8 и 2 | 0 3 7. Найдите медиану.','Kalit 1 | 2 = 12 bo‘lgan diagrammada 1 | 2 5 8 va 2 | 0 3 7 berilgan. Medianani toping.','["18","19","20","21.5"]','B','The ordered values are 12, 15, 18, 20, 23, 27. The median is (18 + 20)/2 = 19.','Упорядоченные значения: 12, 15, 18, 20, 23, 27. Медиана равна (18 + 20)/2 = 19.','Tartiblangan qiymatlar 12, 15, 18, 20, 23, 27. Mediana (18 + 20)/2 = 19.',70),
('P5DAT02-R01','retest','easy','With key 4 | 7 = 47, what observation is shown by stem 4 and leaf 7?','При ключе 4 | 7 = 47 какое наблюдение показывает стебель 4 и лист 7?','Kalit 4 | 7 = 47 bo‘lsa, 4 poya va 7 barg qaysi kuzatuvni bildiradi?','["11","28","47","74"]','C','The key defines 4 | 7 as 47.','Ключ определяет 4 | 7 как 47.','Kalit 4 | 7 ni 47 deb belgilaydi.',45),
('P5DAT02-R02','retest','medium','A diagram with key 2 | 1 = 21 has 2 | 1 5 and 3 | 0 2 9. What is the range?','Диаграмма с ключом 2 | 1 = 21 содержит 2 | 1 5 и 3 | 0 2 9. Найдите размах.','Kalit 2 | 1 = 21 bo‘lgan diagrammada 2 | 1 5 va 3 | 0 2 9 berilgan. Oraliq kengligini toping.','["14","18","21","39"]','B','The smallest value is 21 and the largest is 39, so the range is 39 − 21 = 18.','Минимум 21, максимум 39, поэтому размах 39 − 21 = 18.','Eng kichik qiymat 21, eng katta 39; oraliq kengligi 39 − 21 = 18.',60),
('P5DAT02-M01','mixed','medium','The observations 24, 21 and 29 must be entered on stem 2. Which leaf row is correct?','Наблюдения 24, 21 и 29 нужно записать у стебля 2. Какая строка листьев верна?','24, 21 va 29 kuzatuvlarini 2 poyaga yozish kerak. Qaysi barglar qatori to‘g‘ri?','["1 4 9","4 1 9","2 4 9","1 2 9"]','A','Leaves are the units digits and are conventionally ordered, giving 1, 4, 9.','Листья — это цифры единиц, которые принято располагать по порядку: 1, 4, 9.','Barglar birlik raqamlaridir va odatda tartib bilan yoziladi: 1, 4, 9.',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Representation of Data','P5-DAT-02',s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P5:p5_dat02_runway_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_dat02_runway_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p5_dat02_runway_v1' and component_code='P5' and status='draft'),
keys(k,role) as (values('P5DAT02-D01','diagnostic'),('P5DAT02-L01','learning'),('P5DAT02-L02','learning'),('P5DAT02-L03','learning'),('P5DAT02-R01','retest'),('P5DAT02-R02','retest'),('P5DAT02-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DAT-02','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, data, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored for p5_dat02_runway_v1 from canonical P5-DAT-02 intent using independent examples.','Cambridge 9709 2026-2027 v4; P5 5.1 Representation of Data','Complete Probability & Statistics 1, Representation of Data chapter (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_dat02_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
commit;
