-- P1-02 original iClub content: P1-QUA-01.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (
  select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'
), src(k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1QUA01-D01','diagnostic','medium','Write x² − 6x + 11 in completed-square form.','Запишите x² − 6x + 11 в форме полного квадрата.','x² − 6x + 11 ifodani to‘liq kvadrat ko‘rinishida yozing.','["(x − 3)² + 2","(x − 3)² + 11","(x + 3)² + 2","(x − 6)² − 25"]','A','x² − 6x + 11 = (x − 3)² − 9 + 11 = (x − 3)² + 2.','x² − 6x + 11 = (x − 3)² − 9 + 11 = (x − 3)² + 2.','x² − 6x + 11 = (x − 3)² − 9 + 11 = (x − 3)² + 2.',70),
('P1QUA01-L01','learning','easy','Write x² + 8x + 19 in completed-square form.','Запишите x² + 8x + 19 в форме полного квадрата.','x² + 8x + 19 ifodani to‘liq kvadrat ko‘rinishida yozing.','["(x + 4)² + 3","(x + 4)² + 19","(x − 4)² + 3","(x + 8)² − 45"]','A','x² + 8x + 19 = (x + 4)² − 16 + 19 = (x + 4)² + 3.','x² + 8x + 19 = (x + 4)² − 16 + 19 = (x + 4)² + 3.','x² + 8x + 19 = (x + 4)² − 16 + 19 = (x + 4)² + 3.',55),
('P1QUA01-L02','learning','medium','Find the vertex of y = 2x² − 12x + 7.','Найдите вершину графика y = 2x² − 12x + 7.','y = 2x² − 12x + 7 grafigining uchini toping.','["(3, −11)","(−3, −11)","(3, 7)","(6, −29)"]','A','y = 2(x − 3)² − 11, so the vertex is (3, −11).','y = 2(x − 3)² − 11, поэтому вершина равна (3, −11).','y = 2(x − 3)² − 11, shuning uchun grafik uchi (3, −11).',65),
('P1QUA01-L03','learning','medium','What is the minimum value of x² − 10x + 31?','Каково минимальное значение x² − 10x + 31?','x² − 10x + 31 ifodaning eng kichik qiymati nechaga teng?','["5","6","25","31"]','B','x² − 10x + 31 = (x − 5)² + 6. Since a square is at least 0, the minimum is 6.','x² − 10x + 31 = (x − 5)² + 6. Квадрат неотрицателен, поэтому минимум равен 6.','x² − 10x + 31 = (x − 5)² + 6. Kvadrat manfiy bo‘lmaydi, demak minimum 6.',65),
('P1QUA01-R01','retest','medium','Write x² + 4x − 5 in completed-square form.','Запишите x² + 4x − 5 в форме полного квадрата.','x² + 4x − 5 ifodani to‘liq kvadrat ko‘rinishida yozing.','["(x + 2)² − 9","(x + 2)² − 5","(x − 2)² − 9","(x + 4)² − 21"]','A','x² + 4x − 5 = (x + 2)² − 4 − 5 = (x + 2)² − 9.','x² + 4x − 5 = (x + 2)² − 4 − 5 = (x + 2)² − 9.','x² + 4x − 5 = (x + 2)² − 4 − 5 = (x + 2)² − 9.',65),
('P1QUA01-R02','retest','medium','Find the vertex of y = −x² + 6x − 4.','Найдите вершину графика y = −x² + 6x − 4.','y = −x² + 6x − 4 grafigining uchini toping.','["(3, 5)","(−3, 5)","(3, −4)","(6, −4)"]','A','y = −(x − 3)² + 5, so the vertex is (3, 5).','y = −(x − 3)² + 5, поэтому вершина равна (3, 5).','y = −(x − 3)² + 5, shuning uchun grafik uchi (3, 5).',65),
('P1QUA01-M01','mixed','medium','For any real k, what is the minimum value of x² − 2kx + k² + 4?','Для любого действительного k найдите минимальное значение x² − 2kx + k² + 4.','Har qanday haqiqiy k uchun x² − 2kx + k² + 4 ifodaning eng kichik qiymatini toping.','["0","4","k²","k² + 4"]','B','x² − 2kx + k² + 4 = (x − k)² + 4, so its minimum is 4.','x² − 2kx + k² + 4 = (x − k)² + 4, поэтому минимум равен 4.','x² − 2kx + k² + 4 = (x − k)² + 4, demak minimum 4.',75)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Quadratics','P1-QUA-01',s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_foundations_runway_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
keys(k,role) as (values('P1QUA01-D01','diagnostic'),('P1QUA01-L01','learning'),('P1QUA01-L02','learning'),('P1QUA01-L03','learning'),('P1QUA01-R01','retest'),('P1QUA01-R02','retest'),('P1QUA01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-QUA-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, numbers, distractors, answer and explanation; no Cambridge/coursebook question, diagram or mark-scheme wording copied.','Authored for p1_foundations_runway_v1 from canonical P1-QUA-01 intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.1 Quadratics','Complete Pure Mathematics 1, Ch1 Quadratics pp.2-20 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

commit;
