-- AI-4 Economics Practice 1 deterministic diagnostic batch: Chapter 9.
-- Adds deterministic diagnostics for five MCQs and three numeric-input PES questions.
-- Server scoring remains authoritative; diagnostics only explain the checked result.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,topic,subtopic,qtype,correct_answer,options_en) as (
    values
    (1087,'Elasticity','Price elasticity of supply','mcq','A','["firms can adjust output quickly","inputs are fixed forever","there is no spare capacity","time period is very short"]'::jsonb),
    (1095,'Elasticity','Calculating PES','input','2',null::jsonb),
    (1103,'Elasticity','Interpreting PES numerically','input','3',null::jsonb),
    (1104,'Elasticity','Determinants of PES','mcq','A','["Spare capacity and ability to store goods","Very long production time and fixed capacity","Perishable goods with no storage","No availability of extra inputs"]'::jsonb),
    (1113,'Elasticity','PES: short run and long run','mcq','A','["Firms have more time to change capacity and adjust inputs","Demand becomes perfectly elastic","Prices are fixed in the long run","Opportunity cost disappears"]'::jsonb),
    (1119,'Elasticity','Time and PES','mcq','C','["Have no spare capacity","Cannot hire extra workers","Can increase capacity and adjust inputs quickly","Face perfectly inelastic demand"]'::jsonb),
    (1120,'Elasticity','Calculating PES (input)','input','2',null::jsonb),
    (1132,'Elasticity','PES in the long run','mcq','C','["Because demand becomes inelastic","Because firms can increase land supply instantly","Because construction capacity, planning and entry can adjust over time","Because prices stop changing"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>7
     or q.is_active is not true
     or q.quality_status<>'published'
     or lower(coalesce(q.qtype,''))<>e.qtype
     or q.topic<>e.topic
     or q.subtopic<>e.subtopic
     or upper(trim(coalesce(q.correct_answer,'')))<>upper(e.correct_answer)
     or (e.qtype='mcq' and coalesce(q.options_text_en,'[]')::jsonb is distinct from e.options_en)
     or (e.qtype='input' and q.options_text_en is not null);

  if v_bad<>0 then
    raise exception 'AI-4 diagnostic batch refused: one or more Chapter 9 questions changed';
  end if;

  if exists (
    select 1 from public.question_answer_diagnostics
    where question_id in (1087,1095,1103,1104,1113,1119,1120,1132)
      and quality_status='published'
  ) then
    raise exception 'AI-4 diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1087,'mcq_option','A','firms can adjust output quickly',true,null,null,
 'Верно: предложение более эластично, когда фирмы могут быстро изменить объём выпуска в ответ на изменение цены.',
 'To‘g‘ri: firmalar narx o‘zgarishiga javoban ishlab chiqarish hajmini tez o‘zgartira olsa, taklif elastikroq bo‘ladi.',
 'Correct: supply is more elastic when firms can adjust output quickly in response to a price change.',
 'Свяжите скорость корректировки выпуска с величиной PES.',
 'Ishlab chiqarishni qanchalik tez moslashtirish mumkinligini PES bilan bog‘lang.',
 'Link the speed of output adjustment to the size of PES.',
 'Elasticity','Price elasticity of supply','{}'::jsonb,'published'),
(1087,'mcq_option','B','inputs are fixed forever',false,'pes_flexibility_reversal','Input flexibility and PES',
 'Если факторы производства нельзя изменить, фирме труднее увеличить выпуск, поэтому предложение менее эластично.',
 'Agar ishlab chiqarish omillarini o‘zgartirib bo‘lmasa, firma ishlab chiqarishni oshirishda qiynaladi va taklif kamroq elastik bo‘ladi.',
 'If inputs cannot be adjusted, firms find it harder to change output, making supply less elastic.',
 'Ищите условия, которые повышают гибкость производства.',
 'Ishlab chiqarish moslashuvchanligini oshiradigan shartlarni izlang.',
 'Look for conditions that increase production flexibility.',
 'Elasticity','Price elasticity of supply','{}'::jsonb,'published'),
(1087,'mcq_option','C','there is no spare capacity',false,'spare_capacity_reversal','Spare capacity and PES',
 'Отсутствие свободных мощностей ограничивает возможность быстро нарастить выпуск и снижает PES.',
 'Bo‘sh quvvat yo‘qligi ishlab chiqarishni tez oshirish imkonini cheklaydi va PESni kamaytiradi.',
 'No spare capacity limits the ability to expand output quickly and reduces PES.',
 'Свяжите spare capacity с возможностью увеличить предложение.',
 'Bo‘sh quvvatni taklifni oshirish imkoniyati bilan bog‘lang.',
 'Link spare capacity to the ability to expand supply.',
 'Elasticity','Price elasticity of supply','{}'::jsonb,'published'),
(1087,'mcq_option','D','time period is very short',false,'time_pes_reversal','Time period and PES',
 'В очень коротком периоде фирмы обычно имеют меньше возможностей изменить выпуск, поэтому PES ниже.',
 'Juda qisqa davrda firmalarda ishlab chiqarishni o‘zgartirish imkoniyati kamroq bo‘ladi, shuning uchun PES pastroq.',
 'In a very short time period, firms usually have less ability to adjust output, so PES is lower.',
 'Повторите, почему PES обычно растёт с увеличением периода времени.',
 'Vaqt davri uzayganda PES nega odatda oshishini takrorlang.',
 'Review why PES usually rises as the time period becomes longer.',
 'Elasticity','Price elasticity of supply','{}'::jsonb,'published'),

(1095,'input_exact',null,'2',true,null,null,
 'Верно: PES = 20% ÷ 10% = 2.',
 'To‘g‘ri: PES = 20% ÷ 10% = 2.',
 'Correct: PES = 20% ÷ 10% = 2.',
 'Используйте %ΔQs ÷ %ΔP.',
 '%ΔQs ÷ %ΔP formulasidan foydalaning.',
 'Use %ΔQs ÷ %ΔP.',
 'Elasticity','Calculating PES','{"accepted":"2"}'::jsonb,'published'),
(1095,'fallback',null,null,false,'pes_formula_or_ratio_error','PES calculation',
 'Разделите процентное изменение объёма предложения на процентное изменение цены: 20 ÷ 10 = 2. Ответ должен быть только числом.',
 'Taklif miqdorining foiz o‘zgarishini narxning foiz o‘zgarishiga bo‘ling: 20 ÷ 10 = 2. Javob faqat son bo‘lishi kerak.',
 'Divide the percentage change in quantity supplied by the percentage change in price: 20 ÷ 10 = 2. Enter only the number.',
 'Повторите формулу PES и порядок числителя/знаменателя.',
 'PES formulasini va surat/maxraj tartibini takrorlang.',
 'Review the PES formula and numerator/denominator order.',
 'Elasticity','Calculating PES','{}'::jsonb,'published'),

(1103,'input_exact',null,'3',true,null,null,
 'Верно: PES = 60% ÷ 20% = 3.',
 'To‘g‘ri: PES = 60% ÷ 20% = 3.',
 'Correct: PES = 60% ÷ 20% = 3.',
 'Используйте %ΔQs ÷ %ΔP.',
 '%ΔQs ÷ %ΔP formulasidan foydalaning.',
 'Use %ΔQs ÷ %ΔP.',
 'Elasticity','Interpreting PES numerically','{"accepted":"3"}'::jsonb,'published'),
(1103,'fallback',null,null,false,'pes_formula_or_ratio_error','PES calculation',
 'PES рассчитывается как 60% ÷ 20% = 3. Не переворачивайте отношение и введите только число.',
 'PES 60% ÷ 20% = 3 tarzida hisoblanadi. Nisbatni teskari qilmang va faqat son kiriting.',
 'PES is calculated as 60% ÷ 20% = 3. Do not reverse the ratio, and enter only the number.',
 'Повторите формулу: процентное изменение Qs делится на процентное изменение P.',
 'Formulani takrorlang: Qs foiz o‘zgarishi P foiz o‘zgarishiga bo‘linadi.',
 'Review the formula: percentage change in Qs divided by percentage change in P.',
 'Elasticity','Interpreting PES numerically','{}'::jsonb,'published'),

(1104,'mcq_option','A','Spare capacity and ability to store goods',true,null,null,
 'Верно: свободные мощности и возможность хранения позволяют фирмам легче изменять объём предложения, повышая PES.',
 'To‘g‘ri: bo‘sh quvvat va saqlash imkoniyati firmalarga taklif hajmini osonroq o‘zgartirishga yordam beradi va PESni oshiradi.',
 'Correct: spare capacity and storage make it easier for firms to adjust quantity supplied, increasing PES.',
 'Свяжите производственную гибкость и хранение с эластичностью предложения.',
 'Ishlab chiqarish moslashuvchanligi va saqlashni taklif elastikligi bilan bog‘lang.',
 'Link production flexibility and storage to supply elasticity.',
 'Elasticity','Determinants of PES','{}'::jsonb,'published'),
(1104,'mcq_option','B','Very long production time and fixed capacity',false,'pes_determinant_reversal','Production constraints and PES',
 'Длительное производство и фиксированная мощность затрудняют изменение выпуска и делают предложение менее эластичным.',
 'Uzoq ishlab chiqarish va qat’iy quvvat ishlab chiqarishni o‘zgartirishni qiyinlashtiradi va taklifni kamroq elastik qiladi.',
 'Long production times and fixed capacity make output adjustment harder and supply less elastic.',
 'Ищите факторы, сокращающие время и ограничения корректировки.',
 'Moslashuv vaqtini va cheklovlarni kamaytiradigan omillarni izlang.',
 'Look for factors that reduce adjustment time and constraints.',
 'Elasticity','Determinants of PES','{}'::jsonb,'published'),
(1104,'mcq_option','C','Perishable goods with no storage',false,'storage_pes_reversal','Storability and PES',
 'Если товар нельзя хранить, фирмы имеют меньше возможностей переносить предложение между периодами, что обычно снижает PES.',
 'Tovarni saqlab bo‘lmasa, firmalar taklifni davrlar orasida ko‘chira olmaydi va bu odatda PESni kamaytiradi.',
 'If goods cannot be stored, firms have less ability to shift supply across time, which usually lowers PES.',
 'Повторите влияние storability на PES.',
 'Saqlash imkoniyatining PESga ta’sirini takrorlang.',
 'Review how storability affects PES.',
 'Elasticity','Determinants of PES','{}'::jsonb,'published'),
(1104,'mcq_option','D','No availability of extra inputs',false,'input_availability_reversal','Input availability and PES',
 'Отсутствие дополнительных ресурсов ограничивает расширение производства и снижает эластичность предложения.',
 'Qo‘shimcha resurslar mavjud bo‘lmasa, ishlab chiqarishni kengaytirish cheklanadi va taklif elastikligi pasayadi.',
 'A lack of extra inputs limits production expansion and reduces supply elasticity.',
 'Свяжите доступность ресурсов с возможностью быстро нарастить выпуск.',
 'Resurslar mavjudligini ishlab chiqarishni tez oshirish imkoniyati bilan bog‘lang.',
 'Link input availability to the ability to expand output quickly.',
 'Elasticity','Determinants of PES','{}'::jsonb,'published'),

(1113,'mcq_option','A','Firms have more time to change capacity and adjust inputs',true,null,null,
 'Верно: в долгосрочном периоде фирмы могут изменить мощности, труд и другие ресурсы, поэтому предложение обычно более эластично.',
 'To‘g‘ri: uzoq muddatda firmalar quvvat, mehnat va boshqa resurslarni o‘zgartira oladi, shuning uchun taklif odatda elastikroq.',
 'Correct: in the long run, firms have more time to change capacity, labour and other inputs, so supply is usually more elastic.',
 'Свяжите более длинный период с большей гибкостью ресурсов.',
 'Uzoqroq vaqt davrini resurslarning kattaroq moslashuvchanligi bilan bog‘lang.',
 'Link a longer time period to greater input flexibility.',
 'Elasticity','PES: short run and long run','{}'::jsonb,'published'),
(1113,'mcq_option','B','Demand becomes perfectly elastic',false,'demand_supply_elasticity_confusion','PES vs PED',
 'PES описывает реакцию предложения, а изменение эластичности спроса не является причиной более высокой PES в долгосрочном периоде.',
 'PES taklif reaksiyasini o‘lchaydi; talab elastikligining o‘zgarishi uzoq muddatdagi yuqori PESning sababi emas.',
 'PES measures supply responsiveness; demand becoming more elastic is not the reason PES is higher in the long run.',
 'Различайте PED и PES.',
 'PED va PESni farqlang.',
 'Distinguish PED from PES.',
 'Elasticity','PES: short run and long run','{}'::jsonb,'published'),
(1113,'mcq_option','C','Prices are fixed in the long run',false,'long_run_price_confusion','Long-run supply adjustment',
 'Долгосрочный период не означает фиксированные цены. Главное — больше времени для изменения факторов производства.',
 'Uzoq muddat narxlar qat’iy degani emas. Asosiy narsa — ishlab chiqarish omillarini o‘zgartirish uchun ko‘proq vaqt.',
 'The long run does not mean prices are fixed. The key is more time to adjust factors of production.',
 'Сосредоточьтесь на производственной адаптации, а не на фиксации цен.',
 'Narxlarning qat’iyligiga emas, ishlab chiqarish moslashuviga e’tibor qarating.',
 'Focus on production adjustment rather than price fixing.',
 'Elasticity','PES: short run and long run','{}'::jsonb,'published'),
(1113,'mcq_option','D','Opportunity cost disappears',false,'opportunity_cost_denial','Scarcity in the long run',
 'Альтернативная стоимость не исчезает в долгосрочном периоде; ограниченность ресурсов сохраняется.',
 'Muqobil xarajat uzoq muddatda yo‘qolmaydi; resurslar cheklanganligi saqlanadi.',
 'Opportunity cost does not disappear in the long run; resources remain scarce.',
 'Не связывайте большую PES с исчезновением ограниченности.',
 'Yuqori PESni resurslar cheklanganligi yo‘qolishi bilan bog‘lamang.',
 'Do not link higher PES to the disappearance of scarcity.',
 'Elasticity','PES: short run and long run','{}'::jsonb,'published'),

(1119,'mcq_option','A','Have no spare capacity',false,'spare_capacity_reversal','Spare capacity and PES',
 'Без свободной мощности фирме труднее увеличить выпуск, поэтому PES обычно ниже.',
 'Bo‘sh quvvat bo‘lmasa, firma ishlab chiqarishni oshirishda qiynaladi va PES odatda pastroq.',
 'Without spare capacity, firms find it harder to increase output, so PES is usually lower.',
 'Свяжите spare capacity с большей эластичностью предложения.',
 'Bo‘sh quvvatni yuqoriroq taklif elastikligi bilan bog‘lang.',
 'Link spare capacity to greater supply elasticity.',
 'Elasticity','Time and PES','{}'::jsonb,'published'),
(1119,'mcq_option','B','Cannot hire extra workers',false,'input_constraint_reversal','Input flexibility and PES',
 'Невозможность нанять дополнительных работников ограничивает изменение выпуска и снижает PES.',
 'Qo‘shimcha ishchilarni yollab bo‘lmasligi ishlab chiqarish o‘zgarishini cheklaydi va PESni pasaytiradi.',
 'Being unable to hire extra workers limits output adjustment and reduces PES.',
 'Ищите большую, а не меньшую гибкость ресурсов.',
 'Resurslarning kam emas, katta moslashuvchanligini izlang.',
 'Look for greater, not lower, input flexibility.',
 'Elasticity','Time and PES','{}'::jsonb,'published'),
(1119,'mcq_option','C','Can increase capacity and adjust inputs quickly',true,null,null,
 'Верно: способность быстро увеличить мощности и ресурсы делает предложение более чувствительным к цене.',
 'To‘g‘ri: quvvat va resurslarni tez oshira olish taklifni narx o‘zgarishiga ko‘proq sezgir qiladi.',
 'Correct: being able to expand capacity and adjust inputs quickly makes supply more responsive to price.',
 'Свяжите скорость адаптации с более высокой PES.',
 'Moslashuv tezligini yuqori PES bilan bog‘lang.',
 'Link faster adjustment to higher PES.',
 'Elasticity','Time and PES','{}'::jsonb,'published'),
(1119,'mcq_option','D','Face perfectly inelastic demand',false,'ped_pes_confusion','Demand elasticity vs supply elasticity',
 'Эластичность спроса покупателей не определяет способность фирмы изменить объём предложения.',
 'Xaridorlar talabining elastikligi firmaning taklif hajmini o‘zgartirish qobiliyatini belgilamaydi.',
 'The elasticity of buyer demand does not determine a firm’s ability to change quantity supplied.',
 'Различайте факторы PED и PES.',
 'PED va PES omillarini farqlang.',
 'Distinguish determinants of PED from determinants of PES.',
 'Elasticity','Time and PES','{}'::jsonb,'published'),

(1120,'input_exact',null,'2',true,null,null,
 'Верно: PES = 20% ÷ 10% = 2.',
 'To‘g‘ri: PES = 20% ÷ 10% = 2.',
 'Correct: PES = 20% ÷ 10% = 2.',
 'Используйте %ΔQs ÷ %ΔP.',
 '%ΔQs ÷ %ΔP formulasidan foydalaning.',
 'Use %ΔQs ÷ %ΔP.',
 'Elasticity','Calculating PES (input)','{"accepted":"2"}'::jsonb,'published'),
(1120,'fallback',null,null,false,'pes_formula_or_ratio_error','PES calculation',
 'Разделите 20% изменения объёма предложения на 10% изменения цены: PES = 2. Введите только число.',
 'Taklif miqdorining 20% o‘zgarishini narxning 10% o‘zgarishiga bo‘ling: PES = 2. Faqat son kiriting.',
 'Divide the 20% change in quantity supplied by the 10% change in price: PES = 2. Enter only the number.',
 'Повторите формулу PES.',
 'PES formulasini takrorlang.',
 'Review the PES formula.',
 'Elasticity','Calculating PES (input)','{}'::jsonb,'published'),

(1132,'mcq_option','A','Because demand becomes inelastic',false,'ped_pes_confusion','Long-run housing supply',
 'Эластичность спроса не объясняет, почему производители жилья могут сильнее изменить предложение в долгосрочном периоде.',
 'Talab elastikligi uy-joy ishlab chiqaruvchilari uzoq muddatda taklifni nega ko‘proq o‘zgartira olishini tushuntirmaydi.',
 'Demand elasticity does not explain why housing producers can adjust supply more in the long run.',
 'Сосредоточьтесь на возможностях производства и входа фирм.',
 'Ishlab chiqarish va firmalarning bozorga kirish imkoniyatlariga e’tibor qarating.',
 'Focus on production and firm-entry adjustment.',
 'Elasticity','PES in the long run','{}'::jsonb,'published'),
(1132,'mcq_option','B','Because firms can increase land supply instantly',false,'land_supply_overstatement','Housing supply constraints',
 'Землю нельзя мгновенно создать. Более высокая долгосрочная PES связана с тем, что со временем можно изменить другие мощности и процессы.',
 'Yerni bir zumda ko‘paytirib bo‘lmaydi. Uzoq muddatdagi yuqori PES vaqt o‘tishi bilan boshqa quvvat va jarayonlarni moslashtirish mumkinligi bilan bog‘liq.',
 'Land cannot be increased instantly. Higher long-run PES comes from adjusting other capacity and processes over time.',
 'Не приписывайте долгосрочную гибкость мгновенному росту земли.',
 'Uzoq muddatli moslashuvchanlikni yerning bir zumda ko‘payishi bilan bog‘lamang.',
 'Do not attribute long-run flexibility to instant expansion of land.',
 'Elasticity','PES in the long run','{}'::jsonb,'published'),
(1132,'mcq_option','C','Because construction capacity, planning and entry can adjust over time',true,null,null,
 'Верно: со временем строительные мощности, разрешения, ресурсы и вход фирм могут измениться, делая предложение более эластичным.',
 'To‘g‘ri: vaqt o‘tishi bilan qurilish quvvati, rejalashtirish, resurslar va firmalarning kirishi o‘zgarishi mumkin, bu taklifni elastikroq qiladi.',
 'Correct: over time, construction capacity, planning, resources and firm entry can adjust, making supply more elastic.',
 'Свяжите долгосрочный период с большим числом регулируемых факторов.',
 'Uzoq muddatni ko‘proq o‘zgartiriladigan omillar bilan bog‘lang.',
 'Link the long run to a larger set of adjustable factors.',
 'Elasticity','PES in the long run','{}'::jsonb,'published'),
(1132,'mcq_option','D','Because prices stop changing',false,'long_run_price_confusion','Long-run supply elasticity',
 'Цены не обязаны переставать меняться в долгосрочном периоде. Причина более высокой PES — большая производственная гибкость.',
 'Uzoq muddatda narxlar o‘zgarishni to‘xtatishi shart emas. Yuqori PES sababi — katta ishlab chiqarish moslashuvchanligi.',
 'Prices do not have to stop changing in the long run. Higher PES comes from greater production flexibility.',
 'Различайте изменение цены и способность предложения реагировать.',
 'Narx o‘zgarishi bilan taklifning javob berish qobiliyatini farqlang.',
 'Distinguish price changes from the ability of supply to respond.',
 'Elasticity','PES in the long run','{}'::jsonb,'published');