-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 5; rows 57-70 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(12,'P5','5.2 Permutations and combinations','P5-CNT-02','Считать permutations of distinct objects в line/ordered positions.','P5-CNT-01','Complete Probability & Statistics 1, Ch6 Permutations and combinations','pp. 98–111','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(13,'P5','5.2 Permutations and combinations','P5-CNT-03','Считать arrangements с repeated/identical objects.','P5-CNT-02; PR-ALG-01','Complete Probability & Statistics 1, Ch6 Permutations and combinations','pp. 98–111','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(14,'P5','5.2 Permutations and combinations','P5-CNT-04','Считать arrangements under restrictions (together, apart, fixed positions, rows).','P5-CNT-02; P5-CNT-03','Complete Probability & Statistics 1, Ch6 Permutations and combinations','pp. 98–111','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(15,'P5','5.2 Permutations and combinations','P5-CNT-05','Считать combinations/selections и решать mixed selection–arrangement problems.','P5-CNT-01; P5-CNT-04','Complete Probability & Statistics 1, Ch6 Permutations and combinations','pp. 98–111','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(16,'P5','5.3 Probability','P5-PRO-01','Строить sample space и перечислять equiprobable outcomes без пропусков/повторов.','PR-SET-01; PR-CNT-01','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(17,'P5','5.3 Probability','P5-PRO-02','Вычислять probability через permutations/combinations.','P5-PRO-01; P5-CNT-05','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(18,'P5','5.3 Probability','P5-PRO-03','Применять addition rule, complements и mutually exclusive events.','PR-SET-01; P5-PRO-01','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(19,'P5','5.3 Probability','P5-PRO-04','Применять multiplication rule и проверять/использовать independence.','PR-SET-01; P5-PRO-03','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(20,'P5','5.3 Probability','P5-PRO-05','Вычислять и интерпретировать conditional probability.','P5-PRO-03; P5-PRO-04; PR-ALG-01','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(21,'P5','5.3 Probability','P5-PRO-06','Строить и использовать probability trees для sequential events, включая without replacement.','P5-PRO-04; P5-PRO-05','Complete Probability & Statistics 1, Ch4 Probability','pp. 63–82','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(22,'P5','5.4 Discrete random variables','P5-DRV-01','Строить/проверять discrete probability distribution и находить неизвестную probability.','P5-PRO-03; PR-ALG-03','Complete Probability & Statistics 1, Ch5 Discrete random variables','pp. 84–96','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(23,'P5','5.4 Discrete random variables','P5-DRV-02','Вычислять и интерпретировать expectation E(X) дискретной случайной величины.','P5-DRV-01; PR-ALG-01','Complete Probability & Statistics 1, Ch5 Discrete random variables','pp. 84–96','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(24,'P5','5.4 Discrete random variables','P5-DRV-03','Вычислять variance/standard deviation дискретной случайной величины.','P5-DRV-02; PR-ALG-02','Complete Probability & Statistics 1, Ch5 Discrete random variables','pp. 84–96','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(25,'P5','5.4 Discrete random variables','P5-BIN-01','Распознавать binomial model и проверять fixed n, two outcomes, constant p, independence.','P5-PRO-04; P5-DRV-01','Complete Probability & Statistics 1, Ch7 The binomial distribution','pp. 115–131','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
