-- AI-4 Economics Practice 1 deterministic diagnostic batch: Chapter 1.
-- Adds option-level deterministic explanations for seven already-published MCQs.
-- Scoring remains server-authoritative from questions.correct_answer; these rows only
-- classify the learner's selected option after checking. Existing q1135 mappings remain untouched.

do $guard$
declare
  v_bad integer;
begin
  with expected(question_id,topic,subtopic,correct_answer,options_en) as (
    values
    (1013,'PPC','Opportunity cost','B','["Money spent on a product","The next best alternative foregone","Total cost of production","A tax paid to the government"]'::jsonb),
    (1064,'Intro','Needs and wants','A','["A new smartphone for fun","Clean drinking water","Basic shelter","Essential medicine"]'::jsonb),
    (1068,'Basics','The basic economic problem','A','["resources are scarce","money is unlimited","everyone earns the same","prices never change"]'::jsonb),
    (1084,'Basics','Trade-off','A','["giving up one thing to get another","getting everything at once","prices never change","no opportunity cost"]'::jsonb),
    (1089,'Basics','Opportunity cost','A','["the next best alternative forgone","money paid for a good","total output","government tax"]'::jsonb),
    (1136,'Goods','Public goods','B','["A sandwich","Street lighting","A private car","A smartphone"]'::jsonb),
    (1137,'Demand','Inferior goods','D','["Normal","Luxury","Substitute","Inferior"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>7
     or q.is_active is not true
     or q.quality_status<>'published'
     or lower(coalesce(q.qtype,''))<>'mcq'
     or q.topic<>e.topic
     or q.subtopic<>e.subtopic
     or upper(trim(coalesce(q.correct_answer,'')))<>e.correct_answer
     or coalesce(q.options_text_en,'[]')::jsonb<>e.options_en;

  if v_bad<>0 then
    raise exception 'AI-4 diagnostic batch refused: one or more Chapter 1 questions changed';
  end if;

  if exists (
    select 1
    from public.question_answer_diagnostics d
    where d.question_id in (1013,1064,1068,1084,1089,1136,1137)
      and d.quality_status='published'
  ) then
    raise exception 'AI-4 diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,
  next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
)
values
(1013,'mcq_option','A','Money spent on a product',false,'money_cost_confusion','Opportunity cost vs monetary cost','Вы выбрали денежные расходы. Альтернативная стоимость — это лучшая упущенная альтернатива, а не сумма денег, заплаченная за товар.','Siz pul xarajatini tanladingiz. Muqobil xarajat — tovar uchun to‘langan pul emas, balki voz kechilgan eng yaxshi keyingi imkoniyat.','You chose a money cost. Opportunity cost is the next best alternative forgone, not the money paid for a product.','Повторите определение альтернативной стоимости.','Muqobil xarajat ta’rifini takrorlang.','Review the definition of opportunity cost.','PPC','Opportunity cost','{}'::jsonb,'published'),
(1013,'mcq_option','B','The next best alternative foregone',true,null,null,'Верно: альтернативная стоимость — лучшая упущенная альтернатива.','To‘g‘ri: muqobil xarajat — voz kechilgan eng yaxshi keyingi imkoniyat.','Correct: opportunity cost is the next best alternative forgone.','Свяжите это определение с выбором при ограниченных ресурсах.','Bu ta’rifni cheklangan resurslar sharoitidagi tanlov bilan bog‘lang.','Link this definition to choice under scarcity.','PPC','Opportunity cost','{}'::jsonb,'published'),
(1013,'mcq_option','C','Total cost of production',false,'production_cost_confusion','Opportunity cost vs production cost','Общие издержки производства и альтернативная стоимость — разные понятия. Здесь нужно определить лучшую альтернативу, от которой отказались.','Jami ishlab chiqarish xarajati bilan muqobil xarajat boshqa tushunchalar. Bu yerda voz kechilgan eng yaxshi keyingi imkoniyat aniqlanadi.','Total production cost is different from opportunity cost. Here the key idea is the best alternative that was given up.','Сравните альтернативную стоимость с бухгалтерскими и производственными издержками.','Muqobil xarajatni ishlab chiqarish va pul xarajatlari bilan solishtiring.','Compare opportunity cost with monetary and production costs.','PPC','Opportunity cost','{}'::jsonb,'published'),
(1013,'mcq_option','D','A tax paid to the government',false,'unrelated_payment_confusion','Opportunity cost concept','Налог — это платёж государству, а не определение альтернативной стоимости. Ищите упущенную лучшую альтернативу.','Soliq davlatga to‘lovdir, muqobil xarajatning ta’rifi emas. Voz kechilgan eng yaxshi imkoniyatni toping.','A tax is a payment to government, not the definition of opportunity cost. Look for the best forgone alternative.','Повторите различие между платежом и альтернативной стоимостью.','To‘lov bilan muqobil xarajat o‘rtasidagi farqni takrorlang.','Review the difference between a payment and opportunity cost.','PPC','Opportunity cost','{}'::jsonb,'published'),
(1064,'mcq_option','A','A new smartphone for fun',true,null,null,'Верно: новый смартфон для развлечения — пример желания, а не базовой необходимости.','To‘g‘ri: ko‘ngilochar maqsaddagi yangi smartfon asosiy ehtiyoj emas, istakdir.','Correct: a new smartphone for fun is a want rather than a basic need.','Повторите различие между потребностями и желаниями.','Ehtiyojlar va istaklar farqini takrorlang.','Review the distinction between needs and wants.','Intro','Needs and wants','{}'::jsonb,'published'),
(1064,'mcq_option','B','Clean drinking water',false,'need_want_confusion','Needs vs wants','Чистая питьевая вода относится к базовым потребностям. Нужно выбрать несущественное благо, которое скорее является желанием.','Toza ichimlik suvi asosiy ehtiyojga kiradi. Istak bo‘lgan, zarur bo‘lmagan variantni tanlash kerak.','Clean drinking water is a basic need. The question asks for a non-essential item that is more clearly a want.','Сравните необходимые для жизни блага с необязательными желаниями.','Hayot uchun zarur narsalarni ixtiyoriy istaklar bilan solishtiring.','Compare essentials for basic living with non-essential wants.','Intro','Needs and wants','{}'::jsonb,'published'),
(1064,'mcq_option','C','Basic shelter',false,'need_want_confusion','Needs vs wants','Базовое жильё относится к основным потребностям. Желание — это то, что человек хотел бы иметь сверх необходимого.','Asosiy boshpana fundamental ehtiyojdir. Istak esa zarur narsalardan tashqari ega bo‘lishni xohlagan narsadir.','Basic shelter is a fundamental need. A want is something desired beyond basic essentials.','Повторите примеры потребностей и желаний.','Ehtiyoj va istaklarga misollarni takrorlang.','Review examples of needs and wants.','Intro','Needs and wants','{}'::jsonb,'published'),
(1064,'mcq_option','D','Essential medicine',false,'need_want_confusion','Needs vs wants','Необходимое лекарство относится к потребностям, поскольку связано с базовым здоровьем и жизнедеятельностью.','Zarur dori asosiy salomatlik va hayot bilan bog‘liq bo‘lgani uchun ehtiyojga kiradi.','Essential medicine is a need because it relates to basic health and living.','Ищите вариант, который не является необходимым для базовой жизни.','Asosiy hayot uchun zarur bo‘lmagan variantni izlang.','Look for the option that is not essential for basic living.','Intro','Needs and wants','{}'::jsonb,'published'),
(1068,'mcq_option','A','resources are scarce',true,null,null,'Верно: основная экономическая проблема возникает из-за ограниченности ресурсов по сравнению с желаниями.','To‘g‘ri: asosiy iqtisodiy muammo resurslar istaklarga nisbatan cheklanganligi sababli yuz beradi.','Correct: the basic economic problem arises because resources are scarce relative to wants.','Свяжите ограниченность с выбором и альтернативной стоимостью.','Cheklanganlikni tanlov va muqobil xarajat bilan bog‘lang.','Link scarcity to choice and opportunity cost.','Basics','The basic economic problem','{}'::jsonb,'published'),
(1068,'mcq_option','B','money is unlimited',false,'scarcity_concept_error','Basic economic problem','Неограниченные деньги не объясняют основную экономическую проблему. Наоборот, проблема возникает потому, что ресурсы ограничены.','Cheksiz pul asosiy iqtisodiy muammoni tushuntirmaydi. Aksincha, muammo resurslar cheklanganligi sababli yuz beradi.','Unlimited money does not explain the basic economic problem. The problem exists because resources are scarce.','Повторите понятие ограниченности ресурсов.','Resurslar cheklanganligi tushunchasini takrorlang.','Review the concept of scarcity.','Basics','The basic economic problem','{}'::jsonb,'published'),
(1068,'mcq_option','C','everyone earns the same',false,'distribution_vs_scarcity_confusion','Scarcity vs income distribution','Равенство доходов относится к распределению, а не к причине основной экономической проблемы. Причина — ограниченность ресурсов.','Daromadlarning tengligi taqsimot masalasi, asosiy iqtisodiy muammoning sababi emas. Sabab — resurslarning cheklanganligi.','Equal incomes concern distribution, not the cause of the basic economic problem. The cause is scarcity of resources.','Отделяйте проблему ограниченности от вопросов распределения дохода.','Cheklanganlik muammosini daromad taqsimotidan ajrating.','Separate scarcity from questions of income distribution.','Basics','The basic economic problem','{}'::jsonb,'published'),
(1068,'mcq_option','D','prices never change',false,'price_vs_scarcity_confusion','Scarcity vs price changes','Изменение или неизменность цен не является причиной основной экономической проблемы. Она возникает из-за ограниченности ресурсов.','Narxlarning o‘zgarishi yoki o‘zgarmasligi asosiy iqtisodiy muammoning sababi emas. Muammo resurslarning cheklanganligidan kelib chiqadi.','Whether prices change is not the cause of the basic economic problem. It arises because resources are scarce.','Вернитесь к связи: ограниченность → выбор → альтернативная стоимость.','Cheklanganlik → tanlov → muqobil xarajat bog‘lanishini takrorlang.','Review the link: scarcity → choice → opportunity cost.','Basics','The basic economic problem','{}'::jsonb,'published'),
(1084,'mcq_option','A','giving up one thing to get another',true,null,null,'Верно: компромисс означает отказ от части одного варианта ради другого.','To‘g‘ri: trade-off bir narsadan boshqasi foydasiga qisman voz kechishni anglatadi.','Correct: a trade-off means giving up some of one option to obtain another.','Свяжите компромисс с ограниченностью и выбором.','Trade-offni cheklanganlik va tanlov bilan bog‘lang.','Link trade-offs to scarcity and choice.','Basics','Trade-off','{}'::jsonb,'published'),
(1084,'mcq_option','B','getting everything at once',false,'scarcity_denial','Trade-off under scarcity','При ограниченных ресурсах невозможно получить всё одновременно. Именно необходимость выбора создаёт компромисс.','Cheklangan resurslar bilan hamma narsani bir vaqtda olish mumkin emas. Aynan tanlov zarurati trade-offni yuzaga keltiradi.','Scarce resources prevent getting everything at once. The need to choose is what creates a trade-off.','Повторите, почему ограниченность требует выбора.','Cheklanganlik nima uchun tanlovni talab qilishini takrorlang.','Review why scarcity requires choice.','Basics','Trade-off','{}'::jsonb,'published'),
(1084,'mcq_option','C','prices never change',false,'price_tradeoff_confusion','Trade-off concept','Постоянство цен не определяет компромисс. Компромисс связан с тем, что ради одного варианта приходится отказаться от другого.','Narxlarning o‘zgarmasligi trade-offni ta’riflamaydi. Trade-off bir variant uchun boshqasidan voz kechish bilan bog‘liq.','Unchanging prices do not define a trade-off. A trade-off is about giving up one alternative to gain another.','Повторите определение trade-off без привязки к движению цен.','Trade-off ta’rifini narx o‘zgarishidan alohida takrorlang.','Review the definition of a trade-off separately from price changes.','Basics','Trade-off','{}'::jsonb,'published'),
(1084,'mcq_option','D','no opportunity cost',false,'opportunity_cost_denial','Trade-off and opportunity cost','Компромисс обычно означает наличие альтернативной стоимости: выбранный вариант требует отказаться от другой возможности.','Trade-off odatda muqobil xarajat mavjudligini anglatadi: tanlangan variant boshqa imkoniyatdan voz kechishni talab qiladi.','A trade-off normally implies an opportunity cost because choosing one option requires giving up another.','Свяжите trade-off с лучшей упущенной альтернативой.','Trade-offni voz kechilgan eng yaxshi imkoniyat bilan bog‘lang.','Link a trade-off to the best alternative forgone.','Basics','Trade-off','{}'::jsonb,'published'),
(1089,'mcq_option','A','the next best alternative forgone',true,null,null,'Верно: альтернативная стоимость — следующая лучшая упущенная альтернатива.','To‘g‘ri: muqobil xarajat — voz kechilgan eng yaxshi keyingi imkoniyat.','Correct: opportunity cost is the next best alternative forgone.','Применяйте определение к конкретным выборам.','Ta’rifni aniq tanlovlarga qo‘llang.','Apply the definition to specific choices.','Basics','Opportunity cost','{}'::jsonb,'published'),
(1089,'mcq_option','B','money paid for a good',false,'money_cost_confusion','Opportunity cost vs monetary cost','Цена покупки — денежные расходы, но не обязательно альтернативная стоимость. Альтернативная стоимость — лучшая упущенная альтернатива.','Xarid narxi pul xarajatidir, lekin bu albatta muqobil xarajat emas. Muqobil xarajat — voz kechilgan eng yaxshi imkoniyat.','The purchase price is a money cost, but it is not necessarily the opportunity cost. Opportunity cost is the best alternative forgone.','Различайте денежные расходы и экономическую альтернативную стоимость.','Pul xarajati bilan iqtisodiy muqobil xarajatni farqlang.','Distinguish money cost from economic opportunity cost.','Basics','Opportunity cost','{}'::jsonb,'published'),
(1089,'mcq_option','C','total output',false,'output_vs_opportunity_cost_confusion','Opportunity cost concept','Общий выпуск показывает количество произведённого, а не стоимость упущенной альтернативы.','Jami ishlab chiqarish ishlab chiqarilgan miqdorni ko‘rsatadi, voz kechilgan imkoniyat qiymatini emas.','Total output measures how much is produced, not the value of the alternative that was forgone.','Повторите, что измеряет альтернативная стоимость.','Muqobil xarajat nimani o‘lchashini takrorlang.','Review what opportunity cost measures.','Basics','Opportunity cost','{}'::jsonb,'published'),
(1089,'mcq_option','D','government tax',false,'tax_vs_opportunity_cost_confusion','Opportunity cost concept','Налог — обязательный платёж государству. Это не определение альтернативной стоимости.','Soliq davlatga majburiy to‘lovdir. Bu muqobil xarajatning ta’rifi emas.','A government tax is a payment to the state. It is not the definition of opportunity cost.','Ищите именно упущенную лучшую альтернативу.','Aynan voz kechilgan eng yaxshi imkoniyatni izlang.','Look specifically for the best alternative forgone.','Basics','Opportunity cost','{}'::jsonb,'published'),
(1136,'mcq_option','A','A sandwich',false,'private_public_good_confusion','Public vs private goods','Бутерброд — частное благо: его можно исключить из потребления, и потребление одним человеком оставляет меньше для других.','Sendvich xususiy ne’matdir: undan foydalanishni cheklash mumkin va bir kishining iste’moli boshqalarga qoladigan miqdorni kamaytiradi.','A sandwich is a private good: access can be excluded and one person''s consumption leaves less for others.','Повторите признаки неисключаемости и неконкурентности.','Foydalanishni cheklab bo‘lmaslik va raqobatsizlik belgilarini takrorlang.','Review non-excludability and non-rivalry.','Goods','Public goods','{}'::jsonb,'published'),
(1136,'mcq_option','B','Street lighting',true,null,null,'Верно: уличное освещение является типичным примером общественного блага с признаками неисключаемости и неконкурентности.','To‘g‘ri: ko‘cha yoritgichi foydalanishni cheklash qiyin va iste’molda raqobatsiz bo‘lgan jamoat ne’matiga odatiy misoldir.','Correct: street lighting is a standard example of a public good with non-excludable and non-rival features.','Свяжите эти признаки с проблемой безбилетника.','Bu belgilarni tekin foydalanuvchi muammosi bilan bog‘lang.','Link these features to the free-rider problem.','Goods','Public goods','{}'::jsonb,'published'),
(1136,'mcq_option','C','A private car',false,'private_public_good_confusion','Public vs private goods','Частный автомобиль — частное благо: владелец может исключить других из пользования, а использование связано с ограниченной доступностью конкретного автомобиля.','Xususiy avtomobil xususiy ne’matdir: egasi boshqalarni foydalanishdan cheklashi mumkin va aynan shu avtomobildan foydalanish cheklangan.','A private car is a private good: the owner can exclude others from using it, and use of the specific car is limited.','Проверяйте два признака чистого общественного блага.','Sof jamoat ne’matining ikki belgisini tekshiring.','Check both defining features of a pure public good.','Goods','Public goods','{}'::jsonb,'published'),
(1136,'mcq_option','D','A smartphone',false,'private_public_good_confusion','Public vs private goods','Смартфон — частное благо: доступ к нему исключаем, а конкретное устройство не может одновременно свободно потребляться всеми.','Smartfon xususiy ne’matdir: undan foydalanishni cheklash mumkin va aynan bir qurilmadan hamma bir vaqtda erkin foydalana olmaydi.','A smartphone is a private good: access can be excluded and a specific device cannot be freely consumed by everyone at the same time.','Сравните частные и общественные блага по двум ключевым признакам.','Xususiy va jamoat ne’matlarini ikki asosiy belgi bo‘yicha solishtiring.','Compare private and public goods using the two defining characteristics.','Goods','Public goods','{}'::jsonb,'published'),
(1137,'mcq_option','A','Normal',false,'income_demand_direction_error','Normal vs inferior goods','Для нормального блага спрос обычно растёт при росте дохода. В вопросе спрос падает при росте дохода, поэтому это другой тип блага.','Normal tovar uchun daromad oshganda talab odatda oshadi. Savolda esa daromad oshganda talab kamaymoqda, demak bu boshqa turdagi tovar.','For a normal good, demand normally rises as income rises. Here demand falls as income rises, so the good is not normal.','Сравните знак YED для нормальных и низших благ.','Normal va past toifadagi tovarlar uchun YED ishorasini solishtiring.','Compare the sign of YED for normal and inferior goods.','Demand','Inferior goods','{}'::jsonb,'published'),
(1137,'mcq_option','B','Luxury',false,'luxury_inferior_confusion','Income classification of goods','Предмет роскоши — разновидность нормального блага с положительной реакцией спроса на рост дохода. Здесь спрос, наоборот, снижается.','Hashamat tovari normal tovar turiga kiradi va daromad oshganda talabi musbat yo‘nalishda o‘zgaradi. Bu savolda talab aksincha kamaymoqda.','A luxury good is a type of normal good with demand rising as income rises. In this question demand moves in the opposite direction.','Повторите классификацию благ по эластичности спроса по доходу.','Tovarlarni daromad bo‘yicha talab elastikligi asosida tasniflashni takrorlang.','Review the income-elasticity classification of goods.','Demand','Inferior goods','{}'::jsonb,'published'),
(1137,'mcq_option','C','Substitute',false,'relationship_vs_income_classification','Related goods vs income classification','Товар-заменитель описывает связь между двумя товарами и их ценами, а вопрос описывает реакцию спроса на изменение дохода.','O‘rinbosar atamasi ikki tovar va ularning narxlari o‘rtasidagi bog‘lanishni bildiradi, savol esa talabning daromad o‘zgarishiga reaksiyasini tasvirlaydi.','A substitute describes the relationship between two goods and their prices, while this question describes demand responding to income.','Разделяйте XED и классификацию по YED.','XED bilan YED bo‘yicha tasnifni farqlang.','Separate XED relationships from YED classifications.','Demand','Inferior goods','{}'::jsonb,'published'),
(1137,'mcq_option','D','Inferior',true,null,null,'Верно: у низшего блага спрос при прочих равных снижается с ростом дохода.','To‘g‘ri: past toifadagi tovar uchun boshqa omillar o‘zgarmaganda daromad oshsa talab kamayadi.','Correct: for an inferior good, demand falls as income rises, other things equal.','Свяжите это с отрицательной YED.','Buni manfiy YED bilan bog‘lang.','Link this to negative YED.','Demand','Inferior goods','{}'::jsonb,'published');
