-- P0-08: original iClub P5 content seed (P5-DAT-01 beta floor).
-- DRAFT + INACTIVE only; no learner exposure and no existing-question mutation.
begin;
with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p5_repr_beta_v1' and component_code='P5' and status='draft'
), src(content_key,skill_code,reserve_role,topic,subtopic,difficulty,qtype,
        q_en,opts_en,correct_answer,exp_en,q_ru,q_uz,q_en_dup,
        opts_ru,opts_uz,opts_en_dup,exp_ru,exp_uz,exp_en_dup,book_ref,time_limit_sec,secondary_csv) as (
  values
('P5DAT01-D01','P5-DAT-01','diagnostic','P5 Representation of data','P5-DAT-01','medium','mcq','A teacher wants to compare the median and spread of test scores in three classes without displaying every individual score. Which representation is most suitable?','["Scatter plot", "Pie chart", "Side-by-side box-and-whisker plots", "Line graph"]','C','Box-and-whisker plots show the median, quartiles and spread compactly, so several groups can be compared directly.','Учитель хочет сравнить медиану и разброс результатов теста в трёх классах, не показывая каждый отдельный результат. Какое представление наиболее подходит?','O‘qituvchi uchta sinfdagi test natijalarining medianasi va tarqalishini har bir alohida natijani ko‘rsatmasdan taqqoslamoqchi. Qaysi tasvirlash usuli eng mos?','A teacher wants to compare the median and spread of test scores in three classes without displaying every individual score. Which representation is most suitable?','["Scatter plot", "Pie chart", "Side-by-side box-and-whisker plots", "Line graph"]','["Scatter plot", "Pie chart", "Side-by-side box-and-whisker plots", "Line graph"]','["Scatter plot", "Pie chart", "Side-by-side box-and-whisker plots", "Line graph"]','Диаграммы «ящик с усами» компактно показывают медиану, квартили и разброс, поэтому несколько групп удобно сравнивать напрямую.','Quti-mo‘ylov diagrammalari mediana, kvartillar va tarqalishni ixcham ko‘rsatadi, shuning uchun bir nechta guruhni bevosita taqqoslash mumkin.','Box-and-whisker plots show the median, quartiles and spread compactly, so several groups can be compared directly.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-D01',70,''),
('P5DAT01-L01','P5-DAT-01','learning','P5 Representation of data','P5-DAT-01','easy','mcq','A coach has 18 lap times and wants a display that keeps every original value visible while also showing the distribution. Which representation is best?','["Stem-and-leaf diagram", "Pie chart", "Scatter plot", "Line graph"]','A','A stem-and-leaf diagram preserves the individual data values while displaying the shape of a small numerical dataset.','У тренера есть 18 значений времени круга. Он хочет, чтобы на диаграмме были видны все исходные значения и одновременно форма распределения. Какое представление лучше?','Murabbiyda 18 ta aylana vaqti bor. U har bir asl qiymat ko‘rinib turishi va taqsimot ham namoyon bo‘lishini xohlaydi. Qaysi tasvirlash usuli eng yaxshi?','A coach has 18 lap times and wants a display that keeps every original value visible while also showing the distribution. Which representation is best?','["Stem-and-leaf diagram", "Pie chart", "Scatter plot", "Line graph"]','["Stem-and-leaf diagram", "Pie chart", "Scatter plot", "Line graph"]','["Stem-and-leaf diagram", "Pie chart", "Scatter plot", "Line graph"]','Стебле-листовая диаграмма сохраняет отдельные значения данных и одновременно показывает форму небольшого числового набора.','Poya-barg diagrammasi alohida qiymatlarni saqlaydi va kichik sonli ma’lumotlar to‘plamining shaklini ham ko‘rsatadi.','A stem-and-leaf diagram preserves the individual data values while displaying the shape of a small numerical dataset.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L01',55,''),
('P5DAT01-L02','P5-DAT-01','learning','P5 Representation of data','P5-DAT-01','easy','mcq','A researcher records hours studied and test score for each student and wants to investigate whether the two variables are associated. Which representation is most suitable?','["Box-and-whisker plot", "Scatter plot", "Pie chart", "Cumulative-frequency graph"]','B','A scatter plot displays paired numerical values and is designed to reveal association between two variables.','Исследователь записал для каждого ученика часы подготовки и балл за тест и хочет выяснить, связаны ли эти две переменные. Какое представление наиболее подходит?','Tadqiqotchi har bir o‘quvchi uchun o‘qish soati va test balini yozdi va bu ikki o‘zgaruvchi orasida bog‘lanish bor-yo‘qligini tekshirmoqchi. Qaysi tasvirlash usuli eng mos?','A researcher records hours studied and test score for each student and wants to investigate whether the two variables are associated. Which representation is most suitable?','["Box-and-whisker plot", "Scatter plot", "Pie chart", "Cumulative-frequency graph"]','["Box-and-whisker plot", "Scatter plot", "Pie chart", "Cumulative-frequency graph"]','["Box-and-whisker plot", "Scatter plot", "Pie chart", "Cumulative-frequency graph"]','Диаграмма рассеяния показывает пары числовых значений и позволяет увидеть связь между двумя переменными.','Nuqtali diagramma juft sonli qiymatlarni ko‘rsatadi va ikki o‘zgaruvchi orasidagi bog‘lanishni aniqlashga mos keladi.','A scatter plot displays paired numerical values and is designed to reveal association between two variables.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L02',55,''),
('P5DAT01-L03','P5-DAT-01','learning','P5 Representation of data','P5-DAT-01','medium','mcq','Continuous rainfall measurements have been grouped into intervals of unequal width. Which representation is appropriate for showing the shape of the distribution?','["Pie chart", "Stem-and-leaf diagram", "Scatter plot", "Histogram using frequency density"]','D','For grouped continuous data with unequal class widths, a histogram uses frequency density so bar area represents frequency.','Непрерывные значения количества осадков сгруппированы в интервалы разной ширины. Какое представление подходит для показа формы распределения?','Uzluksiz yog‘in miqdorlari turli kenglikdagi intervallarga guruhlangan. Taqsimot shaklini ko‘rsatish uchun qaysi tasvirlash usuli mos?','Continuous rainfall measurements have been grouped into intervals of unequal width. Which representation is appropriate for showing the shape of the distribution?','["Pie chart", "Stem-and-leaf diagram", "Scatter plot", "Histogram using frequency density"]','["Pie chart", "Stem-and-leaf diagram", "Scatter plot", "Histogram using frequency density"]','["Pie chart", "Stem-and-leaf diagram", "Scatter plot", "Histogram using frequency density"]','Для сгруппированных непрерывных данных с неравными интервалами используют гистограмму с плотностью частоты, чтобы площадь столбца соответствовала частоте.','Turli kenglikdagi intervallarga guruhlangan uzluksiz ma’lumotlar uchun chastota zichligidan foydalanadigan gistogramma qo‘llanadi; ustun yuzi chastotani ifodalaydi.','For grouped continuous data with unequal class widths, a histogram uses frequency density so bar area represents frequency.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L03',65,'P5-DAT-04'),
('P5DAT01-R01','P5-DAT-01','retest','P5 Representation of data','P5-DAT-01','medium','mcq','A logistics manager wants to compare the medians, interquartile ranges and possible extreme values of delivery times for four services. Which display is most useful?','["Four pie charts", "Side-by-side box-and-whisker plots", "One scatter plot", "A line graph"]','B','Side-by-side box plots make median and spread comparisons between several groups direct and compact.','Менеджер по логистике хочет сравнить медианы, межквартильные размахи и возможные крайние значения времени доставки четырёх служб. Какая диаграмма наиболее полезна?','Logistika menejeri to‘rtta xizmatning yetkazib berish vaqtlaridagi medianalar, kvartillararo kengliklar va ehtimoliy chekka qiymatlarni taqqoslamoqchi. Qaysi diagramma eng foydali?','A logistics manager wants to compare the medians, interquartile ranges and possible extreme values of delivery times for four services. Which display is most useful?','["Four pie charts", "Side-by-side box-and-whisker plots", "One scatter plot", "A line graph"]','["Four pie charts", "Side-by-side box-and-whisker plots", "One scatter plot", "A line graph"]','["Four pie charts", "Side-by-side box-and-whisker plots", "One scatter plot", "A line graph"]','Расположенные рядом диаграммы «ящик с усами» позволяют напрямую и компактно сравнивать медианы и разброс нескольких групп.','Yonma-yon quti-mo‘ylov diagrammalari bir nechta guruhning medianasi va tarqalishini ixcham va bevosita taqqoslash imkonini beradi.','Side-by-side box plots make median and spread comparisons between several groups direct and compact.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-R01',65,''),
('P5DAT01-R02','P5-DAT-01','retest','P5 Representation of data','P5-DAT-01','medium','mcq','Two small classes each have fewer than 20 exam marks. A teacher wants to compare the distributions while retaining every original mark. Which representation is best?','["Back-to-back stem-and-leaf diagram", "Histogram with unequal widths", "Pie chart", "Scatter plot"]','A','A back-to-back stem-and-leaf diagram retains all individual values and supports comparison of two small numerical datasets.','В двух небольших классах менее 20 экзаменационных баллов в каждом. Учитель хочет сравнить распределения, сохранив каждый исходный балл. Какое представление лучше?','Ikki kichik sinfning har birida 20 tadan kam imtihon bali bor. O‘qituvchi har bir asl balni saqlagan holda taqsimotlarni taqqoslamoqchi. Qaysi tasvirlash usuli eng yaxshi?','Two small classes each have fewer than 20 exam marks. A teacher wants to compare the distributions while retaining every original mark. Which representation is best?','["Back-to-back stem-and-leaf diagram", "Histogram with unequal widths", "Pie chart", "Scatter plot"]','["Back-to-back stem-and-leaf diagram", "Histogram with unequal widths", "Pie chart", "Scatter plot"]','["Back-to-back stem-and-leaf diagram", "Histogram with unequal widths", "Pie chart", "Scatter plot"]','Двусторонняя стебле-листовая диаграмма сохраняет все отдельные значения и позволяет сравнить два небольших числовых набора.','Orqa-orqaga poya-barg diagrammasi barcha alohida qiymatlarni saqlaydi va ikkita kichik sonli to‘plamni taqqoslashga imkon beradi.','A back-to-back stem-and-leaf diagram retains all individual values and supports comparison of two small numerical datasets.','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-R02',65,'P5-DAT-02')
)
insert into public.questions(
  subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,
  image_url,is_active,question_text_ru,question_text_uz,question_text_en,
  options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,
  book_ref,time_limit_sec,quality_flag,quality_status
)
select 5,s.topic,s.subtopic,s.difficulty,s.qtype,s.q_en,s.opts_en,s.correct_answer,s.exp_en,
       null,false,s.q_ru,s.q_uz,s.q_en_dup,s.opts_ru,s.opts_uz,s.opts_en_dup,s.exp_ru,s.exp_uz,s.exp_en_dup,
       s.book_ref,s.time_limit_sec,null,'draft'
from src s
where not exists(select 1 from public.questions q where q.book_ref=s.book_ref);

with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p5_repr_beta_v1' and component_code='P5' and status='draft'
), src(content_key,skill_code,reserve_role,secondary_csv,book_ref) as (
  values
('P5DAT01-D01','P5-DAT-01','diagnostic','','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-D01'),('P5DAT01-L01','P5-DAT-01','learning','','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L01'),('P5DAT01-L02','P5-DAT-01','learning','','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L02'),('P5DAT01-L03','P5-DAT-01','learning','P5-DAT-04','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-L03'),('P5DAT01-R01','P5-DAT-01','retest','','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-R01'),('P5DAT01-R02','P5-DAT-01','retest','P5-DAT-02','ExamPrep:P5:p5_repr_beta_v1:P5DAT01-R02')
)
insert into private.exam_prep_question_content_meta(
  content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,
  exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,
  coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,
  qa_technical_status,diagnostic_rule_status,question_snapshot_md5
)
select cv.id,s.content_key,q.id,s.skill_code,
       case when nullif(s.secondary_csv,'') is null then '{}'::text[] else string_to_array(s.secondary_csv,',') end,
       s.reserve_role,'withheld','draft',
       'Original iClub-authored stem, data, distractors, answer and explanation; no Cambridge/coursebook question text, diagram or mark-scheme wording copied.',
       'Authored specifically for p5_repr_beta_v1 from canonical skill intent and independent numeric/context examples.',
       'Cambridge 9709 2026-2027 v4; P5 5.1 Representation of data',
       'Complete Probability & Statistics 1, Ch2-3 pp.14-59 (mapping only)',
       'pending','pending','pending','pending','pending',
       case when s.reserve_role='diagnostic' then 'pending' else 'not_applicable' end,
       md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),
         coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),
         coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),
         coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),
         coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),
         coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),
         coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join src s join public.questions q on q.book_ref=s.book_ref
on conflict(content_version_id,content_key) do nothing;
commit;
