-- P1-02 P5 AW21-24 DAT-08: compare datasets by location and spread in context.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw21_24_dat08_v1','P5','P5 AW21-24 DAT-08 dataset comparison','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat08_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5DAT08-D01','diagnostic','medium','Class A has median 70 and IQR 10. Class B has median 74 and IQR 18. Which comparison is best supported?','У класса A медиана 70 и IQR 10. У класса B медиана 74 и IQR 18. Какое сравнение лучше всего подтверждается?','A sinf medianasi 70 va IQR 10. B sinf medianasi 74 va IQR 18. Qaysi taqqoslash eng asosli?','["B has a higher typical score, but A is more consistent","A has a higher typical score and is more spread out","B is more consistent because its median is larger","The classes have the same location and spread"]','["У B выше типичный результат, но A более стабилен","У A выше типичный результат и больше разброс","B стабильнее, потому что медиана больше","Расположение и разброс одинаковы"]','["B ning odatiy natijasi yuqori, lekin A barqarorroq","A ning odatiy natijasi yuqori va tarqalishi katta","B medianasi katta bo‘lgani uchun barqarorroq","Markaz va tarqalish bir xil"]','A','Median compares location and IQR compares spread. B has the higher median, while A has the smaller IQR.','Медиана сравнивает положение, IQR — разброс. У B медиана выше, у A IQR меньше.','Mediana markazni, IQR tarqalishni taqqoslaydi. B medianasi yuqori, A IQR kichik.',50),
('P5DAT08-L01','learning','easy','Two machines have the same mean output. Machine X has standard deviation 2 and machine Y has standard deviation 5. Which is more consistent?','У двух машин одинаковый средний выпуск. У X стандартное отклонение 2, у Y — 5. Какая стабильнее?','Ikki mashinaning o‘rtacha natijasi bir xil. X ning standart og‘ishi 2, Y ning 5. Qaysi barqarorroq?','["Machine X","Machine Y","They are equally consistent","Cannot be compared because the means are equal"]','["Машина X","Машина Y","Одинаково стабильны","Сравнить нельзя, потому что средние равны"]','["X mashina","Y mashina","Bir xil barqaror","O‘rtachalar tengligi sabab taqqoslab bo‘lmaydi"]','A','With the same centre, the smaller standard deviation means observations are more tightly clustered.','При одинаковом центре меньшее стандартное отклонение означает меньший разброс.','Bir xil markazda kichik standart og‘ish kamroq tarqalishni bildiradi.',30),
('P5DAT08-L02','learning','medium','Dataset A has median 52, IQR 8. Dataset B has median 47, IQR 6. Which statement is correct?','У набора A медиана 52, IQR 8. У B медиана 47, IQR 6. Какое утверждение верно?','A to‘plam medianasi 52, IQR 8. B medianasi 47, IQR 6. Qaysi gap to‘g‘ri?','["A has the higher centre; B has the smaller spread","B has the higher centre; A has the smaller spread","A is both higher-centred and less spread","B is both higher-centred and less spread"]','["У A выше центр; у B меньше разброс","У B выше центр; у A меньше разброс","У A и центр выше, и разброс меньше","У B и центр выше, и разброс меньше"]','["A markazi yuqori; B tarqalishi kichik","B markazi yuqori; A tarqalishi kichik","A markazi yuqori va tarqalishi kichik","B markazi yuqori va tarqalishi kichik"]','A','Compare median with median and IQR with IQR: 52>47, while 6<8.','Сравнивайте медианы между собой и IQR между собой: 52>47, а 6<8.','Medianani mediana bilan, IQR ni IQR bilan taqqoslang: 52>47, 6<8.',35),
('P5DAT08-L03','learning','medium','A filling process targets 500 g. Process A has mean 500 g and standard deviation 4 g; process B has mean 498 g and standard deviation 1 g. Which conclusion is best?','Процесс фасовки имеет цель 500 г. У A среднее 500 г и стандартное отклонение 4 г; у B среднее 498 г и стандартное отклонение 1 г. Какой вывод лучший?','Qadoqlash jarayoni maqsadi 500 g. A o‘rtachasi 500 g, standart og‘ishi 4 g; B o‘rtachasi 498 g, standart og‘ishi 1 g. Eng yaxshi xulosa qaysi?','["A is better centred on target; B is more consistent","B is better centred on target and more consistent","A is more consistent because its mean is larger","The two processes are equivalent"]','["A лучше центрирован на цели; B стабильнее","B лучше центрирован и стабильнее","A стабильнее, потому что среднее больше","Процессы эквивалентны"]','["A maqsadga yaxshiroq markazlangan; B barqarorroq","B maqsadga yaxshiroq markazlangan va barqarorroq","A o‘rtachasi katta bo‘lgani uchun barqarorroq","Jarayonlar teng"]','A','A has mean exactly at the 500 g target; B has the smaller standard deviation, so B is less variable.','У A среднее точно на цели 500 г; у B меньше стандартное отклонение, значит меньше вариабельность.','A o‘rtachasi 500 g maqsadda; B standart og‘ishi kichik, demak tarqalishi kam.',45),
('P5DAT08-R01','retest','easy','Dataset P has mean 20 and standard deviation 3. Dataset Q has mean 20 and standard deviation 7. Which has less spread?','У P среднее 20 и стандартное отклонение 3. У Q среднее 20 и стандартное отклонение 7. Где меньше разброс?','P o‘rtachasi 20, standart og‘ishi 3. Q o‘rtachasi 20, standart og‘ishi 7. Qaysida tarqalish kam?','["P","Q","Same spread","Cannot tell"]','["P","Q","Одинаковый разброс","Нельзя определить"]','["P","Q","Bir xil tarqalish","Aniqlab bo‘lmaydi"]','A','Smaller standard deviation means smaller spread.','Меньшее стандартное отклонение означает меньший разброс.','Kichik standart og‘ish kichik tarqalishni bildiradi.',25),
('P5DAT08-R02','retest','medium','Team A has median time 42 s and IQR 5 s. Team B has median time 39 s and IQR 9 s. For a race where lower time is better, which comparison is justified?','У команды A медиана времени 42 с и IQR 5 с. У B медиана 39 с и IQR 9 с. В гонке меньшее время лучше. Какой вывод обоснован?','A jamoa median vaqti 42 s, IQR 5 s. B medianasi 39 s, IQR 9 s. Poygada kichik vaqt yaxshi. Qaysi xulosa asosli?','["B is typically faster, while A is more consistent","A is typically faster and more consistent","B is both faster and more consistent","A is faster, while B is more consistent"]','["B обычно быстрее, а A стабильнее","A обычно быстрее и стабильнее","B и быстрее, и стабильнее","A быстрее, а B стабильнее"]','["B odatda tezroq, A barqarorroq","A odatda tezroq va barqarorroq","B tezroq va barqarorroq","A tezroq, B barqarorroq"]','A','Lower median means B is typically faster; smaller IQR means A is more consistent.','Меньшая медиана означает, что B обычно быстрее; меньший IQR означает, что A стабильнее.','Kichik mediana B odatda tezroq; kichik IQR A barqarorroq ekanini bildiradi.',40),
('P5DAT08-M01','mixed','medium','Dataset A has median 20 and IQR 4. Dataset B has median 20 and IQR 9. Which is the strongest conclusion?','У A медиана 20 и IQR 4. У B медиана 20 и IQR 9. Какой вывод наиболее сильный?','A medianasi 20 va IQR 4. B medianasi 20 va IQR 9. Eng kuchli xulosa qaysi?','["The datasets have the same central location, but A is less spread out","A has a higher centre and less spread","B has a higher centre and more spread","The datasets are identical"]','["Центральное положение одинаково, но A имеет меньший разброс","У A выше центр и меньше разброс","У B выше центр и больше разброс","Наборы идентичны"]','["Markaz bir xil, lekin A kamroq tarqalgan","A markazi yuqori va tarqalishi kichik","B markazi yuqori va tarqalishi katta","To‘plamlar aynan bir xil"]','A','Equal medians support the same central location; the smaller IQR shows A has less middle-50% spread.','Равные медианы указывают на одинаковый центр; меньший IQR у A означает меньший разброс средней половины данных.','Teng medianalar bir xil markazni, A dagi kichik IQR esa kamroq tarqalishni bildiradi.',40)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Data Comparison','P5-DAT-08',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw21_24_dat08_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw21_24_dat08_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat08_v1' and status='draft'), keys(k,role) as (values('P5DAT08-D01','diagnostic'),('P5DAT08-L01','learning'),('P5DAT08-L02','learning'),('P5DAT08-L03','learning'),('P5DAT08-R01','retest'),('P5DAT08-R02','retest'),('P5DAT08-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DAT-08','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw21_24_dat08_v1 from canonical dataset-comparison intent.','Cambridge 9709 2026-2027 v4; P5 5.1 Representation of data','Complete Probability & Statistics 1; representation/comparison of data (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw21_24_dat08_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw21_24_dat08_v1' and m.content_key='P5DAT08-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','reverses_location_and_spread','concept','Median 74 is higher than 70, so B has the higher centre; IQR 10 is smaller than 18, so A has the smaller spread.','Медиана 74 выше 70, поэтому центр выше у B; IQR 10 меньше 18, поэтому разброс меньше у A.','74 medianasi 70 dan katta, markaz B da yuqori; IQR 10 18 dan kichik, tarqalish A da kam.','Compare like with like: median to median, IQR to IQR.','Сравнивайте одинаковые показатели: медиану с медианой, IQR с IQR.','Bir xil ko‘rsatkichlarni taqqoslang: mediana-mediana, IQR-IQR.'),
('C','uses_location_as_consistency','concept','A larger median does not mean lower spread. Consistency is described by a spread measure such as IQR or standard deviation.','Большая медиана не означает меньший разброс. Стабильность оценивается IQR или стандартным отклонением.','Katta mediana kam tarqalishni bildirmaydi. Barqarorlik IQR yoki standart og‘ish bilan baholanadi.','Separate location language from spread language.','Разделяйте выводы о центре и разбросе.','Markaz va tarqalish xulosalarini ajrating.'),
('D','ignores_summary_differences','method','Both summary pairs differ: the medians differ and the IQRs differ.','Обе пары показателей различаются: и медианы, и IQR.','Ikkala ko‘rsatkich ham farq qiladi: medianalar ham, IQR lar ham.','State one location comparison and one spread comparison.','Сформулируйте одно сравнение центра и одно сравнение разброса.','Bitta markaz va bitta tarqalish taqqoslashini yozing.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-DAT-08',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r cross join meta on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat08_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5DAT08-W01','P5','P5-DAT-08','wtv1','Class A has median 72, IQR 12 and range 40. Class B has median 68, IQR 8 and range 18. Compare the two classes in context, making separate claims about typical performance and consistency, and explain which statistics support each claim.','У класса A медиана 72, IQR 12 и размах 40. У B медиана 68, IQR 8 и размах 18. Сравните классы в контексте, отдельно сформулировав выводы о типичном результате и стабильности и указав, какие показатели их подтверждают.','A sinf medianasi 72, IQR 12, range 40. B medianasi 68, IQR 8, range 18. Sinflarni kontekstda taqqoslab, odatiy natija va barqarorlik haqida alohida xulosa yozing va qaysi ko‘rsatkichlar dalil ekanini ayting.','{"max_marks":10,"criteria":[{"id":"location","marks":3,"rule":"States A has the higher typical result because median 72>68."},{"id":"iqr","marks":3,"rule":"States B is more consistent in the middle 50% because IQR 8<12."},{"id":"range","marks":2,"rule":"Notes B also has the smaller overall range 18<40, supporting lower overall spread."},{"id":"context","marks":2,"rule":"Uses cautious contextual language and does not claim every A score exceeds every B score."}]}','Keep centre and spread as separate comparisons; do not turn a summary-statistic comparison into a claim about every observation.','Разделяйте центр и разброс; не превращайте сравнение сводных показателей в утверждение о каждом наблюдении.','Markaz va tarqalishni alohida taqqoslang; summary ko‘rsatkichlardan har bir kuzatuv haqida xulosa chiqarmang.','published','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat08_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_dat08_diagnostic','diagnostic','P5 DAT-08 dataset comparison diagnostic','Диагностика P5 DAT-08: сравнение наборов','P5 DAT-08 to‘plam taqqoslash diagnostikasi'),('p5_dat08_learning','learning','Dataset comparison learning','Сравнение наборов данных: обучение','Ma’lumot to‘plamlarini taqqoslash: o‘rganish'),('p5_dat08_retest','retest','DAT-08 delayed retest','DAT-08 отложенный ретест','DAT-08 kechiktirilgan retest'),('p5_dat08_mixed','mixed','DAT-08 contextual comparison transfer','DAT-08 контекстный перенос','DAT-08 kontekstual transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat08_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_dat08_diagnostic',1,'P5DAT08-D01',null,'diagnostic',true),('p5_dat08_learning',1,'P5DAT08-L01',null,'learning',false),('p5_dat08_learning',2,'P5DAT08-L02',null,'learning',false),('p5_dat08_learning',3,'P5DAT08-L03',null,'learning',false),('p5_dat08_learning',4,null,'P5DAT08-W01','written',false),('p5_dat08_retest',1,'P5DAT08-R01',null,'retest',true),('p5_dat08_retest',2,'P5DAT08-R02',null,'retest',true),('p5_dat08_mixed',1,'P5DAT08-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-DAT-08',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat08_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw21_24_dat08_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat08_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw21_24_dat08_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw21_24_dat08_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-DAT-08') then raise exception 'P5 DAT-08 not ready'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw21_24_dat08_v1:%' and is_active) then raise exception 'P5 DAT-08 legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P5 DAT-08 publication escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P5 DAT-08 active entitlement residue'; end if;
end $$;
commit;