-- P1-02 P5 AW13-16: GEO-01 geometric model recognition and assumptions.
-- Original iClub-authored content only; governed publication; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw13_16_geo01_v1','P5','P5 AW13-16 GEO-01 geometric model selection','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_geo01_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5GEO01-D01','diagnostic','medium','Independent trials have success probability 0.20 and continue until the first success. Which model fits X, the trial number of the first success?','Независимые испытания с вероятностью успеха 0,20 продолжаются до первого успеха. Какая модель подходит для X — номера испытания первого успеха?','Mustaqil sinovlarda muvaffaqiyat ehtimoli 0.20 va birinchi muvaffaqiyatgacha davom etadi. Birinchi muvaffaqiyat sinovi raqami X uchun qaysi model mos?','["Geometric with p=0.20","Binomial with n=20","Uniform over positive integers","Normal with mean 0.20"]','["Геометрическая с p=0,20","Биномиальная с n=20","Равномерная по положительным целым","Нормальная со средним 0,20"]','["p=0.20 geometrik","n=20 binomial","Musbat butunlarda tekis","O‘rtachasi 0.20 normal"]','A','A geometric variable records the waiting time to the first success in independent constant-p trials.','Геометрическая случайная величина задаёт время ожидания первого успеха в независимых испытаниях с постоянной p.','Geometrik tasodifiy miqdor mustaqil, doimiy-p sinovlarda birinchi muvaffaqiyatgacha kutish vaqtini ifodalaydi.',55),
('P5GEO01-L01','learning','easy','A fair die is rolled until the first six. What is the success probability p for the geometric model?','Честный кубик бросают до первой шестёрки. Чему равна вероятность успеха p в геометрической модели?','Adolatli kubik birinchi olti tushguncha tashlanadi. Geometrik modelda muvaffaqiyat ehtimoli p nechaga teng?','["1/6","5/6","1/36","6"]','["1/6","5/6","1/36","6"]','["1/6","5/6","1/36","6"]','A','Each independent roll has success probability P(6)=1/6.','В каждом независимом броске вероятность успеха P(6)=1/6.','Har bir mustaqil tashlashda muvaffaqiyat ehtimoli P(6)=1/6.',35),
('P5GEO01-L02','learning','medium','A coin is tossed exactly 10 times and X is the number of heads. Is X geometric?','Монету подбрасывают ровно 10 раз, X — число орлов. Имеет ли X геометрическое распределение?','Tanga aynan 10 marta tashlanadi, X — gerblar soni. X geometrikmi?','["No; X counts successes in a fixed number of trials","Yes; every toss has two outcomes","Yes; the tosses are independent","No; a geometric variable cannot use a coin"]','["Нет; X считает успехи в фиксированном числе испытаний","Да; у каждого броска два исхода","Да; броски независимы","Нет; геометрическая модель не может использовать монету"]','["Yo‘q; X qat’iy sinovlar sonidagi muvaffaqiyatlarni sanaydi","Ha; har tashlashda ikki natija bor","Ha; tashlashlar mustaqil","Yo‘q; geometrik model tangada bo‘lmaydi"]','A','This is a fixed-n success count, which is binomial-style, not a waiting time to the first success.','Это число успехов при фиксированном n, то есть биномиальный тип, а не ожидание первого успеха.','Bu qat’iy n dagi muvaffaqiyatlar soni, ya’ni binomial tur; birinchi muvaffaqiyatgacha kutish emas.',50),
('P5GEO01-L03','learning','medium','Cards are drawn without replacement until the first red card appears. Why is an ordinary geometric model not exact?','Карты выбирают без возвращения до появления первой красной. Почему обычная геометрическая модель не является точной?','Kartalar qaytarmasdan birinchi qizil karta chiqquncha olinadi. Nega oddiy geometrik model aniq emas?','["The success probability changes from draw to draw","The number of trials is not fixed","There are two outcome categories","The first red card may occur on trial 1"]','["Вероятность успеха меняется от выбора к выбору","Число испытаний не фиксировано","Есть две категории исхода","Первая красная может появиться в первом испытании"]','["Muvaffaqiyat ehtimoli tanlovdan tanlovga o‘zgaradi","Sinovlar soni qat’iy emas","Ikki natija toifasi bor","Birinchi qizil 1-sinovda chiqishi mumkin"]','A','Without replacement changes the remaining composition, so the trials do not have a constant success probability.','Без возвращения состав оставшихся карт меняется, поэтому вероятность успеха непостоянна.','Qaytarmasdan olish qolgan tarkibni o‘zgartiradi, shuning uchun muvaffaqiyat ehtimoli doimiy emas.',55),
('P5GEO01-R01','retest','easy','Independent website visitors convert with probability 0.08. X is the visitor number of the first conversion. Which model fits X?','Независимые посетители сайта совершают конверсию с вероятностью 0,08. X — номер посетителя первой конверсии. Какая модель подходит?','Mustaqil sayt tashrifchilari 0.08 ehtimol bilan konversiya qiladi. X — birinchi konversiya qilgan tashrifchi raqami. Qaysi model mos?','["Geometric with p=0.08","Binomial with n=8","Uniform","Poisson with parameter 0.08"]','["Геометрическая с p=0,08","Биномиальная с n=8","Равномерная","Пуассоновская с параметром 0,08"]','["p=0.08 geometrik","n=8 binomial","Tekis","Parametri 0.08 Puasson"]','A','X is the waiting count to the first success with independent constant-p trials.','X — число испытаний до первого успеха при независимых испытаниях с постоянной p.','X — mustaqil, doimiy-p sinovlarda birinchi muvaffaqiyatgacha sinovlar soni.',40),
('P5GEO01-R02','retest','medium','If X has a geometric distribution with p=0.30, what does X=4 mean?','Если X имеет геометрическое распределение с p=0,30, что означает X=4?','X p=0.30 geometrik taqsimotga ega bo‘lsa, X=4 nimani anglatadi?','["The first success occurs on trial 4","There are four successes","Success probability equals 4","Exactly four trials are always performed"]','["Первый успех происходит в 4-м испытании","Происходит четыре успеха","Вероятность успеха равна 4","Всегда выполняют ровно четыре испытания"]','["Birinchi muvaffaqiyat 4-sinovda chiqadi","To‘rtta muvaffaqiyat bor","Muvaffaqiyat ehtimoli 4","Har doim aynan to‘rtta sinov qilinadi"]','A','Under the trial-number convention, X records the trial on which the first success occurs.','При соглашении о номере испытания X показывает номер испытания первого успеха.','Sinov-raqami kelishuvida X birinchi muvaffaqiyat chiqqan sinov raqamini bildiradi.',45),
('P5GEO01-M01','mixed','medium','Which statement correctly distinguishes binomial and geometric models?','Какое утверждение правильно различает биномиальную и геометрическую модели?','Qaysi gap binomial va geometrik modellarni to‘g‘ri farqlaydi?','["Binomial counts successes in fixed n; geometric counts trials to first success","Binomial always has variable n; geometric always has fixed n","Both require sampling without replacement","Geometric counts total successes in a fixed sample"]','["Биномиальная считает успехи при фиксированном n; геометрическая — испытания до первого успеха","У биномиальной n всегда переменно; у геометрической всегда фиксировано","Обе требуют выбора без возвращения","Геометрическая считает общее число успехов в фиксированной выборке"]','["Binomial qat’iy n da muvaffaqiyatlarni sanaydi; geometrik birinchi muvaffaqiyatgacha sinovlarni sanaydi","Binomialda n doim o‘zgaradi; geometrikda doim qat’iy","Ikkalasi qaytarmasdan tanlashni talab qiladi","Geometrik qat’iy tanlamadagi jami muvaffaqiyatlarni sanaydi"]','A','The defining distinction is fixed-n success count versus waiting time to first success; both standard models require independent constant-p trials.','Главное различие — число успехов при фиксированном n против ожидания первого успеха; обе стандартные модели требуют независимых испытаний с постоянной p.','Asosiy farq — qat’iy n dagi muvaffaqiyatlar soni va birinchi muvaffaqiyatgacha kutish; ikkala standart model ham mustaqil doimiy-p sinovlarni talab qiladi.',55)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Geometric Distribution','P5-GEO-01',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw13_16_geo01_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_geo01_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_geo01_v1' and status='draft'), keys(k,role) as (values('P5GEO01-D01','diagnostic'),('P5GEO01-L01','learning'),('P5GEO01-L02','learning'),('P5GEO01-L03','learning'),('P5GEO01-R01','retest'),('P5GEO01-R02','retest'),('P5GEO01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-GEO-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw13_16_geo01_v1 from canonical GEO-01 intent.','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1; Geometric distribution (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_geo01_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw13_16_geo01_v1' and m.content_key='P5GEO01-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','fixed_count_confusion','concept','The value 0.20 is a success probability, not a fixed trial count n=20. The experiment stops at the first success.','Значение 0,20 — вероятность успеха, а не фиксированное число испытаний n=20. Эксперимент останавливается при первом успехе.','0.20 muvaffaqiyat ehtimoli, n=20 qat’iy sinov soni emas. Tajriba birinchi muvaffaqiyatda to‘xtaydi.','Ask whether X counts successes in fixed n or waits for the first success.','Определите: X считает успехи при фиксированном n или ждёт первый успех?','X qat’iy n dagi muvaffaqiyatlarni sanaydimi yoki birinchi muvaffaqiyatni kutadimi?'),
('C','uniform_waiting_time','concept','Waiting times are not equally likely: later first-success times require more preceding failures.','Времена ожидания не равновероятны: более поздний первый успех требует большего числа предыдущих неудач.','Kutish vaqtlari teng ehtimolli emas: kechroq birinchi muvaffaqiyat oldin ko‘proq muvaffaqiyatsizlik talab qiladi.','Use the repeated failure-then-success structure.','Используйте структуру повторных неудач, затем успеха.','Takroriy muvaffaqiyatsizliklar, keyin muvaffaqiyat tuzilmasidan foydalaning.'),
('D','wrong_distribution_family','concept','A probability of 0.20 does not make a normal model; the discrete waiting-time structure determines the family.','Вероятность 0,20 не делает модель нормальной; семейство определяется дискретной структурой ожидания.','0.20 ehtimol modelni normal qilmaydi; oilani diskret kutish tuzilmasi belgilaydi.','Identify the random variable before choosing a distribution.','Сначала определите случайную величину, затем выбирайте распределение.','Avval tasodifiy miqdorni aniqlang, keyin taqsimotni tanlang.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-GEO-01',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from meta cross join r
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_geo01_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5GEO01-W01','P5','P5-GEO-01','wtv1','For each scenario, decide whether an ordinary geometric model is valid and justify using first-success waiting time, independence and constant p: (i) roll a fair die until the first six; (ii) toss a biased coin independently until the first head, with P(head)=0.35; (iii) draw cards without replacement until the first heart. For each valid case state p and define X precisely.','Для каждого сценария решите, корректна ли обычная геометрическая модель, и обоснуйте через ожидание первого успеха, независимость и постоянную p: (i) бросать честный кубик до первой шестёрки; (ii) независимо подбрасывать смещённую монету до первого орла при P(орёл)=0,35; (iii) выбирать карты без возвращения до первой червы. Для корректных случаев укажите p и точно определите X.','Har bir holat uchun oddiy geometrik model to‘g‘rimi, aniqlang va birinchi muvaffaqiyatgacha kutish, mustaqillik va doimiy p bilan asoslang: (i) adolatli kubikni birinchi oltigacha tashlash; (ii) P(gerb)=0.35 bo‘lgan tangani mustaqil ravishda birinchi gerbgacha tashlash; (iii) kartalarni qaytarmasdan birinchi yurakkacha olish. To‘g‘ri holatlar uchun p ni va X ni aniq yozing.','{"max_marks":11,"criteria":[{"id":"criteria","marks":3,"rule":"States waiting-to-first-success plus independence and constant-p conditions."},{"id":"die","marks":2,"rule":"Accepts (i), p=1/6, X=trial number of first six."},{"id":"coin","marks":2,"rule":"Accepts (ii), p=0.35, X=trial number of first head."},{"id":"cards","marks":3,"rule":"Rejects (iii) because without replacement changes p and creates dependence."},{"id":"communication","marks":1,"rule":"Defines X consistently using the trial-number convention."}]}','Define what X counts before judging the model; then check independence and constant p.','Сначала определите, что считает X, затем проверьте независимость и постоянство p.','Avval X nimani sanashini aniqlang, keyin mustaqillik va doimiy p ni tekshiring.','approved','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_geo01_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_geo01_diagnostic','diagnostic','GEO-01 diagnostic','Диагностика GEO-01','GEO-01 diagnostikasi'),('p5_geo01_learning','learning','GEO-01 learning','GEO-01 обучение','GEO-01 o‘rganish'),('p5_geo01_retest','retest','GEO-01 delayed retest','GEO-01 отложенный ретест','GEO-01 kechiktirilgan retest'),('p5_geo01_mixed','mixed','GEO-01 mixed transfer','GEO-01 смешанный перенос','GEO-01 mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_geo01_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_geo01_diagnostic',1,'P5GEO01-D01',null,'diagnostic',true),('p5_geo01_learning',1,'P5GEO01-L01',null,'learning',false),('p5_geo01_learning',2,'P5GEO01-L02',null,'learning',false),('p5_geo01_learning',3,'P5GEO01-L03',null,'learning',false),('p5_geo01_learning',4,null,'P5GEO01-W01','written',false),('p5_geo01_retest',1,'P5GEO01-R01',null,'retest',true),('p5_geo01_mixed',1,'P5GEO01-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-GEO-01',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_geo01_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw13_16_geo01_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_geo01_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw13_16_geo01_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw13_16_geo01_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw13_16_geo01_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-GEO-01') then raise exception 'GEO-01 not ready after publish'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw13_16_geo01_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
