-- AW13-16 written-understanding checks draft v1.
-- One trilingual understanding check per new written learning task.
begin;
set local lock_timeout='3s';
set local statement_timeout='60s';

do $preflight$
begin
  if (select count(*) from private.exam_prep_written_tasks
      where id between 15638 and 15652 and content_version_id in (4813,4814) and lifecycle_state='draft')<>15
  then raise exception 'aw13_16_written_checks expected 15 draft written tasks'; end if;

  if exists(select 1 from private.exam_prep_written_understanding_checks
            where id between 8938 and 8952 and written_task_id not between 15638 and 15652)
  then raise exception 'aw13_16_written_checks reserved id collision'; end if;
end
$preflight$;

insert into private.exam_prep_written_understanding_checks(
 id,written_task_id,check_order,check_version,check_kind,
 prompt_en,prompt_ru,prompt_uz,options_en,options_ru,options_uz,correct_index,
 rationale_en,rationale_ru,rationale_uz,lifecycle_state,qa_math_status,qa_language_status,qa_technical_status
)
overriding system value
values
(8938,15638,1,'aw14-v1','mcq','Why is a minor segment area found by subtracting the triangle area from the sector area?','Почему площадь меньшего сегмента находят вычитанием площади треугольника из площади сектора?','Nega kichik segment yuzi sektor yuzidan uchburchak yuzini ayirish orqali topiladi?','["Because the sector is exactly the triangle plus the minor segment","Because a segment is always half a sector","Because the triangle lies outside the sector","Because sector area already excludes the triangle"]'::jsonb,'["Потому что сектор состоит ровно из треугольника и меньшего сегмента","Потому что сегмент всегда равен половине сектора","Потому что треугольник лежит вне сектора","Потому что площадь сектора уже не включает треугольник"]'::jsonb,'["Chunki sektor aynan uchburchak va kichik segmentdan iborat","Chunki segment doim sektorning yarmi","Chunki uchburchak sektordan tashqarida","Chunki sektor yuzi uchburchakni allaqachon hisobga olmaydi"]'::jsonb,0,'The two radii and chord split the sector into the central triangle and the corresponding segment, so subtracting the triangle leaves the segment.','Два радиуса и хорда делят сектор на центральный треугольник и соответствующий сегмент, поэтому после вычитания треугольника остаётся сегмент.','Ikki radius va vatar sektorni markaziy uchburchak va mos segmentga ajratadi, shuning uchun uchburchakni ayirganda segment qoladi.','draft','pending','pending','pending'),
(8939,15639,1,'aw14-v1','mcq','After finding a reference angle, what determines the sign of an exact trigonometric value?','После нахождения опорного угла что определяет знак точного тригонометрического значения?','Tayanch burchak topilgach, aniq trigonometrik qiymat ishorasini nima belgilaydi?','["The size of the reference angle only","The quadrant of the original angle and the sign of that trig function there","Whether the angle is written in degrees","The numerator of the exact value"]'::jsonb,'["Только величина опорного угла","Четверть исходного угла и знак данной функции в этой четверти","Записан ли угол в градусах","Числитель точного значения"]'::jsonb,'["Faqat tayanch burchak kattaligi","Asl burchak joylashgan chorak va shu funksiyaning o‘sha chorakdagi ishorasi","Burchak gradusda yozilganligi","Aniq qiymatning surati"]'::jsonb,1,'The reference angle gives the magnitude; the original quadrant determines whether sine, cosine or tangent is positive or negative.','Опорный угол задаёт модуль значения, а четверть исходного угла определяет знак синуса, косинуса или тангенса.','Tayanch burchak qiymat modulini beradi, asl burchak choragi esa sinus, kosinus yoki tangens ishorasini belgilaydi.','draft','pending','pending','pending'),
(8940,15640,1,'aw14-v1','mcq','Why does sin⁻¹(1/2) return 30° rather than both 30° and 150°?','Почему sin⁻¹(1/2) возвращает 30°, а не одновременно 30° и 150°?','Nega sin⁻¹(1/2) bir vaqtning o‘zida 30° va 150° ni emas, 30° ni qaytaradi?','["Because 150° is not an angle","Because sine is one-one on all real angles","Because the inverse function is restricted to a principal-value range","Because 150° has negative sine"]'::jsonb,'["Потому что 150° не является углом","Потому что синус взаимно однозначен на всех действительных углах","Потому что обратная функция ограничена диапазоном главных значений","Потому что sin150° отрицателен"]'::jsonb,'["Chunki 150° burchak emas","Chunki sinus barcha haqiqiy burchaklarda bir qiymatli","Chunki teskari funksiya bosh qiymatlar oralig‘i bilan cheklangan","Chunki sin150° manfiy"]'::jsonb,2,'An inverse trigonometric function must be a function, so it uses a restricted principal range and returns one selected value.','Обратная тригонометрическая функция должна оставаться функцией, поэтому используется ограниченный диапазон главных значений и возвращается одно выбранное значение.','Teskari trigonometrik funksiya funksiya bo‘lib qolishi kerak, shu sababli cheklangan bosh qiymatlar oralig‘i olinadi va bitta tanlangan qiymat qaytariladi.','draft','pending','pending','pending'),
(8941,15641,1,'aw14-v1','mcq','Why must denominator restrictions be stated when simplifying a trigonometric identity?','Почему при упрощении тригонометрического тождества нужно указывать ограничения на знаменатель?','Nega trigonometrik ayniyatni soddalashtirganda maxraj cheklovlari yozilishi kerak?','["Because every trig identity is true only for positive angles","Because restrictions change the value of sine","Because the numerator may otherwise be zero","Because division is valid only where the denominator is non-zero"]'::jsonb,'["Потому что любое тригонометрическое тождество верно только для положительных углов","Потому что ограничения меняют значение синуса","Потому что иначе числитель может быть нулём","Потому что деление допустимо только там, где знаменатель не равен нулю"]'::jsonb,'["Chunki har bir trigonometrik ayniyat faqat musbat burchaklarda to‘g‘ri","Chunki cheklovlar sinus qiymatini o‘zgartiradi","Chunki aks holda surat nol bo‘lishi mumkin","Chunki bo‘lish faqat maxraj nol bo‘lmagan joyda mumkin"]'::jsonb,3,'Algebraic cancellation or division can introduce conditions. An identity involving a denominator is only valid where that denominator is defined and non-zero.','Сокращение или деление может вводить условия. Тождество со знаменателем имеет смысл только там, где знаменатель определён и не равен нулю.','Algebraik qisqartirish yoki bo‘lish shartlar kiritadi. Maxrajli ayniyat faqat maxraj aniqlangan va nol bo‘lmagan joyda to‘g‘ri.','draft','pending','pending','pending'),
(8942,15642,1,'aw14-v1','mcq','What is the safest way to avoid losing solutions in a simple trigonometric equation on a stated interval?','Как надёжнее всего не потерять решения простого тригонометрического уравнения на заданном промежутке?','Berilgan oraliqdagi sodda trigonometrik tenglamada yechimlarni yo‘qotmaslikning eng ishonchli usuli qaysi?','["Find the reference angle, use all valid quadrants/periods, then filter by the stated interval","Use only the calculator principal value","Keep only the smallest positive angle","Assume there are always two solutions"]'::jsonb,'["Найти опорный угол, учесть все подходящие четверти/периоды и затем отфильтровать по заданному промежутку","Использовать только главное значение калькулятора","Оставить только наименьший положительный угол","Считать, что решений всегда два"]'::jsonb,'["Tayanch burchakni topib, barcha mos chorak/davrlarni hisobga olish va keyin berilgan oraliq bo‘yicha tanlash","Faqat kalkulyatorning bosh qiymatini olish","Faqat eng kichik musbat burchakni qoldirish","Har doim ikkita yechim bor deb olish"]'::jsonb,0,'Principal values are only a starting point. Quadrant symmetry and periodicity generate candidates, and the stated interval decides which candidates belong.','Главное значение — только отправная точка. Симметрия по четвертям и периодичность дают кандидатов, а заданный промежуток определяет, какие из них подходят.','Bosh qiymat faqat boshlanish nuqtasi. Chorak simmetriyasi va davriylik nomzodlarni beradi, berilgan oraliq esa qaysilari mosligini belgilaydi.','draft','pending','pending','pending'),
(8943,15643,1,'aw14-v1','mcq','When finding the coefficient of x² in a product of two expansions, which terms can contribute?','При поиске коэффициента при x² в произведении двух разложений какие члены могут дать вклад?','Ikki yoyilma ko‘paytmasida x² koeffitsiyentini topishda qaysi hadlar hissa qo‘sha oladi?','["Only the x² term from the first expansion","Pairs of terms whose powers add to 2","Every term containing x","Only the constant terms"]'::jsonb,'["Только член x² из первого разложения","Пары членов, степени которых в сумме дают 2","Все члены, содержащие x","Только свободные члены"]'::jsonb,'["Faqat birinchi yoyilmadagi x² hadi","Darajalari yig‘indisi 2 bo‘ladigan hadlar juftlari","x qatnashgan barcha hadlar","Faqat o‘zgarmas hadlar"]'::jsonb,1,'In a product, exponents add. Therefore x² comes from combinations such as constant×x² and x×x, depending on the factors.','В произведении показатели степеней складываются. Поэтому x² получается из комбинаций вроде свободный член×x² и x×x в зависимости от множителей.','Ko‘paytmada darajalar qo‘shiladi. Shuning uchun x² o‘zgarmas had×x² yoki x×x kabi mos juftliklardan keladi.','draft','pending','pending','pending'),
(8944,15644,1,'aw14-v1','mcq','What property identifies a geometric progression?','Какое свойство определяет геометрическую прогрессию?','Geometrik progressiyani qaysi xususiyat aniqlaydi?','["A constant difference between all consecutive terms","Every term is positive","A constant ratio between all consecutive non-zero terms","The terms must decrease"]'::jsonb,'["Постоянная разность между соседними членами","Все члены положительны","Постоянное отношение между всеми соседними ненулевыми членами","Члены обязаны убывать"]'::jsonb,'["Ketma-ket hadlar orasidagi doimiy ayirma","Barcha hadlar musbat","Ketma-ket nol bo‘lmagan hadlar orasidagi doimiy nisbat","Hadlar albatta kamayishi"]'::jsonb,2,'A geometric progression is generated by multiplying by the same ratio from one term to the next.','Геометрическая прогрессия получается умножением каждого члена на один и тот же постоянный знаменатель.','Geometrik progressiyada har bir keyingi had oldingi hadni bir xil doimiy nisbatga ko‘paytirish orqali olinadi.','draft','pending','pending','pending'),
(8945,15645,1,'aw14-v1','mcq','What makes a derivative an instantaneous rate rather than an average rate over an interval?','Что делает производную мгновенной скоростью изменения, а не средней скоростью на промежутке?','Hosilani oraliqdagi o‘rtacha tezlik emas, oniy o‘zgarish tezligi qiladigan narsa nima?','["It always uses whole-number inputs","It ignores changes in the function value","It measures a vertical distance only","It is the limit of the difference quotient as the interval width tends to zero"]'::jsonb,'["Она всегда использует только целые значения аргумента","Она игнорирует изменение значения функции","Она измеряет только вертикальное расстояние","Она является пределом разностного отношения при стремлении ширины промежутка к нулю"]'::jsonb,'["U doim faqat butun argumentlardan foydalanadi","U funksiya qiymati o‘zgarishini e’tiborsiz qoldiradi","U faqat vertikal masofani o‘lchaydi","U oraliq kengligi nolga intilgandagi ayirmali nisbat limitidir"]'::jsonb,3,'The secant gradient over a finite interval becomes the tangent gradient at a point in the limit as the interval shrinks to zero.','Градиент секущей на конечном промежутке в пределе при сжатии промежутка до нуля становится градиентом касательной в точке.','Chekli oraliqdagi kesuvchi gradienti oraliq nolga qisqarganda limitda nuqtadagi urinma gradientiga aylanadi.','draft','pending','pending','pending'),
(8946,15646,1,'aw14-v1','mcq','In P(A|B), which probability belongs in the denominator?','В P(A|B) какая вероятность должна стоять в знаменателе?','P(A|B) da qaysi ehtimol maxrajda turishi kerak?','["P(B), because B is the condition defining the restricted sample space","P(A), because A is written first","P(A∩B)","P(A∪B)"]'::jsonb,'["P(B), потому что B — условие, задающее ограниченное пространство исходов","P(A), потому что A записано первым","P(A∩B)","P(A∪B)"]'::jsonb,'["P(B), chunki B cheklangan natijalar fazosini belgilovchi shart","P(A), chunki A birinchi yozilgan","P(A∩B)","P(A∪B)"]'::jsonb,0,'Conditioning on B means we work inside event B. The fraction is therefore P(A∩B)/P(B).','Условие B означает, что мы рассматриваем исходы внутри B. Поэтому дробь имеет вид P(A∩B)/P(B).','B sharti B hodisasi ichida ishlashni anglatadi. Shuning uchun kasr P(A∩B)/P(B) bo‘ladi.','draft','pending','pending','pending'),
(8947,15647,1,'aw14-v1','mcq','How are probabilities combined on a probability tree when several different branches lead to the same final event?','Как объединяются вероятности на дереве, если несколько разных ветвей приводят к одному итоговому событию?','Bir nechta turli shoxlar bir xil yakuniy hodisaga olib kelsa, ehtimollar daraxtida ehtimollar qanday birlashtiriladi?','["Add along each branch, then multiply the totals","Multiply along each complete route, then add the probabilities of the relevant routes","Always multiply every branch in the tree","Use only the most likely route"]'::jsonb,'["Сложить вероятности вдоль каждой ветви, затем перемножить суммы","Перемножить вероятности вдоль каждого полного пути, затем сложить вероятности подходящих путей","Всегда перемножать все ветви дерева","Использовать только самый вероятный путь"]'::jsonb,'["Har bir shox bo‘ylab qo‘shib, keyin yig‘indilarni ko‘paytirish","Har bir to‘liq yo‘l bo‘ylab ko‘paytirib, keyin mos yo‘llar ehtimollarini qo‘shish","Daraxtdagi barcha shoxlarni doim ko‘paytirish","Faqat eng ehtimolli yo‘ldan foydalanish"]'::jsonb,1,'Multiplication gives the probability of following one complete route. Mutually exclusive routes for the same event are then added.','Перемножение даёт вероятность одного полного пути. Затем взаимоисключающие пути, соответствующие одному событию, складываются.','Ko‘paytirish bitta to‘liq yo‘l ehtimolini beradi. Bir xil hodisaga tegishli o‘zaro istisno yo‘llar keyin qo‘shiladi.','draft','pending','pending','pending'),
(8948,15648,1,'aw14-v1','mcq','What two checks are required for a valid discrete probability distribution?','Какие две проверки нужны для корректного дискретного распределения вероятностей?','To‘g‘ri diskret ehtimollar taqsimoti uchun qaysi ikki tekshiruv kerak?','["The values of X must sum to 1 and be positive","The probabilities must all be equal","Every probability lies between 0 and 1, and all probabilities sum to 1","There must be exactly four outcomes"]'::jsonb,'["Значения X должны давать в сумме 1 и быть положительными","Все вероятности должны быть одинаковыми","Каждая вероятность лежит от 0 до 1, и сумма всех вероятностей равна 1","Должно быть ровно четыре исхода"]'::jsonb,'["X qiymatlari yig‘indisi 1 va musbat bo‘lishi kerak","Barcha ehtimollar teng bo‘lishi kerak","Har bir ehtimol 0 va 1 orasida bo‘lib, barcha ehtimollar yig‘indisi 1 bo‘lishi kerak","Aynan to‘rtta natija bo‘lishi kerak"]'::jsonb,2,'Probability values cannot be negative or exceed 1, and the mutually exclusive possible outcomes together must carry total probability 1.','Вероятности не могут быть отрицательными или больше 1, а все возможные взаимоисключающие исходы вместе должны иметь суммарную вероятность 1.','Ehtimollar manfiy yoki 1 dan katta bo‘la olmaydi va barcha mumkin bo‘lgan o‘zaro istisno natijalarning umumiy ehtimoli 1 bo‘lishi kerak.','draft','pending','pending','pending'),
(8949,15649,1,'aw14-v1','mcq','What is the correct interpretation of a positive expected gain of 0.4 units per game?','Как правильно интерпретировать положительный ожидаемый выигрыш 0,4 единицы за игру?','Har bir o‘yin uchun musbat 0.4 birlik kutiladigan yutuqni qanday to‘g‘ri talqin qilish kerak?','["Every single game wins exactly 0.4 units","The next game is guaranteed to be profitable","The probability of winning is 0.4","Over many repetitions, the average net gain tends toward about 0.4 units per game"]'::jsonb,'["Каждая отдельная игра приносит ровно 0,4 единицы","Следующая игра гарантированно будет прибыльной","Вероятность выигрыша равна 0,4","При большом числе повторений средний чистый выигрыш стремится примерно к 0,4 единицы за игру"]'::jsonb,'["Har bir alohida o‘yin aynan 0.4 birlik yutuq beradi","Keyingi o‘yin albatta foydali bo‘ladi","Yutish ehtimoli 0.4","Ko‘p takrorlashda o‘rtacha sof yutuq har bir o‘yinga taxminan 0.4 birlikka yaqinlashadi"]'::jsonb,3,'Expectation is a long-run weighted average, not a guaranteed outcome for one trial.','Математическое ожидание — это долгосрочное взвешенное среднее, а не гарантированный результат одного испытания.','Kutilma uzoq muddatli og‘irlikli o‘rtacha bo‘lib, bitta sinov uchun kafolatlangan natija emas.','draft','pending','pending','pending'),
(8950,15650,1,'aw14-v1','mcq','Which formula correctly connects variance with E(X) and E(X²)?','Какая формула правильно связывает дисперсию с E(X) и E(X²)?','Qaysi formula dispersiyani E(X) va E(X²) bilan to‘g‘ri bog‘laydi?','["Var(X)=E(X²)−[E(X)]²","Var(X)=[E(X²)]²−E(X)","Var(X)=E(X²)−E(X)","Var(X)=E(X²)+[E(X)]²"]'::jsonb,'["Var(X)=E(X²)−[E(X)]²","Var(X)=[E(X²)]²−E(X)","Var(X)=E(X²)−E(X)","Var(X)=E(X²)+[E(X)]²"]'::jsonb,'["Var(X)=E(X²)−[E(X)]²","Var(X)=[E(X²)]²−E(X)","Var(X)=E(X²)−E(X)","Var(X)=E(X²)+[E(X)]²"]'::jsonb,0,'Variance equals the second moment minus the square of the mean.','Дисперсия равна второму моменту минус квадрат математического ожидания.','Dispersiya ikkinchi momentdan o‘rtachaning kvadratini ayirishga teng.','draft','pending','pending','pending'),
(8951,15651,1,'aw14-v1','mcq','Which set of conditions is required for an exact binomial model?','Какой набор условий требуется для точной биномиальной модели?','Aniq binomial model uchun qaysi shartlar to‘plami kerak?','["A variable number of trials and changing p","Fixed n, two outcomes, constant p and independent trials","Any experiment with two possible final totals","Trials must continue until the first success"]'::jsonb,'["Переменное число испытаний и меняющееся p","Фиксированное n, два исхода, постоянное p и независимые испытания","Любой эксперимент с двумя возможными итоговыми суммами","Испытания должны продолжаться до первого успеха"]'::jsonb,'["O‘zgaruvchan sinovlar soni va o‘zgaruvchi p","Belgilangan n, ikki natija, o‘zgarmas p va mustaqil sinovlar","Ikki mumkin bo‘lgan yakuniy songa ega har qanday tajriba","Sinovlar birinchi muvaffaqiyatgacha davom etishi kerak"]'::jsonb,1,'A binomial count uses a fixed number of independent Bernoulli trials with the same success probability.','Биномиальный счёт использует фиксированное число независимых испытаний Бернулли с одной и той же вероятностью успеха.','Binomial hisob bir xil muvaffaqiyat ehtimoliga ega belgilangan sondagi mustaqil Bernulli sinovlaridan foydalanadi.','draft','pending','pending','pending'),
(8952,15652,1,'aw14-v1','mcq','What does a geometric random variable usually count in this syllabus model?','Что обычно считает геометрическая случайная величина в этой модели курса?','Bu kurs modelida geometrik tasodifiy kattalik odatda nimani sanaydi?','["The number of successes in a fixed number of trials","The total value of all successes","The trial number on which the first success occurs","The number of failures after the final success"]'::jsonb,'["Число успехов в фиксированном количестве испытаний","Суммарное значение всех успехов","Номер испытания, на котором происходит первый успех","Число неудач после последнего успеха"]'::jsonb,'["Belgilangan sondagi sinovlardagi muvaffaqiyatlar soni","Barcha muvaffaqiyatlarning umumiy qiymati","Birinchi muvaffaqiyat sodir bo‘ladigan sinov raqami","Oxirgi muvaffaqiyatdan keyingi muvaffaqiyatsizliklar soni"]'::jsonb,2,'The geometric variable is a waiting-time variable: it records how many trials are needed until the first success.','Геометрическая случайная величина — это время ожидания: она показывает, сколько испытаний требуется до первого успеха.','Geometrik tasodifiy kattalik kutish vaqti bo‘lib, birinchi muvaffaqiyatgacha nechta sinov kerakligini ko‘rsatadi.','draft','pending','pending','pending')
on conflict(id) do nothing;

do $postcheck$
declare v_bad int;
begin
  if (select count(*) from private.exam_prep_written_understanding_checks
      where id between 8938 and 8952 and written_task_id between 15638 and 15652
        and lifecycle_state='draft' and qa_math_status='pending' and qa_language_status='pending' and qa_technical_status='pending')<>15
  then raise exception 'aw13_16_written_checks cardinality/state mismatch'; end if;

  select count(*) into v_bad from private.exam_prep_written_understanding_checks c
  where c.id between 8938 and 8952 and (
    jsonb_array_length(c.options_en)<>4 or jsonb_array_length(c.options_ru)<>4 or jsonb_array_length(c.options_uz)<>4
    or c.correct_index not between 0 and 3
    or nullif(btrim(c.prompt_en),'') is null or nullif(btrim(c.prompt_ru),'') is null or nullif(btrim(c.prompt_uz),'') is null
    or nullif(btrim(c.rationale_en),'') is null or nullif(btrim(c.rationale_ru),'') is null or nullif(btrim(c.rationale_uz),'') is null
  );
  if v_bad<>0 then raise exception 'aw13_16_written_checks structural/trilingual invalid=%',v_bad; end if;

  if (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8952 and correct_index=0)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8952 and correct_index=1)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8952 and correct_index=2)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8952 and correct_index=3)<>3
  then raise exception 'aw13_16_written_checks answer-position balance drift'; end if;
end
$postcheck$;

commit;
