-- AI-4 Chemistry Practice 1 precise source pack: Atomic structure.
-- Question-specific approved source cards for the 15 current Atomic structure questions.
-- This migration is source-only: it does not add diagnostics, enable AI, grant entitlements,
-- change scoring, or mutate learner academic/history state.

do $guard$
declare
  v_bad integer;
begin
  with expected(question_id,subtopic,qtype) as (
    values
    (1909,'Deflection in an electric field','mcq'),
    (1914,'Formation of positive ions','mcq'),
    (1916,'Properties of a neutral atom','mcq'),
    (1921,'Charge of a neutron','mcq'),
    (1925,'Periodic table position','mcq'),
    (1929,'Particle not deflected in an electric field','mcq'),
    (1933,'Mass number','mcq'),
    (1943,'Relative atomic mass (Ar)','mcq'),
    (1944,'Electrons in Cl⁻','input'),
    (1954,'Neutrons in copper isotope','input'),
    (1959,'Smallest relative mass of subatomic particles','mcq'),
    (1964,'Electrons in Fe³⁺','input'),
    (3041,'Rutherford scattering and the nucleus','mcq'),
    (3043,'Electron count in aluminium ion','input'),
    (3044,'Mass and charge in the nucleus','mcq')
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>4
     or q.is_active is not true
     or q.quality_status<>'published'
     or q.topic<>'Atomic structure'
     or q.subtopic<>e.subtopic
     or lower(coalesce(q.qtype,''))<>e.qtype;

  if v_bad<>0 then
    raise exception 'AI-4 Chemistry Atomic structure source batch refused: one or more target questions changed';
  end if;
end
$guard$;

insert into private.practice_ai_source_cards(
  source_card_key,subject_key,question_id,topic,subtopic,card_type,locale,source_version,
  title,body_text,approval_status,rights_status,is_runtime_allowed,content_hash,approved_at,updated_at
)
values
('practice:chemistry:p1:q1909:en:v1','chemistry',1909,'Atomic structure','Deflection in an electric field',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Deflection in an electric field','In an electric field, a charged particle experiences force F = qE. For particles with the same speed and equal charge magnitude, the lighter particle has the greater acceleration and is deflected more. Electrons and protons have equal charge magnitude, but the electron has far smaller mass. A neutron has zero charge, so an electric field does not deflect it.',
 'approved','original_iclub',true,encode(digest(convert_to('In an electric field, a charged particle experiences force F = qE. For particles with the same speed and equal charge magnitude, the lighter particle has the greater acceleration and is deflected more. Electrons and protons have equal charge magnitude, but the electron has far smaller mass. A neutron has zero charge, so an electric field does not deflect it.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1909:ru:v1','chemistry',1909,'Atomic structure','Deflection in an electric field',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Отклонение в электрическом поле','В электрическом поле на заряженную частицу действует сила F = qE. При одинаковой скорости и одинаковом модуле заряда более лёгкая частица получает большее ускорение и отклоняется сильнее. Электрон и протон имеют одинаковый по модулю заряд, но масса электрона намного меньше. Нейтрон имеет нулевой заряд, поэтому электрическое поле его не отклоняет.',
 'approved','original_iclub',true,encode(digest(convert_to('В электрическом поле на заряженную частицу действует сила F = qE. При одинаковой скорости и одинаковом модуле заряда более лёгкая частица получает большее ускорение и отклоняется сильнее. Электрон и протон имеют одинаковый по модулю заряд, но масса электрона намного меньше. Нейтрон имеет нулевой заряд, поэтому электрическое поле его не отклоняет.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1909:uz:v1','chemistry',1909,'Atomic structure','Deflection in an electric field',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Elektr maydonida og‘ish','Elektr maydonida zaryadlangan zarrachaga F = qE kuch ta’sir qiladi. Tezlik va zaryad moduli bir xil bo‘lsa, massasi kichikroq zarracha kattaroq tezlanish oladi va ko‘proq og‘adi. Elektron va proton zaryad moduli teng, lekin elektron massasi ancha kichik. Neytronning zaryadi nol, shuning uchun elektr maydoni uni og‘dirmaydi.',
 'approved','original_iclub',true,encode(digest(convert_to('Elektr maydonida zaryadlangan zarrachaga F = qE kuch ta’sir qiladi. Tezlik va zaryad moduli bir xil bo‘lsa, massasi kichikroq zarracha kattaroq tezlanish oladi va ko‘proq og‘adi. Elektron va proton zaryad moduli teng, lekin elektron massasi ancha kichik. Neytronning zaryadi nol, shuning uchun elektr maydoni uni og‘dirmaydi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1914:en:v1','chemistry',1914,'Atomic structure','Formation of positive ions',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Formation of positive ions','A positive ion, or cation, forms when a neutral atom loses one or more electrons. The number of protons in the nucleus does not change during ordinary ion formation. Losing negative charge leaves the particle with an overall positive charge.',
 'approved','original_iclub',true,encode(digest(convert_to('A positive ion, or cation, forms when a neutral atom loses one or more electrons. The number of protons in the nucleus does not change during ordinary ion formation. Losing negative charge leaves the particle with an overall positive charge.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1914:ru:v1','chemistry',1914,'Atomic structure','Formation of positive ions',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Образование положительных ионов','Положительный ион, или катион, образуется, когда нейтральный атом теряет один или несколько электронов. Число протонов в ядре при обычном образовании иона не меняется. Потеря отрицательного заряда приводит к положительному суммарному заряду частицы.',
 'approved','original_iclub',true,encode(digest(convert_to('Положительный ион, или катион, образуется, когда нейтральный атом теряет один или несколько электронов. Число протонов в ядре при обычном образовании иона не меняется. Потеря отрицательного заряда приводит к положительному суммарному заряду частицы.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1914:uz:v1','chemistry',1914,'Atomic structure','Formation of positive ions',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Musbat ionlarning hosil bo‘lishi','Musbat ion, ya’ni kation, neytral atom bir yoki bir nechta elektron yo‘qotganda hosil bo‘ladi. Oddiy ion hosil bo‘lishida yadrodagi protonlar soni o‘zgarmaydi. Manfiy zaryad yo‘qotilishi natijasida zarracha umumiy musbat zaryadga ega bo‘ladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Musbat ion, ya’ni kation, neytral atom bir yoki bir nechta elektron yo‘qotganda hosil bo‘ladi. Oddiy ion hosil bo‘lishida yadrodagi protonlar soni o‘zgarmaydi. Manfiy zaryad yo‘qotilishi natijasida zarracha umumiy musbat zaryadga ega bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1916:en:v1','chemistry',1916,'Atomic structure','Properties of a neutral atom',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Properties of a neutral atom','A neutral atom has no overall electric charge. Because each proton has charge +1 and each electron has charge -1, neutrality requires the number of protons to equal the number of electrons. The number of neutrons does not determine whether an atom is electrically neutral.',
 'approved','original_iclub',true,encode(digest(convert_to('A neutral atom has no overall electric charge. Because each proton has charge +1 and each electron has charge -1, neutrality requires the number of protons to equal the number of electrons. The number of neutrons does not determine whether an atom is electrically neutral.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1916:ru:v1','chemistry',1916,'Atomic structure','Properties of a neutral atom',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Свойства нейтрального атома','Нейтральный атом не имеет суммарного электрического заряда. Поскольку каждый протон имеет заряд +1, а каждый электрон -1, для нейтральности число протонов должно быть равно числу электронов. Число нейтронов не определяет электрическую нейтральность атома.',
 'approved','original_iclub',true,encode(digest(convert_to('Нейтральный атом не имеет суммарного электрического заряда. Поскольку каждый протон имеет заряд +1, а каждый электрон -1, для нейтральности число протонов должно быть равно числу электронов. Число нейтронов не определяет электрическую нейтральность атома.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1916:uz:v1','chemistry',1916,'Atomic structure','Properties of a neutral atom',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Neytral atom xossalari','Neytral atomning umumiy elektr zaryadi nol. Har bir proton +1, har bir elektron -1 zaryadga ega bo‘lgani uchun neytrallikda protonlar soni elektronlar soniga teng bo‘ladi. Neytronlar soni atomning elektr neytralligini belgilamaydi.',
 'approved','original_iclub',true,encode(digest(convert_to('Neytral atomning umumiy elektr zaryadi nol. Har bir proton +1, har bir elektron -1 zaryadga ega bo‘lgani uchun neytrallikda protonlar soni elektronlar soniga teng bo‘ladi. Neytronlar soni atomning elektr neytralligini belgilamaydi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1921:en:v1','chemistry',1921,'Atomic structure','Charge of a neutron',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Charge of a neutron','A neutron has zero electric charge. Protons are positively charged and electrons are negatively charged, while neutrons are electrically neutral. Neutrons still contribute substantially to the mass of the nucleus.',
 'approved','original_iclub',true,encode(digest(convert_to('A neutron has zero electric charge. Protons are positively charged and electrons are negatively charged, while neutrons are electrically neutral. Neutrons still contribute substantially to the mass of the nucleus.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1921:ru:v1','chemistry',1921,'Atomic structure','Charge of a neutron',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Заряд нейтрона','Нейтрон имеет нулевой электрический заряд. Протоны заряжены положительно, электроны — отрицательно, а нейтроны электрически нейтральны. При этом нейтроны вносят существенный вклад в массу ядра.',
 'approved','original_iclub',true,encode(digest(convert_to('Нейтрон имеет нулевой электрический заряд. Протоны заряжены положительно, электроны — отрицательно, а нейтроны электрически нейтральны. При этом нейтроны вносят существенный вклад в массу ядра.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1921:uz:v1','chemistry',1921,'Atomic structure','Charge of a neutron',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Neytron zaryadi','Neytronning elektr zaryadi nol. Protonlar musbat, elektronlar manfiy zaryadlangan, neytronlar esa elektr jihatdan neytral. Shunga qaramay, neytronlar yadro massasiga katta hissa qo‘shadi.',
 'approved','original_iclub',true,encode(digest(convert_to('Neytronning elektr zaryadi nol. Protonlar musbat, elektronlar manfiy zaryadlangan, neytronlar esa elektr jihatdan neytral. Shunga qaramay, neytronlar yadro massasiga katta hissa qo‘shadi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1925:en:v1','chemistry',1925,'Atomic structure','Periodic table position',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Periodic table position and atomic number','An element is defined by its atomic number, which is the number of protons in its nucleus. The modern Periodic Table is arranged by increasing atomic number. Changing the neutron number makes an isotope, not a different element.',
 'approved','original_iclub',true,encode(digest(convert_to('An element is defined by its atomic number, which is the number of protons in its nucleus. The modern Periodic Table is arranged by increasing atomic number. Changing the neutron number makes an isotope, not a different element.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1925:ru:v1','chemistry',1925,'Atomic structure','Periodic table position',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Положение в Периодической таблице','Элемент определяется его атомным номером, то есть числом протонов в ядре. Современная Периодическая таблица расположена по возрастанию атомного номера. Изменение числа нейтронов создаёт изотоп, а не другой элемент.',
 'approved','original_iclub',true,encode(digest(convert_to('Элемент определяется его атомным номером, то есть числом протонов в ядре. Современная Периодическая таблица расположена по возрастанию атомного номера. Изменение числа нейтронов создаёт изотоп, а не другой элемент.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1925:uz:v1','chemistry',1925,'Atomic structure','Periodic table position',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Davriy jadvaldagi o‘rin','Element uning atom raqami, ya’ni yadrosidagi protonlar soni bilan aniqlanadi. Zamonaviy Davriy jadval atom raqami ortib borish tartibida tuzilgan. Neytronlar sonining o‘zgarishi boshqa element emas, izotop hosil qiladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Element uning atom raqami, ya’ni yadrosidagi protonlar soni bilan aniqlanadi. Zamonaviy Davriy jadval atom raqami ortib borish tartibida tuzilgan. Neytronlar sonining o‘zgarishi boshqa element emas, izotop hosil qiladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1929:en:v1','chemistry',1929,'Atomic structure','Particle not deflected in an electric field',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Neutral particles in an electric field','An electric field exerts force on a particle only if the particle has electric charge. A neutron has zero charge, so it is not deflected by an electric field. Protons, electrons and ions carry charge and can be deflected.',
 'approved','original_iclub',true,encode(digest(convert_to('An electric field exerts force on a particle only if the particle has electric charge. A neutron has zero charge, so it is not deflected by an electric field. Protons, electrons and ions carry charge and can be deflected.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1929:ru:v1','chemistry',1929,'Atomic structure','Particle not deflected in an electric field',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Нейтральная частица в электрическом поле','Электрическое поле действует силой на частицу только при наличии электрического заряда. Нейтрон имеет нулевой заряд, поэтому электрическое поле его не отклоняет. Протоны, электроны и ионы заряжены и могут отклоняться.',
 'approved','original_iclub',true,encode(digest(convert_to('Электрическое поле действует силой на частицу только при наличии электрического заряда. Нейтрон имеет нулевой заряд, поэтому электрическое поле его не отклоняет. Протоны, электроны и ионы заряжены и могут отклоняться.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1929:uz:v1','chemistry',1929,'Atomic structure','Particle not deflected in an electric field',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Elektr maydonidagi neytral zarracha','Elektr maydoni zarrachaga faqat u elektr zaryadiga ega bo‘lsa kuch bilan ta’sir qiladi. Neytronning zaryadi nol, shuning uchun elektr maydoni uni og‘dirmaydi. Proton, elektron va ionlar zaryadga ega bo‘lib, og‘ishi mumkin.',
 'approved','original_iclub',true,encode(digest(convert_to('Elektr maydoni zarrachaga faqat u elektr zaryadiga ega bo‘lsa kuch bilan ta’sir qiladi. Neytronning zaryadi nol, shuning uchun elektr maydoni uni og‘dirmaydi. Proton, elektron va ionlar zaryadga ega bo‘lib, og‘ishi mumkin.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1933:en:v1','chemistry',1933,'Atomic structure','Mass number',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Mass number','Mass number A is the total number of nucleons in the nucleus: protons plus neutrons. Atomic number Z is only the number of protons. Electrons are not included in mass number.',
 'approved','original_iclub',true,encode(digest(convert_to('Mass number A is the total number of nucleons in the nucleus: protons plus neutrons. Atomic number Z is only the number of protons. Electrons are not included in mass number.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1933:ru:v1','chemistry',1933,'Atomic structure','Mass number',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Массовое число','Массовое число A — это общее число нуклонов в ядре: протонов плюс нейтронов. Атомный номер Z равен только числу протонов. Электроны в массовое число не входят.',
 'approved','original_iclub',true,encode(digest(convert_to('Массовое число A — это общее число нуклонов в ядре: протонов плюс нейтронов. Атомный номер Z равен только числу протонов. Электроны в массовое число не входят.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1933:uz:v1','chemistry',1933,'Atomic structure','Mass number',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Massa soni','Massa soni A yadroning jami nuklonlari soni, ya’ni protonlar va neytronlar yig‘indisidir. Atom raqami Z faqat protonlar soniga teng. Elektronlar massa soniga kiritilmaydi.',
 'approved','original_iclub',true,encode(digest(convert_to('Massa soni A yadroning jami nuklonlari soni, ya’ni protonlar va neytronlar yig‘indisidir. Atom raqami Z faqat protonlar soniga teng. Elektronlar massa soniga kiritilmaydi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1943:en:v1','chemistry',1943,'Atomic structure','Relative atomic mass (Ar)',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Relative atomic mass','Relative atomic mass Ar is the weighted mean mass of the atoms of an element compared with one twelfth of the mass of a carbon-12 atom. The weighting reflects the relative abundances of the isotopes. Ar is not the mass of one atom in grams and is not simply the mass number of one isotope.',
 'approved','original_iclub',true,encode(digest(convert_to('Relative atomic mass Ar is the weighted mean mass of the atoms of an element compared with one twelfth of the mass of a carbon-12 atom. The weighting reflects the relative abundances of the isotopes. Ar is not the mass of one atom in grams and is not simply the mass number of one isotope.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1943:ru:v1','chemistry',1943,'Atomic structure','Relative atomic mass (Ar)',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Относительная атомная масса Ar','Относительная атомная масса Ar — это средневзвешенная масса атомов элемента по сравнению с одной двенадцатой массы атома углерода-12. Вес каждого изотопа зависит от его относительной распространённости. Ar не является массой одного атома в граммах и не равна просто массовому числу одного изотопа.',
 'approved','original_iclub',true,encode(digest(convert_to('Относительная атомная масса Ar — это средневзвешенная масса атомов элемента по сравнению с одной двенадцатой массы атома углерода-12. Вес каждого изотопа зависит от его относительной распространённости. Ar не является массой одного атома в граммах и не равна просто массовому числу одного изотопа.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1943:uz:v1','chemistry',1943,'Atomic structure','Relative atomic mass (Ar)',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Nisbiy atom massasi Ar','Nisbiy atom massasi Ar element atomlarining uglerod-12 atomi massasining o‘n ikkidan bir qismiga nisbatan olingan og‘irliklangan o‘rtacha massasidir. Og‘irlik izotoplarning nisbiy tarqalishiga bog‘liq. Ar bitta atomning grammdagi massasi ham, bitta izotopning massa soni ham emas.',
 'approved','original_iclub',true,encode(digest(convert_to('Nisbiy atom massasi Ar element atomlarining uglerod-12 atomi massasining o‘n ikkidan bir qismiga nisbatan olingan og‘irliklangan o‘rtacha massasidir. Og‘irlik izotoplarning nisbiy tarqalishiga bog‘liq. Ar bitta atomning grammdagi massasi ham, bitta izotopning massa soni ham emas.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1944:en:v1','chemistry',1944,'Atomic structure','Electrons in Cl⁻',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Electron count in chloride ion','Chlorine has atomic number 17, so a neutral chlorine atom has 17 electrons. A 1- ion has gained one electron while its proton number stays unchanged. Therefore Cl- has 18 electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('Chlorine has atomic number 17, so a neutral chlorine atom has 17 electrons. A 1- ion has gained one electron while its proton number stays unchanged. Therefore Cl- has 18 electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1944:ru:v1','chemistry',1944,'Atomic structure','Electrons in Cl⁻',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Число электронов в ионе хлорида','Хлор имеет атомный номер 17, поэтому нейтральный атом хлора содержит 17 электронов. Ион с зарядом 1- присоединил один электрон, при этом число протонов не изменилось. Поэтому в Cl- находится 18 электронов.',
 'approved','original_iclub',true,encode(digest(convert_to('Хлор имеет атомный номер 17, поэтому нейтральный атом хлора содержит 17 электронов. Ион с зарядом 1- присоединил один электрон, при этом число протонов не изменилось. Поэтому в Cl- находится 18 электронов.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1944:uz:v1','chemistry',1944,'Atomic structure','Electrons in Cl⁻',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Xlorid ionidagi elektronlar soni','Xlorning atom raqami 17, shuning uchun neytral xlor atomida 17 elektron bor. 1- zaryadli ion bitta elektron qabul qilgan, protonlar soni esa o‘zgarmagan. Shuning uchun Cl- ionida 18 elektron bo‘ladi.',
 'approved','original_iclub',true,encode(digest(convert_to('Xlorning atom raqami 17, shuning uchun neytral xlor atomida 17 elektron bor. 1- zaryadli ion bitta elektron qabul qilgan, protonlar soni esa o‘zgarmagan. Shuning uchun Cl- ionida 18 elektron bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1954:en:v1','chemistry',1954,'Atomic structure','Neutrons in copper isotope',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Neutrons in an isotope','For an isotope, mass number A equals protons plus neutrons and atomic number Z equals protons. Therefore the number of neutrons is A - Z. For copper-63 with Z = 29, neutrons = 63 - 29 = 34.',
 'approved','original_iclub',true,encode(digest(convert_to('For an isotope, mass number A equals protons plus neutrons and atomic number Z equals protons. Therefore the number of neutrons is A - Z. For copper-63 with Z = 29, neutrons = 63 - 29 = 34.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1954:ru:v1','chemistry',1954,'Atomic structure','Neutrons in copper isotope',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Число нейтронов в изотопе','Для изотопа массовое число A равно сумме протонов и нейтронов, а атомный номер Z равен числу протонов. Поэтому число нейтронов равно A - Z. Для меди-63 при Z = 29: 63 - 29 = 34 нейтрона.',
 'approved','original_iclub',true,encode(digest(convert_to('Для изотопа массовое число A равно сумме протонов и нейтронов, а атомный номер Z равен числу протонов. Поэтому число нейтронов равно A - Z. Для меди-63 при Z = 29: 63 - 29 = 34 нейтрона.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1954:uz:v1','chemistry',1954,'Atomic structure','Neutrons in copper isotope',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Izotopdagi neytronlar soni','Izotopda massa soni A protonlar va neytronlar yig‘indisiga, atom raqami Z esa protonlar soniga teng. Shuning uchun neytronlar soni A - Z bilan topiladi. Mis-63 uchun Z = 29 bo‘lsa, 63 - 29 = 34 neytron.',
 'approved','original_iclub',true,encode(digest(convert_to('Izotopda massa soni A protonlar va neytronlar yig‘indisiga, atom raqami Z esa protonlar soniga teng. Shuning uchun neytronlar soni A - Z bilan topiladi. Mis-63 uchun Z = 29 bo‘lsa, 63 - 29 = 34 neytron.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1959:en:v1','chemistry',1959,'Atomic structure','Smallest relative mass of subatomic particles',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Relative masses of subatomic particles','Protons and neutrons each have relative mass close to 1. An electron has a much smaller relative mass, about 1/1836 of a proton. Therefore the electron contributes very little to total atomic mass compared with nucleons.',
 'approved','original_iclub',true,encode(digest(convert_to('Protons and neutrons each have relative mass close to 1. An electron has a much smaller relative mass, about 1/1836 of a proton. Therefore the electron contributes very little to total atomic mass compared with nucleons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1959:ru:v1','chemistry',1959,'Atomic structure','Smallest relative mass of subatomic particles',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Относительные массы субатомных частиц','Протон и нейтрон имеют относительную массу, близкую к 1. Масса электрона намного меньше — примерно 1/1836 массы протона. Поэтому вклад электронов в общую массу атома очень мал по сравнению с нуклонами.',
 'approved','original_iclub',true,encode(digest(convert_to('Протон и нейтрон имеют относительную массу, близкую к 1. Масса электрона намного меньше — примерно 1/1836 массы протона. Поэтому вклад электронов в общую массу атома очень мал по сравнению с нуклонами.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1959:uz:v1','chemistry',1959,'Atomic structure','Smallest relative mass of subatomic particles',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Subatom zarrachalarning nisbiy massalari','Proton va neytronning nisbiy massasi taxminan 1 ga teng. Elektronning nisbiy massasi ancha kichik, proton massasining taxminan 1/1836 qismiga teng. Shuning uchun elektronlarning atom umumiy massasiga hissasi nuklonlarga nisbatan juda kichik.',
 'approved','original_iclub',true,encode(digest(convert_to('Proton va neytronning nisbiy massasi taxminan 1 ga teng. Elektronning nisbiy massasi ancha kichik, proton massasining taxminan 1/1836 qismiga teng. Shuning uchun elektronlarning atom umumiy massasiga hissasi nuklonlarga nisbatan juda kichik.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1964:en:v1','chemistry',1964,'Atomic structure','Electrons in Fe³⁺',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Electron count in iron(III) ion','Iron has atomic number 26, so a neutral iron atom has 26 electrons. Forming Fe3+ removes three electrons while the number of protons remains 26. The ion therefore contains 23 electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('Iron has atomic number 26, so a neutral iron atom has 26 electrons. Forming Fe3+ removes three electrons while the number of protons remains 26. The ion therefore contains 23 electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1964:ru:v1','chemistry',1964,'Atomic structure','Electrons in Fe³⁺',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Число электронов в ионе Fe3+','Железо имеет атомный номер 26, поэтому нейтральный атом железа содержит 26 электронов. При образовании Fe3+ атом теряет три электрона, а число протонов остаётся равным 26. Поэтому ион содержит 23 электрона.',
 'approved','original_iclub',true,encode(digest(convert_to('Железо имеет атомный номер 26, поэтому нейтральный атом железа содержит 26 электронов. При образовании Fe3+ атом теряет три электрона, а число протонов остаётся равным 26. Поэтому ион содержит 23 электрона.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q1964:uz:v1','chemistry',1964,'Atomic structure','Electrons in Fe³⁺',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Fe3+ ionidagi elektronlar soni','Temirning atom raqami 26, shuning uchun neytral temir atomida 26 elektron bor. Fe3+ hosil bo‘lganda uchta elektron yo‘qotiladi, protonlar soni esa 26 bo‘lib qoladi. Demak ionda 23 elektron mavjud.',
 'approved','original_iclub',true,encode(digest(convert_to('Temirning atom raqami 26, shuning uchun neytral temir atomida 26 elektron bor. Fe3+ hosil bo‘lganda uchta elektron yo‘qotiladi, protonlar soni esa 26 bo‘lib qoladi. Demak ionda 23 elektron mavjud.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3041:en:v1','chemistry',3041,'Atomic structure','Rutherford scattering and the nucleus',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Rutherford scattering and the nucleus','In the alpha-scattering experiment, most alpha particles passed through the foil, showing that atoms are mostly empty space. A very small fraction were deflected through large angles, which showed that positive charge and almost all atomic mass are concentrated in a tiny, dense nucleus.',
 'approved','original_iclub',true,encode(digest(convert_to('In the alpha-scattering experiment, most alpha particles passed through the foil, showing that atoms are mostly empty space. A very small fraction were deflected through large angles, which showed that positive charge and almost all atomic mass are concentrated in a tiny, dense nucleus.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3041:ru:v1','chemistry',3041,'Atomic structure','Rutherford scattering and the nucleus',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Опыт Резерфорда и ядро','В опыте по рассеянию альфа-частиц большинство частиц проходило через фольгу, показывая, что атом в основном состоит из пустого пространства. Очень малая доля частиц отклонялась на большие углы, что указывает на концентрацию положительного заряда и почти всей массы атома в очень маленьком плотном ядре.',
 'approved','original_iclub',true,encode(digest(convert_to('В опыте по рассеянию альфа-частиц большинство частиц проходило через фольгу, показывая, что атом в основном состоит из пустого пространства. Очень малая доля частиц отклонялась на большие углы, что указывает на концентрацию положительного заряда и почти всей массы атома в очень маленьком плотном ядре.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3041:uz:v1','chemistry',3041,'Atomic structure','Rutherford scattering and the nucleus',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Rezerford tajribasi va yadro','Alfa-zarrachalar sochilishi tajribasida zarrachalarning aksariyati folgadan o‘tib ketgan, bu atomning katta qismi bo‘sh fazo ekanini ko‘rsatadi. Juda oz qismi katta burchakka og‘gan, bu musbat zaryad va atom massasining deyarli barchasi juda kichik va zich yadroda jamlanganini ko‘rsatadi.',
 'approved','original_iclub',true,encode(digest(convert_to('Alfa-zarrachalar sochilishi tajribasida zarrachalarning aksariyati folgadan o‘tib ketgan, bu atomning katta qismi bo‘sh fazo ekanini ko‘rsatadi. Juda oz qismi katta burchakka og‘gan, bu musbat zaryad va atom massasining deyarli barchasi juda kichik va zich yadroda jamlanganini ko‘rsatadi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3043:en:v1','chemistry',3043,'Atomic structure','Electron count in aluminium ion',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Electron count in aluminium ion','Aluminium has atomic number 13, so a neutral aluminium atom has 13 electrons. An Al3+ ion forms by losing three electrons. The ion therefore contains 13 - 3 = 10 electrons.',
 'approved','original_iclub',true,encode(digest(convert_to('Aluminium has atomic number 13, so a neutral aluminium atom has 13 electrons. An Al3+ ion forms by losing three electrons. The ion therefore contains 13 - 3 = 10 electrons.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3043:ru:v1','chemistry',3043,'Atomic structure','Electron count in aluminium ion',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Число электронов в ионе алюминия','Алюминий имеет атомный номер 13, поэтому нейтральный атом алюминия содержит 13 электронов. Ион Al3+ образуется при потере трёх электронов. Поэтому в ионе находится 13 - 3 = 10 электронов.',
 'approved','original_iclub',true,encode(digest(convert_to('Алюминий имеет атомный номер 13, поэтому нейтральный атом алюминия содержит 13 электронов. Ион Al3+ образуется при потере трёх электронов. Поэтому в ионе находится 13 - 3 = 10 электронов.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3043:uz:v1','chemistry',3043,'Atomic structure','Electron count in aluminium ion',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Alyuminiy ionidagi elektronlar soni','Alyuminiyning atom raqami 13, shuning uchun neytral alyuminiy atomida 13 elektron bor. Al3+ ion uchta elektron yo‘qotish orqali hosil bo‘ladi. Shuning uchun ionda 13 - 3 = 10 elektron mavjud.',
 'approved','original_iclub',true,encode(digest(convert_to('Alyuminiyning atom raqami 13, shuning uchun neytral alyuminiy atomida 13 elektron bor. Al3+ ion uchta elektron yo‘qotish orqali hosil bo‘ladi. Shuning uchun ionda 13 - 3 = 10 elektron mavjud.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3044:en:v1','chemistry',3044,'Atomic structure','Mass and charge in the nucleus',
 'answer_explanation','en','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Mass and charge in the nucleus','The nucleus contains protons and neutrons. Protons give the nucleus its positive charge, and protons plus neutrons account for almost all the mass of an atom. The nucleus occupies only a tiny fraction of the atom’s volume.',
 'approved','original_iclub',true,encode(digest(convert_to('The nucleus contains protons and neutrons. Protons give the nucleus its positive charge, and protons plus neutrons account for almost all the mass of an atom. The nucleus occupies only a tiny fraction of the atom’s volume.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3044:ru:v1','chemistry',3044,'Atomic structure','Mass and charge in the nucleus',
 'answer_explanation','ru','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Масса и заряд ядра','Ядро содержит протоны и нейтроны. Протоны придают ядру положительный заряд, а протоны вместе с нейтронами составляют почти всю массу атома. Само ядро занимает лишь очень малую часть объёма атома.',
 'approved','original_iclub',true,encode(digest(convert_to('Ядро содержит протоны и нейтроны. Протоны придают ядру положительный заряд, а протоны вместе с нейтронами составляют почти всю массу атома. Само ядро занимает лишь очень малую часть объёма атома.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:chemistry:p1:q3044:uz:v1','chemistry',3044,'Atomic structure','Mass and charge in the nucleus',
 'answer_explanation','uz','iclub_practice_ai_chemistry_p1_atomic_structure_precise_v1_2026_09_25','Yadroning massasi va zaryadi','Yadro proton va neytronlardan iborat. Protonlar yadroga musbat zaryad beradi, proton va neytronlar esa atom massasining deyarli barchasini tashkil qiladi. Yadro atom hajmining juda kichik qismini egallaydi.',
 'approved','original_iclub',true,encode(digest(convert_to('Yadro proton va neytronlardan iborat. Protonlar yadroga musbat zaryad beradi, proton va neytronlar esa atom massasining deyarli barchasini tashkil qiladi. Yadro atom hajmining juda kichik qismini egallaydi.','UTF8'),'sha256'),'hex'),now(),now())
on conflict(source_card_key) do update
set subject_key=excluded.subject_key,
    question_id=excluded.question_id,
    topic=excluded.topic,
    subtopic=excluded.subtopic,
    card_type=excluded.card_type,
    locale=excluded.locale,
    source_version=excluded.source_version,
    title=excluded.title,
    body_text=excluded.body_text,
    approval_status=excluded.approval_status,
    rights_status=excluded.rights_status,
    is_runtime_allowed=excluded.is_runtime_allowed,
    content_hash=excluded.content_hash,
    approved_at=coalesce(private.practice_ai_source_cards.approved_at,excluded.approved_at),
    updated_at=now();
