-- P1-02 P1 AW21-24 Integration applications: INT-04/05.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw21_24_integration_apps_v1','P1','P1 AW21-24 Integration applications','draft',
       'Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv
where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_apps_v1' and component_code='P1' and status='draft'),
src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-INT-04','P1INT04-D01','diagnostic','medium','Find the area between y=x and y=x^2 for 0<=x<=1.','Найдите площадь между y=x и y=x^2 при 0<=x<=1.','0<=x<=1 da y=x va y=x^2 orasidagi yuzani toping.','["1/6","1/3","1/2","2/3"]','["1/6","1/3","1/2","2/3"]','["1/6","1/3","1/2","2/3"]','A','On 0<=x<=1, x is above x^2. Area = integral_0^1 (x-x^2) dx = 1/2-1/3 = 1/6.','На 0<=x<=1 график y=x выше y=x^2. Площадь = ∫(x-x^2)dx = 1/6.','0<=x<=1 da y=x yuqorida. Yuzasi ∫(x-x^2)dx = 1/6.',45),
('P1-INT-04','P1INT04-L01','learning','easy','Find the area under y=2x from x=0 to x=3.','Найдите площадь под y=2x от x=0 до x=3.','y=2x ostidagi yuzani x=0 dan x=3 gacha toping.','["9","6","18","3"]','["9","6","18","3"]','["9","6","18","3"]','A','Area = integral_0^3 2x dx = [x^2]_0^3 = 9.','Площадь = ∫_0^3 2x dx = 9.','Yuza = ∫_0^3 2x dx = 9.',30),
('P1-INT-04','P1INT04-L02','learning','medium','Find the area between y=4 and y=x^2 from x=-2 to x=2.','Найдите площадь между y=4 и y=x^2 от x=-2 до x=2.','x=-2 dan x=2 gacha y=4 va y=x^2 orasidagi yuzani toping.','["32/3","16/3","8","40/3"]','["32/3","16/3","8","40/3"]','["32/3","16/3","8","40/3"]','A','The upper curve is y=4. Area = integral_-2^2 (4-x^2) dx = 32/3.','Верхняя кривая y=4. Площадь = ∫_-2^2(4-x^2)dx = 32/3.','Yuqori chiziq y=4. Yuza = ∫_-2^2(4-x^2)dx = 32/3.',45),
('P1-INT-04','P1INT04-L03','learning','medium','Find the area between y=x^2 and the x-axis from x=-1 to x=2.','Найдите площадь между y=x^2 и осью x от x=-1 до x=2.','x=-1 dan x=2 gacha y=x^2 va x-o‘qi orasidagi yuzani toping.','["3","7/3","9/2","1"]','["3","7/3","9/2","1"]','["3","7/3","9/2","1"]','A','x^2 is non-negative, so area = integral_-1^2 x^2 dx = [x^3/3]_-1^2 = 3.','x^2 неотрицательна, поэтому площадь = ∫_-1^2 x^2 dx = 3.','x^2 manfiy emas, shuning uchun yuza = ∫_-1^2 x^2 dx = 3.',40),
('P1-INT-04','P1INT04-R01','retest','easy','Find the area under y=3x^2 from x=0 to x=2.','Найдите площадь под y=3x^2 от x=0 до x=2.','x=0 dan x=2 gacha y=3x^2 ostidagi yuzani toping.','["8","12","6","4"]','["8","12","6","4"]','["8","12","6","4"]','A','Area = integral_0^2 3x^2 dx = [x^3]_0^2 = 8.','Площадь = 8.','Yuza = 8.',25),
('P1-INT-04','P1INT04-R02','retest','medium','The curves y=x+2 and y=x^2 intersect at x=-1 and x=2. Find the enclosed area.','Кривые y=x+2 и y=x^2 пересекаются при x=-1 и x=2. Найдите заключённую между ними площадь.','y=x+2 va y=x^2 x=-1 va x=2 da kesishadi. Ular orasidagi yuzani toping.','["9/2","3","5","7/2"]','["9/2","3","5","7/2"]','["9/2","3","5","7/2"]','A','Between the intersections, x+2 is above x^2. Area = integral_-1^2 (x+2-x^2) dx = 9/2.','Между точками пересечения x+2 выше x^2. Площадь = 9/2.','Kesishishlar orasida x+2 yuqorida. Yuza = 9/2.',45),
('P1-INT-04','P1INT04-M01','mixed','medium','Find the total area between y=x and the x-axis from x=-2 to x=2.','Найдите полную площадь между y=x и осью x от x=-2 до x=2.','x=-2 dan x=2 gacha y=x va x-o‘qi orasidagi umumiy yuzani toping.','["4","0","2","8"]','["4","0","2","8"]','["4","0","2","8"]','A','Signed integral is zero, but area must be positive. Split at x=0: integral_-2^0 (-x)dx + integral_0^2 x dx = 4.','Знаковый интеграл равен 0, но площадь положительна. Разбейте при x=0: итог 4.','Ishorali integral 0, lekin yuza musbat. x=0 da bo‘ling: natija 4.',45),

('P1-INT-05','P1INT05-D01','diagnostic','medium','The region under y=x for 0<=x<=2 is rotated about the x-axis. Find the volume.','Область под y=x при 0<=x<=2 вращается вокруг оси x. Найдите объём.','0<=x<=2 da y=x ostidagi soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["8pi/3","4pi","4pi/3","8pi"]','["8pi/3","4pi","4pi/3","8pi"]','["8pi/3","4pi","4pi/3","8pi"]','A','For rotation about the x-axis, V=pi integral y^2 dx = pi integral_0^2 x^2 dx = 8pi/3.','При вращении вокруг оси x: V=pi∫y^2dx = 8pi/3.','x-o‘qi atrofida V=pi∫y^2dx = 8pi/3.',45),
('P1-INT-05','P1INT05-L01','learning','easy','The region y=2, 0<=x<=3, is rotated about the x-axis. Find the volume.','Область y=2, 0<=x<=3, вращается вокруг оси x. Найдите объём.','y=2, 0<=x<=3 soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["12pi","6pi","4pi","18pi"]','["12pi","6pi","4pi","18pi"]','["12pi","6pi","4pi","18pi"]','A','V=pi integral_0^3 2^2 dx = 12pi.','V=pi∫_0^3 4dx = 12pi.','V=pi∫_0^3 4dx = 12pi.',30),
('P1-INT-05','P1INT05-L02','learning','medium','The region under y=sqrt(x) for 0<=x<=4 is rotated about the x-axis. Find the volume.','Область под y=sqrt(x) при 0<=x<=4 вращается вокруг оси x. Найдите объём.','0<=x<=4 da y=sqrt(x) ostidagi soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["8pi","16pi/3","4pi","32pi/3"]','["8pi","16pi/3","4pi","32pi/3"]','["8pi","16pi/3","4pi","32pi/3"]','A','Since y^2=x, V=pi integral_0^4 x dx = 8pi.','Так как y^2=x, V=pi∫_0^4 xdx = 8pi.','y^2=x, shuning uchun V=pi∫_0^4 xdx = 8pi.',40),
('P1-INT-05','P1INT05-L03','learning','medium','The region under y=x^2 for 0<=x<=1 is rotated about the x-axis. Find the volume.','Область под y=x^2 при 0<=x<=1 вращается вокруг оси x. Найдите объём.','0<=x<=1 da y=x^2 ostidagi soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["pi/5","pi/3","pi","2pi/5"]','["pi/5","pi/3","pi","2pi/5"]','["pi/5","pi/3","pi","2pi/5"]','A','V=pi integral_0^1 (x^2)^2 dx = pi integral_0^1 x^4 dx = pi/5.','V=pi∫_0^1 x^4dx = pi/5.','V=pi∫_0^1 x^4dx = pi/5.',40),
('P1-INT-05','P1INT05-R01','retest','easy','The region y=3, 0<=x<=2, is rotated about the x-axis. Find the volume.','Область y=3, 0<=x<=2, вращается вокруг оси x. Найдите объём.','y=3, 0<=x<=2 soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["18pi","9pi","6pi","12pi"]','["18pi","9pi","6pi","12pi"]','["18pi","9pi","6pi","12pi"]','A','V=pi integral_0^2 9 dx = 18pi.','V=18pi.','V=18pi.',25),
('P1-INT-05','P1INT05-R02','retest','medium','The region under y=x+1 for 0<=x<=1 is rotated about the x-axis. Find the volume.','Область под y=x+1 при 0<=x<=1 вращается вокруг оси x. Найдите объём.','0<=x<=1 da y=x+1 ostidagi soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["7pi/3","3pi","4pi/3","8pi/3"]','["7pi/3","3pi","4pi/3","8pi/3"]','["7pi/3","3pi","4pi/3","8pi/3"]','A','V=pi integral_0^1 (x+1)^2 dx = pi[(x+1)^3/3]_0^1 = 7pi/3.','V=pi∫_0^1(x+1)^2dx = 7pi/3.','V=pi∫_0^1(x+1)^2dx = 7pi/3.',40),
('P1-INT-05','P1INT05-M01','mixed','medium','The triangular region under y=2x for 0<=x<=1 is rotated about the x-axis. Find the volume.','Треугольная область под y=2x при 0<=x<=1 вращается вокруг оси x. Найдите объём.','0<=x<=1 da y=2x ostidagi uchburchak soha x-o‘qi atrofida aylantiriladi. Hajmni toping.','["4pi/3","2pi/3","pi","2pi"]','["4pi/3","2pi/3","pi","2pi"]','["4pi/3","2pi/3","pi","2pi"]','A','V=pi integral_0^1 (2x)^2 dx = 4pi/3.','V=4pi/3.','V=4pi/3.',40)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Integration Applications',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw21_24_integration_apps_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw21_24_integration_apps_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_apps_v1' and status='draft'), keys(skill,k,role) as (values
('P1-INT-04','P1INT04-D01','diagnostic'),('P1-INT-04','P1INT04-L01','learning'),('P1-INT-04','P1INT04-L02','learning'),('P1-INT-04','P1INT04-L03','learning'),('P1-INT-04','P1INT04-R01','retest'),('P1-INT-04','P1INT04-R02','retest'),('P1-INT-04','P1INT04-M01','mixed'),
('P1-INT-05','P1INT05-D01','diagnostic'),('P1-INT-05','P1INT05-L01','learning'),('P1-INT-05','P1INT05-L02','learning'),('P1-INT-05','P1INT05-L03','learning'),('P1-INT-05','P1INT05-R01','retest'),('P1-INT-05','P1INT05-R02','retest'),('P1-INT-05','P1INT05-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw21_24_integration_apps_v1 from canonical integration-application skill intent.','Cambridge 9709 2026-2027 v4; P1 1.8 Integration','Complete Pure Mathematics 1; Integration applications (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw21_24_integration_apps_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw21_24_integration_apps_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1INT04-D01','B','integrates_lower_curve_only','method','The area between two curves requires upper minus lower. Integrating x^2 alone does not measure the gap.','Площадь между кривыми требует верхняя минус нижняя. Интеграл только x^2 не измеряет промежуток.','Ikki chiziq orasidagi yuza yuqori minus pastki funksiyani talab qiladi.','Identify which curve is above before forming the integrand.','Сначала определите верхнюю кривую.','Avval qaysi chiziq yuqorida ekanini aniqlang.'),
('P1INT04-D01','C','integrates_upper_curve_only','method','Integral of x alone gives area under y=x, not the area between y=x and y=x^2.','Интеграл от x даёт площадь под y=x, а не между двумя кривыми.','x integrali y=x ostidagi yuzani beradi, ikki chiziq orasidagini emas.','Use upper minus lower on the stated interval.','Используйте верхняя минус нижняя.','Yuqori minus pastki funksiyani ishlating.'),
('P1INT04-D01','D','subtracts_integrals_incorrectly','method','Compute the exact antiderivative difference: 1/2-1/3=1/6, not 2/3.','Точная разность 1/2-1/3=1/6, не 2/3.','Aniq ayirma 1/2-1/3=1/6.','Keep a common denominator when subtracting fractions.','Приведите дроби к общему знаменателю.','Kasrlarni umumiy maxrajga keltiring.'),
('P1INT05-D01','B','forgets_square','concept','For rotation about the x-axis, each cross-section has area pi y^2, not pi y.','При вращении вокруг оси x площадь сечения равна pi y^2, а не pi y.','x-o‘qi atrofida kesim yuzi pi y^2, pi y emas.','Start from disk area pi r^2 with r=y.','Начните с площади диска pi r^2, где r=y.','Disk yuzi pi r^2 dan boshlang, r=y.'),
('P1INT05-D01','C','drops_pi_or_limit_factor','method','The integral of x^2 from 0 to 2 is 8/3; multiplying by pi gives 8pi/3.','Интеграл x^2 от 0 до 2 равен 8/3; затем умножьте на pi.','x^2 ning 0 dan 2 gacha integrali 8/3; keyin pi ga ko‘paytiring.','Write V=pi integral y^2 dx before integrating.','Сначала запишите V=pi∫y^2dx.','Avval V=pi∫y^2dx ni yozing.'),
('P1INT05-D01','D','uses_endpoint_rectangle','concept','8pi is not obtained by summing varying disk areas; the radius changes continuously from 0 to 2.','8pi не учитывает непрерывное изменение радиуса от 0 до 2.','Radius 0 dan 2 gacha uzluksiz o‘zgaradi; bitta oxirgi disk yetarli emas.','Integrate cross-sectional area across x.','Интегрируйте площадь сечения по x.','Kesim yuzini x bo‘yicha integrallang.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_apps_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1INT04-W01','P1-INT-04','Find the enclosed area between y=2x and y=x^2. Then find the total area between y=x^2-1 and the x-axis for -2<=x<=2, splitting the region wherever the sign changes.','Найдите площадь между y=2x и y=x^2. Затем найдите полную площадь между y=x^2-1 и осью x при -2<=x<=2, разбивая область там, где меняется знак.','y=2x va y=x^2 orasidagi yuzani toping. So‘ng -2<=x<=2 da y=x^2-1 va x-o‘qi orasidagi umumiy yuzani ishora o‘zgaradigan joylarda bo‘lib toping.','{"max_marks":11,"criteria":[{"id":"intersections","marks":2,"rule":"Gets x=0 and x=2 for 2x=x^2."},{"id":"first_area","marks":3,"rule":"Gets integral_0^2(2x-x^2)dx=4/3."},{"id":"split_points","marks":2,"rule":"Identifies x=-1 and x=1 for x^2-1=0."},{"id":"piecewise_area","marks":3,"rule":"Uses absolute/piecewise integrals and gets total area 4."},{"id":"communication","marks":1,"rule":"States why sign changes require splitting for total area."}]}','For total geometric area, integrate the positive gap; if the graph crosses, split before integrating.','Для геометрической площади интегрируйте положительный разрыв; при пересечении оси разбивайте область.','Geometrik yuza uchun musbat farqni integrallang; grafik o‘qni kessa, oldin bo‘ling.'),
('P1INT05-W01','P1-INT-05','The region under y=2x-x^2 for 0<=x<=2 is rotated about the x-axis. Form the correct volume integral, expand the squared radius, evaluate it exactly, and state the final volume.','Область под y=2x-x^2 при 0<=x<=2 вращается вокруг оси x. Составьте интеграл объёма, раскройте квадрат радиуса, вычислите точно и укажите итоговый объём.','0<=x<=2 da y=2x-x^2 ostidagi soha x-o‘qi atrofida aylantiriladi. Hajm integralini tuzing, radius kvadratini oching, aniq hisoblang va yakuniy hajmni yozing.','{"max_marks":10,"criteria":[{"id":"setup","marks":3,"rule":"Uses V=pi integral_0^2(2x-x^2)^2 dx."},{"id":"expand","marks":2,"rule":"Gets x^4-4x^3+4x^2."},{"id":"integrate","marks":3,"rule":"Evaluates the polynomial integral as 16/15."},{"id":"volume","marks":2,"rule":"States V=16pi/15 cubic units."}]}','Square the whole radius function before integrating; do not integrate y first.','Сначала возведите всю функцию радиуса в квадрат; не интегрируйте y до этого.','Avval radius funksiyasini to‘liq kvadratga ko‘taring; y ni oldin integrallamang.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_apps_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw21_int_apps_diagnostic','diagnostic','P1 AW21-24 Integration applications diagnostic','Диагностика P1 AW21–24: применения интегрирования','P1 AW21–24 integrallash qo‘llanishi diagnostikasi'),
('p1_int04_learning','learning','Areas by integration learning','Площади интегрированием: обучение','Integral bilan yuza: o‘rganish'),
('p1_int05_learning','learning','Volumes of revolution learning','Объёмы вращения: обучение','Aylanish hajmi: o‘rganish'),
('p1_int04_retest','retest','INT-04 delayed retest','INT-04 отложенный ретест','INT-04 kechiktirilgan retest'),
('p1_int05_retest','retest','INT-05 delayed retest','INT-05 отложенный ретест','INT-05 kechiktirilgan retest'),
('p1_aw21_int_apps_mixed','mixed','P1 AW21-24 Integration applications mixed transfer','P1 AW21–24: смешанный перенос применений интегрирования','P1 AW21–24 integrallash qo‘llanishi mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_apps_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw21_int_apps_diagnostic',1,'P1INT04-D01',null,'P1-INT-04','diagnostic',true),('p1_aw21_int_apps_diagnostic',2,'P1INT05-D01',null,'P1-INT-05','diagnostic',true),
('p1_int04_learning',1,'P1INT04-L01',null,'P1-INT-04','learning',false),('p1_int04_learning',2,'P1INT04-L02',null,'P1-INT-04','learning',false),('p1_int04_learning',3,'P1INT04-L03',null,'P1-INT-04','learning',false),('p1_int04_learning',4,null,'P1INT04-W01','P1-INT-04','written',false),
('p1_int05_learning',1,'P1INT05-L01',null,'P1-INT-05','learning',false),('p1_int05_learning',2,'P1INT05-L02',null,'P1-INT-05','learning',false),('p1_int05_learning',3,'P1INT05-L03',null,'P1-INT-05','learning',false),('p1_int05_learning',4,null,'P1INT05-W01','P1-INT-05','written',false),
('p1_int04_retest',1,'P1INT04-R01',null,'P1-INT-04','retest',true),('p1_int05_retest',1,'P1INT05-R01',null,'P1-INT-05','retest',true),
('p1_aw21_int_apps_mixed',1,'P1INT04-M01',null,'P1-INT-04','mixed',true),('p1_aw21_int_apps_mixed',2,'P1INT05-M01',null,'P1-INT-05','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_integration_apps_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw21_24_integration_apps_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_integration_apps_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw21_24_integration_apps_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw21_24_integration_apps_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw21_24_integration_apps_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
 select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
 foreach v_skill in array array['P1-INT-04','P1-INT-05'] loop
   if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 integration application skill not ready %',v_skill; end if;
 end loop;
 if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw21_24_integration_apps_v1:%' and is_active) then raise exception 'P1 integration applications legacy activation residue'; end if;
 if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P1 integration applications publication escaped fail-closed'; end if;
 if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 integration applications active entitlement residue'; end if;
end $$;
commit;
