-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 3; rows 29-42 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(29,'P1','1.6 Series','P1-SER-01','Раскрывать (a + b x)^n для positive integer n и находить заданные terms/coefficients.','PR-ALG-03; PR-CNT-01','Complete Pure Mathematics 1, Ch6 Binomial expansion','pp. 109–116','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','P1 positive-integer binomial покрыт; rational/approximation expansion из Tour Map исключён как post-P1.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(30,'P1','1.6 Series','P1-SER-02','Распознавать arithmetic и geometric progressions по структуре terms.','PR-ALG-01; PR-ALG-03','Complete Pure Mathematics 1, Ch7 Series','pp. 120–133','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E3 Core Coverage II (декабрь–январь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(31,'P1','1.6 Series','P1-SER-03','Находить nth term и finite sum arithmetic progression, включая inverse problems.','P1-SER-02; PR-EQN-01','Complete Pure Mathematics 1, Ch7 Series','pp. 120–133','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(32,'P1','1.6 Series','P1-SER-04','Находить nth term и finite sum geometric progression, включая inverse problems.','P1-SER-02; PR-ALG-02','Complete Pure Mathematics 1, Ch7 Series','pp. 120–133','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Geometric progression/convergence в Math Tour Map отражены неполно; учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(33,'P1','1.6 Series','P1-SER-05','Проверять convergence geometric series и вычислять sum to infinity.','P1-SER-04; P1-QUA-04','Complete Pure Mathematics 1, Ch7 Series','pp. 120–133','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E3 Core Coverage II (декабрь–январь)','Geometric progression/convergence в Math Tour Map отражены неполно; учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(34,'P1','1.7 Differentiation','P1-DIF-01','Интерпретировать derivative как gradient/rate of change и использовать limit definition в простом случае.','P1-COO-01; PR-ALG-03','Complete Pure Mathematics 1, Ch8 Differentiation','pp. 138–153','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E3 Core Coverage II (декабрь–январь)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(35,'P1','1.7 Differentiation','P1-DIF-02','Дифференцировать powers с rational exponent и linear combinations.','P1-DIF-01; PR-ALG-02','Complete Pure Mathematics 1, Ch8 Differentiation','pp. 138–153','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(36,'P1','1.7 Differentiation','P1-DIF-03','Применять chain rule к функциям вида (a x + b)^n.','P1-DIF-02; PR-ALG-03','Complete Pure Mathematics 1, Ch8 Differentiation','pp. 138–153','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(37,'P1','1.7 Differentiation','P1-DIF-04','Находить equations of tangent и normal в заданной точке.','P1-DIF-02; P1-COO-01; P1-COO-03','Complete Pure Mathematics 1, Ch8–9 Differentiation','pp. 138–167','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(38,'P1','1.7 Differentiation','P1-DIF-05','Определять increasing/decreasing intervals по знаку derivative.','P1-DIF-02; P1-QUA-04','Complete Pure Mathematics 1, Ch9 Further differentiation','pp. 156–167','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(39,'P1','1.7 Differentiation','P1-DIF-06','Решать rate-of-change и connected-rates problems с корректными units/signs.','P1-DIF-03; P1-CIR-02; P1-CIR-03','Complete Pure Mathematics 1, Ch9 Further differentiation','pp. 156–167','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(40,'P1','1.7 Differentiation','P1-DIF-07','Находить stationary points, определять их nature и использовать для sketch/optimisation.','P1-DIF-02; P1-DIF-05; P1-FUN-02','Complete Pure Mathematics 1, Ch9 Further differentiation','pp. 156–167','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(41,'P1','1.8 Integration','P1-INT-01','Интегрировать powers и expressions (a x + b)^n как antiderivatives.','P1-DIF-02; P1-DIF-03; PR-ALG-02','Complete Pure Mathematics 1, Ch10 Integration','pp. 173–200','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(42,'P1','1.8 Integration','P1-INT-02','Использовать constant of integration и point/boundary condition для восстановления curve.','P1-INT-01; PR-EQN-01','Complete Pure Mathematics 1, Ch10 Integration','pp. 173–200','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E4 Complete Coverage (январь–февраль)','Math Tour Map v1 не покрывает эту обязательную область P1. Учебник и официальный syllabus покрывают.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
