-- P1-02 P1 AW17-20 Series pack: SER-03/04/05.
-- Original iClub-authored content only; governed publication; legacy questions stay draft + inactive.
begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw17_20_series_v1','P1','P1 AW17-20 Series: AP, GP, sum to infinity','draft',
'Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_series_v1' and component_code='P1' and status='draft'),
src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-SER-03','P1SER03-D01','diagnostic','medium','An arithmetic progression has first term 5 and common difference 3. Find the sum of the first 10 terms.','Арифметическая прогрессия имеет первый член 5 и разность 3. Найдите сумму первых 10 членов.','Arifmetik progressiyaning birinchi hadi 5, ayirmasi 3. Dastlabki 10 had yig‘indisini toping.','["185","320","95","370"]','["185","320","95","370"]','["185","320","95","370"]','A','S10=10/2[2(5)+9(3)]=5(37)=185.','S10=10/2[2(5)+9(3)]=185.','S10=10/2[2(5)+9(3)]=185.',60),
('P1-SER-03','P1SER03-L01','learning','easy','An arithmetic progression has first term 7 and common difference 4. Find the 12th term.','У арифметической прогрессии первый член 7 и разность 4. Найдите 12-й член.','Arifmetik progressiyaning birinchi hadi 7, ayirmasi 4. 12-hadni toping.','["51","55","48","44"]','["51","55","48","44"]','["51","55","48","44"]','A','u12=7+11(4)=51.','u12=7+11(4)=51.','u12=7+11(4)=51.',40),
('P1-SER-03','P1SER03-L02','learning','medium','Find the sum of the first 20 terms of the arithmetic progression 2,5,8,...','Найдите сумму первых 20 членов арифметической прогрессии 2,5,8,...','2,5,8,... arifmetik progressiyaning dastlabki 20 hadi yig‘indisini toping.','["610","590","1180","61"]','["610","590","1180","61"]','["610","590","1180","61"]','A','S20=20/2[2(2)+19(3)]=10(61)=610.','S20=20/2[2(2)+19(3)]=610.','S20=20/2[2(2)+19(3)]=610.',50),
('P1-SER-03','P1SER03-L03','learning','medium','In an arithmetic progression, the first term is 3 and the 8th term is 31. Find the common difference.','В арифметической прогрессии первый член 3, а 8-й член 31. Найдите разность.','Arifmetik progressiyada birinchi had 3, 8-had 31. Ayirmani toping.','["4","3.5","7","28"]','["4","3,5","7","28"]','["4","3.5","7","28"]','A','31=3+7d, so d=4.','31=3+7d, поэтому d=4.','31=3+7d, demak d=4.',50),
('P1-SER-03','P1SER03-R01','retest','easy','Find S15 for an arithmetic progression with a=4 and d=2.','Найдите S15 для арифметической прогрессии с a=4 и d=2.','a=4 va d=2 bo‘lgan arifmetik progressiya uchun S15 ni toping.','["270","255","480","135"]','["270","255","480","135"]','["270","255","480","135"]','A','S15=15/2[8+28]=270.','S15=15/2[8+28]=270.','S15=15/2[8+28]=270.',40),
('P1-SER-03','P1SER03-R02','retest','medium','The 12th term of an arithmetic progression is 47 and d=4. Find the first term.','12-й член арифметической прогрессии равен 47, d=4. Найдите первый член.','Arifmetik progressiyaning 12-hadi 47, d=4. Birinchi hadni toping.','["3","7","43","−1"]','["3","7","43","−1"]','["3","7","43","−1"]','A','47=a+11(4), so a=3.','47=a+11(4), поэтому a=3.','47=a+11(4), demak a=3.',45),
('P1-SER-03','P1SER03-M01','mixed','hard','For an arithmetic progression, S_n=3n²+2n. Find the nth term u_n.','Для арифметической прогрессии S_n=3n²+2n. Найдите n-й член u_n.','Arifmetik progressiya uchun S_n=3n²+2n. n-had u_n ni toping.','["6n−1","6n+1","3n+2","3n²−2n"]','["6n−1","6n+1","3n+2","3n²−2n"]','["6n−1","6n+1","3n+2","3n²−2n"]','A','u_n=S_n−S_(n−1)=3n²+2n−[3(n−1)²+2(n−1)]=6n−1.','u_n=S_n−S_(n−1)=6n−1.','u_n=S_n−S_(n−1)=6n−1.',75),

('P1-SER-04','P1SER04-D01','diagnostic','medium','A geometric progression has first term 3 and common ratio 2. Find the sum of the first 6 terms.','Геометрическая прогрессия имеет первый член 3 и знаменатель 2. Найдите сумму первых 6 членов.','Geometrik progressiyaning birinchi hadi 3, maxraji 2. Dastlabki 6 had yig‘indisini toping.','["189","192","96","63"]','["189","192","96","63"]','["189","192","96","63"]','A','S6=3(2^6−1)/(2−1)=3(63)=189.','S6=3(2^6−1)/(2−1)=189.','S6=3(2^6−1)/(2−1)=189.',60),
('P1-SER-04','P1SER04-L01','learning','easy','A geometric progression has a=5 and r=1/2. Find the 8th term.','У геометрической прогрессии a=5 и r=1/2. Найдите 8-й член.','Geometrik progressiyada a=5 va r=1/2. 8-hadni toping.','["5/128","5/64","40","1/128"]','["5/128","5/64","40","1/128"]','["5/128","5/64","40","1/128"]','A','u8=5(1/2)^7=5/128.','u8=5(1/2)^7=5/128.','u8=5(1/2)^7=5/128.',40),
('P1-SER-04','P1SER04-L02','learning','medium','Find the sum of the first 5 terms of a geometric progression with a=4 and r=3.','Найдите сумму первых 5 членов геометрической прогрессии с a=4 и r=3.','a=4 va r=3 bo‘lgan geometrik progressiyaning dastlabki 5 hadi yig‘indisini toping.','["484","488","324","242"]','["484","488","324","242"]','["484","488","324","242"]','A','S5=4(3^5−1)/(3−1)=4(242)/2=484.','S5=4(3^5−1)/(3−1)=484.','S5=4(3^5−1)/(3−1)=484.',55),
('P1-SER-04','P1SER04-L03','learning','medium','A geometric progression has first term 2 and fourth term 54. Given r>0, find r.','У геометрической прогрессии первый член 2, а четвёртый 54. Если r>0, найдите r.','Geometrik progressiyaning birinchi hadi 2, to‘rtinchi hadi 54. r>0 bo‘lsa, r ni toping.','["3","9","27","2"]','["3","9","27","2"]','["3","9","27","2"]','A','54=2r³, so r³=27 and r=3.','54=2r³, поэтому r=3.','54=2r³, demak r=3.',50),
('P1-SER-04','P1SER04-R01','retest','easy','Find S4 for a geometric progression with a=6 and r=2.','Найдите S4 для геометрической прогрессии с a=6 и r=2.','a=6 va r=2 bo‘lgan geometrik progressiya uchun S4 ni toping.','["90","96","48","45"]','["90","96","48","45"]','["90","96","48","45"]','A','S4=6(2^4−1)=90.','S4=6(2^4−1)=90.','S4=6(2^4−1)=90.',40),
('P1-SER-04','P1SER04-R02','retest','medium','The third term of a geometric progression is 20 and r=2. Find the first term.','Третий член геометрической прогрессии равен 20, r=2. Найдите первый член.','Geometrik progressiyaning uchinchi hadi 20, r=2. Birinchi hadni toping.','["5","10","4","80"]','["5","10","4","80"]','["5","10","4","80"]','A','20=ar²=4a, so a=5.','20=4a, поэтому a=5.','20=4a, demak a=5.',45),
('P1-SER-04','P1SER04-M01','mixed','medium','A geometric progression has a=2, r=3 and S_n=242. Find n.','Геометрическая прогрессия имеет a=2, r=3 и S_n=242. Найдите n.','Geometrik progressiyada a=2, r=3 va S_n=242. n ni toping.','["5","4","6","3"]','["5","4","6","3"]','["5","4","6","3"]','A','242=2(3^n−1)/(3−1)=3^n−1, so 3^n=243 and n=5.','242=3^n−1, поэтому n=5.','242=3^n−1, demak n=5.',65),

('P1-SER-05','P1SER05-D01','diagnostic','medium','A geometric series has first term 12 and common ratio 1/2. Find its sum to infinity.','Геометрический ряд имеет первый член 12 и знаменатель 1/2. Найдите сумму до бесконечности.','Geometrik qatorning birinchi hadi 12, maxraji 1/2. Cheksiz yig‘indini toping.','["24","18","6","Does not converge"]','["24","18","6","Не сходится"]','["24","18","6","Yaqinlashmaydi"]','A','Since |r|=1/2<1, S∞=12/(1−1/2)=24.','Так как |r|=1/2<1, S∞=24.','|r|=1/2<1 bo‘lgani uchun S∞=24.',50),
('P1-SER-05','P1SER05-L01','learning','easy','For which condition does a geometric series have a finite sum to infinity?','При каком условии геометрический ряд имеет конечную сумму до бесконечности?','Qaysi shartda geometrik qatorning cheksiz yig‘indisi chekli bo‘ladi?','["|r|<1","r>1","|r|>1","r=1"]','["|r|<1","r>1","|r|>1","r=1"]','["|r|<1","r>1","|r|>1","r=1"]','A','A geometric series converges exactly when |r|<1.','Геометрический ряд сходится при |r|<1.','Geometrik qator |r|<1 bo‘lganda yaqinlashadi.',35),
('P1-SER-05','P1SER05-L02','learning','medium','Find the sum to infinity of a geometric series with a=5 and r=0.2.','Найдите сумму до бесконечности геометрического ряда с a=5 и r=0,2.','a=5 va r=0.2 bo‘lgan geometrik qatorning cheksiz yig‘indisini toping.','["6.25","4","25","5.2"]','["6,25","4","25","5,2"]','["6.25","4","25","5.2"]','A','S∞=5/(1−0.2)=6.25.','S∞=5/(1−0,2)=6,25.','S∞=5/(1−0.2)=6.25.',40),
('P1-SER-05','P1SER05-L03','learning','medium','A convergent geometric series has first term 8 and sum to infinity 10. Find r.','Сходящийся геометрический ряд имеет первый член 8 и сумму до бесконечности 10. Найдите r.','Yaqinlashuvchi geometrik qatorning birinchi hadi 8, cheksiz yig‘indisi 10. r ni toping.','["0.2","0.8","−0.2","1.25"]','["0,2","0,8","−0,2","1,25"]','["0.2","0.8","−0.2","1.25"]','A','10=8/(1−r), so 1−r=0.8 and r=0.2.','10=8/(1−r), поэтому r=0,2.','10=8/(1−r), demak r=0.2.',50),
('P1-SER-05','P1SER05-R01','retest','easy','Find the sum to infinity when a=9 and r=1/3.','Найдите сумму до бесконечности при a=9 и r=1/3.','a=9 va r=1/3 bo‘lganda cheksiz yig‘indini toping.','["13.5","12","27","6"]','["13,5","12","27","6"]','["13.5","12","27","6"]','A','S∞=9/(1−1/3)=13.5.','S∞=9/(1−1/3)=13,5.','S∞=9/(1−1/3)=13.5.',40),
('P1-SER-05','P1SER05-R02','retest','medium','A geometric series has a=10 and r=−0.4. Which statement is correct?','Геометрический ряд имеет a=10 и r=−0,4. Какое утверждение верно?','Geometrik qator uchun a=10 va r=−0.4. Qaysi gap to‘g‘ri?','["It converges and S∞=50/7","It diverges because r is negative","It converges and S∞=25","It diverges because |r|<1"]','["Он сходится и S∞=50/7","Он расходится, потому что r отрицательно","Он сходится и S∞=25","Он расходится, потому что |r|<1"]','["U yaqinlashadi va S∞=50/7","r manfiyligi sabab uzoqlashadi","U yaqinlashadi va S∞=25","|r|<1 bo‘lgani uchun uzoqlashadi"]','A','|−0.4|<1, so it converges; S∞=10/(1+0.4)=50/7.','|−0,4|<1, поэтому ряд сходится; S∞=50/7.','|−0.4|<1, demak qator yaqinlashadi; S∞=50/7.',50),
('P1-SER-05','P1SER05-M01','mixed','hard','The series 6+3+1.5+... is geometric. Find the sum of all terms after the first four terms.','Ряд 6+3+1,5+... геометрический. Найдите сумму всех членов после первых четырёх.','6+3+1.5+... geometrik qator. Dastlabki to‘rtta haddan keyingi barcha hadlar yig‘indisini toping.','["0.75","11.25","12","1.5"]','["0,75","11,25","12","1,5"]','["0.75","11.25","12","1.5"]','A','S∞=12 and S4=6(1−(1/2)^4)/(1−1/2)=11.25, so the remainder is 0.75.','S∞=12, S4=11,25, остаток 0,75.','S∞=12, S4=11.25, qoldiq 0.75.',70)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Series',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw17_20_series_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw17_20_series_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_series_v1' and status='draft'), keys(skill,k,role) as (values
('P1-SER-03','P1SER03-D01','diagnostic'),('P1-SER-03','P1SER03-L01','learning'),('P1-SER-03','P1SER03-L02','learning'),('P1-SER-03','P1SER03-L03','learning'),('P1-SER-03','P1SER03-R01','retest'),('P1-SER-03','P1SER03-R02','retest'),('P1-SER-03','P1SER03-M01','mixed'),
('P1-SER-04','P1SER04-D01','diagnostic'),('P1-SER-04','P1SER04-L01','learning'),('P1-SER-04','P1SER04-L02','learning'),('P1-SER-04','P1SER04-L03','learning'),('P1-SER-04','P1SER04-R01','retest'),('P1-SER-04','P1SER04-R02','retest'),('P1-SER-04','P1SER04-M01','mixed'),
('P1-SER-05','P1SER05-D01','diagnostic'),('P1-SER-05','P1SER05-L01','learning'),('P1-SER-05','P1SER05-L02','learning'),('P1-SER-05','P1SER05-L03','learning'),('P1-SER-05','P1SER05-R01','retest'),('P1-SER-05','P1SER05-R02','retest'),('P1-SER-05','P1SER05-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw17_20_series_v1 from canonical Series skill intent.','Cambridge 9709 2026-2027 v4; P1 1.6 Series','Complete Pure Mathematics 1; Series (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw17_20_series_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw17_20_series_v1' and m.reserve_role='diagnostic'),
r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1SER03-D01','B','uses_last_term_as_sum','method','320 is not the sum; calculate the nth term and then use the arithmetic-series sum formula.','320 — не сумма; сначала определите структуру и используйте формулу суммы арифметической прогрессии.','320 yig‘indi emas; arifmetik qator yig‘indisi formulasidan foydalaning.','Use S_n=n/2[2a+(n−1)d].','Используйте S_n=n/2[2a+(n−1)d].','S_n=n/2[2a+(n−1)d] dan foydalaning.'),
('P1SER03-D01','C','forgets_number_of_terms','method','95 corresponds to incomplete aggregation; the sum must include all ten terms.','95 получается при неполном суммировании; нужно учесть все 10 членов.','95 to‘liq bo‘lmagan yig‘indi; 10 ta hadning barchasini hisobga oling.','Check n=10 and the factor n/2.','Проверьте n=10 и множитель n/2.','n=10 va n/2 ko‘paytuvchini tekshiring.'),
('P1SER03-D01','D','double_counts_sum','method','370 is twice the correct total; the arithmetic-series formula already averages the endpoints via the factor 1/2.','370 вдвое больше правильной суммы; формула уже содержит деление на 2.','370 to‘g‘ri yig‘indining ikki baravari; formulada 1/2 allaqachon bor.','Keep the n/2 factor.','Сохраните множитель n/2.','n/2 ko‘paytuvchini saqlang.'),
('P1SER04-D01','B','off_by_one_power','method','A six-term GP uses r^6 in the finite-sum formula; check the exponent against n.','Для шести членов используется r^6; проверьте показатель степени.','Olti hadli GP uchun r^6 ishlatiladi; darajani n bilan tekshiring.','Use S_n=a(r^n−1)/(r−1) for r>1.','Используйте S_n=a(r^n−1)/(r−1).','r>1 uchun S_n=a(r^n−1)/(r−1) dan foydalaning.'),
('P1SER04-D01','C','uses_last_term_only','concept','96 is the sixth term, not the sum of the first six terms.','96 — шестой член, а не сумма первых шести.','96 oltinchi had, dastlabki olti had yig‘indisi emas.','Distinguish u_n=ar^(n−1) from S_n.','Различайте u_n=ar^(n−1) и S_n.','u_n=ar^(n−1) va S_n ni ajrating.'),
('P1SER04-D01','D','drops_first_term','method','63 is the geometric factor 2^6−1, before multiplying by the first term 3.','63 — это множитель 2^6−1 до умножения на первый член 3.','63 — birinchi had 3 ga ko‘paytirishdan oldingi 2^6−1 ko‘paytuvchi.','Retain the factor a in the sum formula.','Не теряйте множитель a.','Yig‘indi formulasida a ko‘paytuvchini saqlang.'),
('P1SER05-D01','B','uses_finite_partial_sum','method','18 is only a partial total; the infinite tail must also be included.','18 — лишь частичная сумма; нужно учесть бесконечный хвост.','18 faqat qisman yig‘indi; cheksiz qolgan hadlarni ham qo‘shish kerak.','Check convergence, then use S∞=a/(1−r).','Проверьте сходимость, затем S∞=a/(1−r).','Yaqinlashishni tekshirib, S∞=a/(1−r) ni ishlating.'),
('P1SER05-D01','C','multiplies_by_one_minus_r','method','Multiplying 12 by 1−r gives 6, but the sum-to-infinity formula divides by 1−r.','Умножение 12 на 1−r даёт 6, но формула требует деления.','12 ni 1−r ga ko‘paytirish 6 beradi, ammo formula bo‘lishni talab qiladi.','Use a/(1−r), not a(1−r).','Используйте a/(1−r), а не a(1−r).','a/(1−r) ni ishlating, a(1−r) emas.'),
('P1SER05-D01','D','wrong_convergence_test','concept','Because |1/2|<1, the series does converge.','Так как |1/2|<1, ряд сходится.','|1/2|<1 bo‘lgani uchun qator yaqinlashadi.','Test |r|<1 before deciding convergence.','Перед выводом проверьте |r|<1.','Xulosa oldidan |r|<1 ni tekshiring.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now()
from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_series_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1SER03-W01','P1-SER-03','An arithmetic progression has a=8 and d=5. Find u18 and S18. Then suppose another AP has u5=23 and u12=51; determine its first term and common difference, showing the two equations used.','Арифметическая прогрессия имеет a=8 и d=5. Найдите u18 и S18. Затем для другой прогрессии даны u5=23 и u12=51; найдите первый член и разность, показав две использованные формулы.','Arifmetik progressiyada a=8 va d=5. u18 va S18 ni toping. Keyin boshqa AP uchun u5=23 va u12=51; ikki tenglamani ko‘rsatib, birinchi had va ayirmani toping.','{"max_marks":10,"criteria":[{"id":"u18","marks":2,"rule":"Obtains u18=93."},{"id":"s18","marks":3,"rule":"Obtains S18=909."},{"id":"inverse_equations","marks":2,"rule":"Sets a+4d=23 and a+11d=51."},{"id":"inverse_solution","marks":3,"rule":"Obtains d=4 and a=7 with valid working."}]}','Keep nth-term and sum formulas separate; for the inverse part subtract the two term equations first.','Разделяйте формулы члена и суммы; в обратной задаче сначала вычтите два уравнения.','Had va yig‘indi formulalarini ajrating; teskari qismda ikki tenglamani avval ayiring.'),
('P1SER04-W01','P1-SER-04','A geometric progression has a=6 and r=2. Find u9 and S9. A second GP has u2=12 and u5=324 with positive ratio; find a and r, showing the ratio equation.','Геометрическая прогрессия имеет a=6 и r=2. Найдите u9 и S9. Для второй прогрессии u2=12 и u5=324, r>0; найдите a и r, показав уравнение для отношения.','Geometrik progressiyada a=6 va r=2. u9 va S9 ni toping. Ikkinchi GP uchun u2=12 va u5=324, r>0; nisbat tenglamasini ko‘rsatib, a va r ni toping.','{"max_marks":10,"criteria":[{"id":"u9","marks":2,"rule":"Obtains u9=1536."},{"id":"s9","marks":3,"rule":"Obtains S9=3066."},{"id":"ratio","marks":3,"rule":"Uses u5/u2=r^3=27 and obtains r=3."},{"id":"first_term","marks":2,"rule":"Obtains a=4."}]}','Use u_n=ar^(n−1) for terms and the finite GP sum for S_n; compare terms to isolate a power of r.','Используйте u_n=ar^(n−1) для членов и конечную сумму GP; отношение членов изолирует степень r.','Hadlar uchun u_n=ar^(n−1), yig‘indi uchun GP formulasini ishlating; hadlar nisbatidan r darajasini ajrating.'),
('P1SER05-W01','P1-SER-05','Consider the geometric series 20−5+1.25−0.3125+... . Identify r, justify convergence, find S∞, find S4, and hence find the sum of all terms after the first four.','Рассмотрите геометрический ряд 20−5+1,25−0,3125+... . Найдите r, обоснуйте сходимость, найдите S∞, S4 и затем сумму всех членов после первых четырёх.','20−5+1.25−0.3125+... geometrik qatorni ko‘ring. r ni toping, yaqinlashishni asoslang, S∞ va S4 ni toping, so‘ng dastlabki to‘rtta haddan keyingi barcha hadlar yig‘indisini toping.','{"max_marks":10,"criteria":[{"id":"ratio","marks":2,"rule":"Identifies r=−1/4."},{"id":"convergence","marks":2,"rule":"Uses |r|<1."},{"id":"infinite_sum","marks":2,"rule":"Obtains S∞=16."},{"id":"partial_sum","marks":2,"rule":"Obtains S4=15.9375."},{"id":"tail","marks":2,"rule":"Obtains tail=0.0625."}]}','Keep the negative ratio throughout; compare S∞ and S4 only after confirming convergence.','Сохраняйте отрицательный знак r; сравнивайте S∞ и S4 только после проверки сходимости.','Manfiy r ni saqlang; yaqinlashishni tekshirgandan keyin S∞ va S4 ni solishtiring.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_series_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw17_series_diagnostic','diagnostic','P1 AW17-20 Series diagnostic','Диагностика P1 AW17–20: ряды','P1 AW17–20 qatorlar diagnostikasi'),
('p1_ser03_learning','learning','Arithmetic progression nth term and sum','Арифметическая прогрессия: член и сумма','Arifmetik progressiya: had va yig‘indi'),
('p1_ser04_learning','learning','Geometric progression nth term and finite sum','Геометрическая прогрессия: член и конечная сумма','Geometrik progressiya: had va chekli yig‘indi'),
('p1_ser05_learning','learning','Geometric convergence and sum to infinity','Сходимость и сумма геометрического ряда','Geometrik qator yaqinlashishi va cheksiz yig‘indi'),
('p1_ser03_retest','retest','SER-03 delayed retest','SER-03 отложенный ретест','SER-03 kechiktirilgan retest'),
('p1_ser04_retest','retest','SER-04 delayed retest','SER-04 отложенный ретест','SER-04 kechiktirilgan retest'),
('p1_ser05_retest','retest','SER-05 delayed retest','SER-05 отложенный ретест','SER-05 kechiktirilgan retest'),
('p1_aw17_series_mixed','mixed','P1 AW17-20 Series mixed transfer','P1 AW17–20: смешанный перенос по рядам','P1 AW17–20 qatorlar mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_series_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id,x.primary_skill_code from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key,x.primary_skill_code from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw17_series_diagnostic',1,'P1SER03-D01',null,'P1-SER-03','diagnostic',true),('p1_aw17_series_diagnostic',2,'P1SER04-D01',null,'P1-SER-04','diagnostic',true),('p1_aw17_series_diagnostic',3,'P1SER05-D01',null,'P1-SER-05','diagnostic',true),
('p1_ser03_learning',1,'P1SER03-L01',null,'P1-SER-03','learning',false),('p1_ser03_learning',2,'P1SER03-L02',null,'P1-SER-03','learning',false),('p1_ser03_learning',3,'P1SER03-L03',null,'P1-SER-03','learning',false),('p1_ser03_learning',4,null,'P1SER03-W01','P1-SER-03','written',false),
('p1_ser04_learning',1,'P1SER04-L01',null,'P1-SER-04','learning',false),('p1_ser04_learning',2,'P1SER04-L02',null,'P1-SER-04','learning',false),('p1_ser04_learning',3,'P1SER04-L03',null,'P1-SER-04','learning',false),('p1_ser04_learning',4,null,'P1SER04-W01','P1-SER-04','written',false),
('p1_ser05_learning',1,'P1SER05-L01',null,'P1-SER-05','learning',false),('p1_ser05_learning',2,'P1SER05-L02',null,'P1-SER-05','learning',false),('p1_ser05_learning',3,'P1SER05-L03',null,'P1-SER-05','learning',false),('p1_ser05_learning',4,null,'P1SER05-W01','P1-SER-05','written',false),
('p1_ser03_retest',1,'P1SER03-R01',null,'P1-SER-03','retest',true),('p1_ser04_retest',1,'P1SER04-R01',null,'P1-SER-04','retest',true),('p1_ser05_retest',1,'P1SER05-R01',null,'P1-SER-05','retest',true),
('p1_aw17_series_mixed',1,'P1SER03-M01',null,'P1-SER-03','mixed',true),('p1_aw17_series_mixed',2,'P1SER04-M01',null,'P1-SER-04','mixed',true),('p1_aw17_series_mixed',3,'P1SER05-M01',null,'P1-SER-05','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw17_20_series_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw17_20_series_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw17_20_series_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw17_20_series_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw17_20_series_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw17_20_series_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P1-SER-03','P1-SER-04','P1-SER-05'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'Series skill not ready %',v_skill; end if; end loop;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw17_20_series_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
