-- P0-08: original iClub P5 content seed (P5-DAT-04 beta floor).
-- DRAFT + INACTIVE only; no learner exposure and no existing-question mutation.
begin;
with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p5_repr_beta_v1' and component_code='P5' and status='draft'
), src(content_key,skill_code,reserve_role,topic,subtopic,difficulty,qtype,
        q_en,opts_en,correct_answer,exp_en,q_ru,q_uz,q_en_dup,
        opts_ru,opts_uz,opts_en_dup,exp_ru,exp_uz,exp_en_dup,book_ref,time_limit_sec,secondary_csv) as (
  values
('P5DAT04-D01','P5-DAT-04','diagnostic','P5 Representation of data','P5-DAT-04','easy','mcq','In a histogram, the class 20 ≤ x < 30 has frequency 40. What should its frequency density be?','["4", "40", "0.25", "400"]','A','Class width is 10, so frequency density = frequency ÷ class width = 40 ÷ 10 = 4.','В гистограмме интервал 20 ≤ x < 30 имеет частоту 40. Чему должна быть равна плотность частоты?','Gistogrammada 20 ≤ x < 30 intervalining chastotasi 40. Uning chastota zichligi nechaga teng?','In a histogram, the class 20 ≤ x < 30 has frequency 40. What should its frequency density be?','["4", "40", "0.25", "400"]','["4", "40", "0.25", "400"]','["4", "40", "0.25", "400"]','Ширина интервала равна 10, поэтому плотность частоты = частота ÷ ширина интервала = 40 ÷ 10 = 4.','Interval kengligi 10, shuning uchun chastota zichligi = chastota ÷ interval kengligi = 40 ÷ 10 = 4.','Class width is 10, so frequency density = frequency ÷ class width = 40 ÷ 10 = 4.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-D01',55,''),
('P5DAT04-L01','P5-DAT-04','learning','P5 Representation of data','P5-DAT-04','easy','input','A histogram class 5 ≤ x < 10 has frequency 30. Enter its frequency density.','[]','6','The class width is 5, so frequency density = 30 ÷ 5 = 6.','Интервал гистограммы 5 ≤ x < 10 имеет частоту 30. Введите плотность частоты.','Gistogrammadagi 5 ≤ x < 10 intervalining chastotasi 30. Chastota zichligini kiriting.','A histogram class 5 ≤ x < 10 has frequency 30. Enter its frequency density.','[]','[]','[]','Ширина интервала равна 5, поэтому плотность частоты = 30 ÷ 5 = 6.','Interval kengligi 5, shuning uchun chastota zichligi = 30 ÷ 5 = 6.','The class width is 5, so frequency density = 30 ÷ 5 = 6.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L01',50,''),
('P5DAT04-L02','P5-DAT-04','learning','P5 Representation of data','P5-DAT-04','medium','input','A histogram bar has class width 4 and frequency density 7. Enter the frequency represented by the bar.','[]','28','Frequency = frequency density × class width = 7 × 4 = 28.','Столбец гистограммы имеет ширину интервала 4 и плотность частоты 7. Введите частоту, которую представляет столбец.','Gistogramma ustunining interval kengligi 4 va chastota zichligi 7. Ustun ifodalagan chastotani kiriting.','A histogram bar has class width 4 and frequency density 7. Enter the frequency represented by the bar.','[]','[]','[]','Частота = плотность частоты × ширина интервала = 7 × 4 = 28.','Chastota = chastota zichligi × interval kengligi = 7 × 4 = 28.','Frequency = frequency density × class width = 7 × 4 = 28.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L02',55,''),
('P5DAT04-L03','P5-DAT-04','learning','P5 Representation of data','P5-DAT-04','medium','mcq','A histogram has class 0 ≤ x < 2 with frequency 8 and class 2 ≤ x < 8 with frequency 24. Which statement about the two bar heights is correct?','["The bars have equal height", "The first bar is twice as high", "The second bar is twice as high", "The second bar is three times as high"]','A','The densities are 8/2 = 4 and 24/6 = 4, so the two bar heights are equal.','В гистограмме интервал 0 ≤ x < 2 имеет частоту 8, а интервал 2 ≤ x < 8 — частоту 24. Какое утверждение о высотах двух столбцов верно?','Gistogrammada 0 ≤ x < 2 intervalining chastotasi 8, 2 ≤ x < 8 intervalining chastotasi 24. Ikki ustun balandligi haqida qaysi fikr to‘g‘ri?','A histogram has class 0 ≤ x < 2 with frequency 8 and class 2 ≤ x < 8 with frequency 24. Which statement about the two bar heights is correct?','["The bars have equal height", "The first bar is twice as high", "The second bar is twice as high", "The second bar is three times as high"]','["The bars have equal height", "The first bar is twice as high", "The second bar is twice as high", "The second bar is three times as high"]','["The bars have equal height", "The first bar is twice as high", "The second bar is twice as high", "The second bar is three times as high"]','Плотности равны 8/2 = 4 и 24/6 = 4, поэтому высоты столбцов одинаковы.','Zichliklar 8/2 = 4 va 24/6 = 4, shuning uchun ikki ustun balandligi teng.','The densities are 8/2 = 4 and 24/6 = 4, so the two bar heights are equal.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L03',65,''),
('P5DAT04-R01','P5-DAT-04','retest','P5 Representation of data','P5-DAT-04','medium','input','A histogram class has width 8 and frequency 32. Enter its frequency density.','[]','4','Frequency density = 32 ÷ 8 = 4.','Интервал гистограммы имеет ширину 8 и частоту 32. Введите плотность частоты.','Gistogramma intervalining kengligi 8 va chastotasi 32. Chastota zichligini kiriting.','A histogram class has width 8 and frequency 32. Enter its frequency density.','[]','[]','[]','Плотность частоты = 32 ÷ 8 = 4.','Chastota zichligi = 32 ÷ 8 = 4.','Frequency density = 32 ÷ 8 = 4.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-R01',50,''),
('P5DAT04-R02','P5-DAT-04','retest','P5 Representation of data','P5-DAT-04','medium','input','A histogram bar has frequency density 5 and class width 6. Enter the frequency for that class.','[]','30','Frequency = 5 × 6 = 30.','Столбец гистограммы имеет плотность частоты 5 и ширину интервала 6. Введите частоту этого интервала.','Gistogramma ustunining chastota zichligi 5 va interval kengligi 6. Shu interval chastotasini kiriting.','A histogram bar has frequency density 5 and class width 6. Enter the frequency for that class.','[]','[]','[]','Частота = 5 × 6 = 30.','Chastota = 5 × 6 = 30.','Frequency = 5 × 6 = 30.','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-R02',50,'')
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,s.topic,s.subtopic,s.difficulty,s.qtype,s.q_en,s.opts_en,s.correct_answer,s.exp_en,null,false,s.q_ru,s.q_uz,s.q_en_dup,s.opts_ru,s.opts_uz,s.opts_en_dup,s.exp_ru,s.exp_uz,s.exp_en_dup,s.book_ref,s.time_limit_sec,null,'draft'
from src s where not exists(select 1 from public.questions q where q.book_ref=s.book_ref);
with cv as (select id from private.exam_prep_content_versions where content_version='p5_repr_beta_v1' and component_code='P5' and status='draft'), src(content_key,skill_code,reserve_role,secondary_csv,book_ref) as (
values ('P5DAT04-D01','P5-DAT-04','diagnostic','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-D01'),('P5DAT04-L01','P5-DAT-04','learning','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L01'),('P5DAT04-L02','P5-DAT-04','learning','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L02'),('P5DAT04-L03','P5-DAT-04','learning','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-L03'),('P5DAT04-R01','P5-DAT-04','retest','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-R01'),('P5DAT04-R02','P5-DAT-04','retest','','ExamPrep:P5:p5_repr_beta_v1:P5DAT04-R02'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,s.content_key,q.id,s.skill_code,case when nullif(s.secondary_csv,'') is null then '{}'::text[] else string_to_array(s.secondary_csv,',') end,s.reserve_role,'withheld','draft','Original iClub-authored stem, data, distractors, answer and explanation; no Cambridge/coursebook question text, diagram or mark-scheme wording copied.','Authored specifically for p5_repr_beta_v1 from canonical skill intent and independent numeric/context examples.','Cambridge 9709 2026-2027 v4; P5 5.1 Representation of data','Complete Probability & Statistics 1, Ch3 pp.34-59 (mapping only)','pending','pending','pending','pending','pending',case when s.reserve_role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join src s join public.questions q on q.book_ref=s.book_ref on conflict(content_version_id,content_key) do nothing;
commit;
