-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 2; rows 15-28 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(15,'P1','1.3 Coordinate geometry','P1-COO-01','Получать equation of a straight line из точки, gradient или двух точек.','PR-GRF-01; PR-EQN-01','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(16,'P1','1.3 Coordinate geometry','P1-COO-02','Использовать формы уравнения прямой, distance, midpoint, gradient и intersection.','P1-COO-01; PR-ALG-02','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(17,'P1','1.3 Coordinate geometry','P1-COO-03','Применять gradient conditions для parallel и perpendicular lines.','P1-COO-01','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(18,'P1','1.3 Coordinate geometry','P1-COO-04','Интерпретировать и строить equation of a circle, включая expanded form, centre и radius.','P1-QUA-01; P1-COO-02','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map сводит coordinate geometry преимущественно к прямым; circle content требуется восстановить. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(19,'P1','1.3 Coordinate geometry','P1-COO-05','Решать line–circle и circle geometry problems, сочетая algebra и geometry.','P1-COO-03; P1-COO-04; P1-QUA-03','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map сводит coordinate geometry преимущественно к прямым; circle content требуется восстановить. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(20,'P1','1.3 Coordinate geometry','P1-COO-06','Определять intersections/tangency и parameter conditions через roots/discriminant.','P1-COO-05; P1-QUA-02','Complete Pure Mathematics 1, Ch3 Coordinate geometry','pp. 48–67','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','Math Tour Map сводит coordinate geometry преимущественно к прямым; circle content требуется восстановить. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(21,'P1','1.4 Circular measure','P1-CIR-01','Переводить degrees ↔ radians и использовать radians как естественную угловую меру.','PR-ALG-01','Complete Pure Mathematics 1, Ch4 Circular measure','pp. 74–81','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','В Math Tour Map arc/sector evidence неполно выражено; в книге и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(22,'P1','1.4 Circular measure','P1-CIR-02','Вычислять arc length и восстанавливать неизвестные r или θ.','P1-CIR-01; PR-ALG-03','Complete Pure Mathematics 1, Ch4 Circular measure','pp. 74–81','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','В Math Tour Map arc/sector evidence неполно выражено; в книге и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(23,'P1','1.4 Circular measure','P1-CIR-03','Вычислять sector area и решать composite sector/segment problems.','P1-CIR-01; P1-CIR-02; PR-TRI-01','Complete Pure Mathematics 1, Ch4 Circular measure','pp. 74–81','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','В Math Tour Map arc/sector evidence неполно выражено; в книге и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(24,'P1','1.5 Trigonometry','P1-TRI-01','Строить и использовать graphs of sin, cos и tan, включая simple transformations.','P1-FUN-06; P1-FUN-08; P1-CIR-01','Complete Pure Mathematics 1, Ch5 Trigonometry','pp. 86–104','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E2 Core Coverage I (октябрь–ноябрь)','P1 content покрыто; addition/double-angle formulae из Tour 6 исключены как post-P1 content.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(25,'P1','1.5 Trigonometry','P1-TRI-02','Использовать exact values и related-angle symmetries.','PR-TRI-01; P1-CIR-01','Complete Pure Mathematics 1, Ch5 Trigonometry','pp. 86–104','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E2 Core Coverage I (октябрь–ноябрь)','P1 content покрыто; addition/double-angle formulae из Tour 6 исключены как post-P1 content.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(26,'P1','1.5 Trigonometry','P1-TRI-03','Находить principal values inverse trigonometric functions и интерпретировать calculator output.','P1-TRI-01; PR-CAL-01','Complete Pure Mathematics 1, Ch5 Trigonometry','pp. 86–104','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E2 Core Coverage I (октябрь–ноябрь)','P1 content покрыто; addition/double-angle formulae из Tour 6 исключены как post-P1 content.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(27,'P1','1.5 Trigonometry','P1-TRI-04','Доказывать и применять базовые trigonometric identities.','P1-TRI-02; PR-ALG-03','Complete Pure Mathematics 1, Ch5 Trigonometry','pp. 86–104','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','P1 content покрыто; addition/double-angle formulae из Tour 6 исключены как post-P1 content.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(28,'P1','1.5 Trigonometry','P1-TRI-05','Решать simple trigonometric equations на заданном interval без потери solutions.','P1-TRI-01; P1-TRI-02; P1-TRI-03; P1-TRI-04','Complete Pure Mathematics 1, Ch5 Trigonometry','pp. 86–104','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E2 Core Coverage I (октябрь–ноябрь)','P1 content покрыто; addition/double-angle formulae из Tour 6 исключены как post-P1 content.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
