-- AW9-12 supplemental learning written-understanding checks draft v1.
-- DRAFT ONLY.
begin;
set local lock_timeout='3s';
set local statement_timeout='90s';

do $preflight$
begin
  if (select count(*) from private.exam_prep_written_tasks
      where id between 15624 and 15637 and content_version_id in (4809,4810) and lifecycle_state='draft')<>14
  then raise exception 'aw09_12_written_checks parent tasks missing'; end if;
  if exists(select 1 from private.exam_prep_written_understanding_checks where id between 8924 and 8937 and written_task_id not between 15624 and 15637)
  then raise exception 'aw09_12_written_checks reserved id collision'; end if;
end
$preflight$;

insert into private.exam_prep_written_understanding_checks(
 id,written_task_id,check_order,check_version,check_kind,
 prompt_en,prompt_ru,prompt_uz,options_en,options_ru,options_uz,correct_index,
 rationale_en,rationale_ru,rationale_uz,lifecycle_state,qa_math_status,qa_language_status,qa_technical_status
)
overriding system value
values
(8924,15624,1,'aw10-v1','mcq','Why is a root included when solving a quadratic inequality with ≤ or ≥?','Почему корень включается в решение квадратичного неравенства со знаком ≤ или ≥?','Nega ≤ yoki ≥ belgili kvadrat tengsizlik yechimiga ildiz ham kiritiladi?','["Because the quadratic equals 0 at the root, and equality is allowed","Because every root must always be included","Because the parabola changes direction at every root","Because ≤ and ≥ mean the variable must be positive"]'::jsonb,'["Потому что в корне квадратичное выражение равно 0, а равенство разрешено","Потому что любой корень всегда должен включаться","Потому что парабола меняет направление в каждом корне","Потому что ≤ и ≥ означают, что переменная должна быть положительной"]'::jsonb,'["Chunki ildizda kvadrat ifoda 0 ga teng va tenglikka ruxsat berilgan","Chunki har qanday ildiz doim yechimga kiritiladi","Chunki parabola har bir ildizda yo‘nalishini o‘zgartiradi","Chunki ≤ va ≥ o‘zgaruvchi musbat bo‘lishi kerakligini anglatadi"]'::jsonb,0,'At a root the quadratic expression is exactly zero. Non-strict inequalities include equality, so that endpoint belongs to the solution set.','В корне квадратичное выражение точно равно нулю. Нестрогие неравенства допускают равенство, поэтому такая граница входит в решение.','Ildizda kvadrat ifoda aynan nolga teng. Qat’iy bo‘lmagan tengsizlik tenglikka ruxsat beradi, shuning uchun bu chegara yechimga kiradi.','draft','pending','pending','pending'),
(8925,15625,1,'aw10-v1','mcq','Why do we set the two y-expressions equal when finding intersections of a line and a parabola?','Почему при поиске точек пересечения прямой и параболы мы приравниваем два выражения для y?','Nega chiziq va parabola kesishish nuqtalarini topishda y uchun ikki ifodani tenglashtiramiz?','["Because their gradients must be equal","Because an intersection has the same x and the same y on both curves","Because every parabola is tangent to a line","Because equal y-values guarantee x=0"]'::jsonb,'["Потому что их градиенты должны быть равны","Потому что в точке пересечения одинаковы и x, и y для обеих кривых","Потому что любая парабола касается прямой","Потому что равные значения y гарантируют x=0"]'::jsonb,'["Chunki ularning gradientlari teng bo‘lishi kerak","Chunki kesishish nuqtasida har ikki egri uchun ham x va y bir xil","Chunki har qanday parabola chiziqqa urinadi","Chunki teng y qiymatlar x=0 ni kafolatlaydi"]'::jsonb,1,'At an intersection one ordered pair lies on both equations, so for the same x the two formulas must produce the same y.','В точке пересечения одна и та же упорядоченная пара удовлетворяет обоим уравнениям, поэтому при одном x оба выражения дают одно и то же y.','Kesishish nuqtasidagi bitta tartibli juft ikkala tenglamani ham qanoatlantiradi, demak bir xil x uchun ikkala formula bir xil y beradi.','draft','pending','pending','pending'),
(8926,15626,1,'aw10-v1','mcq','Why can a repeated expression such as x²−2x be replaced temporarily by u?','Почему повторяющееся выражение вроде x²−2x можно временно заменить переменной u?','Nega x²−2x kabi takrorlanuvchi ifodani vaqtincha u o‘zgaruvchi bilan almashtirish mumkin?','["Because x²−2x is always positive","Because u must be a linear function","Because the equation depends on that whole repeated expression as one quantity","Because substitution removes the need to solve for x"]'::jsonb,'["Потому что x²−2x всегда положительно","Потому что u должна быть линейной функцией","Потому что уравнение зависит от всего повторяющегося выражения как от одной величины","Потому что после замены не нужно возвращаться к x"]'::jsonb,'["Chunki x²−2x doim musbat","Chunki u chiziqli funksiya bo‘lishi kerak","Chunki tenglama takrorlanayotgan butun ifodaga bitta kattalik sifatida bog‘liq","Chunki almashtirishdan keyin x ni topish shart emas"]'::jsonb,2,'The equation contains the same composite quantity repeatedly. Treating it as u reduces the structure to a quadratic in u, after which u is replaced by the original expression.','В уравнении многократно повторяется одна и та же составная величина. Замена её на u сводит задачу к квадратному уравнению по u, после чего выполняется обратная подстановка.','Tenglamada bir xil murakkab kattalik qayta-qayta uchraydi. Uni u deb olish tenglamani u bo‘yicha kvadrat ko‘rinishga keltiradi, keyin u o‘rniga asl ifoda qayta qo‘yiladi.','draft','pending','pending','pending'),
(8927,15627,1,'aw10-v1','mcq','What determines the domain of a composite function f(g(x))?','Что определяет область определения композиции f(g(x))?','f(g(x)) kompozitsiyaning aniqlanish sohasini nima belgilaydi?','["Only the formula for f, regardless of g","Only the original domain of g","Whether f and g have the same range","x must be allowed by g and g(x) must lie in the domain of f"]'::jsonb,'["Только формула f независимо от g","Только исходная область определения g","Совпадают ли области значений f и g","x должен быть допустим для g, а g(x) должен принадлежать области определения f"]'::jsonb,'["Faqat f formulasi, g dan qat’i nazar","Faqat g ning dastlabki aniqlanish sohasi","f va g ning qiymatlar sohasi bir xil bo‘lishi","x g uchun ruxsat etilgan bo‘lishi va g(x) f ning aniqlanish sohasiga kirishi kerak"]'::jsonb,3,'A composite is defined only when the inner function can accept x and its output is a valid input for the outer function.','Композиция определена только тогда, когда внутренняя функция принимает x, а её результат является допустимым входом для внешней функции.','Kompozitsiya faqat ichki funksiya x ni qabul qilganda va uning chiqishi tashqi funksiya uchun ruxsat etilgan kirish bo‘lganda aniqlanadi.','draft','pending','pending','pending'),
(8928,15628,1,'aw10-v1','mcq','Why must a function be one-one on its chosen domain to have an inverse function?','Почему функция должна быть взаимно однозначной на выбранной области, чтобы иметь обратную функцию?','Nega funksiya teskari funksiyaga ega bo‘lishi uchun tanlangan sohada bir qiymatli bo‘lishi kerak?','["Because each output must come from at most one input so the inverse gives one output","Because one-one functions must be quadratic","Because an inverse always has the same formula","Because the domain must contain only positive numbers"]'::jsonb,'["Потому что каждому выходному значению должен соответствовать не более чем один вход, чтобы обратная зависимость была функцией","Потому что взаимно однозначные функции обязаны быть квадратными","Потому что обратная функция всегда имеет ту же формулу","Потому что область определения должна содержать только положительные числа"]'::jsonb,'["Chunki teskari bog‘lanish funksiya bo‘lishi uchun har bir chiqish qiymatiga ko‘pi bilan bitta kirish mos kelishi kerak","Chunki bir qiymatli funksiyalar albatta kvadrat bo‘ladi","Chunki teskari funksiya doim ayni formulaga ega","Chunki aniqlanish sohasi faqat musbat sonlardan iborat bo‘lishi kerak"]'::jsonb,0,'If two different inputs produced the same output, reversing the mapping would send one input of the inverse to two outputs, which would not be a function.','Если два разных входа дают один и тот же выход, то при обращении одно входное значение обратной зависимости получит два выхода, и это уже не функция.','Agar ikki turli kirish bir xil chiqish bersa, teskari akslantirishda bitta kirishga ikkita chiqish mos keladi va bu funksiya bo‘lmaydi.','draft','pending','pending','pending'),
(8929,15629,1,'aw10-v1','mcq','What geometric transformation links the graph of a one-one function and its inverse?','Какое геометрическое преобразование связывает график взаимно однозначной функции и её обратной?','Bir qiymatli funksiya grafigi bilan uning teskari grafigini qaysi geometrik almashtirish bog‘laydi?','["Reflection in the x-axis","Reflection in the line y=x","Translation one unit right","Rotation through 90° about the origin"]'::jsonb,'["Отражение относительно оси x","Отражение относительно прямой y=x","Сдвиг на одну единицу вправо","Поворот на 90° вокруг начала координат"]'::jsonb,'["x o‘qiga nisbatan akslantirish","y=x chiziqqa nisbatan akslantirish","bir birlik o‘ngga siljitish","koordinata boshiga nisbatan 90° burish"]'::jsonb,1,'Taking the inverse swaps input and output, so every point (x,y) becomes (y,x). That is reflection in y=x.','При переходе к обратной функции вход и выход меняются местами: каждая точка (x,y) переходит в (y,x). Это отражение относительно y=x.','Teskari funksiyada kirish va chiqish almashadi: har bir (x,y) nuqta (y,x) ga o‘tadi. Bu y=x ga nisbatan akslantirishdir.','draft','pending','pending','pending'),
(8930,15630,1,'aw10-v1','mcq','In (x−a)²+(y−b)²=r², what does the right-hand side represent?','В уравнении (x−a)²+(y−b)²=r² что означает правая часть?','(x−a)²+(y−b)²=r² tenglamada o‘ng tomon nimani bildiradi?','["The diameter","The radius","The square of the radius","The x-coordinate of the centre"]'::jsonb,'["Диаметр","Радиус","Квадрат радиуса","x-координату центра"]'::jsonb,'["Diametr","Radius","Radiusning kvadrati","Markazning x-koordinatasi"]'::jsonb,2,'The distance formula is squared in the circle equation, so the constant on the right is r², not r.','В уравнении окружности используется квадрат расстояния, поэтому справа стоит r², а не r.','Aylana tenglamasida masofa kvadratlangan, shuning uchun o‘ng tomonda r emas, r² turadi.','draft','pending','pending','pending'),
(8931,15631,1,'aw10-v1','mcq','Why does s=rθ work directly when θ is measured in radians?','Почему формула s=rθ напрямую работает, когда θ измеряется в радианах?','Nega θ radianlarda o‘lchanganda s=rθ formula bevosita ishlaydi?','["Because radians and degrees are numerically equal","Because every circle has radius 1","Because arc length never depends on angle","Because radian measure is defined by θ=s/r"]'::jsonb,'["Потому что радианы и градусы численно равны","Потому что радиус любой окружности равен 1","Потому что длина дуги не зависит от угла","Потому что радианная мера определяется как θ=s/r"]'::jsonb,'["Chunki radian va gradus son jihatdan teng","Chunki har bir aylananing radiusi 1","Chunki yoy uzunligi burchakka bog‘liq emas","Chunki radian o‘lchovi θ=s/r deb ta’riflanadi"]'::jsonb,3,'By definition, θ=s/r for radian measure. Rearranging gives s=rθ without an additional conversion factor.','По определению радианной меры θ=s/r. После преобразования получаем s=rθ без дополнительного коэффициента перевода.','Radian o‘lchov ta’rifiga ko‘ra θ=s/r. Bundan bevosita s=rθ kelib chiqadi va qo‘shimcha o‘tkazish koeffitsiyenti kerak emas.','draft','pending','pending','pending'),
(8932,15632,1,'aw10-v1','mcq','What part of a data set is described by the interquartile range?','Какую часть набора данных описывает межквартильный размах?','Kvartillar oralig‘i ma’lumotlar to‘plamining qaysi qismini tavsiflaydi?','["The spread of the middle 50% of the data","The distance from the minimum to the maximum","Only values above the median","The number of outliers"]'::jsonb,'["Разброс средней половины данных","Расстояние от минимума до максимума","Только значения выше медианы","Количество выбросов"]'::jsonb,'["Ma’lumotlarning o‘rta 50% tarqoqligi","Minimumdan maksimumgacha masofa","Faqat medianadan yuqori qiymatlar","Chet qiymatlar soni"]'::jsonb,0,'IQR=Q3−Q1, so it measures the spread between the 25th and 75th percentiles: the middle half of the data.','IQR=Q3−Q1, поэтому он измеряет разброс между 25-м и 75-м процентилями, то есть средней половины данных.','IQR=Q3−Q1, demak u 25- va 75-percentillar orasidagi, ya’ni ma’lumotlarning o‘rta yarmidagi tarqoqlikni o‘lchaydi.','draft','pending','pending','pending'),
(8933,15633,1,'aw10-v1','mcq','How do you find the number of observations in a range a<x≤b from cumulative frequencies?','Как найти число наблюдений в диапазоне a<x≤b по накопленным частотам?','Kumulyativ chastotalardan a<x≤b oralig‘idagi kuzatuvlar soni qanday topiladi?','["Add CF(a) and CF(b)","Subtract CF(a) from CF(b)","Divide CF(b) by CF(a)","Use only CF(a)"]'::jsonb,'["Сложить CF(a) и CF(b)","Вычесть CF(a) из CF(b)","Разделить CF(b) на CF(a)","Использовать только CF(a)"]'::jsonb,'["CF(a) va CF(b) ni qo‘shish","CF(b) dan CF(a) ni ayirish","CF(b) ni CF(a) ga bo‘lish","Faqat CF(a) dan foydalanish"]'::jsonb,1,'CF(b) counts observations up to b and CF(a) counts those up to a. Their difference leaves the observations with a<x≤b.','CF(b) считает наблюдения до b включительно, а CF(a) — до a включительно. Разность даёт число наблюдений с a<x≤b.','CF(b) b gacha bo‘lgan kuzatuvlarni, CF(a) esa a gacha bo‘lganlarni sanaydi. Ayirma a<x≤b oralig‘idagi kuzatuvlarni beradi.','draft','pending','pending','pending'),
(8934,15634,1,'aw10-v1','mcq','Why does adding the same constant to every value leave standard deviation unchanged?','Почему прибавление одной и той же константы ко всем значениям не меняет стандартное отклонение?','Nega barcha qiymatlarga bir xil doimiy son qo‘shish standart og‘ishni o‘zgartirmaydi?','["Because the mean never changes","Because all values become zero","Because the mean shifts by the same amount, so deviations from the mean stay the same","Because standard deviation depends only on the maximum"]'::jsonb,'["Потому что среднее никогда не меняется","Потому что все значения становятся нулевыми","Потому что среднее сдвигается на ту же величину, поэтому отклонения от среднего не меняются","Потому что стандартное отклонение зависит только от максимума"]'::jsonb,'["Chunki o‘rtacha qiymat hech qachon o‘zgarmaydi","Chunki barcha qiymatlar nol bo‘ladi","Chunki o‘rtacha ham shu miqdorga siljiydi va o‘rtachadan og‘ishlar o‘zgarmaydi","Chunki standart og‘ish faqat maksimumga bog‘liq"]'::jsonb,2,'A common shift moves every observation and the mean equally. Each difference from the mean therefore stays unchanged.','Общий сдвиг одинаково изменяет каждое наблюдение и среднее. Поэтому каждое отклонение от среднего остаётся прежним.','Umumiy siljish har bir kuzatuv va o‘rtachani bir xil o‘zgartiradi. Shuning uchun o‘rtachadan har bir og‘ish o‘zgarishsiz qoladi.','draft','pending','pending','pending'),
(8935,15635,1,'aw10-v1','mcq','When should combinations be used instead of permutations?','Когда следует использовать сочетания вместо перестановок?','Qachon permutatsiya o‘rniga kombinatsiyadan foydalanish kerak?','["Whenever objects are different","Whenever repetition is allowed","Whenever there are more than two choices","When only the selected group matters and its internal order does not"]'::jsonb,'["Всегда, когда объекты различаются","Всегда, когда разрешены повторения","Всегда, когда вариантов больше двух","Когда важен только выбранный состав, а внутренний порядок не важен"]'::jsonb,'["Obyektlar turli bo‘lganda har doim","Takrorlanishga ruxsat berilganda har doim","Tanlovlar ikkitadan ko‘p bo‘lganda har doim","Faqat tanlangan guruh muhim bo‘lib, uning ichki tartibi muhim bo‘lmaganda"]'::jsonb,3,'Combinations count selections where reordering the same chosen members does not create a new outcome.','Сочетания считают выборы, в которых перестановка тех же выбранных элементов не создаёт нового исхода.','Kombinatsiyalar bir xil tanlangan a’zolarni qayta tartiblash yangi natija yaratmaydigan tanlovlarni sanaydi.','draft','pending','pending','pending'),
(8936,15636,1,'aw10-v1','mcq','In a probability calculation using combinations, what should the denominator count?','Что должен считать знаменатель в вычислении вероятности с помощью сочетаний?','Kombinatsiyalar yordamida ehtimol hisoblanganda maxraj nimani sanashi kerak?','["All equally likely unordered selections of the required size","Only the favourable selections","All possible ordered sequences, even if order is irrelevant","Only selections containing the most common category"]'::jsonb,'["Все равновероятные неупорядоченные выборы нужного размера","Только благоприятные выборы","Все возможные упорядоченные последовательности, даже если порядок не важен","Только выборы с самой частой категорией"]'::jsonb,'["Kerakli hajmdagi barcha teng ehtimolli tartibsiz tanlovlar","Faqat qulay tanlovlar","Tartib muhim bo‘lmasa ham barcha tartibli ketma-ketliklar","Faqat eng ko‘p uchraydigan toifani o‘z ichiga olgan tanlovlar"]'::jsonb,0,'Probability is favourable outcomes divided by all equally likely outcomes. If the sample is an unordered selection, the denominator must count all such selections.','Вероятность равна отношению благоприятных исходов ко всем равновероятным исходам. Если выбор неупорядоченный, знаменатель должен считать все такие выборы.','Ehtimol qulay natijalar sonining barcha teng ehtimolli natijalarga nisbatidir. Tanlov tartibsiz bo‘lsa, maxraj barcha shunday tanlovlarni sanashi kerak.','draft','pending','pending','pending'),
(8937,15637,1,'aw10-v1','mcq','Which equality is the standard numerical test for independence of events A and B?','Какое равенство является стандартной численной проверкой независимости событий A и B?','A va B hodisalar mustaqilligini tekshirish uchun qaysi tenglik standart hisoblanadi?','["P(A∪B)=P(A)+P(B)","P(A∩B)=P(A)P(B)","P(A)=P(B)","P(A|B)=0"]'::jsonb,'["P(A∪B)=P(A)+P(B)","P(A∩B)=P(A)P(B)","P(A)=P(B)","P(A|B)=0"]'::jsonb,'["P(A∪B)=P(A)+P(B)","P(A∩B)=P(A)P(B)","P(A)=P(B)","P(A|B)=0"]'::jsonb,1,'Events are independent exactly when their joint probability equals the product of their individual probabilities.','События независимы тогда и только тогда, когда вероятность их пересечения равна произведению отдельных вероятностей.','Hodisalar aynan ularning birgalikdagi ehtimoli alohida ehtimollar ko‘paytmasiga teng bo‘lganda mustaqil bo‘ladi.','draft','pending','pending','pending')
on conflict (id) do nothing;

do $postcheck$
declare v_bad int;
begin
  if (select count(*) from private.exam_prep_written_understanding_checks
      where id between 8924 and 8937 and written_task_id between 15624 and 15637
        and lifecycle_state='draft' and qa_math_status='pending' and qa_language_status='pending' and qa_technical_status='pending')<>14
  then raise exception 'aw09_12_written_checks cardinality/state mismatch'; end if;

  select count(*) into v_bad from private.exam_prep_written_understanding_checks c
  where c.id between 8924 and 8937 and (
    jsonb_array_length(c.options_en)<>4 or jsonb_array_length(c.options_ru)<>4 or jsonb_array_length(c.options_uz)<>4
    or c.correct_index not between 0 and 3
    or nullif(btrim(c.prompt_en),'') is null or nullif(btrim(c.prompt_ru),'') is null or nullif(btrim(c.prompt_uz),'') is null
    or nullif(btrim(c.rationale_en),'') is null or nullif(btrim(c.rationale_ru),'') is null or nullif(btrim(c.rationale_uz),'') is null
  );
  if v_bad<>0 then raise exception 'aw09_12_written_checks structural/trilingual invalid=%',v_bad; end if;

  if (select count(*) from private.exam_prep_written_understanding_checks where id between 8924 and 8937 and correct_index=0)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8924 and 8937 and correct_index=1)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8924 and 8937 and correct_index=2)<>3
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8924 and 8937 and correct_index=3)<>3
  then raise exception 'aw09_12_written_checks answer-position balance drift'; end if;
end
$postcheck$;

commit;
