-- AW5-8 supplemental learning written-understanding checks draft v1.
-- DRAFT ONLY.
begin;
set local lock_timeout='3s';
set local statement_timeout='90s';

do $preflight$
begin
  if (select count(*) from private.exam_prep_written_tasks
      where id between 15610 and 15623 and content_version_id in (4805,4806) and lifecycle_state='draft')<>14
  then raise exception 'aw05_08_written_checks parent tasks missing'; end if;
  if exists(select 1 from private.exam_prep_written_understanding_checks where id between 8910 and 8923 and written_task_id not between 15610 and 15623)
  then raise exception 'aw05_08_written_checks reserved id collision'; end if;
end
$preflight$;

insert into private.exam_prep_written_understanding_checks(
 id,written_task_id,check_order,check_version,check_kind,
 prompt_en,prompt_ru,prompt_uz,options_en,options_ru,options_uz,correct_index,
 rationale_en,rationale_ru,rationale_uz,lifecycle_state,qa_math_status,qa_language_status,qa_technical_status
)
overriding system value
values
(8910,15610,1,'aw06-v1','mcq','Why does f(x−5) move the graph 5 units to the right?','Почему f(x−5) сдвигает график на 5 единиц вправо?','Nega f(x−5) grafikni 5 birlik o‘ngga siljitadi?','["Because the output of f is increased by 5","Because the same original input u is obtained when x−5=u, so x=u+5","Because every negative sign inside f moves a graph left","Because x-coordinates are multiplied by 5"]'::jsonb,'["Because the output of f is increased by 5","Because the same original input u is obtained when x−5=u, so x=u+5","Because every negative sign inside f moves a graph left","Because x-coordinates are multiplied by 5"]'::jsonb,'["Because the output of f is increased by 5","Because the same original input u is obtained when x−5=u, so x=u+5","Because every negative sign inside f moves a graph left","Because x-coordinates are multiplied by 5"]'::jsonb,1,'For the original input u, the transformed graph needs x−5=u, hence x=u+5. The corresponding x-coordinate is therefore 5 larger.','Для исходного аргумента u нужно x−5=u, откуда x=u+5. Поэтому соответствующая x-координата увеличивается на 5.','Dastlabki u argument uchun x−5=u bo‘lishi kerak, bundan x=u+5. Demak mos x-koordinata 5 ga kattalashadi.','draft','pending','pending','pending'),
(8911,15611,1,'aw06-v1','mcq','What is the combined point mapping produced by y=−f(−x)?','Какое общее преобразование координат задаёт y=−f(−x)?','y=−f(−x) qanday umumiy nuqta almashtirishini beradi?','["(x,y)→(x,−y)","(x,y)→(−x,y)","(x,y)→(−x,−y)","(x,y)→(y,x)"]'::jsonb,'["(x,y)→(x,−y)","(x,y)→(−x,y)","(x,y)→(−x,−y)","(x,y)→(y,x)"]'::jsonb,'["(x,y)→(x,−y)","(x,y)→(−x,y)","(x,y)→(−x,−y)","(x,y)→(y,x)"]'::jsonb,2,'The inside −x reflects x-coordinates in the y-axis and the outside minus reflects y-coordinates in the x-axis.','Внутреннее −x отражает x-координаты относительно оси y, а внешний минус отражает y-координаты относительно оси x.','Ichkaridagi −x x-koordinatalarni y o‘qiga, tashqi minus esa y-koordinatalarni x o‘qiga nisbatan akslantiradi.','draft','pending','pending','pending'),
(8912,15612,1,'aw06-v1','mcq','Why are x-coordinates halved in y=f(2x)?','Почему в y=f(2x) x-координаты уменьшаются в 2 раза?','Nega y=f(2x) da x-koordinatalar ikki marta kamayadi?','["To reproduce an original input u, 2x=u, so x=u/2","Because the output of f is divided by 2","Because the graph moves 2 units left","Because every coefficient 2 halves y-values"]'::jsonb,'["To reproduce an original input u, 2x=u, so x=u/2","Because the output of f is divided by 2","Because the graph moves 2 units left","Because every coefficient 2 halves y-values"]'::jsonb,'["To reproduce an original input u, 2x=u, so x=u/2","Because the output of f is divided by 2","Because the graph moves 2 units left","Because every coefficient 2 halves y-values"]'::jsonb,0,'An original input u is reached when 2x=u. Thus the transformed x-coordinate is u/2.','Исходный аргумент u достигается при 2x=u, поэтому новая x-координата равна u/2.','Dastlabki u argument 2x=u bo‘lganda olinadi. Shuning uchun yangi x-koordinata u/2 ga teng.','draft','pending','pending','pending'),
(8913,15613,1,'aw06-v1','mcq','Which calculation gives the gradient of the line through two distinct points (x₁,y₁) and (x₂,y₂)?','Какое вычисление даёт градиент прямой через две различные точки (x₁,y₁) и (x₂,y₂)?','Ikki turli (x₁,y₁) va (x₂,y₂) nuqtadan o‘tuvchi chiziq gradientini qaysi hisoblash beradi?','["(x₂−x₁)/(y₂−y₁)","(y₂+y₁)/(x₂+x₁)","y₂−y₁+x₂−x₁","(y₂−y₁)/(x₂−x₁)"]'::jsonb,'["(x₂−x₁)/(y₂−y₁)","(y₂+y₁)/(x₂+x₁)","y₂−y₁+x₂−x₁","(y₂−y₁)/(x₂−x₁)"]'::jsonb,'["(x₂−x₁)/(y₂−y₁)","(y₂+y₁)/(x₂+x₁)","y₂−y₁+x₂−x₁","(y₂−y₁)/(x₂−x₁)"]'::jsonb,3,'Gradient is vertical change divided by horizontal change: (y₂−y₁)/(x₂−x₁).','Градиент равен изменению по вертикали, делённому на изменение по горизонтали: (y₂−y₁)/(x₂−x₁).','Gradient vertikal o‘zgarishning gorizontal o‘zgarishga nisbatidir: (y₂−y₁)/(x₂−x₁).','draft','pending','pending','pending'),
(8914,15614,1,'aw06-v1','mcq','Why is the midpoint found by averaging the x-coordinates and the y-coordinates separately?','Почему координаты середины находят отдельным усреднением x-координат и y-координат?','Nega o‘rta nuqta x-koordinatalar va y-koordinatalarni alohida o‘rtachalash orqali topiladi?','["Because a midpoint must lie on an axis","Because its horizontal and vertical positions are each halfway between the corresponding endpoint coordinates","Because distance is always the sum of coordinates","Because the midpoint must have integer coordinates"]'::jsonb,'["Because a midpoint must lie on an axis","Because its horizontal and vertical positions are each halfway between the corresponding endpoint coordinates","Because distance is always the sum of coordinates","Because the midpoint must have integer coordinates"]'::jsonb,'["Because a midpoint must lie on an axis","Because its horizontal and vertical positions are each halfway between the corresponding endpoint coordinates","Because distance is always the sum of coordinates","Because the midpoint must have integer coordinates"]'::jsonb,1,'A midpoint is halfway between the endpoints in both coordinate directions, so each coordinate is the average of the two endpoint coordinates.','Середина находится ровно посередине между концами по обоим координатным направлениям, поэтому каждая координата равна среднему соответствующих координат концов.','O‘rta nuqta har ikki koordinata yo‘nalishida uchlar orasining aynan yarmida turadi, shuning uchun har bir koordinata mos uch koordinatalarining o‘rtachasidir.','draft','pending','pending','pending'),
(8915,15615,1,'aw06-v1','mcq','For two non-vertical perpendicular lines with gradients m₁ and m₂, which relation must hold?','Для двух невертикальных перпендикулярных прямых с градиентами m₁ и m₂ какое соотношение выполняется?','Gradientlari m₁ va m₂ bo‘lgan ikki vertikal bo‘lmagan perpendikulyar chiziq uchun qaysi munosabat bajariladi?','["m₁m₂=−1","m₁=m₂","m₁m₂=1","m₁+m₂=0"]'::jsonb,'["m₁m₂=−1","m₁=m₂","m₁m₂=1","m₁+m₂=0"]'::jsonb,'["m₁m₂=−1","m₁=m₂","m₁m₂=1","m₁+m₂=0"]'::jsonb,0,'Perpendicular non-vertical gradients are negative reciprocals, so their product is −1.','Градиенты перпендикулярных невертикальных прямых являются отрицательными обратными величинами, поэтому их произведение равно −1.','Perpendikulyar vertikal bo‘lmagan chiziqlar gradientlari manfiy teskari qiymatlar bo‘lib, ularning ko‘paytmasi −1 ga teng.','draft','pending','pending','pending'),
(8916,15616,1,'aw06-v1','mcq','Which factor converts an angle from degrees to radians?','На какой множитель нужно умножить угол в градусах, чтобы получить радианы?','Gradusdagi burchakni radianga o‘tkazish uchun qaysi koeffitsiyentga ko‘paytiriladi?','["180/π","π","π/180","1/180"]'::jsonb,'["180/π","π","π/180","1/180"]'::jsonb,'["180/π","π","π/180","1/180"]'::jsonb,2,'Since 180°=π radians, one degree equals π/180 radians.','Так как 180°=π радиан, один градус равен π/180 радиан.','180°=π radian bo‘lgani uchun bir gradus π/180 radianga teng.','draft','pending','pending','pending'),
(8917,15617,1,'aw06-v1','mcq','What horizontal translation is represented by y=sin(x−π/4)?','Какой горизонтальный сдвиг задаёт y=sin(x−π/4)?','y=sin(x−π/4) qanday gorizontal siljishni ifodalaydi?','["π/4 to the left","π/2 to the right","π/2 to the left","π/4 to the right"]'::jsonb,'["π/4 to the left","π/2 to the right","π/2 to the left","π/4 to the right"]'::jsonb,'["π/4 to the left","π/2 to the right","π/2 to the left","π/4 to the right"]'::jsonb,3,'For the same sine input u, x−π/4=u gives x=u+π/4, so the graph shifts π/4 to the right.','Для того же аргумента синуса u уравнение x−π/4=u даёт x=u+π/4, поэтому график сдвигается на π/4 вправо.','Bir xil u sinus argumenti uchun x−π/4=u dan x=u+π/4 keladi, demak grafik π/4 ga o‘ngga siljiydi.','draft','pending','pending','pending'),
(8918,15618,1,'aw06-v1','mcq','Why is choosing a chair and a secretary from the same group an ordered outcome?','Почему выбор председателя и секретаря из одной группы является упорядоченным исходом?','Nega bir guruhdan rais va kotib tanlash tartibli natija hisoblanadi?','["Because swapping the two selected people changes who holds each role","Because every selection problem is ordered","Because two people can never form a committee","Because order matters only when numbers are used"]'::jsonb,'["Because swapping the two selected people changes who holds each role","Because every selection problem is ordered","Because two people can never form a committee","Because order matters only when numbers are used"]'::jsonb,'["Because swapping the two selected people changes who holds each role","Because every selection problem is ordered","Because two people can never form a committee","Because order matters only when numbers are used"]'::jsonb,0,'The roles are different. If the same two people swap roles, the assignment changes, so it is a different outcome.','Роли различны. Если те же два человека поменяются ролями, назначение изменится, значит это другой исход.','Vazifalar turlicha. Shu ikki kishi vazifalarni almashtirsa, tayinlov o‘zgaradi, demak bu boshqa natija.','draft','pending','pending','pending'),
(8919,15619,1,'aw06-v1','mcq','Why is 7P4, rather than 7C4, used for placing four of seven distinct books on a shelf?','Почему для размещения четырёх из семи разных книг на полке используют 7P4, а не 7C4?','Nega yetti turli kitobdan to‘rttasini tokchaga joylashtirishda 7C4 emas, 7P4 ishlatiladi?','["Because all seven books must be used","Because combinations are only for repeated objects","Because changing the left-to-right order gives a different display","Because 7P4 is always smaller than 7C4"]'::jsonb,'["Because all seven books must be used","Because combinations are only for repeated objects","Because changing the left-to-right order gives a different display","Because 7P4 is always smaller than 7C4"]'::jsonb,'["Because all seven books must be used","Because combinations are only for repeated objects","Because changing the left-to-right order gives a different display","Because 7P4 is always smaller than 7C4"]'::jsonb,2,'Shelf positions are ordered. The same four books in a different left-to-right order form a different display.','Места на полке упорядочены. Те же четыре книги в другом порядке слева направо образуют другую расстановку.','Tokchadagi joylar tartibli. Xuddi shu to‘rtta kitob boshqa chapdan o‘ngga tartibda joylashsa, boshqa ko‘rinish hosil bo‘ladi.','draft','pending','pending','pending'),
(8920,15620,1,'aw06-v1','mcq','Why do repeated identical letters lead to division by factorials such as 2!?','Почему при повторяющихся одинаковых буквах делят на факториалы, например на 2!?','Nega bir xil takrorlangan harflarda 2! kabi faktoriallarga bo‘linadi?','["Because factorials remove every possible letter","Because swapping identical copies was counted as different in the raw factorial even though the visible arrangement does not change","Because repeated letters must be placed first","Because division makes the answer ordered"]'::jsonb,'["Because factorials remove every possible letter","Because swapping identical copies was counted as different in the raw factorial even though the visible arrangement does not change","Because repeated letters must be placed first","Because division makes the answer ordered"]'::jsonb,'["Because factorials remove every possible letter","Because swapping identical copies was counted as different in the raw factorial even though the visible arrangement does not change","Because repeated letters must be placed first","Because division makes the answer ordered"]'::jsonb,1,'The raw factorial labels identical copies as if they were different. Swapping those copies does not create a new arrangement, so that overcount must be removed.','Исходный факториал считает одинаковые копии различными. Их перестановка не создаёт новой расстановки, поэтому лишний подсчёт нужно убрать.','Dastlabki faktorial bir xil nusxalarni turli deb sanaydi. Ularni almashtirish yangi tartib bermaydi, shuning uchun ortiqcha sanash olib tashlanadi.','draft','pending','pending','pending'),
(8921,15621,1,'aw06-v1','mcq','After fixing C at one end, why are A and B treated as one block when they must stand together?','После фиксации C на одном конце почему A и B считают одним блоком, если они должны стоять рядом?','C ni bir chetda mahkamlagandan keyin A va B yonma-yon turishi shart bo‘lsa, nega ular bitta blok deb olinadi?','["Because A and B then have only one internal order","Because the block removes C from the arrangement","Because blocks are used only for identical people","Because treating AB as one unit guarantees adjacency, after which the two internal orders AB and BA are counted separately"]'::jsonb,'["Because A and B then have only one internal order","Because the block removes C from the arrangement","Because blocks are used only for identical people","Because treating AB as one unit guarantees adjacency, after which the two internal orders AB and BA are counted separately"]'::jsonb,'["Because A and B then have only one internal order","Because the block removes C from the arrangement","Because blocks are used only for identical people","Because treating AB as one unit guarantees adjacency, after which the two internal orders AB and BA are counted separately"]'::jsonb,3,'Making AB one unit enforces adjacency. The block can occupy one position among the other units, and the two internal orders are then counted separately.','Объединение AB в один объект гарантирует соседство. Блок занимает одно место среди остальных объектов, а два внутренних порядка AB и BA учитываются отдельно.','AB ni bitta birlik deb olish yonma-yonlikni kafolatlaydi. Blok boshqa birliklar orasida bitta joy egallaydi, AB va BA ichki tartiblari esa alohida sanaladi.','draft','pending','pending','pending'),
(8922,15622,1,'aw06-v1','mcq','In the event “H occurs or the spinner shows 2”, why is outcome (H,2) counted only once?','Почему в событии «выпала H или на диске выпало 2» исход (H,2) считают только один раз?','“H chiqadi yoki aylantirgichda 2 chiqadi” hodisasida nega (H,2) natija faqat bir marta sanaladi?','["Because (H,2) is impossible","Because it belongs to both parts of the union, but a sample-space outcome appears only once in the union","Because H and 2 are mutually exclusive","Because every union has exactly four outcomes"]'::jsonb,'["Because (H,2) is impossible","Because it belongs to both parts of the union, but a sample-space outcome appears only once in the union","Because H and 2 are mutually exclusive","Because every union has exactly four outcomes"]'::jsonb,'["Because (H,2) is impossible","Because it belongs to both parts of the union, but a sample-space outcome appears only once in the union","Because H and 2 are mutually exclusive","Because every union has exactly four outcomes"]'::jsonb,1,'(H,2) satisfies both conditions, but a union is a set of outcomes, so the same outcome is included once.','(H,2) удовлетворяет обоим условиям, но объединение — это множество исходов, поэтому один и тот же исход включается один раз.','(H,2) ikkala shartni ham bajaradi, lekin birlashma natijalar to‘plami bo‘lgani uchun ayni natija bir marta kiritiladi.','draft','pending','pending','pending'),
(8923,15623,1,'aw06-v1','mcq','Why does the addition rule subtract P(A∩B) once?','Почему в правиле сложения P(A∩B) вычитают один раз?','Nega qo‘shish qoidasida P(A∩B) bir marta ayiriladi?','["Because adding P(A) and P(B) counts the intersection twice","Because intersections always have probability 0","Because subtraction makes A and B independent","Because P(A∩B) is the complement of the union"]'::jsonb,'["Because adding P(A) and P(B) counts the intersection twice","Because intersections always have probability 0","Because subtraction makes A and B independent","Because P(A∩B) is the complement of the union"]'::jsonb,'["Because adding P(A) and P(B) counts the intersection twice","Because intersections always have probability 0","Because subtraction makes A and B independent","Because P(A∩B) is the complement of the union"]'::jsonb,0,'P(A)+P(B) includes every intersection outcome once in A and once in B. Subtracting the intersection once leaves each union outcome counted exactly once.','P(A)+P(B) учитывает каждый исход пересечения один раз в A и один раз в B. Вычитание пересечения один раз оставляет каждый исход объединения посчитанным ровно один раз.','P(A)+P(B) kesishmadagi har bir natijani A da bir marta va B da bir marta sanaydi. Kesishmani bir marta ayirish birlashmadagi har bir natijani aynan bir marta qoldiradi.','draft','pending','pending','pending')
on conflict (id) do nothing;

-- Replace RU/UZ options explicitly to keep each learner-facing language native.
update private.exam_prep_written_understanding_checks set options_ru='["Потому что значение функции увеличивается на 5","Потому что тот же исходный аргумент u получается при x−5=u, то есть x=u+5","Потому что любой знак минус внутри f сдвигает график влево","Потому что x-координаты умножаются на 5"]'::jsonb, options_uz='["Chunki funksiya qiymati 5 ga oshadi","Chunki ayni dastlabki u argument x−5=u bo‘lganda olinadi, ya’ni x=u+5","Chunki f ichidagi har qanday minus grafikni chapga siljitadi","Chunki x-koordinatalar 5 ga ko‘payadi"]'::jsonb where id=8910 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["(x,y)→(x,−y)","(x,y)→(−x,y)","(x,y)→(−x,−y)","(x,y)→(y,x)"]'::jsonb, options_uz='["(x,y)→(x,−y)","(x,y)→(−x,y)","(x,y)→(−x,−y)","(x,y)→(y,x)"]'::jsonb where id=8911 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Чтобы получить исходный аргумент u, нужно 2x=u, поэтому x=u/2","Потому что значение функции делится на 2","Потому что график сдвигается на 2 влево","Потому что любой коэффициент 2 уменьшает y вдвое"]'::jsonb, options_uz='["Dastlabki u argumentni olish uchun 2x=u, demak x=u/2","Chunki funksiya qiymati 2 ga bo‘linadi","Chunki grafik 2 birlik chapga siljiydi","Chunki har qanday 2 koeffitsiyent y ni ikki marta kamaytiradi"]'::jsonb where id=8912 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["(x₂−x₁)/(y₂−y₁)","(y₂+y₁)/(x₂+x₁)","y₂−y₁+x₂−x₁","(y₂−y₁)/(x₂−x₁)"]'::jsonb, options_uz='["(x₂−x₁)/(y₂−y₁)","(y₂+y₁)/(x₂+x₁)","y₂−y₁+x₂−x₁","(y₂−y₁)/(x₂−x₁)"]'::jsonb where id=8913 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что середина обязана лежать на оси","Потому что её горизонтальное и вертикальное положения находятся ровно посередине между соответствующими координатами концов","Потому что расстояние всегда равно сумме координат","Потому что координаты середины должны быть целыми"]'::jsonb, options_uz='["Chunki o‘rta nuqta o‘qda yotishi shart","Chunki uning gorizontal va vertikal o‘rni mos uch koordinatalari orasining aynan yarmida","Chunki masofa doim koordinatalar yig‘indisiga teng","Chunki o‘rta nuqta koordinatalari butun bo‘lishi shart"]'::jsonb where id=8914 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["m₁m₂=−1","m₁=m₂","m₁m₂=1","m₁+m₂=0"]'::jsonb, options_uz='["m₁m₂=−1","m₁=m₂","m₁m₂=1","m₁+m₂=0"]'::jsonb where id=8915 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["180/π","π","π/180","1/180"]'::jsonb, options_uz='["180/π","π","π/180","1/180"]'::jsonb where id=8916 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["π/4 влево","π/2 вправо","π/2 влево","π/4 вправо"]'::jsonb, options_uz='["π/4 chapga","π/2 o‘ngga","π/2 chapga","π/4 o‘ngga"]'::jsonb where id=8917 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что перестановка двух выбранных людей меняет, кто занимает каждую должность","Потому что любая задача выбора является упорядоченной","Потому что два человека никогда не могут образовать комитет","Потому что порядок важен только при использовании чисел"]'::jsonb, options_uz='["Chunki tanlangan ikki kishining o‘rnini almashtirish kim qaysi vazifani bajarishini o‘zgartiradi","Chunki har qanday tanlash masalasi tartibli","Chunki ikki kishi hech qachon qo‘mita tuza olmaydi","Chunki tartib faqat sonlar ishlatilganda muhim"]'::jsonb where id=8918 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что нужно использовать все семь книг","Потому что сочетания применяются только к повторяющимся объектам","Потому что изменение порядка слева направо даёт другую расстановку","Потому что 7P4 всегда меньше 7C4"]'::jsonb, options_uz='["Chunki yetti kitobning barchasi ishlatilishi kerak","Chunki kombinatsiyalar faqat takrorlanuvchi obyektlar uchun","Chunki chapdan o‘ngga tartibni o‘zgartirish boshqa joylashuv beradi","Chunki 7P4 har doim 7C4 dan kichik"]'::jsonb where id=8919 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что факториалы удаляют все возможные буквы","Потому что исходный факториал считает перестановку одинаковых копий различной, хотя видимая расстановка не меняется","Потому что повторяющиеся буквы нужно ставить первыми","Потому что деление делает ответ упорядоченным"]'::jsonb, options_uz='["Chunki faktoriallar barcha mumkin bo‘lgan harflarni olib tashlaydi","Chunki dastlabki faktorial bir xil nusxalarni almashtirishni boshqa deb sanaydi, holbuki ko‘rinadigan tartib o‘zgarmaydi","Chunki takrorlangan harflarni avval qo‘yish kerak","Chunki bo‘lish javobni tartibli qiladi"]'::jsonb where id=8920 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что внутри блока A и B имеют только один порядок","Потому что блок удаляет C из расстановки","Потому что блоки применяются только к одинаковым людям","Потому что блок AB гарантирует соседство, после чего отдельно учитываются два внутренних порядка AB и BA"]'::jsonb, options_uz='["Chunki blok ichida A va B faqat bitta tartibga ega","Chunki blok C ni joylashuvdan olib tashlaydi","Chunki bloklar faqat bir xil odamlar uchun ishlatiladi","Chunki AB ni bitta birlik deb olish yonma-yonlikni kafolatlaydi, keyin AB va BA ichki tartiblari alohida sanaladi"]'::jsonb where id=8921 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что (H,2) невозможен","Потому что он принадлежит обеим частям объединения, но один исход пространства включается в объединение только один раз","Потому что H и 2 взаимоисключающие","Потому что любое объединение содержит ровно четыре исхода"]'::jsonb, options_uz='["Chunki (H,2) mumkin emas","Chunki u birlashmaning ikkala qismiga tegishli, lekin namunalar fazosidagi bitta natija birlashmaga faqat bir marta kiradi","Chunki H va 2 o‘zaro istisno","Chunki har qanday birlashmada aynan to‘rtta natija bor"]'::jsonb where id=8922 and lifecycle_state='draft';
update private.exam_prep_written_understanding_checks set options_ru='["Потому что при сложении P(A) и P(B) пересечение учитывается дважды","Потому что вероятность пересечения всегда равна 0","Потому что вычитание делает A и B независимыми","Потому что P(A∩B) — дополнение объединения"]'::jsonb, options_uz='["Chunki P(A) va P(B) ni qo‘shganda kesishma ikki marta sanaladi","Chunki kesishma ehtimoli doim 0","Chunki ayirish A va B ni mustaqil qiladi","Chunki P(A∩B) birlashmaning to‘ldiruvchisi"]'::jsonb where id=8923 and lifecycle_state='draft';

do $postcheck$
declare v_bad int;
begin
  if (select count(*) from private.exam_prep_written_understanding_checks
      where id between 8910 and 8923 and written_task_id between 15610 and 15623
        and lifecycle_state='draft' and qa_math_status='pending' and qa_language_status='pending' and qa_technical_status='pending')<>14
  then raise exception 'aw05_08_written_checks cardinality/state mismatch'; end if;

  select count(*) into v_bad from private.exam_prep_written_understanding_checks c
  where c.id between 8910 and 8923 and (
    jsonb_array_length(c.options_en)<>4 or jsonb_array_length(c.options_ru)<>4 or jsonb_array_length(c.options_uz)<>4
    or c.correct_index not between 0 and 3
    or nullif(btrim(c.prompt_en),'') is null or nullif(btrim(c.prompt_ru),'') is null or nullif(btrim(c.prompt_uz),'') is null
    or nullif(btrim(c.rationale_en),'') is null or nullif(btrim(c.rationale_ru),'') is null or nullif(btrim(c.rationale_uz),'') is null
  );
  if v_bad<>0 then raise exception 'aw05_08_written_checks structural/trilingual invalid=%',v_bad; end if;

  if (select count(*) from private.exam_prep_written_understanding_checks where id between 8910 and 8923 and correct_index=0)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8910 and 8923 and correct_index=1)<>4
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8910 and 8923 and correct_index=2)<>3
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8910 and 8923 and correct_index=3)<>3
  then raise exception 'aw05_08_written_checks answer-position balance drift'; end if;
end
$postcheck$;

commit;
