-- AW13-16 supplemental learning written-understanding checks draft v1.
-- DRAFT ONLY.
begin;
set local lock_timeout='3s';
set local statement_timeout='90s';

do $preflight$
begin
  if (select count(*) from private.exam_prep_written_tasks
      where id between 15638 and 15649 and content_version_id in (4813,4814) and lifecycle_state='draft')<>12
  then raise exception 'aw13_16_written_checks parent tasks missing'; end if;
  if exists(select 1 from private.exam_prep_written_understanding_checks
            where id between 8938 and 8949 and written_task_id not between 15638 and 15649)
  then raise exception 'aw13_16_written_checks reserved id collision'; end if;
end
$preflight$;

insert into private.exam_prep_written_understanding_checks(
 id,written_task_id,check_order,check_version,check_kind,
 prompt_en,prompt_ru,prompt_uz,options_en,options_ru,options_uz,correct_index,
 rationale_en,rationale_ru,rationale_uz,lifecycle_state,qa_math_status,qa_language_status,qa_technical_status
)
overriding system value
values
(8938,15638,1,'aw14-v1','mcq','Why must an intersection point satisfy both the circle equation and the line equation?','Почему точка пересечения должна удовлетворять и уравнению окружности, и уравнению прямой?','Nega kesishish nuqtasi ham aylana, ham chiziq tenglamasini qanoatlantirishi kerak?','["Because the same ordered pair lies on both graphs","Because every line through a circle centre is tangent","Because the x-coordinate must be zero","Because circles and lines always have two intersections"]'::jsonb,'["Потому что одна и та же упорядоченная пара лежит на обоих графиках","Потому что любая прямая через центр окружности является касательной","Потому что x-координата должна быть равна нулю","Потому что окружность и прямая всегда имеют две точки пересечения"]'::jsonb,'["Chunki bir xil tartibli juft ikkala grafikda ham yotadi","Chunki aylana markazidan o‘tgan har qanday chiziq urinma","Chunki x-koordinata nol bo‘lishi kerak","Chunki aylana va chiziq doim ikkita nuqtada kesishadi"]'::jsonb,0,'An intersection is one point common to both graphs, so its coordinates must make both original equations true.','Точка пересечения принадлежит обоим графикам, поэтому её координаты должны удовлетворять обоим исходным уравнениям.','Kesishish nuqtasi ikkala grafik uchun umumiy, shuning uchun uning koordinatalari ikkala dastlabki tenglamani ham qanoatlantirishi kerak.','draft','pending','pending','pending'),
(8939,15639,1,'aw14-v1','mcq','After substituting a line into a circle equation, what condition identifies tangency?','После подстановки уравнения прямой в уравнение окружности какое условие определяет касание?','Chiziq tenglamasini aylana tenglamasiga qo‘ygandan keyin urinishni qaysi shart aniqlaydi?','["The quadratic has two distinct roots","The quadratic has discriminant zero","The quadratic has no real roots","The gradient of the line is zero"]'::jsonb,'["Квадратное уравнение имеет два различных корня","Дискриминант квадратного уравнения равен нулю","Квадратное уравнение не имеет действительных корней","Градиент прямой равен нулю"]'::jsonb,'["Kvadrat tenglama ikkita turli ildizga ega","Kvadrat tenglama diskriminanti nol","Kvadrat tenglama haqiqiy ildizga ega emas","Chiziq gradienti nol"]'::jsonb,1,'A tangent meets the circle at exactly one point, so the substituted quadratic has one repeated root and therefore discriminant zero.','Касательная имеет с окружностью ровно одну общую точку, поэтому полученное квадратное уравнение имеет кратный корень и нулевой дискриминант.','Urinma aylana bilan aynan bitta umumiy nuqtaga ega, shuning uchun hosil bo‘lgan kvadrat tenglama takroriy ildizga va nol diskriminantga ega.','draft','pending','pending','pending'),
(8940,15640,1,'aw14-v1','mcq','How is the area of a minor circular segment found when the sector and its central triangle are known?','Как найти площадь малого кругового сегмента, если известны площади сектора и центрального треугольника?','Sektor va markaziy uchburchak yuzlari ma’lum bo‘lsa, kichik doira segmenti yuzi qanday topiladi?','["Triangle area plus sector area","Triangle area divided by sector area","Sector area minus triangle area","Sector area multiplied by the angle"]'::jsonb,'["Площадь треугольника плюс площадь сектора","Площадь треугольника разделить на площадь сектора","Площадь сектора минус площадь треугольника","Площадь сектора умножить на угол"]'::jsonb,'["Uchburchak yuzi bilan sektor yuzini qo‘shish","Uchburchak yuzini sektor yuziga bo‘lish","Sektor yuzidan uchburchak yuzini ayirish","Sektor yuzini burchakka ko‘paytirish"]'::jsonb,2,'The minor segment is the part of the sector outside the triangle formed by the two radii and the chord.','Малый сегмент — это часть сектора вне треугольника, образованного двумя радиусами и хордой.','Kichik segment ikki radius va vatar hosil qilgan uchburchakdan tashqaridagi sektor qismidir.','draft','pending','pending','pending'),
(8941,15641,1,'aw14-v1','mcq','When finding an exact trigonometric value from a reference angle, what determines the sign?','При нахождении точного тригонометрического значения по опорному углу что определяет знак?','Tayanch burchakdan aniq trigonometrik qiymat topilganda ishorani nima belgilaydi?','["Only the size of the reference angle","Whether the angle is larger than 90°","Whether the answer contains a square root","The quadrant and the trigonometric function"]'::jsonb,'["Только величина опорного угла","Только то, больше ли угол 90°","Только наличие квадратного корня в ответе","Четверть и выбранная тригонометрическая функция"]'::jsonb,'["Faqat tayanch burchak kattaligi","Faqat burchak 90° dan kattaligi","Faqat javobda kvadrat ildiz borligi","Chorak va tanlangan trigonometrik funksiya"]'::jsonb,3,'The reference angle gives the magnitude. The quadrant tells whether sine, cosine or tangent is positive or negative.','Опорный угол задаёт модуль значения, а четверть определяет знак синуса, косинуса или тангенса.','Tayanch burchak qiymat modulini beradi, chorak esa sinus, kosinus yoki tangens ishorasini belgilaydi.','draft','pending','pending','pending'),
(8942,15642,1,'aw14-v1','mcq','What is the principal-value range of cos⁻¹ in degrees?','Каков диапазон главных значений cos⁻¹ в градусах?','cos⁻¹ ning graduslardagi asosiy qiymatlar oralig‘i qaysi?','["0°≤θ≤180°","−90°≤θ≤90°","0°≤θ<360°","−180°<θ≤180°"]'::jsonb,'["0°≤θ≤180°","−90°≤θ≤90°","0°≤θ<360°","−180°<θ≤180°"]'::jsonb,'["0°≤θ≤180°","−90°≤θ≤90°","0°≤θ<360°","−180°<θ≤180°"]'::jsonb,0,'The inverse cosine function returns its principal value in the interval from 0° to 180°, inclusive.','Обратный косинус возвращает главное значение в промежутке от 0° до 180° включительно.','Teskari kosinus asosiy qiymatni 0° dan 180° gacha, chegaralari bilan birga, qaytaradi.','draft','pending','pending','pending'),
(8943,15643,1,'aw14-v1','mcq','Why must denominator restrictions be stated before cancelling factors in a trigonometric identity?','Почему перед сокращением множителей в тригонометрическом тождестве нужно указать ограничения знаменателя?','Nega trigonometrik ayniyatda omillarni qisqartirishdan oldin maxraj cheklovlarini yozish kerak?','["Because every trigonometric expression is positive","Because cancellation cannot make an originally undefined expression valid","Because identities are true only for acute angles","Because denominators must always equal 1"]'::jsonb,'["Потому что любое тригонометрическое выражение положительно","Потому что сокращение не может сделать допустимым выражение, которое изначально не определено","Потому что тождества верны только для острых углов","Потому что знаменатель всегда должен быть равен 1"]'::jsonb,'["Chunki har qanday trigonometrik ifoda musbat","Chunki qisqartirish dastlab aniqlanmagan ifodani ruxsat etilgan qilib qo‘ya olmaydi","Chunki ayniyatlar faqat o‘tkir burchaklar uchun to‘g‘ri","Chunki maxraj doim 1 ga teng bo‘lishi kerak"]'::jsonb,1,'Algebraic simplification preserves the original domain. Values that made an original denominator zero remain excluded even if a factor cancels.','Алгебраическое упрощение сохраняет исходную область определения. Значения, обращавшие исходный знаменатель в ноль, остаются исключёнными даже после сокращения.','Algebraik soddalashtirish dastlabki aniqlanish sohasini saqlaydi. Dastlabki maxrajni nol qilgan qiymatlar omil qisqarsa ham chiqarib tashlanadi.','draft','pending','pending','pending'),
(8944,15644,1,'aw14-v1','mcq','After reducing a trigonometric equation to a quadratic in sin θ or cos θ, what must be checked before finding angles?','После сведения тригонометрического уравнения к квадратному относительно sin θ или cos θ что нужно проверить до нахождения углов?','Trigonometrik tenglama sin θ yoki cos θ bo‘yicha kvadrat tenglamaga keltirilgach, burchaklarni topishdan oldin nimani tekshirish kerak?','["Every root must be positive","Every root must be an integer","Each sine or cosine value must lie between −1 and 1","Each root must be less than 360"]'::jsonb,'["Каждый корень должен быть положительным","Каждый корень должен быть целым","Каждое значение синуса или косинуса должно лежать от −1 до 1","Каждый корень должен быть меньше 360"]'::jsonb,'["Har bir ildiz musbat bo‘lishi kerak","Har bir ildiz butun son bo‘lishi kerak","Har bir sinus yoki kosinus qiymati −1 va 1 orasida bo‘lishi kerak","Har bir ildiz 360 dan kichik bo‘lishi kerak"]'::jsonb,2,'Real sine and cosine values cannot be below −1 or above 1, so any algebraic root outside that interval must be rejected.','Действительные значения синуса и косинуса не могут быть меньше −1 или больше 1, поэтому алгебраический корень вне этого диапазона нужно отбросить.','Haqiqiy sinus va kosinus qiymatlari −1 dan kichik yoki 1 dan katta bo‘la olmaydi, shuning uchun bu oraliqdan tashqaridagi algebraik ildiz rad etiladi.','draft','pending','pending','pending'),
(8945,15645,1,'aw14-v1','mcq','Which statistics should be separated when comparing the typical value and consistency of two data sets?','Какие статистики следует разделять при сравнении типичного значения и стабильности двух наборов данных?','Ikki ma’lumot to‘plamining odatiy qiymati va barqarorligini taqqoslashda qaysi statistikalarni alohida ko‘rish kerak?','["Maximum for typical value and minimum for consistency","Range for typical value and median for consistency","Only the mean for both claims","A location measure for typical value and a spread measure for consistency"]'::jsonb,'["Максимум для типичного значения и минимум для стабильности","Размах для типичного значения и медиану для стабильности","Только среднее для обоих выводов","Меру положения для типичного значения и меру разброса для стабильности"]'::jsonb,'["Odatiy qiymat uchun maksimum, barqarorlik uchun minimum","Odatiy qiymat uchun diapazon, barqarorlik uchun mediana","Har ikkala xulosa uchun faqat o‘rtacha","Odatiy qiymat uchun markaz o‘lchovi, barqarorlik uchun tarqalish o‘lchovi"]'::jsonb,3,'Typical level and consistency answer different questions. A centre statistic such as median describes location, while IQR or standard deviation describes spread.','Типичный уровень и стабильность отвечают на разные вопросы. Мера центра, например медиана, описывает положение, а IQR или стандартное отклонение — разброс.','Odatiy daraja va barqarorlik turli savollarga javob beradi. Mediana kabi markaz o‘lchovi joylashuvni, IQR yoki standart og‘ish esa tarqalishni bildiradi.','draft','pending','pending','pending'),
(8946,15646,1,'aw14-v1','mcq','Which expression gives the variance when n, Σx and Σx² are known and division by n is used?','Какое выражение даёт дисперсию, когда известны n, Σx и Σx² и используется деление на n?','n, Σx va Σx² ma’lum bo‘lib, n ga bo‘lish ishlatilganda dispersiya qaysi ifoda bilan topiladi?','["Σx²/n−(Σx/n)²","Σx²−Σx","Σx/n+Σx²/n","(Σx²/n)²−Σx/n"]'::jsonb,'["Σx²/n−(Σx/n)²","Σx²−Σx","Σx/n+Σx²/n","(Σx²/n)²−Σx/n"]'::jsonb,'["Σx²/n−(Σx/n)²","Σx²−Σx","Σx/n+Σx²/n","(Σx²/n)²−Σx/n"]'::jsonb,0,'Variance is mean of squares minus square of the mean: Σx²/n−(Σx/n)².','Дисперсия равна среднему квадратов минус квадрат среднего: Σx²/n−(Σx/n)².','Dispersiya kvadratlar o‘rtachasidan o‘rtacha kvadratini ayirish bilan topiladi: Σx²/n−(Σx/n)².','draft','pending','pending','pending'),
(8947,15647,1,'aw14-v1','mcq','Why must group sizes be used when finding a combined mean?','Почему при нахождении объединённого среднего нужно учитывать размеры групп?','Birlashtirilgan o‘rtachani topishda nima uchun guruh hajmlarini hisobga olish kerak?','["Because the group with the larger mean is always more important","Because each group mean must first be converted back to its total contribution","Because combined means are found by adding the two means only","Because group sizes affect only the standard deviation"]'::jsonb,'["Потому что группа с большим средним всегда важнее","Потому что среднее каждой группы сначала нужно преобразовать обратно в её суммарный вклад","Потому что объединённое среднее находят простым сложением двух средних","Потому что размеры групп влияют только на стандартное отклонение"]'::jsonb,'["Chunki o‘rtachasi katta guruh doim muhimroq","Chunki har bir guruh o‘rtachasini avval uning umumiy yig‘indisiga aylantirish kerak","Chunki birlashtirilgan o‘rtacha faqat ikki o‘rtachani qo‘shish bilan topiladi","Chunki guruh hajmi faqat standart og‘ishga ta’sir qiladi"]'::jsonb,1,'A mean is total divided by count. Different group sizes contribute different totals, so each mean must be weighted by its number of observations.','Среднее — это сумма, делённая на число наблюдений. Группы разного размера дают разные суммарные вклады, поэтому каждое среднее взвешивается числом наблюдений.','O‘rtacha yig‘indining kuzatuvlar soniga nisbatidir. Turli hajmdagi guruhlar turli umumiy hissa beradi, shuning uchun har bir o‘rtacha kuzatuvlar soni bilan og‘irlanadi.','draft','pending','pending','pending'),
(8948,15648,1,'aw14-v1','mcq','In P(A|B), which event defines the denominator of the conditional probability?','В P(A|B) какое событие задаёт знаменатель условной вероятности?','P(A|B) da shartli ehtimol maxrajini qaysi hodisa belgilaydi?','["A∪B","A","B","Aᶜ"]'::jsonb,'["A∪B","A","B","Aᶜ"]'::jsonb,'["A∪B","A","B","Aᶜ"]'::jsonb,2,'Conditioning on B restricts the sample space to B, so P(A|B)=P(A∩B)/P(B).','Условие B ограничивает пространство исходов событием B, поэтому P(A|B)=P(A∩B)/P(B).','B ga shartlash namunalar fazosini B hodisasi bilan cheklaydi, shuning uchun P(A|B)=P(A∩B)/P(B).','draft','pending','pending','pending'),
(8949,15649,1,'aw14-v1','mcq','How are probabilities combined on a probability tree for mutually exclusive complete paths?','Как объединяются вероятности на дереве вероятностей для взаимоисключающих полных путей?','Ehtimollar daraxtida o‘zaro istisno to‘liq yo‘llar ehtimollari qanday birlashtiriladi?','["Add along each path and multiply different paths","Subtract branch probabilities from 1 at every step","Multiply only the first-stage probabilities","Multiply along each path, then add the probabilities of the required disjoint paths"]'::jsonb,'["Складывать вдоль каждого пути и перемножать разные пути","На каждом шаге вычитать вероятность ветви из 1","Перемножать только вероятности первого этапа","Перемножать вдоль каждого пути, затем складывать вероятности нужных несовместимых путей"]'::jsonb,'["Har bir yo‘l bo‘ylab qo‘shib, turli yo‘llarni ko‘paytirish","Har bosqichda shox ehtimolini 1 dan ayirish","Faqat birinchi bosqich ehtimollarini ko‘paytirish","Har bir yo‘l bo‘ylab ko‘paytirib, kerakli o‘zaro istisno yo‘llar ehtimollarini qo‘shish"]'::jsonb,3,'A complete path represents consecutive events, so branch probabilities are multiplied. Different disjoint paths for the same required outcome are then added.','Полный путь представляет последовательные события, поэтому вероятности ветвей перемножаются. Затем вероятности разных несовместимых путей нужного исхода складываются.','To‘liq yo‘l ketma-ket hodisalarni bildiradi, shuning uchun shox ehtimollari ko‘paytiriladi. Bir xil kerakli natijaga olib boruvchi o‘zaro istisno yo‘llar ehtimollari esa qo‘shiladi.','draft','pending','pending','pending')
on conflict(id) do nothing;

do $postcheck$
declare v_bad int;
begin
  if (select count(*) from private.exam_prep_written_understanding_checks
      where id between 8938 and 8949 and written_task_id between 15638 and 15649
        and lifecycle_state='draft' and qa_math_status='pending'
        and qa_language_status='pending' and qa_technical_status='pending')<>12
  then raise exception 'aw13_16_written_checks cardinality/state mismatch'; end if;

  select count(*) into v_bad
  from private.exam_prep_written_understanding_checks c
  where c.id between 8938 and 8949 and (
    jsonb_array_length(c.options_en)<>4
    or jsonb_array_length(c.options_ru)<>4
    or jsonb_array_length(c.options_uz)<>4
    or c.correct_index not between 0 and 3
    or nullif(btrim(c.prompt_en),'') is null or nullif(btrim(c.prompt_ru),'') is null or nullif(btrim(c.prompt_uz),'') is null
    or nullif(btrim(c.rationale_en),'') is null or nullif(btrim(c.rationale_ru),'') is null or nullif(btrim(c.rationale_uz),'') is null
  );
  if v_bad<>0 then raise exception 'aw13_16_written_checks structural/trilingual invalid=%',v_bad; end if;

  if (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8949 and correct_index=0)<>3
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8949 and correct_index=1)<>3
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8949 and correct_index=2)<>3
     or (select count(*) from private.exam_prep_written_understanding_checks where id between 8938 and 8949 and correct_index=3)<>3
  then raise exception 'aw13_16_written_checks answer-position balance drift'; end if;
end
$postcheck$;

commit;
