-- P1-02 P5 AW21-24 DAT-09: mean and standard deviation from raw/frequency/summary totals.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw21_24_dat09_v1','P5','P5 AW21-24 DAT-09 mean and standard deviation','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat09_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5DAT09-D01','diagnostic','medium','For n=5 observations, sum x=40 and sum x^2=350. Find the mean and standard deviation using variance = sum x^2/n - mean^2.','Для n=5 наблюдений sum x=40 и sum x^2=350. Найдите среднее и стандартное отклонение по формуле variance = sum x^2/n - mean^2.','n=5 kuzatuv uchun sum x=40 va sum x^2=350. variance = sum x^2/n - mean^2 formulasi bilan o‘rtacha va standart og‘ishni toping.','["mean 8, standard deviation sqrt(6)","mean 8, standard deviation 6","mean 7, standard deviation sqrt(6)","mean 8, standard deviation sqrt(70)"]','["среднее 8, стандартное отклонение sqrt(6)","среднее 8, стандартное отклонение 6","среднее 7, стандартное отклонение sqrt(6)","среднее 8, стандартное отклонение sqrt(70)"]','["o‘rtacha 8, standart og‘ish sqrt(6)","o‘rtacha 8, standart og‘ish 6","o‘rtacha 7, standart og‘ish sqrt(6)","o‘rtacha 8, standart og‘ish sqrt(70)"]','A','Mean=40/5=8. Variance=350/5-8^2=70-64=6, so standard deviation=sqrt(6).','Среднее 8. Дисперсия 350/5-64=6, поэтому стандартное отклонение sqrt(6).','O‘rtacha 8. Dispersiya 350/5-64=6, standart og‘ish sqrt(6).',55),
('P5DAT09-L01','learning','easy','The values are 2, 4, 6, 8. Find the mean and standard deviation using division by n.','Значения 2, 4, 6, 8. Найдите среднее и стандартное отклонение, деля на n.','Qiymatlar 2, 4, 6, 8. n ga bo‘lib o‘rtacha va standart og‘ishni toping.','["mean 5, standard deviation sqrt(5)","mean 5, standard deviation 5","mean 4, standard deviation sqrt(5)","mean 5, standard deviation sqrt(20)"]','["среднее 5, стандартное отклонение sqrt(5)","среднее 5, стандартное отклонение 5","среднее 4, стандартное отклонение sqrt(5)","среднее 5, стандартное отклонение sqrt(20)"]','["o‘rtacha 5, standart og‘ish sqrt(5)","o‘rtacha 5, standart og‘ish 5","o‘rtacha 4, standart og‘ish sqrt(5)","o‘rtacha 5, standart og‘ish sqrt(20)"]','A','Mean=5. Squared deviations are 9,1,1,9; their mean is 5, so SD=sqrt(5).','Среднее 5. Среднее квадратов отклонений равно 5, поэтому SD=sqrt(5).','O‘rtacha 5. Kvadrat og‘ishlarning o‘rtachasi 5, demak SD=sqrt(5).',40),
('P5DAT09-L02','learning','medium','For n=10, sum x=50 and sum x^2=290. Find the standard deviation.','Для n=10, sum x=50 и sum x^2=290. Найдите стандартное отклонение.','n=10, sum x=50 va sum x^2=290. Standart og‘ishni toping.','["2","4","sqrt(29)","5"]','["2","4","sqrt(29)","5"]','["2","4","sqrt(29)","5"]','A','Mean=5. Variance=290/10-25=4, so SD=2.','Среднее 5. Дисперсия 29-25=4, значит SD=2.','O‘rtacha 5. Dispersiya 29-25=4, demak SD=2.',40),
('P5DAT09-L03','learning','hard','Values 1,2,3 have frequencies 2,3,1 respectively. Find the mean and standard deviation.','Значения 1,2,3 имеют частоты 2,3,1. Найдите среднее и стандартное отклонение.','1,2,3 qiymatlarning chastotalari mos ravishda 2,3,1. O‘rtacha va standart og‘ishni toping.','["mean 11/6, standard deviation sqrt(17)/6","mean 11/6, standard deviation 17/36","mean 2, standard deviation sqrt(17)/6","mean 11/6, standard deviation sqrt(23/6)"]','["среднее 11/6, стандартное отклонение sqrt(17)/6","среднее 11/6, стандартное отклонение 17/36","среднее 2, стандартное отклонение sqrt(17)/6","среднее 11/6, стандартное отклонение sqrt(23/6)"]','["o‘rtacha 11/6, standart og‘ish sqrt(17)/6","o‘rtacha 11/6, standart og‘ish 17/36","o‘rtacha 2, standart og‘ish sqrt(17)/6","o‘rtacha 11/6, standart og‘ish sqrt(23/6)"]','A','n=6, sum fx=11 and sum fx^2=23. Variance=23/6-(11/6)^2=17/36, so SD=sqrt(17)/6.','n=6, sum fx=11, sum fx^2=23. Дисперсия=17/36, поэтому SD=sqrt(17)/6.','n=6, sum fx=11, sum fx^2=23. Dispersiya=17/36, SD=sqrt(17)/6.',60),
('P5DAT09-R01','retest','medium','For n=4, sum x=20 and sum x^2=120. Find the mean and standard deviation.','Для n=4, sum x=20 и sum x^2=120. Найдите среднее и стандартное отклонение.','n=4, sum x=20 va sum x^2=120. O‘rtacha va standart og‘ishni toping.','["mean 5, standard deviation sqrt(5)","mean 5, standard deviation 5","mean 4, standard deviation sqrt(5)","mean 5, standard deviation sqrt(30)"]','["среднее 5, стандартное отклонение sqrt(5)","среднее 5, стандартное отклонение 5","среднее 4, стандартное отклонение sqrt(5)","среднее 5, стандартное отклонение sqrt(30)"]','["o‘rtacha 5, standart og‘ish sqrt(5)","o‘rtacha 5, standart og‘ish 5","o‘rtacha 4, standart og‘ish sqrt(5)","o‘rtacha 5, standart og‘ish sqrt(30)"]','A','Mean=5. Variance=120/4-25=5, so SD=sqrt(5).','Среднее 5. Дисперсия 30-25=5, SD=sqrt(5).','O‘rtacha 5. Dispersiya 30-25=5, SD=sqrt(5).',40),
('P5DAT09-R02','retest','easy','The data are 1,1,3,3. Find the standard deviation using division by n.','Данные 1,1,3,3. Найдите стандартное отклонение, деля на n.','Ma’lumotlar 1,1,3,3. n ga bo‘lib standart og‘ishni toping.','["1","2","sqrt(2)","0.5"]','["1","2","sqrt(2)","0,5"]','["1","2","sqrt(2)","0.5"]','A','Mean=2. Each deviation has magnitude 1, so variance=1 and SD=1.','Среднее 2. Все отклонения по модулю 1, поэтому дисперсия 1 и SD=1.','O‘rtacha 2. Har bir og‘ish moduli 1, dispersiya 1 va SD=1.',30),
('P5DAT09-M01','mixed','medium','For n=6, sum x=30 and sum x^2=174. Find the variance.','Для n=6, sum x=30 и sum x^2=174. Найдите дисперсию.','n=6, sum x=30 va sum x^2=174. Dispersiyani toping.','["4","2","29","25"]','["4","2","29","25"]','["4","2","29","25"]','A','Mean=5. Variance=174/6-25=29-25=4.','Среднее 5. Дисперсия=29-25=4.','O‘rtacha 5. Dispersiya=29-25=4.',35)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Summary Statistics','P5-DAT-09',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw21_24_dat09_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw21_24_dat09_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat09_v1' and status='draft'), keys(k,role) as (values('P5DAT09-D01','diagnostic'),('P5DAT09-L01','learning'),('P5DAT09-L02','learning'),('P5DAT09-L03','learning'),('P5DAT09-R01','retest'),('P5DAT09-R02','retest'),('P5DAT09-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DAT-09','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw21_24_dat09_v1 from canonical mean/standard-deviation skill intent.','Cambridge 9709 2026-2027 v4; P5 5.1 Representation of data','Complete Probability & Statistics 1; numerical summaries (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw21_24_dat09_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw21_24_dat09_v1' and m.content_key='P5DAT09-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','variance_not_square_rooted','method','6 is the variance. Standard deviation is the positive square root, sqrt(6).','6 — это дисперсия. Стандартное отклонение равно положительному корню sqrt(6).','6 dispersiya. Standart og‘ish musbat kvadrat ildiz, sqrt(6).','Keep variance and standard deviation as separate final quantities.','Разделяйте дисперсию и стандартное отклонение.','Dispersiya va standart og‘ishni alohida saqlang.'),
('C','mean_division_error','method','The mean is sum x/n=40/5=8, not 7.','Среднее равно 40/5=8, не 7.','O‘rtacha 40/5=8, 7 emas.','Compute mean before using the variance shortcut.','Сначала вычислите среднее, затем используйте формулу дисперсии.','Avval o‘rtachani toping, keyin dispersiya formulasini ishlating.'),
('D','omits_mean_square','concept','sqrt(70) uses only sum x^2/n and does not subtract mean^2. Spread is measured around the mean.','sqrt(70) использует только sum x^2/n и не вычитает mean^2. Разброс измеряется относительно среднего.','sqrt(70) faqat sum x^2/n ni oladi va mean^2 ni ayirmaydi. Tarqalish o‘rtacha atrofida o‘lchanadi.','Use variance = mean of x^2 minus square of mean.','Используйте variance = mean(x^2) - mean(x)^2.','variance = mean(x^2) - mean(x)^2 ni ishlating.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-DAT-09',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r cross join meta on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat09_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5DAT09-W01','P5','P5-DAT-09','wtv1','A dataset has n=8, sum x=96 and sum x^2=1224. Find the mean, variance and standard deviation. Then verify the same formulas on the frequency table x=1,2,4 with frequencies 2,3,3 by calculating n, sum fx and sum fx^2 first.','Набор имеет n=8, sum x=96 и sum x^2=1224. Найдите среднее, дисперсию и стандартное отклонение. Затем примените те же формулы к таблице x=1,2,4 с частотами 2,3,3, сначала вычислив n, sum fx и sum fx^2.','To‘plamda n=8, sum x=96, sum x^2=1224. O‘rtacha, dispersiya va standart og‘ishni toping. So‘ng x=1,2,4 va chastotalar 2,3,3 jadvalida n, sum fx va sum fx^2 ni hisoblab shu formulalarni qo‘llang.','{"max_marks":12,"criteria":[{"id":"summary_mean","marks":2,"rule":"Gets mean=12."},{"id":"summary_variance","marks":2,"rule":"Gets variance=1224/8-144=9."},{"id":"summary_sd","marks":1,"rule":"Gets SD=3."},{"id":"freq_totals","marks":3,"rule":"Gets n=8, sum fx=20, sum fx^2=62."},{"id":"freq_mean","marks":1,"rule":"Gets mean=2.5."},{"id":"freq_variance_sd","marks":3,"rule":"Gets variance=62/8-2.5^2=1.5 and SD=sqrt(1.5)."}]}','Build the three totals n, sum x and sum x^2 first; only then substitute into mean and variance formulas.','Сначала получите три итога n, sum x и sum x^2; затем подставляйте в формулы.','Avval n, sum x va sum x^2 uchta yig‘indini toping; keyin formulalarga qo‘ying.','published','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat09_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_dat09_diagnostic','diagnostic','P5 DAT-09 summary statistics diagnostic','Диагностика P5 DAT-09: среднее и стандартное отклонение','P5 DAT-09 summary statistika diagnostikasi'),('p5_dat09_learning','learning','Mean and standard deviation learning','Среднее и стандартное отклонение: обучение','O‘rtacha va standart og‘ish: o‘rganish'),('p5_dat09_retest','retest','DAT-09 delayed retest','DAT-09 отложенный ретест','DAT-09 kechiktirilgan retest'),('p5_dat09_mixed','mixed','DAT-09 mixed summary-statistics transfer','DAT-09 смешанный перенос','DAT-09 mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat09_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_dat09_diagnostic',1,'P5DAT09-D01',null,'diagnostic',true),('p5_dat09_learning',1,'P5DAT09-L01',null,'learning',false),('p5_dat09_learning',2,'P5DAT09-L02',null,'learning',false),('p5_dat09_learning',3,'P5DAT09-L03',null,'learning',false),('p5_dat09_learning',4,null,'P5DAT09-W01','written',false),('p5_dat09_retest',1,'P5DAT09-R01',null,'retest',true),('p5_dat09_retest',2,'P5DAT09-R02',null,'retest',true),('p5_dat09_mixed',1,'P5DAT09-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-DAT-09',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat09_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw21_24_dat09_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat09_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw21_24_dat09_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw21_24_dat09_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-DAT-09') then raise exception 'P5 DAT-09 not ready'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw21_24_dat09_v1:%' and is_active) then raise exception 'P5 DAT-09 legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P5 DAT-09 publication escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P5 DAT-09 active entitlement residue'; end if;
end $$;
commit;