-- AI-4 Economics Practice 1 topic-level source pack v1.
-- Original iClub summaries grounded in the approved Economics coursebook/topic map.
-- Broad fallback only: question_id/subtopic are intentionally NULL.
-- Exact misconception claims still require deterministic diagnosis; this migration
-- does not add diagnostic mappings, enable AI or create learner entitlements.

insert into private.practice_ai_source_cards(
  source_card_key,subject_key,question_id,topic,subtopic,card_type,locale,source_version,
  title,body_text,approval_status,rights_status,is_runtime_allowed,content_hash,approved_at,updated_at
)
values
('practice:economics:p1:topic:intro:en:v1','economics',null,'Intro',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Economic thinking','Economics studies how people, firms and governments make choices when resources are scarce. Positive statements can be tested against evidence, while normative statements depend on value judgements. Microeconomics focuses on individual consumers, firms and markets; macroeconomics looks at the economy as a whole.','approved','original_iclub',true,'a5e26f2285ad259c3b90853620339c1d757d8c43d5e79e87f464b0ca8509ba8b',now(),now()),
('practice:economics:p1:topic:intro:ru:v1','economics',null,'Intro',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Экономическое мышление','Экономика изучает, как люди, фирмы и государство делают выбор при ограниченных ресурсах. Позитивные утверждения можно проверять с помощью фактов, а нормативные зависят от оценочных суждений. Микроэкономика рассматривает отдельных потребителей, фирмы и рынки, а макроэкономика — экономику в целом.','approved','original_iclub',true,'e62220e7cb5371a056eb1eb324cc73fb7fb0b6098fc19c0896dac719ba52297b',now(),now()),
('practice:economics:p1:topic:intro:uz:v1','economics',null,'Intro',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Iqtisodiy fikrlash','Iqtisodiyot cheklangan resurslar sharoitida odamlar, firmalar va davlat qanday tanlov qilishini o‘rganadi. Pozitiv fikrlarni dalillar bilan tekshirish mumkin, normativ fikrlar esa qadriyat va baholashga bog‘liq. Mikroiqtisodiyot alohida iste’molchilar, firmalar va bozorlarni, makroiqtisodiyot esa butun iqtisodiyotni o‘rganadi.','approved','original_iclub',true,'5f8c4fa4443a7dd8d068c77c0a2ceac14a75cd3d5bcbf941762653c57ee9f8cd',now(),now()),
('practice:economics:p1:topic:basics:en:v1','economics',null,'Basics',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Scarcity, choice and factors of production','Scarcity means resources are limited compared with human wants, so choices have to be made. Opportunity cost is the next best alternative given up when a choice is made. The main factors of production are land, labour, capital and enterprise, rewarded by rent, wages, interest and profit.','approved','original_iclub',true,'ee79f93c4e7fdcf710f8d3ce7c729c8ef50d5c74df03dffa7de3fb4349f28996',now(),now()),
('practice:economics:p1:topic:basics:ru:v1','economics',null,'Basics',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Ограниченность, выбор и факторы производства','Ограниченность означает, что ресурсов недостаточно для удовлетворения всех человеческих потребностей, поэтому приходится делать выбор. Альтернативная стоимость — это лучшая из упущенных альтернатив. Основные факторы производства: земля, труд, капитал и предпринимательство; их доходы — рента, заработная плата, процент и прибыль.','approved','original_iclub',true,'a130f69efbfd072707fd521e0c772ca1eaaa50330a259ef2d141713c03c84171',now(),now()),
('practice:economics:p1:topic:basics:uz:v1','economics',null,'Basics',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Cheklanganlik, tanlov va ishlab chiqarish omillari','Cheklanganlik resurslar inson ehtiyojlariga nisbatan kamligini anglatadi, shuning uchun tanlov qilish kerak. Muqobil xarajat — tanlov qilinganda voz kechilgan eng yaxshi keyingi imkoniyat. Asosiy ishlab chiqarish omillari yer, mehnat, kapital va tadbirkorlik bo‘lib, ularning daromadlari renta, ish haqi, foiz va foydadir.','approved','original_iclub',true,'f13f83c7f68a6e2529b19562f18cdf02ce9ec3c6d67f1490afdf61da9d033395',now(),now()),
('practice:economics:p1:topic:systems:en:v1','economics',null,'Systems',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Economic systems and resource allocation','Every economy must decide what to produce, how to produce it and who receives the output. A market economy relies mainly on prices and private decisions, a planned economy relies mainly on central decisions, and a mixed economy combines market forces with government involvement.','approved','original_iclub',true,'260a959d41d0245bde1e63bb62ffa77a274ab193c97965b7776a124a8767b79e',now(),now()),
('practice:economics:p1:topic:systems:ru:v1','economics',null,'Systems',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Экономические системы и распределение ресурсов','Любая экономика должна решить, что производить, как производить и кто получит произведённые товары и услуги. Рыночная экономика в основном опирается на цены и частные решения, плановая — на централизованные решения, а смешанная сочетает рыночный механизм с участием государства.','approved','original_iclub',true,'bf5745e79f6c214b31a13a235017f190113732ae4b17102b832709010ba77190',now(),now()),
('practice:economics:p1:topic:systems:uz:v1','economics',null,'Systems',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Iqtisodiy tizimlar va resurslarni taqsimlash','Har bir iqtisodiyot nima ishlab chiqarish, qanday ishlab chiqarish va ishlab chiqarilgan mahsulot kimga tegishini hal qiladi. Bozor iqtisodiyoti asosan narxlar va xususiy qarorlarga, rejalashtirilgan iqtisodiyot markaziy qarorlarga tayanadi, aralash iqtisodiyot esa bozor mexanizmi bilan davlat ishtirokini birlashtiradi.','approved','original_iclub',true,'95d9ae922f10d42f092063a48caa3d3c4e44bffb918435b8885dceff6a8acd63',now(),now()),
('practice:economics:p1:topic:ppc:en:v1','economics',null,'PPC',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Production possibility curve','A production possibility curve shows the maximum attainable combinations of two outputs with current resources and technology. Points on the curve are productively efficient, points inside show unused or inefficiently used resources, and points outside are currently unattainable. Moving along the curve shows opportunity cost, while an outward shift shows greater productive capacity.','approved','original_iclub',true,'06591ab39cbc673251b77dd7560c15a2a7f66b17908d1e6c55b59cef73701918',now(),now()),
('practice:economics:p1:topic:ppc:ru:v1','economics',null,'PPC',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Кривая производственных возможностей','Кривая производственных возможностей показывает максимальные достижимые сочетания выпуска двух благ при имеющихся ресурсах и технологии. Точки на кривой означают производственную эффективность, точки внутри — неполное или неэффективное использование ресурсов, а точки за пределами кривой сейчас недостижимы. Движение по кривой показывает альтернативную стоимость, а сдвиг наружу — рост производственного потенциала.','approved','original_iclub',true,'146dc1f7858e58acae00e68173ac188ecc772979551067a278d41efbd9ffa9ec',now(),now()),
('practice:economics:p1:topic:ppc:uz:v1','economics',null,'PPC',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Ishlab chiqarish imkoniyatlari egri chizig‘i','Ishlab chiqarish imkoniyatlari egri chizig‘i mavjud resurslar va texnologiya bilan ikki mahsulotning erishish mumkin bo‘lgan maksimal kombinatsiyalarini ko‘rsatadi. Egri chiziq ustidagi nuqtalar ishlab chiqarish samaradorligini, ichkaridagi nuqtalar resurslardan to‘liq yoki samarali foydalanilmayotganini, tashqaridagi nuqtalar esa hozircha erishib bo‘lmasligini bildiradi. Egri chiziq bo‘ylab harakat muqobil xarajatni, tashqariga siljish esa ishlab chiqarish salohiyati oshganini ko‘rsatadi.','approved','original_iclub',true,'2ea921790a6957366043360be26bd62a217b202681603b2976e064d1f1099229',now(),now()),
('practice:economics:p1:topic:goods:en:v1','economics',null,'Goods',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Classification of goods','Economic goods use scarce resources and have an opportunity cost, while free goods are not scarce in the relevant situation. Private goods are excludable and rival in consumption. Pure public goods are non-excludable and non-rival. Merit goods tend to be under-consumed and demerit goods over-consumed when consumers have imperfect information about their benefits or costs.','approved','original_iclub',true,'581039f35b8b203b95a438614fb2502ef7427928e8c695a151190580fc50bbdf',now(),now()),
('practice:economics:p1:topic:goods:ru:v1','economics',null,'Goods',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Классификация благ','Экономические блага используют ограниченные ресурсы и имеют альтернативную стоимость, тогда как свободные блага в соответствующей ситуации не являются редкими. Частные блага исключаемы и конкурентны в потреблении. Чистые общественные блага неисключаемы и неконкурентны. Блага с положительным общественным эффектом могут потребляться недостаточно, а блага с отрицательным — чрезмерно, если потребители не полностью понимают их выгоды или издержки.','approved','original_iclub',true,'f08afa78b49e42f386921a38dbe2ef460671f1454e65a8bc352f876f89d8b0ad',now(),now()),
('practice:economics:p1:topic:goods:uz:v1','economics',null,'Goods',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Ne’matlarni tasniflash','Iqtisodiy ne’matlar cheklangan resurslardan foydalanadi va muqobil xarajatga ega, erkin ne’matlar esa tegishli holatda tanqis emas. Xususiy ne’matlarda boshqalarni foydalanishdan cheklash mumkin va iste’mol raqobatli bo‘ladi. Sof jamoat ne’matlari esa cheklab bo‘lmaydigan va raqobatsizdir. Ijobiy xususiyatlari to‘liq tushunilmagan foydali ne’matlar kam, zararli ne’matlar esa ortiqcha iste’mol qilinishi mumkin.','approved','original_iclub',true,'922ab3524b88debed7a8d38f5b85e80302dd05db149573824d56ceb509b1b9d1',now(),now()),
('practice:economics:p1:topic:demand:en:v1','economics',null,'Demand',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Demand and changes in demand','Demand shows the quantities consumers are willing and able to buy at different prices, other things equal. A change in the product’s own price causes a movement along the demand curve; a non-price determinant shifts the curve. Important determinants include income, tastes, expectations and the prices of substitutes and complements.','approved','original_iclub',true,'b2e7d438f3171f06b66ef5d4b9cb6e8a8c294bdf878f1957655ec62cda189cd6',now(),now()),
('practice:economics:p1:topic:demand:ru:v1','economics',null,'Demand',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Спрос и его изменения','Спрос показывает объёмы товара, которые потребители готовы и способны купить при разных ценах при прочих равных условиях. Изменение собственной цены товара вызывает движение вдоль кривой спроса, а изменение неценового фактора сдвигает всю кривую. К важным факторам относятся доход, вкусы, ожидания и цены заменителей и дополняющих товаров.','approved','original_iclub',true,'029f7dd4e08f94668732ccb6b0390131238d35829b38d3fc2490cabf394b2430',now(),now()),
('practice:economics:p1:topic:demand:uz:v1','economics',null,'Demand',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Talab va talabning o‘zgarishi','Talab boshqa omillar o‘zgarmagan holda iste’molchilar turli narxlarda qancha mahsulot sotib olishga tayyor va qodirligini ko‘rsatadi. Mahsulotning o‘z narxi o‘zgarsa talab egri chizig‘i bo‘ylab harakat yuz beradi, narxdan tashqari omil o‘zgarsa butun egri chiziq siljiydi. Muhim omillarga daromad, did, kutilmalar hamda o‘rinbosar va to‘ldiruvchi tovarlar narxlari kiradi.','approved','original_iclub',true,'0d7a5c78c6df152749c214d13764cc15a28be0cb9fe3357dd0b6c84d3dd1774d',now(),now()),
('practice:economics:p1:topic:supply:en:v1','economics',null,'Supply',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Supply and changes in supply','Supply shows the quantities producers are willing and able to offer at different prices, other things equal. A change in the product’s own price causes a movement along the supply curve; a non-price determinant shifts the curve. Production costs, productivity, taxes, subsidies, technology and expectations can change supply.','approved','original_iclub',true,'70be8fdb0ba790c70bc95ae127a6c43cb84cf9a77d0c2392d1fbedf61108c4bc',now(),now()),
('practice:economics:p1:topic:supply:ru:v1','economics',null,'Supply',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Предложение и его изменения','Предложение показывает объёмы товара, которые производители готовы и способны предложить при разных ценах при прочих равных условиях. Изменение собственной цены товара вызывает движение вдоль кривой предложения, а изменение неценового фактора сдвигает кривую. На предложение могут влиять производственные издержки, производительность, налоги, субсидии, технология и ожидания.','approved','original_iclub',true,'c71136fc8a97cbc94fb621b377469d6afe350dff3a03e39ff75b59698b8f6948',now(),now()),
('practice:economics:p1:topic:supply:uz:v1','economics',null,'Supply',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Taklif va taklifning o‘zgarishi','Taklif boshqa omillar o‘zgarmagan holda ishlab chiqaruvchilar turli narxlarda qancha mahsulot taklif qilishga tayyor va qodirligini ko‘rsatadi. Mahsulotning o‘z narxi o‘zgarsa taklif egri chizig‘i bo‘ylab harakat yuz beradi, narxdan tashqari omil o‘zgarsa egri chiziq siljiydi. Ishlab chiqarish xarajatlari, unumdorlik, soliqlar, subsidiyalar, texnologiya va kutilmalar taklifni o‘zgartirishi mumkin.','approved','original_iclub',true,'9be794f4362dc7efc2b7e20f3f2f592a2b4c7e278790538dfb7b09ee67fbe626',now(),now()),
('practice:economics:p1:topic:elasticity:en:v1','economics',null,'Elasticity',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Elasticity','Elasticity measures responsiveness using percentage changes. PED compares percentage change in quantity demanded with percentage change in price; PES compares percentage change in quantity supplied with percentage change in price. YED links demand to income and XED links demand for one good to the price of another. The size and, where relevant, the sign of the coefficient help interpret the relationship.','approved','original_iclub',true,'45e2dfe08782190db0cc6207759565a9f316c2437d62d2c2b62fe962c8b53e27',now(),now()),
('practice:economics:p1:topic:elasticity:ru:v1','economics',null,'Elasticity',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Эластичность','Эластичность измеряет чувствительность с помощью процентных изменений. PED сопоставляет процентное изменение объёма спроса с процентным изменением цены, а PES — процентное изменение объёма предложения с изменением цены. YED связывает спрос с доходом, XED — спрос на один товар с ценой другого. Для интерпретации важны величина коэффициента и, когда это имеет значение, его знак.','approved','original_iclub',true,'b77a4ba5576768a06df3971e0a791099f40064b5590c235e6f6c92aa27bb0714',now(),now()),
('practice:economics:p1:topic:elasticity:uz:v1','economics',null,'Elasticity',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Elastiklik','Elastiklik foizdagi o‘zgarishlar orqali ta’sirchanlikni o‘lchaydi. PED talab miqdorining foizdagi o‘zgarishini narxning foizdagi o‘zgarishi bilan, PES esa taklif miqdorining foizdagi o‘zgarishini narx o‘zgarishi bilan taqqoslaydi. YED talabni daromad bilan, XED esa bir tovar talabini boshqa tovar narxi bilan bog‘laydi. Koeffitsiyentning kattaligi va kerakli hollarda ishorasi munosabatni talqin qilishga yordam beradi.','approved','original_iclub',true,'f6192b168f11acb8283343b934c5c135aa69396923961758b502713684d89a88',now(),now()),
('practice:economics:p1:topic:equilibrium:en:v1','economics',null,'Equilibrium',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Market equilibrium','Market equilibrium occurs where quantity demanded equals quantity supplied. Excess demand creates upward pressure on price, while excess supply creates downward pressure, other things equal. Shifts in demand or supply change the equilibrium price, the equilibrium quantity, or both.','approved','original_iclub',true,'ee221ecbae25c1a7f5f7c8673c2235bea7401152f81c088b92cd35f794a74745',now(),now()),
('practice:economics:p1:topic:equilibrium:ru:v1','economics',null,'Equilibrium',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Рыночное равновесие','Рыночное равновесие возникает, когда объём спроса равен объёму предложения. Избыточный спрос при прочих равных создаёт давление на цену вверх, а избыточное предложение — вниз. Сдвиги спроса или предложения изменяют равновесную цену, равновесный объём или оба показателя.','approved','original_iclub',true,'8e070f8db6ffcc56e3597dcfe29ebf830715bbaec63751fb026f8bf589d02b2b',now(),now()),
('practice:economics:p1:topic:equilibrium:uz:v1','economics',null,'Equilibrium',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Bozor muvozanati','Bozor muvozanati talab miqdori taklif miqdoriga teng bo‘lganda yuz beradi. Boshqa shartlar o‘zgarmasa, ortiqcha talab narxni oshirishga, ortiqcha taklif esa narxni pasaytirishga bosim qiladi. Talab yoki taklif egri chizig‘ining siljishi muvozanat narxini, muvozanat miqdorini yoki ikkalasini ham o‘zgartiradi.','approved','original_iclub',true,'fab2cd92864ee60ae6a549a99431ef09a266ad33064ede6376bc3912bafeac77',now(),now()),
('practice:economics:p1:topic:market:en:v1','economics',null,'Market',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Market outcomes and surplus','Consumer surplus is the difference between what consumers are willing to pay and the market price; producer surplus is the difference between the price producers receive and the minimum they are willing to accept. Changes in price and quantity can change these surpluses. In a competitive framework, allocative efficiency is associated with the output where the value of the last unit to consumers matches its marginal cost.','approved','original_iclub',true,'a88e506a4779713e3e1e4243fd2eb6ce2007faccff21b0098d6c35f3613fb9e5',now(),now()),
('practice:economics:p1:topic:market:ru:v1','economics',null,'Market',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Рыночные результаты и излишек','Потребительский излишек — это разница между суммой, которую потребители готовы заплатить, и рыночной ценой; излишек производителя — разница между получаемой ценой и минимальной ценой, которую производитель готов принять. Изменения цены и объёма могут изменять эти излишки. В конкурентной модели аллокативная эффективность связана с выпуском, при котором ценность последней единицы для потребителей соответствует её предельным издержкам.','approved','original_iclub',true,'c3ebab42738938da13af54792dd27bf39b69ae191d450b7c1449af5501072841',now(),now()),
('practice:economics:p1:topic:market:uz:v1','economics',null,'Market',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Bozor natijalari va ortiqchalik','Iste’molchi ortiqchaligi iste’molchi to‘lashga tayyor bo‘lgan summa bilan bozor narxi o‘rtasidagi farqdir; ishlab chiqaruvchi ortiqchaligi esa olingan narx bilan ishlab chiqaruvchi qabul qilishga tayyor bo‘lgan eng past narx o‘rtasidagi farqdir. Narx va miqdor o‘zgarishi bu ortiqchaliklarni o‘zgartirishi mumkin. Raqobatli modelda allokativ samaradorlik oxirgi birlikning iste’molchi uchun qiymati uning chegaraviy xarajatiga teng bo‘lgan ishlab chiqarish hajmi bilan bog‘liq.','approved','original_iclub',true,'1fd8515bd8d7bc9f80d03c18c8a14389d8a259d7490eea522e1f9e64ef2e230d',now(),now()),
('practice:economics:p1:topic:costs:en:v1','economics',null,'Costs',null,'answer_explanation','en','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Fixed and variable costs','In the short run, fixed costs do not change when output changes, while variable costs change with the level of output. Total cost is the sum of total fixed cost and total variable cost. Average fixed cost falls as the same fixed cost is spread across more units of output.','approved','original_iclub',true,'4a7633a914231d7c6d4a1ebac107efeb9b64a825da4114d2348e8b5329caae05',now(),now()),
('practice:economics:p1:topic:costs:ru:v1','economics',null,'Costs',null,'answer_explanation','ru','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Постоянные и переменные издержки','В краткосрочном периоде постоянные издержки не меняются при изменении объёма выпуска, тогда как переменные издержки зависят от выпуска. Общие издержки равны сумме общих постоянных и общих переменных издержек. Средние постоянные издержки снижаются, когда одна и та же сумма постоянных издержек распределяется на большее число единиц продукции.','approved','original_iclub',true,'f11016af66c612d8873c853b43520dbc4b4840444293a561805c33842f3c0bf2',now(),now()),
('practice:economics:p1:topic:costs:uz:v1','economics',null,'Costs',null,'answer_explanation','uz','iclub_practice_ai_economics_p1_topic_v1_2026_09_25','Doimiy va o‘zgaruvchan xarajatlar','Qisqa muddatda doimiy xarajatlar ishlab chiqarish hajmi o‘zgarganda o‘zgarmaydi, o‘zgaruvchan xarajatlar esa ishlab chiqarish hajmiga bog‘liq. Umumiy xarajat jami doimiy va jami o‘zgaruvchan xarajatlar yig‘indisidir. Bir xil doimiy xarajat ko‘proq mahsulot birligiga taqsimlanganda o‘rtacha doimiy xarajat kamayadi.','approved','original_iclub',true,'a31a119e050bfd6e36fd4776899a9c37cc29f774e9d12af8aef4e97c5bd8f2db',now(),now())
on conflict(source_card_key) do update
set subject_key=excluded.subject_key,
    question_id=excluded.question_id,
    topic=excluded.topic,
    subtopic=excluded.subtopic,
    card_type=excluded.card_type,
    locale=excluded.locale,
    source_version=excluded.source_version,
    title=excluded.title,
    body_text=excluded.body_text,
    approval_status=excluded.approval_status,
    rights_status=excluded.rights_status,
    is_runtime_allowed=excluded.is_runtime_allowed,
    content_hash=excluded.content_hash,
    approved_at=coalesce(private.practice_ai_source_cards.approved_at,excluded.approved_at),
    updated_at=now();
