-- P1-02 P5 AW13-16: DRV-02 expectation.
-- Original iClub-authored content only; governed publication; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw13_16_drv02_v1','P5','P5 AW13-16 DRV-02 expectation','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.' from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0' on conflict(program_version_id,content_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv02_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5DRV02-D01','diagnostic','medium','X takes values 0,1,2 with probabilities 0.20,0.50,0.30. Find E(X).','X принимает значения 0,1,2 с вероятностями 0,20,0,50,0,30. Найдите E(X).','X 0,1,2 qiymatlarni 0.20,0.50,0.30 ehtimollar bilan oladi. E(X) ni toping.','["1.10","1.00","0.80","1.50"]','["1,10","1,00","0,80","1,50"]','["1.10","1.00","0.80","1.50"]','A','E(X)=0×0.20+1×0.50+2×0.30=1.10.','E(X)=0×0,20+1×0,50+2×0,30=1,10.','E(X)=0×0.20+1×0.50+2×0.30=1.10.',60),
('P5DRV02-L01','learning','easy','X takes values 1,2,3 with probabilities 0.25,0.50,0.25. Find E(X).','X принимает значения 1,2,3 с вероятностями 0,25,0,50,0,25. Найдите E(X).','X 1,2,3 qiymatlarni 0.25,0.50,0.25 ehtimollar bilan oladi. E(X) ni toping.','["2","1.5","2.5","6"]','["2","1,5","2,5","6"]','["2","1.5","2.5","6"]','A','E(X)=1(0.25)+2(0.50)+3(0.25)=2.','E(X)=1(0,25)+2(0,50)+3(0,25)=2.','E(X)=1(0.25)+2(0.50)+3(0.25)=2.',45),
('P5DRV02-L02','learning','medium','A game gives a gain of 4 units with probability 0.40 and a loss of 1 unit with probability 0.60. Find the expected gain.','Игра даёт выигрыш 4 единицы с вероятностью 0,40 и проигрыш 1 единицы с вероятностью 0,60. Найдите ожидаемый выигрыш.','O‘yin 0.40 ehtimol bilan 4 birlik foyda, 0.60 ehtimol bilan 1 birlik zarar beradi. Kutilgan foydani toping.','["1.0","2.2","1.6","−1.0"]','["1,0","2,2","1,6","−1,0"]','["1.0","2.2","1.6","−1.0"]','A','Treat the loss as −1: E=4(0.40)+(−1)(0.60)=1.00.','Проигрыш учитывается как −1: E=4(0,40)+(−1)(0,60)=1,00.','Zararni −1 deb olamiz: E=4(0.40)+(−1)(0.60)=1.00.',60),
('P5DRV02-L03','learning','medium','X takes values 0 and 2. If E(X)=1.6, find P(X=2).','X принимает значения 0 и 2. Если E(X)=1,6, найдите P(X=2).','X 0 va 2 qiymatlarni oladi. E(X)=1.6 bo‘lsa, P(X=2) ni toping.','["0.8","0.2","1.6","0.6"]','["0,8","0,2","1,6","0,6"]','["0.8","0.2","1.6","0.6"]','A','Let p=P(X=2). Then 2p=1.6, so p=0.8.','Пусть p=P(X=2). Тогда 2p=1,6, поэтому p=0,8.','p=P(X=2) bo‘lsin. 2p=1.6, demak p=0.8.',55),
('P5DRV02-R01','retest','easy','X takes values 1 and 4 with probabilities 0.70 and 0.30. Find E(X).','X принимает значения 1 и 4 с вероятностями 0,70 и 0,30. Найдите E(X).','X 1 va 4 qiymatlarni 0.70 va 0.30 ehtimollar bilan oladi. E(X) ni toping.','["1.9","2.5","1.2","5.0"]','["1,9","2,5","1,2","5,0"]','["1.9","2.5","1.2","5.0"]','A','E(X)=1(0.70)+4(0.30)=1.90.','E(X)=1(0,70)+4(0,30)=1,90.','E(X)=1(0.70)+4(0.30)=1.90.',40),
('P5DRV02-R02','retest','medium','X takes values −2 and 3 with probabilities 0.40 and 0.60. Find E(X).','X принимает значения −2 и 3 с вероятностями 0,40 и 0,60. Найдите E(X).','X −2 va 3 qiymatlarni 0.40 va 0.60 ehtimollar bilan oladi. E(X) ni toping.','["1.0","0.2","2.6","−1.0"]','["1,0","0,2","2,6","−1,0"]','["1.0","0.2","2.6","−1.0"]','A','E(X)=−2(0.40)+3(0.60)=1.00.','E(X)=−2(0,40)+3(0,60)=1,00.','E(X)=−2(0.40)+3(0.60)=1.00.',50),
('P5DRV02-M01','mixed','medium','A ticket wins 5 units with probability 0.20 and loses 1 unit otherwise. What is the expected net gain per ticket?','Билет приносит 5 единиц выигрыша с вероятностью 0,20 и теряет 1 единицу в остальных случаях. Каков ожидаемый чистый результат?','Bilet 0.20 ehtimol bilan 5 birlik yutuq, aks holda 1 birlik zarar beradi. Har bilet uchun kutilgan sof foyda?','["0.20","1.00","−0.20","4.00"]','["0,20","1,00","−0,20","4,00"]','["0.20","1.00","−0.20","4.00"]','A','E=5(0.20)+(−1)(0.80)=0.20.','E=5(0,20)+(−1)(0,80)=0,20.','E=5(0.20)+(−1)(0.80)=0.20.',55))
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Discrete Random Variables','P5-DRV-02',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw13_16_drv02_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_drv02_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv02_v1' and status='draft'), keys(k,role) as (values('P5DRV02-D01','diagnostic'),('P5DRV02-L01','learning'),('P5DRV02-L02','learning'),('P5DRV02-L03','learning'),('P5DRV02-R01','retest'),('P5DRV02-R02','retest'),('P5DRV02-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DRV-02','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw13_16_drv02_v1 from canonical DRV-02 intent.','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1; expectation (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_drv02_v1:'||k.k on conflict(content_version_id,content_key) do nothing;
with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw13_16_drv02_v1' and m.content_key='P5DRV02-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','unweighted_average','concept','Expectation is a probability-weighted average, not the ordinary average of possible values.','Ожидание — среднее, взвешенное вероятностями, а не обычное среднее возможных значений.','Kutilma ehtimollar bilan vaznlangan o‘rtacha, oddiy qiymatlar o‘rtachasi emas.','Compute each xP(X=x), then add.','Вычислите каждое xP(X=x), затем сложите.','Har bir xP(X=x) ni hisoblab, qo‘shing.'),
('C','wrong_weighting','method','The value 2 contributes 2×0.30=0.60, not merely 0.30.','Значение 2 даёт вклад 2×0,30=0,60, а не просто 0,30.','2 qiymatining hissasi 2×0.30=0.60, faqat 0.30 emas.','Multiply every value by its own probability.','Умножьте каждое значение на его вероятность.','Har bir qiymatni o‘z ehtimoliga ko‘paytiring.'),
('D','adds_probabilities','concept','Adding probabilities gives 1, but expectation also uses the values of X.','Сумма вероятностей равна 1, но ожидание использует и значения X.','Ehtimollar yig‘indisi 1, ammo kutilmada X qiymatlari ham ishlatiladi.','Use E(X)=Σxp(x), not Σp(x).','Используйте E(X)=Σxp(x), а не Σp(x).','E(X)=Σxp(x) ni ishlating, Σp(x) emas.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-DRV-02',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from meta cross join r on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv02_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5DRV02-W01','P5','P5-DRV-02','wtv1','A game has net outcomes −3, 2 and 7 units with probabilities 0.20, 0.50 and 0.30. Find the expectation, interpret it over many plays, and explain why it is not a guarantee for one play.','Игра имеет чистые результаты −3, 2 и 7 единиц с вероятностями 0,20, 0,50 и 0,30. Найдите ожидание, интерпретируйте его при многих играх и объясните, почему оно не гарантирует результат одной игры.','O‘yinning sof natijalari −3, 2 va 7, ehtimollar 0.20, 0.50 va 0.30. Kutilmani toping, ko‘p o‘yinlar uchun izohlang va nega bitta o‘yinni kafolatlamasligini ayting.','{"max_marks":10,"criteria":[{"id":"formula","marks":2,"rule":"Uses E(X)=Σxp(x)."},{"id":"calculation","marks":3,"rule":"Obtains 2.5."},{"id":"interpretation","marks":3,"rule":"Interprets +2.5 as long-run average net gain."},{"id":"single_play","marks":2,"rule":"Explains expectation is not a guaranteed realised outcome."}]}','Keep losses negative and distinguish long-run average from one outcome.','Сохраняйте знак минус у проигрышей и отличайте долгосрочное среднее от одного исхода.','Zararni manfiy saqlang va uzoq muddatli o‘rtachani bitta natijadan ajrating.','approved','pass','pass','pass','pass',now() from cv on conflict(content_version_id,task_key,task_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv02_v1' and status='draft'), defs(k,t,en,ru,uz) as (values('p5_drv02_diagnostic','diagnostic','DRV-02 diagnostic','Диагностика DRV-02','DRV-02 diagnostikasi'),('p5_drv02_learning','learning','DRV-02 learning','DRV-02 обучение','DRV-02 o‘rganish'),('p5_drv02_retest','retest','DRV-02 delayed retest','DRV-02 отложенный ретест','DRV-02 kechiktirilgan retest'),('p5_drv02_mixed','mixed','DRV-02 mixed transfer','DRV-02 смешанный перенос','DRV-02 mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz) select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv02_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values('p5_drv02_diagnostic',1,'P5DRV02-D01',null,'diagnostic',true),('p5_drv02_learning',1,'P5DRV02-L01',null,'learning',false),('p5_drv02_learning',2,'P5DRV02-L02',null,'learning',false),('p5_drv02_learning',3,'P5DRV02-L03',null,'learning',false),('p5_drv02_learning',4,null,'P5DRV02-W01','written',false),('p5_drv02_retest',1,'P5DRV02-R01',null,'retest',true),('p5_drv02_mixed',1,'P5DRV02-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout) select a.id,i.ord,m.question_id,w.id,'P5-DRV-02',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;
update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_drv02_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw13_16_drv02_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_drv02_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw13_16_drv02_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw13_16_drv02_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw13_16_drv02_v1' and status='approved';
do $$ declare v_program bigint; begin select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'; if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-DRV-02') then raise exception 'DRV-02 not ready after publish'; end if; if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw13_16_drv02_v1:%' and is_active) then raise exception 'legacy activation residue'; end if; if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if; if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if; end $$;
commit;
