-- P1-02 P5 AW17-20 Geometric pack: GEO-02/03.
-- Convention: X is the trial number of the first success (support 1,2,...).
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw17_20_geometric_v1','P5','P5 AW17-20 Geometric probabilities and expectation','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied. Geometric convention: X is trial number of first success.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw17_20_geometric_v1' and component_code='P5' and status='draft'), src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5-GEO-02','P5GEO02-D01','diagnostic','medium','X is geometric with success probability p=0.20, where X is the trial number of the first success. Find P(X=3).','X имеет геометрическое распределение с p=0,20, где X — номер испытания первого успеха. Найдите P(X=3).','X p=0.20 geometrik taqsimotga ega, X — birinchi muvaffaqiyat sinovi raqami. P(X=3) ni toping.','["0.128","0.032","0.512","0.200"]','["0,128","0,032","0,512","0,200"]','["0.128","0.032","0.512","0.200"]','A','For first success on trial 3: fail, fail, success, so P=0.8²(0.2)=0.128.','Для первого успеха в 3-м испытании: две неудачи, затем успех: 0,8²(0,2)=0,128.','3-sinovdagi birinchi muvaffaqiyat: ikki muvaffaqiyatsizlik, keyin muvaffaqiyat: 0.8²(0.2)=0.128.',50),
('P5-GEO-02','P5GEO02-L01','learning','medium','For geometric X with p=0.30, find P(X>4).','Для геометрического X с p=0,30 найдите P(X>4).','p=0.30 geometrik X uchun P(X>4) ni toping.','["0.2401","0.07203","0.7599","0.343"]','["0,2401","0,07203","0,7599","0,343"]','["0.2401","0.07203","0.7599","0.343"]','A','X>4 means the first four trials all fail: 0.7^4=0.2401.','X>4 означает неудачу в первых четырёх испытаниях: 0,7^4=0,2401.','X>4 dastlabki to‘rtta sinov muvaffaqiyatsiz: 0.7^4=0.2401.',45),
('P5-GEO-02','P5GEO02-L02','learning','medium','For geometric X with p=0.25, find P(X≤3).','Для геометрического X с p=0,25 найдите P(X≤3).','p=0.25 geometrik X uchun P(X≤3) ni toping.','["0.578125","0.421875","0.140625","0.75"]','["0,578125","0,421875","0,140625","0,75"]','["0.578125","0.421875","0.140625","0.75"]','A','P(X≤3)=1−P(X>3)=1−0.75^3=0.578125.','P(X≤3)=1−0,75^3=0,578125.','P(X≤3)=1−0.75^3=0.578125.',45),
('P5-GEO-02','P5GEO02-L03','learning','easy','For geometric X with p=0.40, find P(X=1).','Для геометрического X с p=0,40 найдите P(X=1).','p=0.40 geometrik X uchun P(X=1) ni toping.','["0.40","0.60","0.24","1.00"]','["0,40","0,60","0,24","1,00"]','["0.40","0.60","0.24","1.00"]','A','First success on trial 1 has probability p=0.40.','Первый успех в первом испытании имеет вероятность p=0,40.','Birinchi sinovdagi muvaffaqiyat ehtimoli p=0.40.',30),
('P5-GEO-02','P5GEO02-R01','retest','easy','For geometric X with p=0.50, find P(X=4).','Для геометрического X с p=0,50 найдите P(X=4).','p=0.50 geometrik X uchun P(X=4) ni toping.','["0.0625","0.125","0.25","0.9375"]','["0,0625","0,125","0,25","0,9375"]','["0.0625","0.125","0.25","0.9375"]','A','P(X=4)=0.5³(0.5)=0.0625.','P(X=4)=0,5^4=0,0625.','P(X=4)=0.5^4=0.0625.',35),
('P5-GEO-02','P5GEO02-R02','retest','medium','For geometric X with p=0.10, find P(X>2).','Для геометрического X с p=0,10 найдите P(X>2).','p=0.10 geometrik X uchun P(X>2) ni toping.','["0.81","0.19","0.09","0.729"]','["0,81","0,19","0,09","0,729"]','["0.81","0.19","0.09","0.729"]','A','X>2 means two initial failures: 0.9²=0.81.','X>2 означает две начальные неудачи: 0,9²=0,81.','X>2 ikki dastlabki muvaffaqiyatsizlik: 0.9²=0.81.',35),
('P5-GEO-02','P5GEO02-M01','mixed','hard','For geometric X with p=0.20, find P(3≤X≤5).','Для геометрического X с p=0,20 найдите P(3≤X≤5).','p=0.20 geometrik X uchun P(3≤X≤5) ni toping.','["0.31232","0.32768","0.64000","0.40960"]','["0,31232","0,32768","0,64000","0,40960"]','["0.31232","0.32768","0.64000","0.40960"]','A','P(3≤X≤5)=P(X≥3)−P(X≥6)=0.8²−0.8^5=0.31232.','P(3≤X≤5)=0,8²−0,8^5=0,31232.','P(3≤X≤5)=0.8²−0.8^5=0.31232.',60),

('P5-GEO-03','P5GEO03-D01','diagnostic','medium','For geometric X with p=0.25, find E(X).','Для геометрического X с p=0,25 найдите E(X).','p=0.25 geometrik X uchun E(X) ni toping.','["4","0.25","3","5"]','["4","0,25","3","5"]','["4","0.25","3","5"]','A','Under the trial-number convention, E(X)=1/p=4.','При соглашении о номере испытания E(X)=1/p=4.','Sinov-raqami kelishuvida E(X)=1/p=4.',35),
('P5-GEO-03','P5GEO03-L01','learning','easy','For geometric X with p=0.20, find E(X).','Для геометрического X с p=0,20 найдите E(X).','p=0.20 geometrik X uchun E(X) ni toping.','["5","4","0.2","6"]','["5","4","0,2","6"]','["5","4","0.2","6"]','A','E(X)=1/0.20=5.','E(X)=5.','E(X)=5.',30),
('P5-GEO-03','P5GEO03-L02','learning','medium','A geometric variable has E(X)=8. Find p.','Геометрическая случайная величина имеет E(X)=8. Найдите p.','Geometrik tasodifiy miqdor uchun E(X)=8. p ni toping.','["0.125","0.8","7/8","8"]','["0,125","0,8","7/8","8"]','["0.125","0.8","7/8","8"]','A','1/p=8, so p=1/8=0.125.','1/p=8, поэтому p=0,125.','1/p=8, demak p=0.125.',35),
('P5-GEO-03','P5GEO03-L03','learning','medium','A geometric variable has expected waiting time 2.5 trials. Find p.','У геометрической случайной величины ожидаемое время ожидания 2,5 испытания. Найдите p.','Geometrik tasodifiy miqdorning kutilgan kutish vaqti 2.5 sinov. p ni toping.','["0.4","0.25","0.6","2.5"]','["0,4","0,25","0,6","2,5"]','["0.4","0.25","0.6","2.5"]','A','p=1/E(X)=1/2.5=0.4.','p=1/2,5=0,4.','p=1/2.5=0.4.',35),
('P5-GEO-03','P5GEO03-R01','retest','easy','For geometric X with p=0.50, find E(X).','Для геометрического X с p=0,50 найдите E(X).','p=0.50 geometrik X uchun E(X) ni toping.','["2","1","0.5","3"]','["2","1","0,5","3"]','["2","1","0.5","3"]','A','E(X)=1/0.5=2.','E(X)=2.','E(X)=2.',30),
('P5-GEO-03','P5GEO03-R02','retest','medium','A geometric variable has E(X)=4. Find p.','Геометрическая случайная величина имеет E(X)=4. Найдите p.','Geometrik tasodifiy miqdor uchun E(X)=4. p ni toping.','["0.25","0.75","4","0.5"]','["0,25","0,75","4","0,5"]','["0.25","0.75","4","0.5"]','A','p=1/4=0.25.','p=0,25.','p=0.25.',30),
('P5-GEO-03','P5GEO03-M01','mixed','hard','For a geometric variable, P(X>3)=0.216. Find p and E(X).','Для геометрической случайной величины P(X>3)=0,216. Найдите p и E(X).','Geometrik tasodifiy miqdor uchun P(X>3)=0.216. p va E(X) ni toping.','["p=0.4, E(X)=2.5","p=0.6, E(X)=5/3","p=0.216, E(X)=4.63","p=0.8, E(X)=1.25"]','["p=0,4, E(X)=2,5","p=0,6, E(X)=5/3","p=0,216, E(X)=4,63","p=0,8, E(X)=1,25"]','["p=0.4, E(X)=2.5","p=0.6, E(X)=5/3","p=0.216, E(X)=4.63","p=0.8, E(X)=1.25"]','A','P(X>3)=q³=0.216=0.6³, so q=0.6, p=0.4 and E(X)=1/p=2.5.','P(X>3)=q³=0,216=0,6³, поэтому p=0,4 и E(X)=2,5.','P(X>3)=q³=0.216=0.6³, demak p=0.4 va E(X)=2.5.',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Geometric Distribution',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw17_20_geometric_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw17_20_geometric_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw17_20_geometric_v1' and status='draft'), keys(skill,k,role) as (values
('P5-GEO-02','P5GEO02-D01','diagnostic'),('P5-GEO-02','P5GEO02-L01','learning'),('P5-GEO-02','P5GEO02-L02','learning'),('P5-GEO-02','P5GEO02-L03','learning'),('P5-GEO-02','P5GEO02-R01','retest'),('P5-GEO-02','P5GEO02-R02','retest'),('P5-GEO-02','P5GEO02-M01','mixed'),
('P5-GEO-03','P5GEO03-D01','diagnostic'),('P5-GEO-03','P5GEO03-L01','learning'),('P5-GEO-03','P5GEO03-L02','learning'),('P5-GEO-03','P5GEO03-L03','learning'),('P5-GEO-03','P5GEO03-R01','retest'),('P5-GEO-03','P5GEO03-R02','retest'),('P5-GEO-03','P5GEO03-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw17_20_geometric_v1 under trial-number convention.','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1; Geometric distribution (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw17_20_geometric_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw17_20_geometric_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P5GEO02-D01','B','uses_success_cube','method','For X=3 there are two failures before the success, not three successes.','Для X=3 перед успехом две неудачи, а не три успеха.','X=3 da muvaffaqiyatdan oldin ikki muvaffaqiyatsizlik bor.','Use q^(x−1)p.','Используйте q^(x−1)p.','q^(x−1)p ni ishlating.'),
('P5GEO02-D01','C','omits_final_success','method','0.8³ is three failures; X=3 requires two failures then one success.','0,8³ — три неудачи; X=3 требует две неудачи и успех.','0.8³ uch muvaffaqiyatsizlik; X=3 ikki muvaffaqiyatsizlik va muvaffaqiyat.','Write the outcome sequence explicitly.','Запишите последовательность исходов.','Natijalar ketma-ketligini yozing.'),
('P5GEO02-D01','D','uses_p_only','concept','p alone is P(X=1); later first success also requires preceding failures.','p — это P(X=1); для более позднего успеха нужны предыдущие неудачи.','p faqat P(X=1); keyingi muvaffaqiyat uchun oldingi muvaffaqiyatsizliklar kerak.','Count failures before first success.','Посчитайте неудачи до первого успеха.','Birinchi muvaffaqiyatgacha muvaffaqiyatsizliklarni sanang.'),
('P5GEO03-D01','B','uses_p_as_mean','concept','p is the success probability, not the expected trial number.','p — вероятность успеха, а не ожидаемый номер испытания.','p muvaffaqiyat ehtimoli, kutilgan sinov raqami emas.','Use E(X)=1/p.','Используйте E(X)=1/p.','E(X)=1/p ni ishlating.'),
('P5GEO03-D01','C','counts_failures_convention','concept','3=(1−p)/p is the expected number of failures before success, not the trial-number convention used here.','3=(1−p)/p — ожидаемое число неудач до успеха, а не номер испытания в используемом соглашении.','3=(1−p)/p muvaffaqiyatgacha muvaffaqiyatsizliklar soni; bu yerda sinov-raqami kelishuvi ishlatiladi.','Check the definition of X: trial number of first success.','Проверьте определение X: номер испытания первого успеха.','X ta’rifini tekshiring: birinchi muvaffaqiyat sinovi raqami.'),
('P5GEO03-D01','D','off_by_one_expectation','method','For the trial-number convention the mean is exactly 1/p=4, not 1/p+1.','Для номера испытания среднее ровно 1/p=4, а не 1/p+1.','Sinov-raqami kelishuvida o‘rtacha aynan 1/p=4, 1/p+1 emas.','Use the stated convention consistently.','Последовательно используйте заданное соглашение.','Berilgan kelishuvni izchil ishlating.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw17_20_geometric_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P5GEO02-W01','P5-GEO-02','Let X be geometric with p=0.30 under the trial-number convention. Find P(X=4), P(X>5), P(X≤4), and P(2≤X≤4). Explain which events are easiest by complement.','Пусть X имеет геометрическое распределение с p=0,30 при соглашении о номере испытания. Найдите P(X=4), P(X>5), P(X≤4) и P(2≤X≤4). Объясните, где удобнее дополнение.','X p=0.30 geometrik bo‘lsin, sinov-raqami kelishuvida. P(X=4), P(X>5), P(X≤4) va P(2≤X≤4) ni toping. Qayerda to‘ldiruvchi qulayligini tushuntiring.','{"max_marks":11,"criteria":[{"id":"point","marks":2,"rule":"Gets P(X=4)=0.7^3(0.3)=0.1029."},{"id":"tail","marks":2,"rule":"Gets P(X>5)=0.7^5=0.16807."},{"id":"cumulative","marks":2,"rule":"Gets P(X≤4)=1−0.7^4=0.7599."},{"id":"interval","marks":3,"rule":"Gets P(2≤X≤4)=0.7−0.7^4=0.4599."},{"id":"method","marks":2,"rule":"Explains useful complement/tail identities."}]}','Translate each event into failures-before-success before calculating.','Переведите каждое событие в число неудач до успеха.','Har bir hodisani muvaffaqiyatgacha muvaffaqiyatsizliklar soniga aylantiring.'),
('P5GEO03-W01','P5-GEO-03','A geometric variable has expected trial number 5. Find p. Then find P(X>3) and P(X=4), and explain what E(X)=5 means in repeated independent experiments.','У геометрической случайной величины ожидаемый номер испытания равен 5. Найдите p. Затем найдите P(X>3), P(X=4) и объясните смысл E(X)=5 при многократном повторении.','Geometrik tasodifiy miqdorning kutilgan sinov raqami 5. p ni toping. Keyin P(X>3), P(X=4) ni topib, ko‘p takrorlashda E(X)=5 ma’nosini tushuntiring.','{"max_marks":10,"criteria":[{"id":"p","marks":2,"rule":"Gets p=0.2."},{"id":"tail","marks":2,"rule":"Gets P(X>3)=0.8^3=0.512."},{"id":"point","marks":2,"rule":"Gets P(X=4)=0.8^3(0.2)=0.1024."},{"id":"interpretation","marks":3,"rule":"Interprets 5 as long-run average trial number of first success, not a guarantee."},{"id":"convention","marks":1,"rule":"Uses trial-number convention consistently."}]}','Recover p from 1/p first, then use the same q=1−p for probabilities.','Сначала восстановите p из 1/p, затем используйте q=1−p.','Avval p ni 1/p dan toping, keyin q=1−p ni ishlating.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P5',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw17_20_geometric_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_aw17_geometric_diagnostic','diagnostic','P5 AW17-20 Geometric diagnostic','Диагностика P5 AW17–20: geometric','P5 AW17–20 geometrik diagnostikasi'),('p5_geo02_learning','learning','Geometric probabilities learning','Геометрические вероятности: обучение','Geometrik ehtimollar: o‘rganish'),('p5_geo03_learning','learning','Geometric expectation learning','Ожидание geometric: обучение','Geometrik kutilma: o‘rganish'),('p5_geo02_retest','retest','GEO-02 delayed retest','GEO-02 отложенный ретест','GEO-02 kechiktirilgan retest'),('p5_geo03_retest','retest','GEO-03 delayed retest','GEO-03 отложенный ретест','GEO-03 kechiktirilgan retest'),('p5_aw17_geometric_mixed','mixed','P5 AW17-20 Geometric mixed transfer','P5 AW17–20: смешанный перенос geometric','P5 AW17–20 geometrik mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw17_20_geometric_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p5_aw17_geometric_diagnostic',1,'P5GEO02-D01',null,'P5-GEO-02','diagnostic',true),('p5_aw17_geometric_diagnostic',2,'P5GEO03-D01',null,'P5-GEO-03','diagnostic',true),
('p5_geo02_learning',1,'P5GEO02-L01',null,'P5-GEO-02','learning',false),('p5_geo02_learning',2,'P5GEO02-L02',null,'P5-GEO-02','learning',false),('p5_geo02_learning',3,'P5GEO02-L03',null,'P5-GEO-02','learning',false),('p5_geo02_learning',4,null,'P5GEO02-W01','P5-GEO-02','written',false),
('p5_geo03_learning',1,'P5GEO03-L01',null,'P5-GEO-03','learning',false),('p5_geo03_learning',2,'P5GEO03-L02',null,'P5-GEO-03','learning',false),('p5_geo03_learning',3,'P5GEO03-L03',null,'P5-GEO-03','learning',false),('p5_geo03_learning',4,null,'P5GEO03-W01','P5-GEO-03','written',false),
('p5_geo02_retest',1,'P5GEO02-R01',null,'P5-GEO-02','retest',true),('p5_geo03_retest',1,'P5GEO03-R01',null,'P5-GEO-03','retest',true),
('p5_aw17_geometric_mixed',1,'P5GEO02-M01',null,'P5-GEO-02','mixed',true),('p5_aw17_geometric_mixed',2,'P5GEO03-M01',null,'P5-GEO-03','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw17_20_geometric_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw17_20_geometric_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw17_20_geometric_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw17_20_geometric_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw17_20_geometric_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw17_20_geometric_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P5-GEO-02','P5-GEO-03'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P5',v_skill) then raise exception 'Geometric skill not ready %',v_skill; end if; end loop;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw17_20_geometric_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
