-- P1-02 P5 AW21-24 DAT-10: coded totals and combining/splitting datasets.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw21_24_dat10_v1','P5','P5 AW21-24 DAT-10 coded and combined data','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat10_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5DAT10-D01','diagnostic','medium','Dataset A has 20 values with mean 12. Dataset B has 30 values with mean 18. Find the combined mean.','В наборе A 20 значений со средним 12. В наборе B 30 значений со средним 18. Найдите объединённое среднее.','A to‘plamda 20 qiymat, o‘rtacha 12. B da 30 qiymat, o‘rtacha 18. Birlashtirilgan o‘rtachani toping.','["15.6","15","18","12"]','["15,6","15","18","12"]','["15.6","15","18","12"]','A','Combined total is 20(12)+30(18)=780 across 50 values, so mean=780/50=15.6.','Общая сумма 20(12)+30(18)=780 для 50 значений, поэтому среднее 15,6.','Umumiy yig‘indi 20(12)+30(18)=780, 50 ta qiymat uchun o‘rtacha 15.6.',50),
('P5DAT10-L01','learning','easy','Ten observations have mean 4 and fifteen observations have mean 6. Find the combined mean.','У 10 наблюдений среднее 4, у 15 наблюдений среднее 6. Найдите объединённое среднее.','10 kuzatuv o‘rtachasi 4, 15 kuzatuv o‘rtachasi 6. Birlashtirilgan o‘rtachani toping.','["5.2","5","10","6"]','["5,2","5","10","6"]','["5.2","5","10","6"]','A','Combined total=10(4)+15(6)=130; divide by 25 to get 5.2.','Общая сумма 130; делим на 25 и получаем 5,2.','Umumiy yig‘indi 130; 25 ga bo‘lib 5.2.',35),
('P5DAT10-L02','learning','medium','A combined set of 40 values has mean 12. A subgroup of 15 values has mean 10. Find the mean of the remaining 25 values.','Объединённый набор из 40 значений имеет среднее 12. Подгруппа из 15 значений имеет среднее 10. Найдите среднее оставшихся 25 значений.','40 qiymatli umumiy to‘plam o‘rtachasi 12. 15 qiymatli guruh o‘rtachasi 10. Qolgan 25 qiymat o‘rtachasini toping.','["13.2","11","12","14"]','["13,2","11","12","14"]','["13.2","11","12","14"]','A','Overall total=480; subgroup total=150; remainder total=330, so mean=330/25=13.2.','Общая сумма 480, сумма подгруппы 150, остаток 330; 330/25=13,2.','Umumiy yig‘indi 480, guruh 150, qolgan 330; 330/25=13.2.',45),
('P5DAT10-L03','learning','medium','For 8 values define y=x-10. If sum y=12, find the mean of x.','Для 8 значений задано y=x-10. Если sum y=12, найдите среднее x.','8 qiymat uchun y=x-10. Agar sum y=12 bo‘lsa, x ning o‘rtachasini toping.','["11.5","12","10.5","92"]','["11,5","12","10,5","92"]','["11.5","12","10.5","92"]','A','x=y+10, so sum x=sum y+8(10)=92 and mean=92/8=11.5.','x=y+10, поэтому sum x=12+80=92 и среднее 11,5.','x=y+10, demak sum x=12+80=92 va o‘rtacha 11.5.',40),
('P5DAT10-R01','retest','easy','Five values have mean 8 and another five values have mean 12. Find the combined mean.','Пять значений имеют среднее 8, ещё пять — среднее 12. Найдите объединённое среднее.','5 qiymat o‘rtachasi 8, yana 5 qiymat o‘rtachasi 12. Birlashtirilgan o‘rtachani toping.','["10","20","8","12"]','["10","20","8","12"]','["10","20","8","12"]','A','Equal group sizes make the combined mean (8+12)/2=10.','При равных размерах групп объединённое среднее равно 10.','Guruhlar teng bo‘lsa, birlashtirilgan o‘rtacha 10.',25),
('P5DAT10-R02','retest','medium','For 4 values define y=(x-20)/5. If sum y=6, find the mean of x.','Для 4 значений y=(x-20)/5. Если sum y=6, найдите среднее x.','4 qiymat uchun y=(x-20)/5. Agar sum y=6 bo‘lsa, x o‘rtachasini toping.','["27.5","26","35","110"]','["27,5","26","35","110"]','["27.5","26","35","110"]','A','x=5y+20. Thus sum x=5(6)+4(20)=110 and mean=27.5.','x=5y+20. Поэтому sum x=110 и среднее 27,5.','x=5y+20. Demak sum x=110 va o‘rtacha 27.5.',40),
('P5DAT10-M01','mixed','hard','For 3 values define y=x-5. If sum y=6 and sum y^2=14, find sum x^2.','Для 3 значений y=x-5. Если sum y=6 и sum y^2=14, найдите sum x^2.','3 qiymat uchun y=x-5. Agar sum y=6 va sum y^2=14 bo‘lsa, sum x^2 ni toping.','["149","89","44","164"]','["149","89","44","164"]','["149","89","44","164"]','A','x=y+5, so x^2=y^2+10y+25. Summing gives 14+10(6)+25(3)=149.','x=y+5, поэтому x^2=y^2+10y+25. Сумма 14+60+75=149.','x=y+5, demak x^2=y^2+10y+25. Yig‘indi 14+60+75=149.',55)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Coded and Combined Data','P5-DAT-10',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw21_24_dat10_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw21_24_dat10_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat10_v1' and status='draft'), keys(k,role) as (values('P5DAT10-D01','diagnostic'),('P5DAT10-L01','learning'),('P5DAT10-L02','learning'),('P5DAT10-L03','learning'),('P5DAT10-R01','retest'),('P5DAT10-R02','retest'),('P5DAT10-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DAT-10','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw21_24_dat10_v1 from canonical coded/combined-data intent.','Cambridge 9709 2026-2027 v4; P5 5.1 Representation of data','Complete Probability & Statistics 1; coded and combined data (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw21_24_dat10_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw21_24_dat10_v1' and m.content_key='P5DAT10-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','averages_means_unweighted','concept','A simple average of 12 and 18 ignores that the groups have different sizes. The combined mean must weight each mean by its group size.','Простое среднее 12 и 18 игнорирует разные размеры групп. Нужно взвешивать по числу наблюдений.','12 va 18 ni oddiy o‘rtachalash guruh o‘lchamlarini e’tiborsiz qoldiradi. O‘rtachalarni guruh soniga ko‘ra og‘irlang.','Convert each group mean back to its total before combining.','Сначала восстановите сумму каждой группы из среднего и размера.','Har bir guruh o‘rtachasidan umumiy yig‘indini tiklang.'),
('C','uses_larger_group_mean_only','method','The larger group has more weight, but the smaller group still contributes to the combined total.','Большая группа имеет больший вес, но меньшая группа тоже входит в общую сумму.','Katta guruh ko‘proq og‘irlikka ega, lekin kichik guruh ham umumiy yig‘indiga kiradi.','Add both group totals and divide by total n.','Сложите суммы обеих групп и разделите на общее n.','Ikkala guruh yig‘indisini qo‘shib, umumiy n ga bo‘ling.'),
('D','uses_smaller_group_mean_only','method','The combined dataset contains all 50 observations, not only the 20 observations from A.','Объединённый набор содержит все 50 наблюдений, а не только 20 из A.','Birlashtirilgan to‘plamda A dagi 20 emas, barcha 50 kuzatuv bor.','Track both sample sizes explicitly.','Явно учитывайте оба размера выборок.','Ikkala guruh hajmini aniq hisobga oling.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-DAT-10',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r cross join meta on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat10_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5DAT10-W01','P5','P5-DAT-10','wtv1','Dataset A has n=4, sum x=20, sum x^2=120. Dataset B has n=6, sum x=42, sum x^2=310. Find the combined mean and standard deviation. Then, for a separate coded dataset with y=(x-50)/5, n=20, sum y=6 and sum y^2=32, recover sum x, mean x, sum x^2 and the standard deviation of x.','Набор A: n=4, sum x=20, sum x^2=120. Набор B: n=6, sum x=42, sum x^2=310. Найдите объединённые среднее и стандартное отклонение. Затем для отдельного кодированного набора y=(x-50)/5, n=20, sum y=6 и sum y^2=32 восстановите sum x, mean x, sum x^2 и стандартное отклонение x.','A to‘plam: n=4, sum x=20, sum x^2=120. B: n=6, sum x=42, sum x^2=310. Birlashtirilgan o‘rtacha va standart og‘ishni toping. So‘ng y=(x-50)/5, n=20, sum y=6, sum y^2=32 kodlangan to‘plam uchun sum x, mean x, sum x^2 va x standart og‘ishini tiklang.','{"max_marks":14,"criteria":[{"id":"combine_totals","marks":2,"rule":"Gets combined n=10, sum x=62, sum x^2=430."},{"id":"combine_mean","marks":2,"rule":"Gets mean=6.2."},{"id":"combine_sd","marks":3,"rule":"Gets variance=43-6.2^2=4.56 and SD=sqrt(4.56)."},{"id":"coded_sum_mean","marks":3,"rule":"Uses x=5y+50 to get sum x=1030 and mean=51.5."},{"id":"coded_squares","marks":2,"rule":"Gets sum x^2=25(32)+500(6)+2500(20)=53800."},{"id":"coded_sd","marks":2,"rule":"Gets variance=53800/20-51.5^2=37.75 and SD=sqrt(37.75)."}]}','For combining, add raw totals; for coding, algebraically invert the coding relation before transforming both first and second moments.','Для объединения складывайте исходные суммы; для кодирования сначала алгебраически выразите x через y и преобразуйте первую и вторую суммы.','Birlashtirishda xom yig‘indilarni qo‘shing; kodlashda avval x ni y orqali ifodalab, birinchi va ikkinchi momentlarni o‘zgartiring.','published','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat10_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_dat10_diagnostic','diagnostic','P5 DAT-10 coded and combined data diagnostic','Диагностика P5 DAT-10: кодированные и объединённые данные','P5 DAT-10 kodlangan va birlashtirilgan data diagnostikasi'),('p5_dat10_learning','learning','Coded and combined data learning','Кодированные и объединённые данные: обучение','Kodlangan va birlashtirilgan data: o‘rganish'),('p5_dat10_retest','retest','DAT-10 delayed retest','DAT-10 отложенный ретест','DAT-10 kechiktirilgan retest'),('p5_dat10_mixed','mixed','DAT-10 coded totals transfer','DAT-10 перенос кодированных сумм','DAT-10 kodlangan yig‘indilar transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_dat10_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_dat10_diagnostic',1,'P5DAT10-D01',null,'diagnostic',true),('p5_dat10_learning',1,'P5DAT10-L01',null,'learning',false),('p5_dat10_learning',2,'P5DAT10-L02',null,'learning',false),('p5_dat10_learning',3,'P5DAT10-L03',null,'learning',false),('p5_dat10_learning',4,null,'P5DAT10-W01','written',false),('p5_dat10_retest',1,'P5DAT10-R01',null,'retest',true),('p5_dat10_retest',2,'P5DAT10-R02',null,'retest',true),('p5_dat10_mixed',1,'P5DAT10-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-DAT-10',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat10_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw21_24_dat10_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_dat10_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw21_24_dat10_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw21_24_dat10_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-DAT-10') then raise exception 'P5 DAT-10 not ready'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw21_24_dat10_v1:%' and is_active) then raise exception 'P5 DAT-10 legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P5 DAT-10 publication escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P5 DAT-10 active entitlement residue'; end if;
end $$;
commit;