-- P1-02 original iClub content: P1-QUA-03 solving quadratics/method choice.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1QUA03-D01','diagnostic','medium','Solve 2x² − 7x + 3 = 0.','Решите 2x² − 7x + 3 = 0.','2x² − 7x + 3 = 0 tenglamani yeching.','["x = 3 or x = 1/2","x = −3 or x = −1/2","x = 1 or x = 3/2","x = −1 or x = 3"]','A','2x² − 7x + 3 = (2x − 1)(x − 3), so x = 1/2 or 3.','2x² − 7x + 3 = (2x − 1)(x − 3), поэтому x = 1/2 или 3.','2x² − 7x + 3 = (2x − 1)(x − 3), demak x = 1/2 yoki 3.',70),
('P1QUA03-L01','learning','easy','Solve x² − 9x + 20 = 0.','Решите x² − 9x + 20 = 0.','x² − 9x + 20 = 0 tenglamani yeching.','["x = 4 or 5","x = −4 or −5","x = 2 or 10","x = 1 or 20"]','A','x² − 9x + 20 = (x − 4)(x − 5), so x = 4 or 5.','x² − 9x + 20 = (x − 4)(x − 5), поэтому x = 4 или 5.','x² − 9x + 20 = (x − 4)(x − 5), demak x = 4 yoki 5.',55),
('P1QUA03-L02','learning','medium','Solve 3x² + 2x − 8 = 0.','Решите 3x² + 2x − 8 = 0.','3x² + 2x − 8 = 0 tenglamani yeching.','["x = 4/3 or −2","x = −4/3 or 2","x = 8/3 or −1","x = 2/3 or −4"]','A','Using the quadratic formula gives x = (−2 ± 10)/6, hence x = 4/3 or −2.','По формуле квадратного уравнения x = (−2 ± 10)/6, поэтому x = 4/3 или −2.','Kvadrat tenglama formulasi bo‘yicha x = (−2 ± 10)/6, demak x = 4/3 yoki −2.',70),
('P1QUA03-L03','learning','medium','Solve x² + 6x + 1 = 0.','Решите x² + 6x + 1 = 0.','x² + 6x + 1 = 0 tenglamani yeching.','["x = −3 ± 2√2","x = 3 ± 2√2","x = −6 ± √35","x = −3 ± √2"]','A','x = (−6 ± √32)/2 = −3 ± 2√2.','x = (−6 ± √32)/2 = −3 ± 2√2.','x = (−6 ± √32)/2 = −3 ± 2√2.',75),
('P1QUA03-R01','retest','medium','Solve 4x² − 12x + 5 = 0.','Решите 4x² − 12x + 5 = 0.','4x² − 12x + 5 = 0 tenglamani yeching.','["x = 1/2 or 5/2","x = −1/2 or −5/2","x = 1 or 5","x = 3/2 or 5/2"]','A','x = (12 ± 8)/8, so x = 1/2 or 5/2.','x = (12 ± 8)/8, поэтому x = 1/2 или 5/2.','x = (12 ± 8)/8, demak x = 1/2 yoki 5/2.',70),
('P1QUA03-R02','retest','easy','Solve x² − 5x − 14 = 0.','Решите x² − 5x − 14 = 0.','x² − 5x − 14 = 0 tenglamani yeching.','["x = 7 or −2","x = −7 or 2","x = 14 or −1","x = 5 or −14"]','A','x² − 5x − 14 = (x − 7)(x + 2), so x = 7 or −2.','x² − 5x − 14 = (x − 7)(x + 2), поэтому x = 7 или −2.','x² − 5x − 14 = (x − 7)(x + 2), demak x = 7 yoki −2.',60),
('P1QUA03-M01','mixed','medium','Solve x(x − 5) = 24.','Решите x(x − 5) = 24.','x(x − 5) = 24 tenglamani yeching.','["x = 8 or −3","x = −8 or 3","x = 6 or −4","x = 3 or −8"]','A','Rearrange to x² − 5x − 24 = 0 = (x − 8)(x + 3), so x = 8 or −3.','После переноса получаем x² − 5x − 24 = 0 = (x − 8)(x + 3), поэтому x = 8 или −3.','Bir tomonga o‘tkazsak x² − 5x − 24 = 0 = (x − 8)(x + 3), demak x = 8 yoki −3.',75)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Quadratics','P1-QUA-03',s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_foundations_runway_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
keys(k,role) as (values('P1QUA03-D01','diagnostic'),('P1QUA03-L01','learning'),('P1QUA03-L02','learning'),('P1QUA03-L03','learning'),('P1QUA03-R01','retest'),('P1QUA03-R02','retest'),('P1QUA03-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-QUA-03','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, numbers, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored for p1_foundations_runway_v1 from canonical P1-QUA-03 intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.1 Quadratics','Complete Pure Mathematics 1, Ch1 Quadratics pp.2-20 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
commit;
