-- P1-02 original iClub content: P1-FUN-02 range under domain restriction.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1FUN02-D01','diagnostic','medium','For f(x) = x² + 1 with −2 ≤ x ≤ 3, what is the range of f?','Для f(x) = x² + 1 при −2 ≤ x ≤ 3 найдите область значений f.','f(x) = x² + 1 va −2 ≤ x ≤ 3 bo‘lsa, f ning qiymatlar sohasini toping.','["1 ≤ f(x) ≤ 10","2 ≤ f(x) ≤ 10","1 ≤ f(x) ≤ 5","−3 ≤ f(x) ≤ 4"]','A','The minimum occurs at x = 0: f = 1. The largest endpoint value is f(3) = 10, so the range is [1, 10].','Минимум при x = 0: f = 1. Наибольшее значение на концах f(3) = 10, поэтому область значений [1, 10].','Minimum x = 0 da: f = 1. Chegaralardagi eng katta qiymat f(3) = 10, demak qiymatlar sohasi [1, 10].',75),
('P1FUN02-L01','learning','easy','For f(x) = 2x − 5 with 1 ≤ x ≤ 4, what is the range?','Для f(x) = 2x − 5 при 1 ≤ x ≤ 4 найдите область значений.','f(x) = 2x − 5 va 1 ≤ x ≤ 4 bo‘lsa, qiymatlar sohasini toping.','["−3 ≤ f(x) ≤ 3","−5 ≤ f(x) ≤ 8","1 ≤ f(x) ≤ 4","−3 < f(x) < 3"]','A','The function is increasing. f(1) = −3 and f(4) = 3, and both endpoints are included.','Функция возрастает. f(1) = −3 и f(4) = 3, причём обе границы включены.','Funksiya o‘suvchi. f(1) = −3 va f(4) = 3, ikkala chegara ham kiradi.',55),
('P1FUN02-L02','learning','medium','For f(x) = (x − 2)² with 0 ≤ x ≤ 5, what is the range?','Для f(x) = (x − 2)² при 0 ≤ x ≤ 5 найдите область значений.','f(x) = (x − 2)² va 0 ≤ x ≤ 5 bo‘lsa, qiymatlar sohasini toping.','["0 ≤ f(x) ≤ 9","0 ≤ f(x) ≤ 4","4 ≤ f(x) ≤ 9","−2 ≤ f(x) ≤ 5"]','A','The minimum 0 occurs at x = 2. Endpoint values are 4 and 9, so the maximum is 9.','Минимум 0 достигается при x = 2. Значения на концах равны 4 и 9, поэтому максимум 9.','Minimum 0 x = 2 da. Chegara qiymatlari 4 va 9, shuning uchun maksimum 9.',65),
('P1FUN02-L03','learning','medium','For f(x) = −x² + 4 with −1 ≤ x ≤ 2, what is the range?','Для f(x) = −x² + 4 при −1 ≤ x ≤ 2 найдите область значений.','f(x) = −x² + 4 va −1 ≤ x ≤ 2 bo‘lsa, qiymatlar sohasini toping.','["0 ≤ f(x) ≤ 4","−4 ≤ f(x) ≤ 4","3 ≤ f(x) ≤ 4","0 < f(x) < 4"]','A','The maximum is f(0) = 4. The minimum on the interval is f(2) = 0, so the range is [0, 4].','Максимум f(0) = 4. Минимум на интервале f(2) = 0, поэтому область значений [0, 4].','Maksimum f(0) = 4. Intervaldagi minimum f(2) = 0, demak qiymatlar sohasi [0, 4].',65),
('P1FUN02-R01','retest','medium','For f(x) = x² − 4x + 7 with 1 ≤ x ≤ 5, what is the range?','Для f(x) = x² − 4x + 7 при 1 ≤ x ≤ 5 найдите область значений.','f(x) = x² − 4x + 7 va 1 ≤ x ≤ 5 bo‘lsa, qiymatlar sohasini toping.','["3 ≤ f(x) ≤ 12","1 ≤ f(x) ≤ 12","3 ≤ f(x) ≤ 7","−1 ≤ f(x) ≤ 12"]','A','f(x) = (x − 2)² + 3. The minimum is 3 at x = 2; the largest endpoint value is f(5) = 12.','f(x) = (x − 2)² + 3. Минимум 3 при x = 2; наибольшее значение на концах f(5) = 12.','f(x) = (x − 2)² + 3. Minimum x = 2 da 3; chekkalardagi eng katta qiymat f(5) = 12.',70),
('P1FUN02-R02','retest','hard','For f(x) = 1 − 2x with −3 < x ≤ 2, what is the range?','Для f(x) = 1 − 2x при −3 < x ≤ 2 найдите область значений.','f(x) = 1 − 2x va −3 < x ≤ 2 bo‘lsa, qiymatlar sohasini toping.','["−3 ≤ f(x) < 7","−3 < f(x) ≤ 7","−3 ≤ f(x) ≤ 7","−5 < f(x) ≤ 5"]','A','f is decreasing. At x = 2, f = −3 and this endpoint is included. As x approaches −3 from above, f approaches 7 but never reaches it.','f убывает. При x = 2 получаем f = −3, и эта граница включена. При x → −3 справа f → 7, но 7 не достигается.','f kamayuvchi. x = 2 da f = −3 va bu chegara kiradi. x −3 ga o‘ngdan yaqinlashganda f 7 ga yaqinlashadi, lekin 7 ga teng bo‘lmaydi.',80),
('P1FUN02-M01','mixed','medium','For f(x) = (x + 1)² with −4 ≤ x ≤ 1, what is the range?','Для f(x) = (x + 1)² при −4 ≤ x ≤ 1 найдите область значений.','f(x) = (x + 1)² va −4 ≤ x ≤ 1 bo‘lsa, qiymatlar sohasini toping.','["0 ≤ f(x) ≤ 9","1 ≤ f(x) ≤ 9","0 ≤ f(x) ≤ 4","−4 ≤ f(x) ≤ 1"]','A','The minimum is 0 at x = −1. Endpoint values are 9 and 4, so the maximum is 9.','Минимум 0 достигается при x = −1. Значения на концах 9 и 4, поэтому максимум 9.','Minimum x = −1 da 0. Chegara qiymatlari 9 va 4, shuning uchun maksimum 9.',70)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Functions','P1-FUN-02',s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_foundations_runway_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
keys(k,role) as (values('P1FUN02-D01','diagnostic'),('P1FUN02-L01','learning'),('P1FUN02-L02','learning'),('P1FUN02-L03','learning'),('P1FUN02-R01','retest'),('P1FUN02-R02','retest'),('P1FUN02-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-FUN-02','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, numbers, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored for p1_foundations_runway_v1 from canonical P1-FUN-02 intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.2 Functions','Complete Pure Mathematics 1, Ch2 Functions and transformations pp.24-42 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
commit;
