-- P1-02 E2 original content: P1-COO-03 parallel/perpendicular gradient conditions.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1COO03-D01','diagnostic','medium','A line has gradient 3/2. What is the gradient of a line perpendicular to it?','Прямая имеет градиент 3/2. Каков градиент перпендикулярной ей прямой?','Chiziq gradienti 3/2. Unga perpendikulyar chiziq gradienti qanday?','["−2/3","2/3","−3/2","3/2"]','["−2/3","2/3","−3/2","3/2"]','["−2/3","2/3","−3/2","3/2"]','A','Perpendicular non-vertical gradients satisfy m₁m₂=−1, so m₂=−2/3.','Для перпендикулярных непараллельных осям прямых m₁m₂=−1, поэтому m₂=−2/3.','Perpendikulyar chiziqlar uchun m₁m₂=−1, demak m₂=−2/3.',55),
('P1COO03-L01','learning','easy','Which line is parallel to y=−4x+7?','Какая прямая параллельна y=−4x+7?','Qaysi chiziq y=−4x+7 ga parallel?','["y=4x−2","y=−4x−1","y=x−4","y=−x+7"]','["y=4x−2","y=−4x−1","y=x−4","y=−x+7"]','["y=4x−2","y=−4x−1","y=x−4","y=−x+7"]','B','Parallel lines have equal gradients. Both lines have gradient −4.','Параллельные прямые имеют одинаковые градиенты. Здесь оба градиента равны −4.','Parallel chiziqlarning gradientlari teng. Bu yerda ikkalasi −4.',45),
('P1COO03-L02','learning','medium','The line L has equation 2y=x+6. Which gradient belongs to a line perpendicular to L?','Прямая L задана уравнением 2y=x+6. Какой градиент имеет перпендикулярная ей прямая?','L chiziq 2y=x+6 tenglama bilan berilgan. Unga perpendikulyar chiziq gradienti qaysi?','["2","−2","1/2","−1/2"]','["2","−2","1/2","−1/2"]','["2","−2","1/2","−1/2"]','B','Rearrange to y=(1/2)x+3, so the perpendicular gradient is −2.','Преобразуем: y=(1/2)x+3, поэтому перпендикулярный градиент равен −2.','y=(1/2)x+3 ko‘rinishga keltiramiz; perpendikulyar gradient −2.',60),
('P1COO03-L03','learning','medium','Line A passes through (1,2) and (5,10). Line B passes through (−2,3) and (0,7). What is the relationship between A and B?','Прямая A проходит через (1,2) и (5,10), а B — через (−2,3) и (0,7). Как связаны эти прямые?','A chiziq (1,2) va (5,10), B chiziq esa (−2,3) va (0,7) orqali o‘tadi. Ular qanday bog‘langan?','["parallel","perpendicular","same line","neither parallel nor perpendicular"]','["параллельны","перпендикулярны","совпадают","ни параллельны, ни перпендикулярны"]','["parallel","perpendikulyar","bir xil chiziq","na parallel, na perpendikulyar"]','A','Both gradients equal 2, but the lines have different intercepts, so they are parallel.','Оба градиента равны 2, но свободные члены различны, поэтому прямые параллельны.','Ikkala gradient ham 2, lekin kesishish hadlari turli; demak ular parallel.',70),
('P1COO03-R01','retest','easy','A line has gradient −5. What gradient must a parallel line have?','Прямая имеет градиент −5. Какой градиент должна иметь параллельная прямая?','Chiziq gradienti −5. Parallel chiziq gradienti qanday bo‘lishi kerak?','["5","−5","1/5","−1/5"]','["5","−5","1/5","−1/5"]','["5","−5","1/5","−1/5"]','B','Parallel lines have equal gradients, so the gradient is −5.','У параллельных прямых одинаковый градиент: −5.','Parallel chiziqlarning gradienti teng: −5.',40),
('P1COO03-R02','retest','medium','Which equation is perpendicular to y=2x−3?','Какая прямая перпендикулярна y=2x−3?','Qaysi tenglama y=2x−3 ga perpendikulyar chiziqni beradi?','["y=−2x+1","y=(1/2)x+1","y=−(1/2)x+1","y=2x+1"]','["y=−2x+1","y=(1/2)x+1","y=−(1/2)x+1","y=2x+1"]','["y=−2x+1","y=(1/2)x+1","y=−(1/2)x+1","y=2x+1"]','C','The negative reciprocal of 2 is −1/2.','Отрицательная обратная величина к 2 равна −1/2.','2 ning manfiy teskari qiymati −1/2.',50),
('P1COO03-M01','mixed','hard','A line through P(2,5) is perpendicular to the line through A(−1,1) and B(3,3). Which equation represents the line through P?','Прямая через P(2,5) перпендикулярна прямой через A(−1,1) и B(3,3). Какое уравнение задаёт прямую через P?','P(2,5) orqali o‘tuvchi chiziq A(−1,1) va B(3,3) orqali o‘tuvchi chiziqqa perpendikulyar. P orqali o‘tuvchi chiziq tenglamasi qaysi?','["y=−2x+9","y=2x+1","y=−(1/2)x+6","y=(1/2)x+4"]','["y=−2x+9","y=2x+1","y=−(1/2)x+6","y=(1/2)x+4"]','["y=−2x+9","y=2x+1","y=−(1/2)x+6","y=(1/2)x+4"]','A','AB has gradient (3−1)/(3−(−1))=1/2. A perpendicular gradient is −2. Through P: y−5=−2(x−2), hence y=−2x+9.','У AB градиент 1/2, значит перпендикулярный градиент −2. Через P: y−5=−2(x−2), откуда y=−2x+9.','AB gradienti 1/2, demak perpendikulyar gradient −2. P orqali: y−5=−2(x−2), shundan y=−2x+9.',85)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Coordinate geometry','P1-COO-03',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and status='draft'),
keys(k,role) as (values('P1COO03-D01','diagnostic'),('P1COO03-L01','learning'),('P1COO03-L02','learning'),('P1COO03-L03','learning'),('P1COO03-R01','retest'),('P1COO03-R02','retest'),('P1COO03-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-COO-03','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored from canonical parallel/perpendicular gradient reasoning using independent coordinates.','Cambridge 9709 2026-2027 v4; P1 1.3 Coordinate geometry','Complete Pure Mathematics 1, Ch3 Coordinate geometry pp.48-67 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
do $$ declare v_id bigint; begin select id into v_id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1'; if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code='P1-COO-03')<>7 then raise exception 'P1-02 COO-03 expected 7 question objects'; end if; end $$;
commit;
