-- P1-02 E2 original content: P1-TRI-01 sine/cosine/tangent graphs and simple transformations.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1TRI01-D01','diagnostic','medium','Which statement is true for y=sin x on 0≤x≤2π?','Какое утверждение верно для y=sin x на 0≤x≤2π?','0≤x≤2π da y=sin x uchun qaysi tasdiq to‘g‘ri?','["The maximum is 1 at x=π/2","The maximum is 1 at x=π","The minimum is −1 at x=π","The period is π"]','["Максимум 1 при x=π/2","Максимум 1 при x=π","Минимум −1 при x=π","Период равен π"]','["Maksimum 1, x=π/2 da","Maksimum 1, x=π da","Minimum −1, x=π da","Davr π"]','A','The standard sine graph reaches 1 at π/2, 0 at π, −1 at 3π/2, and has period 2π.','Стандартный график sin x достигает 1 при π/2, 0 при π, −1 при 3π/2 и имеет период 2π.','Standart sin x grafigi π/2 da 1, π da 0, 3π/2 da −1 ga ega va davri 2π.',55),
('P1TRI01-L01','learning','easy','What is the period of y=cos x?','Каков период y=cos x?','y=cos x funksiyaning davri qancha?','["π/2","π","2π","4π"]','["π/2","π","2π","4π"]','["π/2","π","2π","4π"]','C','The cosine graph repeats every 2π radians.','График косинуса повторяется каждые 2π радиан.','Kosinus grafigi har 2π radianda takrorlanadi.',35),
('P1TRI01-L02','learning','medium','The graph y=2sin x has which maximum and minimum values?','Каковы максимальное и минимальное значения графика y=2sin x?','y=2sin x grafigining maksimum va minimum qiymatlari qanday?','["maximum 1, minimum −1","maximum 2, minimum −2","maximum 2, minimum 0","maximum 1, minimum −2"]','["максимум 1, минимум −1","максимум 2, минимум −2","максимум 2, минимум 0","максимум 1, минимум −2"]','["maksimum 1, minimum −1","maksimum 2, minimum −2","maksimum 2, minimum 0","maksimum 1, minimum −2"]','B','Multiplying sin x by 2 doubles all y-values, so the range is [−2,2].','Умножение sin x на 2 удваивает все y-значения, поэтому диапазон [−2,2].','sin x ni 2 ga ko‘paytirish barcha y qiymatlarni ikki baravar qiladi; oraliq [−2,2].',45),
('P1TRI01-L03','learning','medium','Which graph is obtained from y=cos x by translating it upward by 3 units?','Какой график получается из y=cos x сдвигом вверх на 3 единицы?','y=cos x grafigini 3 birlik yuqoriga siljitganda qaysi grafik hosil bo‘ladi?','["y=cos(x+3)","y=3cos x","y=cos x+3","y=cos(x−3)"]','["y=cos(x+3)","y=3cos x","y=cos x+3","y=cos(x−3)"]','["y=cos(x+3)","y=3cos x","y=cos x+3","y=cos(x−3)"]','C','An outside +3 adds 3 to every output value, so the graph moves upward by 3.','Внешнее +3 добавляет 3 к каждому значению функции, сдвигая график вверх.','Tashqaridagi +3 har bir chiqish qiymatiga 3 qo‘shadi, grafik 3 birlik yuqoriga siljiydi.',45),
('P1TRI01-R01','retest','easy','Where does y=tan x have a vertical asymptote in 0<x<π?','Где y=tan x имеет вертикальную асимптоту при 0<x<π?','0<x<π da y=tan x qayerda vertikal asimptotaga ega?','["x=π/4","x=π/2","x=3π/4","x=π"]','["x=π/4","x=π/2","x=3π/4","x=π"]','["x=π/4","x=π/2","x=3π/4","x=π"]','B','tan x=sin x/cos x is undefined when cos x=0, so x=π/2.','tan x=sin x/cos x не определён при cos x=0, то есть x=π/2.','tan x=sin x/cos x, cos x=0 bo‘lganda aniqlanmagan; x=π/2.',45),
('P1TRI01-R02','retest','medium','What is the range of y=3cos x−1?','Какова область значений y=3cos x−1?','y=3cos x−1 funksiyaning qiymatlar sohasi qanday?','["−3≤y≤3","−4≤y≤2","−2≤y≤4","−1≤y≤3"]','["−3≤y≤3","−4≤y≤2","−2≤y≤4","−1≤y≤3"]','["−3≤y≤3","−4≤y≤2","−2≤y≤4","−1≤y≤3"]','B','Since −1≤cos x≤1, multiplying by 3 gives [−3,3], then subtracting 1 gives [−4,2].','Так как −1≤cos x≤1, после умножения на 3 получаем [−3,3], а после вычитания 1 — [−4,2].','−1≤cos x≤1, 3 ga ko‘paytirib [−3,3], keyin 1 ayirsak [−4,2].',55),
('P1TRI01-M01','mixed','hard','For y=−2sin x+1, what are the maximum value, minimum value and midline?','Для y=−2sin x+1 найдите максимум, минимум и среднюю линию.','y=−2sin x+1 uchun maksimum, minimum va o‘rta chiziqni toping.','["max 3, min −1, midline y=1","max 2, min −2, midline y=0","max 1, min −3, midline y=−1","max 3, min −2, midline y=1"]','["max 3, min −1, средняя линия y=1","max 2, min −2, средняя линия y=0","max 1, min −3, средняя линия y=−1","max 3, min −2, средняя линия y=1"]','["max 3, min −1, o‘rta chiziq y=1","max 2, min −2, o‘rta chiziq y=0","max 1, min −3, o‘rta chiziq y=−1","max 3, min −2, o‘rta chiziq y=1"]','A','−2sin x ranges from −2 to 2; adding 1 gives [−1,3]. The vertical shift sets the midline y=1.','−2sin x принимает значения от −2 до 2; после +1 получаем [−1,3]. Средняя линия y=1.','−2sin x [−2,2] oralig‘ida; +1 dan keyin [−1,3]. O‘rta chiziq y=1.',75)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Trigonometry','P1-TRI-01',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1' and status='draft'),
keys(k,role) as (values('P1TRI01-D01','diagnostic'),('P1TRI01-L01','learning'),('P1TRI01-L02','learning'),('P1TRI01-L03','learning'),('P1TRI01-R01','retest'),('P1TRI01-R02','retest'),('P1TRI01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-TRI-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored from canonical trigonometric graph features and simple transformations using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.5 Trigonometry','Complete Pure Mathematics 1, Ch5 Trigonometry pp.86-104 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_e2_coordinate_circular_trig_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
do $$ declare v_id bigint; begin select id into v_id from private.exam_prep_content_versions where content_version='p1_e2_coordinate_circular_trig_v1'; if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code='P1-TRI-01')<>7 then raise exception 'P1-02 TRI-01 expected 7 question objects'; end if; end $$;
commit;
