-- P1-02 P1 AW13-16 Circular + Trigonometry pack: CIR-03, TRI-02/03/04/05.
-- Original iClub-authored content. Governed publication only; public.questions remain draft + inactive.

begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw13_16_circular_trig_v1','P1','P1 AW13-16 Circular measure + Trigonometry closure','draft',
       'Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no Cambridge/coursebook question, diagram, answer or mark-scheme wording copied.'
from private.exam_prep_program_versions pv
where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (
  select id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1' and component_code='P1' and status='draft'
), src(skill,k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1-CIR-03','P1CIR03-D01','diagnostic','medium','A sector has radius 6 and angle π/3 radians. What is its area?','Сектор имеет радиус 6 и угол π/3 радиан. Чему равна его площадь?','Sektor radiusi 6, burchagi π/3 radian. Uning yuzi nechaga teng?','["6π","12π","18π","36π"]','A','Sector area = 1/2 r²θ = 1/2×36×π/3 = 6π.','Площадь сектора = 1/2 r²θ = 1/2×36×π/3 = 6π.','Sektor yuzi = 1/2 r²θ = 1/2×36×π/3 = 6π.',70),
('P1-CIR-03','P1CIR03-L01','learning','easy','Find the area of a sector of radius 5 with angle 1.2 radians.','Найдите площадь сектора радиуса 5 с углом 1,2 радиан.','Radiusi 5 va burchagi 1.2 radian bo‘lgan sektor yuzini toping.','["15","30","6","25"]','A','1/2×5²×1.2 = 15.','1/2×5²×1,2 = 15.','1/2×5²×1.2 = 15.',50),
('P1-CIR-03','P1CIR03-L02','learning','medium','A sector has radius 4 and area 24. Find its angle in radians.','Сектор имеет радиус 4 и площадь 24. Найдите угол в радианах.','Sektor radiusi 4 va yuzi 24. Burchagini radianlarda toping.','["3","1.5","6","12"]','A','24 = 1/2×16×θ = 8θ, so θ=3.','24 = 1/2×16×θ = 8θ, поэтому θ=3.','24 = 1/2×16×θ = 8θ, demak θ=3.',65),
('P1-CIR-03','P1CIR03-L03','learning','medium','A sector of radius 4 has angle π/2. The triangle formed by the two radii has area 8. What is the area of the minor segment?','Сектор радиуса 4 имеет угол π/2. Площадь треугольника, образованного двумя радиусами, равна 8. Чему равна площадь малого сегмента?','Radiusi 4 bo‘lgan sektor burchagi π/2. Ikki radius hosil qilgan uchburchak yuzi 8. Kichik segment yuzi nechaga teng?','["4π−8","8π−8","4π+8","8"]','A','Sector area is 1/2×16×π/2=4π. Segment area = sector − triangle = 4π−8.','Площадь сектора 4π. Площадь сегмента = сектор − треугольник = 4π−8.','Sektor yuzi 4π. Segment yuzi = sektor − uchburchak = 4π−8.',75),
('P1-CIR-03','P1CIR03-R01','retest','easy','A sector has radius 3 and angle 2 radians. Find its area.','Сектор имеет радиус 3 и угол 2 радиана. Найдите площадь.','Sektor radiusi 3 va burchagi 2 radian. Yuzini toping.','["9","18","6","4.5"]','A','1/2×9×2 = 9.','1/2×9×2 = 9.','1/2×9×2 = 9.',45),
('P1-CIR-03','P1CIR03-R02','retest','medium','A sector has area 10 and angle 0.8 radians. Find its radius.','Площадь сектора равна 10, угол 0,8 радиан. Найдите радиус.','Sektor yuzi 10, burchagi 0.8 radian. Radiusini toping.','["5","4","2.5","25"]','A','10 = 1/2 r²(0.8)=0.4r², so r²=25 and r=5.','10 = 0,4r², поэтому r²=25 и r=5.','10 = 0.4r², demak r²=25 va r=5.',65),
('P1-CIR-03','P1CIR03-M01','mixed','medium','An annular sector has outer radius 6, inner radius 3 and angle π/3. Find its area.','Кольцевой сектор имеет внешний радиус 6, внутренний радиус 3 и угол π/3. Найдите его площадь.','Halqasimon sektor tashqi radiusi 6, ichki radiusi 3 va burchagi π/3. Yuzini toping.','["9π/2","3π","9π","27π/2"]','A','Area = 1/2(6²−3²)(π/3)=1/2×27×π/3=9π/2.','Площадь = 1/2(6²−3²)(π/3)=9π/2.','Yuza = 1/2(6²−3²)(π/3)=9π/2.',80),

('P1-TRI-02','P1TRI02-D01','diagnostic','medium','Find the exact value of sin 150°.','Найдите точное значение sin 150°.','sin 150° ning aniq qiymatini toping.','["1/2","−1/2","√3/2","−√3/2"]','A','150°=180°−30°. Sine is positive in quadrant II, so sin150°=sin30°=1/2.','150°=180°−30°. Во II четверти синус положителен, поэтому sin150°=1/2.','150°=180°−30°. II chorakda sinus musbat, shuning uchun sin150°=1/2.',60),
('P1-TRI-02','P1TRI02-L01','learning','easy','Find the exact value of cos 120°.','Найдите точное значение cos 120°.','cos 120° ning aniq qiymatini toping.','["−1/2","1/2","−√3/2","√3/2"]','A','120°=180°−60°. Cosine is negative in quadrant II, so cos120°=−cos60°=−1/2.','120°=180°−60°. Во II четверти косинус отрицателен: −1/2.','120°=180°−60°. II chorakda kosinus manfiy: −1/2.',50),
('P1-TRI-02','P1TRI02-L02','learning','medium','Find the exact value of tan 225°.','Найдите точное значение tan 225°.','tan 225° ning aniq qiymatini toping.','["1","−1","√3","0"]','A','225°=180°+45°. Tangent has period 180°, so tan225°=tan45°=1.','Тангенс имеет период 180°, поэтому tan225°=tan45°=1.','Tangens davri 180°, shuning uchun tan225°=tan45°=1.',55),
('P1-TRI-02','P1TRI02-L03','learning','medium','Find the exact value of sin 330°.','Найдите точное значение sin 330°.','sin 330° ning aniq qiymatini toping.','["−1/2","1/2","−√3/2","√3/2"]','A','330°=360°−30°. Sine is negative in quadrant IV, so sin330°=−1/2.','330°=360°−30°. В IV четверти синус отрицателен: −1/2.','330°=360°−30°. IV chorakda sinus manfiy: −1/2.',55),
('P1-TRI-02','P1TRI02-R01','retest','easy','Find the exact value of cos 300°.','Найдите точное значение cos 300°.','cos 300° ning aniq qiymatini toping.','["1/2","−1/2","√3/2","−√3/2"]','A','300°=360°−60° and cosine is positive in quadrant IV, so cos300°=1/2.','300°=360°−60°, косинус в IV четверти положителен: 1/2.','300°=360°−60°, IV chorakda kosinus musbat: 1/2.',45),
('P1-TRI-02','P1TRI02-R02','retest','medium','Find the exact value of tan 135°.','Найдите точное значение tan 135°.','tan 135° ning aniq qiymatini toping.','["−1","1","0","√3"]','A','135°=180°−45°. Tangent is negative in quadrant II, so tan135°=−1.','135°=180°−45°. Во II четверти тангенс отрицателен: −1.','135°=180°−45°. II chorakda tangens manfiy: −1.',50),
('P1-TRI-02','P1TRI02-M01','mixed','medium','Evaluate exactly: 2sin30° + cos180°.','Вычислите точно: 2sin30° + cos180°.','Aniq hisoblang: 2sin30° + cos180°.','["0","1","2","−2"]','A','2sin30° + cos180° = 2(1/2)−1 = 0.','2sin30° + cos180° = 1−1=0.','2sin30° + cos180° = 1−1=0.',55),

('P1-TRI-03','P1TRI03-D01','diagnostic','medium','Using principal values in degrees, evaluate cos⁻¹(−1/2).','Используя главное значение в градусах, вычислите cos⁻¹(−1/2).','Gradusdagi asosiy qiymatni ishlatib, cos⁻¹(−1/2) ni toping.','["120°","60°","240°","−60°"]','A','The principal arccos range is 0° to 180°. cos120°=−1/2, so the principal value is 120°.','Главный диапазон arccos — от 0° до 180°. cos120°=−1/2, поэтому ответ 120°.','arccos asosiy oralig‘i 0° dan 180° gacha. cos120°=−1/2, demak 120°.',65),
('P1-TRI-03','P1TRI03-L01','learning','easy','Evaluate sin⁻¹(1/2) as a principal value in degrees.','Вычислите главное значение sin⁻¹(1/2) в градусах.','sin⁻¹(1/2) ning gradusdagi asosiy qiymatini toping.','["30°","150°","330°","60°"]','A','The principal arcsin range is −90° to 90°, and sin30°=1/2.','Главный диапазон arcsin — от −90° до 90°, sin30°=1/2.','arcsin asosiy oralig‘i −90° dan 90° gacha, sin30°=1/2.',45),
('P1-TRI-03','P1TRI03-L02','learning','medium','Evaluate tan⁻¹(−1) as a principal value in degrees.','Вычислите главное значение tan⁻¹(−1) в градусах.','tan⁻¹(−1) ning gradusdagi asosiy qiymatini toping.','["−45°","45°","135°","225°"]','A','The principal arctan range is between −90° and 90°, so tan⁻¹(−1)=−45°.','Главное значение arctan лежит между −90° и 90°, поэтому −45°.','arctan asosiy qiymati −90° va 90° orasida, demak −45°.',50),
('P1-TRI-03','P1TRI03-L03','learning','medium','Evaluate sin⁻¹(−√3/2) as a principal value in degrees.','Вычислите главное значение sin⁻¹(−√3/2) в градусах.','sin⁻¹(−√3/2) ning gradusdagi asosiy qiymatini toping.','["−60°","60°","240°","300°"]','A','Within the principal arcsin range, sin(−60°)=−√3/2.','В главном диапазоне arcsin sin(−60°)=−√3/2.','arcsin asosiy oralig‘ida sin(−60°)=−√3/2.',55),
('P1-TRI-03','P1TRI03-R01','retest','easy','Evaluate cos⁻¹(0) as a principal value in degrees.','Вычислите главное значение cos⁻¹(0) в градусах.','cos⁻¹(0) ning gradusdagi asosiy qiymatini toping.','["90°","0°","180°","270°"]','A','cos90°=0 and 90° lies in the principal arccos range.','cos90°=0, и 90° лежит в главном диапазоне arccos.','cos90°=0 va 90° arccos asosiy oralig‘ida.',40),
('P1-TRI-03','P1TRI03-R02','retest','medium','Evaluate tan⁻¹(√3) as a principal value in degrees.','Вычислите главное значение tan⁻¹(√3) в градусах.','tan⁻¹(√3) ning gradusdagi asosiy qiymatini toping.','["60°","120°","240°","300°"]','A','tan60°=√3 and 60° is in the principal arctan range.','tan60°=√3, и 60° находится в главном диапазоне arctan.','tan60°=√3 va 60° arctan asosiy oralig‘ida.',50),
('P1-TRI-03','P1TRI03-M01','mixed','medium','A calculator gives cos⁻¹(0.25). Which value is the correct principal value to 1 decimal place?','Калькулятор вычисляет cos⁻¹(0,25). Каково правильное главное значение с точностью до 0,1°?','Kalkulyator cos⁻¹(0.25) ni hisoblaydi. 0.1° aniqlikdagi to‘g‘ri asosiy qiymat qaysi?','["75.5°","14.5°","284.5°","104.5°"]','A','cos⁻¹(0.25)≈75.522°, so to 1 decimal place it is 75.5°.','cos⁻¹(0,25)≈75,522°, поэтому 75,5°.','cos⁻¹(0.25)≈75.522°, demak 75.5°.',65),

('P1-TRI-04','P1TRI04-D01','diagnostic','medium','Simplify 1 − sin²x.','Упростите 1 − sin²x.','1 − sin²x ni soddalashtiring.','["cos²x","sin²x","tan²x","1"]','A','From sin²x+cos²x=1, we get 1−sin²x=cos²x.','Из sin²x+cos²x=1 получаем 1−sin²x=cos²x.','sin²x+cos²x=1 dan 1−sin²x=cos²x.',45),
('P1-TRI-04','P1TRI04-L01','learning','easy','Which identity is true for all x?','Какое тождество верно для всех x?','Qaysi ayniyat barcha x uchun to‘g‘ri?','["sin²x+cos²x=1","sin x+cos x=1","tan x=sin x cos x","sin²x−cos²x=1"]','A','The fundamental Pythagorean identity is sin²x+cos²x=1.','Основное пифагорово тождество: sin²x+cos²x=1.','Asosiy Pifagor ayniyati: sin²x+cos²x=1.',40),
('P1-TRI-04','P1TRI04-L02','learning','medium','For cos x ≠ 0, simplify sin x / cos x.','При cos x ≠ 0 упростите sin x / cos x.','cos x ≠ 0 bo‘lsa, sin x / cos x ni soddalashtiring.','["tan x","sin²x","cos²x","1"]','A','By definition, tan x = sin x / cos x.','По определению tan x = sin x / cos x.','Ta’rif bo‘yicha tan x = sin x / cos x.',40),
('P1-TRI-04','P1TRI04-L03','learning','medium','For sin x ≠ 0, simplify (1−cos²x)/sin x.','При sin x ≠ 0 упростите (1−cos²x)/sin x.','sin x ≠ 0 bo‘lsa, (1−cos²x)/sin x ni soddalashtiring.','["sin x","cos x","tan x","1"]','A','1−cos²x=sin²x, so sin²x/sin x=sin x.','1−cos²x=sin²x, поэтому sin²x/sin x=sin x.','1−cos²x=sin²x, demak sin²x/sin x=sin x.',55),
('P1-TRI-04','P1TRI04-R01','retest','easy','Complete the identity: sin²x = 1 − ___.','Дополните тождество: sin²x = 1 − ___.','Ayniyatni to‘ldiring: sin²x = 1 − ___.','["cos²x","cos x","tan²x","sin x"]','A','Rearrange sin²x+cos²x=1.','Переносим cos²x в тождестве sin²x+cos²x=1.','sin²x+cos²x=1 ni qayta yozamiz.',40),
('P1-TRI-04','P1TRI04-R02','retest','medium','For cos x ≠ 0, simplify (sin²x+cos²x)/cos x.','При cos x ≠ 0 упростите (sin²x+cos²x)/cos x.','cos x ≠ 0 bo‘lsa, (sin²x+cos²x)/cos x ni soddalashtiring.','["1/cos x","cos x","tan x","1"]','A','The numerator is 1, so the expression is 1/cos x.','Числитель равен 1, поэтому выражение равно 1/cos x.','Surat 1 ga teng, demak ifoda 1/cos x.',50),
('P1-TRI-04','P1TRI04-M01','mixed','medium','For sin x cos x ≠ 0, simplify (1−cos²x)/(sin x cos x).','При sin x cos x ≠ 0 упростите (1−cos²x)/(sin x cos x).','sin x cos x ≠ 0 bo‘lsa, (1−cos²x)/(sin x cos x) ni soddalashtiring.','["tan x","sin x","cos x","1"]','A','Replace 1−cos²x by sin²x, then cancel one sin x: sin x/cos x=tan x.','Заменяем 1−cos²x на sin²x и сокращаем: sin x/cos x=tan x.','1−cos²x ni sin²x ga almashtirib qisqartiramiz: sin x/cos x=tan x.',65),

('P1-TRI-05','P1TRI05-D01','diagnostic','medium','Solve sin θ = 1/2 for 0° ≤ θ ≤ 360°.','Решите sin θ = 1/2 при 0° ≤ θ ≤ 360°.','0° ≤ θ ≤ 360° uchun sin θ = 1/2 ni yeching.','["30°,150°","30°,330°","150°,210°","60°,120°"]','A','Reference angle is 30°. Sine is positive in quadrants I and II, giving 30° and 150°.','Опорный угол 30°. Синус положителен в I и II четвертях: 30° и 150°.','Tayanch burchak 30°. Sinus I va II choraklarda musbat: 30° va 150°.',75),
('P1-TRI-05','P1TRI05-L01','learning','easy','Solve cos θ = 1/2 for 0° ≤ θ < 360°.','Решите cos θ = 1/2 при 0° ≤ θ < 360°.','0° ≤ θ < 360° uchun cos θ = 1/2 ni yeching.','["60°,300°","60°,120°","120°,240°","30°,330°"]','A','Reference angle 60°; cosine is positive in quadrants I and IV: 60°,300°.','Опорный угол 60°; косинус положителен в I и IV четвертях: 60°,300°.','Tayanch burchak 60°; kosinus I va IV choraklarda musbat: 60°,300°.',55),
('P1-TRI-05','P1TRI05-L02','learning','medium','Solve tan θ = 1 for 0° ≤ θ < 360°.','Решите tan θ = 1 при 0° ≤ θ < 360°.','0° ≤ θ < 360° uchun tan θ = 1 ni yeching.','["45°,225°","45°,135°","135°,315°","90°,270°"]','A','Tangent has reference angle 45° and is positive in quadrants I and III: 45°,225°.','Опорный угол 45°; тангенс положителен в I и III четвертях: 45°,225°.','Tayanch burchak 45°; tangens I va III choraklarda musbat: 45°,225°.',55),
('P1-TRI-05','P1TRI05-L03','learning','medium','Solve sin θ = −√3/2 for 0° ≤ θ < 360°.','Решите sin θ = −√3/2 при 0° ≤ θ < 360°.','0° ≤ θ < 360° uchun sin θ = −√3/2 ni yeching.','["240°,300°","60°,120°","120°,240°","210°,330°"]','A','Reference angle is 60°. Sine is negative in quadrants III and IV: 240°,300°.','Опорный угол 60°. Синус отрицателен в III и IV четвертях: 240°,300°.','Tayanch burchak 60°. Sinus III va IV choraklarda manfiy: 240°,300°.',65),
('P1-TRI-05','P1TRI05-R01','retest','easy','Solve cos θ = −1/2 for 0° ≤ θ < 360°.','Решите cos θ = −1/2 при 0° ≤ θ < 360°.','0° ≤ θ < 360° uchun cos θ = −1/2 ni yeching.','["120°,240°","60°,300°","120°,300°","60°,240°"]','A','Reference angle 60°; cosine is negative in quadrants II and III: 120°,240°.','Опорный угол 60°; косинус отрицателен во II и III четвертях: 120°,240°.','Tayanch burchak 60°; kosinus II va III choraklarda manfiy: 120°,240°.',55),
('P1-TRI-05','P1TRI05-R02','retest','medium','Solve tan θ = −√3 for 0° ≤ θ < 360°.','Решите tan θ = −√3 при 0° ≤ θ < 360°.','0° ≤ θ < 360° uchun tan θ = −√3 ni yeching.','["120°,300°","60°,240°","120°,240°","60°,300°"]','A','Reference angle 60°; tangent is negative in quadrants II and IV: 120°,300°.','Опорный угол 60°; тангенс отрицателен во II и IV четвертях: 120°,300°.','Tayanch burchak 60°; tangens II va IV choraklarda manfiy: 120°,300°.',65),
('P1-TRI-05','P1TRI05-M01','mixed','medium','Solve 2sin θ = 1 for 0° ≤ θ ≤ 360°.','Решите 2sin θ = 1 при 0° ≤ θ ≤ 360°.','0° ≤ θ ≤ 360° uchun 2sin θ = 1 ni yeching.','["30°,150°","60°,120°","30°,330°","150°,330°"]','A','First sinθ=1/2. The solutions in the interval are 30° and 150°.','Сначала sinθ=1/2. Решения на интервале: 30° и 150°.','Avval sinθ=1/2. Oraliqdagi yechimlar: 30° va 150°.',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,case when s.skill='P1-CIR-03' then 'P1 Circular Measure' else 'P1 Trigonometry' end,s.skill,s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw13_16_circular_trig_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw13_16_circular_trig_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1' and status='draft'), keys(skill,k,role) as (values
('P1-CIR-03','P1CIR03-D01','diagnostic'),('P1-CIR-03','P1CIR03-L01','learning'),('P1-CIR-03','P1CIR03-L02','learning'),('P1-CIR-03','P1CIR03-L03','learning'),('P1-CIR-03','P1CIR03-R01','retest'),('P1-CIR-03','P1CIR03-R02','retest'),('P1-CIR-03','P1CIR03-M01','mixed'),
('P1-TRI-02','P1TRI02-D01','diagnostic'),('P1-TRI-02','P1TRI02-L01','learning'),('P1-TRI-02','P1TRI02-L02','learning'),('P1-TRI-02','P1TRI02-L03','learning'),('P1-TRI-02','P1TRI02-R01','retest'),('P1-TRI-02','P1TRI02-R02','retest'),('P1-TRI-02','P1TRI02-M01','mixed'),
('P1-TRI-03','P1TRI03-D01','diagnostic'),('P1-TRI-03','P1TRI03-L01','learning'),('P1-TRI-03','P1TRI03-L02','learning'),('P1-TRI-03','P1TRI03-L03','learning'),('P1-TRI-03','P1TRI03-R01','retest'),('P1-TRI-03','P1TRI03-R02','retest'),('P1-TRI-03','P1TRI03-M01','mixed'),
('P1-TRI-04','P1TRI04-D01','diagnostic'),('P1-TRI-04','P1TRI04-L01','learning'),('P1-TRI-04','P1TRI04-L02','learning'),('P1-TRI-04','P1TRI04-L03','learning'),('P1-TRI-04','P1TRI04-R01','retest'),('P1-TRI-04','P1TRI04-R02','retest'),('P1-TRI-04','P1TRI04-M01','mixed'),
('P1-TRI-05','P1TRI05-D01','diagnostic'),('P1-TRI-05','P1TRI05-L01','learning'),('P1-TRI-05','P1TRI05-L02','learning'),('P1-TRI-05','P1TRI05-L03','learning'),('P1-TRI-05','P1TRI05-R01','retest'),('P1-TRI-05','P1TRI05-R02','retest'),('P1-TRI-05','P1TRI05-M01','mixed')
)
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, values, distractors, answer and explanation; no protected question or mark-scheme wording copied.','Authored for p1_aw13_16_circular_trig_v1 from canonical skill intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 Circular measure / Trigonometry','Complete Pure Mathematics 1; Circular measure / Trigonometry (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw13_16_circular_trig_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with rules(ckey,match,dcode,mtype,skill,fen,fru,fuz,nen,nru,nuz) as (values
('P1CIR03-D01','B','missed_half_factor','method','P1-CIR-03','Sector area includes the factor 1/2. Using r²θ gives twice the correct area.','В формуле площади сектора есть множитель 1/2. r²θ даёт вдвое больший ответ.','Sektor yuzi formulasida 1/2 bor. r²θ javobni ikki baravar qiladi.','Use A=1/2 r²θ with θ in radians.','Используйте A=1/2 r²θ при θ в радианах.','θ radian bo‘lsa A=1/2 r²θ ni ishlating.'),
('P1CIR03-D01','C','angle_handling_error','method','P1-CIR-03','π/3 must multiply 18; it is not replaced by π.','π/3 нужно умножить на 18; нельзя заменять его на π.','π/3 ni 18 ga ko‘paytirish kerak; uni π bilan almashtirmang.','Substitute r and θ before simplifying.','Сначала подставьте r и θ, затем упрощайте.','Avval r va θ ni qo‘ying, keyin soddalashtiring.'),
('P1CIR03-D01','D','used_full_circle_area','concept','P1-CIR-03','36π is the area of the full circle, not the π/3 sector.','36π — площадь всего круга, а не сектора π/3.','36π butun doira yuzi, π/3 sektor yuzi emas.','Compare θ with 2π to see what fraction of the full circle is used.','Сравните θ с 2π, чтобы увидеть долю полного круга.','θ ni 2π bilan solishtirib doiraning qaysi qismi olinganini ko‘ring.'),
('P1TRI02-D01','B','quadrant_sign_error','concept','P1-TRI-02','150° is in quadrant II, where sine is positive.','150° находится во II четверти, где синус положителен.','150° II chorakda, bu yerda sinus musbat.','Find the reference angle and then apply the quadrant sign.','Найдите опорный угол и затем знак по четверти.','Tayanch burchakni topib, chorak ishorasini qo‘llang.'),
('P1TRI02-D01','C','wrong_exact_function_value','concept','P1-TRI-02','√3/2 is cos30° (and sin60°), not sin30°.','√3/2 — это cos30° (и sin60°), а не sin30°.','√3/2 cos30° (va sin60°), sin30° emas.','Recall the 30°/60° exact-value triangle.','Вспомните точные значения для 30°/60°.','30°/60° aniq qiymatlarini eslang.'),
('P1TRI02-D01','D','value_and_sign_error','method','P1-TRI-02','Both the reference value and quadrant sign are wrong.','Неверны и опорное значение, и знак четверти.','Tayanch qiymat ham, chorak ishorasi ham noto‘g‘ri.','Separate magnitude from sign: sin30° first, then quadrant II sign.','Разделите модуль и знак: сначала sin30°, затем знак II четверти.','Qiymat va ishorani ajrating: avval sin30°, keyin II chorak ishorasi.'),
('P1TRI03-D01','B','ignored_negative_cosine','concept','P1-TRI-03','cos60° is +1/2, not −1/2. The negative value has principal angle 120°.','cos60°=+1/2, а не −1/2. Отрицательному значению соответствует 120°.','cos60°=+1/2. Manfiy qiymatning asosiy burchagi 120°.','Check the sign of cosine at the candidate angle.','Проверьте знак косинуса у выбранного угла.','Tanlangan burchakda kosinus ishorasini tekshiring.'),
('P1TRI03-D01','C','used_nonprincipal_solution','concept','P1-TRI-03','240° also has cosine −1/2, but it is outside the principal arccos range 0°–180°.','cos240° тоже равен −1/2, но 240° вне главного диапазона arccos 0°–180°.','cos240° ham −1/2, lekin 240° arccos asosiy 0°–180° oralig‘idan tashqarida.','For inverse functions, enforce the principal-value range.','Для обратных функций соблюдайте диапазон главных значений.','Teskari funksiyada asosiy qiymat oralig‘ini tekshiring.'),
('P1TRI03-D01','D','wrong_inverse_range','concept','P1-TRI-03','−60° is not in the principal arccos range and cos(−60°)=+1/2.','−60° не входит в главный диапазон arccos, и cos(−60°)=+1/2.','−60° arccos asosiy oralig‘ida emas va cos(−60°)=+1/2.','Use arccos range [0°,180°] and verify by substitution.','Используйте диапазон arccos [0°,180°] и проверьте подстановкой.','arccos [0°,180°] oralig‘ini ishlating va tekshirib ko‘ring.'),
('P1TRI04-D01','B','identity_rearrangement_error','concept','P1-TRI-04','The Pythagorean identity gives cos²x after subtracting sin²x from 1.','Пифагорово тождество даёт cos²x после вычитания sin²x из 1.','Pifagor ayniyatida 1 dan sin²x ayirilsa cos²x qoladi.','Start from sin²x+cos²x=1 and rearrange one term at a time.','Начните с sin²x+cos²x=1 и перенесите один член.','sin²x+cos²x=1 dan boshlab bir hadni ko‘chiring.'),
('P1TRI04-D01','C','confused_tangent_identity','concept','P1-TRI-04','tan x is a ratio sin x/cos x; it is not equal to 1−sin²x.','tan x — отношение sin x/cos x; оно не равно 1−sin²x.','tan x = sin x/cos x; u 1−sin²x ga teng emas.','Keep the ratio identity separate from the Pythagorean identity.','Не смешивайте отношение для tan с пифагоровым тождеством.','tan nisbat ayniyatini Pifagor ayniyatidan ajrating.'),
('P1TRI04-D01','D','dropped_variable_term','method','P1-TRI-04','1−sin²x varies with x; it is not identically 1.','1−sin²x зависит от x и не равно тождественно 1.','1−sin²x x ga bog‘liq, doim 1 emas.','Use the identity before simplifying.','Перед упрощением примените тождество.','Soddalashtirishdan oldin ayniyatni qo‘llang.'),
('P1TRI05-D01','B','wrong_second_quadrant','concept','P1-TRI-05','330° has negative sine. For positive sine, the second solution is in quadrant II at 150°.','У 330° синус отрицателен. Для положительного синуса второе решение во II четверти: 150°.','330° da sinus manfiy. Musbat sinus uchun ikkinchi yechim II chorakda: 150°.','Use the reference angle 30° and the sign of sine by quadrant.','Используйте опорный угол 30° и знак синуса по четвертям.','30° tayanch burchak va sinus ishoralarini ishlating.'),
('P1TRI05-D01','C','wrong_reference_pair','method','P1-TRI-05','150° is valid, but 210° has sine −1/2, so the pair is incomplete/wrong.','150° подходит, но sin210°=−1/2, поэтому пара неверна.','150° to‘g‘ri, lekin sin210°=−1/2, shuning uchun juft noto‘g‘ri.','Check every candidate by substitution.','Проверьте каждый кандидат подстановкой.','Har bir variantni qo‘yib tekshiring.'),
('P1TRI05-D01','D','used_cosine_reference','concept','P1-TRI-05','60° and 120° have sine √3/2, not 1/2.','sin60° и sin120° равен √3/2, а не 1/2.','sin60° va sin120° = √3/2, 1/2 emas.','The reference angle for sinθ=1/2 is 30°, not 60°.','Опорный угол для sinθ=1/2 равен 30°, а не 60°.','sinθ=1/2 uchun tayanch burchak 30°, 60° emas.')
), meta as (
select m.id,m.content_key from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw13_16_circular_trig_v1' and m.reserve_role='diagnostic')
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,r.skill,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from rules r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1CIR03-W01','P1-CIR-03','A sector has radius 8 and angle 1.1 radians. (a) Find its area. (b) The triangle formed by the radii has area 25.6. Find the area of the corresponding segment. (c) A concentric inner sector of radius 5 with the same angle is removed. Find the remaining annular-sector area. Show the formula used in each part.','Сектор имеет радиус 8 и угол 1,1 радиан. (a) Найдите его площадь. (b) Площадь треугольника между радиусами равна 25,6. Найдите площадь соответствующего сегмента. (c) Удаляют концентрический сектор радиуса 5 с тем же углом. Найдите оставшуюся площадь кольцевого сектора. Покажите формулу в каждой части.','Sektor radiusi 8 va burchagi 1.1 radian. (a) Yuzini toping. (b) Radiuslar orasidagi uchburchak yuzi 25.6. Segment yuzini toping. (c) Shu burchakli radiusi 5 ichki sektor olib tashlanadi. Qolgan halqasimon sektor yuzini toping. Har qismda formulani ko‘rsating.','{"max_marks":10,"criteria":[{"id":"sector","marks":3,"rule":"Uses 1/2×8²×1.1=35.2."},{"id":"segment","marks":2,"rule":"Finds 35.2−25.6=9.6."},{"id":"annular","marks":3,"rule":"Uses 1/2(8²−5²)1.1=21.45."},{"id":"method","marks":2,"rule":"Uses radians consistently and distinguishes sector, segment and annular-sector subtraction."}]}','Check the 1/2 factor and keep the same angle in both concentric sectors. A segment is sector minus triangle.','Проверьте множитель 1/2 и используйте один и тот же угол для концентрических секторов. Сегмент = сектор − треугольник.','1/2 ko‘paytuvchini tekshiring va ikkala konsentrik sektorda bir xil burchakni ishlating. Segment = sektor − uchburchak.'),
('P1TRI02-W01','P1-TRI-02','Without a calculator, find the exact values of sin150°, cos240°, tan315° and 2sin30°−cos180°. For each single angle, state the reference angle and the quadrant sign.','Без калькулятора найдите точные значения sin150°, cos240°, tan315° и 2sin30°−cos180°. Для каждого отдельного угла укажите опорный угол и знак по четверти.','Kalkulyatorsiz sin150°, cos240°, tan315° va 2sin30°−cos180° ning aniq qiymatlarini toping. Har bir alohida burchak uchun tayanch burchak va chorak ishorasini yozing.','{"max_marks":10,"criteria":[{"id":"sin","marks":2,"rule":"sin150°=1/2 with reference 30° and positive QII sign."},{"id":"cos","marks":2,"rule":"cos240°=−1/2 with reference 60° and negative QIII sign."},{"id":"tan","marks":2,"rule":"tan315°=−1 with reference 45° and negative QIV sign."},{"id":"expression","marks":2,"rule":"2(1/2)−(−1)=2."},{"id":"communication","marks":2,"rule":"Separates exact magnitude from quadrant sign consistently."}]}','Use a reference angle first, then apply the sign. Do not convert exact values to decimals.','Сначала находите опорный угол, затем применяйте знак. Не переводите точные значения в десятичные.','Avval tayanch burchakni toping, keyin ishorani qo‘llang. Aniq qiymatlarni o‘nli songa aylantirmang.'),
('P1TRI03-W01','P1-TRI-03','State the principal-value ranges in degrees for sin⁻¹, cos⁻¹ and tan⁻¹. Then evaluate sin⁻¹(−1/2), cos⁻¹(−√3/2) and tan⁻¹(1). Finally explain why a principal inverse value is not automatically the full solution set of a trigonometric equation.','sin⁻¹, cos⁻¹ и tan⁻¹ үшін градусах укажите диапазоны главных значений. Затем вычислите sin⁻¹(−1/2), cos⁻¹(−√3/2) и tan⁻¹(1). В конце объясните, почему главное значение обратной функции не является автоматически полным набором решений тригонометрического уравнения.','sin⁻¹, cos⁻¹ va tan⁻¹ uchun gradusdagi asosiy qiymat oraliqlarini yozing. So‘ng sin⁻¹(−1/2), cos⁻¹(−√3/2) va tan⁻¹(1) ni toping. Oxirida asosiy teskari qiymat trigonometrik tenglamaning barcha yechimlari emasligini tushuntiring.','{"max_marks":10,"criteria":[{"id":"ranges","marks":3,"rule":"States arcsin [−90°,90°], arccos [0°,180°], arctan (−90°,90°)."},{"id":"values","marks":3,"rule":"Obtains −30°,150°,45° respectively."},{"id":"meaning","marks":2,"rule":"Explains inverse functions return one principal value."},{"id":"equation_link","marks":2,"rule":"Explains full equations require symmetry/periodicity and interval filtering."}]}','Keep inverse-function range and equation-solution interval as two different ideas.','Разделяйте диапазон главного значения обратной функции и интервал решений уравнения.','Teskari funksiyaning asosiy oralig‘i bilan tenglama yechim oralig‘ini ajrating.'),
('P1TRI04-W01','P1-TRI-04','Prove, for values where the expressions are defined, that (1−cos²x)/(sin x cos x)=tan x. Then simplify (sin²x+cos²x)/(1−sin²x) and state any denominator restriction you use.','Докажите для допустимых x, что (1−cos²x)/(sin x cos x)=tan x. Затем упростите (sin²x+cos²x)/(1−sin²x) и укажите ограничения на знаменатели.','Ifodalar aniqlangan x lar uchun (1−cos²x)/(sin x cos x)=tan x ekanini isbotlang. So‘ng (sin²x+cos²x)/(1−sin²x) ni soddalashtiring va maxraj cheklovlarini yozing.','{"max_marks":10,"criteria":[{"id":"first_identity","marks":4,"rule":"Uses 1−cos²x=sin²x, cancels valid sin x, obtains sin x/cos x=tan x."},{"id":"second_identity","marks":3,"rule":"Uses numerator=1 and denominator=cos²x, obtaining 1/cos²x."},{"id":"restrictions","marks":2,"rule":"Notes the original denominators require sin x cos x≠0 for the first and cos x≠0 for the second."},{"id":"logic","marks":1,"rule":"Transforms one side rather than assuming the result."}]}','Use only established identities and keep track of what you cancel.','Используйте только известные тождества и следите за тем, что сокращаете.','Faqat ma’lum ayniyatlardan foydalaning va nimani qisqartirayotganingizni kuzating.'),
('P1TRI05-W01','P1-TRI-05','Solve on 0°≤θ<360°: (a) sinθ=√3/2, (b) cosθ=−1/2, (c) tanθ=−1. For each equation, show the reference angle, identify the valid quadrants and list every solution in the interval.','Решите при 0°≤θ<360°: (a) sinθ=√3/2, (b) cosθ=−1/2, (c) tanθ=−1. Для каждого уравнения покажите опорный угол, нужные четверти и все решения на интервале.','0°≤θ<360° da yeching: (a) sinθ=√3/2, (b) cosθ=−1/2, (c) tanθ=−1. Har bir tenglama uchun tayanch burchak, mos choraklar va oraliqdagi barcha yechimlarni yozing.','{"max_marks":10,"criteria":[{"id":"sin","marks":3,"rule":"Uses reference 60°, QI/QII, solutions 60°,120°."},{"id":"cos","marks":3,"rule":"Uses reference 60°, QII/QIII, solutions 120°,240°."},{"id":"tan","marks":3,"rule":"Uses reference 45°, QII/QIV, solutions 135°,315°."},{"id":"interval","marks":1,"rule":"No duplicated or out-of-interval solutions."}]}','For each equation: principal/reference angle → sign quadrants → interval check.','Для каждого уравнения: опорный угол → четверти по знаку → проверка интервала.','Har bir tenglama: tayanch burchak → ishora choraklari → oraliq tekshiruvi.')
)
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw13_16_circular_trig_diagnostic','diagnostic','P1 AW13-16 Circular/Trig diagnostic','Диагностика P1 AW13–16: окружность/тригонометрия','P1 AW13–16 Circular/Trig diagnostikasi'),
('p1_cir03_learning','learning','Sector and segment area learning','Площадь сектора и сегмента','Sektor va segment yuzi'),
('p1_tri02_learning','learning','Exact trigonometric values learning','Точные тригонометрические значения','Aniq trigonometrik qiymatlar'),
('p1_tri03_learning','learning','Inverse trigonometric principal values','Главные значения обратных функций','Teskari trigonometrik asosiy qiymatlar'),
('p1_tri04_learning','learning','Trigonometric identities learning','Тригонометрические тождества','Trigonometrik ayniyatlar'),
('p1_tri05_learning','learning','Trigonometric equations learning','Тригонометрические уравнения','Trigonometrik tenglamalar'),
('p1_cir03_retest','retest','Sector/segment delayed retest','Отложенный ретест: сектор/сегмент','Kechiktirilgan retest: sektor/segment'),
('p1_tri02_retest','retest','Exact values delayed retest','Отложенный ретест: точные значения','Kechiktirilgan retest: aniq qiymatlar'),
('p1_tri03_retest','retest','Inverse trig delayed retest','Отложенный ретест: обратная тригонометрия','Kechiktirilgan retest: teskari trigonometrik'),
('p1_tri04_retest','retest','Identities delayed retest','Отложенный ретест: тождества','Kechiktirilgan retest: ayniyatlar'),
('p1_tri05_retest','retest','Trig equations delayed retest','Отложенный ретест: уравнения','Kechiktirilgan retest: tenglamalar'),
('p1_aw13_16_circular_trig_mixed','mixed','P1 AW13-16 Circular/Trig mixed transfer','Смешанный перенос P1 AW13–16','P1 AW13–16 mixed transfer')
)
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw13_16_circular_trig_diagnostic',1,'P1CIR03-D01',null,'P1-CIR-03','diagnostic',true),('p1_aw13_16_circular_trig_diagnostic',2,'P1TRI02-D01',null,'P1-TRI-02','diagnostic',true),('p1_aw13_16_circular_trig_diagnostic',3,'P1TRI03-D01',null,'P1-TRI-03','diagnostic',true),('p1_aw13_16_circular_trig_diagnostic',4,'P1TRI04-D01',null,'P1-TRI-04','diagnostic',true),('p1_aw13_16_circular_trig_diagnostic',5,'P1TRI05-D01',null,'P1-TRI-05','diagnostic',true),
('p1_cir03_learning',1,'P1CIR03-L01',null,'P1-CIR-03','learning',false),('p1_cir03_learning',2,'P1CIR03-L02',null,'P1-CIR-03','learning',false),('p1_cir03_learning',3,'P1CIR03-L03',null,'P1-CIR-03','learning',false),('p1_cir03_learning',4,null,'P1CIR03-W01','P1-CIR-03','written',false),
('p1_tri02_learning',1,'P1TRI02-L01',null,'P1-TRI-02','learning',false),('p1_tri02_learning',2,'P1TRI02-L02',null,'P1-TRI-02','learning',false),('p1_tri02_learning',3,'P1TRI02-L03',null,'P1-TRI-02','learning',false),('p1_tri02_learning',4,null,'P1TRI02-W01','P1-TRI-02','written',false),
('p1_tri03_learning',1,'P1TRI03-L01',null,'P1-TRI-03','learning',false),('p1_tri03_learning',2,'P1TRI03-L02',null,'P1-TRI-03','learning',false),('p1_tri03_learning',3,'P1TRI03-L03',null,'P1-TRI-03','learning',false),('p1_tri03_learning',4,null,'P1TRI03-W01','P1-TRI-03','written',false),
('p1_tri04_learning',1,'P1TRI04-L01',null,'P1-TRI-04','learning',false),('p1_tri04_learning',2,'P1TRI04-L02',null,'P1-TRI-04','learning',false),('p1_tri04_learning',3,'P1TRI04-L03',null,'P1-TRI-04','learning',false),('p1_tri04_learning',4,null,'P1TRI04-W01','P1-TRI-04','written',false),
('p1_tri05_learning',1,'P1TRI05-L01',null,'P1-TRI-05','learning',false),('p1_tri05_learning',2,'P1TRI05-L02',null,'P1-TRI-05','learning',false),('p1_tri05_learning',3,'P1TRI05-L03',null,'P1-TRI-05','learning',false),('p1_tri05_learning',4,null,'P1TRI05-W01','P1-TRI-05','written',false),
('p1_cir03_retest',1,'P1CIR03-R01',null,'P1-CIR-03','retest',true),('p1_tri02_retest',1,'P1TRI02-R01',null,'P1-TRI-02','retest',true),('p1_tri03_retest',1,'P1TRI03-R01',null,'P1-TRI-03','retest',true),('p1_tri04_retest',1,'P1TRI04-R01',null,'P1-TRI-04','retest',true),('p1_tri05_retest',1,'P1TRI05-R01',null,'P1-TRI-05','retest',true),
('p1_aw13_16_circular_trig_mixed',1,'P1CIR03-M01',null,'P1-CIR-03','mixed',true),('p1_aw13_16_circular_trig_mixed',2,'P1TRI02-M01',null,'P1-TRI-02','mixed',true),('p1_aw13_16_circular_trig_mixed',3,'P1TRI03-M01',null,'P1-TRI-03','mixed',true),('p1_aw13_16_circular_trig_mixed',4,'P1TRI04-M01',null,'P1-TRI-04','mixed',true),('p1_aw13_16_circular_trig_mixed',5,'P1TRI05-M01',null,'P1-TRI-05','mixed',true)
)
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

-- Static QA.
do $$ declare v_id bigint; v_skill text; v_bad int; begin
select id into v_id from private.exam_prep_content_versions where content_version='p1_aw13_16_circular_trig_v1' and status='draft';
if v_id is null then raise exception 'P1 AW13 circular/trig draft missing'; end if;
if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id)<>35 then raise exception 'P1 AW13 circular/trig expected 35 questions'; end if;
foreach v_skill in array array['P1-CIR-03','P1-TRI-02','P1-TRI-03','P1-TRI-04','P1-TRI-05'] loop
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='diagnostic')<>1 then raise exception '% diagnostic floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='learning')<>3 then raise exception '% learning floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='retest')<>2 then raise exception '% retest floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='mixed')<>1 then raise exception '% mixed floor',v_skill; end if;
 if (select count(*) from private.exam_prep_written_tasks where content_version_id=v_id and primary_skill_code=v_skill and lifecycle_state='approved')<>1 then raise exception '% written floor',v_skill; end if;
end loop;
select count(*) into v_bad from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id where m.content_version_id=v_id and (q.subject_id<>5 or q.is_active or q.quality_status is distinct from 'draft' or nullif(trim(q.question_text_en),'') is null or nullif(trim(q.question_text_ru),'') is null or nullif(trim(q.question_text_uz),'') is null or nullif(trim(q.options_text_en),'') is null or jsonb_typeof(q.options_text_en::jsonb)<>'array' or jsonb_array_length(q.options_text_en::jsonb)<>4 or q.correct_answer not in ('A','B','C','D') or nullif(trim(q.explanation_en),'') is null or nullif(trim(q.explanation_ru),'') is null or nullif(trim(q.explanation_uz),'') is null or md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))<>m.question_snapshot_md5);
if v_bad<>0 then raise exception 'P1 AW13 circular/trig payload failures=%',v_bad; end if;
select count(*) into v_bad from (select m.id from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id left join private.exam_prep_diagnostic_rules r on r.content_meta_id=m.id and r.status='approved' and r.answer_kind='mcq_option' where m.content_version_id=v_id and m.reserve_role='diagnostic' group by m.id,q.correct_answer having count(r.id)<>3 or count(r.id) filter(where r.answer_match=q.correct_answer)<>0) x;
if v_bad<>0 then raise exception 'P1 AW13 circular/trig diagnostic rules failures=%',v_bad; end if;
if (select count(*) from private.exam_prep_question_content_meta m where m.content_version_id=v_id and m.reserve_role='retest' and not exists(select 1 from private.exam_prep_assessment_items i where i.question_id=m.question_id))<>5 then raise exception 'P1 AW13 circular/trig expected 5 R02 isolated holdouts'; end if;
end $$;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw13_16_circular_trig_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw13_16_circular_trig_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw13_16_circular_trig_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw13_16_circular_trig_v1' and cv.status='approved' and w.lifecycle_state='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw13_16_circular_trig_v1' and cv.status='approved' and a.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw13_16_circular_trig_v1' and status='approved';

-- Final acceptance: 5/8 P1 AW13-16 ready; global runway remains RED until the full slice is ready.
do $$ declare v_program bigint; v_skill text; v_ready int; v_r jsonb; v_cfg private.exam_prep_feature_config%rowtype; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P1-CIR-03','P1-TRI-02','P1-TRI-03','P1-TRI-04','P1-TRI-05'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 AW13 circular/trig final not ready=%',v_skill; end if; end loop;
select count(*) into v_ready from private.exam_prep_content_runway_release_skills rs join private.exam_prep_content_runway_releases r on r.id=rs.release_id where r.release_key='aw13_16_core_coverage_iii' and r.component_code='P1' and rs.required_for_release and private.exam_prep_skill_content_ready_v1(v_program,'P1',rs.skill_code);
if v_ready<>5 then raise exception 'P1 AW13 circular/trig expected ready=5 got=%',v_ready; end if;
v_r:=public.get_exam_prep_content_runway_v1(13::smallint); if coalesce((v_r->>'hard_floor_green')::boolean,false) then raise exception 'P1 AW13 partial pack must leave global runway RED'; end if;
select * into v_cfg from private.exam_prep_feature_config where id=1; if v_cfg.rollout_state<>'off' or v_cfg.core_enabled or v_cfg.ai_enabled or v_cfg.mentor_enabled or not v_cfg.kill_switch then raise exception 'P1 AW13 circular/trig feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 AW13 circular/trig entitlement residue'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw13_16_circular_trig_v1:%' and is_active) then raise exception 'P1 AW13 circular/trig legacy activation'; end if;
end $$;

commit;
