-- AI-4 Chemistry Practice 1 deterministic diagnostics: Electrons in atoms.
-- Adds option-level mappings for all 18 current MCQs in this topic.
-- Server scoring remains authoritative; diagnostics explain the checked result only.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,subtopic,correct_answer,options_en) as (
    values
    (1908,'Shape of the p orbital','B','["s","p","d","f"]'::jsonb),
    (1917,'Orbital electron capacity','B','["s","p","d","f"]'::jsonb),
    (1927,'Effective nuclear charge across a period','C','["Decreases","Does not change","Increases","First decreases"]'::jsonb),
    (1931,'Atomic radius across a period','C','["Increases","Does not change","Decreases","First increases"]'::jsonb),
    (1937,'Group properties and outer electrons','C','["Same number of neutrons","Same number of energy levels","Same number of outer electrons","Same mass"]'::jsonb),
    (1939,'First energy level','B','["Can hold 8 electrons","Contains only s orbital","Contains p orbitals","Always fully filled"]'::jsonb),
    (1941,'Atomic radius trend down a group','C','["Decreases","Remains constant","Increases","First decreases"]'::jsonb),
    (1945,'Electron configuration of magnesium','A','["1s2 2s2 2p6 3s2","1s2 2s2 2p6 3s1","1s2 2s2 2p6 3p2","1s2 2s2 2p5 3s2"]'::jsonb),
    (1953,'Ionisation energy down a group','C','["Nuclear charge increases","Number of electrons decreases","Radius and shielding increase","Number of protons decreases"]'::jsonb),
    (1956,'Atomic radius across a period','C','["Number of protons decreases","Shielding increases","Effective nuclear charge increases","Number of energy levels decreases"]'::jsonb),
    (1960,'Electron capacity of the p subshell','B','["2","6","10","14"]'::jsonb),
    (1962,'Energy levels in the same period','B','["Same number of protons","Same number of electron shells","Same mass","Same group"]'::jsonb),
    (1968,'First ionisation energy across a period','C','["Always constant","Decreases","Increases","Equal to Ar"]'::jsonb),
    (1971,'Valence electrons and group properties','C','["Density","Colour","Chemical reactivity","Mass"]'::jsonb),
    (3036,'Capacity of the p sub-shell','C','["2","4","6","8"]'::jsonb),
    (3037,'Electron configuration of aluminium','A','["1s2 2s2 2p6 3s2 3p1","1s2 2s2 2p6 3s1","1s2 2s2 2p6 3s2","1s2 2s2 2p6 3p3"]'::jsonb),
    (3039,'First ionisation energy across Period 3','B','["Because atomic radius increases","Because nuclear charge increases while shielding stays roughly similar","Because the number of electron shells increases","Because the outer electron is farther from the nucleus"]'::jsonb),
    (3046,'Large jump in successive ionisation energies','B','["Na","Mg","Al","Si"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>4
     or q.is_active is not true
     or q.quality_status<>'published'
     or q.topic<>'Electrons in atoms'
     or q.subtopic<>e.subtopic
     or lower(coalesce(q.qtype,''))<>'mcq'
     or upper(trim(coalesce(q.correct_answer,'')))<>e.correct_answer
     or coalesce(q.options_text_en,'[]')::jsonb is distinct from e.options_en;

  if v_bad<>0 then
    raise exception 'AI-4 Chemistry Electrons diagnostic batch refused: one or more target questions changed';
  end if;

  if exists (
    select 1 from public.question_answer_diagnostics
    where question_id in (1908,1917,1927,1931,1937,1939,1941,1945,1953,1956,1960,1962,1968,1971,3036,3037,3039,3046)
      and quality_status='published'
  ) then
    raise exception 'AI-4 Chemistry Electrons diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
)
values
(1908,'mcq_option','A','s',false,'s_orbital_shape_confusion','Orbital shapes',
 's-орбиталь имеет сферическую, а не гантелеобразную форму.','s-orbital sferik, gantel shaklida emas.','An s orbital is spherical, not dumbbell-shaped.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Shape of the p orbital','{}'::jsonb,'published'),
(1908,'mcq_option','B','p',true,null,null,
 'Верно: p-орбитали обычно описываются как гантелеобразные.','To‘g‘ri: p-orbitallar odatda gantel shaklida tasvirlanadi.','Correct: p orbitals are commonly described as dumbbell-shaped.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Shape of the p orbital','{}'::jsonb,'published'),
(1908,'mcq_option','C','d',false,'d_orbital_shape_confusion','Orbital shapes',
 'd-орбитали имеют более сложную многолепестковую форму; стандартная гантелеобразная форма относится к p-орбиталям.','d-orbitallar murakkab ko‘p bo‘lakli shaklga ega; odatiy gantel shakli p-orbitallarga xos.','d orbitals have more complex multi-lobed shapes; the standard dumbbell shape belongs to p orbitals.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Shape of the p orbital','{}'::jsonb,'published'),
(1908,'mcq_option','D','f',false,'f_orbital_shape_confusion','Orbital shapes',
 'f-орбитали имеют ещё более сложную форму и не являются стандартными гантелеобразными орбиталями.','f-orbitallar yanada murakkab shaklga ega va odatiy gantel shaklidagi orbitallar emas.','f orbitals have still more complex shapes; they are not the standard dumbbell-shaped orbitals.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Shape of the p orbital','{}'::jsonb,'published'),
(1917,'mcq_option','A','s',false,'subshell_capacity_confusion','Subshell electron capacity',
 's-подуровень содержит одну орбиталь и вмещает максимум 2 электрона, а не 6.','s-qavatchada bitta orbital bo‘lib, ko‘pi bilan 2 elektron sig‘adi, 6 emas.','An s subshell contains one orbital and holds at most 2 electrons, not 6.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Orbital electron capacity','{}'::jsonb,'published'),
(1917,'mcq_option','B','p',true,null,null,
 'Верно: p-подуровень имеет три орбитали по два электрона, поэтому максимум равен 6.','To‘g‘ri: p-qavatchada uchta orbital bo‘lib, har birida ikki elektron, jami maksimum 6 ta.','Correct: a p subshell has three orbitals, each holding two electrons, so its maximum is 6.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Orbital electron capacity','{}'::jsonb,'published'),
(1917,'mcq_option','C','d',false,'subshell_capacity_confusion','Subshell electron capacity',
 'd-подуровень содержит пять орбиталей и вмещает до 10 электронов.','d-qavatchada beshta orbital bo‘lib, 10 tagacha elektron sig‘adi.','A d subshell contains five orbitals and can hold up to 10 electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Orbital electron capacity','{}'::jsonb,'published'),
(1917,'mcq_option','D','f',false,'subshell_capacity_confusion','Subshell electron capacity',
 'f-подуровень содержит семь орбиталей и вмещает до 14 электронов.','f-qavatchada yettita orbital bo‘lib, 14 tagacha elektron sig‘adi.','An f subshell contains seven orbitals and can hold up to 14 electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Orbital electron capacity','{}'::jsonb,'published'),
(1927,'mcq_option','A','Decreases',false,'periodic_trend_direction_error','Effective nuclear charge across a period',
 'В периоде число протонов растёт, а экранирование меняется относительно мало, поэтому эффективный заряд ядра в целом увеличивается, а не уменьшается.','Davr bo‘ylab protonlar soni ortadi, ekranlanish nisbatan kam o‘zgaradi, shuning uchun effektiv yadro zaryadi kamaymay, odatda ortadi.','Across a period proton number rises while shielding changes relatively little, so effective nuclear charge generally increases rather than decreases.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Effective nuclear charge across a period','{}'::jsonb,'published'),
(1927,'mcq_option','B','Does not change',false,'shielding_nuclear_charge_balance_error','Effective nuclear charge across a period',
 'Он не остаётся постоянным, поскольку заряд ядра увеличивается при добавлении протонов в периоде.','U o‘zgarmay qolmaydi, chunki davr bo‘ylab protonlar qo‘shilib, yadro zaryadi ortadi.','It does not stay constant because nuclear charge increases as protons are added across the period.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Effective nuclear charge across a period','{}'::jsonb,'published'),
(1927,'mcq_option','C','Increases',true,null,null,
 'Верно: эффективный заряд ядра в целом увеличивается слева направо в периоде.','To‘g‘ri: effektiv yadro zaryadi davr bo‘ylab chapdan o‘ngga odatda ortadi.','Correct: effective nuclear charge generally increases from left to right across a period.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Effective nuclear charge across a period','{}'::jsonb,'published'),
(1927,'mcq_option','D','First decreases',false,'periodic_trend_pattern_error','Effective nuclear charge across a period',
 'Общая тенденция — рост эффективного заряда ядра в периоде; общего правила о первоначальном снижении нет.','Umumiy tendensiya davr bo‘ylab effektiv yadro zaryadining ortishidir; avval kamayadi degan umumiy qoida yo‘q.','The general trend is increasing effective nuclear charge across the period; there is no general rule that it first decreases.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Effective nuclear charge across a period','{}'::jsonb,'published'),
(1931,'mcq_option','A','Increases',false,'atomic_radius_trend_reversal','Atomic radius across a period',
 'Атомный радиус в целом уменьшается в периоде, потому что растущий эффективный заряд ядра сильнее притягивает электроны.','Atom radiusi davr bo‘ylab odatda kamayadi, chunki ortayotgan effektiv yadro zaryadi elektronlarni kuchliroq tortadi.','Atomic radius generally decreases across a period because increasing effective nuclear charge pulls electrons closer.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1931,'mcq_option','B','Does not change',false,'atomic_radius_trend_ignored','Atomic radius across a period',
 'Атомный радиус не остаётся постоянным в периоде; более сильное притяжение ядра в целом уменьшает его.','Atom radiusi davr bo‘ylab o‘zgarmay qolmaydi; kuchliroq yadro tortishi uni odatda kichraytiradi.','Atomic radius is not constant across a period; the stronger nuclear attraction generally makes it smaller.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1931,'mcq_option','C','Decreases',true,null,null,
 'Верно: атомный радиус в целом уменьшается слева направо в периоде.','To‘g‘ri: atom radiusi davr bo‘ylab chapdan o‘ngga odatda kamayadi.','Correct: atomic radius generally decreases from left to right across a period.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1931,'mcq_option','D','First increases',false,'atomic_radius_pattern_error','Atomic radius across a period',
 'Общая тенденция в периоде — уменьшение радиуса, а не первоначальный общий рост.','Davr bo‘ylab umumiy tendensiya radiusning kamayishidir, avval umumiy ortish emas.','The overall trend across a period is a decrease, not an initial general increase.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1937,'mcq_option','A','Same number of neutrons',false,'group_property_neutron_confusion','Group properties and valence electrons',
 'Элементы одной группы не обязаны иметь одинаковое число нейтронов; оно может различаться даже у изотопов одного элемента.','Bir guruh elementlarida neytronlar soni bir xil bo‘lishi shart emas; hatto bir element izotoplarida ham u farq qiladi.','Elements in a group do not need the same neutron number; neutron number can vary between isotopes.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Group properties and outer electrons','{}'::jsonb,'published'),
(1937,'mcq_option','B','Same number of energy levels',false,'group_period_confusion','Group vs period structure',
 'Одинаковое число занятых энергетических уровней связано с одним периодом, а не одной группой.','Band energetik qavatlar sonining bir xil bo‘lishi bir guruhga emas, bir davrga xos.','Having the same number of occupied energy levels is associated with being in the same period, not the same group.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Group properties and outer electrons','{}'::jsonb,'published'),
(1937,'mcq_option','C','Same number of outer electrons',true,null,null,
 'Верно: элементы одной группы имеют одинаковое число валентных электронов, поэтому их химическое поведение сходно.','To‘g‘ri: bir guruh elementlarida valent elektronlar soni bir xil bo‘lib, kimyoviy xossalari o‘xshash bo‘ladi.','Correct: elements in the same group have the same number of valence electrons, giving similar chemical behaviour.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Group properties and outer electrons','{}'::jsonb,'published'),
(1937,'mcq_option','D','Same mass',false,'group_property_mass_confusion','Group properties and valence electrons',
 'Сходные химические свойства не вызваны одинаковой атомной массой; массы элементов группы различаются.','O‘xshash kimyoviy xossalar bir xil atom massasidan kelib chiqmaydi; guruh elementlarining massalari turlicha.','Similar chemical properties are not caused by equal atomic mass. Elements in a group have different masses.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Group properties and outer electrons','{}'::jsonb,'published'),
(1939,'mcq_option','A','Can hold 8 electrons',false,'first_shell_capacity_error','First energy level',
 'Первый энергетический уровень содержит только одну орбиталь 1s, поэтому вмещает максимум 2 электрона, а не 8.','Birinchi energetik qavatda faqat bitta 1s orbital bor, shuning uchun u 8 emas, ko‘pi bilan 2 elektron sig‘diradi.','The first energy level contains only one 1s orbital, so it can hold a maximum of 2 electrons, not 8.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First energy level','{}'::jsonb,'published'),
(1939,'mcq_option','B','Contains only s orbital',true,null,null,
 'Верно: первый энергетический уровень содержит только орбиталь 1s.','To‘g‘ri: birinchi energetik qavat faqat 1s orbitalni o‘z ichiga oladi.','Correct: the first energy level contains only the 1s orbital.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','First energy level','{}'::jsonb,'published'),
(1939,'mcq_option','C','Contains p orbitals',false,'invalid_1p_orbital','First energy level',
 'На первом энергетическом уровне p-орбиталей нет; они появляются начиная с n = 2.','Birinchi energetik qavatda p-orbitallar yo‘q; ular n = 2 dan boshlanadi.','There are no p orbitals in the first energy level; p orbitals begin at n = 2.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First energy level','{}'::jsonb,'published'),
(1939,'mcq_option','D','Always fully filled',false,'shell_occupancy_overgeneralization','First energy level',
 'Первый уровень не всегда заполнен полностью; например, у водорода в 1s находится только один электрон.','Birinchi qavat har doim to‘liq to‘lmagan; masalan, vodorodda 1s da faqat bitta elektron bor.','The first level is not always fully occupied; hydrogen, for example, has only one electron in 1s.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First energy level','{}'::jsonb,'published'),
(1941,'mcq_option','A','Decreases',false,'group_radius_trend_reversal','Atomic radius down a group',
 'Атомный радиус в целом увеличивается вниз по группе из-за появления дополнительных занятых оболочек.','Atom radiusi guruh bo‘ylab pastga qo‘shimcha band qavatlar paydo bo‘lgani uchun odatda ortadi.','Atomic radius generally increases down a group because additional occupied shells are added.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius trend down a group','{}'::jsonb,'published'),
(1941,'mcq_option','B','Remains constant',false,'group_radius_trend_ignored','Atomic radius down a group',
 'Радиус не остаётся постоянным; при движении вниз по группе добавляется новая занятая оболочка.','Radius o‘zgarmay qolmaydi; guruh bo‘ylab pastga har qadamda yangi band qavat qo‘shiladi.','Radius does not remain constant; each step down the group adds another occupied shell.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius trend down a group','{}'::jsonb,'published'),
(1941,'mcq_option','C','Increases',true,null,null,
 'Верно: атомный радиус в целом увеличивается вниз по группе.','To‘g‘ri: atom radiusi guruh bo‘ylab pastga odatda ortadi.','Correct: atomic radius generally increases down a group.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Atomic radius trend down a group','{}'::jsonb,'published'),
(1941,'mcq_option','D','First decreases',false,'group_radius_pattern_error','Atomic radius down a group',
 'Общая тенденция — рост радиуса вниз по группе, а не первоначальное уменьшение.','Umumiy tendensiya guruh bo‘ylab radiusning ortishidir, avval kamayish emas.','The general trend is increasing radius down the group, not a rule that it first decreases.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius trend down a group','{}'::jsonb,'published'),
(1945,'mcq_option','A','1s2 2s2 2p6 3s2',true,null,null,
 'Верно: у Mg 12 электронов, поэтому конфигурация 1s2 2s2 2p6 3s2.','To‘g‘ri: Mg da 12 elektron bo‘lib, konfiguratsiya 1s2 2s2 2p6 3s2.','Correct: Mg has 12 electrons, giving 1s2 2s2 2p6 3s2.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Electron configuration of magnesium','{}'::jsonb,'published'),
(1945,'mcq_option','B','1s2 2s2 2p6 3s1',false,'electron_count_error','Electron configuration of Mg',
 'Эта конфигурация содержит 11 электронов, но нейтральный магний имеет 12, так как Z = 12.','Bu konfiguratsiyada 11 elektron bor, neytral magniyda esa Z = 12 bo‘lgani uchun 12 elektron bo‘ladi.','This configuration contains 11 electrons, but neutral magnesium has 12 because Z = 12.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of magnesium','{}'::jsonb,'published'),
(1945,'mcq_option','C','1s2 2s2 2p6 3p2',false,'orbital_filling_order_error','Electron configuration of Mg',
 'После заполнения 2p электроны сначала занимают 3s, а не 3p. Магний заканчивается на 3s2.','2p to‘lgandan keyin elektronlar 3p dan oldin 3s ga joylashadi. Magniy 3s2 bilan tugaydi.','After 2p is filled, electrons enter 3s before 3p. Magnesium ends with 3s2, not 3p2.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of magnesium','{}'::jsonb,'published'),
(1945,'mcq_option','D','1s2 2s2 2p5 3s2',false,'subshell_filling_error','Electron configuration of Mg',
 'В основном состоянии магния подуровень 2p должен быть заполнен до 2p6 до заполнения 3s.','Magniyning asosiy holatida 3s to‘lishidan oldin 2p qavatcha 2p6 gacha to‘lishi kerak.','The 2p subshell should be filled to 2p6 before electrons occupy 3s in ground-state magnesium.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of magnesium','{}'::jsonb,'published'),
(1953,'mcq_option','A','Nuclear charge increases',false,'ie_group_cause_confusion','Ionisation energy down a group',
 'Заряд ядра вниз по группе действительно растёт, но сам по себе он усиливал бы притяжение; снижение энергии ионизации главным образом объясняется большим расстоянием и экранированием.','Yadro zaryadi guruh bo‘ylab ortadi, lekin bu o‘zi tortishni kuchaytirardi; ionlanish energiyasining kamayishi asosan katta masofa va ekranlanish bilan tushuntiriladi.','Nuclear charge does increase down a group, but this alone would strengthen attraction; the observed fall in ionisation energy is mainly explained by greater distance and shielding.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Ionisation energy down a group','{}'::jsonb,'published'),
(1953,'mcq_option','B','Number of electrons decreases',false,'electron_number_trend_error','Ionisation energy down a group',
 'Число электронов вниз по группе не уменьшается; у атомов в целом становится больше электронов.','Guruh bo‘ylab pastga elektronlar soni kamaymaydi; atomlarda odatda elektronlar ko‘payadi.','The number of electrons does not decrease down a group; atoms generally contain more electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Ionisation energy down a group','{}'::jsonb,'published'),
(1953,'mcq_option','C','Radius and shielding increase',true,null,null,
 'Верно: увеличение радиуса и экранирования ослабляет притяжение внешнего электрона, поэтому энергия ионизации вниз по группе обычно уменьшается.','To‘g‘ri: radius va ekranlanish ortishi tashqi elektron tortilishini zaiflashtiradi, shuning uchun ionlanish energiyasi guruh bo‘ylab odatda kamayadi.','Correct: increased atomic radius and shielding weaken attraction to the outer electron, so ionisation energy generally falls down a group.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Ionisation energy down a group','{}'::jsonb,'published'),
(1953,'mcq_option','D','Number of protons decreases',false,'proton_number_trend_error','Ionisation energy down a group',
 'Число протонов вниз по группе увеличивается, а не уменьшается.','Guruh bo‘ylab pastga protonlar soni kamaymay, ortadi.','Proton number increases, not decreases, down a group.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Ionisation energy down a group','{}'::jsonb,'published'),
(1956,'mcq_option','A','Number of protons decreases',false,'proton_trend_reversal','Atomic radius across a period',
 'Число протонов в периоде увеличивается, а не уменьшается.','Davr bo‘ylab protonlar soni kamaymay, ortadi.','Proton number increases rather than decreases across a period.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1956,'mcq_option','B','Shielding increases',false,'shielding_explanation_error','Atomic radius across a period',
 'Экранирование в периоде меняется относительно мало, так как электроны добавляются на тот же главный уровень; его рост не является основной причиной уменьшения радиуса.','Davr bo‘ylab elektronlar bir xil asosiy qavatga qo‘shilgani uchun ekranlanish nisbatan kam o‘zgaradi; radiusning kamayishiga asosiy sabab ekranlanishning ortishi emas.','Shielding changes relatively little across a period because electrons are added to the same main shell; increased shielding is not the main cause of the smaller radius.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1956,'mcq_option','C','Effective nuclear charge increases',true,null,null,
 'Верно: рост эффективного заряда ядра сильнее притягивает электронное облако и уменьшает атомный радиус в периоде.','To‘g‘ri: effektiv yadro zaryadining ortishi elektron bulutini yaqinroq tortib, davr bo‘ylab atom radiusini kamaytiradi.','Correct: increasing effective nuclear charge pulls the electron cloud closer, reducing atomic radius across the period.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1956,'mcq_option','D','Number of energy levels decreases',false,'period_shell_count_error','Atomic radius across a period',
 'Элементы одного периода имеют одинаковое число занятых главных оболочек; число энергетических уровней не уменьшается.','Bir davr elementlarida band asosiy qavatlar soni bir xil; energetik qavatlar soni kamaymaydi.','Elements in the same period have the same number of occupied principal shells; the number of energy levels does not decrease.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Atomic radius across a period','{}'::jsonb,'published'),
(1960,'mcq_option','A','2',false,'p_capacity_underestimate','p subshell capacity',
 'Два электрона — это вместимость одной орбитали, а не всего p-подуровня. В p-подуровне три орбитали.','Ikki elektron bitta orbital sig‘imi, butun p-qavatcha emas. p-qavatchada uchta orbital bor.','Two electrons is the capacity of one orbital, not the whole p subshell. A p subshell has three orbitals.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron capacity of the p subshell','{}'::jsonb,'published'),
(1960,'mcq_option','B','6',true,null,null,
 'Верно: p-подуровень имеет три орбитали × два электрона = 6 электронов.','To‘g‘ri: p-qavatchada uchta orbital × ikki elektron = 6 elektron.','Correct: a p subshell has three orbitals × two electrons = 6 electrons.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Electron capacity of the p subshell','{}'::jsonb,'published'),
(1960,'mcq_option','C','10',false,'p_d_capacity_confusion','p vs d subshell capacity',
 'Десять электронов — максимальная вместимость d-подуровня, а не p-подуровня.','O‘n elektron d-qavatchaning maksimal sig‘imi, p-qavatchaniki emas.','Ten electrons is the maximum capacity of a d subshell, not a p subshell.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron capacity of the p subshell','{}'::jsonb,'published'),
(1960,'mcq_option','D','14',false,'p_f_capacity_confusion','p vs f subshell capacity',
 'Четырнадцать электронов — максимальная вместимость f-подуровня, а не p-подуровня.','O‘n to‘rt elektron f-qavatchaning maksimal sig‘imi, p-qavatchaniki emas.','Fourteen electrons is the maximum capacity of an f subshell, not a p subshell.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron capacity of the p subshell','{}'::jsonb,'published'),
(1962,'mcq_option','A','Same number of protons',false,'period_atomic_number_confusion','Period and electron shells',
 'У элементов одного периода разное число протонов; оно увеличивается слева направо.','Bir davr elementlarida protonlar soni turlicha bo‘lib, chapdan o‘ngga ortadi.','Elements in a period have different proton numbers; proton number increases from left to right.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Energy levels in the same period','{}'::jsonb,'published'),
(1962,'mcq_option','B','Same number of electron shells',true,null,null,
 'Верно: элементы одного периода имеют одинаковое число занятых главных электронных оболочек.','To‘g‘ri: bir davr elementlarida band asosiy elektron qavatlar soni bir xil.','Correct: elements in the same period have the same number of occupied principal electron shells.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Energy levels in the same period','{}'::jsonb,'published'),
(1962,'mcq_option','C','Same mass',false,'period_mass_confusion','Period and electron shells',
 'Элементы одного периода не имеют одинаковой атомной массы.','Bir davr elementlarining atom massalari bir xil emas.','Elements in the same period do not have the same atomic mass.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Energy levels in the same period','{}'::jsonb,'published'),
(1962,'mcq_option','D','Same group',false,'period_group_confusion','Period vs group',
 'Один период не означает одну группу. Периоды — горизонтальные ряды, группы — вертикальные столбцы.','Bir davr bir guruh degani emas. Davrlar gorizontal qatorlar, guruhlar vertikal ustunlar.','Being in the same period does not mean being in the same group. Periods are horizontal rows; groups are vertical columns.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Energy levels in the same period','{}'::jsonb,'published'),
(1968,'mcq_option','A','Always constant',false,'ie_period_trend_ignored','First ionisation energy across a period',
 'Первая энергия ионизации не постоянна; в целом она растёт в периоде, хотя есть небольшие исключения.','Birinchi ionlanish energiyasi doimiy emas; kichik istisnolar bilan davr bo‘ylab odatda ortadi.','First ionisation energy is not constant; it generally rises across a period, with small exceptions.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across a period','{}'::jsonb,'published'),
(1968,'mcq_option','B','Decreases',false,'ie_period_trend_reversal','First ionisation energy across a period',
 'Общая тенденция — увеличение, а не уменьшение, поскольку эффективное притяжение ядра усиливается.','Umumiy tendensiya kamayish emas, ortishdir, chunki effektiv yadro tortishi kuchayadi.','The general trend is an increase, not a decrease, because effective nuclear attraction becomes stronger.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across a period','{}'::jsonb,'published'),
(1968,'mcq_option','C','Increases',true,null,null,
 'Верно: первая энергия ионизации в целом увеличивается в периоде, хотя есть небольшие исключения.','To‘g‘ri: birinchi ionlanish energiyasi davr bo‘ylab odatda ortadi, garchi kichik istisnolar bo‘lsa ham.','Correct: first ionisation energy generally increases across a period, although the trend has small exceptions.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','First ionisation energy across a period','{}'::jsonb,'published'),
(1968,'mcq_option','D','Equal to Ar',false,'ie_ar_confusion','Ionisation energy vs relative atomic mass',
 'Энергия ионизации — это энергия удаления электрона; она не равна относительной атомной массе Ar.','Ionlanish energiyasi elektronni chiqarish uchun kerak bo‘lgan energiya bo‘lib, nisbiy atom massasi Ar ga teng emas.','Ionisation energy is an energy required to remove an electron; it is not equal to relative atomic mass Ar.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across a period','{}'::jsonb,'published'),
(1971,'mcq_option','A','Density',false,'valence_property_confusion','Valence electrons and properties',
 'Плотность зависит от нескольких структурных и массовых факторов и не объясняется просто одинаковым числом валентных электронов.','Zichlik bir nechta tuzilish va massa omillariga bog‘liq bo‘lib, faqat valent elektronlar sonining bir xilligi bilan tushuntirilmaydi.','Density depends on several structural and mass factors and is not directly explained simply by having the same number of valence electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Valence electrons and group properties','{}'::jsonb,'published'),
(1971,'mcq_option','B','Colour',false,'valence_property_confusion','Valence electrons and properties',
 'Цвет не является определяющим свойством группы, которое объясняется одинаковым числом валентных электронов.','Rang valent elektronlar sonining bir xilligi bilan izohlanadigan asosiy guruh xossasi emas.','Colour is not the defining group property explained by having the same number of valence electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Valence electrons and group properties','{}'::jsonb,'published'),
(1971,'mcq_option','C','Chemical reactivity',true,null,null,
 'Верно: сходное строение валентных электронов приводит к сходной химической активности элементов одной группы.','To‘g‘ri: o‘xshash valent elektron tuzilishi bir guruhda o‘xshash kimyoviy faollikka olib keladi.','Correct: similar valence-electron arrangements lead to similar patterns of chemical reactivity within a group.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Valence electrons and group properties','{}'::jsonb,'published'),
(1971,'mcq_option','D','Mass',false,'valence_mass_confusion','Valence electrons and properties',
 'Атомная масса определяется главным образом протонами и нейтронами и не объясняется числом валентных электронов.','Atom massasi asosan proton va neytronlar bilan belgilanadi, valent elektronlar soni bilan emas.','Atomic mass is determined mainly by protons and neutrons and is not explained by the number of valence electrons.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Valence electrons and group properties','{}'::jsonb,'published'),
(3036,'mcq_option','A','2',false,'p_capacity_underestimate','3p subshell capacity',
 'Подуровень 3p содержит три орбитали, а не одну, поэтому его максимум больше 2.','3p qavatchada bitta emas, uchta orbital bor, shuning uchun maksimum 2 dan katta.','The 3p subshell contains three orbitals, not one, so its maximum is greater than 2.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Capacity of the p sub-shell','{}'::jsonb,'published'),
(3036,'mcq_option','B','4',false,'p_capacity_count_error','3p subshell capacity',
 'Три p-орбитали могут содержать по два электрона, поэтому получается 6, а не 4.','Uchta p-orbitalning har biri ikki elektron sig‘diradi, jami 4 emas, 6 bo‘ladi.','Three p orbitals can each hold two electrons, giving 6 rather than 4.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Capacity of the p sub-shell','{}'::jsonb,'published'),
(3036,'mcq_option','C','6',true,null,null,
 'Верно: 3p содержит три орбитали и вмещает максимум 6 электронов.','To‘g‘ri: 3p da uchta orbital bor va ko‘pi bilan 6 elektron sig‘adi.','Correct: 3p has three orbitals and can hold a maximum of 6 electrons.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Capacity of the p sub-shell','{}'::jsonb,'published'),
(3036,'mcq_option','D','8',false,'p_capacity_overestimate','3p subshell capacity',
 'В p-подуровне только три орбитали, поэтому максимум равен 6, а не 8.','p-qavatchada faqat uchta orbital bor, shuning uchun maksimum 8 emas, 6.','A p subshell has only three orbitals, so its maximum occupancy is 6 rather than 8.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Capacity of the p sub-shell','{}'::jsonb,'published'),
(3037,'mcq_option','A','1s2 2s2 2p6 3s2 3p1',true,null,null,
 'Верно: у алюминия 13 электронов, поэтому конфигурация 1s2 2s2 2p6 3s2 3p1.','To‘g‘ri: alyuminiyda 13 elektron bo‘lib, konfiguratsiya 1s2 2s2 2p6 3s2 3p1.','Correct: aluminium has 13 electrons, giving 1s2 2s2 2p6 3s2 3p1.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Electron configuration of aluminium','{}'::jsonb,'published'),
(3037,'mcq_option','B','1s2 2s2 2p6 3s1',false,'electron_count_error','Electron configuration of Al',
 'Эта конфигурация содержит 11 электронов, но нейтральный алюминий имеет 13, так как Z = 13.','Bu konfiguratsiyada 11 elektron bor, neytral alyuminiyda esa Z = 13 bo‘lgani uchun 13 elektron bo‘ladi.','This configuration has 11 electrons, but neutral aluminium has 13 because Z = 13.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of aluminium','{}'::jsonb,'published'),
(3037,'mcq_option','C','1s2 2s2 2p6 3s2',false,'electron_count_error','Electron configuration of Al',
 'Эта конфигурация содержит 12 электронов и соответствует Mg, а не Al.','Bu konfiguratsiyada 12 elektron bor va Al emas, Mg ga mos keladi.','This configuration has 12 electrons and corresponds to Mg, not Al.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of aluminium','{}'::jsonb,'published'),
(3037,'mcq_option','D','1s2 2s2 2p6 3p3',false,'orbital_filling_order_error','Electron configuration of Al',
 'Подуровень 3s заполняется раньше 3p. У алюминия должно быть 3s2 перед одним электроном 3p.','3s qavatcha 3p dan oldin to‘ladi. Alyuminiyda bitta 3p elektrondan oldin 3s2 bo‘lishi kerak.','The 3s subshell fills before 3p. Aluminium should contain 3s2 before the single 3p electron.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Electron configuration of aluminium','{}'::jsonb,'published'),
(3039,'mcq_option','A','Because atomic radius increases',false,'period3_radius_trend_reversal','Period 3 ionisation energy',
 'Атомный радиус в третьем периоде в целом уменьшается, а не увеличивается.','3-davr bo‘ylab atom radiusi odatda kamayadi, ortmaydi.','Atomic radius generally decreases across Period 3, not increases.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across Period 3','{}'::jsonb,'published'),
(3039,'mcq_option','B','Because nuclear charge increases while shielding stays roughly similar',true,null,null,
 'Верно: в третьем периоде заряд ядра растёт, а экранирование остаётся примерно сходным, поэтому притяжение внешнего электрона в целом усиливается.','To‘g‘ri: 3-davr bo‘ylab yadro zaryadi ortadi, ekranlanish taxminan o‘xshash qoladi va tashqi elektron tortilishi odatda kuchayadi.','Correct: across Period 3 nuclear charge rises while shielding is broadly similar, so attraction to the outer electron generally strengthens.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','First ionisation energy across Period 3','{}'::jsonb,'published'),
(3039,'mcq_option','C','Because the number of electron shells increases',false,'period_shell_count_error','Period 3 ionisation energy',
 'Все атомы третьего периода имеют одинаковое число занятых главных оболочек; их число в периоде не растёт.','3-davr atomlarida band asosiy qavatlar soni bir xil; davr bo‘ylab qavatlar soni ortmaydi.','All Period 3 atoms have the same number of occupied principal shells; the number of shells does not increase across the period.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across Period 3','{}'::jsonb,'published'),
(3039,'mcq_option','D','Because the outer electron is farther from the nucleus',false,'period3_distance_trend_reversal','Period 3 ionisation energy',
 'Внешний электрон в целом сильнее притягивается и находится ближе к ядру при росте эффективного заряда; он не становится всё дальше.','Effektiv yadro zaryadi ortganda tashqi elektron odatda kuchliroq tortilib, yaqinlashadi; u tobora uzoqlashmaydi.','The outer electron is generally pulled closer across the period as effective nuclear charge rises; it is not progressively farther away.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','First ionisation energy across Period 3','{}'::jsonb,'published'),
(3046,'mcq_option','A','Na',false,'successive_ie_valence_count_error','Successive ionisation energies',
 'У Na один валентный электрон, поэтому большой скачок ожидается между первой и второй энергиями ионизации, а не между второй и третьей.','Na da bitta valent elektron bor, shuning uchun katta sakrash ikkinchi va uchinchi emas, birinchi va ikkinchi ionlanish energiyalari orasida kutiladi.','Na has one valence electron, so its large jump is expected between the first and second ionisation energies, not the second and third.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Large jump in successive ionisation energies','{}'::jsonb,'published'),
(3046,'mcq_option','B','Mg',true,null,null,
 'Верно: у Mg два валентных электрона, поэтому большой скачок появляется между второй и третьей энергиями ионизации.','To‘g‘ri: Mg da ikki valent elektron bor, shuning uchun katta sakrash ikkinchi va uchinchi ionlanish energiyalari orasida paydo bo‘ladi.','Correct: Mg has two valence electrons, so a large jump appears between the second and third ionisation energies.',
 'Повторите правило и свяжите его с ключевым признаком вопроса.','Qoidani takrorlab, uni savoldagi asosiy belgi bilan bog‘lang.','Review the rule and link it to the key feature in the question.',
 'Electrons in atoms','Large jump in successive ionisation energies','{}'::jsonb,'published'),
(3046,'mcq_option','C','Al',false,'successive_ie_valence_count_error','Successive ionisation energies',
 'У Al три валентных электрона, поэтому большой скачок ожидается после удаления третьего электрона — между третьей и четвёртой энергиями ионизации.','Al da uchta valent elektron bor, shuning uchun katta sakrash uchinchi elektron chiqarilgandan keyin, uchinchi va to‘rtinchi ionlanish energiyalari orasida kutiladi.','Al has three valence electrons, so the major jump is expected after the third electron is removed, between the third and fourth ionisation energies.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Large jump in successive ionisation energies','{}'::jsonb,'published'),
(3046,'mcq_option','D','Si',false,'successive_ie_valence_count_error','Successive ionisation energies',
 'У Si четыре валентных электрона, поэтому большой скачок ожидается между четвёртой и пятой энергиями ионизации.','Si da to‘rtta valent elektron bor, shuning uchun katta sakrash to‘rtinchi va beshinchi ionlanish energiyalari orasida kutiladi.','Si has four valence electrons, so its large jump is expected between the fourth and fifth ionisation energies.',
 'Сверьте выбранный вариант с правилом для этой электронной структуры или периодической тенденции.','Tanlangan javobni shu elektron tuzilishi yoki davriy tendensiya qoidasi bilan tekshiring.','Check the chosen option against the relevant electron-structure or periodic-trend rule.',
 'Electrons in atoms','Large jump in successive ionisation energies','{}'::jsonb,'published');
