-- iClub APP — P0-02 safe legacy assessment contract v4
-- VERIFIED PRODUCTION-GATE MIGRATION.
-- Additive only with respect to existing production data and legacy access paths.
-- It creates private v4 runtime state and new RPCs only.
-- It does NOT remove questions_public_read, Tour policies, old RPCs, rows, IDs, progress, ratings or history.

begin;

-- =========================================================
-- 1. Private runtime state
-- =========================================================

create table if not exists public.practice_sessions_v4 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  subject_id bigint not null references public.subjects(id),
  pool_id bigint not null references public.practice_pools(id),
  client_session_id text not null,
  question_ids bigint[] not null,
  legacy_attempt_id bigint unique references public.practice_attempts(id),
  status text not null default 'in_progress'
    check (status in ('in_progress','finalized','abandoned')),
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  unique (user_id, client_session_id),
  check (cardinality(question_ids) = 10),
  check (length(client_session_id) between 8 and 128)
);

create table if not exists public.practice_session_answers_v4 (
  session_id bigint not null references public.practice_sessions_v4(id) on delete cascade,
  question_id bigint not null references public.questions(id),
  user_answer text,
  picked_index integer,
  is_correct boolean not null,
  time_spent integer not null default 0 check (time_spent >= 0),
  answered_at timestamptz not null default now(),
  primary key (session_id, question_id)
);

create table if not exists public.tour_session_runtime_v4 (
  attempt_id bigint primary key references public.tour_attempts(id) on delete cascade,
  user_id uuid not null,
  tour_id bigint not null references public.tours(id),
  client_session_id text not null,
  question_ids bigint[] not null,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, client_session_id),
  unique (user_id, tour_id),
  check (cardinality(question_ids) = 20),
  check (length(client_session_id) between 8 and 128)
);

create table if not exists public.tour_session_answers_v4 (
  attempt_id bigint not null references public.tour_session_runtime_v4(attempt_id) on delete cascade,
  question_id bigint not null references public.questions(id),
  user_answer text,
  answered boolean not null default true,
  is_correct boolean not null default false,
  time_spent integer not null default 0 check (time_spent >= 0),
  finish_reason text,
  answered_at timestamptz not null default now(),
  primary key (attempt_id, question_id)
);

alter table public.practice_sessions_v4 enable row level security;
alter table public.practice_session_answers_v4 enable row level security;
alter table public.tour_session_runtime_v4 enable row level security;
alter table public.tour_session_answers_v4 enable row level security;

-- Browser roles must never access private runtime tables directly.
revoke all on table public.practice_sessions_v4 from public, anon, authenticated;
revoke all on table public.practice_session_answers_v4 from public, anon, authenticated;
revoke all on table public.tour_session_runtime_v4 from public, anon, authenticated;
revoke all on table public.tour_session_answers_v4 from public, anon, authenticated;
revoke all on sequence public.practice_sessions_v4_id_seq from public, anon, authenticated;

-- =========================================================
-- 2. Internal evaluators
-- =========================================================

-- Practice evaluator mirrors current submit_practice_attempt correctness semantics.
create or replace function public.iclub_eval_practice_question_safe_v4(
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_q public.questions%rowtype;
  v_selected text;
  v_selected_norm text;
  v_correct boolean := false;
begin
  select q.* into v_q
  from public.questions q
  where q.id=p_question_id and q.is_active is true;

  if v_q.id is null then
    raise exception 'question_not_found_or_inactive' using errcode='P0002';
  end if;

  if lower(coalesce(v_q.qtype,''))='mcq' then
    if p_picked_index is not null and p_picked_index between 0 and 25 then
      v_selected := chr(65+p_picked_index);
    elsif trim(coalesce(p_user_answer,'')) ~ '^[0-9]+$'
      and trim(p_user_answer)::integer between 0 and 25 then
      v_selected := chr(65+trim(p_user_answer)::integer);
    else
      v_selected := upper(trim(coalesce(p_user_answer,'')));
    end if;

    v_correct := (
      upper(trim(coalesce(v_selected,''))) = upper(trim(coalesce(v_q.correct_answer,'')))
      or public.iclub_normalize_answer(v_selected) = public.iclub_normalize_answer(v_q.correct_answer)
    );
  else
    v_selected := trim(coalesce(p_user_answer,''));
    v_selected_norm := public.iclub_normalize_answer(v_selected);

    v_correct := exists(
      select 1
      from regexp_split_to_table(coalesce(v_q.correct_answer,''), '\\|') accepted_answer
      where public.iclub_normalize_answer(accepted_answer)=v_selected_norm
    );

    if not v_correct
       and public.iclub_is_numeric(v_selected)
       and public.iclub_is_numeric(v_q.correct_answer) then
      v_correct := replace(v_selected,',','.')::numeric = replace(v_q.correct_answer,',','.')::numeric;
    end if;
  end if;

  return jsonb_build_object(
    'selected_answer',nullif(v_selected,''),
    'is_correct',v_correct
  );
end;
$$;

-- Tour input evaluator mirrors current client semantics: strict sign/format + 1e-9 numeric tolerance.
create or replace function public.iclub_tour_input_is_correct_v4(
  p_user_answer text,
  p_expected_answer text
)
returns boolean
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_user text := trim(translate(coalesce(p_user_answer,''), '−–—', '---'));
  v_expected text := trim(translate(coalesce(p_expected_answer,''), '−–—', '---'));
  v_user_num double precision;
  v_expected_num double precision;
  v_diff double precision;
  v_scale double precision;
  v_expected_signed boolean;
begin
  if v_user='' or v_expected='' then return false; end if;

  if v_expected ~ '^[+-]?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$' then
    if v_user !~ '^[+-]?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$' then return false; end if;

    v_expected_signed := v_expected ~ '^[+-]';
    if v_expected_signed then
      if left(v_expected,1) <> left(v_user,1) then return false; end if;
    elsif v_user ~ '^[+-]' then
      return false;
    end if;

    begin
      v_user_num := v_user::double precision;
      v_expected_num := v_expected::double precision;
    exception when others then
      return false;
    end;

    v_diff := abs(v_user_num-v_expected_num);
    v_scale := greatest(1::double precision,abs(v_user_num),abs(v_expected_num));
    return v_diff <= v_scale*1e-9;
  end if;

  if v_expected ~ '^[A-Z][A-Za-z0-9]*$' then
    if v_user !~ '^[A-Za-z][A-Za-z0-9]*$' then return false; end if;
    return lower(v_user)=lower(v_expected);
  end if;

  return lower(regexp_replace(v_user,'\\s+','','g'))
       = lower(regexp_replace(v_expected,'\\s+','','g'));
end;
$$;

create or replace function public.iclub_eval_tour_question_safe_v4(
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer default null,
  p_answered boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_q public.questions%rowtype;
  v_selected text;
  v_correct boolean := false;
begin
  select q.* into v_q
  from public.questions q
  where q.id=p_question_id and q.is_active is true;

  if v_q.id is null then
    raise exception 'question_not_found_or_inactive' using errcode='P0002';
  end if;

  if coalesce(p_answered,true) is false then
    return jsonb_build_object('selected_answer',null,'is_correct',false);
  end if;

  if lower(coalesce(v_q.qtype,''))='mcq' then
    if p_picked_index is not null and p_picked_index between 0 and 25 then
      v_selected := chr(65+p_picked_index);
    elsif upper(trim(coalesce(p_user_answer,''))) ~ '^[A-Z]$' then
      v_selected := upper(trim(p_user_answer));
    elsif trim(coalesce(p_user_answer,'')) ~ '^[0-9]+$'
      and trim(p_user_answer)::integer between 0 and 25 then
      v_selected := chr(65+trim(p_user_answer)::integer);
    else
      v_selected := upper(trim(coalesce(p_user_answer,'')));
    end if;

    v_correct := upper(trim(coalesce(v_selected,'')))=upper(trim(coalesce(v_q.correct_answer,'')));
  else
    v_selected := trim(coalesce(p_user_answer,''));
    v_correct := public.iclub_tour_input_is_correct_v4(v_selected,v_q.correct_answer);
  end if;

  return jsonb_build_object(
    'selected_answer',nullif(v_selected,''),
    'is_correct',v_correct
  );
end;
$$;

revoke all on function public.iclub_eval_practice_question_safe_v4(bigint,text,integer) from public,anon,authenticated;
revoke all on function public.iclub_tour_input_is_correct_v4(text,text) from public,anon,authenticated;
revoke all on function public.iclub_eval_tour_question_safe_v4(bigint,text,integer,boolean) from public,anon,authenticated;

-- =========================================================
-- 3. Practice safe contract
-- =========================================================

create or replace function public.start_practice_session_safe_v4(
  p_pool_id bigint,
  p_client_session_id text,
  p_question_ids bigint[]
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_pool public.practice_pools%rowtype;
  v_s public.practice_sessions_v4%rowtype;
  v_qids bigint[];
  v_allowed integer;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if p_pool_id is null or p_pool_id <= 0 then raise exception 'invalid_pool_id' using errcode='22023'; end if;
  if p_client_session_id is null or length(trim(p_client_session_id)) not between 8 and 128 then
    raise exception 'invalid_client_session_id' using errcode='22023';
  end if;

  select * into v_s
  from public.practice_sessions_v4 s
  where s.user_id=v_uid and s.client_session_id=trim(p_client_session_id)
  limit 1;

  if v_s.id is not null then
    if v_s.pool_id <> p_pool_id then
      raise exception 'client_session_scope_mismatch' using errcode='22023';
    end if;
    return jsonb_build_object(
      'session_id',v_s.id,'status',v_s.status,
      'question_count',cardinality(v_s.question_ids),
      'legacy_attempt_id',v_s.legacy_attempt_id,'resumed',true
    );
  end if;

  select * into v_pool
  from public.practice_pools p
  where p.id=p_pool_id and p.is_active is true;
  if v_pool.id is null then raise exception 'pool_not_found_or_inactive' using errcode='P0002'; end if;

  if p_question_ids is null or cardinality(p_question_ids) <> 10 then
    raise exception 'practice_question_selection_must_have_10' using errcode='22023';
  end if;

  select array_agg(x.qid order by x.ord)
  into v_qids
  from unnest(p_question_ids) with ordinality x(qid,ord)
  where x.qid is not null;

  if coalesce(cardinality(v_qids),0) <> 10 then
    raise exception 'practice_question_selection_must_have_10' using errcode='22023';
  end if;

  if (select count(distinct qid) from unnest(v_qids) q(qid)) <> 10 then
    raise exception 'duplicate_question_ids' using errcode='22023';
  end if;

  select count(*)::integer into v_allowed
  from public.practice_pool_questions ppq
  join public.questions q on q.id=ppq.question_id
  where ppq.pool_id=p_pool_id
    and ppq.is_active is true
    and q.is_active is true
    and q.subject_id=v_pool.subject_id
    and ppq.question_id=any(v_qids);

  if v_allowed <> 10 then
    raise exception 'question_not_in_active_pool' using errcode='22023';
  end if;

  insert into public.practice_sessions_v4(
    user_id,subject_id,pool_id,client_session_id,question_ids
  ) values(
    v_uid,v_pool.subject_id,p_pool_id,trim(p_client_session_id),v_qids
  ) returning * into v_s;

  return jsonb_build_object(
    'session_id',v_s.id,'status',v_s.status,
    'question_count',10,'legacy_attempt_id',null,'resumed',false
  );
exception when unique_violation then
  select * into v_s
  from public.practice_sessions_v4 s
  where s.user_id=v_uid and s.client_session_id=trim(p_client_session_id)
  limit 1;
  if v_s.id is null then raise; end if;
  if v_s.pool_id <> p_pool_id then
    raise exception 'client_session_scope_mismatch' using errcode='22023';
  end if;
  return jsonb_build_object(
    'session_id',v_s.id,'status',v_s.status,
    'question_count',cardinality(v_s.question_ids),
    'legacy_attempt_id',v_s.legacy_attempt_id,'resumed',true
  );
end;
$$;

create or replace function public.get_practice_session_questions_safe_v4(p_session_id bigint)
returns table(
  order_no integer,
  id bigint,
  subject_id bigint,
  time_limit_sec integer,
  question_text text,
  question_text_ru text,
  question_text_uz text,
  question_text_en text,
  options_text text,
  options_text_ru text,
  options_text_uz text,
  options_text_en text,
  image_url text,
  topic text,
  subtopic text,
  difficulty text,
  qtype text,
  book_ref text
)
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select x.ord::integer,q.id,q.subject_id,q.time_limit_sec,
    q.question_text,q.question_text_ru,q.question_text_uz,q.question_text_en,
    q.options_text,q.options_text_ru,q.options_text_uz,q.options_text_en,
    q.image_url,q.topic,q.subtopic,q.difficulty,q.qtype,q.book_ref
  from public.practice_sessions_v4 s
  cross join lateral unnest(s.question_ids) with ordinality x(qid,ord)
  join public.questions q on q.id=x.qid and q.is_active is true
  where s.id=p_session_id and s.user_id=auth.uid()
  order by x.ord;
$$;

create or replace function public.submit_practice_session_answer_safe_v4(
  p_session_id bigint,
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer,
  p_time_spent integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_s public.practice_sessions_v4%rowtype;
  v_q public.questions%rowtype;
  v_eval jsonb;
  v_saved public.practice_session_answers_v4%rowtype;
  v_answered integer;
  v_score integer;
  v_was_existing boolean := false;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;

  select * into v_s
  from public.practice_sessions_v4 s
  where s.id=p_session_id and s.user_id=v_uid;
  if v_s.id is null then raise exception 'session_not_found' using errcode='P0002'; end if;
  if v_s.status <> 'in_progress' then raise exception 'session_not_in_progress' using errcode='55000'; end if;
  if not (p_question_id=any(v_s.question_ids)) then raise exception 'question_not_in_session' using errcode='22023'; end if;

  select * into v_q
  from public.questions q
  where q.id=p_question_id and q.is_active is true and q.subject_id=v_s.subject_id;
  if v_q.id is null then raise exception 'question_not_found_or_subject_mismatch' using errcode='P0002'; end if;

  select * into v_saved
  from public.practice_session_answers_v4 a
  where a.session_id=p_session_id and a.question_id=p_question_id;
  v_was_existing := v_saved.session_id is not null;

  if not v_was_existing then
    v_eval := public.iclub_eval_practice_question_safe_v4(p_question_id,p_user_answer,p_picked_index);

    insert into public.practice_session_answers_v4(
      session_id,question_id,user_answer,picked_index,is_correct,time_spent,answered_at
    ) values(
      p_session_id,p_question_id,v_eval->>'selected_answer',p_picked_index,
      coalesce((v_eval->>'is_correct')::boolean,false),
      greatest(coalesce(p_time_spent,0),0),now()
    ) on conflict(session_id,question_id) do nothing;

    select * into v_saved
    from public.practice_session_answers_v4 a
    where a.session_id=p_session_id and a.question_id=p_question_id;
  end if;

  if v_saved.session_id is null then
    raise exception 'practice_answer_save_failed' using errcode='55000';
  end if;

  select count(*)::integer,count(*) filter(where a.is_correct is true)::integer
  into v_answered,v_score
  from public.practice_session_answers_v4 a
  where a.session_id=p_session_id;

  return jsonb_build_object(
    'ok',true,'session_id',p_session_id,'question_id',p_question_id,
    'is_correct',v_saved.is_correct,
    'answered',v_answered,'score_so_far',v_score,'question_count',10,
    'correct_answer',v_q.correct_answer,
    'explanation',v_q.explanation,
    'explanation_ru',v_q.explanation_ru,
    'explanation_uz',v_q.explanation_uz,
    'explanation_en',v_q.explanation_en,
    'idempotent',v_was_existing
  );
end;
$$;

create or replace function public.finalize_practice_session_safe_v4(
  p_session_id bigint,
  p_total_time integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_s public.practice_sessions_v4%rowtype;
  v_answered integer;
  v_payload jsonb;
  v_attempt_id bigint;
  v_score integer;
  v_percent numeric;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;

  select * into v_s
  from public.practice_sessions_v4 s
  where s.id=p_session_id and s.user_id=v_uid
  for update;
  if v_s.id is null then raise exception 'session_not_found' using errcode='P0002'; end if;

  if v_s.status='finalized' and v_s.legacy_attempt_id is not null then
    select pa.score,pa.percent into v_score,v_percent
    from public.practice_attempts pa
    where pa.id=v_s.legacy_attempt_id and pa.user_id=v_uid;

    return jsonb_build_object(
      'ok',true,'session_id',v_s.id,'attempt_id',v_s.legacy_attempt_id,
      'score',coalesce(v_score,0),'percent',coalesce(v_percent,0),
      'question_count',10,'idempotent',true
    );
  end if;

  if v_s.status <> 'in_progress' then
    raise exception 'session_not_in_progress' using errcode='55000';
  end if;

  select count(*)::integer into v_answered
  from public.practice_session_answers_v4 a
  where a.session_id=p_session_id and a.question_id=any(v_s.question_ids);

  if v_answered <> 10 then
    raise exception 'session_answers_incomplete' using errcode='55000';
  end if;

  select jsonb_agg(
    jsonb_build_object(
      'question_id',a.question_id,
      'user_answer',a.user_answer,
      'picked_index',a.picked_index,
      'time_spent',a.time_spent
    ) order by x.ord
  ) into v_payload
  from public.practice_session_answers_v4 a
  join lateral unnest(v_s.question_ids) with ordinality x(qid,ord)
    on x.qid=a.question_id
  where a.session_id=p_session_id;

  -- Existing production RPC rechecks correctness and writes the canonical legacy history.
  v_attempt_id := public.submit_practice_attempt(
    v_s.subject_id,0,0,greatest(coalesce(p_total_time,0),0),coalesce(v_payload,'[]'::jsonb)
  );

  if v_attempt_id is null then
    raise exception 'practice_finalize_failed' using errcode='55000';
  end if;

  update public.practice_sessions_v4
  set status='finalized',legacy_attempt_id=v_attempt_id,finalized_at=now()
  where id=p_session_id and user_id=v_uid;

  select pa.score,pa.percent into v_score,v_percent
  from public.practice_attempts pa
  where pa.id=v_attempt_id and pa.user_id=v_uid;

  return jsonb_build_object(
    'ok',true,'session_id',p_session_id,'attempt_id',v_attempt_id,
    'score',coalesce(v_score,0),'percent',coalesce(v_percent,0),
    'question_count',10,'idempotent',false
  );
end;
$$;

create or replace function public.get_practice_review_safe_v4(p_attempt_id bigint)
returns table(
  question_id bigint,
  user_answer text,
  is_correct boolean,
  time_spent integer,
  correct_answer text,
  explanation text,
  explanation_ru text,
  explanation_uz text,
  explanation_en text,
  topic text,
  subtopic text,
  book_ref text
)
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select a.question_id,a.user_answer,a.is_correct,a.time_spent,
    q.correct_answer,q.explanation,q.explanation_ru,q.explanation_uz,q.explanation_en,
    q.topic,q.subtopic,q.book_ref
  from public.practice_answers a
  join public.practice_attempts pa on pa.id=a.attempt_id and pa.user_id=auth.uid()
  join public.questions q on q.id=a.question_id
  where a.attempt_id=p_attempt_id
  order by a.id;
$$;

-- =========================================================
-- 4. Tour safe contract
-- =========================================================

create or replace function public.start_tour_attempt_safe_v4(
  p_tour_id bigint,
  p_client_session_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_tour public.tours%rowtype;
  v_attempt public.tour_attempts%rowtype;
  v_rt public.tour_session_runtime_v4%rowtype;
  v_qids bigint[];
  v_attempt_id bigint;
  v_today date := (now() at time zone 'Asia/Tashkent')::date;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if p_tour_id is null or p_tour_id <= 0 then raise exception 'invalid_tour_id' using errcode='22023'; end if;
  if p_client_session_id is null or length(trim(p_client_session_id)) not between 8 and 128 then
    raise exception 'invalid_client_session_id' using errcode='22023';
  end if;

  select * into v_rt
  from public.tour_session_runtime_v4 r
  where r.user_id=v_uid and r.client_session_id=trim(p_client_session_id)
  limit 1;

  if v_rt.attempt_id is not null then
    if v_rt.tour_id <> p_tour_id then
      raise exception 'client_session_scope_mismatch' using errcode='22023';
    end if;
    return jsonb_build_object(
      'attempt_id',v_rt.attempt_id,'question_count',20,
      'finalized',v_rt.finalized_at is not null,'resumed',true
    );
  end if;

  select * into v_tour
  from public.tours t
  where t.id=p_tour_id and t.is_active is true;
  if v_tour.id is null then raise exception 'tour_not_found_or_inactive' using errcode='P0002'; end if;

  if v_tour.start_date is null or v_tour.end_date is null
     or v_today < v_tour.start_date or v_today > v_tour.end_date then
    raise exception 'tour_not_open' using errcode='55000';
  end if;

  if not exists(
    select 1 from public.users u
    where u.id=v_uid and coalesce(u.is_school_student,false) is true
  ) then
    raise exception 'tour_requires_school_student' using errcode='42501';
  end if;

  if not exists(
    select 1 from public.user_subjects us
    where us.user_id=v_uid
      and us.subject_id=v_tour.subject_id
      and us.mode='competitive'
  ) then
    raise exception 'tour_subject_not_competitive_for_user' using errcode='42501';
  end if;

  select * into v_attempt
  from public.tour_attempts a
  where a.user_id=v_uid and a.tour_id=p_tour_id
  limit 1;

  if v_attempt.id is not null then
    select * into v_rt
    from public.tour_session_runtime_v4 r
    where r.attempt_id=v_attempt.id and r.user_id=v_uid;

    if v_rt.attempt_id is not null and v_rt.finalized_at is null then
      return jsonb_build_object(
        'attempt_id',v_rt.attempt_id,'question_count',20,
        'finalized',false,'resumed',true
      );
    end if;

    raise exception 'already_attempted' using errcode='23505';
  end if;

  select array_agg(tq.question_id order by tq.order_no,tq.id)
  into v_qids
  from public.tour_questions tq
  join public.questions q on q.id=tq.question_id and q.is_active is true
  where tq.tour_id=p_tour_id
    and tq.is_active is true
    and q.subject_id=v_tour.subject_id;

  if coalesce(cardinality(v_qids),0) <> 20 then
    raise exception 'tour_question_count_not_20' using errcode='55000';
  end if;

  insert into public.tour_attempts(user_id,tour_id,score,percent,total_time,status)
  values(v_uid,p_tour_id,0,0,0,'submitted')
  returning id into v_attempt_id;

  insert into public.tour_session_runtime_v4(
    attempt_id,user_id,tour_id,client_session_id,question_ids
  ) values(
    v_attempt_id,v_uid,p_tour_id,trim(p_client_session_id),v_qids
  );

  return jsonb_build_object(
    'attempt_id',v_attempt_id,'question_count',20,
    'finalized',false,'resumed',false
  );
exception when unique_violation then
  select * into v_attempt
  from public.tour_attempts a
  where a.user_id=v_uid and a.tour_id=p_tour_id
  limit 1;
  if v_attempt.id is null then raise; end if;

  select * into v_rt
  from public.tour_session_runtime_v4 r
  where r.attempt_id=v_attempt.id and r.user_id=v_uid;

  if v_rt.attempt_id is null or v_rt.finalized_at is not null then
    raise exception 'already_attempted' using errcode='23505';
  end if;

  return jsonb_build_object(
    'attempt_id',v_rt.attempt_id,'question_count',20,
    'finalized',false,'resumed',true
  );
end;
$$;

create or replace function public.get_tour_session_questions_safe_v4(p_attempt_id bigint)
returns table(
  order_no integer,
  id bigint,
  subject_id bigint,
  time_limit_sec integer,
  question_text text,
  question_text_ru text,
  question_text_uz text,
  question_text_en text,
  options_text text,
  options_text_ru text,
  options_text_uz text,
  options_text_en text,
  image_url text,
  topic text,
  subtopic text,
  difficulty text,
  qtype text,
  book_ref text
)
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select x.ord::integer,q.id,q.subject_id,q.time_limit_sec,
    q.question_text,q.question_text_ru,q.question_text_uz,q.question_text_en,
    q.options_text,q.options_text_ru,q.options_text_uz,q.options_text_en,
    q.image_url,q.topic,q.subtopic,q.difficulty,q.qtype,q.book_ref
  from public.tour_session_runtime_v4 r
  cross join lateral unnest(r.question_ids) with ordinality x(qid,ord)
  join public.questions q on q.id=x.qid and q.is_active is true
  where r.attempt_id=p_attempt_id
    and r.user_id=auth.uid()
    and r.finalized_at is null
  order by x.ord;
$$;

create or replace function public.submit_tour_answer_safe_v4(
  p_attempt_id bigint,
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer,
  p_time_spent integer,
  p_answered boolean default true,
  p_finish_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_rt public.tour_session_runtime_v4%rowtype;
  v_eval jsonb;
  v_saved public.tour_session_answers_v4%rowtype;
  v_count integer;
  v_was_existing boolean := false;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;

  select * into v_rt
  from public.tour_session_runtime_v4 r
  where r.attempt_id=p_attempt_id and r.user_id=v_uid;
  if v_rt.attempt_id is null then raise exception 'tour_session_not_found' using errcode='P0002'; end if;
  if v_rt.finalized_at is not null then raise exception 'tour_session_finalized' using errcode='55000'; end if;
  if not (p_question_id=any(v_rt.question_ids)) then raise exception 'question_not_in_tour_session' using errcode='22023'; end if;

  select * into v_saved
  from public.tour_session_answers_v4 a
  where a.attempt_id=p_attempt_id and a.question_id=p_question_id;
  v_was_existing := v_saved.attempt_id is not null;

  if not v_was_existing then
    v_eval := public.iclub_eval_tour_question_safe_v4(
      p_question_id,p_user_answer,p_picked_index,coalesce(p_answered,true)
    );

    insert into public.tour_session_answers_v4(
      attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason,answered_at
    ) values(
      p_attempt_id,p_question_id,v_eval->>'selected_answer',coalesce(p_answered,true),
      coalesce((v_eval->>'is_correct')::boolean,false),
      greatest(coalesce(p_time_spent,0),0),
      nullif(trim(coalesce(p_finish_reason,'')),''),now()
    ) on conflict(attempt_id,question_id) do nothing;

    select * into v_saved
    from public.tour_session_answers_v4 a
    where a.attempt_id=p_attempt_id and a.question_id=p_question_id;
  end if;

  if v_saved.attempt_id is null then
    raise exception 'tour_answer_save_failed' using errcode='55000';
  end if;

  select count(*)::integer into v_count
  from public.tour_session_answers_v4 a
  where a.attempt_id=p_attempt_id;

  -- No correctness, answer key or explanation is returned during an active Tour.
  return jsonb_build_object(
    'ok',true,'attempt_id',p_attempt_id,'question_id',p_question_id,
    'recorded',true,'recorded_count',v_count,'question_count',20,
    'idempotent',v_was_existing
  );
end;
$$;

create or replace function public.finalize_tour_attempt_safe_v4(
  p_attempt_id bigint,
  p_total_time integer,
  p_status text default 'submitted'
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_rt public.tour_session_runtime_v4%rowtype;
  v_score integer;
  v_percent numeric;
  v_status text := lower(trim(coalesce(p_status,'submitted')));
  v_saved_status text;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;
  if v_status not in ('submitted','time_expired','anti_cheat','abandoned') then
    raise exception 'invalid_tour_status' using errcode='22023';
  end if;

  select * into v_rt
  from public.tour_session_runtime_v4 r
  where r.attempt_id=p_attempt_id and r.user_id=v_uid
  for update;
  if v_rt.attempt_id is null then raise exception 'tour_session_not_found' using errcode='P0002'; end if;

  if v_rt.finalized_at is not null then
    select a.score,a.percent,a.status into v_score,v_percent,v_saved_status
    from public.tour_attempts a
    where a.id=p_attempt_id and a.user_id=v_uid;

    return jsonb_build_object(
      'ok',true,'attempt_id',p_attempt_id,
      'score',coalesce(v_score,0),'percent',coalesce(v_percent,0),
      'question_count',20,'status',v_saved_status,'idempotent',true
    );
  end if;

  -- Fill omitted questions as unanswered. Existing answered rows are immutable.
  insert into public.tour_session_answers_v4(
    attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason
  )
  select p_attempt_id,x.qid,null,false,false,0,v_status
  from unnest(v_rt.question_ids) x(qid)
  where not exists(
    select 1 from public.tour_session_answers_v4 a
    where a.attempt_id=p_attempt_id and a.question_id=x.qid
  )
  on conflict do nothing;

  select count(*) filter(where a.is_correct is true)::integer
  into v_score
  from public.tour_session_answers_v4 a
  where a.attempt_id=p_attempt_id and a.question_id=any(v_rt.question_ids);

  v_percent := round((coalesce(v_score,0)::numeric/20::numeric)*100,2);

  insert into public.tour_answers(
    attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason
  )
  select a.attempt_id,a.question_id,a.user_answer,a.answered,a.is_correct,a.time_spent,a.finish_reason
  from public.tour_session_answers_v4 a
  where a.attempt_id=p_attempt_id and a.question_id=any(v_rt.question_ids)
  on conflict(attempt_id,question_id) do update set
    user_answer=excluded.user_answer,
    answered=excluded.answered,
    is_correct=excluded.is_correct,
    time_spent=excluded.time_spent,
    finish_reason=excluded.finish_reason;

  update public.tour_attempts a
  set score=coalesce(v_score,0),
      percent=v_percent,
      total_time=greatest(coalesce(p_total_time,0),0),
      status=v_status
  where a.id=p_attempt_id and a.user_id=v_uid and a.tour_id=v_rt.tour_id;

  if not found then
    raise exception 'tour_attempt_update_failed' using errcode='P0002';
  end if;

  update public.tour_session_runtime_v4
  set finalized_at=now()
  where attempt_id=p_attempt_id and user_id=v_uid;

  return jsonb_build_object(
    'ok',true,'attempt_id',p_attempt_id,
    'score',coalesce(v_score,0),'percent',v_percent,
    'question_count',20,'status',v_status,'idempotent',false
  );
end;
$$;

create or replace function public.get_tour_review_safe_v4(p_attempt_id bigint)
returns table(
  question_id bigint,
  user_answer text,
  answered boolean,
  is_correct boolean,
  time_spent integer,
  correct_answer text,
  explanation text,
  explanation_ru text,
  explanation_uz text,
  explanation_en text,
  topic text,
  subtopic text,
  book_ref text
)
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_tour public.tours%rowtype;
  v_today date := (now() at time zone 'Asia/Tashkent')::date;
begin
  if v_uid is null then raise exception 'not_authenticated' using errcode='28000'; end if;

  select t.* into v_tour
  from public.tour_attempts ta
  join public.tours t on t.id=ta.tour_id
  where ta.id=p_attempt_id and ta.user_id=v_uid;

  if v_tour.id is null then
    raise exception 'tour_attempt_not_found' using errcode='P0002';
  end if;

  if v_tour.end_date is null or v_today <= v_tour.end_date then
    raise exception 'tour_review_not_open' using errcode='55000';
  end if;

  return query
  select a.question_id,a.user_answer,a.answered,a.is_correct,a.time_spent,
    q.correct_answer,q.explanation,q.explanation_ru,q.explanation_uz,q.explanation_en,
    q.topic,q.subtopic,q.book_ref
  from public.tour_answers a
  join public.questions q on q.id=a.question_id
  where a.attempt_id=p_attempt_id
  order by a.id;
end;
$$;

-- =========================================================
-- 5. Browser grants: RPC only
-- =========================================================

revoke all on function public.start_practice_session_safe_v4(bigint,text,bigint[]) from public,anon;
revoke all on function public.get_practice_session_questions_safe_v4(bigint) from public,anon;
revoke all on function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) from public,anon;
revoke all on function public.finalize_practice_session_safe_v4(bigint,integer) from public,anon;
revoke all on function public.get_practice_review_safe_v4(bigint) from public,anon;
revoke all on function public.start_tour_attempt_safe_v4(bigint,text) from public,anon;
revoke all on function public.get_tour_session_questions_safe_v4(bigint) from public,anon;
revoke all on function public.submit_tour_answer_safe_v4(bigint,bigint,text,integer,integer,boolean,text) from public,anon;
revoke all on function public.finalize_tour_attempt_safe_v4(bigint,integer,text) from public,anon;
revoke all on function public.get_tour_review_safe_v4(bigint) from public,anon;

grant execute on function public.start_practice_session_safe_v4(bigint,text,bigint[]) to authenticated;
grant execute on function public.get_practice_session_questions_safe_v4(bigint) to authenticated;
grant execute on function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) to authenticated;
grant execute on function public.finalize_practice_session_safe_v4(bigint,integer) to authenticated;
grant execute on function public.get_practice_review_safe_v4(bigint) to authenticated;
grant execute on function public.start_tour_attempt_safe_v4(bigint,text) to authenticated;
grant execute on function public.get_tour_session_questions_safe_v4(bigint) to authenticated;
grant execute on function public.submit_tour_answer_safe_v4(bigint,bigint,text,integer,integer,boolean,text) to authenticated;
grant execute on function public.finalize_tour_attempt_safe_v4(bigint,integer,text) to authenticated;
grant execute on function public.get_tour_review_safe_v4(bigint) to authenticated;

comment on table public.practice_sessions_v4 is
'P0-02 private Practice runtime. Exactly 10 questions; no direct browser access; finalized state maps to legacy practice history.';
comment on table public.tour_session_runtime_v4 is
'P0-02 private Tour runtime. Exactly 20 questions; no direct browser access; preserves legacy one-attempt law.';
comment on function public.get_practice_session_questions_safe_v4(bigint) is
'P0-02 pre-answer Practice delivery: no correct_answer or explanation.';
comment on function public.submit_practice_session_answer_safe_v4(bigint,bigint,text,integer,integer) is
'P0-02 Practice submit: first accepted answer is immutable; feedback is only for the answered item.';
comment on function public.get_tour_session_questions_safe_v4(bigint) is
'P0-02 active Tour delivery: no correct_answer, explanation or live correctness.';
comment on function public.submit_tour_answer_safe_v4(bigint,bigint,text,integer,integer,boolean,text) is
'P0-02 Tour submit: server-enforced no-back; no correctness returned during active Tour.';
comment on function public.start_tour_attempt_safe_v4(bigint,text) is
'P0-02 Tour start: date, school-student, competitive-subject, one-attempt and 20-question guards.';

commit;
