-- P1-02 P1 AW21-24 Coordinate Geometry closure: COO-05/06.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw21_24_coordinate_v1','P1','P1 AW21-24 Coordinate Geometry closure','draft',
       'Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv
where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_coordinate_v1' and component_code='P1' and status='draft'),
src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-COO-05','P1COO05-D01','diagnostic','medium','The circle (x−2)^2+(y+1)^2=25 is cut by the line y=−1. What are the intersection points?','Окружность (x−2)^2+(y+1)^2=25 пересечена прямой y=−1. Каковы точки пересечения?','(x−2)^2+(y+1)^2=25 aylana y=−1 chiziq bilan kesiladi. Kesishish nuqtalari qaysi?','["(−3,−1) and (7,−1)","(−5,−1) and (5,−1)","(2,−6) and (2,4)","(−3,1) and (7,1)"]','["(−3,−1) и (7,−1)","(−5,−1) и (5,−1)","(2,−6) и (2,4)","(−3,1) и (7,1)"]','["(−3,−1) va (7,−1)","(−5,−1) va (5,−1)","(2,−6) va (2,4)","(−3,1) va (7,1)"]','A','Substitute y=−1: (x−2)^2=25, so x=2±5, giving x=−3 or 7.','Подставьте y=−1: (x−2)^2=25, поэтому x=2±5, то есть −3 или 7.','y=−1 ni qo‘ying: (x−2)^2=25, demak x=2±5, ya’ni −3 yoki 7.',50),
('P1-COO-05','P1COO05-L01','learning','easy','The circle x^2+y^2=25 is intersected by x=3. Find the two y-coordinates.','Окружность x^2+y^2=25 пересечена прямой x=3. Найдите две y-координаты.','x^2+y^2=25 aylana x=3 chiziq bilan kesiladi. Ikki y-koordinatani toping.','["±4","±5","±3","4 only"]','["±4","±5","±3","только 4"]','["±4","±5","±3","faqat 4"]','A','9+y^2=25, so y^2=16 and y=±4.','9+y^2=25, значит y^2=16 и y=±4.','9+y^2=25, demak y^2=16 va y=±4.',35),
('P1-COO-05','P1COO05-L02','learning','medium','The circle (x−2)^2+(y+1)^2=9 is intersected by the horizontal line through its centre. What is the length of the resulting chord?','Окружность (x−2)^2+(y+1)^2=9 пересечена горизонтальной прямой через центр. Какова длина хорды?','(x−2)^2+(y+1)^2=9 aylana markazidan o‘tuvchi gorizontal chiziq bilan kesiladi. Hosil bo‘lgan xordaning uzunligi qancha?','["6","3","9","12"]','["6","3","9","12"]','["6","3","9","12"]','A','A chord through the centre is a diameter. Radius=3, so the chord length is 6.','Хорда через центр — диаметр. Радиус 3, поэтому длина хорды 6.','Markazdan o‘tgan xorda diametr. Radius 3, xorda uzunligi 6.',35),
('P1-COO-05','P1COO05-L03','learning','medium','Find the intersection points of y=x and x^2+y^2=18.','Найдите точки пересечения y=x и x^2+y^2=18.','y=x va x^2+y^2=18 kesishish nuqtalarini toping.','["(3,3) and (−3,−3)","(3,−3) and (−3,3)","(9,9) and (−9,−9)","(sqrt(18),sqrt(18)) only"]','["(3,3) и (−3,−3)","(3,−3) и (−3,3)","(9,9) и (−9,−9)","только (sqrt(18),sqrt(18))"]','["(3,3) va (−3,−3)","(3,−3) va (−3,3)","(9,9) va (−9,−9)","faqat (sqrt(18),sqrt(18))"]','A','Substitute y=x: 2x^2=18, so x=±3 and y has the same sign.','Подставьте y=x: 2x^2=18, поэтому x=±3 и y имеет тот же знак.','y=x ni qo‘ying: 2x^2=18, demak x=±3 va y ham shu ishorada.',45),
('P1-COO-05','P1COO05-R01','retest','easy','The circle (x−1)^2+y^2=10 is intersected by x=2. Find y.','Окружность (x−1)^2+y^2=10 пересечена прямой x=2. Найдите y.','(x−1)^2+y^2=10 aylana x=2 bilan kesiladi. y ni toping.','["±3","±sqrt(10)","±1","3 only"]','["±3","±sqrt(10)","±1","только 3"]','["±3","±sqrt(10)","±1","faqat 3"]','A','1+y^2=10, so y^2=9 and y=±3.','1+y^2=10, поэтому y=±3.','1+y^2=10, demak y=±3.',30),
('P1-COO-05','P1COO05-R02','retest','medium','For x^2+y^2=13 and y=2, what are the x-coordinates of the intersections?','Для x^2+y^2=13 и y=2 каковы x-координаты точек пересечения?','x^2+y^2=13 va y=2 uchun kesishish nuqtalarining x-koordinatalari qaysi?','["±3","±sqrt(13)","±9","3 only"]','["±3","±sqrt(13)","±9","только 3"]','["±3","±sqrt(13)","±9","faqat 3"]','A','x^2+4=13, so x^2=9 and x=±3.','x^2+4=13, значит x=±3.','x^2+4=13, demak x=±3.',30),
('P1-COO-05','P1COO05-M01','mixed','medium','The line y=4 cuts the circle x^2+y^2=25. What is the chord length between the two intersection points?','Прямая y=4 пересекает окружность x^2+y^2=25. Какова длина хорды между точками пересечения?','y=4 chiziq x^2+y^2=25 aylanani kesadi. Ikki kesishish nuqtasi orasidagi xorda uzunligi qancha?','["6","3","8","10"]','["6","3","8","10"]','["6","3","8","10"]','A','x^2+16=25 gives x=±3, so the horizontal distance between the points is 3−(−3)=6.','x^2+16=25 даёт x=±3, поэтому расстояние между точками равно 6.','x^2+16=25 dan x=±3, nuqtalar orasidagi gorizontal masofa 6.',45),

('P1-COO-06','P1COO06-D01','diagnostic','medium','For the circle x^2+y^2=25, the line y=k is tangent. What are the possible values of k?','Для окружности x^2+y^2=25 прямая y=k является касательной. Каковы возможные значения k?','x^2+y^2=25 aylana uchun y=k chiziq urinma. k ning mumkin qiymatlari qaysi?','["k=±5","k=5 only","k=±25","k=0"]','["k=±5","только k=5","k=±25","k=0"]','["k=±5","faqat k=5","k=±25","k=0"]','A','A horizontal tangent is one radius above or below the centre, so |k|=5. Equivalently x^2=25−k^2 has one root when k^2=25.','Горизонтальная касательная находится на один радиус выше или ниже центра, поэтому |k|=5. Эквивалентно x^2=25−k^2 имеет один корень при k^2=25.','Gorizontal urinma markazdan bir radius yuqori yoki pastda, shuning uchun |k|=5. Yoki x^2=25−k^2 bitta ildizga ega bo‘lishi uchun k^2=25.',50),
('P1-COO-06','P1COO06-L01','learning','hard','The line y=x+c is tangent to x^2+y^2=10. Find c.','Прямая y=x+c касается окружности x^2+y^2=10. Найдите c.','y=x+c chiziq x^2+y^2=10 aylanaga urinma. c ni toping.','["c=±2sqrt(5)","c=±sqrt(5)","c=±10","c=0"]','["c=±2sqrt(5)","c=±sqrt(5)","c=±10","c=0"]','["c=±2sqrt(5)","c=±sqrt(5)","c=±10","c=0"]','A','Substitution gives 2x^2+2cx+c^2−10=0. Tangency requires discriminant 0: 4c^2−8(c^2−10)=0, so c^2=20.','Подстановка даёт 2x^2+2cx+c^2−10=0. Для касания дискриминант равен 0, откуда c^2=20.','Qo‘yishdan 2x^2+2cx+c^2−10=0. Urinma uchun diskriminant 0: c^2=20.',70),
('P1-COO-06','P1COO06-L02','learning','medium','The circle (x−2)^2+y^2=9 has a vertical tangent x=k. Find k.','Окружность (x−2)^2+y^2=9 имеет вертикальную касательную x=k. Найдите k.','(x−2)^2+y^2=9 aylananing vertikal urinmasi x=k. k ni toping.','["−1 or 5","−3 or 3","2 only","−7 or 11"]','["−1 или 5","−3 или 3","только 2","−7 или 11"]','["−1 yoki 5","−3 yoki 3","faqat 2","−7 yoki 11"]','A','Centre x-coordinate is 2 and radius is 3, so vertical tangents are x=2±3: −1 and 5.','x-координата центра 2, радиус 3, поэтому вертикальные касательные x=2±3: −1 и 5.','Markazning x-koordinatasi 2, radius 3, vertikal urinmalar x=2±3: −1 va 5.',45),
('P1-COO-06','P1COO06-L03','learning','easy','After substituting a line into a circle equation, a quadratic in x has discriminant zero. What does this mean geometrically?','После подстановки прямой в уравнение окружности получается квадратное уравнение по x с нулевым дискриминантом. Что это означает геометрически?','Chiziq aylana tenglamasiga qo‘yilganda x bo‘yicha kvadrat tenglama diskriminanti nol bo‘ldi. Geometrik ma’nosi nima?','["The line is tangent to the circle","The line cuts the circle twice","The line misses the circle","The circle has radius zero"]','["Прямая касается окружности","Прямая пересекает окружность в двух точках","Прямая не пересекает окружность","Радиус окружности равен нулю"]','["Chiziq aylanaga urinma","Chiziq aylanani ikki nuqtada kesadi","Chiziq aylanani kesmaydi","Aylana radiusi nol"]','A','Discriminant zero means one repeated algebraic intersection, so the line touches the circle at one point.','Нулевой дискриминант означает один кратный корень — прямая касается окружности в одной точке.','Diskriminant nol — bitta takroriy ildiz, ya’ni chiziq aylanaga bitta nuqtada tegadi.',35),
('P1-COO-06','P1COO06-R01','retest','easy','For x^2+y^2=4, the horizontal line y=k is tangent. Find k.','Для x^2+y^2=4 горизонтальная прямая y=k является касательной. Найдите k.','x^2+y^2=4 uchun gorizontal y=k urinma. k ni toping.','["±2","±4","2 only","0"]','["±2","±4","только 2","0"]','["±2","±4","faqat 2","0"]','A','The radius is 2, so horizontal tangents are y=±2.','Радиус равен 2, поэтому горизонтальные касательные y=±2.','Radius 2, gorizontal urinmalar y=±2.',30),
('P1-COO-06','P1COO06-R02','retest','medium','The line y=x+c is tangent to x^2+y^2=2. Find c.','Прямая y=x+c касается x^2+y^2=2. Найдите c.','y=x+c chiziq x^2+y^2=2 ga urinma. c ni toping.','["±2","±sqrt(2)","±1","0"]','["±2","±sqrt(2)","±1","0"]','["±2","±sqrt(2)","±1","0"]','A','Substitution gives 2x^2+2cx+c^2−2=0. Discriminant zero gives 16−4c^2=0, hence c=±2.','Подстановка даёт 2x^2+2cx+c^2−2=0. Нулевой дискриминант даёт c=±2.','Qo‘yishdan 2x^2+2cx+c^2−2=0. Diskriminant nol bo‘lsa c=±2.',55),
('P1-COO-06','P1COO06-M01','mixed','hard','The line y=2x+k is tangent to the circle x^2+y^2=5. Find k.','Прямая y=2x+k касается окружности x^2+y^2=5. Найдите k.','y=2x+k chiziq x^2+y^2=5 aylanaga urinma. k ni toping.','["k=±5","k=±sqrt(5)","k=±10","k=0"]','["k=±5","k=±sqrt(5)","k=±10","k=0"]','["k=±5","k=±sqrt(5)","k=±10","k=0"]','A','Substitution gives 5x^2+4kx+k^2−5=0. Tangency requires 16k^2−20(k^2−5)=0, so k^2=25.','Подстановка даёт 5x^2+4kx+k^2−5=0. Для касания 16k^2−20(k^2−5)=0, поэтому k^2=25.','Qo‘yishdan 5x^2+4kx+k^2−5=0. Urinma uchun 16k^2−20(k^2−5)=0, demak k^2=25.',70)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Coordinate Geometry',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw21_24_coordinate_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw21_24_coordinate_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_coordinate_v1' and status='draft'), keys(skill,k,role) as (values
('P1-COO-05','P1COO05-D01','diagnostic'),('P1-COO-05','P1COO05-L01','learning'),('P1-COO-05','P1COO05-L02','learning'),('P1-COO-05','P1COO05-L03','learning'),('P1-COO-05','P1COO05-R01','retest'),('P1-COO-05','P1COO05-R02','retest'),('P1-COO-05','P1COO05-M01','mixed'),
('P1-COO-06','P1COO06-D01','diagnostic'),('P1-COO-06','P1COO06-L01','learning'),('P1-COO-06','P1COO06-L02','learning'),('P1-COO-06','P1COO06-L03','learning'),('P1-COO-06','P1COO06-R01','retest'),('P1-COO-06','P1COO06-R02','retest'),('P1-COO-06','P1COO06-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw21_24_coordinate_v1 from canonical coordinate-geometry skill intent.','Cambridge 9709 2026-2027 v4; P1 1.3 Coordinate geometry','Complete Pure Mathematics 1; Coordinate geometry (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw21_24_coordinate_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw21_24_coordinate_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1COO05-D01','B','ignores_centre_shift','concept','The circle is centred at (2,−1), not the origin. With y=−1 the horizontal displacement is measured from x=2.','Центр окружности (2,−1), а не начало координат. При y=−1 горизонтальное смещение отсчитывается от x=2.','Aylana markazi (2,−1), koordinata boshi emas. y=−1 da gorizontal masofa x=2 dan olinadi.','Read centre and radius from completed-square form before substituting.','Сначала считайте центр и радиус из канонической формы, затем подставляйте.','Avval markaz va radiusni standart ko‘rinishdan o‘qing, keyin qo‘ying.'),
('P1COO05-D01','C','uses_vertical_diameter','method','Those are the vertical diameter endpoints, but the given line is horizontal y=−1.','Это концы вертикального диаметра, но дана горизонтальная прямая y=−1.','Bular vertikal diametr uchlari, lekin berilgan chiziq gorizontal y=−1.','Respect the line constraint before solving the circle.','Сначала учтите ограничение заданной прямой.','Avval berilgan chiziq shartini qo‘llang.'),
('P1COO05-D01','D','wrong_line_sign','method','The intersection points must satisfy y=−1 exactly; y=1 cannot be on the specified line.','Точки пересечения обязаны удовлетворять y=−1; y=1 не лежит на заданной прямой.','Kesishish nuqtalari y=−1 ni qanoatlantirishi kerak; y=1 berilgan chiziqda emas.','Verify every candidate in both equations.','Каждую точку проверяйте в обоих уравнениях.','Har bir nuqtani ikkala tenglamada tekshiring.'),
('P1COO06-D01','B','single_tangent_only','concept','A circle centred at the origin has both an upper and a lower horizontal tangent.','У окружности с центром в начале координат есть верхняя и нижняя горизонтальные касательные.','Markazi koordinata boshida bo‘lgan aylananing yuqori va pastki gorizontal urinmalari bor.','Consider both signs when distance from the centre equals the radius.','Когда расстояние от центра равно радиусу, учитывайте оба знака.','Markazdan masofa radiusga teng bo‘lganda ikkala ishorani hisobga oling.'),
('P1COO06-D01','C','uses_radius_squared','concept','25 is r^2; the radius is 5. Tangent distance from the centre is r, not r^2.','25 — это r^2; радиус равен 5. Расстояние до касательной равно r, а не r^2.','25 bu r^2; radius 5. Urinmagacha masofa r ga teng, r^2 ga emas.','Take the square root when reading radius from x^2+y^2=r^2.','При чтении радиуса из x^2+y^2=r^2 извлеките квадратный корень.','x^2+y^2=r^2 dan radiusni olishda kvadrat ildiz oling.'),
('P1COO06-D01','D','diameter_not_tangent','concept','y=0 passes through the centre and cuts the circle twice; it is a diameter line, not a tangent.','y=0 проходит через центр и пересекает окружность дважды; это диаметр, не касательная.','y=0 markazdan o‘tadi va aylanani ikki marta kesadi; bu diametr chizig‘i, urinma emas.','Tangency means exactly one intersection.','Касание означает ровно одну точку пересечения.','Urinish aynan bitta kesishish nuqtasini anglatadi.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_coordinate_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1COO05-W01','P1-COO-05','Find the intersection points of the circle x^2+y^2=25 and the line y=x+1. Show the substitution and factorisation, verify both points in both original equations, and find the distance between the two intersection points.','Найдите точки пересечения окружности x^2+y^2=25 и прямой y=x+1. Покажите подстановку и разложение на множители, проверьте обе точки в исходных уравнениях и найдите расстояние между точками.','x^2+y^2=25 aylana va y=x+1 chiziq kesishish nuqtalarini toping. Qo‘yish va faktorlashni ko‘rsating, ikki nuqtani ikkala asl tenglamada tekshiring va ular orasidagi masofani toping.','{"max_marks":11,"criteria":[{"id":"substitution","marks":2,"rule":"Obtains x^2+(x+1)^2=25 and simplifies correctly."},{"id":"roots","marks":2,"rule":"Gets x=3 and x=−4."},{"id":"points","marks":2,"rule":"Gets (3,4) and (−4,−3)."},{"id":"verification","marks":2,"rule":"Checks both points satisfy line and circle."},{"id":"distance","marks":3,"rule":"Gets sqrt(7^2+7^2)=7sqrt(2)."}]}','Keep the line equation attached to each x-root so the corresponding y-value cannot be mismatched.','Сохраняйте связь каждого корня x с уравнением прямой, чтобы не перепутать y.','Har bir x ildizini chiziq tenglamasi bilan bog‘lab, y ni adashtirmang.'),
('P1COO06-W01','P1-COO-06','For the circle x^2+y^2=25, find all values of c for which y=x+c is tangent. Solve first by substituting and setting the quadratic discriminant to zero, then verify the same condition using the perpendicular distance from the origin to the line.','Для окружности x^2+y^2=25 найдите все c, при которых y=x+c является касательной. Сначала решите подстановкой и условием нулевого дискриминанта, затем подтвердите результат через расстояние от начала координат до прямой.','x^2+y^2=25 aylana uchun y=x+c urinma bo‘ladigan barcha c ni toping. Avval qo‘yish va diskriminantni nolga tenglash bilan yeching, keyin koordinata boshidan chiziqqacha masofa orqali tekshiring.','{"max_marks":11,"criteria":[{"id":"quadratic","marks":2,"rule":"Gets 2x^2+2cx+c^2−25=0."},{"id":"discriminant","marks":3,"rule":"Sets 4c^2−8(c^2−25)=0 and gets c^2=50."},{"id":"values","marks":2,"rule":"Gets c=±5sqrt(2)."},{"id":"distance","marks":3,"rule":"Uses |c|/sqrt(2)=5 to verify the same values."},{"id":"interpretation","marks":1,"rule":"Connects repeated root/distance=r to one-point tangency."}]}','Use two independent tangency tests; if they disagree, recheck algebra before finalising.','Используйте два независимых признака касания; при расхождении перепроверьте алгебру.','Ikki mustaqil urinish testidan foydalaning; mos kelmasa algebra ni tekshiring.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_coordinate_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw21_coordinate_diagnostic','diagnostic','P1 AW21-24 Coordinate diagnostic','Диагностика P1 AW21–24: coordinate geometry','P1 AW21–24 coordinate diagnostikasi'),
('p1_coo05_learning','learning','Line-circle intersections learning','Пересечения прямой и окружности: обучение','Chiziq-aylana kesishishi: o‘rganish'),
('p1_coo06_learning','learning','Tangency and parameter conditions learning','Касание и параметры: обучение','Urinish va parametr shartlari: o‘rganish'),
('p1_coo05_retest','retest','COO-05 delayed retest','COO-05 отложенный ретест','COO-05 kechiktirilgan retest'),
('p1_coo06_retest','retest','COO-06 delayed retest','COO-06 отложенный ретест','COO-06 kechiktirilgan retest'),
('p1_aw21_coordinate_mixed','mixed','P1 AW21-24 Coordinate mixed transfer','P1 AW21–24: смешанный перенос coordinate','P1 AW21–24 coordinate mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_coordinate_v1'),
a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id),
m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id),
w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id),
items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw21_coordinate_diagnostic',1,'P1COO05-D01',null,'P1-COO-05','diagnostic',true),('p1_aw21_coordinate_diagnostic',2,'P1COO06-D01',null,'P1-COO-06','diagnostic',true),
('p1_coo05_learning',1,'P1COO05-L01',null,'P1-COO-05','learning',false),('p1_coo05_learning',2,'P1COO05-L02',null,'P1-COO-05','learning',false),('p1_coo05_learning',3,'P1COO05-L03',null,'P1-COO-05','learning',false),('p1_coo05_learning',4,null,'P1COO05-W01','P1-COO-05','written',false),
('p1_coo06_learning',1,'P1COO06-L01',null,'P1-COO-06','learning',false),('p1_coo06_learning',2,'P1COO06-L02',null,'P1-COO-06','learning',false),('p1_coo06_learning',3,'P1COO06-L03',null,'P1-COO-06','learning',false),('p1_coo06_learning',4,null,'P1COO06-W01','P1-COO-06','written',false),
('p1_coo05_retest',1,'P1COO05-R01',null,'P1-COO-05','retest',true),('p1_coo06_retest',1,'P1COO06-R01',null,'P1-COO-06','retest',true),
('p1_aw21_coordinate_mixed',1,'P1COO05-M01',null,'P1-COO-05','mixed',true),('p1_aw21_coordinate_mixed',2,'P1COO06-M01',null,'P1-COO-06','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_coordinate_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw21_24_coordinate_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_coordinate_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw21_24_coordinate_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw21_24_coordinate_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw21_24_coordinate_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
 select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
 foreach v_skill in array array['P1-COO-05','P1-COO-06'] loop
   if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 coordinate closure skill not ready %',v_skill; end if;
 end loop;
 if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw21_24_coordinate_v1:%' and is_active) then raise exception 'P1 coordinate legacy activation residue'; end if;
 if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P1 coordinate publication escaped fail-closed'; end if;
 if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 coordinate active entitlement residue'; end if;
end $$;
commit;
