-- P1-02 P1 AW17-20 Differentiation pack: DIF-02/03/04.
-- Original iClub-authored content only; governed publication; legacy questions stay draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw17_20_diff_v1','P1','P1 AW17-20 Differentiation: powers, chain rule, tangent/normal','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_diff_v1' and component_code='P1' and status='draft'), src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-DIF-02','P1DIF02-D01','diagnostic','medium','Differentiate y=4x^(3/2)−3x².','Найдите производную y=4x^(3/2)−3x².','y=4x^(3/2)−3x² funksiyaning hosilasini toping.','["6x^(1/2)−6x","4x^(1/2)−6x","6x^(3/2)−6x","6x^(1/2)−3x"]','["6x^(1/2)−6x","4x^(1/2)−6x","6x^(3/2)−6x","6x^(1/2)−3x"]','["6x^(1/2)−6x","4x^(1/2)−6x","6x^(3/2)−6x","6x^(1/2)−3x"]','A','Use d(x^n)/dx=nx^(n−1): 4(3/2)x^(1/2)−6x=6x^(1/2)−6x.','Используем правило степени: 4(3/2)x^(1/2)−6x=6x^(1/2)−6x.','Daraja qoidasidan: 4(3/2)x^(1/2)−6x=6x^(1/2)−6x.',60),
('P1-DIF-02','P1DIF02-L01','learning','easy','Differentiate y=5x^4−2x³+7.','Найдите производную y=5x^4−2x³+7.','y=5x^4−2x³+7 hosilasini toping.','["20x³−6x²","20x³−2x²","5x³−6x²","20x^4−6x³"]','["20x³−6x²","20x³−2x²","5x³−6x²","20x^4−6x³"]','["20x³−6x²","20x³−2x²","5x³−6x²","20x^4−6x³"]','A','Differentiate term by term; the constant has derivative 0.','Дифференцируем по членам; производная константы равна 0.','Har bir hadni alohida differensiallang; doimiyning hosilasi 0.',35),
('P1-DIF-02','P1DIF02-L02','learning','medium','Differentiate y=3x^(1/2)+2x^(−1).','Найдите производную y=3x^(1/2)+2x^(−1).','y=3x^(1/2)+2x^(−1) hosilasini toping.','["(3/2)x^(−1/2)−2x^(−2)","(3/2)x^(1/2)+2x^(−2)","3x^(−1/2)−x^(−2)","(1/2)x^(−1/2)−2x^(−1)"]','["(3/2)x^(−1/2)−2x^(−2)","(3/2)x^(1/2)+2x^(−2)","3x^(−1/2)−x^(−2)","(1/2)x^(−1/2)−2x^(−1)"]','["(3/2)x^(−1/2)−2x^(−2)","(3/2)x^(1/2)+2x^(−2)","3x^(−1/2)−x^(−2)","(1/2)x^(−1/2)−2x^(−1)"]','A','Apply the power rule to exponents 1/2 and −1.','Примените правило степени к показателям 1/2 и −1.','1/2 va −1 darajalarga daraja qoidasini qo‘llang.',50),
('P1-DIF-02','P1DIF02-L03','learning','medium','For y=x³−4x²+2x, find dy/dx at x=2.','Для y=x³−4x²+2x найдите dy/dx при x=2.','y=x³−4x²+2x uchun x=2 da dy/dx ni toping.','["−2","2","−6","6"]','["−2","2","−6","6"]','["−2","2","−6","6"]','A','dy/dx=3x²−8x+2; at x=2 this is 12−16+2=−2.','dy/dx=3x²−8x+2; при x=2 получаем −2.','dy/dx=3x²−8x+2; x=2 da −2.',45),
('P1-DIF-02','P1DIF02-R01','retest','easy','Differentiate y=7x^(5/2).','Найдите производную y=7x^(5/2).','y=7x^(5/2) hosilasini toping.','["(35/2)x^(3/2)","(35/2)x^(5/2)","7x^(3/2)","(5/2)x^(3/2)"]','["(35/2)x^(3/2)","(35/2)x^(5/2)","7x^(3/2)","(5/2)x^(3/2)"]','["(35/2)x^(3/2)","(35/2)x^(5/2)","7x^(3/2)","(5/2)x^(3/2)"]','A','Multiply by 5/2 and reduce the exponent by 1.','Умножьте на 5/2 и уменьшите показатель на 1.','5/2 ga ko‘paytirib, darajani 1 ga kamaytiring.',35),
('P1-DIF-02','P1DIF02-R02','retest','medium','Differentiate y=4/x²+3x.','Найдите производную y=4/x²+3x.','y=4/x²+3x hosilasini toping.','["−8/x³+3","8/x³+3","−8/x+3","4/x³+3"]','["−8/x³+3","8/x³+3","−8/x+3","4/x³+3"]','["−8/x³+3","8/x³+3","−8/x+3","4/x³+3"]','A','Write 4/x² as 4x^(−2), giving −8x^(−3)+3.','Запишите 4/x² как 4x^(−2): получаем −8x^(−3)+3.','4/x² ni 4x^(−2) deb yozing: −8x^(−3)+3.',45),
('P1-DIF-02','P1DIF02-M01','mixed','medium','For f(x)=2x^(3/2)−x^(1/2), find f′(4).','Для f(x)=2x^(3/2)−x^(1/2) найдите f′(4).','f(x)=2x^(3/2)−x^(1/2) uchun f′(4) ni toping.','["23/4","11/4","6","5"]','["23/4","11/4","6","5"]','["23/4","11/4","6","5"]','A','f′(x)=3x^(1/2)−(1/2)x^(−1/2); at x=4: 6−1/4=23/4.','f′(x)=3x^(1/2)−(1/2)x^(−1/2); при x=4: 23/4.','f′(x)=3x^(1/2)−(1/2)x^(−1/2); x=4 da 23/4.',55),

('P1-DIF-03','P1DIF03-D01','diagnostic','medium','Differentiate y=(2x+1)^5.','Найдите производную y=(2x+1)^5.','y=(2x+1)^5 hosilasini toping.','["10(2x+1)^4","5(2x+1)^4","10(2x+1)^5","2(2x+1)^4"]','["10(2x+1)^4","5(2x+1)^4","10(2x+1)^5","2(2x+1)^4"]','["10(2x+1)^4","5(2x+1)^4","10(2x+1)^5","2(2x+1)^4"]','A','Outer derivative gives 5(2x+1)^4 and inner derivative contributes a factor 2.','Внешняя производная даёт 5(2x+1)^4, внутренняя — множитель 2.','Tashqi hosila 5(2x+1)^4, ichki hosila esa 2 ko‘paytuvchi beradi.',50),
('P1-DIF-03','P1DIF03-L01','learning','easy','Differentiate y=(3x−2)^4.','Найдите производную y=(3x−2)^4.','y=(3x−2)^4 hosilasini toping.','["12(3x−2)^3","4(3x−2)^3","12(3x−2)^4","3(3x−2)^3"]','["12(3x−2)^3","4(3x−2)^3","12(3x−2)^4","3(3x−2)^3"]','["12(3x−2)^3","4(3x−2)^3","12(3x−2)^4","3(3x−2)^3"]','A','4(3x−2)^3×3=12(3x−2)^3.','4(3x−2)^3×3=12(3x−2)^3.','4(3x−2)^3×3=12(3x−2)^3.',35),
('P1-DIF-03','P1DIF03-L02','learning','medium','Differentiate y=(5−2x)^3.','Найдите производную y=(5−2x)^3.','y=(5−2x)^3 hosilasini toping.','["−6(5−2x)^2","6(5−2x)^2","−2(5−2x)^3","3(5−2x)^2"]','["−6(5−2x)^2","6(5−2x)^2","−2(5−2x)^3","3(5−2x)^2"]','["−6(5−2x)^2","6(5−2x)^2","−2(5−2x)^3","3(5−2x)^2"]','A','3(5−2x)^2×(−2)=−6(5−2x)^2.','3(5−2x)^2×(−2)=−6(5−2x)^2.','3(5−2x)^2×(−2)=−6(5−2x)^2.',40),
('P1-DIF-03','P1DIF03-L03','learning','medium','Differentiate y=(4x+3)^(−2).','Найдите производную y=(4x+3)^(−2).','y=(4x+3)^(−2) hosilasini toping.','["−8(4x+3)^(−3)","−2(4x+3)^(−3)","8(4x+3)^(−1)","−8(4x+3)^(−2)"]','["−8(4x+3)^(−3)","−2(4x+3)^(−3)","8(4x+3)^(−1)","−8(4x+3)^(−2)"]','["−8(4x+3)^(−3)","−2(4x+3)^(−3)","8(4x+3)^(−1)","−8(4x+3)^(−2)"]','A','−2(4x+3)^(−3)×4=−8(4x+3)^(−3).','−2(4x+3)^(−3)×4=−8(4x+3)^(−3).','−2(4x+3)^(−3)×4=−8(4x+3)^(−3).',50),
('P1-DIF-03','P1DIF03-R01','retest','easy','Differentiate y=(x+4)^6.','Найдите производную y=(x+4)^6.','y=(x+4)^6 hosilasini toping.','["6(x+4)^5","6(x+4)^6","(x+4)^5","5(x+4)^4"]','["6(x+4)^5","6(x+4)^6","(x+4)^5","5(x+4)^4"]','["6(x+4)^5","6(x+4)^6","(x+4)^5","5(x+4)^4"]','A','The inner derivative is 1, so the result is 6(x+4)^5.','Внутренняя производная равна 1, результат 6(x+4)^5.','Ichki hosila 1, natija 6(x+4)^5.',35),
('P1-DIF-03','P1DIF03-R02','retest','medium','Differentiate y=(1−3x)^4.','Найдите производную y=(1−3x)^4.','y=(1−3x)^4 hosilasini toping.','["−12(1−3x)^3","12(1−3x)^3","−3(1−3x)^4","4(1−3x)^3"]','["−12(1−3x)^3","12(1−3x)^3","−3(1−3x)^4","4(1−3x)^3"]','["−12(1−3x)^3","12(1−3x)^3","−3(1−3x)^4","4(1−3x)^3"]','A','4(1−3x)^3×(−3)=−12(1−3x)^3.','4(1−3x)^3×(−3)=−12(1−3x)^3.','4(1−3x)^3×(−3)=−12(1−3x)^3.',40),
('P1-DIF-03','P1DIF03-M01','mixed','hard','For f(x)=(2x−1)^4, find f′(1).','Для f(x)=(2x−1)^4 найдите f′(1).','f(x)=(2x−1)^4 uchun f′(1) ni toping.','["8","4","16","2"]','["8","4","16","2"]','["8","4","16","2"]','A','f′(x)=8(2x−1)^3; at x=1 this is 8.','f′(x)=8(2x−1)^3; при x=1 получаем 8.','f′(x)=8(2x−1)^3; x=1 da 8.',50),

('P1-DIF-04','P1DIF04-D01','diagnostic','medium','For y=x²+3x, find the equation of the tangent at x=1.','Для y=x²+3x найдите уравнение касательной при x=1.','y=x²+3x uchun x=1 dagi urinma tenglamasini toping.','["y=5x−1","y=5x+1","y=(1/5)x+19/5","y=4x"]','["y=5x−1","y=5x+1","y=(1/5)x+19/5","y=4x"]','["y=5x−1","y=5x+1","y=(1/5)x+19/5","y=4x"]','A','At x=1, y=4 and dy/dx=2x+3=5. Thus y−4=5(x−1), so y=5x−1.','При x=1: y=4, dy/dx=5. Поэтому y−4=5(x−1), то есть y=5x−1.','x=1 da y=4 va dy/dx=5. Demak y−4=5(x−1), ya’ni y=5x−1.',65),
('P1-DIF-04','P1DIF04-L01','learning','easy','The gradient of a tangent is 4. What is the gradient of the normal at the same point?','Угловой коэффициент касательной равен 4. Каков коэффициент нормали в той же точке?','Urinmaning gradienti 4. Shu nuqtadagi normal gradienti qancha?','["−1/4","1/4","−4","4"]','["−1/4","1/4","−4","4"]','["−1/4","1/4","−4","4"]','A','Perpendicular non-vertical lines have gradients whose product is −1.','У перпендикулярных невертикальных прямых произведение коэффициентов равно −1.','Perpendikulyar vertikal bo‘lmagan chiziqlar gradientlari ko‘paytmasi −1.',35),
('P1-DIF-04','P1DIF04-L02','learning','medium','For y=x², find the tangent at x=2.','Для y=x² найдите касательную при x=2.','y=x² uchun x=2 dagi urinmani toping.','["y=4x−4","y=2x","y=4x+4","y=−(1/4)x+9/2"]','["y=4x−4","y=2x","y=4x+4","y=−(1/4)x+9/2"]','["y=4x−4","y=2x","y=4x+4","y=−(1/4)x+9/2"]','A','At (2,4), the tangent gradient is 2x=4: y−4=4(x−2).','В точке (2,4) градиент касательной равен 4: y−4=4(x−2).','(2,4) nuqtada urinma gradienti 4: y−4=4(x−2).',45),
('P1-DIF-04','P1DIF04-L03','learning','medium','For y=x², find the normal at x=2.','Для y=x² найдите нормаль при x=2.','y=x² uchun x=2 dagi normalni toping.','["y−4=−(1/4)(x−2)","y−4=4(x−2)","y−2=−4(x−4)","y=−4x+12"]','["y−4=−(1/4)(x−2)","y−4=4(x−2)","y−2=−4(x−4)","y=−4x+12"]','["y−4=−(1/4)(x−2)","y−4=4(x−2)","y−2=−4(x−4)","y=−4x+12"]','A','The tangent gradient is 4, so the normal gradient is −1/4 through (2,4).','Градиент касательной 4, поэтому градиент нормали −1/4 через (2,4).','Urinma gradienti 4, normal gradienti −1/4 va u (2,4) dan o‘tadi.',50),
('P1-DIF-04','P1DIF04-R01','retest','easy','For y=3x², find the tangent gradient at x=1.','Для y=3x² найдите градиент касательной при x=1.','y=3x² uchun x=1 da urinma gradientini toping.','["6","3","1/6","−6"]','["6","3","1/6","−6"]','["6","3","1/6","−6"]','A','dy/dx=6x, giving gradient 6 at x=1.','dy/dx=6x, при x=1 градиент 6.','dy/dx=6x, x=1 da gradient 6.',35),
('P1-DIF-04','P1DIF04-R02','retest','medium','For y=x³, what is the normal gradient at x=1?','Для y=x³ каков градиент нормали при x=1?','y=x³ uchun x=1 da normal gradienti qancha?','["−1/3","3","1/3","−3"]','["−1/3","3","1/3","−3"]','["−1/3","3","1/3","−3"]','A','The tangent gradient is 3x²=3; the normal gradient is −1/3.','Градиент касательной 3, нормали −1/3.','Urinma gradienti 3, normal gradienti −1/3.',40),
('P1-DIF-04','P1DIF04-M01','mixed','hard','For y=(2x+1)^3, find the equation of the tangent at x=0.','Для y=(2x+1)^3 найдите уравнение касательной при x=0.','y=(2x+1)^3 uchun x=0 dagi urinma tenglamasini toping.','["y=6x+1","y=3x+1","y=6x−1","y=−(1/6)x+1"]','["y=6x+1","y=3x+1","y=6x−1","y=−(1/6)x+1"]','["y=6x+1","y=3x+1","y=6x−1","y=−(1/6)x+1"]','A','dy/dx=6(2x+1)^2, so at x=0 the gradient is 6 and the point is (0,1).','dy/dx=6(2x+1)^2; при x=0 градиент 6 и точка (0,1).','dy/dx=6(2x+1)^2; x=0 da gradient 6 va nuqta (0,1).',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Differentiation',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw17_20_diff_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw17_20_diff_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_diff_v1' and status='draft'), keys(skill,k,role) as (values
('P1-DIF-02','P1DIF02-D01','diagnostic'),('P1-DIF-02','P1DIF02-L01','learning'),('P1-DIF-02','P1DIF02-L02','learning'),('P1-DIF-02','P1DIF02-L03','learning'),('P1-DIF-02','P1DIF02-R01','retest'),('P1-DIF-02','P1DIF02-R02','retest'),('P1-DIF-02','P1DIF02-M01','mixed'),
('P1-DIF-03','P1DIF03-D01','diagnostic'),('P1-DIF-03','P1DIF03-L01','learning'),('P1-DIF-03','P1DIF03-L02','learning'),('P1-DIF-03','P1DIF03-L03','learning'),('P1-DIF-03','P1DIF03-R01','retest'),('P1-DIF-03','P1DIF03-R02','retest'),('P1-DIF-03','P1DIF03-M01','mixed'),
('P1-DIF-04','P1DIF04-D01','diagnostic'),('P1-DIF-04','P1DIF04-L01','learning'),('P1-DIF-04','P1DIF04-L02','learning'),('P1-DIF-04','P1DIF04-L03','learning'),('P1-DIF-04','P1DIF04-R01','retest'),('P1-DIF-04','P1DIF04-R02','retest'),('P1-DIF-04','P1DIF04-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw17_20_diff_v1 from canonical Differentiation skill intent.','Cambridge 9709 2026-2027 v4; P1 1.7 Differentiation','Complete Pure Mathematics 1; Differentiation (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw17_20_diff_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw17_20_diff_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1DIF02-D01','B','coefficient_power_error','method','The derivative of 4x^(3/2) has coefficient 4×3/2=6.','Для 4x^(3/2) коэффициент производной равен 4×3/2=6.','4x^(3/2) hosilasida koeffitsiyent 4×3/2=6.','Multiply by the old exponent before reducing it by 1.','Сначала умножьте на старый показатель, затем уменьшите его на 1.','Avval eski darajaga ko‘paytirib, keyin darajani 1 ga kamaytiring.'),
('P1DIF02-D01','C','exponent_not_reduced','method','After differentiating x^(3/2), the exponent becomes 1/2, not 3/2.','После дифференцирования x^(3/2) показатель становится 1/2.','x^(3/2) differensiallanganda daraja 1/2 bo‘ladi.','Use nx^(n−1).','Используйте nx^(n−1).','nx^(n−1) ni ishlating.'),
('P1DIF02-D01','D','second_term_coefficient','method','The derivative of −3x² is −6x, not −3x.','Производная −3x² равна −6x, а не −3x.','−3x² hosilasi −6x, −3x emas.','Apply the power rule to every term.','Примените правило степени к каждому члену.','Har bir hadga daraja qoidasini qo‘llang.'),
('P1DIF03-D01','B','missing_inner_derivative','concept','The factor 2 from d(2x+1)/dx is missing.','Пропущен множитель 2 от производной 2x+1.','2x+1 ichki hosilasidan 2 ko‘paytuvchi yetishmaydi.','Multiply the outer derivative by the inner derivative.','Умножьте внешнюю производную на внутреннюю.','Tashqi hosilani ichki hosilaga ko‘paytiring.'),
('P1DIF03-D01','C','exponent_not_reduced','method','The outer exponent reduces from 5 to 4 after differentiation.','После дифференцирования внешний показатель уменьшается с 5 до 4.','Differensiallanganda tashqi daraja 5 dan 4 ga kamayadi.','Differentiate the outer power first.','Сначала продифференцируйте внешнюю степень.','Avval tashqi darajani differensiallang.'),
('P1DIF03-D01','D','drops_outer_coefficient','method','Both the outer factor 5 and inner factor 2 are required, giving 10.','Нужны оба множителя: внешний 5 и внутренний 2, итого 10.','Tashqi 5 va ichki 2 ikkalasi kerak, natija 10.','Write outer derivative × inner derivative explicitly.','Запишите явно внешняя производная × внутренняя производная.','Tashqi hosila × ichki hosilani aniq yozing.'),
('P1DIF04-D01','B','point_substitution_sign','method','The tangent must pass through (1,4); y=5x+1 gives y=6 at x=1.','Касательная должна проходить через (1,4); y=5x+1 этого не делает.','Urinma (1,4) dan o‘tishi kerak; y=5x+1 x=1 da 6 beradi.','Check the final line through the point of contact.','Проверьте, проходит ли прямая через точку касания.','Yakuniy chiziq tegish nuqtasidan o‘tishini tekshiring.'),
('P1DIF04-D01','C','uses_normal_gradient','concept','1/5 is related to the reciprocal, but the tangent gradient itself is 5.','1/5 связано с обратным коэффициентом, но градиент касательной равен 5.','1/5 teskari gradientga bog‘liq, ammo urinma gradienti 5.','Use dy/dx for the tangent; use negative reciprocal only for the normal.','Для касательной используйте dy/dx; отрицательную обратную — только для нормали.','Urinma uchun dy/dx, normal uchun manfiy teskari gradientni ishlating.'),
('P1DIF04-D01','D','uses_point_y_as_gradient','concept','The y-coordinate 4 is not the tangent gradient; the derivative gives gradient 5.','Координата y=4 не является градиентом; производная даёт 5.','y=4 koordinata gradient emas; hosila 5 beradi.','Separate the point value from dy/dx.','Разделяйте значение точки и dy/dx.','Nuqta qiymati va dy/dx ni ajrating.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_diff_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1DIF02-W01','P1-DIF-02','For f(x)=3x^(5/2)−4x^(3/2)+2x^(−1), find f′(x) and evaluate f′(4), showing the exponent changes clearly.','Для f(x)=3x^(5/2)−4x^(3/2)+2x^(−1) найдите f′(x) и f′(4), ясно показывая изменение показателей.','f(x)=3x^(5/2)−4x^(3/2)+2x^(−1) uchun f′(x) va f′(4) ni toping, darajalar o‘zgarishini ko‘rsating.','{"max_marks":10,"criteria":[{"id":"power_rule","marks":5,"rule":"Obtains f′(x)=(15/2)x^(3/2)−6x^(1/2)−2x^(−2)."},{"id":"substitution","marks":3,"rule":"Substitutes x=4 correctly."},{"id":"value","marks":2,"rule":"Obtains f′(4)=383/8."}]}','Apply nx^(n−1) term by term before substituting x=4.','Примените nx^(n−1) по членам до подстановки x=4.','x=4 ni qo‘yishdan oldin har bir hadga nx^(n−1) ni qo‘llang.'),
('P1DIF03-W01','P1-DIF-03','Differentiate f(x)=2(3x−1)^5−(4x+2)^3. Then find f′(1). Show the inner derivative factor for each term.','Найдите производную f(x)=2(3x−1)^5−(4x+2)^3, затем f′(1). Покажите внутренний множитель для каждого члена.','f(x)=2(3x−1)^5−(4x+2)^3 ni differensiallang, keyin f′(1) ni toping. Har bir had uchun ichki hosila ko‘paytuvchisini ko‘rsating.','{"max_marks":10,"criteria":[{"id":"first_chain","marks":3,"rule":"Gets 30(3x−1)^4."},{"id":"second_chain","marks":3,"rule":"Gets −12(4x+2)^2."},{"id":"substitution","marks":2,"rule":"Substitutes x=1 consistently."},{"id":"value","marks":2,"rule":"Obtains f′(1)=48."}]}','For each composite power write outer derivative × inner derivative.','Для каждой сложной степени пишите внешняя производная × внутренняя.','Har bir murakkab daraja uchun tashqi hosila × ichki hosilani yozing.'),
('P1DIF04-W01','P1-DIF-04','For y=(2x+1)^3, find the point, tangent equation and normal equation at x=1. Verify that both lines pass through the same point and that their gradients multiply to −1.','Для y=(2x+1)^3 найдите точку, уравнение касательной и нормали при x=1. Проверьте, что обе прямые проходят через одну точку и произведение их градиентов равно −1.','y=(2x+1)^3 uchun x=1 dagi nuqta, urinma va normal tenglamalarini toping. Ikkala chiziq bir nuqtadan o‘tishi va gradientlar ko‘paytmasi −1 ekanini tekshiring.','{"max_marks":11,"criteria":[{"id":"point","marks":2,"rule":"Gets (1,27)."},{"id":"derivative","marks":2,"rule":"Gets dy/dx=6(2x+1)^2 and tangent gradient 54."},{"id":"tangent","marks":3,"rule":"Gets y−27=54(x−1)."},{"id":"normal","marks":3,"rule":"Gets y−27=−(1/54)(x−1)."},{"id":"verification","marks":1,"rule":"Checks shared point and product −1."}]}','Find the contact point before forming either line; the normal uses the negative reciprocal gradient.','Сначала найдите точку касания; для нормали используйте отрицательную обратную градиента.','Avval tegish nuqtasini toping; normal uchun gradientning manfiy teskarisini ishlating.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_diff_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw17_diff_diagnostic','diagnostic','P1 AW17-20 Differentiation diagnostic','Диагностика P1 AW17–20: производная','P1 AW17–20 hosila diagnostikasi'),
('p1_dif02_learning','learning','Power rule learning','Правило степени: обучение','Daraja qoidasi: o‘rganish'),('p1_dif03_learning','learning','Chain rule learning','Цепное правило: обучение','Zanjir qoidasi: o‘rganish'),('p1_dif04_learning','learning','Tangent and normal learning','Касательная и нормаль: обучение','Urinma va normal: o‘rganish'),
('p1_dif02_retest','retest','DIF-02 delayed retest','DIF-02 отложенный ретест','DIF-02 kechiktirilgan retest'),('p1_dif03_retest','retest','DIF-03 delayed retest','DIF-03 отложенный ретест','DIF-03 kechiktirilgan retest'),('p1_dif04_retest','retest','DIF-04 delayed retest','DIF-04 отложенный ретест','DIF-04 kechiktirilgan retest'),
('p1_aw17_diff_mixed','mixed','P1 AW17-20 Differentiation mixed transfer','P1 AW17–20: смешанный перенос производной','P1 AW17–20 hosila mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw17_20_diff_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw17_diff_diagnostic',1,'P1DIF02-D01',null,'P1-DIF-02','diagnostic',true),('p1_aw17_diff_diagnostic',2,'P1DIF03-D01',null,'P1-DIF-03','diagnostic',true),('p1_aw17_diff_diagnostic',3,'P1DIF04-D01',null,'P1-DIF-04','diagnostic',true),
('p1_dif02_learning',1,'P1DIF02-L01',null,'P1-DIF-02','learning',false),('p1_dif02_learning',2,'P1DIF02-L02',null,'P1-DIF-02','learning',false),('p1_dif02_learning',3,'P1DIF02-L03',null,'P1-DIF-02','learning',false),('p1_dif02_learning',4,null,'P1DIF02-W01','P1-DIF-02','written',false),
('p1_dif03_learning',1,'P1DIF03-L01',null,'P1-DIF-03','learning',false),('p1_dif03_learning',2,'P1DIF03-L02',null,'P1-DIF-03','learning',false),('p1_dif03_learning',3,'P1DIF03-L03',null,'P1-DIF-03','learning',false),('p1_dif03_learning',4,null,'P1DIF03-W01','P1-DIF-03','written',false),
('p1_dif04_learning',1,'P1DIF04-L01',null,'P1-DIF-04','learning',false),('p1_dif04_learning',2,'P1DIF04-L02',null,'P1-DIF-04','learning',false),('p1_dif04_learning',3,'P1DIF04-L03',null,'P1-DIF-04','learning',false),('p1_dif04_learning',4,null,'P1DIF04-W01','P1-DIF-04','written',false),
('p1_dif02_retest',1,'P1DIF02-R01',null,'P1-DIF-02','retest',true),('p1_dif03_retest',1,'P1DIF03-R01',null,'P1-DIF-03','retest',true),('p1_dif04_retest',1,'P1DIF04-R01',null,'P1-DIF-04','retest',true),
('p1_aw17_diff_mixed',1,'P1DIF02-M01',null,'P1-DIF-02','mixed',true),('p1_aw17_diff_mixed',2,'P1DIF03-M01',null,'P1-DIF-03','mixed',true),('p1_aw17_diff_mixed',3,'P1DIF04-M01',null,'P1-DIF-04','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw17_20_diff_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw17_20_diff_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw17_20_diff_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw17_20_diff_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw17_20_diff_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw17_20_diff_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P1-DIF-02','P1-DIF-03','P1-DIF-04'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'Differentiation skill not ready %',v_skill; end if; end loop;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw17_20_diff_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
