-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 6; rows 71-81 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(26,'P5','5.4 Discrete random variables','P5-BIN-02','Вычислять point, interval и cumulative binomial probabilities.','P5-BIN-01; P5-CNT-05; PR-CAL-01','Complete Probability & Statistics 1, Ch7 The binomial distribution','pp. 115–131','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(27,'P5','5.4 Discrete random variables','P5-BIN-03','Использовать binomial mean/variance и решать inverse parameter problems.','P5-BIN-01; P5-DRV-02; P5-DRV-03','Complete Probability & Statistics 1, Ch7 The binomial distribution','pp. 115–131','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(28,'P5','5.4 Discrete random variables','P5-GEO-01','Распознавать geometric model как waiting time to first success и проверять assumptions.','P5-PRO-04; P5-DRV-01','Complete Probability & Statistics 1, Ch8 The geometric distribution','pp. 133–145','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E3 Core Coverage II (декабрь–январь)','КРИТИЧЕСКИЙ institutional gap: geometric distribution отсутствует в plan v2.0; добавить Ch8 и отдельный mastery node. В учебнике и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(29,'P5','5.4 Discrete random variables','P5-GEO-02','Вычислять exact/cumulative geometric probabilities, включая complements.','P5-GEO-01; P5-PRO-03; PR-ALG-02','Complete Probability & Statistics 1, Ch8 The geometric distribution','pp. 133–145','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','КРИТИЧЕСКИЙ institutional gap: geometric distribution отсутствует в plan v2.0; добавить Ch8 и отдельный mastery node. В учебнике и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(30,'P5','5.4 Discrete random variables','P5-GEO-03','Использовать geometric expectation и восстанавливать parameter p.','P5-GEO-01; P5-DRV-02; PR-EQN-01','Complete Probability & Statistics 1, Ch8 The geometric distribution','pp. 133–145','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E3 Core Coverage II (декабрь–январь)','КРИТИЧЕСКИЙ institutional gap: geometric distribution отсутствует в plan v2.0; добавить Ch8 и отдельный mastery node. В учебнике и syllabus покрыто.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(31,'P5','5.5 The normal distribution','P5-NOR-01','Распознавать normal model, использовать notation и sketch с μ/σ.','P5-DAT-06; P5-DAT-07; PR-GRF-01','Complete Probability & Statistics 1, Ch9 The normal distribution','pp. 147–171','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(32,'P5','5.5 The normal distribution','P5-NOR-02','Стандартизовать normal variable и использовать tables/calculator с корректным tail.','P5-NOR-01; PR-ALG-03; PR-CAL-01','Complete Probability & Statistics 1, Ch9 The normal distribution','pp. 147–171','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(33,'P5','5.5 The normal distribution','P5-NOR-03','Вычислять direct normal probabilities для intervals/tails.','P5-NOR-02; P5-PRO-03','Complete Probability & Statistics 1, Ch9 The normal distribution','pp. 147–171','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E3 Core Coverage II (декабрь–январь)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(34,'P5','5.5 The normal distribution','P5-NOR-04','Находить inverse normal quantiles/critical values по заданной probability.','P5-NOR-02; PR-EQN-01','Complete Probability & Statistics 1, Ch9 The normal distribution','pp. 147–171','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(35,'P5','5.5 The normal distribution','P5-NOR-05','Находить unknown μ и/или σ из probability/quantile conditions.','P5-NOR-04; PR-ALG-03; PR-EQN-01','Complete Probability & Statistics 1, Ch9 The normal distribution','pp. 147–171','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(36,'P5','5.5 The normal distribution','P5-NOR-06','Применять normal approximation to binomial с conditions и continuity correction.','P5-BIN-02; P5-BIN-03; P5-NOR-03','Complete Probability & Statistics 1, Ch10 Normal approximation to binomial','pp. 173–179','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E4 Complete Coverage (январь–февраль)','Math Tour Map относится к P1; plan v2.0 и учебник покрывают этот P5 skill. Компонентная mastery — только P5.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
