-- P1-02 intentional diagnostic interpretations for the six newly authored opening skills.
-- Three wrong-option rules per diagnostic item; private only.

begin;
with rules(cvkey,ckey,match,dcode,mtype,skill,fen,fru,fuz,nen,nru,nuz) as (values
('p1_foundations_runway_v1','P1QUA01-D01','B','constant_not_adjusted','method','P1-QUA-01','Completing the square changes the constant: adding 9 inside (x − 3)² must be offset outside.','При выделении полного квадрата меняется свободный член: добавленные 9 внутри (x − 3)² нужно компенсировать снаружи.','To‘liq kvadrat ajratilganda doimiy had o‘zgaradi: (x − 3)² ichidagi qo‘shilgan 9 tashqarida qoplanishi kerak.','Expand your completed-square form to verify every coefficient.','Раскройте скобки в полученной форме и проверьте все коэффициенты.','Hosil qilgan to‘liq kvadrat ko‘rinishini ochib, barcha koeffitsiyentlarni tekshiring.'),
('p1_foundations_runway_v1','P1QUA01-D01','C','linear_sign_error','algebra','P1-QUA-01','The sign inside the square must reproduce −6x; (x + 3)² produces +6x.','Знак внутри квадрата должен давать −6x; (x + 3)² даёт +6x.','Kvadrat ichidagi ishora −6x ni berishi kerak; (x + 3)² esa +6x beradi.','Check the middle term after expanding (x ± a)².','Проверьте средний член после раскрытия (x ± a)².','(x ± a)² ni ochgandan keyin o‘rta hadni tekshiring.'),
('p1_foundations_runway_v1','P1QUA01-D01','D','halving_error','method','P1-QUA-01','The shift is half the x-coefficient, not the full coefficient: −6 gives a shift of 3.','Сдвиг равен половине коэффициента при x, а не всему коэффициенту: из −6 получается 3.','Siljish x koeffitsiyentining yarmi bo‘ladi: −6 dan 3 olinadi.','Use half the linear coefficient, then square it and compensate the constant.','Возьмите половину линейного коэффициента, возведите её в квадрат и компенсируйте свободный член.','Chiziqli koeffitsiyentning yarmini oling, kvadratga oshiring va doimiy hadni qoplang.'),

('p1_foundations_runway_v1','P1QUA02-D01','A','discriminant_arithmetic','method','P1-QUA-02','Equal roots require b² − 4ac = 0. Substituting a = 1, b = 4, c = k gives 16 − 4k = 0, not k = 2.','Для равных корней b² − 4ac = 0. При a = 1, b = 4, c = k получаем 16 − 4k = 0, а не k = 2.','Teng ildizlar uchun b² − 4ac = 0. a = 1, b = 4, c = k qo‘ysak 16 − 4k = 0 chiqadi, k = 2 emas.','Write a, b and c explicitly before forming the discriminant.','Сначала явно выпишите a, b и c, затем составьте дискриминант.','Avval a, b va c ni aniq yozing, keyin diskriminantni tuzing.'),
('p1_foundations_runway_v1','P1QUA02-D01','C','forgot_factor_4ac','method','P1-QUA-02','The discriminant uses 4ac, not ac. Omitting the factor 4 changes the parameter condition.','В дискриминанте используется 4ac, а не ac. Пропуск множителя 4 меняет условие на параметр.','Diskriminantda ac emas, 4ac ishlatiladi. 4 ko‘paytuvchini tashlab yuborish parametr shartini o‘zgartiradi.','Use Δ = b² − 4ac and set Δ = 0 for equal roots.','Используйте Δ = b² − 4ac и при равных корнях положите Δ = 0.','Δ = b² − 4ac dan foydalaning va teng ildizlar uchun Δ = 0 qiling.'),
('p1_foundations_runway_v1','P1QUA02-D01','D','used_b_squared_only','concept','P1-QUA-02','Using b² alone ignores the constant term. Root type is determined by the complete discriminant b² − 4ac.','Использование только b² игнорирует свободный член. Тип корней определяется полным дискриминантом b² − 4ac.','Faqat b² ni ishlatish doimiy hadni e’tiborsiz qoldiradi. Ildiz turi to‘liq b² − 4ac diskriminanti bilan aniqlanadi.','Relate the sign of the full discriminant to the number of real roots.','Свяжите знак полного дискриминанта с числом действительных корней.','To‘liq diskriminant ishorasini haqiqiy ildizlar soni bilan bog‘lang.'),

('p1_foundations_runway_v1','P1QUA03-D01','B','signs_reversed','algebra','P1-QUA-03','The factors are (2x − 1)(x − 3), so setting each factor to zero gives positive 1/2 and 3, not both negatives.','Разложение равно (2x − 1)(x − 3), поэтому корни 1/2 и 3, а не оба отрицательные.','Ko‘paytuvchilarga ajratish (2x − 1)(x − 3), shuning uchun ildizlar 1/2 va 3, ikkalasi ham manfiy emas.','Substitute each proposed root back into the original equation as a quick check.','Подставьте каждый предполагаемый корень обратно в исходное уравнение.','Har bir taxminiy ildizni dastlabki tenglamaga qo‘yib tekshiring.'),
('p1_foundations_runway_v1','P1QUA03-D01','C','factor_pair_error','method','P1-QUA-03','The proposed roots do not give product c/a = 3/2. For this quadratic the product of roots must be 3/2 and their sum 7/2.','Предложенные корни не дают произведение c/a = 3/2. Здесь произведение корней 3/2, а сумма 7/2.','Taklif qilingan ildizlar c/a = 3/2 ko‘paytmani bermaydi. Bu tenglamada ildizlar ko‘paytmasi 3/2, yig‘indisi 7/2 bo‘lishi kerak.','Use factorisation or check roots using sum/product before finalising.','Используйте разложение или проверьте корни по сумме и произведению.','Ko‘paytuvchilarga ajrating yoki ildizlarni yig‘indi va ko‘paytma orqali tekshiring.'),
('p1_foundations_runway_v1','P1QUA03-D01','D','single_coefficient_guess','method','P1-QUA-03','Choosing numbers from coefficients without satisfying both factor conditions does not solve the quadratic.','Выбор чисел из коэффициентов без выполнения обоих условий разложения не решает квадратное уравнение.','Koeffitsiyentlardan sonlarni tanlashning o‘zi yetarli emas; ko‘paytuvchilarga ajratishning ikkala sharti ham bajarilishi kerak.','Verify by expanding your factors back to 2x² − 7x + 3.','Разверните выбранные множители обратно и получите 2x² − 7x + 3.','Tanlangan ko‘paytuvchilarni ochib, 2x² − 7x + 3 hosil bo‘lishini tekshiring.'),

('p1_foundations_runway_v1','P1FUN01-D01','B','inverse_confused_with_function','concept','P1-FUN-01','“Each output has exactly one input” describes the stronger one-one condition, not the basic definition of a function.','«Каждому выходу соответствует ровно один вход» — это более сильное условие взаимной однозначности, а не определение функции.','“Har bir chiqishga aynan bitta kirish” — funksiya ta’rifi emas, kuchliroq bir-biriga bir qiymatlilik sharti.','Separate the definition of function from the additional one-one property.','Отделите определение функции от дополнительного свойства взаимной однозначности.','Funksiya ta’rifini qo‘shimcha bir-biriga bir qiymatlilik xossasidan ajrating.'),
('p1_foundations_runway_v1','P1FUN01-D01','C','unrelated_sign_restriction','concept','P1-FUN-01','Inputs and outputs do not need to be positive; the allowed domain and rule determine their values.','Входы и выходы не обязаны быть положительными; их задают область определения и правило функции.','Kirish va chiqishlar musbat bo‘lishi shart emas; ularni aniqlanish sohasi va funksiya qoidasi belgilaydi.','Ask only whether every permitted input has one well-defined output.','Проверяйте только: имеет ли каждый допустимый вход ровно один определённый выход.','Faqat har bir ruxsat etilgan kirishning bitta aniq chiqishi bor-yo‘qligini tekshiring.'),
('p1_foundations_runway_v1','P1FUN01-D01','D','graph_shape_myth','concept','P1-FUN-01','Functions can have many graph shapes; being a straight line is not required.','График функции может иметь разную форму; быть прямой линией не требуется.','Funksiya grafigi turli shaklda bo‘lishi mumkin; to‘g‘ri chiziq bo‘lishi shart emas.','Use the input-output definition rather than the visual shape of one special family.','Используйте определение через вход и выход, а не форму графика отдельного семейства.','Bitta maxsus oilaning grafik shakliga emas, kirish-chiqish ta’rifiga tayaning.'),

('p1_foundations_runway_v1','P1FUN02-D01','B','endpoint_only_minimum','method','P1-FUN-02','The interval contains x = 0, where x² + 1 reaches 1. Checking only endpoints misses the interior minimum.','Интервал содержит x = 0, где x² + 1 достигает 1. Проверка только концов пропускает внутренний минимум.','Interval x = 0 ni o‘z ichiga oladi, bu yerda x² + 1 qiymati 1. Faqat chegaralarni tekshirish ichki minimumni o‘tkazib yuboradi.','Check turning points inside the restricted domain as well as endpoints.','Проверяйте точки экстремума внутри ограниченной области вместе с концами.','Chegaralar bilan birga cheklangan soha ichidagi burilish nuqtalarini ham tekshiring.'),
('p1_foundations_runway_v1','P1FUN02-D01','C','wrong_max_endpoint','method','P1-FUN-02','At x = 3 the function equals 10, so 5 cannot be the maximum on the stated domain.','При x = 3 функция равна 10, поэтому 5 не может быть максимумом на заданной области.','x = 3 da funksiya 10 ga teng, shuning uchun berilgan sohada maksimum 5 bo‘la olmaydi.','Evaluate both endpoints and any internal turning point before writing the range.','Перед записью области значений вычислите оба конца и внутренние точки экстремума.','Qiymatlar sohasini yozishdan oldin ikkala chegara va ichki burilish nuqtalarini hisoblang.'),
('p1_foundations_runway_v1','P1FUN02-D01','D','domain_used_as_range','concept','P1-FUN-02','The domain interval is not automatically the range. The range must be found from the output values f(x).','Область определения не равна автоматически области значений. Область значений находят по выходам f(x).','Aniqlanish sohasi avtomatik ravishda qiymatlar sohasi bo‘lmaydi. Qiymatlar sohasi f(x) chiqishlaridan topiladi.','Map the restricted x-values through the function and identify output extrema.','Преобразуйте допустимые x через функцию и найдите экстремальные выходные значения.','Cheklangan x qiymatlarini funksiya orqali o‘tkazib, chiqish ekstremumlarini toping.'),

('p5_dat02_runway_v1','P5DAT02-D01','B','decimal_key_misread','representation','P5-DAT-02','The key says 1 | 2 = 12, so the stem is tens and the leaf is units; it is not a decimal 1.2.','Ключ 1 | 2 = 12 означает десятки в стебле и единицы в листе; это не десятичное число 1,2.','Kalit 1 | 2 = 12 poya o‘nlik, barg birlik ekanini bildiradi; bu 1.2 o‘nli soni emas.','Read the key before interpreting any stem-and-leaf value.','Сначала прочитайте ключ, затем интерпретируйте значения.','Har qanday qiymatni talqin qilishdan oldin kalitni o‘qing.'),
('p5_dat02_runway_v1','P5DAT02-D01','C','stem_leaf_concatenation_error','representation','P5-DAT-02','Each leaf pairs with its own stem. On stem 1, leaves 2, 4 and 7 mean 12, 14 and 17—not 12, 24 and 27.','Каждый лист соединяется со своим стеблем. У стебля 1 листья 2, 4, 7 означают 12, 14, 17, а не 12, 24, 27.','Har bir barg o‘z poyasi bilan juftlanadi. 1 poyadagi 2, 4, 7 barglar 12, 14, 17 ni bildiradi, 12, 24, 27 ni emas.','Combine each leaf with the stem shown on the same row.','Соединяйте каждый лист со стеблем той же строки.','Har bir bargni aynan o‘sha qatordagi poya bilan birlashtiring.'),
('p5_dat02_runway_v1','P5DAT02-D01','D','lost_place_value','representation','P5-DAT-02','Reading leaves alone discards place value. The stem-and-leaf key is needed to reconstruct the original observations.','Чтение одних листьев теряет разрядность. Для восстановления исходных наблюдений нужен ключ и стебель.','Faqat barglarni o‘qish razryad qiymatini yo‘qotadi. Asl kuzatuvlarni tiklash uchun poya va kalit kerak.','Use both stem and leaf for every observation.','Для каждого наблюдения используйте и стебель, и лист.','Har bir kuzatuv uchun ham poya, ham bargdan foydalaning.')
), meta as (
  select m.id,m.content_key,cv.content_version
  from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id
  where m.reserve_role='diagnostic' and cv.content_version in ('p1_foundations_runway_v1','p5_dat02_runway_v1')
)
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,r.skill,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now()
from rules r join meta on meta.content_version=r.cvkey and meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

do $$ declare v_bad int; begin
  select count(*) into v_bad from (
    select m.id from private.exam_prep_question_content_meta m
    join private.exam_prep_content_versions cv on cv.id=m.content_version_id
    left join private.exam_prep_diagnostic_rules r on r.content_meta_id=m.id and r.status='approved'
    where cv.content_version in ('p1_foundations_runway_v1','p5_dat02_runway_v1') and m.reserve_role='diagnostic'
    group by m.id having count(r.id)<>3
  ) x;
  if v_bad<>0 then raise exception 'P1-02 diagnostic rule floor failed for % items',v_bad; end if;
end $$;

commit;
