-- P1-02 original iClub content: P1-QUA-02 discriminant/parameter conditions.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1QUA02-D01','diagnostic','medium','The equation x² + 4x + k = 0 has equal real roots. Find k.','Уравнение x² + 4x + k = 0 имеет равные действительные корни. Найдите k.','x² + 4x + k = 0 tenglama teng haqiqiy ildizlarga ega. k ni toping.','["2","4","8","16"]','B','Equal roots require discriminant 0: 4² − 4k = 0, so k = 4.','Для равных корней дискриминант равен 0: 4² − 4k = 0, откуда k = 4.','Teng ildizlar uchun diskriminant 0: 4² − 4k = 0, demak k = 4.',70),
('P1QUA02-L01','learning','easy','How many real roots does x² − 6x + 10 = 0 have?','Сколько действительных корней имеет x² − 6x + 10 = 0?','x² − 6x + 10 = 0 tenglama nechta haqiqiy ildizga ega?','["0","1","2","3"]','A','The discriminant is 36 − 40 = −4 < 0, so there are no real roots.','Дискриминант 36 − 40 = −4 < 0, поэтому действительных корней нет.','Diskriminant 36 − 40 = −4 < 0, shuning uchun haqiqiy ildiz yo‘q.',55),
('P1QUA02-L02','learning','medium','For which values of k does 2x² + kx + 8 = 0 have two distinct real roots?','При каких k уравнение 2x² + kx + 8 = 0 имеет два различных действительных корня?','Qaysi k qiymatlarida 2x² + kx + 8 = 0 tenglama ikkita turli haqiqiy ildizga ega?','["−8 < k < 8","k ≤ −8 or k ≥ 8","k < −8 or k > 8","k > 8 only"]','C','Two distinct real roots require k² − 64 > 0, so k < −8 or k > 8.','Для двух различных действительных корней нужно k² − 64 > 0, то есть k < −8 или k > 8.','Ikkita turli haqiqiy ildiz uchun k² − 64 > 0, ya’ni k < −8 yoki k > 8.',70),
('P1QUA02-L03','learning','medium','For which value of k does x² − 2(k + 1)x + k² = 0 have equal roots?','При каком k уравнение x² − 2(k + 1)x + k² = 0 имеет равные корни?','Qaysi k qiymatida x² − 2(k + 1)x + k² = 0 tenglama teng ildizlarga ega?','["−1","−1/2","0","1/2"]','B','The discriminant is 4(k + 1)² − 4k² = 4(2k + 1). Setting it to 0 gives k = −1/2.','Дискриминант равен 4(k + 1)² − 4k² = 4(2k + 1). Приравнивая к 0, получаем k = −1/2.','Diskriminant 4(k + 1)² − 4k² = 4(2k + 1). Uni 0 ga tenglashtirib, k = −1/2 ni olamiz.',75),
('P1QUA02-R01','retest','medium','For which values of c does 3x² − 6x + c = 0 have no real roots?','При каких c уравнение 3x² − 6x + c = 0 не имеет действительных корней?','Qaysi c qiymatlarida 3x² − 6x + c = 0 tenglama haqiqiy ildizga ega emas?','["c < 3","c = 3","c > 3","c ≥ 3"]','C','No real roots require 36 − 12c < 0, hence c > 3.','Для отсутствия действительных корней нужно 36 − 12c < 0, следовательно c > 3.','Haqiqiy ildiz bo‘lmasligi uchun 36 − 12c < 0, demak c > 3.',70),
('P1QUA02-R02','retest','medium','For which values of p does x² + px + 9 = 0 have two distinct real roots?','При каких p уравнение x² + px + 9 = 0 имеет два различных действительных корня?','Qaysi p qiymatlarida x² + px + 9 = 0 tenglama ikkita turli haqiqiy ildizga ega?','["−6 < p < 6","p < −6 or p > 6","p ≤ −6 or p ≥ 6","p > 6 only"]','B','The discriminant must be positive: p² − 36 > 0, so p < −6 or p > 6.','Дискриминант должен быть положительным: p² − 36 > 0, поэтому p < −6 или p > 6.','Diskriminant musbat bo‘lishi kerak: p² − 36 > 0, demak p < −6 yoki p > 6.',70),
('P1QUA02-M01','mixed','medium','The horizontal line y = k is tangent to y = x² + 2x + 5. Find k.','Горизонтальная прямая y = k касается параболы y = x² + 2x + 5. Найдите k.','y = k gorizontal chiziq y = x² + 2x + 5 parabolaga urinadi. k ni toping.','["3","4","5","6"]','B','Tangency gives one repeated solution of x² + 2x + 5 = k. The discriminant is 4 − 4(5 − k) = 4k − 16, so k = 4.','Касание означает двойной корень у x² + 2x + 5 = k. Дискриминант 4 − 4(5 − k) = 4k − 16, поэтому k = 4.','Urinish x² + 2x + 5 = k tenglamada takroriy ildiz beradi. Diskriminant 4 − 4(5 − k) = 4k − 16, demak k = 4.',80)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Quadratics','P1-QUA-02',s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_foundations_runway_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
keys(k,role) as (values('P1QUA02-D01','diagnostic'),('P1QUA02-L01','learning'),('P1QUA02-L02','learning'),('P1QUA02-L03','learning'),('P1QUA02-R01','retest'),('P1QUA02-R02','retest'),('P1QUA02-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-QUA-02','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, numbers, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored for p1_foundations_runway_v1 from canonical P1-QUA-02 intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.1 Quadratics','Complete Pure Mathematics 1, Ch1 Quadratics pp.2-20 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
commit;
