-- P1-02 P5 AW13-16: BIN-01 binomial model recognition and assumptions.
-- Original iClub-authored content only; governed publication; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw13_16_bin01_v1','P5','P5 AW13-16 BIN-01 binomial model selection','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_bin01_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5BIN01-D01','diagnostic','medium','Five cards are drawn without replacement from a standard deck and X is the number of aces drawn. Why is X not exactly binomial?','Из стандартной колоды без возвращения выбирают 5 карт, X — число тузов. Почему X не имеет точного биномиального распределения?','Standart kolodadan qaytarmasdan 5 karta olinadi, X — tushgan aslar soni. Nega X aniq binomial taqsimotga ega emas?','["The trials are dependent and the success probability changes","There are only two outcome categories","The number of trials is fixed","Zero aces is possible"]','["Испытания зависимы, и вероятность успеха меняется","Есть только две категории исхода","Число испытаний фиксировано","Возможно получить ноль тузов"]','["Sinovlar bog‘liq va muvaffaqiyat ehtimoli o‘zgaradi","Faqat ikki natija toifasi bor","Sinovlar soni qat’iy","Nol ta as chiqishi mumkin"]','A','Without replacement, the deck composition changes after each draw, so trials are dependent and p is not constant.','Без возвращения состав колоды меняется после каждого выбора, поэтому испытания зависимы и p непостоянна.','Qaytarmasdan olinganda koloda tarkibi har safar o‘zgaradi, shuning uchun sinovlar bog‘liq va p doimiy emas.',65),
('P5BIN01-L01','learning','easy','Ten independent bulbs are tested. Each bulb is defective with probability 0.03. Which model fits the number X of defective bulbs?','Проверяют 10 независимых ламп. Каждая дефектна с вероятностью 0,03. Какая модель подходит для числа X дефектных ламп?','10 ta mustaqil lampa tekshiriladi. Har birining nuqsonli bo‘lish ehtimoli 0.03. Nuqsonli lampalar soni X uchun qaysi model mos?','["X~B(10,0.03)","X~B(0.03,10)","A geometric model","No probability model"]','["X~B(10;0,03)","X~B(0,03;10)","Геометрическая модель","Вероятностная модель неприменима"]','["X~B(10,0.03)","X~B(0.03,10)","Geometrik model","Ehtimollik modeli yo‘q"]','A','There are fixed n=10 independent trials, two outcomes and constant p=0.03.','Есть фиксированные n=10 независимых испытаний, два исхода и постоянная p=0,03.','n=10 qat’iy mustaqil sinov, ikki natija va doimiy p=0.03 mavjud.',40),
('P5BIN01-L02','learning','easy','A fair die is rolled 8 times and X is the number of sixes. What are the binomial parameters?','Честный кубик бросают 8 раз, X — число шестёрок. Каковы параметры биномиальной модели?','Adolatli kubik 8 marta tashlanadi, X — oltilar soni. Binomial model parametrlari qanday?','["n=8, p=1/6","n=6, p=1/8","n=8, p=5/6","n=1/6, p=8"]','["n=8, p=1/6","n=6, p=1/8","n=8, p=5/6","n=1/6, p=8"]','["n=8, p=1/6","n=6, p=1/8","n=8, p=5/6","n=1/6, p=8"]','A','Each roll is an independent trial; success is a six with constant probability 1/6.','Каждый бросок независим; успех — выпадение шестёрки с постоянной вероятностью 1/6.','Har bir tashlash mustaqil; muvaffaqiyat — olti tushishi, doimiy ehtimol 1/6.',40),
('P5BIN01-L03','learning','medium','A coin is tossed repeatedly until the first tail occurs. Is the number of heads before the first tail binomial?','Монету подбрасывают до первого выпадения решки. Имеет ли число орлов до первой решки биномиальное распределение?','Tanga birinchi gerb bo‘lmagan tomon tushguncha tashlanadi. Birinchi dumgacha gerblar soni binomialmi?','["No, because the number of trials is not fixed in advance","Yes, because every toss has two outcomes","Yes, because tosses are independent","No, because p is greater than 1"]','["Нет, число испытаний заранее не фиксировано","Да, потому что у каждого броска два исхода","Да, потому что броски независимы","Нет, потому что p больше 1"]','["Yo‘q, chunki sinovlar soni oldindan qat’iy emas","Ha, chunki har tashlashda ikki natija bor","Ha, chunki tashlashlar mustaqil","Yo‘q, chunki p 1 dan katta"]','A','Binomial counting needs a fixed number of trials. Stopping at the first tail creates a waiting-time setting instead.','Для биномиальной модели число испытаний должно быть фиксировано. Остановка при первой решке создаёт задачу ожидания.','Binomial sanashda sinovlar soni qat’iy bo‘lishi kerak. Birinchi dumda to‘xtash kutish-vaqti holatini beradi.',55),
('P5BIN01-R01','retest','easy','A player takes 20 independent free throws, each with the same scoring probability p. Which model fits the number scored?','Игрок выполняет 20 независимых штрафных бросков с одинаковой вероятностью попадания p. Какая модель подходит для числа попаданий?','O‘yinchi 20 ta mustaqil jarima to‘pi otadi, har birida tushirish ehtimoli p bir xil. Tushganlar soni uchun qaysi model mos?','["B(20,p)","Geometric(p)","B(p,20)","No model because p is unknown"]','["B(20,p)","Geometric(p)","B(p,20)","Модель неприменима, потому что p неизвестна"]','["B(20,p)","Geometric(p)","B(p,20)","p noma’lumligi sabab model yo‘q"]','A','The binomial assumptions are stated directly; p may remain symbolic.','Условия биномиальной модели заданы напрямую; p может оставаться символом.','Binomial shartlar bevosita berilgan; p ramziy qolishi mumkin.',40),
('P5BIN01-R02','retest','medium','Four students are selected without replacement from a class and X counts left-handed students. Which binomial assumption is most directly violated?','Из класса без возвращения выбирают 4 учеников, X — число левшей. Какое условие биномиальной модели нарушается наиболее прямо?','Sinfdan qaytarmasdan 4 o‘quvchi tanlanadi, X — chapaqaylar soni. Binomial modelning qaysi sharti eng to‘g‘ridan-to‘g‘ri buziladi?','["Independence/constant success probability","Fixed number of trials","Two outcome categories","X is a count"]','["Независимость/постоянная вероятность успеха","Фиксированное число испытаний","Две категории исходов","X является счётчиком"]','["Mustaqillik/doimiy muvaffaqiyat ehtimoli","Qat’iy sinovlar soni","Ikki natija toifasi","X sanash miqdori"]','A','Without replacement, one selection changes the composition for the next selection.','При выборе без возвращения один выбор меняет состав для следующего.','Qaytarmasdan tanlashda bir tanlov keyingi tarkibni o‘zgartiradi.',50),
('P5BIN01-M01','mixed','medium','Which situation is modelled by X~B(12,0.4)?','Какую ситуацию моделирует X~B(12;0,4)?','Qaysi holat X~B(12,0.4) bilan modellashtiriladi?','["The number of successes in 12 independent trials, each with success probability 0.4","The trial number on which the first success occurs when p=0.4","The number selected until 12 successes occur","A sample of 12 drawn without replacement from a changing population"]','["Число успехов в 12 независимых испытаниях с вероятностью успеха 0,4 в каждом","Номер испытания первого успеха при p=0,4","Число испытаний до 12 успехов","Выборка 12 без возвращения из меняющейся совокупности"]','["Har biri p=0.4 bo‘lgan 12 mustaqil sinovdagi muvaffaqiyatlar soni","p=0.4 da birinchi muvaffaqiyat chiqqan sinov raqami","12 muvaffaqiyatgacha sinovlar soni","O‘zgaruvchi to‘plamdan qaytarmasdan 12 tanlov"]','A','B(n,p) counts successes in a fixed number n of independent constant-p trials.','B(n,p) считает успехи в фиксированном числе n независимых испытаний с постоянной p.','B(n,p) qat’iy n ta mustaqil, doimiy-p sinovdagi muvaffaqiyatlarni sanaydi.',50)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Binomial Distribution','P5-BIN-01',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw13_16_bin01_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_bin01_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_bin01_v1' and status='draft'), keys(k,role) as (values('P5BIN01-D01','diagnostic'),('P5BIN01-L01','learning'),('P5BIN01-L02','learning'),('P5BIN01-L03','learning'),('P5BIN01-R01','retest'),('P5BIN01-R02','retest'),('P5BIN01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-BIN-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw13_16_bin01_v1 from canonical BIN-01 intent.','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1; Binomial distribution (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_bin01_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw13_16_bin01_v1' and m.content_key='P5BIN01-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','two_categories_not_problem','concept','Having two categories—ace or not ace—is actually compatible with a binomial trial; the problem is dependence after drawing without replacement.','Две категории — туз или не туз — как раз совместимы с биномиальным испытанием; проблема в зависимости при выборе без возвращения.','Ikki toifa — as yoki as emas — binomial sinovga mos; muammo qaytarmasdan tanlashdagi bog‘liqlikda.','Check all four conditions, especially independence and constant p.','Проверьте все четыре условия, особенно независимость и постоянство p.','To‘rtta shartni, ayniqsa mustaqillik va doimiy p ni tekshiring.'),
('C','fixed_n_not_problem','concept','A fixed five draws supports the binomial model rather than invalidating it.','Фиксированные пять выборов поддерживают биномиальную модель, а не нарушают её.','Qat’iy beshta tanlov binomial modelni qo‘llab-quvvatlaydi, buzmaydi.','Identify the condition that changes after each draw.','Какое условие меняется после каждого выбора?','Har bir tanlovdan keyin qaysi shart o‘zgarishini aniqlang.'),
('D','zero_success_valid','concept','A binomial variable may take the value zero; zero successes is not a violation.','Биномиальная случайная величина может быть равна нулю; ноль успехов не нарушает модель.','Binomial tasodifiy miqdor nol bo‘lishi mumkin; nol muvaffaqiyat modelni buzmaydi.','Focus on whether trials are independent with the same p.','Сосредоточьтесь на независимости испытаний и одинаковой p.','Sinovlar mustaqil va p bir xilmi — shunga e’tibor bering.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-BIN-01',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from meta cross join r
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_bin01_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5BIN01-W01','P5','P5-BIN-01','wtv1','For each scenario, decide whether a binomial model is valid and justify your decision using fixed n, two outcome categories, constant p and independence: (i) roll a fair die 12 times and count sixes; (ii) draw 6 cards without replacement and count hearts; (iii) inspect 20 independently produced items, each defective with probability 0.02. State n and p for each valid case.','Для каждого сценария решите, корректна ли биномиальная модель, и обоснуйте по условиям: фиксированное n, две категории исхода, постоянная p и независимость: (i) 12 раз бросить честный кубик и считать шестёрки; (ii) выбрать 6 карт без возвращения и считать червы; (iii) проверить 20 независимо произведённых изделий, каждое дефектно с вероятностью 0,02. Для корректных случаев укажите n и p.','Har bir holat uchun binomial model to‘g‘rimi, aniqlang va qat’iy n, ikki natija toifasi, doimiy p va mustaqillik shartlari bilan asoslang: (i) adolatli kubikni 12 marta tashlab oltilarni sanash; (ii) qaytarmasdan 6 karta olib yuraklarni sanash; (iii) mustaqil ishlab chiqarilgan 20 buyumni tekshirish, har biri p=0.02 bilan nuqsonli. To‘g‘ri holatlar uchun n va p ni yozing.','{"max_marks":12,"criteria":[{"id":"criteria","marks":4,"rule":"States and applies all four binomial conditions."},{"id":"die","marks":2,"rule":"Accepts (i) with n=12,p=1/6."},{"id":"cards","marks":3,"rule":"Rejects (ii) because without replacement breaks independence/constant p."},{"id":"items","marks":2,"rule":"Accepts (iii) with n=20,p=0.02 under stated independence."},{"id":"communication","marks":1,"rule":"Separates assumptions from parameter identification clearly."}]}','For every scenario, run the same four-condition checklist before writing B(n,p).','Для каждого сценария сначала примените один и тот же список из четырёх условий, затем записывайте B(n,p).','Har bir holatda B(n,p) yozishdan oldin bir xil to‘rtta shartni tekshiring.','approved','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_bin01_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_bin01_diagnostic','diagnostic','BIN-01 diagnostic','Диагностика BIN-01','BIN-01 diagnostikasi'),('p5_bin01_learning','learning','BIN-01 learning','BIN-01 обучение','BIN-01 o‘rganish'),('p5_bin01_retest','retest','BIN-01 delayed retest','BIN-01 отложенный ретест','BIN-01 kechiktirilgan retest'),('p5_bin01_mixed','mixed','BIN-01 mixed transfer','BIN-01 смешанный перенос','BIN-01 mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_bin01_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_bin01_diagnostic',1,'P5BIN01-D01',null,'diagnostic',true),('p5_bin01_learning',1,'P5BIN01-L01',null,'learning',false),('p5_bin01_learning',2,'P5BIN01-L02',null,'learning',false),('p5_bin01_learning',3,'P5BIN01-L03',null,'learning',false),('p5_bin01_learning',4,null,'P5BIN01-W01','written',false),('p5_bin01_retest',1,'P5BIN01-R01',null,'retest',true),('p5_bin01_mixed',1,'P5BIN01-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-BIN-01',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_bin01_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw13_16_bin01_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_bin01_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw13_16_bin01_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw13_16_bin01_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw13_16_bin01_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-BIN-01') then raise exception 'BIN-01 not ready after publish'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw13_16_bin01_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
