-- iClub APP — P0-02 safe legacy assessment contract v2
-- Branch-only design migration. DO NOT apply to production until P0-02 gate approval.
--
-- Goals:
--   1) keep pre-answer question payloads free of correct_answer/explanations;
--   2) move Practice/Tour correctness to SECURITY DEFINER server RPCs;
--   3) preserve legacy completed Practice/Tour rows and one-attempt Tour semantics;
--   4) keep current questions_public_read and legacy policies untouched until regression passes;
--   5) make all new session/runtime tables private to direct anon/auth access.
--
-- This migration is additive. It contains no UPDATE/DELETE/TRUNCATE of historical rows,
-- no rewrite of question IDs, no RLS cutover, and no feature enable.

begin;

-- =========================================================
-- 1. Private runtime/session tables
-- =========================================================

create table if not exists public.practice_sessions_v2 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  subject_id bigint not null references public.subjects(id),
  pool_id bigint not null references public.practice_pools(id),
  client_session_id text not null,
  question_ids bigint[] not null,
  legacy_attempt_id bigint unique references public.practice_attempts(id),
  status text not null default 'in_progress'
    check (status in ('in_progress','finalized','abandoned')),
  created_at timestamptz not null default now(),
  finalized_at timestamptz,
  unique (user_id, client_session_id),
  check (cardinality(question_ids) between 1 and 200),
  check (length(client_session_id) between 8 and 128)
);

create table if not exists public.practice_session_answers_v2 (
  session_id bigint not null references public.practice_sessions_v2(id) on delete cascade,
  question_id bigint not null references public.questions(id),
  selected_answer text,
  picked_index integer,
  is_correct boolean not null,
  time_spent integer not null default 0 check (time_spent >= 0),
  diagnostic_id bigint references public.question_answer_diagnostics(id),
  mistake_type text,
  weak_skill text,
  feedback_ru text,
  feedback_uz text,
  feedback_en text,
  next_action_ru text,
  next_action_uz text,
  next_action_en text,
  answered_at timestamptz not null default now(),
  primary key (session_id, question_id)
);

create table if not exists public.tour_session_runtime_v2 (
  attempt_id bigint primary key references public.tour_attempts(id) on delete cascade,
  user_id uuid not null,
  tour_id bigint not null references public.tours(id),
  client_session_id text not null,
  question_ids bigint[] not null,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, client_session_id),
  unique (user_id, tour_id),
  check (cardinality(question_ids) between 1 and 100),
  check (length(client_session_id) between 8 and 128)
);

create table if not exists public.tour_session_answers_v2 (
  attempt_id bigint not null references public.tour_session_runtime_v2(attempt_id) on delete cascade,
  question_id bigint not null references public.questions(id),
  user_answer text,
  answered boolean not null default true,
  is_correct boolean not null default false,
  time_spent integer not null default 0 check (time_spent >= 0),
  finish_reason text,
  answered_at timestamptz not null default now(),
  primary key (attempt_id, question_id)
);

alter table public.practice_sessions_v2 enable row level security;
alter table public.practice_session_answers_v2 enable row level security;
alter table public.tour_session_runtime_v2 enable row level security;
alter table public.tour_session_answers_v2 enable row level security;

-- Runtime tables are intentionally inaccessible directly from browser roles.
revoke all on table public.practice_sessions_v2 from public, anon, authenticated;
revoke all on table public.practice_session_answers_v2 from public, anon, authenticated;
revoke all on table public.tour_session_runtime_v2 from public, anon, authenticated;
revoke all on table public.tour_session_answers_v2 from public, anon, authenticated;
revoke all on sequence public.practice_sessions_v2_id_seq from public, anon, authenticated;

-- =========================================================
-- 2. Shared internal evaluator helpers
-- =========================================================

create or replace function public.iclub_tour_input_is_correct_v2(
  p_user_answer text,
  p_expected_answer text
)
returns boolean
language plpgsql
immutable
set search_path = public, pg_temp
as $$
declare
  v_user text := trim(translate(coalesce(p_user_answer,''), '−–—', '---'));
  v_expected text := trim(translate(coalesce(p_expected_answer,''), '−–—', '---'));
  v_user_num double precision;
  v_expected_num double precision;
  v_diff double precision;
  v_scale double precision;
  v_expected_signed boolean;
begin
  if v_user = '' or v_expected = '' then
    return false;
  end if;

  -- Mirrors current Tour client strict numeric format:
  -- dot decimal, optional explicit sign, optional e/E notation, no internal spaces/units.
  if v_expected ~ '^[+-]?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$' then
    if v_user !~ '^[+-]?[0-9]+([.][0-9]+)?([eE][+-]?[0-9]+)?$' then
      return false;
    end if;

    v_expected_signed := v_expected ~ '^[+-]';
    if v_expected_signed then
      if left(v_expected,1) <> left(v_user,1) then
        return false;
      end if;
    elsif v_user ~ '^[+-]' then
      return false;
    end if;

    begin
      v_user_num := v_user::double precision;
      v_expected_num := v_expected::double precision;
    exception when others then
      return false;
    end;

    v_diff := abs(v_user_num - v_expected_num);
    v_scale := greatest(1::double precision, abs(v_user_num), abs(v_expected_num));
    return v_diff <= v_scale * 1e-9;
  end if;

  -- Formula/token mode used by current client: ASCII alphanumeric only,
  -- case-insensitive, no spaces/subscript glyphs.
  if v_expected ~ '^[A-Z][A-Za-z0-9]*$' then
    if v_user !~ '^[A-Za-z][A-Za-z0-9]*$' then
      return false;
    end if;
    return lower(v_user) = lower(v_expected);
  end if;

  -- Current free-text fallback removes whitespace and compares case-insensitively.
  return lower(regexp_replace(v_user, '\s+', '', 'g'))
       = lower(regexp_replace(v_expected, '\s+', '', 'g'));
end;
$$;

create or replace function public.iclub_practice_eval_v2(
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_q public.questions%rowtype;
  v_diag public.question_answer_diagnostics%rowtype;
  v_selected text;
  v_selected_norm text;
  v_is_correct boolean := false;
begin
  select q.* into v_q
  from public.questions q
  where q.id = p_question_id
    and q.is_active is true;

  if v_q.id is null then
    raise exception 'question_not_found_or_inactive' using errcode = 'P0002';
  end if;

  if lower(coalesce(v_q.qtype,'')) = 'mcq' then
    if p_picked_index is not null and p_picked_index between 0 and 25 then
      v_selected := chr(65 + p_picked_index);
    elsif trim(coalesce(p_user_answer,'')) ~ '^[0-9]+$'
      and trim(p_user_answer)::integer between 0 and 25 then
      v_selected := chr(65 + trim(p_user_answer)::integer);
    else
      v_selected := upper(trim(coalesce(p_user_answer,'')));
    end if;

    v_is_correct := (
      upper(trim(coalesce(v_selected,''))) = upper(trim(coalesce(v_q.correct_answer,'')))
      or public.iclub_normalize_answer(v_selected) = public.iclub_normalize_answer(v_q.correct_answer)
    );

    select d.* into v_diag
    from public.question_answer_diagnostics d
    where d.question_id = p_question_id
      and d.answer_kind = 'mcq_option'
      and upper(trim(coalesce(d.answer_key,d.answer_value,''))) = upper(trim(coalesce(v_selected,'')))
      and d.quality_status = 'published'
    order by d.is_correct desc, d.id
    limit 1;
  else
    v_selected := trim(coalesce(p_user_answer,''));
    v_selected_norm := public.iclub_normalize_answer(v_selected);

    v_is_correct := exists (
      select 1
      from regexp_split_to_table(coalesce(v_q.correct_answer,''), '\|') as accepted_answer
      where public.iclub_normalize_answer(accepted_answer) = v_selected_norm
    );

    if not v_is_correct
       and public.iclub_is_numeric(v_selected)
       and public.iclub_is_numeric(v_q.correct_answer) then
      v_is_correct := replace(v_selected,',','.')::numeric = replace(v_q.correct_answer,',','.')::numeric;
    end if;

    select d.* into v_diag
    from public.question_answer_diagnostics d
    where d.question_id = p_question_id
      and d.answer_kind = 'input_exact'
      and d.quality_status = 'published'
      and (
        public.iclub_normalize_answer(coalesce(d.answer_value,d.answer_key,'')) = v_selected_norm
        or d.is_correct = v_is_correct
      )
    order by d.is_correct desc, d.id
    limit 1;

    if v_diag.id is null and public.iclub_is_numeric(v_selected) then
      select d.* into v_diag
      from public.question_answer_diagnostics d
      where d.question_id = p_question_id
        and d.answer_kind = 'input_tolerance'
        and d.quality_status = 'published'
        and coalesce(d.rule_json->>'target','') ~ '^-?[0-9]+([\.,][0-9]+)?$'
        and coalesce(d.rule_json->>'tolerance','') ~ '^[0-9]+([\.,][0-9]+)?$'
        and abs(replace(v_selected,',','.')::numeric - replace(d.rule_json->>'target',',','.')::numeric)
            <= replace(d.rule_json->>'tolerance',',','.')::numeric
      order by d.is_correct desc, d.id
      limit 1;
    end if;

    if v_diag.id is null then
      select d.* into v_diag
      from public.question_answer_diagnostics d
      where d.question_id = p_question_id
        and d.answer_kind = 'input_pattern'
        and d.quality_status = 'published'
        and d.answer_value is not null
        and v_selected ~* d.answer_value
      order by d.is_correct desc, d.id
      limit 1;
    end if;
  end if;

  if v_diag.id is null then
    select d.* into v_diag
    from public.question_answer_diagnostics d
    where d.question_id = p_question_id
      and d.answer_kind = 'fallback'
      and d.quality_status = 'published'
    order by d.is_correct desc, d.id
    limit 1;
  end if;

  return jsonb_build_object(
    'selected_answer', nullif(v_selected,''),
    'is_correct', v_is_correct,
    'diagnostic_id', v_diag.id,
    'mistake_type', v_diag.mistake_type,
    'weak_skill', v_diag.weak_skill,
    'feedback_ru', v_diag.feedback_ru,
    'feedback_uz', v_diag.feedback_uz,
    'feedback_en', v_diag.feedback_en,
    'next_action_ru', v_diag.next_action_ru,
    'next_action_uz', v_diag.next_action_uz,
    'next_action_en', v_diag.next_action_en
  );
end;
$$;

create or replace function public.iclub_tour_eval_v2(
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer,
  p_answered boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_q public.questions%rowtype;
  v_selected text;
  v_is_correct boolean := false;
begin
  select q.* into v_q
  from public.questions q
  where q.id = p_question_id
    and q.is_active is true;

  if v_q.id is null then
    raise exception 'question_not_found_or_inactive' using errcode = 'P0002';
  end if;

  if coalesce(p_answered,true) is false then
    return jsonb_build_object('selected_answer', null, 'is_correct', false);
  end if;

  if lower(coalesce(v_q.qtype,'')) = 'mcq' then
    if p_picked_index is not null and p_picked_index between 0 and 25 then
      v_selected := chr(65 + p_picked_index);
    elsif upper(trim(coalesce(p_user_answer,''))) ~ '^[A-Z]$' then
      v_selected := upper(trim(p_user_answer));
    elsif trim(coalesce(p_user_answer,'')) ~ '^[0-9]+$'
      and trim(p_user_answer)::integer between 0 and 25 then
      v_selected := chr(65 + trim(p_user_answer)::integer);
    else
      v_selected := upper(trim(coalesce(p_user_answer,'')));
    end if;

    v_is_correct := upper(trim(coalesce(v_selected,''))) = upper(trim(coalesce(v_q.correct_answer,'')));
  else
    v_selected := trim(coalesce(p_user_answer,''));
    v_is_correct := public.iclub_tour_input_is_correct_v2(v_selected, v_q.correct_answer);
  end if;

  return jsonb_build_object('selected_answer', nullif(v_selected,''), 'is_correct', v_is_correct);
end;
$$;

-- Internal helpers must never be callable from browser roles.
revoke all on function public.iclub_tour_input_is_correct_v2(text,text) from public, anon, authenticated;
revoke all on function public.iclub_practice_eval_v2(bigint,text,integer) from public, anon, authenticated;
revoke all on function public.iclub_tour_eval_v2(bigint,text,integer,boolean) from public, anon, authenticated;

-- =========================================================
-- 3. Practice v2 safe contract
-- =========================================================

create or replace function public.start_practice_session_safe_v2(
  p_pool_id bigint,
  p_client_session_id text,
  p_question_ids bigint[] default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_pool public.practice_pools%rowtype;
  v_session public.practice_sessions_v2%rowtype;
  v_qids bigint[];
  v_total integer;
  v_allowed integer;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if p_pool_id is null or p_pool_id <= 0 then
    raise exception 'invalid_pool_id' using errcode = '22023';
  end if;
  if p_client_session_id is null or length(trim(p_client_session_id)) not between 8 and 128 then
    raise exception 'invalid_client_session_id' using errcode = '22023';
  end if;

  select * into v_session
  from public.practice_sessions_v2 s
  where s.user_id = v_uid and s.client_session_id = trim(p_client_session_id)
  limit 1;

  if v_session.id is not null then
    return jsonb_build_object(
      'session_id', v_session.id,
      'status', v_session.status,
      'question_count', cardinality(v_session.question_ids),
      'legacy_attempt_id', v_session.legacy_attempt_id,
      'resumed', true
    );
  end if;

  select * into v_pool
  from public.practice_pools p
  where p.id = p_pool_id and p.is_active is true;

  if v_pool.id is null then
    raise exception 'pool_not_found_or_inactive' using errcode = 'P0002';
  end if;

  if p_question_ids is null or cardinality(p_question_ids) = 0 then
    select array_agg(ppq.question_id order by ppq.order_no, ppq.id)
      into v_qids
    from public.practice_pool_questions ppq
    join public.questions q on q.id = ppq.question_id and q.is_active is true
    where ppq.pool_id = p_pool_id and ppq.is_active is true;
  else
    select array_agg(x.qid order by x.ord)
      into v_qids
    from unnest(p_question_ids) with ordinality as x(qid,ord)
    where x.qid is not null;
  end if;

  v_total := coalesce(cardinality(v_qids),0);
  if v_total < 1 or v_total > 200 then
    raise exception 'invalid_question_count' using errcode = '22023';
  end if;

  if (select count(distinct x) from unnest(v_qids) x) <> v_total then
    raise exception 'duplicate_question_ids' using errcode = '22023';
  end if;

  select count(*)::integer into v_allowed
  from public.practice_pool_questions ppq
  join public.questions q on q.id = ppq.question_id
  where ppq.pool_id = p_pool_id
    and ppq.is_active is true
    and q.is_active is true
    and q.subject_id = v_pool.subject_id
    and ppq.question_id = any(v_qids);

  if v_allowed <> v_total then
    raise exception 'question_not_in_active_pool' using errcode = '22023';
  end if;

  insert into public.practice_sessions_v2(
    user_id, subject_id, pool_id, client_session_id, question_ids
  ) values (
    v_uid, v_pool.subject_id, p_pool_id, trim(p_client_session_id), v_qids
  ) returning * into v_session;

  return jsonb_build_object(
    'session_id', v_session.id,
    'status', v_session.status,
    'question_count', v_total,
    'legacy_attempt_id', null,
    'resumed', false
  );
exception
  when unique_violation then
    select * into v_session
    from public.practice_sessions_v2 s
    where s.user_id = v_uid and s.client_session_id = trim(p_client_session_id)
    limit 1;
    if v_session.id is null then raise; end if;
    return jsonb_build_object(
      'session_id', v_session.id,
      'status', v_session.status,
      'question_count', cardinality(v_session.question_ids),
      'legacy_attempt_id', v_session.legacy_attempt_id,
      'resumed', true
    );
end;
$$;

create or replace function public.get_practice_session_questions_safe_v2(p_session_id bigint)
returns table (
  order_no integer,
  id bigint,
  subject_id bigint,
  time_limit_sec integer,
  question_text text,
  question_text_ru text,
  question_text_uz text,
  question_text_en text,
  options_text text,
  options_text_ru text,
  options_text_uz text,
  options_text_en text,
  image_url text,
  topic text,
  subtopic text,
  difficulty text,
  qtype text,
  book_ref text,
  book_id bigint,
  book_reference text
)
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select
    x.ord::integer,
    q.id,
    q.subject_id,
    q.time_limit_sec,
    q.question_text,
    q.question_text_ru,
    q.question_text_uz,
    q.question_text_en,
    q.options_text,
    q.options_text_ru,
    q.options_text_uz,
    q.options_text_en,
    q.image_url,
    q.topic,
    q.subtopic,
    q.difficulty,
    q.qtype,
    q.book_ref,
    q.book_id,
    q.book_reference
  from public.practice_sessions_v2 s
  cross join lateral unnest(s.question_ids) with ordinality as x(qid,ord)
  join public.questions q on q.id = x.qid and q.is_active is true
  where s.id = p_session_id
    and s.user_id = auth.uid()
  order by x.ord;
$$;

create or replace function public.submit_practice_session_answer_safe_v2(
  p_session_id bigint,
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer,
  p_time_spent integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_s public.practice_sessions_v2%rowtype;
  v_q public.questions%rowtype;
  v_eval jsonb;
  v_answered integer;
  v_score integer;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  select * into v_s from public.practice_sessions_v2 s
  where s.id = p_session_id and s.user_id = v_uid;

  if v_s.id is null then
    raise exception 'session_not_found' using errcode = 'P0002';
  end if;
  if v_s.status <> 'in_progress' then
    raise exception 'session_not_in_progress' using errcode = '55000';
  end if;
  if not (p_question_id = any(v_s.question_ids)) then
    raise exception 'question_not_in_session' using errcode = '22023';
  end if;

  select q.* into v_q from public.questions q
  where q.id = p_question_id and q.is_active is true and q.subject_id = v_s.subject_id;
  if v_q.id is null then
    raise exception 'question_not_found_or_subject_mismatch' using errcode = 'P0002';
  end if;

  v_eval := public.iclub_practice_eval_v2(p_question_id,p_user_answer,p_picked_index);

  insert into public.practice_session_answers_v2(
    session_id, question_id, selected_answer, picked_index, is_correct, time_spent,
    diagnostic_id, mistake_type, weak_skill, feedback_ru, feedback_uz, feedback_en,
    next_action_ru, next_action_uz, next_action_en, answered_at
  ) values (
    p_session_id, p_question_id,
    v_eval->>'selected_answer', p_picked_index, coalesce((v_eval->>'is_correct')::boolean,false),
    greatest(coalesce(p_time_spent,0),0),
    nullif(v_eval->>'diagnostic_id','')::bigint,
    v_eval->>'mistake_type', v_eval->>'weak_skill',
    v_eval->>'feedback_ru', v_eval->>'feedback_uz', v_eval->>'feedback_en',
    v_eval->>'next_action_ru', v_eval->>'next_action_uz', v_eval->>'next_action_en', now()
  )
  on conflict (session_id,question_id) do update set
    selected_answer = excluded.selected_answer,
    picked_index = excluded.picked_index,
    is_correct = excluded.is_correct,
    time_spent = excluded.time_spent,
    diagnostic_id = excluded.diagnostic_id,
    mistake_type = excluded.mistake_type,
    weak_skill = excluded.weak_skill,
    feedback_ru = excluded.feedback_ru,
    feedback_uz = excluded.feedback_uz,
    feedback_en = excluded.feedback_en,
    next_action_ru = excluded.next_action_ru,
    next_action_uz = excluded.next_action_uz,
    next_action_en = excluded.next_action_en,
    answered_at = now();

  select count(*)::integer,
         count(*) filter (where a.is_correct is true)::integer
    into v_answered, v_score
  from public.practice_session_answers_v2 a
  where a.session_id = p_session_id;

  -- Practice is a learning flow: reveal only THIS answered question after server acceptance.
  -- No future question answer key is returned.
  return jsonb_build_object(
    'ok', true,
    'session_id', p_session_id,
    'question_id', p_question_id,
    'is_correct', coalesce((v_eval->>'is_correct')::boolean,false),
    'answered', v_answered,
    'score_so_far', v_score,
    'question_count', cardinality(v_s.question_ids),
    'correct_answer', v_q.correct_answer,
    'explanation', v_q.explanation,
    'explanation_ru', v_q.explanation_ru,
    'explanation_uz', v_q.explanation_uz,
    'explanation_en', v_q.explanation_en,
    'diagnostic_id', nullif(v_eval->>'diagnostic_id','')::bigint,
    'mistake_type', v_eval->>'mistake_type',
    'weak_skill', v_eval->>'weak_skill',
    'feedback_ru', v_eval->>'feedback_ru',
    'feedback_uz', v_eval->>'feedback_uz',
    'feedback_en', v_eval->>'feedback_en',
    'next_action_ru', v_eval->>'next_action_ru',
    'next_action_uz', v_eval->>'next_action_uz',
    'next_action_en', v_eval->>'next_action_en'
  );
end;
$$;

create or replace function public.finalize_practice_session_safe_v2(
  p_session_id bigint,
  p_total_time integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_s public.practice_sessions_v2%rowtype;
  v_answered integer;
  v_score integer;
  v_percent numeric;
  v_attempt_id bigint;
  v_row public.practice_session_answers_v2%rowtype;
  v_practice_answer_id bigint;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  select * into v_s from public.practice_sessions_v2 s
  where s.id = p_session_id and s.user_id = v_uid
  for update;

  if v_s.id is null then
    raise exception 'session_not_found' using errcode = 'P0002';
  end if;

  if v_s.status = 'finalized' and v_s.legacy_attempt_id is not null then
    select pa.score, pa.percent into v_score, v_percent
    from public.practice_attempts pa where pa.id = v_s.legacy_attempt_id;
    return jsonb_build_object(
      'ok', true, 'session_id', v_s.id, 'attempt_id', v_s.legacy_attempt_id,
      'score', coalesce(v_score,0), 'percent', coalesce(v_percent,0),
      'question_count', cardinality(v_s.question_ids), 'idempotent', true
    );
  end if;

  if v_s.status <> 'in_progress' then
    raise exception 'session_not_in_progress' using errcode = '55000';
  end if;

  select count(*)::integer,
         count(*) filter (where a.is_correct is true)::integer
    into v_answered, v_score
  from public.practice_session_answers_v2 a
  where a.session_id = p_session_id
    and a.question_id = any(v_s.question_ids);

  if v_answered <> cardinality(v_s.question_ids) then
    raise exception 'session_answers_incomplete' using errcode = '55000';
  end if;

  v_percent := case when v_answered > 0
    then round((v_score::numeric / v_answered::numeric) * 100, 2)
    else 0 end;

  insert into public.practice_attempts(user_id,subject_id,score,percent,time_seconds)
  values (v_uid,v_s.subject_id,v_score,v_percent,greatest(coalesce(p_total_time,0),0))
  returning id into v_attempt_id;

  for v_row in
    select a.* from public.practice_session_answers_v2 a
    cross join lateral (
      select min(x.ord) as ord
      from unnest(v_s.question_ids) with ordinality x(qid,ord)
      where x.qid = a.question_id
    ) o
    where a.session_id = p_session_id
    order by o.ord
  loop
    insert into public.practice_answers(attempt_id,question_id,user_answer,is_correct,time_spent)
    values (v_attempt_id,v_row.question_id,v_row.selected_answer,v_row.is_correct,v_row.time_spent)
    returning id into v_practice_answer_id;

    insert into public.user_answer_diagnosis(
      user_id,subject_id,attempt_type,attempt_id,practice_answer_id,question_id,
      selected_answer,is_correct,diagnostic_id,mistake_type,weak_skill,
      feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en
    ) values (
      v_uid,v_s.subject_id,'practice',v_attempt_id,v_practice_answer_id,v_row.question_id,
      v_row.selected_answer,v_row.is_correct,v_row.diagnostic_id,v_row.mistake_type,v_row.weak_skill,
      v_row.feedback_ru,v_row.feedback_uz,v_row.feedback_en,
      v_row.next_action_ru,v_row.next_action_uz,v_row.next_action_en
    )
    on conflict (practice_answer_id) where practice_answer_id is not null
    do update set
      selected_answer=excluded.selected_answer,
      is_correct=excluded.is_correct,
      diagnostic_id=excluded.diagnostic_id,
      mistake_type=excluded.mistake_type,
      weak_skill=excluded.weak_skill,
      feedback_ru=excluded.feedback_ru,
      feedback_uz=excluded.feedback_uz,
      feedback_en=excluded.feedback_en,
      next_action_ru=excluded.next_action_ru,
      next_action_uz=excluded.next_action_uz,
      next_action_en=excluded.next_action_en;
  end loop;

  update public.practice_sessions_v2
  set status='finalized', legacy_attempt_id=v_attempt_id, finalized_at=now()
  where id=p_session_id and user_id=v_uid;

  return jsonb_build_object(
    'ok', true, 'session_id', p_session_id, 'attempt_id', v_attempt_id,
    'score', v_score, 'percent', v_percent,
    'question_count', v_answered, 'idempotent', false
  );
end;
$$;

-- =========================================================
-- 4. Tour v2 safe contract
-- =========================================================

create or replace function public.start_tour_attempt_safe_v2(
  p_tour_id bigint,
  p_client_session_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_tour public.tours%rowtype;
  v_existing_attempt public.tour_attempts%rowtype;
  v_rt public.tour_session_runtime_v2%rowtype;
  v_qids bigint[];
  v_attempt_id bigint;
  v_today date := (now() at time zone 'Asia/Tashkent')::date;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if p_tour_id is null or p_tour_id <= 0 then
    raise exception 'invalid_tour_id' using errcode = '22023';
  end if;
  if p_client_session_id is null or length(trim(p_client_session_id)) not between 8 and 128 then
    raise exception 'invalid_client_session_id' using errcode = '22023';
  end if;

  select * into v_rt from public.tour_session_runtime_v2 r
  where r.user_id=v_uid and r.client_session_id=trim(p_client_session_id)
  limit 1;
  if v_rt.attempt_id is not null then
    return jsonb_build_object(
      'attempt_id',v_rt.attempt_id,
      'question_count',cardinality(v_rt.question_ids),
      'finalized',v_rt.finalized_at is not null,
      'resumed',true
    );
  end if;

  select * into v_tour from public.tours t
  where t.id=p_tour_id and t.is_active is true;
  if v_tour.id is null then
    raise exception 'tour_not_found_or_inactive' using errcode='P0002';
  end if;
  if v_tour.start_date is null or v_tour.end_date is null
     or v_today < v_tour.start_date or v_today > v_tour.end_date then
    raise exception 'tour_not_open' using errcode='55000';
  end if;

  -- Preserve the historical UNIQUE(user_id,tour_id) one-attempt law.
  select * into v_existing_attempt from public.tour_attempts a
  where a.user_id=v_uid and a.tour_id=p_tour_id
  limit 1;
  if v_existing_attempt.id is not null then
    select * into v_rt from public.tour_session_runtime_v2 r
    where r.attempt_id=v_existing_attempt.id and r.user_id=v_uid;
    if v_rt.attempt_id is not null and v_rt.finalized_at is null then
      return jsonb_build_object(
        'attempt_id',v_rt.attempt_id,
        'question_count',cardinality(v_rt.question_ids),
        'finalized',false,
        'resumed',true
      );
    end if;
    raise exception 'already_attempted' using errcode='23505';
  end if;

  select array_agg(tq.question_id order by tq.order_no,tq.id)
    into v_qids
  from public.tour_questions tq
  join public.questions q on q.id=tq.question_id and q.is_active is true
  where tq.tour_id=p_tour_id and tq.is_active is true and q.subject_id=v_tour.subject_id;

  if coalesce(cardinality(v_qids),0) < 1 then
    raise exception 'tour_has_no_active_questions' using errcode='55000';
  end if;

  insert into public.tour_attempts(user_id,tour_id,score,percent,total_time,status)
  values (v_uid,p_tour_id,0,0,0,'submitted')
  returning id into v_attempt_id;

  insert into public.tour_session_runtime_v2(
    attempt_id,user_id,tour_id,client_session_id,question_ids
  ) values (
    v_attempt_id,v_uid,p_tour_id,trim(p_client_session_id),v_qids
  );

  return jsonb_build_object(
    'attempt_id',v_attempt_id,
    'question_count',cardinality(v_qids),
    'finalized',false,
    'resumed',false
  );
exception
  when unique_violation then
    select * into v_existing_attempt from public.tour_attempts a
    where a.user_id=v_uid and a.tour_id=p_tour_id limit 1;
    if v_existing_attempt.id is null then raise; end if;
    select * into v_rt from public.tour_session_runtime_v2 r
    where r.attempt_id=v_existing_attempt.id and r.user_id=v_uid;
    if v_rt.attempt_id is null or v_rt.finalized_at is not null then
      raise exception 'already_attempted' using errcode='23505';
    end if;
    return jsonb_build_object(
      'attempt_id',v_rt.attempt_id,
      'question_count',cardinality(v_rt.question_ids),
      'finalized',false,
      'resumed',true
    );
end;
$$;

create or replace function public.get_tour_session_questions_safe_v2(p_attempt_id bigint)
returns table (
  order_no integer,
  id bigint,
  subject_id bigint,
  time_limit_sec integer,
  question_text text,
  question_text_ru text,
  question_text_uz text,
  question_text_en text,
  options_text text,
  options_text_ru text,
  options_text_uz text,
  options_text_en text,
  image_url text,
  topic text,
  subtopic text,
  difficulty text,
  qtype text,
  book_ref text,
  book_id bigint,
  book_reference text
)
language sql
security definer
set search_path = public, auth, pg_temp
as $$
  select
    x.ord::integer,
    q.id,
    q.subject_id,
    q.time_limit_sec,
    q.question_text,
    q.question_text_ru,
    q.question_text_uz,
    q.question_text_en,
    q.options_text,
    q.options_text_ru,
    q.options_text_uz,
    q.options_text_en,
    q.image_url,
    q.topic,
    q.subtopic,
    q.difficulty,
    q.qtype,
    q.book_ref,
    q.book_id,
    q.book_reference
  from public.tour_session_runtime_v2 r
  cross join lateral unnest(r.question_ids) with ordinality as x(qid,ord)
  join public.questions q on q.id=x.qid and q.is_active is true
  where r.attempt_id=p_attempt_id and r.user_id=auth.uid()
  order by x.ord;
$$;

create or replace function public.submit_tour_answer_safe_v2(
  p_attempt_id bigint,
  p_question_id bigint,
  p_user_answer text,
  p_picked_index integer,
  p_time_spent integer,
  p_answered boolean default true,
  p_finish_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_rt public.tour_session_runtime_v2%rowtype;
  v_eval jsonb;
  v_answered_count integer;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode='28000';
  end if;

  select * into v_rt from public.tour_session_runtime_v2 r
  where r.attempt_id=p_attempt_id and r.user_id=v_uid;
  if v_rt.attempt_id is null then
    raise exception 'tour_session_not_found' using errcode='P0002';
  end if;
  if v_rt.finalized_at is not null then
    raise exception 'tour_session_finalized' using errcode='55000';
  end if;
  if not (p_question_id = any(v_rt.question_ids)) then
    raise exception 'question_not_in_tour_session' using errcode='22023';
  end if;

  v_eval := public.iclub_tour_eval_v2(
    p_question_id,p_user_answer,p_picked_index,coalesce(p_answered,true)
  );

  insert into public.tour_session_answers_v2(
    attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason,answered_at
  ) values (
    p_attempt_id,p_question_id,
    v_eval->>'selected_answer',coalesce(p_answered,true),
    coalesce((v_eval->>'is_correct')::boolean,false),
    greatest(coalesce(p_time_spent,0),0),nullif(trim(coalesce(p_finish_reason,'')),''),now()
  )
  on conflict (attempt_id,question_id) do update set
    user_answer=excluded.user_answer,
    answered=excluded.answered,
    is_correct=excluded.is_correct,
    time_spent=excluded.time_spent,
    finish_reason=excluded.finish_reason,
    answered_at=now();

  select count(*)::integer into v_answered_count
  from public.tour_session_answers_v2 a
  where a.attempt_id=p_attempt_id;

  -- Protected Tour response deliberately omits is_correct, correct_answer and explanation.
  return jsonb_build_object(
    'ok',true,
    'attempt_id',p_attempt_id,
    'question_id',p_question_id,
    'recorded',true,
    'recorded_count',v_answered_count,
    'question_count',cardinality(v_rt.question_ids)
  );
end;
$$;

create or replace function public.finalize_tour_attempt_safe_v2(
  p_attempt_id bigint,
  p_total_time integer,
  p_status text default 'submitted'
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_rt public.tour_session_runtime_v2%rowtype;
  v_total integer;
  v_score integer;
  v_percent numeric;
  v_status text := lower(trim(coalesce(p_status,'submitted')));
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode='28000';
  end if;
  if v_status not in ('submitted','time_expired','anti_cheat','abandoned') then
    raise exception 'invalid_tour_status' using errcode='22023';
  end if;

  select * into v_rt from public.tour_session_runtime_v2 r
  where r.attempt_id=p_attempt_id and r.user_id=v_uid
  for update;
  if v_rt.attempt_id is null then
    raise exception 'tour_session_not_found' using errcode='P0002';
  end if;

  if v_rt.finalized_at is not null then
    select a.score,a.percent into v_score,v_percent
    from public.tour_attempts a where a.id=p_attempt_id and a.user_id=v_uid;
    return jsonb_build_object(
      'ok',true,'attempt_id',p_attempt_id,
      'score',coalesce(v_score,0),'percent',coalesce(v_percent,0),
      'question_count',cardinality(v_rt.question_ids),'status',v_status,'idempotent',true
    );
  end if;

  v_total := cardinality(v_rt.question_ids);

  -- Persist an explicit unanswered row for every omitted question at finalization.
  insert into public.tour_session_answers_v2(
    attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason
  )
  select p_attempt_id,x.qid,null,false,false,0,v_status
  from unnest(v_rt.question_ids) x(qid)
  where not exists (
    select 1 from public.tour_session_answers_v2 a
    where a.attempt_id=p_attempt_id and a.question_id=x.qid
  )
  on conflict do nothing;

  select count(*) filter (where a.is_correct is true)::integer
    into v_score
  from public.tour_session_answers_v2 a
  where a.attempt_id=p_attempt_id and a.question_id=any(v_rt.question_ids);

  v_percent := case when v_total > 0
    then round((v_score::numeric / v_total::numeric) * 100,2)
    else 0 end;

  insert into public.tour_answers(
    attempt_id,question_id,user_answer,answered,is_correct,time_spent,finish_reason
  )
  select a.attempt_id,a.question_id,a.user_answer,a.answered,a.is_correct,a.time_spent,a.finish_reason
  from public.tour_session_answers_v2 a
  where a.attempt_id=p_attempt_id and a.question_id=any(v_rt.question_ids)
  on conflict (attempt_id,question_id) do update set
    user_answer=excluded.user_answer,
    answered=excluded.answered,
    is_correct=excluded.is_correct,
    time_spent=excluded.time_spent,
    finish_reason=excluded.finish_reason;

  update public.tour_attempts a
  set score=v_score,
      percent=v_percent,
      total_time=greatest(coalesce(p_total_time,0),0),
      status=v_status
  where a.id=p_attempt_id and a.user_id=v_uid and a.tour_id=v_rt.tour_id;

  if not found then
    raise exception 'tour_attempt_update_failed' using errcode='P0002';
  end if;

  update public.tour_session_runtime_v2
  set finalized_at=now()
  where attempt_id=p_attempt_id and user_id=v_uid;

  return jsonb_build_object(
    'ok',true,'attempt_id',p_attempt_id,
    'score',v_score,'percent',v_percent,
    'question_count',v_total,'status',v_status,'idempotent',false
  );
end;
$$;

-- =========================================================
-- 5. Browser-role grants: RPC only, no runtime-table access
-- =========================================================

revoke all on function public.start_practice_session_safe_v2(bigint,text,bigint[]) from public, anon;
revoke all on function public.get_practice_session_questions_safe_v2(bigint) from public, anon;
revoke all on function public.submit_practice_session_answer_safe_v2(bigint,bigint,text,integer,integer) from public, anon;
revoke all on function public.finalize_practice_session_safe_v2(bigint,integer) from public, anon;
revoke all on function public.start_tour_attempt_safe_v2(bigint,text) from public, anon;
revoke all on function public.get_tour_session_questions_safe_v2(bigint) from public, anon;
revoke all on function public.submit_tour_answer_safe_v2(bigint,bigint,text,integer,integer,boolean,text) from public, anon;
revoke all on function public.finalize_tour_attempt_safe_v2(bigint,integer,text) from public, anon;

grant execute on function public.start_practice_session_safe_v2(bigint,text,bigint[]) to authenticated;
grant execute on function public.get_practice_session_questions_safe_v2(bigint) to authenticated;
grant execute on function public.submit_practice_session_answer_safe_v2(bigint,bigint,text,integer,integer) to authenticated;
grant execute on function public.finalize_practice_session_safe_v2(bigint,integer) to authenticated;
grant execute on function public.start_tour_attempt_safe_v2(bigint,text) to authenticated;
grant execute on function public.get_tour_session_questions_safe_v2(bigint) to authenticated;
grant execute on function public.submit_tour_answer_safe_v2(bigint,bigint,text,integer,integer,boolean,text) to authenticated;
grant execute on function public.finalize_tour_attempt_safe_v2(bigint,integer,text) to authenticated;

comment on table public.practice_sessions_v2 is
'P0-02 private Practice runtime sessions. Additive only; finalized sessions materialize legacy practice_attempts/practice_answers.';
comment on table public.tour_session_runtime_v2 is
'P0-02 private Tour runtime anchor. Preserves legacy one-attempt row while keeping live correctness private until finalization.';
comment on function public.get_practice_session_questions_safe_v2(bigint) is
'Pre-answer Practice delivery. Must never return correct_answer or explanation.';
comment on function public.get_tour_session_questions_safe_v2(bigint) is
'Protected Tour delivery. Must never return correct_answer, explanation, or live correctness.';

commit;
