-- P1-02 P1 AW13-16 Series + Differentiation foundations: SER-01, SER-02, DIF-01.
-- Original iClub-authored content; governed publication only; legacy question rows remain inactive.

begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw13_16_series_diff_v1','P1','P1 AW13-16 Series + Differentiation foundations','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no Cambridge/coursebook question, diagram, answer or mark-scheme wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1' and component_code='P1' and status='draft'), src(skill,k,role,diff,qen,qru,quz,opts,ans,een,eru,euz,secs) as (values
('P1-SER-01','P1SER01-D01','diagnostic','medium','Find the coefficient of x² in (1 + 2x)⁴.','Найдите коэффициент при x² в (1 + 2x)⁴.','(1 + 2x)⁴ da x² koeffitsiyentini toping.','["24","12","16","6"]','A','The x² term is C(4,2)(2x)² = 6×4x² = 24x².','Член с x²: C(4,2)(2x)² = 24x².','x² hadi: C(4,2)(2x)² = 24x².',65),
('P1-SER-01','P1SER01-L01','learning','easy','What is the coefficient of x² in (1+x)³?','Чему равен коэффициент при x² в (1+x)³?','(1+x)³ da x² koeffitsiyenti nechaga teng?','["3","1","6","9"]','A','(1+x)³=1+3x+3x²+x³, so the coefficient is 3.','(1+x)³=1+3x+3x²+x³, коэффициент равен 3.','(1+x)³=1+3x+3x²+x³, koeffitsiyent 3.',45),
('P1-SER-01','P1SER01-L02','learning','medium','Find the coefficient of x³ in (2+x)⁵.','Найдите коэффициент при x³ в (2+x)⁵.','(2+x)⁵ da x³ koeffitsiyentini toping.','["40","20","80","10"]','A','Choose three x factors: C(5,3)2² = 10×4 = 40.','Выбираем три множителя x: C(5,3)2² = 40.','Uchta x omil tanlanadi: C(5,3)2² = 40.',60),
('P1-SER-01','P1SER01-L03','learning','medium','What is the constant term in (3−2x)⁴?','Чему равен свободный член в (3−2x)⁴?','(3−2x)⁴ dagi doimiy had nechaga teng?','["81","16","−81","24"]','A','The constant term uses no x factors, so it is 3⁴=81.','Свободный член получается без x: 3⁴=81.','Doimiy had x siz olinadi: 3⁴=81.',50),
('P1-SER-01','P1SER01-R01','retest','easy','Find the coefficient of x in (1−3x)⁴.','Найдите коэффициент при x в (1−3x)⁴.','(1−3x)⁴ da x koeffitsiyentini toping.','["−12","12","−3","4"]','A','The x term is C(4,1)(−3x)=−12x.','Член с x: C(4,1)(−3x)=−12x.','x hadi: C(4,1)(−3x)=−12x.',45),
('P1-SER-01','P1SER01-R02','retest','medium','Find the coefficient of x² in (2+x)⁴.','Найдите коэффициент при x² в (2+x)⁴.','(2+x)⁴ da x² koeffitsiyentini toping.','["24","12","6","16"]','A','C(4,2)2² = 6×4 = 24.','C(4,2)2² = 24.','C(4,2)2² = 24.',50),
('P1-SER-01','P1SER01-M01','mixed','medium','Find the coefficient of x² in (1+x)³(1+2x).','Найдите коэффициент при x² в (1+x)³(1+2x).','(1+x)³(1+2x) da x² koeffitsiyentini toping.','["9","6","3","12"]','A','From (1+x)³, x² contributes 3×1 and x contributes 3×2x, giving 3+6=9.','Из (1+x)³ вклад x² равен 3×1, а вклад x равен 3×2, итого 9.','(1+x)³ dan x² hissasi 3×1, x hissasi 3×2, jami 9.',70),

('P1-SER-02','P1SER02-D01','diagnostic','medium','The sequence 5, 8, 11, 14, ... is:','Последовательность 5, 8, 11, 14, ... является:','5, 8, 11, 14, ... ketma-ketlik:','["arithmetic with common difference 3","geometric with ratio 3","arithmetic with difference 5","geometric with ratio 8/5"]','A','Consecutive differences are all 3, so the sequence is arithmetic with d=3.','Разности соседних членов равны 3, поэтому это арифметическая прогрессия с d=3.','Ketma-ket ayirmalar 3, demak arifmetik progressiya, d=3.',50),
('P1-SER-02','P1SER02-L01','learning','easy','The sequence 2, 6, 18, 54, ... is:','Последовательность 2, 6, 18, 54, ... является:','2, 6, 18, 54, ... ketma-ketlik:','["geometric with ratio 3","arithmetic with difference 4","geometric with ratio 2","arithmetic with difference 6"]','A','Each term is multiplied by 3, so it is geometric with r=3.','Каждый член умножается на 3, значит это геометрическая прогрессия с r=3.','Har bir had 3 ga ko‘payadi, demak geometrik progressiya, r=3.',45),
('P1-SER-02','P1SER02-L02','learning','medium','Classify 12, 9, 6, 3, ...','Классифицируйте 12, 9, 6, 3, ...','12, 9, 6, 3, ... ni tasniflang.','["arithmetic, d=−3","geometric, r=3/4","arithmetic, d=3","geometric, r=−3"]','A','Every consecutive difference is −3.','Каждая соседняя разность равна −3.','Har bir ketma-ket ayirma −3.',45),
('P1-SER-02','P1SER02-L03','learning','medium','Classify 81, 27, 9, 3, ...','Классифицируйте 81, 27, 9, 3, ...','81, 27, 9, 3, ... ni tasniflang.','["geometric, r=1/3","arithmetic, d=−54","geometric, r=3","arithmetic, d=−18"]','A','Each term is one third of the previous term, so r=1/3.','Каждый член равен одной трети предыдущего, поэтому r=1/3.','Har bir had oldingisining uchdan biri, demak r=1/3.',50),
('P1-SER-02','P1SER02-R01','retest','easy','The sequence 4, 7, 10, 13, ... is:','Последовательность 4, 7, 10, 13, ... является:','4, 7, 10, 13, ... ketma-ketlik:','["arithmetic, d=3","geometric, r=3","arithmetic, d=4","geometric, r=7/4"]','A','The constant difference is 3.','Постоянная разность равна 3.','Doimiy ayirma 3.',40),
('P1-SER-02','P1SER02-R02','retest','medium','The sequence 5, 10, 20, 40, ... is:','Последовательность 5, 10, 20, 40, ... является:','5, 10, 20, 40, ... ketma-ketlik:','["geometric, r=2","arithmetic, d=5","geometric, r=5","arithmetic, d=10"]','A','Each term is twice the previous one, so r=2.','Каждый член вдвое больше предыдущего, r=2.','Har bir had oldingisidan ikki baravar, r=2.',40),
('P1-SER-02','P1SER02-M01','mixed','medium','Which description fits 2, 4, 8, 16, ...?','Какое описание подходит для 2, 4, 8, 16, ...?','2, 4, 8, 16, ... uchun qaysi tavsif to‘g‘ri?','["geometric with ratio 2","arithmetic with difference 2","geometric with ratio 4","neither arithmetic nor geometric"]','A','The ratio of consecutive terms is constantly 2.','Отношение соседних членов постоянно и равно 2.','Ketma-ket hadlar nisbati doim 2.',45),

('P1-DIF-01','P1DIF01-D01','diagnostic','medium','For f(x)=x², evaluate lim(h→0) [(3+h)²−9]/h.','Для f(x)=x² вычислите lim(h→0) [(3+h)²−9]/h.','f(x)=x² uchun lim(h→0) [(3+h)²−9]/h ni hisoblang.','["6","3","9","0"]','A','Expand: ((3+h)²−9)/h=(6h+h²)/h=6+h, so the limit is 6.','Раскрываем: (6h+h²)/h=6+h, предел равен 6.','Ochamiz: (6h+h²)/h=6+h, limit 6.',70),
('P1-DIF-01','P1DIF01-L01','learning','easy','For f(x)=x², what is the gradient at x=2?','Для f(x)=x² чему равен градиент при x=2?','f(x)=x² uchun x=2 dagi gradient nechaga teng?','["4","2","1","8"]','A','Using the simple limit definition gives f′(x)=2x, hence f′(2)=4.','По определению через предел f′(x)=2x, поэтому f′(2)=4.','Limit ta’rifi orqali f′(x)=2x, demak f′(2)=4.',50),
('P1-DIF-01','P1DIF01-L02','learning','medium','The gradient of y=x² at x=−1 is:','Градиент y=x² при x=−1 равен:','y=x² ning x=−1 dagi gradienti:','["−2","2","−1","1"]','A','For y=x², the gradient is 2x, so at x=−1 it is −2.','Для y=x² градиент равен 2x, при x=−1 получаем −2.','y=x² uchun gradient 2x, x=−1 da −2.',45),
('P1-DIF-01','P1DIF01-L03','learning','medium','If ds/dt = 5 at t=2 seconds, what does this mean?','Если ds/dt = 5 при t=2 с, что это означает?','Agar t=2 sekundda ds/dt=5 bo‘lsa, bu nimani anglatadi?','["The instantaneous rate of change of s is 5 units per second","s equals 5 at all times","The average rate from 0 to 2 is necessarily 5","t changes at 5 seconds per unit"]','A','A derivative at a point is the instantaneous rate of change at that time.','Производная в точке — мгновенная скорость изменения в этот момент.','Nuqtadagi hosila shu vaqtdagi oniy o‘zgarish tezligi.',55),
('P1-DIF-01','P1DIF01-R01','retest','easy','Evaluate lim(h→0) [(2+h)²−4]/h.','Вычислите lim(h→0) [(2+h)²−4]/h.','lim(h→0) [(2+h)²−4]/h ni hisoblang.','["4","2","0","8"]','A','The quotient is (4h+h²)/h=4+h, so the limit is 4.','Дробь равна 4+h, поэтому предел 4.','Ifoda 4+h ga teng, limit 4.',55),
('P1-DIF-01','P1DIF01-R02','retest','medium','Evaluate lim(h→0) [(1+h)³−1]/h.','Вычислите lim(h→0) [(1+h)³−1]/h.','lim(h→0) [(1+h)³−1]/h ni hisoblang.','["3","1","0","6"]','A','(1+h)³−1=3h+3h²+h³. Divide by h and let h→0 to get 3.','(1+h)³−1=3h+3h²+h³. Делим на h и получаем предел 3.','(1+h)³−1=3h+3h²+h³. h ga bo‘lib, h→0 da 3.',65),
('P1-DIF-01','P1DIF01-M01','mixed','medium','For y=x²+1, find the tangent gradient at x=2 using the difference-quotient idea.','Для y=x²+1 найдите градиент касательной при x=2, используя идею разностного отношения.','y=x²+1 uchun x=2 dagi urinma gradientini ayirmali nisbat g‘oyasi bilan toping.','["4","5","2","1"]','A','The +1 cancels in the difference quotient; the x² part gives gradient 2x=4 at x=2.','+1 сокращается в разностном отношении; для x² градиент при x=2 равен 4.','+1 ayirmali nisbatda yo‘qoladi; x² qismi x=2 da 4 gradient beradi.',65)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,case when s.skill like 'P1-SER-%' then 'P1 Series' else 'P1 Differentiation' end,s.skill,s.diff,'mcq',s.qen,s.opts,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.opts,s.opts,s.opts,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw13_16_series_diff_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw13_16_series_diff_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1' and status='draft'), keys(skill,k,role) as (values
('P1-SER-01','P1SER01-D01','diagnostic'),('P1-SER-01','P1SER01-L01','learning'),('P1-SER-01','P1SER01-L02','learning'),('P1-SER-01','P1SER01-L03','learning'),('P1-SER-01','P1SER01-R01','retest'),('P1-SER-01','P1SER01-R02','retest'),('P1-SER-01','P1SER01-M01','mixed'),
('P1-SER-02','P1SER02-D01','diagnostic'),('P1-SER-02','P1SER02-L01','learning'),('P1-SER-02','P1SER02-L02','learning'),('P1-SER-02','P1SER02-L03','learning'),('P1-SER-02','P1SER02-R01','retest'),('P1-SER-02','P1SER02-R02','retest'),('P1-SER-02','P1SER02-M01','mixed'),
('P1-DIF-01','P1DIF01-D01','diagnostic'),('P1-DIF-01','P1DIF01-L01','learning'),('P1-DIF-01','P1DIF01-L02','learning'),('P1-DIF-01','P1DIF01-L03','learning'),('P1-DIF-01','P1DIF01-R01','retest'),('P1-DIF-01','P1DIF01-R02','retest'),('P1-DIF-01','P1DIF01-M01','mixed')
)
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source question, answer or mark-scheme wording copied.','Authored for p1_aw13_16_series_diff_v1 from canonical skill intent.','Cambridge 9709 2026-2027 v4; P1 Series / Differentiation','Complete Pure Mathematics 1; Series / Differentiation (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw13_16_series_diff_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with rules(ckey,match,dcode,mtype,skill,fen,fru,fuz,nen,nru,nuz) as (values
('P1SER01-D01','B','missed_power_factor','method','P1-SER-01','C(4,2)=6 is only the binomial coefficient; the factor (2x)² contributes another 4.','C(4,2)=6 — только биномиальный коэффициент; (2x)² даёт дополнительный множитель 4.','C(4,2)=6 faqat binomial koeffitsiyent; (2x)² yana 4 beradi.','Write the full term C(4,2)1²(2x)² before simplifying.','Запишите полный член C(4,2)1²(2x)².','Soddalashtirishdan oldin to‘liq C(4,2)1²(2x)² hadini yozing.'),
('P1SER01-D01','C','used_two_power_only','method','P1-SER-01','16 is 2⁴ and does not select the x² term.','16 — это 2⁴, но это не коэффициент члена x².','16 = 2⁴, lekin x² hadi koeffitsiyenti emas.','Match the chosen power of x to r=2 in the binomial term.','Сопоставьте степень x с r=2 в биномиальном члене.','Binomial haddagi x darajasini r=2 bilan moslang.'),
('P1SER01-D01','D','combination_only','concept','P1-SER-01','6 counts the choices of two x factors but ignores that each chosen x factor is 2x.','6 выбирает два множителя x, но игнорирует коэффициент 2 у каждого x.','6 ikkita x omilni tanlaydi, lekin har bir x oldidagi 2 ni hisobga olmaydi.','Include both C(n,r) and the powers of each binomial term.','Учитывайте и C(n,r), и степени обоих членов бинома.','C(n,r) ham, binom hadlarining darajalarini ham hisobga oling.'),
('P1SER02-D01','B','ratio_instead_difference','concept','P1-SER-02','The ratios 8/5, 11/8 and 14/11 are not constant, so the sequence is not geometric.','Отношения 8/5, 11/8 и 14/11 не постоянны, значит прогрессия не геометрическая.','8/5, 11/8, 14/11 nisbatlari doimiy emas, demak geometrik emas.','Check consecutive differences and ratios separately.','Проверьте отдельно соседние разности и отношения.','Ketma-ket ayirma va nisbatlarni alohida tekshiring.'),
('P1SER02-D01','C','wrong_difference','method','P1-SER-02','The common difference is 8−5=3, not 5.','Общая разность 8−5=3, а не 5.','Umumiy ayirma 8−5=3, 5 emas.','Subtract consecutive terms in the same order.','Вычитайте соседние члены в одном порядке.','Ketma-ket hadlarni bir xil tartibda ayiring.'),
('P1SER02-D01','D','first_ratio_only','concept','P1-SER-02','A single ratio 8/5 is not enough; a geometric sequence needs the same ratio for every adjacent pair.','Одного отношения 8/5 недостаточно; в геометрической прогрессии отношение должно быть постоянным.','Faqat 8/5 yetarli emas; geometrik progressiyada barcha qo‘shni nisbatlar bir xil bo‘lishi kerak.','Verify at least the next ratio before classifying as geometric.','Проверьте хотя бы следующее отношение.','Geometrik deb aytishdan oldin keyingi nisbatni ham tekshiring.'),
('P1DIF01-D01','B','used_x_value_as_gradient','concept','P1-DIF-01','3 is the x-coordinate, not the derivative value. The difference quotient must be simplified before h→0.','3 — это координата x, а не значение производной. Сначала упростите разностное отношение.','3 x-koordinata, hosila qiymati emas. h→0 dan oldin ayirmali nisbatni soddalashtiring.','Expand (3+h)² and cancel h.','Раскройте (3+h)² и сократите h.','(3+h)² ni oching va h ni qisqartiring.'),
('P1DIF01-D01','C','used_function_value','concept','P1-DIF-01','9 is f(3), the curve value, not the tangent gradient.','9 — это f(3), значение функции, а не градиент касательной.','9 = f(3), funksiya qiymati, urinma gradienti emas.','Distinguish function value from rate of change.','Различайте значение функции и скорость изменения.','Funksiya qiymati bilan o‘zgarish tezligini ajrating.'),
('P1DIF01-D01','D','substituted_h_too_early','method','P1-DIF-01','Substituting h=0 before cancelling creates 0/0 and loses the limiting gradient.','Подстановка h=0 до сокращения даёт 0/0 и теряет предельный градиент.','h ni qisqartirishdan oldin 0 qo‘yish 0/0 beradi va gradient yo‘qoladi.','Algebraically simplify for h≠0 first, then take the limit.','Сначала упростите при h≠0, затем переходите к пределу.','Avval h≠0 da soddalashtiring, keyin limit oling.')
), meta as (select m.id,m.content_key from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw13_16_series_diff_v1' and m.reserve_role='diagnostic')
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,r.skill,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from rules r join meta on meta.content_key=r.ckey on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1SER01-W01','P1-SER-01','For (2−x)⁵: (a) write the first four terms in ascending powers of x; (b) find the coefficient of x³; (c) explain how the binomial coefficient and the powers of 2 and −x combine in that term.','Для (2−x)⁵: (a) запишите первые четыре члена по возрастанию степеней x; (b) найдите коэффициент при x³; (c) объясните, как в этом члене сочетаются биномиальный коэффициент и степени 2 и −x.','(2−x)⁵ uchun: (a) x darajalari o‘sish tartibida dastlabki to‘rt hadni yozing; (b) x³ koeffitsiyentini toping; (c) bu hadda binomial koeffitsiyent hamda 2 va −x darajalari qanday birlashishini tushuntiring.','{"max_marks":10,"criteria":[{"id":"expansion","marks":4,"rule":"Obtains 32−80x+80x²−40x³ for the first four terms."},{"id":"coefficient","marks":2,"rule":"States x³ coefficient −40."},{"id":"method","marks":3,"rule":"Uses C(5,3)2²(−x)³ for the x³ term."},{"id":"communication","marks":1,"rule":"Keeps signs and powers explicit."}]}','Write the general binomial term before substituting r. Track the negative sign as part of (−x)^r.','Сначала запишите общий биномиальный член. Следите за знаком как частью (−x)^r.','Avval umumiy binomial hadni yozing. Manfiy ishorani (−x)^r ning bir qismi sifatida kuzating.'),
('P1SER02-W01','P1-SER-02','For each sequence, decide whether it is arithmetic, geometric or neither, and justify using constant differences or ratios: A: 7,11,15,19; B: 48,24,12,6; C: 2,5,10,17. State d or r when it exists.','Для каждой последовательности определите: арифметическая, геометрическая или ни одна, и обоснуйте постоянными разностями или отношениями: A: 7,11,15,19; B: 48,24,12,6; C: 2,5,10,17. Укажите d или r, если они существуют.','Har bir ketma-ketlikni arifmetik, geometrik yoki hech qaysi deb aniqlang va doimiy ayirma yoki nisbat bilan asoslang: A: 7,11,15,19; B: 48,24,12,6; C: 2,5,10,17. Mavjud bo‘lsa d yoki r ni yozing.','{"max_marks":10,"criteria":[{"id":"A","marks":3,"rule":"A arithmetic with d=4, supported by repeated differences."},{"id":"B","marks":3,"rule":"B geometric with r=1/2, supported by repeated ratios."},{"id":"C","marks":3,"rule":"C neither because neither differences nor ratios are constant."},{"id":"method","marks":1,"rule":"Uses more than one adjacent comparison before classifying."}]}','Do not classify from the first pair only; verify the pattern across the sequence.','Не классифицируйте по первой паре; проверьте закономерность по нескольким переходам.','Faqat birinchi juftlikka qarab tasniflamang; bir necha o‘tishni tekshiring.'),
('P1DIF01-W01','P1-DIF-01','Using the limit definition, derive the gradient of f(x)=x² at a general point x=a. Then use your result to find the tangent gradient at a=4 and explain in one sentence what that gradient means geometrically.','Используя определение через предел, выведите градиент f(x)=x² в общей точке x=a. Затем найдите градиент касательной при a=4 и одним предложением объясните его геометрический смысл.','Limit ta’rifidan foydalanib f(x)=x² ning x=a dagi umumiy gradientini chiqaring. So‘ng a=4 dagi urinma gradientini toping va uning geometrik ma’nosini bir gapda tushuntiring.','{"max_marks":10,"criteria":[{"id":"quotient","marks":3,"rule":"Forms [(a+h)²−a²]/h."},{"id":"algebra","marks":3,"rule":"Expands to 2a+h after cancelling h for h≠0."},{"id":"limit","marks":2,"rule":"Takes h→0 to obtain 2a and hence 8 at a=4."},{"id":"meaning","marks":2,"rule":"Identifies the value as the gradient of the tangent/instantaneous rate at that point."}]}','Do not substitute h=0 before cancelling. The limit is taken after algebraic simplification.','Не подставляйте h=0 до сокращения. Предел берётся после алгебраического упрощения.','h ni qisqartirishdan oldin 0 qo‘ymang. Limit algebraik soddalashtirishdan keyin olinadi.')
)
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw13_16_series_diff_diagnostic','diagnostic','P1 AW13-16 Series/Differentiation diagnostic','Диагностика P1 AW13–16: ряды/производная','P1 AW13–16 Series/Differentiation diagnostikasi'),
('p1_ser01_learning','learning','Binomial expansion learning','Биномиальное разложение','Binomial yoyilma'),
('p1_ser02_learning','learning','AP/GP recognition learning','Распознавание AP/GP','AP/GP aniqlash'),
('p1_dif01_learning','learning','Derivative meaning and limit learning','Смысл производной и предел','Hosila ma’nosi va limit'),
('p1_ser01_retest','retest','Binomial expansion delayed retest','Отложенный ретест: биномиальное разложение','Kechiktirilgan retest: binomial yoyilma'),
('p1_ser02_retest','retest','AP/GP delayed retest','Отложенный ретест: AP/GP','Kechiktirilgan retest: AP/GP'),
('p1_dif01_retest','retest','Derivative-limit delayed retest','Отложенный ретест: производная','Kechiktirilgan retest: hosila'),
('p1_aw13_16_series_diff_mixed','mixed','P1 AW13-16 Series/Differentiation mixed transfer','Смешанный перенос P1 AW13–16: ряды/производная','P1 AW13–16 Series/Differentiation mixed transfer')
)
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw13_16_series_diff_diagnostic',1,'P1SER01-D01',null,'P1-SER-01','diagnostic',true),('p1_aw13_16_series_diff_diagnostic',2,'P1SER02-D01',null,'P1-SER-02','diagnostic',true),('p1_aw13_16_series_diff_diagnostic',3,'P1DIF01-D01',null,'P1-DIF-01','diagnostic',true),
('p1_ser01_learning',1,'P1SER01-L01',null,'P1-SER-01','learning',false),('p1_ser01_learning',2,'P1SER01-L02',null,'P1-SER-01','learning',false),('p1_ser01_learning',3,'P1SER01-L03',null,'P1-SER-01','learning',false),('p1_ser01_learning',4,null,'P1SER01-W01','P1-SER-01','written',false),
('p1_ser02_learning',1,'P1SER02-L01',null,'P1-SER-02','learning',false),('p1_ser02_learning',2,'P1SER02-L02',null,'P1-SER-02','learning',false),('p1_ser02_learning',3,'P1SER02-L03',null,'P1-SER-02','learning',false),('p1_ser02_learning',4,null,'P1SER02-W01','P1-SER-02','written',false),
('p1_dif01_learning',1,'P1DIF01-L01',null,'P1-DIF-01','learning',false),('p1_dif01_learning',2,'P1DIF01-L02',null,'P1-DIF-01','learning',false),('p1_dif01_learning',3,'P1DIF01-L03',null,'P1-DIF-01','learning',false),('p1_dif01_learning',4,null,'P1DIF01-W01','P1-DIF-01','written',false),
('p1_ser01_retest',1,'P1SER01-R01',null,'P1-SER-01','retest',true),('p1_ser02_retest',1,'P1SER02-R01',null,'P1-SER-02','retest',true),('p1_dif01_retest',1,'P1DIF01-R01',null,'P1-DIF-01','retest',true),
('p1_aw13_16_series_diff_mixed',1,'P1SER01-M01',null,'P1-SER-01','mixed',true),('p1_aw13_16_series_diff_mixed',2,'P1SER02-M01',null,'P1-SER-02','mixed',true),('p1_aw13_16_series_diff_mixed',3,'P1DIF01-M01',null,'P1-DIF-01','mixed',true)
)
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

do $$ declare v_id bigint; v_skill text; v_bad int; begin
select id into v_id from private.exam_prep_content_versions where content_version='p1_aw13_16_series_diff_v1' and status='draft'; if v_id is null then raise exception 'P1 AW13 series/diff draft missing'; end if;
if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id)<>21 then raise exception 'P1 AW13 series/diff expected 21 questions'; end if;
foreach v_skill in array array['P1-SER-01','P1-SER-02','P1-DIF-01'] loop
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='diagnostic')<>1 then raise exception '% diagnostic floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='learning')<>3 then raise exception '% learning floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='retest')<>2 then raise exception '% retest floor',v_skill; end if;
 if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id and primary_skill_code=v_skill and reserve_role='mixed')<>1 then raise exception '% mixed floor',v_skill; end if;
 if (select count(*) from private.exam_prep_written_tasks where content_version_id=v_id and primary_skill_code=v_skill and lifecycle_state='approved')<>1 then raise exception '% written floor',v_skill; end if;
end loop;
select count(*) into v_bad from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id where m.content_version_id=v_id and (q.subject_id<>5 or q.is_active or q.quality_status is distinct from 'draft' or nullif(trim(q.question_text_en),'') is null or nullif(trim(q.question_text_ru),'') is null or nullif(trim(q.question_text_uz),'') is null or jsonb_typeof(q.options_text_en::jsonb)<>'array' or jsonb_array_length(q.options_text_en::jsonb)<>4 or q.correct_answer not in ('A','B','C','D') or nullif(trim(q.explanation_en),'') is null or nullif(trim(q.explanation_ru),'') is null or nullif(trim(q.explanation_uz),'') is null or md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))<>m.question_snapshot_md5); if v_bad<>0 then raise exception 'P1 AW13 series/diff payload failures=%',v_bad; end if;
select count(*) into v_bad from (select m.id from private.exam_prep_question_content_meta m join public.questions q on q.id=m.question_id left join private.exam_prep_diagnostic_rules r on r.content_meta_id=m.id and r.status='approved' and r.answer_kind='mcq_option' where m.content_version_id=v_id and m.reserve_role='diagnostic' group by m.id,q.correct_answer having count(r.id)<>3 or count(r.id) filter(where r.answer_match=q.correct_answer)<>0) x; if v_bad<>0 then raise exception 'P1 AW13 series/diff diagnostic failures=%',v_bad; end if;
if (select count(*) from private.exam_prep_question_content_meta m where m.content_version_id=v_id and m.reserve_role='retest' and not exists(select 1 from private.exam_prep_assessment_items i where i.question_id=m.question_id))<>3 then raise exception 'P1 AW13 series/diff expected 3 isolated R02 holdouts'; end if;
end $$;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw13_16_series_diff_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw13_16_series_diff_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw13_16_series_diff_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw13_16_series_diff_v1' and cv.status='approved' and w.lifecycle_state='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw13_16_series_diff_v1' and cv.status='approved' and a.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw13_16_series_diff_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; v_ready int; v_r jsonb; v_cfg private.exam_prep_feature_config%rowtype; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
foreach v_skill in array array['P1-SER-01','P1-SER-02','P1-DIF-01'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 AW13 series/diff final not ready=%',v_skill; end if; end loop;
select count(*) into v_ready from private.exam_prep_content_runway_release_skills rs join private.exam_prep_content_runway_releases r on r.id=rs.release_id where r.release_key='aw13_16_core_coverage_iii' and r.component_code='P1' and rs.required_for_release and private.exam_prep_skill_content_ready_v1(v_program,'P1',rs.skill_code); if v_ready<>8 then raise exception 'P1 AW13 expected full P1 ready=8 got=%',v_ready; end if;
v_r:=public.get_exam_prep_content_runway_v1(13::smallint); if coalesce((v_r->>'hard_floor_green')::boolean,false) then raise exception 'P1 AW13 P1-only completion must leave global runway RED while P5 incomplete'; end if;
select * into v_cfg from private.exam_prep_feature_config where id=1; if v_cfg.rollout_state<>'off' or v_cfg.core_enabled or v_cfg.ai_enabled or v_cfg.mentor_enabled or not v_cfg.kill_switch then raise exception 'P1 AW13 series/diff feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 AW13 series/diff entitlement residue'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw13_16_series_diff_v1:%' and is_active) then raise exception 'P1 AW13 series/diff legacy activation'; end if;
end $$;
commit;
