-- P1-02 P5 AW13-16: DRV-03 variance and standard deviation.
-- Original iClub-authored content only; governed publication; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw13_16_drv03_v1','P5','P5 AW13-16 DRV-03 variance and standard deviation','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv03_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5DRV03-D01','diagnostic','medium','X takes values 0,1,2 with probabilities 0.25,0.50,0.25. Find Var(X).','X принимает значения 0,1,2 с вероятностями 0,25,0,50,0,25. Найдите Var(X).','X 0,1,2 qiymatlarni 0.25,0.50,0.25 ehtimollar bilan oladi. Var(X) ni toping.','["0.50","1.00","1.50","0.25"]','["0,50","1,00","1,50","0,25"]','["0.50","1.00","1.50","0.25"]','A','E(X)=1 and E(X²)=1.5, so Var(X)=E(X²)−[E(X)]²=1.5−1=0.5.','E(X)=1 и E(X²)=1,5, поэтому Var(X)=1,5−1²=0,5.','E(X)=1 va E(X²)=1.5, demak Var(X)=1.5−1²=0.5.',75),
('P5DRV03-L01','learning','easy','For a random variable, E(X)=3 and E(X²)=11. Find Var(X).','Для случайной величины E(X)=3 и E(X²)=11. Найдите Var(X).','Tasodifiy miqdor uchun E(X)=3 va E(X²)=11. Var(X) ni toping.','["2","8","20","121"]','["2","8","20","121"]','["2","8","20","121"]','A','Var(X)=11−3²=2.','Var(X)=11−3²=2.','Var(X)=11−3²=2.',40),
('P5DRV03-L02','learning','easy','If Var(X)=4, find the standard deviation of X.','Если Var(X)=4, найдите стандартное отклонение X.','Var(X)=4 bo‘lsa, X ning standart og‘ishini toping.','["2","4","8","16"]','["2","4","8","16"]','["2","4","8","16"]','A','Standard deviation is the positive square root of variance: √4=2.','Стандартное отклонение — положительный квадратный корень из дисперсии: √4=2.','Standart og‘ish dispersiyaning musbat kvadrat ildizi: √4=2.',35),
('P5DRV03-L03','learning','medium','X takes values 1 and 3, each with probability 0.5. Find Var(X).','X принимает значения 1 и 3, каждое с вероятностью 0,5. Найдите Var(X).','X 1 va 3 qiymatlarni har biri 0.5 ehtimol bilan oladi. Var(X) ni toping.','["1","2","4","5"]','["1","2","4","5"]','["1","2","4","5"]','A','E(X)=2 and E(X²)=5, so Var(X)=5−4=1.','E(X)=2 и E(X²)=5, поэтому Var(X)=5−4=1.','E(X)=2 va E(X²)=5, demak Var(X)=5−4=1.',55),
('P5DRV03-R01','retest','easy','For X, E(X)=2 and E(X²)=6. Find Var(X).','Для X: E(X)=2 и E(X²)=6. Найдите Var(X).','X uchun E(X)=2 va E(X²)=6. Var(X) ni toping.','["2","4","8","10"]','["2","4","8","10"]','["2","4","8","10"]','A','Var(X)=6−2²=2.','Var(X)=6−2²=2.','Var(X)=6−2²=2.',40),
('P5DRV03-R02','retest','easy','If Var(X)=2.25, find the standard deviation.','Если Var(X)=2,25, найдите стандартное отклонение.','Var(X)=2.25 bo‘lsa, standart og‘ishni toping.','["1.5","2.25","4.5","1.125"]','["1,5","2,25","4,5","1,125"]','["1.5","2.25","4.5","1.125"]','A','SD(X)=√2.25=1.5.','SD(X)=√2,25=1,5.','SD(X)=√2.25=1.5.',35),
('P5DRV03-M01','mixed','medium','X takes values 0 and 2, each with probability 0.5. Find the standard deviation of X.','X принимает значения 0 и 2, каждое с вероятностью 0,5. Найдите стандартное отклонение X.','X 0 va 2 qiymatlarni har biri 0.5 ehtimol bilan oladi. X ning standart og‘ishini toping.','["1","2","√2","0.5"]','["1","2","√2","0,5"]','["1","2","√2","0.5"]','A','E(X)=1, E(X²)=2, Var(X)=1, so SD(X)=1.','E(X)=1, E(X²)=2, Var(X)=1, поэтому SD(X)=1.','E(X)=1, E(X²)=2, Var(X)=1, demak SD(X)=1.',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Discrete Random Variables','P5-DRV-03',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw13_16_drv03_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw13_16_drv03_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv03_v1' and status='draft'), keys(k,role) as (values('P5DRV03-D01','diagnostic'),('P5DRV03-L01','learning'),('P5DRV03-L02','learning'),('P5DRV03-L03','learning'),('P5DRV03-R01','retest'),('P5DRV03-R02','retest'),('P5DRV03-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-DRV-03','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw13_16_drv03_v1 from canonical DRV-03 intent.','Cambridge 9709 2026-2027 v4; P5 5.4 Discrete random variables','Complete Probability & Statistics 1; variance and standard deviation (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw13_16_drv03_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw13_16_drv03_v1' and m.content_key='P5DRV03-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','uses_mean_as_variance','concept','The mean is 1, but variance measures spread around the mean and is not generally equal to E(X).','Среднее равно 1, но дисперсия измеряет разброс вокруг среднего и обычно не равна E(X).','O‘rtacha 1, ammo dispersiya o‘rtacha atrofidagi tarqalishni o‘lchaydi va E(X) ga teng emas.','Compute E(X²) and then subtract [E(X)]².','Найдите E(X²), затем вычтите [E(X)]².','E(X²) ni topib, [E(X)]² ni ayiring.'),
('C','uses_second_moment','method','E(X²)=1.5 is the second moment, not the variance; the squared mean must be subtracted.','E(X²)=1,5 — второй момент, а не дисперсия; нужно вычесть квадрат среднего.','E(X²)=1.5 ikkinchi moment, dispersiya emas; o‘rtachaning kvadratini ayirish kerak.','Use Var(X)=E(X²)−[E(X)]².','Используйте Var(X)=E(X²)−[E(X)]².','Var(X)=E(X²)−[E(X)]² dan foydalaning.'),
('D','squares_probability','method','Variance is not found by squaring one probability; it uses the entire distribution.','Дисперсия не находится возведением одной вероятности в квадрат; используется всё распределение.','Dispersiya bitta ehtimolni kvadratlash bilan topilmaydi; butun taqsimot ishlatiladi.','Build E(X) and E(X²) from all outcomes.','Постройте E(X) и E(X²) по всем исходам.','Barcha natijalardan E(X) va E(X²) ni tuzing.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-DRV-03',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from meta cross join r
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv03_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5DRV03-W01','P5','P5-DRV-03','wtv1','X takes values 0, 2 and 4 with probabilities 0.25, 0.50 and 0.25. Find E(X), E(X²), Var(X) and the standard deviation. Explain why a valid variance cannot be negative.','X принимает значения 0, 2 и 4 с вероятностями 0,25, 0,50 и 0,25. Найдите E(X), E(X²), Var(X) и стандартное отклонение. Объясните, почему корректная дисперсия не может быть отрицательной.','X 0, 2 va 4 qiymatlarni 0.25, 0.50 va 0.25 ehtimollar bilan oladi. E(X), E(X²), Var(X) va standart og‘ishni toping. Nega to‘g‘ri dispersiya manfiy bo‘la olmasligini tushuntiring.','{"max_marks":10,"criteria":[{"id":"mean","marks":2,"rule":"Obtains E(X)=2."},{"id":"second_moment","marks":2,"rule":"Obtains E(X²)=6."},{"id":"variance","marks":2,"rule":"Obtains Var(X)=2."},{"id":"sd","marks":2,"rule":"Obtains SD=sqrt(2)."},{"id":"nonnegative","marks":2,"rule":"Explains variance is an expectation of squared deviations and therefore cannot be negative."}]}','Calculate E(X) and E(X²) separately, then apply Var(X)=E(X²)−[E(X)]² and take the positive square root.','Отдельно найдите E(X) и E(X²), затем примените Var(X)=E(X²)−[E(X)]² и возьмите положительный корень.','E(X) va E(X²) ni alohida toping, keyin Var(X)=E(X²)−[E(X)]² ni qo‘llab, musbat ildizni oling.','approved','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv03_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_drv03_diagnostic','diagnostic','DRV-03 diagnostic','Диагностика DRV-03','DRV-03 diagnostikasi'),('p5_drv03_learning','learning','DRV-03 learning','DRV-03 обучение','DRV-03 o‘rganish'),('p5_drv03_retest','retest','DRV-03 delayed retest','DRV-03 отложенный ретест','DRV-03 kechiktirilgan retest'),('p5_drv03_mixed','mixed','DRV-03 mixed transfer','DRV-03 смешанный перенос','DRV-03 mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw13_16_drv03_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_drv03_diagnostic',1,'P5DRV03-D01',null,'diagnostic',true),('p5_drv03_learning',1,'P5DRV03-L01',null,'learning',false),('p5_drv03_learning',2,'P5DRV03-L02',null,'learning',false),('p5_drv03_learning',3,'P5DRV03-L03',null,'learning',false),('p5_drv03_learning',4,null,'P5DRV03-W01','written',false),('p5_drv03_retest',1,'P5DRV03-R01',null,'retest',true),('p5_drv03_mixed',1,'P5DRV03-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-DRV-03',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_drv03_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw13_16_drv03_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw13_16_drv03_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p5_aw13_16_drv03_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw13_16_drv03_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw13_16_drv03_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-DRV-03') then raise exception 'DRV-03 not ready after publish'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw13_16_drv03_v1:%' and is_active) then raise exception 'legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'feature escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'active entitlement residue'; end if;
end $$;
commit;
