-- P1-02 P1 AW21-24 Differentiation applications: DIF-05/06/07.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw21_24_diff_apps_v1','P1','P1 AW21-24 Differentiation applications','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_diff_apps_v1' and component_code='P1' and status='draft'), src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-DIF-05','P1DIF05-D01','diagnostic','medium','For f(x)=x^3−3x, on which intervals is f increasing?','Для f(x)=x^3−3x на каких промежутках функция возрастает?','f(x)=x^3−3x qaysi oraliqlarda o‘sadi?','["x<−1 or x>1","−1<x<1","x>−1 only","all real x"]','["x<−1 или x>1","−1<x<1","только x>−1","все x"]','["x<−1 yoki x>1","−1<x<1","faqat x>−1","barcha x"]','A','f′(x)=3(x^2−1)=3(x−1)(x+1), which is positive outside the roots −1 and 1.','f′(x)=3(x^2−1), положительна вне корней −1 и 1.','f′(x)=3(x^2−1), u −1 va 1 ildizlar tashqarisida musbat.',50),
('P1-DIF-05','P1DIF05-L01','learning','easy','For f(x)=x^2−4x, which statement is correct?','Для f(x)=x^2−4x какое утверждение верно?','f(x)=x^2−4x uchun qaysi gap to‘g‘ri?','["decreasing for x<2 and increasing for x>2","increasing for x<2 and decreasing for x>2","increasing for all x","decreasing for all x"]','["убывает при x<2 и возрастает при x>2","возрастает при x<2 и убывает при x>2","всегда возрастает","всегда убывает"]','["x<2 da kamayadi, x>2 da o‘sadi","x<2 da o‘sadi, x>2 da kamayadi","har doim o‘sadi","har doim kamayadi"]','A','f′(x)=2x−4 changes from negative to positive at x=2.','f′(x)=2x−4 меняет знак с минуса на плюс при x=2.','f′(x)=2x−4 x=2 da manfiydan musbatga o‘tadi.',35),
('P1-DIF-05','P1DIF05-L02','learning','medium','A derivative factorises as f′(x)=(x−2)(x+1). Where is f decreasing?','Производная разлагается как f′(x)=(x−2)(x+1). Где f убывает?','Hosila f′(x)=(x−2)(x+1). f qayerda kamayadi?','["−1<x<2","x<−1 or x>2","x>2 only","x<2"]','["−1<x<2","x<−1 или x>2","только x>2","x<2"]','["−1<x<2","x<−1 yoki x>2","faqat x>2","x<2"]','A','The product is negative between its two roots.','Произведение отрицательно между двумя корнями.','Ko‘paytma ikki ildiz orasida manfiy.',40),
('P1-DIF-05','P1DIF05-L03','learning','medium','For f(x)=−x^2+6x, where is f increasing?','Для f(x)=−x^2+6x где f возрастает?','f(x)=−x^2+6x qayerda o‘sadi?','["x<3","x>3","x<−3","all real x"]','["x<3","x>3","x<−3","все x"]','["x<3","x>3","x<−3","barcha x"]','A','f′(x)=−2x+6>0 when x<3.','f′(x)=−2x+6>0 при x<3.','f′(x)=−2x+6>0 x<3 da.',35),
('P1-DIF-05','P1DIF05-R01','retest','easy','For f(x)=x^2+2x, where is f decreasing?','Для f(x)=x^2+2x где f убывает?','f(x)=x^2+2x qayerda kamayadi?','["x<−1","x>−1","x<1","all real x"]','["x<−1","x>−1","x<1","все x"]','["x<−1","x>−1","x<1","barcha x"]','A','f′(x)=2x+2<0 when x<−1.','f′(x)=2x+2<0 при x<−1.','f′(x)=2x+2<0 x<−1 da.',30),
('P1-DIF-05','P1DIF05-R02','retest','medium','If f′(x)=x^2−4, where is f increasing?','Если f′(x)=x^2−4, где f возрастает?','Agar f′(x)=x^2−4 bo‘lsa, f qayerda o‘sadi?','["x<−2 or x>2","−2<x<2","x>−2","all real x"]','["x<−2 или x>2","−2<x<2","x>−2","все x"]','["x<−2 yoki x>2","−2<x<2","x>−2","barcha x"]','A','x^2−4>0 outside −2 and 2.','x^2−4>0 вне промежутка между −2 и 2.','x^2−4>0 −2 va 2 tashqarisida.',35),
('P1-DIF-05','P1DIF05-M01','mixed','medium','For f(x)=x^3−12x, where is f increasing?','Для f(x)=x^3−12x где f возрастает?','f(x)=x^3−12x qayerda o‘sadi?','["x<−2 or x>2","−2<x<2","x>2 only","x<2"]','["x<−2 или x>2","−2<x<2","только x>2","x<2"]','["x<−2 yoki x>2","−2<x<2","faqat x>2","x<2"]','A','f′=3(x^2−4), positive outside ±2.','f′=3(x^2−4), положительна вне ±2.','f′=3(x^2−4), ±2 tashqarisida musbat.',40),

('P1-DIF-06','P1DIF06-D01','diagnostic','medium','A circle has radius r increasing at 2 cm/s. Find dA/dt when r=3 cm.','Радиус окружности увеличивается со скоростью 2 см/с. Найдите dA/dt при r=3 см.','Aylana radiusi 2 cm/s tezlikda oshmoqda. r=3 cm da dA/dt ni toping.','["12pi cm^2/s","6pi cm^2/s","18pi cm^2/s","12pi cm/s"]','["12pi см^2/с","6pi см^2/с","18pi см^2/с","12pi см/с"]','["12pi cm^2/s","6pi cm^2/s","18pi cm^2/s","12pi cm/s"]','A','A=pi r^2, so dA/dt=2pi r(dr/dt)=2pi(3)(2)=12pi cm^2/s.','A=pi r^2, поэтому dA/dt=2pi r(dr/dt)=12pi см^2/с.','A=pi r^2, demak dA/dt=2pi r(dr/dt)=12pi cm^2/s.',50),
('P1-DIF-06','P1DIF06-L01','learning','easy','A particle has displacement s=t^3 metres. What is its speed at t=2 s?','Перемещение частицы s=t^3 м. Какова скорость при t=2 с?','Zarra siljishi s=t^3 metr. t=2 s da tezlik qancha?','["12 m/s","8 m/s","6 m/s","24 m/s"]','["12 м/с","8 м/с","6 м/с","24 м/с"]','["12 m/s","8 m/s","6 m/s","24 m/s"]','A','ds/dt=3t^2, so at t=2 the speed is 12 m/s.','ds/dt=3t^2, при t=2 скорость 12 м/с.','ds/dt=3t^2, t=2 da tezlik 12 m/s.',30),
('P1-DIF-06','P1DIF06-L02','learning','medium','A sphere has radius increasing at 0.5 cm/s. Find dV/dt when r=2 cm.','Радиус сферы увеличивается на 0,5 см/с. Найдите dV/dt при r=2 см.','Sfera radiusi 0.5 cm/s tezlikda oshadi. r=2 cm da dV/dt ni toping.','["8pi cm^3/s","4pi cm^3/s","16pi cm^3/s","2pi cm^2/s"]','["8pi см^3/с","4pi см^3/с","16pi см^3/с","2pi см^2/с"]','["8pi cm^3/s","4pi cm^3/s","16pi cm^3/s","2pi cm^2/s"]','A','V=4pi r^3/3 gives dV/dt=4pi r^2 dr/dt=4pi(4)(0.5)=8pi.','V=4pi r^3/3, поэтому dV/dt=4pi r^2 dr/dt=8pi.','V=4pi r^3/3, demak dV/dt=4pi r^2 dr/dt=8pi.',45),
('P1-DIF-06','P1DIF06-L03','learning','medium','If y=x^2 and x is increasing at 3 units/s, find dy/dt when x=4.','Если y=x^2 и x увеличивается со скоростью 3 ед/с, найдите dy/dt при x=4.','Agar y=x^2 va x 3 birlik/s tezlikda oshsa, x=4 da dy/dt ni toping.','["24 units/s","12 units/s","48 units/s","8 units/s"]','["24 ед/с","12 ед/с","48 ед/с","8 ед/с"]','["24 birlik/s","12 birlik/s","48 birlik/s","8 birlik/s"]','A','dy/dt=(dy/dx)(dx/dt)=2x(3)=24 at x=4.','dy/dt=(dy/dx)(dx/dt)=2x(3)=24 при x=4.','dy/dt=(dy/dx)(dx/dt)=2x(3)=24, x=4 da.',40),
('P1-DIF-06','P1DIF06-R01','retest','easy','A square side x increases at 1.5 cm/s. Find dA/dt when x=4 cm.','Сторона квадрата x увеличивается на 1,5 см/с. Найдите dA/dt при x=4 см.','Kvadrat tomoni x 1.5 cm/s tezlikda oshadi. x=4 cm da dA/dt ni toping.','["12 cm^2/s","6 cm^2/s","24 cm^2/s","8 cm/s"]','["12 см^2/с","6 см^2/с","24 см^2/с","8 см/с"]','["12 cm^2/s","6 cm^2/s","24 cm^2/s","8 cm/s"]','A','A=x^2, so dA/dt=2x dx/dt=2(4)(1.5)=12.','A=x^2, поэтому dA/dt=12.','A=x^2, demak dA/dt=12.',30),
('P1-DIF-06','P1DIF06-R02','retest','medium','A circle radius is decreasing at 0.2 m/s. Find the rate of change of circumference.','Радиус окружности уменьшается со скоростью 0,2 м/с. Найдите скорость изменения длины окружности.','Aylana radiusi 0.2 m/s tezlikda kamaymoqda. Aylana uzunligining o‘zgarish tezligini toping.','["−0.4pi m/s","0.4pi m/s","−0.2pi m/s","−0.4pi m^2/s"]','["−0,4pi м/с","0,4pi м/с","−0,2pi м/с","−0,4pi м^2/с"]','["−0.4pi m/s","0.4pi m/s","−0.2pi m/s","−0.4pi m^2/s"]','A','C=2pi r, so dC/dt=2pi dr/dt=2pi(−0.2)=−0.4pi.','C=2pi r, поэтому dC/dt=−0,4pi.','C=2pi r, demak dC/dt=−0.4pi.',35),
('P1-DIF-06','P1DIF06-M01','mixed','hard','A sphere has volume increasing at 36pi cm^3/s. Find dr/dt when r=3 cm.','Объём сферы увеличивается на 36pi см^3/с. Найдите dr/dt при r=3 см.','Sfera hajmi 36pi cm^3/s tezlikda oshmoqda. r=3 cm da dr/dt ni toping.','["1 cm/s","3 cm/s","4 cm/s","1/3 cm/s"]','["1 см/с","3 см/с","4 см/с","1/3 см/с"]','["1 cm/s","3 cm/s","4 cm/s","1/3 cm/s"]','A','dV/dt=4pi r^2 dr/dt. At r=3, 36pi=36pi dr/dt, hence dr/dt=1.','dV/dt=4pi r^2 dr/dt. При r=3 получаем dr/dt=1.','dV/dt=4pi r^2 dr/dt. r=3 da dr/dt=1.',50),

('P1-DIF-07','P1DIF07-D01','diagnostic','hard','For f(x)=x^3−3x^2, classify the stationary points.','Для f(x)=x^3−3x^2 классифицируйте стационарные точки.','f(x)=x^3−3x^2 uchun statsionar nuqtalarni tasniflang.','["local maximum at x=0 and local minimum at x=2","local minimum at x=0 and local maximum at x=2","maxima at both x=0 and x=2","only one stationary point at x=1"]','["локальный максимум при x=0 и минимум при x=2","локальный минимум при x=0 и максимум при x=2","максимумы при x=0 и x=2","только одна точка x=1"]','["x=0 da lokal maksimum, x=2 da lokal minimum","x=0 da lokal minimum, x=2 da lokal maksimum","ikkalasi ham maksimum","faqat x=1 statsionar"]','A','f′=3x(x−2), so x=0,2. f′′=6x−6 is negative at 0 and positive at 2.','f′=3x(x−2), поэтому x=0,2. f′′=6x−6 отрицательна при 0 и положительна при 2.','f′=3x(x−2), demak x=0,2. f′′=6x−6 0 da manfiy, 2 da musbat.',60),
('P1-DIF-07','P1DIF07-L01','learning','easy','For f(x)=x^2−4x+1, where is the stationary point and what is its nature?','Для f(x)=x^2−4x+1 где стационарная точка и каков её тип?','f(x)=x^2−4x+1 statsionar nuqta qayerda va turi qanday?','["x=2, minimum","x=2, maximum","x=−2, minimum","x=4, maximum"]','["x=2, минимум","x=2, максимум","x=−2, минимум","x=4, максимум"]','["x=2, minimum","x=2, maksimum","x=−2, minimum","x=4, maksimum"]','A','f′=2x−4=0 at x=2 and f′′=2>0, so it is a minimum.','f′=2x−4=0 при x=2, f′′=2>0, значит минимум.','f′=2x−4=0 x=2 da, f′′=2>0, demak minimum.',35),
('P1-DIF-07','P1DIF07-L02','learning','easy','For f(x)=−x^2+6x, what is the x-coordinate of the maximum?','Для f(x)=−x^2+6x какова x-координата максимума?','f(x)=−x^2+6x maksimumining x-koordinatasi qancha?','["3","−3","6","0"]','["3","−3","6","0"]','["3","−3","6","0"]','A','f′=−2x+6=0 gives x=3; f′′=−2<0 confirms a maximum.','f′=−2x+6=0 даёт x=3; f′′=−2<0 подтверждает максимум.','f′=−2x+6=0 dan x=3; f′′=−2<0 maksimum.',30),
('P1-DIF-07','P1DIF07-L03','learning','medium','A rectangle has perimeter 20. If one side is x, its area is A=x(10−x). For x>0, at what x is the area maximum?','Прямоугольник имеет периметр 20. Если одна сторона x, площадь A=x(10−x). При x>0 когда площадь максимальна?','To‘g‘ri to‘rtburchak perimetri 20. Bir tomoni x bo‘lsa, A=x(10−x). x>0 da maydon qachon maksimal?','["x=5","x=10","x=2.5","x=1"]','["x=5","x=10","x=2,5","x=1"]','["x=5","x=10","x=2.5","x=1"]','A','A′=10−2x=0 gives x=5 and A′′=−2<0.','A′=10−2x=0 даёт x=5, A′′=−2<0.','A′=10−2x=0 dan x=5, A′′=−2<0.',40),
('P1-DIF-07','P1DIF07-R01','retest','medium','For f(x)=x^3−12x, classify the stationary points x=−2 and x=2.','Для f(x)=x^3−12x классифицируйте стационарные точки x=−2 и x=2.','f(x)=x^3−12x uchun x=−2 va x=2 statsionar nuqtalarni tasniflang.','["maximum at −2, minimum at 2","minimum at −2, maximum at 2","both maxima","both minima"]','["максимум при −2, минимум при 2","минимум при −2, максимум при 2","оба максимумы","оба минимумы"]','["−2 da maksimum, 2 da minimum","−2 da minimum, 2 da maksimum","ikkalasi maksimum","ikkalasi minimum"]','A','f′′=6x: negative at −2 and positive at 2.','f′′=6x: отрицательна при −2 и положительна при 2.','f′′=6x: −2 da manfiy, 2 da musbat.',35),
('P1-DIF-07','P1DIF07-R02','retest','easy','For f(x)=x^2+6x+7, where is its minimum?','Для f(x)=x^2+6x+7 где находится минимум?','f(x)=x^2+6x+7 minimumi qayerda?','["x=−3","x=3","x=−6","x=7"]','["x=−3","x=3","x=−6","x=7"]','["x=−3","x=3","x=−6","x=7"]','A','f′=2x+6=0 gives x=−3 and f′′=2>0.','f′=2x+6=0 даёт x=−3, f′′=2>0.','f′=2x+6=0 dan x=−3, f′′=2>0.',30),
('P1-DIF-07','P1DIF07-M01','mixed','medium','A profit model is P(x)=−2x^2+12x+5. At what x is profit maximised?','Модель прибыли P(x)=−2x^2+12x+5. При каком x прибыль максимальна?','Foyda modeli P(x)=−2x^2+12x+5. Qaysi x da foyda maksimal?','["3","6","−3","12"]','["3","6","−3","12"]','["3","6","−3","12"]','A','P′=−4x+12=0 gives x=3 and P′′=−4<0.','P′=−4x+12=0 даёт x=3, P′′=−4<0.','P′=−4x+12=0 dan x=3, P′′=−4<0.',35)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Differentiation Applications',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw21_24_diff_apps_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw21_24_diff_apps_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_diff_apps_v1' and status='draft'), keys(skill,k,role) as (values
('P1-DIF-05','P1DIF05-D01','diagnostic'),('P1-DIF-05','P1DIF05-L01','learning'),('P1-DIF-05','P1DIF05-L02','learning'),('P1-DIF-05','P1DIF05-L03','learning'),('P1-DIF-05','P1DIF05-R01','retest'),('P1-DIF-05','P1DIF05-R02','retest'),('P1-DIF-05','P1DIF05-M01','mixed'),
('P1-DIF-06','P1DIF06-D01','diagnostic'),('P1-DIF-06','P1DIF06-L01','learning'),('P1-DIF-06','P1DIF06-L02','learning'),('P1-DIF-06','P1DIF06-L03','learning'),('P1-DIF-06','P1DIF06-R01','retest'),('P1-DIF-06','P1DIF06-R02','retest'),('P1-DIF-06','P1DIF06-M01','mixed'),
('P1-DIF-07','P1DIF07-D01','diagnostic'),('P1-DIF-07','P1DIF07-L01','learning'),('P1-DIF-07','P1DIF07-L02','learning'),('P1-DIF-07','P1DIF07-L03','learning'),('P1-DIF-07','P1DIF07-R01','retest'),('P1-DIF-07','P1DIF07-R02','retest'),('P1-DIF-07','P1DIF07-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw21_24_diff_apps_v1 from canonical differentiation-application skill intent.','Cambridge 9709 2026-2027 v4; P1 1.7 Differentiation','Complete Pure Mathematics 1; Differentiation applications (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw21_24_diff_apps_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw21_24_diff_apps_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1DIF05-D01','B','reverses_derivative_sign','concept','Between −1 and 1 the derivative is negative, so f is decreasing there, not increasing.','Между −1 и 1 производная отрицательна, поэтому функция там убывает.','−1 va 1 orasida hosila manfiy, demak funksiya kamayadi.','Make a sign chart for f′ around every critical root.','Постройте таблицу знаков f′ около каждого критического корня.','Har bir kritik ildiz atrofida f′ ishora jadvalini tuzing.'),
('P1DIF05-D01','C','drops_left_interval','method','The quadratic derivative is also positive for x<−1; do not keep only the right-hand interval.','Квадратичная производная положительна также при x<−1; нельзя оставлять только правый интервал.','Kvadrat hosila x<−1 da ham musbat; faqat o‘ng oraliqni qoldirmang.','Test one point in every interval separated by derivative roots.','Проверяйте по одной точке в каждом интервале между корнями производной.','Hosila ildizlari ajratgan har bir oraliqda bitta nuqtani tekshiring.'),
('P1DIF05-D01','D','ignores_critical_points','concept','f′ changes sign at ±1, so f cannot be increasing on all real x.','f′ меняет знак при ±1, поэтому f не возрастает на всей прямой.','f′ ±1 da ishora almashtiradi, shuning uchun f barcha x da o‘smaydi.','Solve f′=0 before deciding monotonic intervals.','Сначала решите f′=0, затем определяйте интервалы монотонности.','Avval f′=0 ni yeching, keyin monoton oraliqlarni aniqlang.'),
('P1DIF06-D01','B','omits_dr_dt','method','2pi r is dA/dr only. The time rate must also multiply by dr/dt=2.','2pi r — это только dA/dr. Для скорости по времени нужно умножить на dr/dt=2.','2pi r faqat dA/dr. Vaqt bo‘yicha tezlik uchun dr/dt=2 ga ko‘paytirish kerak.','Write dA/dt=(dA/dr)(dr/dt).','Запишите dA/dt=(dA/dr)(dr/dt).','dA/dt=(dA/dr)(dr/dt) ni yozing.'),
('P1DIF06-D01','C','differentiates_radius_squared_wrong','method','d(r^2)/dt is 2r dr/dt, not r^2 dr/dt.','d(r^2)/dt =2r dr/dt, а не r^2 dr/dt.','d(r^2)/dt =2r dr/dt, r^2 dr/dt emas.','Differentiate with respect to r first, then chain to time.','Сначала дифференцируйте по r, затем примените цепочку по времени.','Avval r bo‘yicha hosila oling, keyin vaqtga chain qo‘llang.'),
('P1DIF06-D01','D','wrong_units','communication','Area changes in square centimetres per second, not centimetres per second.','Площадь изменяется в см^2/с, а не см/с.','Maydon cm^2/s da o‘zgaradi, cm/s da emas.','Track dimensions when reporting a rate.','Проверяйте размерность при записи скорости изменения.','Tezlikni yozganda o‘lchov birliklarini tekshiring.'),
('P1DIF07-D01','B','reverses_second_derivative','concept','f′′<0 means local maximum and f′′>0 means local minimum, not the reverse.','f′′<0 означает локальный максимум, f′′>0 — минимум, а не наоборот.','f′′<0 lokal maksimum, f′′>0 lokal minimumni bildiradi.','Evaluate f′′ at each stationary x separately.','Вычисляйте f′′ отдельно в каждой стационарной точке.','Har bir statsionar x da f′′ ni alohida hisoblang.'),
('P1DIF07-D01','C','same_nature_both','concept','The second derivative has opposite signs at x=0 and x=2, so the stationary points have different natures.','Вторая производная имеет разные знаки при x=0 и x=2, поэтому типы точек различны.','Ikkinchi hosila x=0 va x=2 da qarama-qarshi ishorali, nuqtalar turi turlicha.','Do not classify before substituting each stationary value into f′′.','Не классифицируйте точки до подстановки каждого значения в f′′.','Har bir statsionar qiymatni f′′ ga qo‘ymasdan tasniflamang.'),
('P1DIF07-D01','D','solves_derivative_incorrectly','method','f′=3x(x−2)=0 has two roots, x=0 and x=2; x=1 is not stationary.','f′=3x(x−2)=0 имеет корни 0 и 2; x=1 не стационарная точка.','f′=3x(x−2)=0 ildizlari 0 va 2; x=1 statsionar emas.','Factor f′ fully before solving.','Полностью разложите f′ на множители перед решением.','f′ ni yechishdan oldin to‘liq faktorlash.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_diff_apps_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1DIF05-W01','P1-DIF-05','For f(x)=x^3−3x^2−9x+5, find all stationary x-values and determine the intervals where f is increasing and decreasing. Present a derivative sign chart and explain every sign change.','Для f(x)=x^3−3x^2−9x+5 найдите все стационарные x и интервалы возрастания/убывания. Представьте таблицу знаков производной и объясните изменения знака.','f(x)=x^3−3x^2−9x+5 uchun barcha statsionar x larni va o‘sish/kamayish oraliqlarini toping. Hosila ishora jadvalini ko‘rsating.','{"max_marks":10,"criteria":[{"id":"derivative","marks":2,"rule":"Gets f′=3(x−3)(x+1)."},{"id":"critical","marks":2,"rule":"Gets x=−1 and 3."},{"id":"increasing","marks":2,"rule":"Gets x<−1 and x>3."},{"id":"decreasing","marks":2,"rule":"Gets −1<x<3."},{"id":"sign_chart","marks":2,"rule":"Shows consistent sign evidence across all three intervals."}]}','Factor the derivative first; then test one value per interval rather than guessing from the graph.','Сначала разложите производную; затем проверяйте по одной точке в каждом интервале.','Avval hosilani faktorlash; keyin har bir oraliqda bitta qiymatni tekshiring.'),
('P1DIF06-W01','P1-DIF-06','A spherical balloon has radius r cm and volume V=4pi r^3/3. Its volume increases at 100pi cm^3/s. Find dr/dt when r=5 cm, then find the rate of change of its surface area S=4pi r^2 at that instant. Include units and signs.','Сферический шар имеет радиус r см и объём V=4pi r^3/3. Объём растёт со скоростью 100pi см^3/с. Найдите dr/dt при r=5 см, затем скорость изменения площади S=4pi r^2 в этот момент. Укажите единицы и знаки.','Sferik shar radiusi r cm, V=4pi r^3/3. Hajm 100pi cm^3/s tezlikda oshadi. r=5 cm da dr/dt ni, so‘ng S=4pi r^2 yuzaning o‘zgarish tezligini toping. Birlik va ishoralarni yozing.','{"max_marks":11,"criteria":[{"id":"volume_chain","marks":3,"rule":"Uses dV/dt=4pi r^2 dr/dt."},{"id":"radius_rate","marks":2,"rule":"Gets dr/dt=1 cm/s at r=5."},{"id":"surface_chain","marks":3,"rule":"Uses dS/dt=8pi r dr/dt."},{"id":"surface_rate","marks":2,"rule":"Gets dS/dt=40pi cm^2/s."},{"id":"units","marks":1,"rule":"Reports correct positive signs and units."}]}','Write one chain equation for each dependent quantity before substituting numbers.','Сначала запишите цепное равенство для каждой зависимой величины, потом подставляйте числа.','Har bir bog‘liq kattalik uchun avval chain tenglamani yozing, keyin sonlarni qo‘ying.'),
('P1DIF07-W01','P1-DIF-07','A rectangle has perimeter 40 cm. Let one side be x cm. Express its area as a function of x, find the stationary point, prove it is a maximum, and state the rectangle dimensions and maximum area.','Прямоугольник имеет периметр 40 см. Пусть одна сторона x см. Выразите площадь через x, найдите стационарную точку, докажите максимум и укажите размеры и максимальную площадь.','To‘g‘ri to‘rtburchak perimetri 40 cm. Bir tomoni x cm. Maydonni x orqali yozing, statsionar nuqtani toping, maksimum ekanini isbotlang va o‘lchamlar hamda maksimal maydonni ayting.','{"max_marks":10,"criteria":[{"id":"model","marks":2,"rule":"Gets other side 20−x and A=x(20−x)."},{"id":"stationary","marks":2,"rule":"Gets A′=20−2x=0 -> x=10."},{"id":"nature","marks":2,"rule":"Uses A′′=−2<0 or valid sign change to prove maximum."},{"id":"dimensions","marks":2,"rule":"Gets 10 cm by 10 cm."},{"id":"area","marks":2,"rule":"Gets maximum area 100 cm^2."}]}','Convert the constraint to a one-variable objective before differentiating.','Сначала сведите ограничение к функции одной переменной, затем дифференцируйте.','Avval cheklovni bir o‘zgaruvchili maqsad funksiyasiga aylantiring, keyin hosila oling.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_diff_apps_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw21_diff_apps_diagnostic','diagnostic','P1 AW21-24 Differentiation applications diagnostic','Диагностика P1 AW21–24: применения производной','P1 AW21–24 hosila qo‘llanishi diagnostikasi'),
('p1_dif05_learning','learning','Monotonic intervals learning','Интервалы монотонности: обучение','Monoton oraliqlar: o‘rganish'),('p1_dif06_learning','learning','Rates of change learning','Скорости изменения: обучение','O‘zgarish tezligi: o‘rganish'),('p1_dif07_learning','learning','Stationary points and optimisation learning','Стационарные точки и оптимизация: обучение','Statsionar nuqtalar va optimizatsiya: o‘rganish'),
('p1_dif05_retest','retest','DIF-05 delayed retest','DIF-05 отложенный ретест','DIF-05 kechiktirilgan retest'),('p1_dif06_retest','retest','DIF-06 delayed retest','DIF-06 отложенный ретест','DIF-06 kechiktirilgan retest'),('p1_dif07_retest','retest','DIF-07 delayed retest','DIF-07 отложенный ретест','DIF-07 kechiktirilgan retest'),
('p1_aw21_diff_apps_mixed','mixed','P1 AW21-24 Differentiation applications mixed transfer','P1 AW21–24: смешанный перенос применений производной','P1 AW21–24 hosila qo‘llanishi mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz) select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_diff_apps_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw21_diff_apps_diagnostic',1,'P1DIF05-D01',null,'P1-DIF-05','diagnostic',true),('p1_aw21_diff_apps_diagnostic',2,'P1DIF06-D01',null,'P1-DIF-06','diagnostic',true),('p1_aw21_diff_apps_diagnostic',3,'P1DIF07-D01',null,'P1-DIF-07','diagnostic',true),
('p1_dif05_learning',1,'P1DIF05-L01',null,'P1-DIF-05','learning',false),('p1_dif05_learning',2,'P1DIF05-L02',null,'P1-DIF-05','learning',false),('p1_dif05_learning',3,'P1DIF05-L03',null,'P1-DIF-05','learning',false),('p1_dif05_learning',4,null,'P1DIF05-W01','P1-DIF-05','written',false),
('p1_dif06_learning',1,'P1DIF06-L01',null,'P1-DIF-06','learning',false),('p1_dif06_learning',2,'P1DIF06-L02',null,'P1-DIF-06','learning',false),('p1_dif06_learning',3,'P1DIF06-L03',null,'P1-DIF-06','learning',false),('p1_dif06_learning',4,null,'P1DIF06-W01','P1-DIF-06','written',false),
('p1_dif07_learning',1,'P1DIF07-L01',null,'P1-DIF-07','learning',false),('p1_dif07_learning',2,'P1DIF07-L02',null,'P1-DIF-07','learning',false),('p1_dif07_learning',3,'P1DIF07-L03',null,'P1-DIF-07','learning',false),('p1_dif07_learning',4,null,'P1DIF07-W01','P1-DIF-07','written',false),
('p1_dif05_retest',1,'P1DIF05-R01',null,'P1-DIF-05','retest',true),('p1_dif06_retest',1,'P1DIF06-R01',null,'P1-DIF-06','retest',true),('p1_dif07_retest',1,'P1DIF07-R01',null,'P1-DIF-07','retest',true),
('p1_aw21_diff_apps_mixed',1,'P1DIF05-M01',null,'P1-DIF-05','mixed',true),('p1_aw21_diff_apps_mixed',2,'P1DIF06-M01',null,'P1-DIF-06','mixed',true),('p1_aw21_diff_apps_mixed',3,'P1DIF07-M01',null,'P1-DIF-07','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout) select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_diff_apps_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw21_24_diff_apps_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_diff_apps_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw21_24_diff_apps_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw21_24_diff_apps_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw21_24_diff_apps_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'; foreach v_skill in array array['P1-DIF-05','P1-DIF-06','P1-DIF-07'] loop if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 differentiation application skill not ready %',v_skill; end if; end loop; if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw21_24_diff_apps_v1:%' and is_active) then raise exception 'P1 differentiation legacy activation residue'; end if; if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P1 differentiation publication escaped fail-closed'; end if; if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 differentiation active entitlement residue'; end if; end $$;
commit;
