-- P1-02 original iClub E2 bridge content: P1-FUN-06/07/08.
-- Per skill: 1 diagnostic + 3 learning + 2 delayed-retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p1_e2_functions_bridge_v1' and component_code='P1' and status='draft'
), src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
-- P1-FUN-06: translations
('P1-FUN-06','P1FUN06-D01','diagnostic','medium','The point (2, 5) lies on y = f(x). Which point lies on y = f(x − 3) + 4?','Точка (2, 5) лежит на y = f(x). Какая точка лежит на y = f(x − 3) + 4?','(2, 5) nuqta y = f(x) da yotadi. y = f(x − 3) + 4 da qaysi nuqta yotadi?','["(5, 9)","(-1, 9)","(5, 1)","(-1, 1)"]','["(5, 9)","(-1, 9)","(5, 1)","(-1, 1)"]','["(5, 9)","(-1, 9)","(5, 1)","(-1, 1)"]','A','Replacing x by x − 3 moves the graph 3 units right, and +4 moves it 4 units up. So (2,5) maps to (5,9).','Замена x на x − 3 сдвигает график на 3 вправо, а +4 — на 4 вверх. Поэтому (2,5) переходит в (5,9).','x ni x − 3 ga almashtirish grafikni 3 birlik o‘ngga, +4 esa 4 birlik yuqoriga siljitadi. Shuning uchun (2,5) → (5,9).',85),
('P1-FUN-06','P1FUN06-L01','learning','easy','What transformation takes y = f(x) to y = f(x) + 2?','Какое преобразование переводит y = f(x) в y = f(x) + 2?','y = f(x) dan y = f(x) + 2 ga qaysi o‘zgarish olib boradi?','["Translation 2 units up","Translation 2 units down","Translation 2 units right","Reflection in the x-axis"]','["Сдвиг на 2 вверх","Сдвиг на 2 вниз","Сдвиг на 2 вправо","Отражение относительно оси x"]','["2 birlik yuqoriga siljish","2 birlik pastga siljish","2 birlik o‘ngga siljish","x o‘qiga nisbatan akslantirish"]','A','Adding 2 outside the function increases every y-coordinate by 2.','Прибавление 2 снаружи функции увеличивает каждую y-координату на 2.','Funksiyadan tashqarida 2 qo‘shish har bir y-koordinatani 2 ga oshiradi.',50),
('P1-FUN-06','P1FUN06-L02','learning','easy','What transformation takes y = f(x) to y = f(x − 4)?','Какое преобразование переводит y = f(x) в y = f(x − 4)?','y = f(x) dan y = f(x − 4) ga qaysi o‘zgarish olib boradi?','["Translation 4 units right","Translation 4 units left","Translation 4 units up","Vertical stretch factor 4"]','["Сдвиг на 4 вправо","Сдвиг на 4 влево","Сдвиг на 4 вверх","Вертикальное растяжение в 4 раза"]','["4 birlik o‘ngga siljish","4 birlik chapga siljish","4 birlik yuqoriga siljish","4 marta vertikal cho‘zish"]','A','For y = f(x − a), the same input value of f occurs when x is a units larger, so the graph shifts right by a.','Для y = f(x − a) прежнее значение аргумента f достигается при x на a больше, поэтому график сдвигается вправо на a.','y = f(x − a) da f ning eski argumenti x a birlik kattaroq bo‘lganda hosil bo‘ladi, shuning uchun grafik a birlik o‘ngga siljiydi.',55),
('P1-FUN-06','P1FUN06-L03','learning','medium','The point (−1, 3) lies on y = f(x). Where does it move on y = f(x + 2) − 5?','Точка (−1, 3) лежит на y = f(x). Куда она перейдёт на y = f(x + 2) − 5?','(−1, 3) nuqta y = f(x) da yotadi. y = f(x + 2) − 5 da u qayerga o‘tadi?','["(−3, −2)","(1, −2)","(−3, 8)","(1, 8)"]','["(−3, −2)","(1, −2)","(−3, 8)","(1, 8)"]','["(−3, −2)","(1, −2)","(−3, 8)","(1, 8)"]','A','x + 2 shifts left by 2 and −5 shifts down by 5: (−1,3) maps to (−3,−2).','x + 2 сдвигает на 2 влево, а −5 — на 5 вниз: (−1,3) переходит в (−3,−2).','x + 2 grafikni 2 birlik chapga, −5 esa 5 birlik pastga siljitadi: (−1,3) → (−3,−2).',70),
('P1-FUN-06','P1FUN06-R01','retest','easy','The graph y = f(x) − 7 is obtained from y = f(x) by:','График y = f(x) − 7 получается из y = f(x) с помощью:','y = f(x) − 7 grafigi y = f(x) dan qanday hosil qilinadi?','["a translation 7 units down","a translation 7 units up","a translation 7 units left","a reflection in the y-axis"]','["сдвига на 7 вниз","сдвига на 7 вверх","сдвига на 7 влево","отражения относительно оси y"]','["7 birlik pastga siljish","7 birlik yuqoriga siljish","7 birlik chapga siljish","y o‘qiga nisbatan akslantirish"]','A','Subtracting 7 outside f lowers every output by 7.','Вычитание 7 снаружи f уменьшает каждое значение функции на 7.','f dan tashqarida 7 ayirish har bir chiqish qiymatini 7 ga kamaytiradi.',50),
('P1-FUN-06','P1FUN06-R02','retest','easy','The graph y = f(x + 5) is y = f(x) translated:','График y = f(x + 5) — это y = f(x), сдвинутый:','y = f(x + 5) grafigi y = f(x) ning qaysi siljishi?','["5 units left","5 units right","5 units up","5 units down"]','["на 5 влево","на 5 вправо","на 5 вверх","на 5 вниз"]','["5 birlik chapga","5 birlik o‘ngga","5 birlik yuqoriga","5 birlik pastga"]','A','An addition inside the input produces the opposite horizontal direction: x + 5 shifts the graph left by 5.','Прибавление внутри аргумента даёт противоположное горизонтальное направление: x + 5 сдвигает график на 5 влево.','Argument ichidagi qo‘shish gorizontal yo‘nalishni teskarisiga beradi: x + 5 grafikni 5 birlik chapga siljitadi.',55),
('P1-FUN-06','P1FUN06-M01','mixed','medium','The point (3, −2) lies on y = f(x). Which point lies on y = f(x − 1) + 6?','Точка (3, −2) лежит на y = f(x). Какая точка лежит на y = f(x − 1) + 6?','(3, −2) nuqta y = f(x) da yotadi. y = f(x − 1) + 6 da qaysi nuqta yotadi?','["(4, 4)","(2, 4)","(4, −8)","(2, −8)"]','["(4, 4)","(2, 4)","(4, −8)","(2, −8)"]','["(4, 4)","(2, 4)","(4, −8)","(2, −8)"]','A','The graph moves 1 right and 6 up, so (3,−2) maps to (4,4).','График сдвигается на 1 вправо и на 6 вверх, поэтому (3,−2) переходит в (4,4).','Grafik 1 birlik o‘ngga va 6 birlik yuqoriga siljiydi, shuning uchun (3,−2) → (4,4).',75),

-- P1-FUN-07: reflections
('P1-FUN-07','P1FUN07-D01','diagnostic','medium','The point (2, −3) lies on y = f(x). Which point lies on y = −f(x)?','Точка (2, −3) лежит на y = f(x). Какая точка лежит на y = −f(x)?','(2, −3) nuqta y = f(x) da yotadi. y = −f(x) da qaysi nuqta yotadi?','["(2, 3)","(−2, −3)","(−2, 3)","(3, 2)"]','["(2, 3)","(−2, −3)","(−2, 3)","(3, 2)"]','["(2, 3)","(−2, −3)","(−2, 3)","(3, 2)"]','A','Multiplying the output by −1 reflects the graph in the x-axis: (x,y) maps to (x,−y).','Умножение значения функции на −1 отражает график относительно оси x: (x,y) переходит в (x,−y).','Chiqish qiymatini −1 ga ko‘paytirish grafikni x o‘qiga nisbatan akslantiradi: (x,y) → (x,−y).',70),
('P1-FUN-07','P1FUN07-L01','learning','easy','Which expression reflects y = f(x) in the y-axis?','Какое выражение отражает y = f(x) относительно оси y?','Qaysi ifoda y = f(x) ni y o‘qiga nisbatan akslantiradi?','["y = f(−x)","y = −f(x)","y = f(x) + 1","y = f(x − 1)"]','["y = f(−x)","y = −f(x)","y = f(x) + 1","y = f(x − 1)"]','["y = f(−x)","y = −f(x)","y = f(x) + 1","y = f(x − 1)"]','A','Replacing x by −x reverses x-coordinates while leaving y-coordinates unchanged, which is reflection in the y-axis.','Замена x на −x меняет знак x-координат и сохраняет y-координаты, то есть отражает относительно оси y.','x ni −x ga almashtirish x-koordinatalar ishorasini o‘zgartirib, y-koordinatalarni saqlaydi; bu y o‘qiga nisbatan akslantirishdir.',55),
('P1-FUN-07','P1FUN07-L02','learning','medium','The point (−4, 5) lies on y = f(x). Where is the corresponding point on y = f(−x)?','Точка (−4, 5) лежит на y = f(x). Где соответствующая точка на y = f(−x)?','(−4, 5) nuqta y = f(x) da yotadi. y = f(−x) da mos nuqta qayerda?','["(4, 5)","(−4, −5)","(4, −5)","(5, −4)"]','["(4, 5)","(−4, −5)","(4, −5)","(5, −4)"]','["(4, 5)","(−4, −5)","(4, −5)","(5, −4)"]','A','Reflection in the y-axis changes (x,y) to (−x,y).','Отражение относительно оси y переводит (x,y) в (−x,y).','y o‘qiga nisbatan akslantirish (x,y) ni (−x,y) ga o‘tkazadi.',55),
('P1-FUN-07','P1FUN07-L03','learning','medium','What is the combined effect of y = −f(−x) on the graph y = f(x)?','Каков общий эффект преобразования y = −f(−x) для графика y = f(x)?','y = −f(−x) o‘zgarishi y = f(x) grafigiga qanday umumiy ta’sir qiladi?','["Reflection in both coordinate axes","Translation right then up","Vertical stretch only","Reflection in the line y = x"]','["Отражение относительно обеих координатных осей","Сдвиг вправо, затем вверх","Только вертикальное растяжение","Отражение относительно прямой y = x"]','["Ikkala koordinata o‘qiga nisbatan akslantirish","O‘ngga, so‘ng yuqoriga siljish","Faqat vertikal cho‘zish","y = x chizig‘iga nisbatan akslantirish"]','A','f(−x) reflects in the y-axis, and the outside minus then reflects in the x-axis.','f(−x) отражает относительно оси y, а внешний минус затем отражает относительно оси x.','f(−x) y o‘qiga nisbatan, tashqi minus esa keyin x o‘qiga nisbatan akslantiradi.',65),
('P1-FUN-07','P1FUN07-R01','retest','easy','If (3, 1) is on y = f(x), which point is on y = −f(x)?','Если (3, 1) лежит на y = f(x), какая точка лежит на y = −f(x)?','Agar (3, 1) y = f(x) da yotsa, y = −f(x) da qaysi nuqta yotadi?','["(3, −1)","(−3, 1)","(−3, −1)","(1, 3)"]','["(3, −1)","(−3, 1)","(−3, −1)","(1, 3)"]','["(3, −1)","(−3, 1)","(−3, −1)","(1, 3)"]','A','Reflection in the x-axis keeps x and changes the sign of y.','Отражение относительно оси x сохраняет x и меняет знак y.','x o‘qiga nisbatan akslantirish x ni saqlab, y ishorasini o‘zgartiradi.',50),
('P1-FUN-07','P1FUN07-R02','retest','easy','If (−2, −6) is on y = f(x), which point is on y = f(−x)?','Если (−2, −6) лежит на y = f(x), какая точка лежит на y = f(−x)?','Agar (−2, −6) y = f(x) da yotsa, y = f(−x) da qaysi nuqta yotadi?','["(2, −6)","(−2, 6)","(2, 6)","(−6, 2)"]','["(2, −6)","(−2, 6)","(2, 6)","(−6, 2)"]','["(2, −6)","(−2, 6)","(2, 6)","(−6, 2)"]','A','Reflection in the y-axis changes only the sign of x.','Отражение относительно оси y меняет только знак x.','y o‘qiga nisbatan akslantirish faqat x ishorasini o‘zgartiradi.',50),
('P1-FUN-07','P1FUN07-M01','mixed','medium','The point (5, −4) lies on y = f(x). Which point lies on y = −f(−x)?','Точка (5, −4) лежит на y = f(x). Какая точка лежит на y = −f(−x)?','(5, −4) nuqta y = f(x) da yotadi. y = −f(−x) da qaysi nuqta yotadi?','["(−5, 4)","(5, 4)","(−5, −4)","(4, −5)"]','["(−5, 4)","(5, 4)","(−5, −4)","(4, −5)"]','["(−5, 4)","(5, 4)","(−5, −4)","(4, −5)"]','A','The inside minus changes x to −x and the outside minus changes y to −y, so (5,−4) maps to (−5,4).','Внутренний минус меняет x на −x, а внешний — y на −y, поэтому (5,−4) переходит в (−5,4).','Ichki minus x ni −x ga, tashqi minus y ni −y ga o‘zgartiradi, shuning uchun (5,−4) → (−5,4).',70),

-- P1-FUN-08: stretches/compressions and combinations
('P1-FUN-08','P1FUN08-D01','diagnostic','hard','The point (4, 3) lies on y = f(x). Which point lies on y = 2f(2x)?','Точка (4, 3) лежит на y = f(x). Какая точка лежит на y = 2f(2x)?','(4, 3) nuqta y = f(x) da yotadi. y = 2f(2x) da qaysi nuqta yotadi?','["(2, 6)","(8, 6)","(2, 1.5)","(8, 1.5)"]','["(2, 6)","(8, 6)","(2, 1.5)","(8, 1.5)"]','["(2, 6)","(8, 6)","(2, 1.5)","(8, 1.5)"]','A','For f(2x), x-coordinates are divided by 2; the outside factor 2 doubles y-coordinates. Thus (4,3) maps to (2,6).','Для f(2x) x-координаты делятся на 2; внешний множитель 2 удваивает y-координаты. Поэтому (4,3) переходит в (2,6).','f(2x) da x-koordinatalar 2 ga bo‘linadi; tashqi 2 y-koordinatalarni ikki baravar qiladi. Demak (4,3) → (2,6).',90),
('P1-FUN-08','P1FUN08-L01','learning','easy','What transformation takes y = f(x) to y = 3f(x)?','Какое преобразование переводит y = f(x) в y = 3f(x)?','y = f(x) dan y = 3f(x) ga qaysi o‘zgarish olib boradi?','["Vertical stretch by factor 3","Horizontal stretch by factor 3","Translation 3 units up","Reflection in the x-axis"]','["Вертикальное растяжение в 3 раза","Горизонтальное растяжение в 3 раза","Сдвиг на 3 вверх","Отражение относительно оси x"]','["3 marta vertikal cho‘zish","3 marta gorizontal cho‘zish","3 birlik yuqoriga siljish","x o‘qiga nisbatan akslantirish"]','A','Multiplying f(x) by 3 triples every y-coordinate while x-coordinates stay fixed.','Умножение f(x) на 3 утраивает каждую y-координату, а x-координаты не меняются.','f(x) ni 3 ga ko‘paytirish har bir y-koordinatani uch baravar qiladi, x esa o‘zgarmaydi.',55),
('P1-FUN-08','P1FUN08-L02','learning','medium','What is the horizontal scale effect of y = f(4x) compared with y = f(x)?','Как изменяется горизонтальный масштаб y = f(4x) по сравнению с y = f(x)?','y = f(4x) ning gorizontal masshtabi y = f(x) ga nisbatan qanday o‘zgaradi?','["Compressed by scale factor 1/4","Stretched by scale factor 4","Compressed by scale factor 4","Unchanged horizontally"]','["Сжат в 4 раза (масштаб 1/4)","Растянут в 4 раза","Сжат с масштабом 4","По горизонтали не меняется"]','["1/4 masshtab bilan siqiladi","4 marta cho‘ziladi","4 masshtab bilan siqiladi","Gorizontal o‘zgarmaydi"]','A','To obtain the same original input u, 4x=u gives x=u/4, so every x-coordinate is divided by 4.','Чтобы получить прежний аргумент u, из 4x=u получаем x=u/4, поэтому каждая x-координата делится на 4.','Eski u argumentni olish uchun 4x=u dan x=u/4 bo‘ladi, shuning uchun har bir x-koordinata 4 ga bo‘linadi.',65),
('P1-FUN-08','P1FUN08-L03','learning','medium','The point (−2, 5) lies on y = f(x). Which point lies on y = f(x/2)?','Точка (−2, 5) лежит на y = f(x). Какая точка лежит на y = f(x/2)?','(−2, 5) nuqta y = f(x) da yotadi. y = f(x/2) da qaysi nuqta yotadi?','["(−4, 5)","(−1, 5)","(−4, 2.5)","(−1, 10)"]','["(−4, 5)","(−1, 5)","(−4, 2.5)","(−1, 10)"]','["(−4, 5)","(−1, 5)","(−4, 2.5)","(−1, 10)"]','A','For f(x/2), x/2 must equal the old x-value. So x-coordinates double while y stays unchanged.','Для f(x/2) величина x/2 должна равняться прежнему x. Поэтому x-координаты удваиваются, а y не меняется.','f(x/2) da x/2 eski x qiymatiga teng bo‘lishi kerak. Shuning uchun x-koordinatalar ikki baravar bo‘ladi, y o‘zgarmaydi.',70),
('P1-FUN-08','P1FUN08-R01','retest','easy','If (6, −2) lies on y = f(x), which point lies on y = 0.5f(x)?','Если (6, −2) лежит на y = f(x), какая точка лежит на y = 0.5f(x)?','Agar (6, −2) y = f(x) da yotsa, y = 0.5f(x) da qaysi nuqta yotadi?','["(6, −1)","(3, −2)","(12, −2)","(6, −4)"]','["(6, −1)","(3, −2)","(12, −2)","(6, −4)"]','["(6, −1)","(3, −2)","(12, −2)","(6, −4)"]','A','The outside factor 0.5 halves y-coordinates and leaves x-coordinates unchanged.','Внешний множитель 0,5 делит y-координаты пополам и не меняет x.','Tashqi 0.5 ko‘paytuvchi y-koordinatalarni yarmiga tushiradi, x ni o‘zgartirmaydi.',55),
('P1-FUN-08','P1FUN08-R02','retest','medium','If (8, 3) lies on y = f(x), which point lies on y = f(2x)?','Если (8, 3) лежит на y = f(x), какая точка лежит на y = f(2x)?','Agar (8, 3) y = f(x) da yotsa, y = f(2x) da qaysi nuqta yotadi?','["(4, 3)","(16, 3)","(8, 6)","(8, 1.5)"]','["(4, 3)","(16, 3)","(8, 6)","(8, 1.5)"]','["(4, 3)","(16, 3)","(8, 6)","(8, 1.5)"]','A','For f(2x), the new x-coordinate is half the old one; the y-coordinate is unchanged.','Для f(2x) новая x-координата равна половине старой, а y не меняется.','f(2x) da yangi x-koordinata eski qiymatning yarmi bo‘ladi, y o‘zgarmaydi.',60),
('P1-FUN-08','P1FUN08-M01','mixed','hard','The point (6, −1) lies on y = f(x). Which point lies on y = 3f(2(x − 1)) + 5?','Точка (6, −1) лежит на y = f(x). Какая точка лежит на y = 3f(2(x − 1)) + 5?','(6, −1) nuqta y = f(x) da yotadi. y = 3f(2(x − 1)) + 5 da qaysi nuqta yotadi?','["(4, 2)","(13, 2)","(4, −8)","(2, 2)"]','["(4, 2)","(13, 2)","(4, −8)","(2, 2)"]','["(4, 2)","(13, 2)","(4, −8)","(2, 2)"]','A','Set 2(x−1)=6, giving x=4. The output becomes 3(−1)+5=2, so the mapped point is (4,2).','Положим 2(x−1)=6, тогда x=4. Выход равен 3(−1)+5=2, поэтому точка переходит в (4,2).','2(x−1)=6 deb olsak, x=4. Chiqish 3(−1)+5=2 bo‘ladi, demak nuqta (4,2) ga o‘tadi.',90)
)
insert into public.questions(
  subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,
  question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,
  explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status
)
select 5,'P1 Functions transformations',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,
       s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,
       'ExamPrep:P1:p1_e2_functions_bridge_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_e2_functions_bridge_v1:'||s.k);

with cv as (
  select id from private.exam_prep_content_versions
  where content_version='p1_e2_functions_bridge_v1' and component_code='P1' and status='draft'
), keys(skill,k,role) as (values
('P1-FUN-06','P1FUN06-D01','diagnostic'),('P1-FUN-06','P1FUN06-L01','learning'),('P1-FUN-06','P1FUN06-L02','learning'),('P1-FUN-06','P1FUN06-L03','learning'),('P1-FUN-06','P1FUN06-R01','retest'),('P1-FUN-06','P1FUN06-R02','retest'),('P1-FUN-06','P1FUN06-M01','mixed'),
('P1-FUN-07','P1FUN07-D01','diagnostic'),('P1-FUN-07','P1FUN07-L01','learning'),('P1-FUN-07','P1FUN07-L02','learning'),('P1-FUN-07','P1FUN07-L03','learning'),('P1-FUN-07','P1FUN07-R01','retest'),('P1-FUN-07','P1FUN07-R02','retest'),('P1-FUN-07','P1FUN07-M01','mixed'),
('P1-FUN-08','P1FUN08-D01','diagnostic'),('P1-FUN-08','P1FUN08-L01','learning'),('P1-FUN-08','P1FUN08-L02','learning'),('P1-FUN-08','P1FUN08-L03','learning'),('P1-FUN-08','P1FUN08-R01','retest'),('P1-FUN-08','P1FUN08-R02','retest'),('P1-FUN-08','P1FUN08-M01','mixed')
)
insert into private.exam_prep_question_content_meta(
  content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,
  originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,
  copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5
)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft',
       'Original iClub-authored stem, distractors, answer and explanation; no Cambridge/coursebook wording copied.',
       'Authored for p1_e2_functions_bridge_v1 from the canonical transformation skill intent using independent point-mapping examples.',
       'Cambridge 9709 2026-2027 v4; P1 1.2 Functions',
       'Complete Pure Mathematics 1, Ch2 Functions and transformations pp.24-42 (mapping only)',
       'pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
       md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k
join public.questions q on q.book_ref='ExamPrep:P1:p1_e2_functions_bridge_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

-- Draft structure only; no release before diagnostic/written/assessment QA layers.
do $$ declare v_id bigint; begin
  select id into v_id from private.exam_prep_content_versions where content_version='p1_e2_functions_bridge_v1';
  if (select count(*) from private.exam_prep_question_content_meta where content_version_id=v_id)<>21 then
    raise exception 'P1-02 E2 functions bridge expected 21 question objects';
  end if;
  if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_e2_functions_bridge_v1:%' and is_active) then
    raise exception 'P1-02 E2 bridge question leaked into legacy active state';
  end if;
end $$;
commit;
