-- AI-4 Economics Practice 1 precise source pack: Chapter 1.
-- Original iClub summaries grounded in the approved Economics coursebook.
-- Exact topic+subtopic cards improve source precision only; no diagnosis or AI enablement.

insert into private.practice_ai_source_cards(
  source_card_key,subject_key,question_id,topic,subtopic,card_type,locale,source_version,
  title,body_text,approval_status,rights_status,is_runtime_allowed,content_hash,approved_at,updated_at
)
values
('practice:economics:p1:precise:income-from-factors:en:v1','economics',null,'Basics','Income from factors of production','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Factor rewards','The four factors of production receive different rewards: land earns rent, labour earns wages, capital earns interest and enterprise earns profit.','approved','original_iclub',true,encode(digest(convert_to('The four factors of production receive different rewards: land earns rent, labour earns wages, capital earns interest and enterprise earns profit.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:income-from-factors:ru:v1','economics',null,'Basics','Income from factors of production','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Доходы факторов производства','Четыре фактора производства получают разные виды дохода: земля — ренту, труд — заработную плату, капитал — процент, предпринимательство — прибыль.','approved','original_iclub',true,encode(digest(convert_to('Четыре фактора производства получают разные виды дохода: земля — ренту, труд — заработную плату, капитал — процент, предпринимательство — прибыль.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:income-from-factors:uz:v1','economics',null,'Basics','Income from factors of production','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Ishlab chiqarish omillari daromadi','To‘rtta ishlab chiqarish omili turli daromad oladi: yer — renta, mehnat — ish haqi, kapital — foiz, tadbirkorlik — foyda.','approved','original_iclub',true,encode(digest(convert_to('To‘rtta ishlab chiqarish omili turli daromad oladi: yer — renta, mehnat — ish haqi, kapital — foiz, tadbirkorlik — foyda.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:opportunity-cost:en:v1','economics',null,'Basics','Opportunity cost','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Opportunity cost','Opportunity cost is the next best alternative that is given up when a choice is made. It is measured by the value of the best forgone option, not by every alternative that was possible.','approved','original_iclub',true,encode(digest(convert_to('Opportunity cost is the next best alternative that is given up when a choice is made. It is measured by the value of the best forgone option, not by every alternative that was possible.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:opportunity-cost:ru:v1','economics',null,'Basics','Opportunity cost','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Альтернативная стоимость','Альтернативная стоимость — это лучшая из альтернатив, от которой приходится отказаться при выборе. Она определяется ценностью лучшего упущенного варианта, а не суммой всех возможных альтернатив.','approved','original_iclub',true,encode(digest(convert_to('Альтернативная стоимость — это лучшая из альтернатив, от которой приходится отказаться при выборе. Она определяется ценностью лучшего упущенного варианта, а не суммой всех возможных альтернатив.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:opportunity-cost:uz:v1','economics',null,'Basics','Opportunity cost','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Muqobil xarajat','Muqobil xarajat — tanlov qilinganda voz kechilgan eng yaxshi keyingi imkoniyat. U barcha mumkin bo‘lgan variantlar bilan emas, aynan eng yaxshi voz kechilgan variant qiymati bilan o‘lchanadi.','approved','original_iclub',true,encode(digest(convert_to('Muqobil xarajat — tanlov qilinganda voz kechilgan eng yaxshi keyingi imkoniyat. U barcha mumkin bo‘lgan variantlar bilan emas, aynan eng yaxshi voz kechilgan variant qiymati bilan o‘lchanadi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:basic-economic-problem:en:v1','economics',null,'Basics','The basic economic problem','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','The basic economic problem','Human wants are greater than the scarce resources available to satisfy them. Because resources have alternative uses, scarcity forces individuals, firms and governments to make choices.','approved','original_iclub',true,encode(digest(convert_to('Human wants are greater than the scarce resources available to satisfy them. Because resources have alternative uses, scarcity forces individuals, firms and governments to make choices.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:basic-economic-problem:ru:v1','economics',null,'Basics','The basic economic problem','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Основная экономическая проблема','Желания людей превышают объём ограниченных ресурсов, доступных для их удовлетворения. Поскольку ресурсы можно использовать по-разному, ограниченность заставляет людей, фирмы и государство делать выбор.','approved','original_iclub',true,encode(digest(convert_to('Желания людей превышают объём ограниченных ресурсов, доступных для их удовлетворения. Поскольку ресурсы можно использовать по-разному, ограниченность заставляет людей, фирмы и государство делать выбор.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:basic-economic-problem:uz:v1','economics',null,'Basics','The basic economic problem','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Asosiy iqtisodiy muammo','Inson istaklari ularni qondirish uchun mavjud bo‘lgan cheklangan resurslardan ko‘proq. Resurslardan turli maqsadlarda foydalanish mumkinligi sababli cheklanganlik odamlar, firmalar va davlatni tanlov qilishga majbur qiladi.','approved','original_iclub',true,encode(digest(convert_to('Inson istaklari ularni qondirish uchun mavjud bo‘lgan cheklangan resurslardan ko‘proq. Resurslardan turli maqsadlarda foydalanish mumkinligi sababli cheklanganlik odamlar, firmalar va davlatni tanlov qilishga majbur qiladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:trade-off:en:v1','economics',null,'Basics','Trade-off','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Trade-offs','A trade-off exists when gaining more of one objective or good requires giving up some of another. It arises because scarce resources cannot be used for all alternatives at the same time.','approved','original_iclub',true,encode(digest(convert_to('A trade-off exists when gaining more of one objective or good requires giving up some of another. It arises because scarce resources cannot be used for all alternatives at the same time.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:trade-off:ru:v1','economics',null,'Basics','Trade-off','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Компромисс выбора','Компромисс возникает, когда для получения большего количества одного блага или достижения одной цели приходится отказаться от части другого. Причина в том, что ограниченные ресурсы нельзя одновременно использовать во всех возможных направлениях.','approved','original_iclub',true,encode(digest(convert_to('Компромисс возникает, когда для получения большего количества одного блага или достижения одной цели приходится отказаться от части другого. Причина в том, что ограниченные ресурсы нельзя одновременно использовать во всех возможных направлениях.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:trade-off:uz:v1','economics',null,'Basics','Trade-off','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Tanlovdagi almashinuv','Bir maqsad yoki ne’matdan ko‘proq olish uchun boshqasining bir qismidan voz kechish kerak bo‘lsa, tanlovdagi almashinuv yuz beradi. Buning sababi cheklangan resurslarni bir vaqtning o‘zida barcha yo‘nalishlarda ishlatib bo‘lmasligidir.','approved','original_iclub',true,encode(digest(convert_to('Bir maqsad yoki ne’matdan ko‘proq olish uchun boshqasining bir qismidan voz kechish kerak bo‘lsa, tanlovdagi almashinuv yuz beradi. Buning sababi cheklangan resurslarni bir vaqtning o‘zida barcha yo‘nalishlarda ishlatib bo‘lmasligidir.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:inferior-goods:en:v1','economics',null,'Demand','Inferior goods','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Inferior goods','An inferior good is one for which demand tends to fall when consumer income rises, other things equal, and tends to rise when income falls. Its income elasticity of demand is negative.','approved','original_iclub',true,encode(digest(convert_to('An inferior good is one for which demand tends to fall when consumer income rises, other things equal, and tends to rise when income falls. Its income elasticity of demand is negative.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:inferior-goods:ru:v1','economics',null,'Demand','Inferior goods','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Низшие блага','Низшее благо — это товар, спрос на который при прочих равных обычно снижается при росте дохода потребителей и растёт при снижении дохода. Его эластичность спроса по доходу отрицательна.','approved','original_iclub',true,encode(digest(convert_to('Низшее благо — это товар, спрос на который при прочих равных обычно снижается при росте дохода потребителей и растёт при снижении дохода. Его эластичность спроса по доходу отрицательна.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:inferior-goods:uz:v1','economics',null,'Demand','Inferior goods','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Past toifadagi tovarlar','Past toifadagi tovar — boshqa omillar o‘zgarmaganda iste’molchi daromadi oshsa talabi kamayadigan, daromad pasaysa esa talabi oshadigan tovar. Uning daromad bo‘yicha talab elastikligi manfiy bo‘ladi.','approved','original_iclub',true,encode(digest(convert_to('Past toifadagi tovar — boshqa omillar o‘zgarmaganda iste’molchi daromadi oshsa talabi kamayadigan, daromad pasaysa esa talabi oshadigan tovar. Uning daromad bo‘yicha talab elastikligi manfiy bo‘ladi.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:public-goods:en:v1','economics',null,'Goods','Public goods','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Public goods','A pure public good is non-excludable and non-rival: people cannot easily be prevented from benefiting, and one person’s use does not significantly reduce availability to others. These features can create a free-rider problem and lead to under-provision by markets.','approved','original_iclub',true,encode(digest(convert_to('A pure public good is non-excludable and non-rival: people cannot easily be prevented from benefiting, and one person’s use does not significantly reduce availability to others. These features can create a free-rider problem and lead to under-provision by markets.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:public-goods:ru:v1','economics',null,'Goods','Public goods','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Общественные блага','Чистое общественное благо неисключаемо и неконкурентно: трудно не допустить человека к выгоде от него, а использование одним человеком существенно не уменьшает доступность для других. Эти свойства создают проблему безбилетника и могут приводить к недостаточному рыночному предложению.','approved','original_iclub',true,encode(digest(convert_to('Чистое общественное благо неисключаемо и неконкурентно: трудно не допустить человека к выгоде от него, а использование одним человеком существенно не уменьшает доступность для других. Эти свойства создают проблему безбилетника и могут приводить к недостаточному рыночному предложению.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:public-goods:uz:v1','economics',null,'Goods','Public goods','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Jamoat ne’matlari','Sof jamoat ne’mati cheklab bo‘lmaydigan va raqobatsiz bo‘ladi: odamlarni undan foyda olishdan osonlikcha chetlatib bo‘lmaydi va bir kishining foydalanishi boshqalarga mavjud miqdorni sezilarli kamaytirmaydi. Bu xususiyatlar tekin foydalanuvchi muammosini keltirib chiqarib, bozor tomonidan yetarli taklif qilinmasligiga olib kelishi mumkin.','approved','original_iclub',true,encode(digest(convert_to('Sof jamoat ne’mati cheklab bo‘lmaydigan va raqobatsiz bo‘ladi: odamlarni undan foyda olishdan osonlikcha chetlatib bo‘lmaydi va bir kishining foydalanishi boshqalarga mavjud miqdorni sezilarli kamaytirmaydi. Bu xususiyatlar tekin foydalanuvchi muammosini keltirib chiqarib, bozor tomonidan yetarli taklif qilinmasligiga olib kelishi mumkin.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:needs-and-wants:en:v1','economics',null,'Intro','Needs and wants','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Needs and wants','Needs are goods and services regarded as essential for basic living, while wants are things people would like to have beyond those essentials. Wants can keep expanding, but income and resources are limited.','approved','original_iclub',true,encode(digest(convert_to('Needs are goods and services regarded as essential for basic living, while wants are things people would like to have beyond those essentials. Wants can keep expanding, but income and resources are limited.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:needs-and-wants:ru:v1','economics',null,'Intro','Needs and wants','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Потребности и желания','Потребности — это товары и услуги, считающиеся необходимыми для базовой жизни, а желания — то, что люди хотели бы иметь сверх необходимого. Желания могут постоянно расширяться, но доход и ресурсы ограничены.','approved','original_iclub',true,encode(digest(convert_to('Потребности — это товары и услуги, считающиеся необходимыми для базовой жизни, а желания — то, что люди хотели бы иметь сверх необходимого. Желания могут постоянно расширяться, но доход и ресурсы ограничены.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:needs-and-wants:uz:v1','economics',null,'Intro','Needs and wants','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Ehtiyojlar va istaklar','Ehtiyojlar asosiy hayot uchun zarur deb hisoblanadigan tovar va xizmatlardir, istaklar esa zaruriy narsalardan tashqari odamlar ega bo‘lishni xohlaydigan narsalardir. Istaklar kengayib borishi mumkin, ammo daromad va resurslar cheklangan.','approved','original_iclub',true,encode(digest(convert_to('Ehtiyojlar asosiy hayot uchun zarur deb hisoblanadigan tovar va xizmatlardir, istaklar esa zaruriy narsalardan tashqari odamlar ega bo‘lishni xohlaydigan narsalardir. Istaklar kengayib borishi mumkin, ammo daromad va resurslar cheklangan.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:ppc-opportunity-cost-basic:en:v1','economics',null,'PPC','Opportunity cost','answer_explanation','en','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Opportunity cost on a PPC','On a production possibility curve, increasing production of one good normally requires reducing production of the other. The amount of the other good sacrificed represents the opportunity cost of the extra output.','approved','original_iclub',true,encode(digest(convert_to('On a production possibility curve, increasing production of one good normally requires reducing production of the other. The amount of the other good sacrificed represents the opportunity cost of the extra output.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:ppc-opportunity-cost-basic:ru:v1','economics',null,'PPC','Opportunity cost','answer_explanation','ru','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','Альтернативная стоимость на PPC','На кривой производственных возможностей увеличение выпуска одного блага обычно требует сокращения выпуска другого. Количество другого блага, которым приходится пожертвовать, показывает альтернативную стоимость дополнительного выпуска.','approved','original_iclub',true,encode(digest(convert_to('На кривой производственных возможностей увеличение выпуска одного блага обычно требует сокращения выпуска другого. Количество другого блага, которым приходится пожертвовать, показывает альтернативную стоимость дополнительного выпуска.','UTF8'),'sha256'),'hex'),now(),now()),
('practice:economics:p1:precise:ppc-opportunity-cost-basic:uz:v1','economics',null,'PPC','Opportunity cost','answer_explanation','uz','iclub_practice_ai_economics_p1_precise_ch1_v1_2026_09_25','PPCdagi muqobil xarajat','Ishlab chiqarish imkoniyatlari egri chizig‘ida bir mahsulot ishlab chiqarishni ko‘paytirish odatda boshqa mahsulot ishlab chiqarishni kamaytirishni talab qiladi. Voz kechilgan boshqa mahsulot miqdori qo‘shimcha ishlab chiqarishning muqobil xarajatini ko‘rsatadi.','approved','original_iclub',true,encode(digest(convert_to('Ishlab chiqarish imkoniyatlari egri chizig‘ida bir mahsulot ishlab chiqarishni ko‘paytirish odatda boshqa mahsulot ishlab chiqarishni kamaytirishni talab qiladi. Voz kechilgan boshqa mahsulot miqdori qo‘shimcha ishlab chiqarishning muqobil xarajatini ko‘rsatadi.','UTF8'),'sha256'),'hex'),now(),now())
on conflict(source_card_key) do update
set subject_key=excluded.subject_key,
    question_id=excluded.question_id,
    topic=excluded.topic,
    subtopic=excluded.subtopic,
    card_type=excluded.card_type,
    locale=excluded.locale,
    source_version=excluded.source_version,
    title=excluded.title,
    body_text=excluded.body_text,
    approval_status=excluded.approval_status,
    rights_status=excluded.rights_status,
    is_runtime_allowed=excluded.is_runtime_allowed,
    content_hash=excluded.content_hash,
    approved_at=coalesce(private.practice_ai_source_cards.approved_at,excluded.approved_at),
    updated_at=now();
