-- AI-4 Economics Practice 1 deterministic diagnostic batch: Chapter 10.
-- Adds deterministic diagnostics for seven MCQs and two equilibrium-price numeric inputs.
-- Server scoring remains authoritative; diagnostics only explain the checked result.

do $guard$
declare v_bad integer;
begin
  with expected(question_id,topic,subtopic,qtype,correct_answer,options_en) as (
    values
    (1032,'Equilibrium','Equilibrium price from linear demand and supply','input','10',null::jsonb),
    (1074,'Equilibrium','Surplus','mcq','A','["quantity supplied exceeds quantity demanded","quantity demanded exceeds quantity supplied","price equals zero","demand curve shifts right"]'::jsonb),
    (1075,'Equilibrium','Shortage','mcq','A','["quantity demanded exceeds quantity supplied","quantity supplied exceeds quantity demanded","costs fall","supply shifts right"]'::jsonb),
    (1076,'Equilibrium','Equilibrium price from linear demand and supply','input','15',null::jsonb),
    (1086,'Supply','Subsidy and supply','mcq','A','["shift supply right","shift supply left","shift demand right","cause shortage"]'::jsonb),
    (1088,'Equilibrium','Market equilibrium','mcq','A','["clear (no persistent surplus/shortage)","always have shortage","always have surplus","stop trading"]'::jsonb),
    (1096,'Equilibrium','Price above equilibrium','mcq','A','["surplus","shortage","no effect","higher demand"]'::jsonb),
    (1097,'Equilibrium','Price below equilibrium','mcq','A','["shortage","surplus","no effect","lower supply curve"]'::jsonb),
    (1117,'Equilibrium','Price ceiling and shortage','mcq','A','["Queuing / waiting in line","A higher official equilibrium price","Automatic market clearing","Perfectly elastic supply"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>7
     or q.is_active is not true
     or q.quality_status<>'published'
     or lower(coalesce(q.qtype,''))<>e.qtype
     or q.topic<>e.topic
     or q.subtopic<>e.subtopic
     or upper(trim(coalesce(q.correct_answer,'')))<>upper(e.correct_answer)
     or (e.qtype='mcq' and coalesce(q.options_text_en,'[]')::jsonb is distinct from e.options_en)
     or (e.qtype='input' and q.options_text_en is not null);

  if v_bad<>0 then
    raise exception 'AI-4 diagnostic batch refused: one or more Chapter 10 questions changed';
  end if;

  if exists (
    select 1 from public.question_answer_diagnostics
    where question_id in (1032,1074,1075,1076,1086,1088,1096,1097,1117)
      and quality_status='published'
  ) then
    raise exception 'AI-4 diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
) values
(1032,'input_exact',null,'10',true,null,null,
 'Верно: в равновесии Qd = Qs, поэтому 80 − 2P = 20 + 4P; 60 = 6P; P = 10.',
 'To‘g‘ri: muvozanatda Qd = Qs, shuning uchun 80 − 2P = 20 + 4P; 60 = 6P; P = 10.',
 'Correct: at equilibrium Qd = Qs, so 80 − 2P = 20 + 4P; 60 = 6P; P = 10.',
 'Сначала приравнивайте Qd и Qs, затем решайте уравнение относительно P.',
 'Avval Qd va Qsni tenglashtiring, keyin P bo‘yicha yeching.',
 'Set Qd equal to Qs first, then solve for P.',
 'Equilibrium','Equilibrium price from linear demand and supply','{"accepted":"10"}'::jsonb,'published'),
(1032,'fallback',null,null,false,'equilibrium_equation_error','Solving linear market equilibrium',
 'Для равновесной цены нужно приравнять спрос и предложение: 80 − 2P = 20 + 4P. Отсюда P = 10. Введите только число.',
 'Muvozanat narxini topish uchun talab va taklifni tenglashtiring: 80 − 2P = 20 + 4P. Bundan P = 10. Faqat son kiriting.',
 'To find equilibrium price, set demand equal to supply: 80 − 2P = 20 + 4P. This gives P = 10. Enter only the number.',
 'Повторите алгоритм решения линейного равновесия.',
 'Chiziqli muvozanatni yechish algoritmini takrorlang.',
 'Review the linear-equilibrium solving method.',
 'Equilibrium','Equilibrium price from linear demand and supply','{}'::jsonb,'published'),

(1074,'mcq_option','A','quantity supplied exceeds quantity demanded',true,null,null,
 'Верно: избыток означает, что при текущей цене объём предложения превышает объём спроса.',
 'To‘g‘ri: ortiqcha taklif joriy narxda taklif miqdori talab miqdoridan katta bo‘lishini anglatadi.',
 'Correct: a surplus means quantity supplied exceeds quantity demanded at the current price.',
 'Запомните: surplus = Qs > Qd.',
 'Eslab qoling: surplus = Qs > Qd.',
 'Remember: surplus = Qs > Qd.',
 'Equilibrium','Surplus','{}'::jsonb,'published'),
(1074,'mcq_option','B','quantity demanded exceeds quantity supplied',false,'surplus_shortage_reversal','Surplus vs shortage',
 'Если Qd > Qs, это дефицит, а не избыток.',
 'Agar Qd > Qs bo‘lsa, bu ortiqcha taklif emas, taqchillik.',
 'If Qd > Qs, that is a shortage, not a surplus.',
 'Сравните определения surplus и shortage.',
 'Surplus va shortage ta’riflarini solishtiring.',
 'Compare the definitions of surplus and shortage.',
 'Equilibrium','Surplus','{}'::jsonb,'published'),
(1074,'mcq_option','C','price equals zero',false,'surplus_definition_error','Meaning of surplus',
 'Нулевая цена не определяет избыток. Важно сравнение Qs и Qd при данной цене.',
 'Narxning nol bo‘lishi ortiqcha taklifni ta’riflamaydi. Muhim narsa joriy narxda Qs va Qdni solishtirish.',
 'A zero price does not define a surplus. What matters is comparing Qs and Qd at the current price.',
 'Определяйте избыток через количества, а не через абсолютный уровень цены.',
 'Ortiqcha taklifni narx darajasi emas, miqdorlar orqali aniqlang.',
 'Define surplus using quantities, not the absolute price level.',
 'Equilibrium','Surplus','{}'::jsonb,'published'),
(1074,'mcq_option','D','demand curve shifts right',false,'shift_vs_imbalance_confusion','Market imbalance vs curve shift',
 'Сдвиг спроса вправо может изменить равновесие, но сам по себе не является определением избытка.',
 'Talabning o‘ngga siljishi muvozanatni o‘zgartirishi mumkin, ammo ortiqcha taklifning ta’rifi emas.',
 'A rightward demand shift can change equilibrium, but it is not the definition of a surplus.',
 'Отделяйте причину изменения рынка от состояния Qs > Qd.',
 'Bozor o‘zgarishi sababini Qs > Qd holatidan ajrating.',
 'Separate a market shift from the condition Qs > Qd.',
 'Equilibrium','Surplus','{}'::jsonb,'published'),

(1075,'mcq_option','A','quantity demanded exceeds quantity supplied',true,null,null,
 'Верно: дефицит означает Qd > Qs при текущей цене.',
 'To‘g‘ri: taqchillik joriy narxda Qd > Qs ekanini anglatadi.',
 'Correct: a shortage means Qd > Qs at the current price.',
 'Запомните: shortage = Qd > Qs.',
 'Eslab qoling: shortage = Qd > Qs.',
 'Remember: shortage = Qd > Qs.',
 'Equilibrium','Shortage','{}'::jsonb,'published'),
(1075,'mcq_option','B','quantity supplied exceeds quantity demanded',false,'surplus_shortage_reversal','Shortage vs surplus',
 'Если Qs > Qd, это избыток, а не дефицит.',
 'Agar Qs > Qd bo‘lsa, bu taqchillik emas, ortiqcha taklif.',
 'If Qs > Qd, that is a surplus, not a shortage.',
 'Сравните Qd > Qs и Qs > Qd.',
 'Qd > Qs va Qs > Qdni solishtiring.',
 'Compare Qd > Qs with Qs > Qd.',
 'Equilibrium','Shortage','{}'::jsonb,'published'),
(1075,'mcq_option','C','costs fall',false,'shortage_definition_error','Meaning of shortage',
 'Падение издержек может сдвинуть предложение, но не является определением дефицита.',
 'Xarajatlarning pasayishi taklifni siljitishi mumkin, ammo taqchillikning ta’rifi emas.',
 'Falling costs may shift supply, but they do not define a shortage.',
 'Определяйте дефицит через Qd и Qs.',
 'Taqchillikni Qd va Qs orqali aniqlang.',
 'Define shortage using Qd and Qs.',
 'Equilibrium','Shortage','{}'::jsonb,'published'),
(1075,'mcq_option','D','supply shifts right',false,'shift_vs_shortage_confusion','Supply shift vs shortage',
 'Сдвиг предложения вправо обычно уменьшает дефицит, а не определяет его.',
 'Taklifning o‘ngga siljishi odatda taqchillikni kamaytiradi, uni ta’riflamaydi.',
 'A rightward supply shift would usually reduce a shortage rather than define one.',
 'Различайте состояние рынка и сдвиг кривой.',
 'Bozor holati bilan egri chiziq siljishini farqlang.',
 'Distinguish a market condition from a curve shift.',
 'Equilibrium','Shortage','{}'::jsonb,'published'),

(1076,'input_exact',null,'15',true,null,null,
 'Верно: 80 − 2P = 20 + 2P; 60 = 4P; P = 15.',
 'To‘g‘ri: 80 − 2P = 20 + 2P; 60 = 4P; P = 15.',
 'Correct: 80 − 2P = 20 + 2P; 60 = 4P; P = 15.',
 'Приравнивайте Qd и Qs и аккуратно собирайте коэффициенты при P.',
 'Qd va Qsni tenglashtirib, P koeffitsiyentlarini to‘g‘ri jamlang.',
 'Set Qd equal to Qs and combine the P terms carefully.',
 'Equilibrium','Equilibrium price from linear demand and supply','{"accepted":"15"}'::jsonb,'published'),
(1076,'fallback',null,null,false,'equilibrium_equation_error','Solving linear market equilibrium',
 'В равновесии 80 − 2P = 20 + 2P. После переноса членов получается 60 = 4P, поэтому P = 15. Введите только число.',
 'Muvozanatda 80 − 2P = 20 + 2P. Hadlarni ko‘chirganda 60 = 4P, shuning uchun P = 15. Faqat son kiriting.',
 'At equilibrium 80 − 2P = 20 + 2P. Rearranging gives 60 = 4P, so P = 15. Enter only the number.',
 'Повторите решение линейных уравнений равновесия.',
 'Chiziqli muvozanat tenglamalarini yechishni takrorlang.',
 'Review solving linear equilibrium equations.',
 'Equilibrium','Equilibrium price from linear demand and supply','{}'::jsonb,'published'),

(1086,'mcq_option','A','shift supply right',true,null,null,
 'Верно: субсидия снижает эффективные издержки производителей и обычно увеличивает предложение.',
 'To‘g‘ri: subsidiya ishlab chiqaruvchilarning samarali xarajatlarini kamaytiradi va odatda taklifni oshiradi.',
 'Correct: a subsidy lowers producers’ effective costs and usually increases supply.',
 'Свяжите subsidy с более низкими издержками и сдвигом предложения вправо.',
 'Subsidiyani pastroq xarajatlar va taklifning o‘ngga siljishi bilan bog‘lang.',
 'Link a subsidy to lower costs and a rightward supply shift.',
 'Supply','Subsidy and supply','{}'::jsonb,'published'),
(1086,'mcq_option','B','shift supply left',false,'subsidy_direction_error','Subsidy effect on supply',
 'Субсидия снижает, а не повышает издержки производителя, поэтому предложение обычно растёт.',
 'Subsidiya ishlab chiqaruvchi xarajatlarini oshirmaydi, kamaytiradi; shuning uchun taklif odatda oshadi.',
 'A subsidy lowers rather than raises producer costs, so supply usually increases.',
 'Сравните влияние налога и субсидии на предложение.',
 'Soliq va subsidiyaning taklifga ta’sirini solishtiring.',
 'Compare the effects of a tax and a subsidy on supply.',
 'Supply','Subsidy and supply','{}'::jsonb,'published'),
(1086,'mcq_option','C','shift demand right',false,'supply_demand_side_confusion','Producer subsidy affects supply',
 'Субсидия производителям непосредственно действует на издержки и предложение, а не на спрос покупателей.',
 'Ishlab chiqaruvchilarga subsidiya bevosita xarajat va taklifga ta’sir qiladi, xaridor talabiga emas.',
 'A producer subsidy directly affects production costs and supply, not buyer demand.',
 'Определяйте, какой стороне рынка предоставлена субсидия.',
 'Subsidiya bozorning qaysi tomoniga berilganini aniqlang.',
 'Identify which side of the market receives the subsidy.',
 'Supply','Subsidy and supply','{}'::jsonb,'published'),
(1086,'mcq_option','D','cause shortage',false,'subsidy_shortage_confusion','Supply increase vs shortage',
 'Увеличение предложения обычно снижает, а не создаёт дефицит при прочих равных.',
 'Taklifning oshishi boshqa shartlar o‘zgarmaganda taqchillikni yaratmaydi, odatda kamaytiradi.',
 'An increase in supply would usually reduce rather than create a shortage, other things equal.',
 'Свяжите сдвиг предложения вправо с количеством доступного товара.',
 'Taklifning o‘ngga siljishini mavjud tovar miqdori bilan bog‘lang.',
 'Link a rightward supply shift to greater availability.',
 'Supply','Subsidy and supply','{}'::jsonb,'published'),

(1088,'mcq_option','A','clear (no persistent surplus/shortage)',true,null,null,
 'Верно: в равновесии Qd = Qs, поэтому устойчивого избытка или дефицита нет.',
 'To‘g‘ri: muvozanatda Qd = Qs, shuning uchun doimiy ortiqcha yoki taqchillik bo‘lmaydi.',
 'Correct: at equilibrium Qd = Qs, so there is no persistent surplus or shortage.',
 'Свяжите market clearing с Qd = Qs.',
 'Market clearingni Qd = Qs bilan bog‘lang.',
 'Link market clearing to Qd = Qs.',
 'Equilibrium','Market equilibrium','{}'::jsonb,'published'),
(1088,'mcq_option','B','always have shortage',false,'equilibrium_shortage_confusion','Market equilibrium',
 'При равновесии спрос и предложение совпадают, поэтому постоянного дефицита нет.',
 'Muvozanatda talab va taklif teng, shuning uchun doimiy taqchillik bo‘lmaydi.',
 'At equilibrium, demand and supply are equal, so there is no persistent shortage.',
 'Повторите условие равновесия.',
 'Muvozanat shartini takrorlang.',
 'Review the equilibrium condition.',
 'Equilibrium','Market equilibrium','{}'::jsonb,'published'),
(1088,'mcq_option','C','always have surplus',false,'equilibrium_surplus_confusion','Market equilibrium',
 'Равновесие не означает постоянный избыток; Qs и Qd равны.',
 'Muvozanat doimiy ortiqcha taklifni anglatmaydi; Qs va Qd teng.',
 'Equilibrium does not mean a persistent surplus; Qs and Qd are equal.',
 'Свяжите равновесие с отсутствием устойчивого дисбаланса.',
 'Muvozanatni doimiy nomutanosiblik yo‘qligi bilan bog‘lang.',
 'Link equilibrium to the absence of a persistent imbalance.',
 'Equilibrium','Market equilibrium','{}'::jsonb,'published'),
(1088,'mcq_option','D','stop trading',false,'equilibrium_no_trade_confusion','Market clearing vs no trade',
 'Равновесие означает согласование покупок и продаж, а не прекращение торговли.',
 'Muvozanat savdo to‘xtashi emas, xarid va sotuvlarning mos kelishini anglatadi.',
 'Equilibrium means buying and selling plans are matched, not that trade stops.',
 'Не путайте market clearing с отсутствием сделок.',
 'Market clearingni savdo yo‘qligi bilan adashtirmang.',
 'Do not confuse market clearing with no transactions.',
 'Equilibrium','Market equilibrium','{}'::jsonb,'published'),

(1096,'mcq_option','A','surplus',true,null,null,
 'Верно: при цене выше равновесной Qs обычно превышает Qd, создавая избыток.',
 'To‘g‘ri: muvozanat narxidan yuqorida Qs odatda Qddan katta bo‘lib, ortiqcha taklif hosil qiladi.',
 'Correct: above equilibrium price, Qs usually exceeds Qd, creating a surplus.',
 'Свяжите высокую цену с большим Qs и меньшим Qd.',
 'Yuqori narxni kattaroq Qs va kichikroq Qd bilan bog‘lang.',
 'Link a high price to higher Qs and lower Qd.',
 'Equilibrium','Price above equilibrium','{}'::jsonb,'published'),
(1096,'mcq_option','B','shortage',false,'above_below_equilibrium_reversal','Price above equilibrium',
 'Дефицит характерен для цены ниже равновесной. При цене выше равновесной возникает избыток.',
 'Taqchillik muvozanat narxidan pastda yuz beradi. Yuqorida esa ortiqcha taklif bo‘ladi.',
 'A shortage is associated with a price below equilibrium. Above equilibrium, there is a surplus.',
 'Сравните последствия цены выше и ниже равновесной.',
 'Muvozanatdan yuqori va past narx oqibatlarini solishtiring.',
 'Compare outcomes above and below equilibrium price.',
 'Equilibrium','Price above equilibrium','{}'::jsonb,'published'),
(1096,'mcq_option','C','no effect',false,'market_imbalance_ignored','Price relative to equilibrium',
 'Цена выше равновесной меняет Qd и Qs и создаёт дисбаланс.',
 'Muvozanatdan yuqori narx Qd va Qsni o‘zgartirib, nomutanosiblik yaratadi.',
 'A price above equilibrium changes Qd and Qs and creates an imbalance.',
 'Не игнорируйте положение цены относительно равновесия.',
 'Narxning muvozanatga nisbatan holatini e’tiborsiz qoldirmang.',
 'Do not ignore the price position relative to equilibrium.',
 'Equilibrium','Price above equilibrium','{}'::jsonb,'published'),
(1096,'mcq_option','D','higher demand',false,'price_demand_direction_error','Price above equilibrium',
 'Более высокая собственная цена обычно уменьшает объём спроса, а не увеличивает его.',
 'Yuqori o‘z narxi odatda talab miqdorini oshirmaydi, kamaytiradi.',
 'A higher own price usually reduces quantity demanded rather than increasing it.',
 'Повторите закон спроса.',
 'Talab qonunini takrorlang.',
 'Review the law of demand.',
 'Equilibrium','Price above equilibrium','{}'::jsonb,'published'),

(1097,'mcq_option','A','shortage',true,null,null,
 'Верно: при цене ниже равновесной Qd обычно превышает Qs, создавая дефицит.',
 'To‘g‘ri: muvozanat narxidan pastda Qd odatda Qsdan katta bo‘lib, taqchillik yaratadi.',
 'Correct: below equilibrium price, Qd usually exceeds Qs, creating a shortage.',
 'Свяжите низкую цену с большим Qd и меньшим Qs.',
 'Past narxni kattaroq Qd va kichikroq Qs bilan bog‘lang.',
 'Link a low price to higher Qd and lower Qs.',
 'Equilibrium','Price below equilibrium','{}'::jsonb,'published'),
(1097,'mcq_option','B','surplus',false,'above_below_equilibrium_reversal','Price below equilibrium',
 'Избыток возникает при цене выше равновесной, а не ниже неё.',
 'Ortiqcha taklif muvozanat narxidan yuqorida yuz beradi, pastda emas.',
 'A surplus occurs above equilibrium price, not below it.',
 'Сравните цену выше и ниже равновесной.',
 'Muvozanatdan yuqori va past narxni solishtiring.',
 'Compare prices above and below equilibrium.',
 'Equilibrium','Price below equilibrium','{}'::jsonb,'published'),
(1097,'mcq_option','C','no effect',false,'market_imbalance_ignored','Price relative to equilibrium',
 'Цена ниже равновесной влияет на решения покупателей и продавцов и создаёт дефицит.',
 'Muvozanatdan past narx xaridor va sotuvchilar qarorlariga ta’sir qilib, taqchillik yaratadi.',
 'A price below equilibrium affects buyers and sellers and creates a shortage.',
 'Используйте Qd и Qs для проверки дисбаланса.',
 'Nomutanosiblikni tekshirish uchun Qd va Qsdan foydalaning.',
 'Use Qd and Qs to check the imbalance.',
 'Equilibrium','Price below equilibrium','{}'::jsonb,'published'),
(1097,'mcq_option','D','lower supply curve',false,'movement_shift_confusion','Quantity supplied vs supply shift',
 'Низкая собственная цена вызывает движение вдоль кривой предложения, а не сдвиг самой кривой.',
 'Past o‘z narxi taklif egri chizig‘i bo‘ylab harakatni keltirib chiqaradi, egri chiziqning siljishini emas.',
 'A lower own price causes movement along the supply curve, not a shift of the curve itself.',
 'Различайте quantity supplied и supply.',
 'Quantity supplied bilan supplyni farqlang.',
 'Distinguish quantity supplied from supply.',
 'Equilibrium','Price below equilibrium','{}'::jsonb,'published'),

(1117,'mcq_option','A','Queuing / waiting in line',true,null,null,
 'Верно: если обязательный потолок цены создаёт дефицит, товар часто распределяется через очереди и затраты времени.',
 'To‘g‘ri: majburiy narx chegarasi taqchillik yaratsa, tovar ko‘pincha navbat va vaqt xarajati orqali taqsimlanadi.',
 'Correct: when a binding price ceiling creates a shortage, goods are often rationed through queues and waiting time.',
 'Свяжите дефицит при фиксированной цене с неценовым нормированием.',
 'Belgilangan narxdagi taqchillikni narxdan tashqari taqsimlash bilan bog‘lang.',
 'Link a shortage under a fixed price to non-price rationing.',
 'Equilibrium','Price ceiling and shortage','{}'::jsonb,'published'),
(1117,'mcq_option','B','A higher official equilibrium price',false,'price_ceiling_logic_error','Binding price ceiling',
 'Потолок цены ограничивает официальную цену сверху; дефицит не автоматически создаёт более высокую официальную равновесную цену.',
 'Narx chegarasi rasmiy narxni yuqoridan cheklaydi; taqchillik avtomatik ravishda yuqori rasmiy muvozanat narxini yaratmaydi.',
 'A price ceiling caps the official price; the shortage does not automatically create a higher official equilibrium price.',
 'Различайте рыночное давление и юридически установленную цену.',
 'Bozor bosimi bilan huquqiy belgilangan narxni farqlang.',
 'Distinguish market pressure from the legally controlled price.',
 'Equilibrium','Price ceiling and shortage','{}'::jsonb,'published'),
(1117,'mcq_option','C','Automatic market clearing',false,'price_control_market_clearing_confusion','Price ceiling and shortage',
 'Обязательный потолок ниже равновесия препятствует обычному ценовому очищению рынка, поэтому дефицит сохраняется.',
 'Muvozanatdan past majburiy narx chegarasi odatiy narx orqali market clearingga to‘sqinlik qiladi va taqchillik saqlanadi.',
 'A binding ceiling below equilibrium prevents normal price-based market clearing, so the shortage persists.',
 'Повторите, почему binding price ceiling создаёт excess demand.',
 'Binding price ceiling nega excess demand yaratishini takrorlang.',
 'Review why a binding price ceiling creates excess demand.',
 'Equilibrium','Price ceiling and shortage','{}'::jsonb,'published'),
(1117,'mcq_option','D','Perfectly elastic supply',false,'price_ceiling_elasticity_confusion','Rationing under price controls',
 'Потолок цены и дефицит не означают, что предложение становится совершенно эластичным.',
 'Narx chegarasi va taqchillik taklif mutlaqo elastik bo‘lib qolishini anglatmaydi.',
 'A price ceiling and shortage do not imply that supply becomes perfectly elastic.',
 'Не путайте механизм распределения дефицита с эластичностью кривой предложения.',
 'Taqchillikni taqsimlash mexanizmini taklif egri chizig‘i elastikligi bilan adashtirmang.',
 'Do not confuse shortage rationing with supply-curve elasticity.',
 'Equilibrium','Price ceiling and shortage','{}'::jsonb,'published');