-- P0-06: canonical Cambridge AS Mathematics P1+P5 registry.
-- Source: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0.xlsx
-- Canonical map version: 01_Academic_Syllabus_Source_Map_P1_P5_v1.0
-- Deterministic source-data SHA256: b3d78f8b6ea0b2a6694deee0ff045022aafe53ff9b5da0a923c2ded39e10959b
-- Additive only. No legacy questions/Practice/Tours/ratings/certificates are updated or deleted.
-- Skill seed chunk 1; rows 1-14 of 81.

begin;

with pv as (
  select id from private.exam_prep_program_versions
  where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0'
)
insert into private.exam_prep_syllabus_nodes (
  program_version_id, sequence_no, component_code, official_syllabus_section, skill_code,
  canonical_description, prerequisites_text, book_chapter, book_pages, mcq_suitability,
  input_suitability, mixed_suitability, written_suitability, required_mastery_evidence,
  app_can_verify, mentor_must_verify, recommended_stage, content_note, future_change_note,
  official_source_url
)
select pv.id, v.sequence_no, v.component_code, v.official_syllabus_section, v.skill_code,
       v.canonical_description, v.prerequisites_text, v.book_chapter, v.book_pages, v.mcq_suitability,
       v.input_suitability, v.mixed_suitability, v.written_suitability, v.required_mastery_evidence,
       v.app_can_verify, v.mentor_must_verify, v.recommended_stage, v.content_note, v.future_change_note,
       v.official_source_url
from pv
cross join (values
(1,'P1','1.1 Quadratics','P1-QUA-01','Приводить квадратный трёхчлен к completed-square form и извлекать vertex/shape information.','PR-ALG-03; PR-GRF-01','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(2,'P1','1.1 Quadratics','P1-QUA-02','Использовать discriminant для определения числа и типа действительных корней, включая parameter conditions.','P1-QUA-01; PR-EQN-01','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(3,'P1','1.1 Quadratics','P1-QUA-03','Решать quadratic equations и осознанно выбирать factorisation, formula или completing the square.','PR-ALG-02; PR-ALG-03; PR-EQN-01','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(4,'P1','1.1 Quadratics','P1-QUA-04','Решать quadratic inequalities с корректными interval endpoints.','P1-QUA-03; PR-GRF-01','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(5,'P1','1.1 Quadratics','P1-QUA-05','Решать simultaneous system из одной linear и одной quadratic relation.','P1-QUA-03; PR-EQN-01','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(6,'P1','1.1 Quadratics','P1-QUA-06','Распознавать и решать equations quadratic in a transformed expression.','P1-QUA-03; PR-ALG-03','Complete Pure Mathematics 1, Ch1 Quadratics','pp. 2–20','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E1 Foundations (сентябрь–октябрь)','Официальный skill покрыт учебником; отдельного content gap не выявлено.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(7,'P1','1.2 Functions','P1-FUN-01','Использовать язык function, domain, range, one-one, inverse и composition.','PR-ALG-03; PR-GRF-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Высокая','Ограниченная','Высокая','Обязательная','3 независимых случая: распознавание, non-example и перенос в mixed-задачу; ≥80% и delayed retest через 7–14 дней; краткое обоснование выбора модели.','Распознавание/выбор, допустимые ответы, домен/условия как структурированные поля, точность и delayed-retest history.','Обоснование модели, корректность условий и нотации, логика исключения альтернатив, AO2-коммуникация.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(8,'P1','1.2 Functions','P1-FUN-02','Определять range функции с учётом заданного domain restriction.','P1-FUN-01; P1-QUA-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(9,'P1','1.2 Functions','P1-FUN-03','Находить composite functions и проверять совместимость domain/range.','P1-FUN-01; PR-ALG-03','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Высокая','Высокая','Обязательная','4 независимых задания: 2 routine, 1 transfer и 1 mixed/timed; ≥80% и delayed retest ≥80%; сохранены постановка, промежуточные шаги и проверка результата.','Числовой/алгебраический финал, эквивалентные формы, точность, ограничения ответа, время, попытки и retest.','Метод, полнота working, правомерность преобразований, method marks, единицы/контекст и качество проверки.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(10,'P1','1.2 Functions','P1-FUN-04','Проверять one-one condition и находить inverse function с корректным domain.','P1-FUN-01; PR-EQN-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Ограниченная','Высокая','Обязательная','2 контекстных сравнения/доказательных решения и 1 timed mixed-задача; заключение связано с данными/условиями; delayed retest ≥80%.','Промежуточные числовые результаты, выбор утверждений/оснований, наличие требуемых элементов и история попыток.','Логическая достаточность, контекстное заключение, математический язык, качество аргумента и AO2.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(11,'P1','1.2 Functions','P1-FUN-05','Связывать графики function и inverse отражением в y = x.','P1-FUN-04; PR-GRF-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(12,'P1','1.2 Functions','P1-FUN-06','Выполнять горизонтальные и вертикальные translations графиков.','P1-FUN-01; PR-GRF-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(13,'P1','1.2 Functions','P1-FUN-07','Выполнять reflections графиков в координатных осях.','P1-FUN-01; PR-GRF-01','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf'),
(14,'P1','1.2 Functions','P1-FUN-08','Выполнять stretches/compressions и простые combinations transformations с point mapping.','P1-FUN-06; P1-FUN-07','Complete Pure Mathematics 1, Ch2 Functions and transformations','pp. 24–42','Средняя','Частичная','Высокая','Обязательная','2 самостоятельных построения и 2 интерпретации, включая mixed/timed case; все ключевые features отмечены; delayed retest через 7–14 дней.','Выбранные features, координаты, интервалы, соответствие свойств и ограниченная проверка digital sketch.','Форма, масштаб, labels, асимптотика/пересечения где применимо, геометрическая точность и связное working.','E1 Foundations (сентябрь–октябрь)','В Math Tour Map functions/transformations смешаны с modulus (вне P1); этот P1 skill нужно хранить отдельно. Учебник покрывает.','Без изменения содержания: syllabus 2028–2030 сообщает об отсутствии существенных teaching changes; стабильный code сохраняется.','https://www.cambridgeinternational.org/Images/697427-2026-2027-syllabus.pdf')
) as v(
  sequence_no, component_code, official_syllabus_section, skill_code, canonical_description,
  prerequisites_text, book_chapter, book_pages, mcq_suitability, input_suitability, mixed_suitability,
  written_suitability, required_mastery_evidence, app_can_verify, mentor_must_verify,
  recommended_stage, content_note, future_change_note, official_source_url
)
on conflict (program_version_id, skill_code) do update set
  sequence_no=excluded.sequence_no,
  component_code=excluded.component_code,
  official_syllabus_section=excluded.official_syllabus_section,
  canonical_description=excluded.canonical_description,
  prerequisites_text=excluded.prerequisites_text,
  book_chapter=excluded.book_chapter,
  book_pages=excluded.book_pages,
  mcq_suitability=excluded.mcq_suitability,
  input_suitability=excluded.input_suitability,
  mixed_suitability=excluded.mixed_suitability,
  written_suitability=excluded.written_suitability,
  required_mastery_evidence=excluded.required_mastery_evidence,
  app_can_verify=excluded.app_can_verify,
  mentor_must_verify=excluded.mentor_must_verify,
  recommended_stage=excluded.recommended_stage,
  content_note=excluded.content_note,
  future_change_note=excluded.future_change_note,
  official_source_url=excluded.official_source_url;

commit;
