-- P1-02 P5 AW21-24 NOR-06: normal approximation to binomial with conditions and continuity correction.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;
insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p5_aw21_24_nor06_v1','P5','P5 AW21-24 NOR-06 normal approximation to binomial','draft','Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Probability & Statistics 1 is mapping/teaching reference only; no protected source wording copied. Includes suitability conditions and continuity correction.'
from private.exam_prep_program_versions pv where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_nor06_v1' and component_code='P5' and status='draft'), src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P5NOR06-D01','diagnostic','medium','X~Bin(100,0.4). Which is the correct normal-approximation setup for P(X<=45)?','X~Bin(100,0,4). Как правильно записать normal approximation для P(X<=45)?','X~Bin(100,0.4). P(X<=45) uchun to‘g‘ri normal approximation qaysi?','["Y~N(40,24) and use P(Y<45.5)","Y~N(40,24) and use P(Y<45)","Y~N(40,sqrt(24)) and use P(Y<45.5)","Y~N(60,24) and use P(Y<45.5)"]','["Y~N(40,24) и P(Y<45,5)","Y~N(40,24) и P(Y<45)","Y~N(40,sqrt(24)) и P(Y<45,5)","Y~N(60,24) и P(Y<45,5)"]','["Y~N(40,24) va P(Y<45.5)","Y~N(40,24) va P(Y<45)","Y~N(40,sqrt(24)) va P(Y<45.5)","Y~N(60,24) va P(Y<45.5)"]','A','For Bin(n,p), mean=np=40 and variance=np(1-p)=24. P(X<=45) uses the continuity-corrected boundary 45.5.','Для Bin(n,p): среднее np=40, дисперсия np(1-p)=24. Для P(X<=45) граница с continuity correction равна 45,5.','Bin(n,p) uchun mean=np=40, variance=np(1-p)=24. P(X<=45) da continuity correction chegarasi 45.5.',55),
('P5NOR06-L01','learning','easy','Which binomial distribution is most suitable for a normal approximation?','Какое биномиальное распределение наиболее подходит для normal approximation?','Qaysi binomial taqsimot normal approximation uchun eng mos?','["Bin(50,0.5)","Bin(20,0.05)","Bin(100,0.99)","Bin(8,0.5)"]','["Bin(50,0,5)","Bin(20,0,05)","Bin(100,0,99)","Bin(8,0,5)"]','["Bin(50,0.5)","Bin(20,0.05)","Bin(100,0.99)","Bin(8,0.5)"]','A','For Bin(50,0.5), np=25 and n(1-p)=25, so both expected success and failure counts are comfortably large.','Для Bin(50,0,5) значения np=25 и n(1-p)=25 достаточно велики.','Bin(50,0.5) uchun np=25 va n(1-p)=25, ikkalasi ham yetarlicha katta.',35),
('P5NOR06-L02','learning','medium','X~Bin(80,0.5). Use a normal approximation with continuity correction to estimate P(X<=44), to 4 d.p.','X~Bin(80,0,5). Используйте normal approximation с continuity correction для оценки P(X<=44) до 4 знаков.','X~Bin(80,0.5). Continuity correction bilan normal approximation orqali P(X<=44) ni 4 xonagacha toping.','["0.8428","0.8145","0.1572","0.8697"]','["0,8428","0,8145","0,1572","0,8697"]','["0.8428","0.8145","0.1572","0.8697"]','A','Use Y~N(40,20) and P(Y<44.5). z=(44.5-40)/sqrt(20)=1.0062, giving about 0.8428.','Используем Y~N(40,20) и P(Y<44,5). z≈1,0062, вероятность≈0,8428.','Y~N(40,20), P(Y<44.5). z≈1.0062, ehtimol≈0.8428.',50),
('P5NOR06-L03','learning','medium','X~Bin(100,0.3). Use a normal approximation with continuity correction to estimate P(X>=35), to 4 d.p.','X~Bin(100,0,3). Оцените P(X>=35) через normal approximation с continuity correction до 4 знаков.','X~Bin(100,0.3). Continuity correction bilan normal approximation orqali P(X>=35) ni 4 xonagacha toping.','["0.1631","0.8369","0.1492","0.1841"]','["0,1631","0,8369","0,1492","0,1841"]','["0.1631","0.8369","0.1492","0.1841"]','A','Y~N(30,21). X>=35 becomes Y>34.5. z=(34.5-30)/sqrt(21)=0.9820, so upper-tail probability is about 0.1631.','Y~N(30,21). X>=35 превращается в Y>34,5. z≈0,9820, верхний хвост≈0,1631.','Y~N(30,21). X>=35 -> Y>34.5. z≈0.9820, yuqori tail≈0.1631.',50),
('P5NOR06-R01','retest','medium','X~Bin(64,0.5). Use a normal approximation with continuity correction to estimate P(X<=36), to 4 d.p.','X~Bin(64,0,5). Оцените P(X<=36) через normal approximation с continuity correction до 4 знаков.','X~Bin(64,0.5). Continuity correction bilan normal approximation orqali P(X<=36) ni 4 xonagacha toping.','["0.8697","0.8413","0.1303","0.8944"]','["0,8697","0,8413","0,1303","0,8944"]','["0.8697","0.8413","0.1303","0.8944"]','A','Y~N(32,16). Use 36.5; z=(36.5-32)/4=1.125, giving 0.8697.','Y~N(32,16). Используем 36,5; z=1,125, вероятность 0,8697.','Y~N(32,16). 36.5 ni ishlating; z=1.125, ehtimol 0.8697.',45),
('P5NOR06-R02','retest','hard','X~Bin(100,0.5). Use a normal approximation with continuity correction to estimate P(45<=X<=55), to 4 d.p.','X~Bin(100,0,5). Оцените P(45<=X<=55) через normal approximation с continuity correction до 4 знаков.','X~Bin(100,0.5). Continuity correction bilan normal approximation orqali P(45<=X<=55) ni 4 xonagacha toping.','["0.7287","0.6827","0.2713","0.8413"]','["0,7287","0,6827","0,2713","0,8413"]','["0.7287","0.6827","0.2713","0.8413"]','A','Y~N(50,25). The corrected interval is 44.5<Y<55.5, giving z=-1.1 to 1.1 and probability about 0.7287.','Y~N(50,25). Скорректированный интервал 44,5<Y<55,5, z от -1,1 до 1,1, вероятность≈0,7287.','Y~N(50,25). Tuzatilgan interval 44.5<Y<55.5, z=-1.1 dan 1.1 gacha, ehtimol≈0.7287.',55),
('P5NOR06-M01','mixed','hard','X~Bin(200,0.2). Use a normal approximation with continuity correction to estimate P(X>50), to 4 d.p.','X~Bin(200,0,2). Оцените P(X>50) через normal approximation с continuity correction до 4 знаков.','X~Bin(200,0.2). Continuity correction bilan normal approximation orqali P(X>50) ni 4 xonagacha toping.','["0.0317","0.9683","0.0392","0.0228"]','["0,0317","0,9683","0,0392","0,0228"]','["0.0317","0.9683","0.0392","0.0228"]','A','Y~N(40,32). X>50 means X>=51, so use Y>50.5. z=(50.5-40)/sqrt(32)=1.8562 and the upper tail is about 0.0317.','Y~N(40,32). X>50 означает X>=51, поэтому используем Y>50,5. z≈1,8562, верхний хвост≈0,0317.','Y~N(40,32). X>50 -> X>=51, shuning uchun Y>50.5. z≈1.8562, yuqori tail≈0.0317.',60)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P5 Normal Approximation','P5-NOR-06',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P5:p5_aw21_24_nor06_v1:'||s.k,s.secs,null,'draft' from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P5:p5_aw21_24_nor06_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_nor06_v1' and status='draft'), keys(k,role) as (values('P5NOR06-D01','diagnostic'),('P5NOR06-L01','learning'),('P5NOR06-L02','learning'),('P5NOR06-L03','learning'),('P5NOR06-R01','retest'),('P5NOR06-R02','retest'),('P5NOR06-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P5-NOR-06','{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p5_aw21_24_nor06_v1 from canonical normal-approximation intent.','Cambridge 9709 2026-2027 v4; P5 5.5 The normal distribution','Complete Probability & Statistics 1; normal approximation to binomial (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P5:p5_aw21_24_nor06_v1:'||k.k on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p5_aw21_24_nor06_v1' and m.content_key='P5NOR06-D01'), r(match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('B','omits_continuity_correction','concept','The discrete event X<=45 corresponds to the continuous boundary 45.5, not 45.','Дискретное событие X<=45 соответствует непрерывной границе 45,5, а не 45.','Diskret X<=45 uzluksiz 45.5 chegaraga mos, 45 ga emas.','Translate integer inequalities to half-unit boundaries before standardising.','Перед стандартизацией переводите целочисленные границы в полуцелые.','Standartlashdan oldin butun chegaralarni yarim birlikka aylantiring.'),
('C','uses_sd_as_variance_parameter','concept','In N(mu,sigma^2) notation the second parameter is the variance 24, not the standard deviation sqrt(24).','В N(mu,sigma^2) второй параметр — дисперсия 24, а не стандартное отклонение sqrt(24).','N(mu,sigma^2) da ikkinchi parametr variance 24, sqrt(24) emas.','Keep mean=np and variance=npq separate from sigma=sqrt(npq).','Разделяйте mean=np, variance=npq и sigma=sqrt(npq).','mean=np, variance=npq va sigma=sqrt(npq) ni ajrating.'),
('D','uses_failure_mean','concept','The binomial counts successes, so its mean is np=40, not nq=60.','Биномиальная переменная считает успехи, поэтому среднее np=40, а не nq=60.','Binomial muvaffaqiyatlarni sanaydi, mean=np=40, nq=60 emas.','Use the p attached to the counted success event.','Используйте p события, которое считается успехом.','Sanayotgan muvaffaqiyat hodisasining p sini ishlating.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,'P5-NOR-06',r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r cross join meta on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_nor06_v1' and status='draft')
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,'P5NOR06-W01','P5','P5-NOR-06','wtv1','Let X~Bin(120,0.4). Explain why a normal approximation is reasonable. Then use Y~N(np,npq) with continuity correction to estimate P(X<=55) and P(42<=X<=54), giving answers to 4 d.p.','Пусть X~Bin(120,0,4). Объясните, почему normal approximation разумна. Затем используйте Y~N(np,npq) с continuity correction для оценки P(X<=55) и P(42<=X<=54), ответы до 4 знаков.','X~Bin(120,0.4). Normal approximation nega mosligini tushuntiring. So‘ng Y~N(np,npq) va continuity correction bilan P(X<=55) hamda P(42<=X<=54) ni 4 xonagacha toping.','{"max_marks":13,"criteria":[{"id":"conditions","marks":2,"rule":"Notes np=48 and nq=72 are both large, so approximation is reasonable."},{"id":"parameters","marks":2,"rule":"Uses mean=48, variance=28.8, sigma=sqrt(28.8)."},{"id":"first_cc","marks":2,"rule":"Uses P(Y<55.5)."},{"id":"first_probability","marks":2,"rule":"Uses z≈1.3975 and gets about 0.9189."},{"id":"interval_cc","marks":2,"rule":"Uses 41.5<Y<54.5."},{"id":"interval_probability","marks":3,"rule":"Uses z≈-1.2112 to 1.2112 and gets about 0.7742."}]}','Write the corrected continuous boundaries before calculating any z-values; this prevents most one-unit errors.','Сначала запишите скорректированные непрерывные границы, затем вычисляйте z.','Avval tuzatilgan uzluksiz chegaralarni yozing, keyin z ni hisoblang.','published','pass','pass','pass','pass',now() from cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_nor06_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p5_nor06_diagnostic','diagnostic','P5 NOR-06 normal approximation diagnostic','Диагностика P5 NOR-06: normal approximation','P5 NOR-06 normal approximation diagnostikasi'),('p5_nor06_learning','learning','Normal approximation to binomial learning','Normal approximation to binomial: обучение','Binomialga normal approximation: o‘rganish'),('p5_nor06_retest','retest','NOR-06 delayed retest','NOR-06 отложенный ретест','NOR-06 kechiktirilgan retest'),('p5_nor06_mixed','mixed','NOR-06 continuity-correction transfer','NOR-06 перенос continuity correction','NOR-06 continuity correction transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P5',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv on conflict(content_version_id,assessment_key,assessment_version) do nothing;
with cv as (select id from private.exam_prep_content_versions where content_version='p5_aw21_24_nor06_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,role,holdout) as (values
('p5_nor06_diagnostic',1,'P5NOR06-D01',null,'diagnostic',true),('p5_nor06_learning',1,'P5NOR06-L01',null,'learning',false),('p5_nor06_learning',2,'P5NOR06-L02',null,'learning',false),('p5_nor06_learning',3,'P5NOR06-L03',null,'learning',false),('p5_nor06_learning',4,null,'P5NOR06-W01','written',false),('p5_nor06_retest',1,'P5NOR06-R01',null,'retest',true),('p5_nor06_retest',2,'P5NOR06-R02',null,'retest',true),('p5_nor06_mixed',1,'P5NOR06-M01',null,'mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,'P5-NOR-06',i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_nor06_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p5_aw21_24_nor06_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p5_aw21_24_nor06_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p5_aw21_24_nor06_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p5_aw21_24_nor06_v1' and status='approved';

do $$ declare v_program bigint; begin
select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
if not private.exam_prep_skill_content_ready_v1(v_program,'P5','P5-NOR-06') then raise exception 'P5 NOR-06 not ready'; end if;
if exists(select 1 from public.questions where book_ref like 'ExamPrep:P5:p5_aw21_24_nor06_v1:%' and is_active) then raise exception 'P5 NOR-06 legacy activation residue'; end if;
if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P5 NOR-06 publication escaped fail-closed'; end if;
if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P5 NOR-06 active entitlement residue'; end if;
end $$;
commit;