-- P1-02 original iClub content: P1-FUN-01 function/domain/range/one-one/inverse/composition language.
-- 1 diagnostic + 3 learning + 2 retest + 1 mixed. DRAFT + INACTIVE only.

begin;
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
src(k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1FUN01-D01','diagnostic','medium','Which statement is the defining requirement for a relation to be a function?','Какое утверждение является определяющим условием того, что отношение является функцией?','Munosabat funksiya bo‘lishi uchun qaysi shart asosiy hisoblanadi?','["Each input has exactly one output","Each output has exactly one input","All inputs and outputs must be positive","The graph must be a straight line"]','["Каждому входу соответствует ровно один выход","Каждому выходу соответствует ровно один вход","Все входы и выходы должны быть положительными","График должен быть прямой"]','["Har bir kirishga aynan bitta chiqish mos keladi","Har bir chiqishga aynan bitta kirish mos keladi","Barcha kirish va chiqishlar musbat bo‘lishi kerak","Grafik to‘g‘ri chiziq bo‘lishi kerak"]','A','A function assigns exactly one output to each permitted input. Different inputs may share an output unless the function is one-one.','Функция каждому допустимому входу сопоставляет ровно один выход. Разные входы могут иметь один выход, если функция не является взаимно однозначной.','Funksiya har bir ruxsat etilgan kirishga aynan bitta chiqish qiymatini moslaydi. Turli kirishlar bir xil chiqishga ega bo‘lishi mumkin, agar funksiya bir-biriga bir qiymatli bo‘lmasa.',75),
('P1FUN01-L01','learning','easy','The domain of a function is best described as:','Область определения функции — это:','Funksiyaning aniqlanish sohasi nima?','["the set of permitted input values","the set of output values actually obtained","the equation of the inverse","the gradient of the graph"]','["множество допустимых входных значений","множество фактически получаемых выходных значений","уравнение обратной функции","градиент графика"]','["ruxsat etilgan kirish qiymatlari to‘plami","hosil bo‘ladigan chiqish qiymatlari to‘plami","teskari funksiya tenglamasi","grafik gradienti"]','A','The domain is the set of input values for which the function is defined.','Область определения — множество входных значений, для которых функция определена.','Aniqlanish sohasi — funksiya aniqlangan kirish qiymatlari to‘plami.',50),
('P1FUN01-L02','learning','medium','Which condition guarantees that a function is one-one on its stated domain?','Какое условие гарантирует, что функция взаимно однозначна на своей области определения?','Qaysi shart funksiya berilgan aniqlanish sohasida bir-biriga bir qiymatli ekanini kafolatlaydi?','["Different inputs give different outputs","Every output is positive","The domain contains all real numbers","The graph crosses the y-axis"]','["Разные входы дают разные выходы","Каждый выход положителен","Область определения содержит все действительные числа","График пересекает ось y"]','["Turli kirishlar turli chiqishlar beradi","Har bir chiqish musbat","Aniqlanish sohasi barcha haqiqiy sonlarni o‘z ichiga oladi","Grafik y o‘qini kesadi"]','A','A one-one function never gives the same output for two different inputs in its domain.','У взаимно однозначной функции два разных входа не дают один и тот же выход.','Bir-biriga bir qiymatli funksiyada ikki xil kirish bir xil chiqish bermaydi.',60),
('P1FUN01-L03','learning','easy','If (f ∘ g)(x) is defined, which expression does it mean?','Если (f ∘ g)(x) определено, какое выражение оно означает?','Agar (f ∘ g)(x) aniqlangan bo‘lsa, u qaysi ifodani anglatadi?','["f(g(x))","g(f(x))","f(x)g(x)","f(x) + g(x)"]','["f(g(x))","g(f(x))","f(x)g(x)","f(x) + g(x)"]','["f(g(x))","g(f(x))","f(x)g(x)","f(x) + g(x)"]','A','Composition f ∘ g means apply g first, then apply f: f(g(x)).','Композиция f ∘ g означает сначала применить g, затем f: f(g(x)).','f ∘ g kompozitsiyasi avval g, keyin f ni qo‘llashni anglatadi: f(g(x)).',55),
('P1FUN01-R01','retest','medium','Which property is required before a function can have an inverse function on its stated domain?','Какое свойство необходимо, чтобы функция имела обратную функцию на своей области определения?','Funksiya berilgan aniqlanish sohasida teskari funksiyaga ega bo‘lishi uchun qaysi xossa zarur?','["It must be one-one","It must be quadratic","Its range must be all real numbers","It must pass through the origin"]','["Она должна быть взаимно однозначной","Она должна быть квадратной","Её область значений должна быть всеми действительными числами","Она должна проходить через начало координат"]','["U bir-biriga bir qiymatli bo‘lishi kerak","U kvadratik bo‘lishi kerak","Qiymatlar sohasi barcha haqiqiy sonlar bo‘lishi kerak","U koordinata boshidan o‘tishi kerak"]','A','An inverse function requires each output to correspond to one input, so the original function must be one-one on the stated domain.','Для существования обратной функции каждому выходу должен соответствовать один вход, поэтому исходная функция должна быть взаимно однозначной.','Teskari funksiya mavjud bo‘lishi uchun har bir chiqishga bitta kirish mos kelishi kerak; demak asl funksiya bir-biriga bir qiymatli bo‘lishi zarur.',65),
('P1FUN01-R02','retest','medium','Which statement correctly describes the range of a function?','Какое утверждение верно описывает область значений функции?','Funksiyaning qiymatlar sohasi qaysi ta’rifga mos keladi?','["the set of output values produced from the allowed domain","the set of all symbols used in its formula","the set of inputs only","the coordinates of the y-intercept only"]','["множество выходных значений, получаемых из допустимой области определения","множество всех символов в формуле","только множество входных значений","только координаты пересечения с осью y"]','["ruxsat etilgan aniqlanish sohasidan hosil bo‘ladigan chiqish qiymatlari to‘plami","formuladagi barcha belgilar to‘plami","faqat kirish qiymatlari to‘plami","faqat y o‘qi bilan kesishish koordinatalari"]','A','The range contains the outputs obtained when allowed domain values are used.','Область значений состоит из выходных значений, получаемых при допустимых значениях аргумента.','Qiymatlar sohasi ruxsat etilgan argument qiymatlaridan hosil bo‘ladigan chiqish qiymatlaridan iborat.',60),
('P1FUN01-M01','mixed','medium','Let f(x) = x² with domain x ≥ 0. Which statement is correct?','Пусть f(x) = x² при области определения x ≥ 0. Какое утверждение верно?','f(x) = x² va aniqlanish sohasi x ≥ 0 bo‘lsin. Qaysi tasdiq to‘g‘ri?','["f is one-one and f⁻¹(x) = √x for x ≥ 0","f is not a function","f⁻¹(x) = −√x for x ≥ 0","f is one-one only when x < 0"]','["f взаимно однозначна и f⁻¹(x) = √x при x ≥ 0","f не является функцией","f⁻¹(x) = −√x при x ≥ 0","f взаимно однозначна только при x < 0"]','["f bir-biriga bir qiymatli va x ≥ 0 da f⁻¹(x) = √x","f funksiya emas","x ≥ 0 da f⁻¹(x) = −√x","f faqat x < 0 da bir-biriga bir qiymatli"]','A','Restricting x² to x ≥ 0 makes it one-one. Solving y = x² with x ≥ 0 gives x = √y, so f⁻¹(x) = √x.','Ограничение x² областью x ≥ 0 делает функцию взаимно однозначной. Из y = x² при x ≥ 0 получаем x = √y, поэтому f⁻¹(x) = √x.','x² funksiyasini x ≥ 0 bilan cheklash uni bir-biriga bir qiymatli qiladi. y = x² va x ≥ 0 dan x = √y, shuning uchun f⁻¹(x) = √x.',80)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Functions','P1-FUN-01',s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_foundations_runway_v1:'||s.k,s.secs,null,'draft' from cv cross join src s
where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||s.k);
with cv as (select id from private.exam_prep_content_versions where content_version='p1_foundations_runway_v1' and component_code='P1' and status='draft'),
keys(k,role) as (values('P1FUN01-D01','diagnostic'),('P1FUN01-L01','learning'),('P1FUN01-L02','learning'),('P1FUN01-L03','learning'),('P1FUN01-R01','retest'),('P1FUN01-R02','retest'),('P1FUN01-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,'P1-FUN-01','{}'::text[],k.role,'withheld','draft','Original iClub-authored stem, distractors, answer and explanation; no Cambridge/coursebook wording copied.','Authored for p1_foundations_runway_v1 from canonical P1-FUN-01 intent using independent examples.','Cambridge 9709 2026-2027 v4; P1 1.2 Functions','Complete Pure Mathematics 1, Ch2 Functions and transformations pp.24-42 (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,''))) from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_foundations_runway_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;
commit;
