-- AI-4 Chemistry Practice 1 deterministic diagnostic batch: Atomic structure.
-- Adds option-level mappings for 11 MCQs and exact/fallback mappings for 4 input questions.
-- Server scoring remains authoritative from questions.correct_answer; these rows only
-- classify and explain an already-checked answer. No learner history is backfilled.

do $guard$
declare
  v_bad integer;
begin
  with expected(question_id,subtopic,qtype,correct_answer,options_en) as (
    values
    (1909,'Deflection in an electric field','mcq','C','["Protons","Neutrons","Electrons","All equally"]'::jsonb),
    (1914,'Formation of positive ions','mcq','B','["Gain of an electron","Loss of an electron","Gain of a proton","Absorption of a neutron"]'::jsonb),
    (1916,'Properties of a neutral atom','mcq','C','["Number of protons greater than electrons","Number of electrons greater than neutrons","Number of protons equals number of electrons","Number of neutrons equals number of electrons"]'::jsonb),
    (1921,'Charge of a neutron','mcq','C','["Positive","Negative","Zero","Variable"]'::jsonb),
    (1925,'Periodic table position','mcq','C','["Number of neutrons","Number of electron shells","Number of protons","Mass number"]'::jsonb),
    (1929,'Particle not deflected in an electric field','mcq','C','["Proton","Electron","Neutron","Ion"]'::jsonb),
    (1933,'Mass number','mcq','C','["Equal to number of protons","Equal to number of neutrons","Equal to protons plus neutrons","Equal to number of electrons"]'::jsonb),
    (1943,'Relative atomic mass (Ar)','mcq','B','["Mass of one atom in grams","Weighted mean mass compared with 1/12 of a carbon-12 atom","Sum of masses of protons and electrons","Number of protons in the nucleus"]'::jsonb),
    (1944,'Electrons in Cl⁻','input','18',null::jsonb),
    (1954,'Neutrons in copper isotope','input','34',null::jsonb),
    (1959,'Smallest relative mass of subatomic particles','mcq','C','["Proton","Neutron","Electron","Ion"]'::jsonb),
    (1964,'Electrons in Fe³⁺','input','23',null::jsonb),
    (3041,'Rutherford scattering and the nucleus','mcq','B','["Because the atom is completely filled with electrons","Because the positive charge and almost all the mass are concentrated in a very small nucleus","Because neutrons strongly repel alpha particles","Because electrons are heavier than alpha particles"]'::jsonb),
    (3043,'Electron count in aluminium ion','input','10',null::jsonb),
    (3044,'Mass and charge in the nucleus','mcq','A','["The nucleus contains almost all of the mass of the atom and has a positive charge","The nucleus contains only electrons and has no charge","The nucleus occupies almost all of the volume of the atom","The nucleus contains only neutrons"]'::jsonb)
  )
  select count(*) into v_bad
  from expected e
  left join public.questions q on q.id=e.question_id
  where q.id is null
     or q.subject_id<>4
     or q.is_active is not true
     or q.quality_status<>'published'
     or q.topic<>'Atomic structure'
     or q.subtopic<>e.subtopic
     or lower(coalesce(q.qtype,''))<>e.qtype
     or trim(coalesce(q.correct_answer,''))<>e.correct_answer
     or (e.qtype='mcq' and coalesce(q.options_text_en,'[]')::jsonb is distinct from e.options_en)
     or (e.qtype='input' and coalesce(q.options_text_en,'[]')::jsonb<>'[]'::jsonb);

  if v_bad<>0 then
    raise exception 'AI-4 Chemistry Atomic structure diagnostic batch refused: one or more target questions changed';
  end if;

  if exists (
    select 1
    from public.question_answer_diagnostics
    where question_id in (1909,1914,1916,1921,1925,1929,1933,1943,1944,1954,1959,1964,3041,3043,3044)
      and quality_status='published'
  ) then
    raise exception 'AI-4 Chemistry Atomic structure diagnostic batch refused: published mappings already exist for a target question';
  end if;
end
$guard$;

insert into public.question_answer_diagnostics(
  question_id,answer_kind,answer_key,answer_value,is_correct,mistake_type,weak_skill,
  feedback_ru,feedback_uz,feedback_en,
  next_action_ru,next_action_uz,next_action_en,
  recommended_topic,recommended_subtopic,rule_json,quality_status
)
values
(1909,'mcq_option','A','Protons',false,'mass_response_confusion','Charge-to-mass ratio in electric-field deflection',
 'Протон заряжен, но он намного тяжелее электрона. При одинаковом модуле заряда и скорости его ускорение в электрическом поле меньше, поэтому он отклоняется слабее.','Proton zaryadlangan, lekin elektrondan ancha og‘ir. Zaryad moduli va tezlik bir xil bo‘lsa, elektr maydonidagi tezlanishi kichikroq bo‘ladi va kamroq og‘adi.','A proton is charged, but it is far heavier than an electron. With the same charge magnitude and speed, its acceleration in the electric field is smaller, so it is deflected less.',
 'Сравните силу и ускорение через F = qE и a = F/m.','F = qE va a = F/m orqali kuch va tezlanishni solishtiring.','Compare electric force and acceleration using F = qE and a = F/m.',
 'Atomic structure','Deflection in an electric field','{}'::jsonb,'published'),
(1909,'mcq_option','B','Neutrons',false,'neutral_particle_confusion','Charge and electric-field deflection',
 'Нейтрон имеет нулевой электрический заряд, поэтому электрическое поле его не отклоняет.','Neytronning elektr zaryadi nol, shuning uchun elektr maydoni uni og‘dirmaydi.','A neutron has zero electric charge, so an electric field does not deflect it.',
 'Повторите, какие субатомные частицы имеют заряд.','Qaysi subatom zarrachalar zaryadga ega ekanini takrorlang.','Review which subatomic particles carry charge.',
 'Atomic structure','Deflection in an electric field','{}'::jsonb,'published'),
(1909,'mcq_option','C','Electrons',true,null,null,
 'Верно: электрон отклоняется сильнее всего, потому что его заряд по модулю равен заряду протона, но масса намного меньше.','To‘g‘ri: elektron eng ko‘p og‘adi, chunki uning zaryad moduli protonnikiga teng, massasi esa ancha kichik.','Correct: the electron is deflected most because it has the same charge magnitude as a proton but much smaller mass.',
 'Свяжите большее отношение заряда к массе с большим отклонением.','Kattaroq zaryad/massa nisbatini kattaroq og‘ish bilan bog‘lang.','Link greater charge-to-mass ratio to greater deflection.',
 'Atomic structure','Deflection in an electric field','{}'::jsonb,'published'),
(1909,'mcq_option','D','All equally',false,'equal_deflection_assumption','Charge-to-mass ratio and neutrality',
 'Пучки отклоняются не одинаково: частицы имеют разные заряды и массы. Нейтрон нейтрален, а отношение заряда к массе у электрона намного больше, чем у протона.','Nurlar bir xil og‘maydi, chunki zarrachalarning zaryadi va massasi turlicha. Neytron neytral, elektronning zaryad/massa nisbati esa protonnikidan ancha katta.','The beams are not deflected equally because the particles have different charges and masses. The neutron is uncharged and the electron has a much larger charge-to-mass ratio than the proton.',
 'Перед выводом сравните заряд и массу каждой частицы.','Og‘ishni aniqlashdan oldin har bir zarrachaning zaryadi va massasini solishtiring.','Compare charge and mass for each particle before predicting deflection.',
 'Atomic structure','Deflection in an electric field','{}'::jsonb,'published'),
(1914,'mcq_option','A','Gain of an electron',false,'ion_charge_direction_error','Electron gain/loss and ionic charge',
 'Присоединение электрона добавляет отрицательный заряд и образует отрицательный, а не положительный ион.','Elektron qabul qilish manfiy zaryad qo‘shadi va musbat emas, manfiy ion hosil qiladi.','Gaining an electron adds negative charge and forms a negative ion, not a positive ion.',
 'Повторите, как присоединение и потеря электронов меняют заряд иона.','Elektron qabul qilish va yo‘qotish ion zaryadini qanday o‘zgartirishini takrorlang.','Review how electron gain and loss change ionic charge.',
 'Atomic structure','Formation of positive ions','{}'::jsonb,'published'),
(1914,'mcq_option','B','Loss of an electron',true,null,null,
 'Верно: положительный ион образуется, когда атом теряет один или несколько электронов.','To‘g‘ri: musbat ion atom bir yoki bir nechta elektron yo‘qotganda hosil bo‘ladi.','Correct: a positive ion forms when an atom loses one or more electrons.',
 'Свяжите потерю отрицательного заряда с положительным суммарным зарядом.','Manfiy zaryad yo‘qotilishini umumiy musbat zaryad bilan bog‘lang.','Link loss of negative charge to a positive net charge.',
 'Atomic structure','Formation of positive ions','{}'::jsonb,'published'),
(1914,'mcq_option','C','Gain of a proton',false,'nuclear_change_vs_ionisation','Ion formation vs nuclear change',
 'При обычном образовании иона меняется число электронов, а не протонов. Изменение числа протонов меняет сам элемент.','Oddiy ion hosil bo‘lishida elektronlar soni o‘zgaradi, protonlar soni emas. Protonlar sonini o‘zgartirish elementning o‘zini o‘zgartiradi.','Ordinary ion formation changes the number of electrons, not the number of protons. Changing proton number changes the element itself.',
 'Отделяйте перенос электронов от изменений в ядре.','Elektron almashinuvini yadrodagi o‘zgarishlardan ajrating.','Separate electron transfer from changes inside the nucleus.',
 'Atomic structure','Formation of positive ions','{}'::jsonb,'published'),
(1914,'mcq_option','D','Absorption of a neutron',false,'isotope_vs_ion_confusion','Neutrons vs ionic charge',
 'Добавление нейтрона меняет изотоп или массовое число, но нейтрон не имеет заряда и не создаёт положительный ион.','Neytron qo‘shish izotop yoki massa sonini o‘zgartiradi, lekin neytron zaryadsiz va musbat ion hosil qilmaydi.','Adding a neutron changes the isotope or mass number, but a neutron has no charge and does not create a positive ion.',
 'Повторите роли протонов, нейтронов и электронов в определении элемента, массы и заряда.','Proton, neytron va elektronlarning element, massa va zaryaddagi rolini takrorlang.','Review the roles of protons, neutrons and electrons in identity, mass and charge.',
 'Atomic structure','Formation of positive ions','{}'::jsonb,'published'),
(1916,'mcq_option','A','Number of protons greater than electrons',false,'neutrality_charge_balance_error','Charge balance in atoms',
 'Если протонов больше, чем электронов, частица имеет положительный суммарный заряд и не является нейтральной.','Agar protonlar elektronlardan ko‘p bo‘lsa, zarrachaning umumiy zaryadi musbat bo‘ladi va u neytral emas.','If protons outnumber electrons, the particle has a net positive charge and is not neutral.',
 'Используйте заряды протонов и электронов для проверки нейтральности.','Neytrallikni tekshirish uchun proton va elektron zaryadlaridan foydalaning.','Use proton and electron charges to test neutrality.',
 'Atomic structure','Properties of a neutral atom','{}'::jsonb,'published'),
(1916,'mcq_option','B','Number of electrons greater than neutrons',false,'neutron_charge_confusion','Neutrality and subatomic charges',
 'Число нейтронов не определяет электрическую нейтральность, потому что нейтроны имеют нулевой заряд.','Neytronlar soni elektr neytralligini belgilamaydi, chunki neytron zaryadi nol.','The number of neutrons does not determine electrical neutrality because neutrons have zero charge.',
 'При определении суммарного заряда учитывайте заряженные частицы.','Umumiy zaryadni tekshirishda zaryadlangan zarrachalarga e’tibor qarating.','Focus on charged particles when checking total charge.',
 'Atomic structure','Properties of a neutral atom','{}'::jsonb,'published'),
(1916,'mcq_option','C','Number of protons equals number of electrons',true,null,null,
 'Верно: в нейтральном атоме число протонов равно числу электронов.','To‘g‘ri: neytral atomda protonlar soni elektronlar soniga teng.','Correct: in a neutral atom, the number of protons equals the number of electrons.',
 'Свяжите равное число положительных и отрицательных зарядов с нулевым суммарным зарядом.','Musbat va manfiy zaryadlar tengligini nol umumiy zaryad bilan bog‘lang.','Link equal positive and negative charges to zero net charge.',
 'Atomic structure','Properties of a neutral atom','{}'::jsonb,'published'),
(1916,'mcq_option','D','Number of neutrons equals number of electrons',false,'neutron_electron_equality_confusion','Neutrality and particle counts',
 'Для нейтральности не требуется равенство числа нейтронов и электронов. Нейтральность зависит от равенства протонов и электронов.','Neytrallik uchun neytronlar soni elektronlar soniga teng bo‘lishi shart emas. Neytrallik protonlar va elektronlar sonining tengligiga bog‘liq.','There is no neutrality rule requiring neutrons to equal electrons. Neutrality depends on equal proton and electron numbers.',
 'Повторите заряды +1, 0 и -1 у субатомных частиц.','Subatom zarrachalarning +1, 0 va -1 zaryadlarini takrorlang.','Review which particles carry +1, 0 and -1 charge.',
 'Atomic structure','Properties of a neutral atom','{}'::jsonb,'published'),
(1921,'mcq_option','A','Positive',false,'proton_neutron_charge_confusion','Subatomic particle charges',
 'Положительный заряд имеет протон. Нейтрон электрически нейтрален.','Musbat zaryad protonga tegishli. Neytron elektr jihatdan neytral.','Positive charge belongs to a proton. A neutron is electrically neutral.',
 'Повторите заряды протона, нейтрона и электрона.','Proton, neytron va elektron zaryadlarini takrorlang.','Review proton, neutron and electron charges.',
 'Atomic structure','Charge of a neutron','{}'::jsonb,'published'),
(1921,'mcq_option','B','Negative',false,'electron_neutron_charge_confusion','Subatomic particle charges',
 'Отрицательный заряд имеет электрон. Нейтрон имеет нулевой заряд.','Manfiy zaryad elektronga tegishli. Neytronning zaryadi nol.','Negative charge belongs to an electron. A neutron has zero charge.',
 'Повторите заряды протона, нейтрона и электрона.','Proton, neytron va elektron zaryadlarini takrorlang.','Review proton, neutron and electron charges.',
 'Atomic structure','Charge of a neutron','{}'::jsonb,'published'),
(1921,'mcq_option','C','Zero',true,null,null,
 'Верно: нейтрон имеет нулевой электрический заряд.','To‘g‘ri: neytronning elektr zaryadi nol.','Correct: a neutron has zero electric charge.',
 'Разделяйте заряд и относительную массу частицы.','Zaryad va nisbiy massani alohida zarracha xossalari sifatida ko‘ring.','Keep charge and relative mass as separate particle properties.',
 'Atomic structure','Charge of a neutron','{}'::jsonb,'published'),
(1921,'mcq_option','D','Variable',false,'variable_neutron_charge_error','Fixed charge of subatomic particles',
 'Обычный электрический заряд нейтрона не является переменным; его суммарный заряд равен нулю.','Neytronning odatiy elektr zaryadi o‘zgaruvchan emas; uning umumiy zaryadi nol.','A neutron does not have a variable ordinary electric charge; its net charge is zero.',
 'Запомните постоянные относительные заряды протона, нейтрона и электрона.','Proton, neytron va elektronning doimiy nisbiy zaryadlarini yodda tuting.','Memorize the fixed relative charges of proton, neutron and electron.',
 'Atomic structure','Charge of a neutron','{}'::jsonb,'published'),
(1925,'mcq_option','A','Number of neutrons',false,'isotope_element_identity_confusion','Atomic number and element identity',
 'Число нейтронов может различаться у изотопов одного элемента, поэтому оно не определяет положение элемента в Периодической таблице.','Bir element izotoplarida neytronlar soni turlicha bo‘lishi mumkin, shuning uchun u elementning Davriy jadvaldagi o‘rnini belgilamaydi.','Neutron number can vary between isotopes of the same element, so it does not define the element’s position in the Periodic Table.',
 'Свяжите идентичность элемента с атомным номером, а не числом нейтронов.','Elementni atom raqami bilan bog‘lang, neytronlar soni bilan emas.','Link element identity to atomic number, not neutron number.',
 'Atomic structure','Periodic table position','{}'::jsonb,'published'),
(1925,'mcq_option','B','Number of electron shells',false,'period_vs_full_position_confusion','Atomic number and Periodic Table ordering',
 'Число занятых оболочек помогает определить период, но уникальное положение элемента в современной Периодической таблице определяется атомным номером.','Band elektron qavatlar soni davrni aniqlashga yordam beradi, lekin elementning zamonaviy Davriy jadvaldagi aniq o‘rni atom raqami bilan belgilanadi.','The number of occupied shells helps identify the period, but the element’s unique position in the modern Periodic Table is determined by atomic number.',
 'Отделяйте номер периода от расположения элементов по атомному номеру.','Davr raqamini elementlarning atom raqami bo‘yicha tartibidan farqlang.','Distinguish period number from the atomic-number ordering of elements.',
 'Atomic structure','Periodic table position','{}'::jsonb,'published'),
(1925,'mcq_option','C','Number of protons',true,null,null,
 'Верно: число протонов — это атомный номер, который однозначно определяет элемент и его положение в современной Периодической таблице.','To‘g‘ri: protonlar soni atom raqami bo‘lib, elementni aniq belgilaydi va zamonaviy Davriy jadvaldagi o‘rnini aniqlaydi.','Correct: the number of protons is the atomic number, which uniquely identifies the element and determines its position in the modern Periodic Table.',
 'Свяжите число протонов, атомный номер и идентичность элемента.','Protonlar soni, atom raqami va element identifikatsiyasini bog‘lang.','Connect proton number, atomic number and element identity.',
 'Atomic structure','Periodic table position','{}'::jsonb,'published'),
(1925,'mcq_option','D','Mass number',false,'mass_number_element_identity_confusion','Mass number vs atomic number',
 'Массовое число может различаться у изотопов одного элемента. Порядок в Периодической таблице основан на атомном номере, а не массовом числе.','Massa soni bir element izotoplarida farq qilishi mumkin. Davriy jadval tartibi massa soniga emas, atom raqamiga asoslanadi.','Mass number can differ between isotopes of the same element. Periodic Table order is based on atomic number, not mass number.',
 'Сравните A = протоны + нейтроны и Z = протоны.','A = protonlar + neytronlar va Z = protonlarni solishtiring.','Compare A = protons + neutrons with Z = protons.',
 'Atomic structure','Periodic table position','{}'::jsonb,'published'),
(1929,'mcq_option','A','Proton',false,'charged_particle_field_confusion','Electric-field force and charge',
 'Протон имеет положительный заряд, поэтому электрическое поле действует на него силой и может отклонить.','Proton musbat zaryadga ega, shuning uchun elektr maydoni unga kuch bilan ta’sir qilib, og‘dirishi mumkin.','A proton has positive charge, so an electric field exerts a force on it and can deflect it.',
 'Используйте F = qE, чтобы определить действие поля на частицу.','Zarracha maydondan ta’sir olishini aniqlash uchun F = qE dan foydalaning.','Use F = qE to decide whether a particle is affected.',
 'Atomic structure','Particle not deflected in an electric field','{}'::jsonb,'published'),
(1929,'mcq_option','B','Electron',false,'charged_particle_field_confusion','Electric-field force and charge',
 'Электрон имеет отрицательный заряд, поэтому отклоняется в электрическом поле в направлении, противоположном положительному заряду.','Elektron manfiy zaryadga ega, shuning uchun elektr maydonida musbat zaryadga qarama-qarshi yo‘nalishda og‘adi.','An electron has negative charge, so it is deflected in an electric field, in the opposite direction to a positive charge.',
 'Повторите, как знак заряда влияет на направление отклонения.','Zaryad ishorasi og‘ish yo‘nalishiga qanday ta’sir qilishini takrorlang.','Review how the sign of charge affects deflection direction.',
 'Atomic structure','Particle not deflected in an electric field','{}'::jsonb,'published'),
(1929,'mcq_option','C','Neutron',true,null,null,
 'Верно: нейтрон имеет нулевой заряд, поэтому электрическое поле не действует на него электрической силой.','To‘g‘ri: neytronning zaryadi nol, shuning uchun elektr maydoni unga elektr kuchi bilan ta’sir qilmaydi.','Correct: a neutron has zero charge, so an electric field exerts no electric force on it.',
 'Свяжите нулевой заряд с нулевой электрической силой.','Nol zaryadni nol elektr kuchi bilan bog‘lang.','Link zero charge to zero electric force.',
 'Atomic structure','Particle not deflected in an electric field','{}'::jsonb,'published'),
(1929,'mcq_option','D','Ion',false,'ion_charge_definition_error','Ions and electric charge',
 'Ион по определению имеет суммарный электрический заряд, поэтому может отклоняться электрическим полем.','Ion ta’rifiga ko‘ra umumiy elektr zaryadiga ega, shuning uchun elektr maydoni uni og‘dirishi mumkin.','An ion has a net electric charge by definition, so it can be deflected by an electric field.',
 'Вспомните, что ион возникает при нарушении баланса электронов и протонов.','Ion elektron va proton sonlari muvozanati buzilganda hosil bo‘lishini eslang.','Recall that ions form when electron and proton counts no longer balance.',
 'Atomic structure','Particle not deflected in an electric field','{}'::jsonb,'published'),
(1933,'mcq_option','A','Equal to number of protons',false,'mass_number_atomic_number_confusion','Mass number vs atomic number',
 'Только число протонов — это атомный номер Z, а не массовое число A.','Faqat protonlar soni atom raqami Z bo‘ladi, massa soni A emas.','The number of protons alone is the atomic number Z, not the mass number A.',
 'Сравните Z = p и A = p + n.','Z = p va A = p + n ni solishtiring.','Compare Z = p with A = p + n.',
 'Atomic structure','Mass number','{}'::jsonb,'published'),
(1933,'mcq_option','B','Equal to number of neutrons',false,'mass_number_neutron_only_error','Mass number composition',
 'Массовое число включает и протоны, и нейтроны, а не только нейтроны.','Massa soni faqat neytronlarni emas, proton va neytronlarning ikkalasini ham o‘z ichiga oladi.','Mass number includes both protons and neutrons, not neutrons alone.',
 'Повторите, какие частицы относятся к нуклонам.','Qaysi zarrachalar nuklon ekanini takrorlang.','Review which particles are nucleons.',
 'Atomic structure','Mass number','{}'::jsonb,'published'),
(1933,'mcq_option','C','Equal to protons plus neutrons',true,null,null,
 'Верно: массовое число равно общему числу протонов и нейтронов в ядре.','To‘g‘ri: massa soni yadrodagi protonlar va neytronlar umumiy soniga teng.','Correct: mass number is the total number of protons plus neutrons in the nucleus.',
 'Используйте A = Z + N в расчётах изотопов.','Izotop hisoblarida A = Z + N dan foydalaning.','Use A = Z + N in isotope calculations.',
 'Atomic structure','Mass number','{}'::jsonb,'published'),
(1933,'mcq_option','D','Equal to number of electrons',false,'electron_mass_number_confusion','Nuclear composition and mass number',
 'Электроны не входят в массовое число. Массовое число учитывает нуклоны в ядре.','Elektronlar massa soniga kiritilmaydi. Massa soni yadrodagi nuklonlarni hisoblaydi.','Electrons are not included in mass number. Mass number counts nucleons in the nucleus.',
 'Отделяйте число частиц ядра от числа электронов.','Yadro zarrachalari sonini elektronlar sonidan ajrating.','Separate nuclear particle counts from electron counts.',
 'Atomic structure','Mass number','{}'::jsonb,'published'),
(1943,'mcq_option','A','Mass of one atom in grams',false,'relative_absolute_mass_confusion','Definition of relative atomic mass',
 'Относительная атомная масса — это безразмерная относительная шкала, а не масса одного атома, непосредственно измеренная в граммах.','Nisbiy atom massasi o‘lchovsiz nisbiy shkala bo‘lib, bitta atomning grammdagi to‘g‘ridan-to‘g‘ri massasi emas.','Relative atomic mass is a dimensionless relative scale, not the mass of one atom measured directly in grams.',
 'Повторите значение слова «относительная» в Ar.','Ar dagi “nisbiy” so‘zining ma’nosini takrorlang.','Review what the word relative means in Ar.',
 'Atomic structure','Relative atomic mass (Ar)','{}'::jsonb,'published'),
(1943,'mcq_option','B','Weighted mean mass compared with 1/12 of a carbon-12 atom',true,null,null,
 'Верно: Ar — средневзвешенная атомная масса по сравнению с одной двенадцатой массы атома углерода-12.','To‘g‘ri: Ar atomlarning og‘irliklangan o‘rtacha massasini uglerod-12 atomi massasining o‘n ikkidan bir qismiga nisbatan ifodalaydi.','Correct: Ar is the weighted mean atomic mass compared with one twelfth of the mass of a carbon-12 atom.',
 'Свяжите распространённость изотопов со средневзвешенным значением.','Izotop tarqalishini og‘irliklangan o‘rtacha qiymat bilan bog‘lang.','Link isotope abundance to the weighted mean.',
 'Atomic structure','Relative atomic mass (Ar)','{}'::jsonb,'published'),
(1943,'mcq_option','C','Sum of masses of protons and electrons',false,'ar_particle_sum_confusion','Relative atomic mass and isotopic abundance',
 'Ar не находят сложением масс протонов и электронов. Это средневзвешенное значение по природным изотопам на шкале углерода-12.','Ar proton va elektron massalarini qo‘shish orqali topilmaydi. U tabiiy izotoplar bo‘yicha uglerod-12 nisbiy shkalasidagi og‘irliklangan o‘rtacha qiymatdir.','Ar is not found by adding proton and electron masses. It is a weighted mean across naturally occurring isotopes on the carbon-12 relative scale.',
 'Повторите определение Ar через распространённость изотопов.','Ar ning izotop tarqalishiga asoslangan ta’rifini takrorlang.','Review the isotope-abundance definition of Ar.',
 'Atomic structure','Relative atomic mass (Ar)','{}'::jsonb,'published'),
(1943,'mcq_option','D','Number of protons in the nucleus',false,'ar_atomic_number_confusion','Relative atomic mass vs atomic number',
 'Число протонов — это атомный номер Z. Относительная атомная масса Ar — средневзвешенная масса, а не число протонов.','Protonlar soni atom raqami Z. Nisbiy atom massasi Ar esa og‘irliklangan massa qiymati, protonlar soni emas.','The number of protons is atomic number Z. Relative atomic mass Ar is a weighted mass value, not a proton count.',
 'Различайте Z, A и Ar.','Z, A va Ar ni farqlang.','Separate Z, A and Ar.',
 'Atomic structure','Relative atomic mass (Ar)','{}'::jsonb,'published'),
(1959,'mcq_option','A','Proton',false,'relative_mass_confusion','Relative masses of subatomic particles',
 'Протон имеет относительную массу около 1, что намного больше относительной массы электрона примерно 1/1836.','Protonning nisbiy massasi taxminan 1 bo‘lib, elektronning taxminan 1/1836 nisbiy massasidan ancha katta.','A proton has relative mass close to 1, much greater than the electron’s relative mass of about 1/1836.',
 'Сравните относительные массы протона, нейтрона и электрона.','Proton, neytron va elektronning nisbiy massalarini solishtiring.','Compare proton, neutron and electron relative masses.',
 'Atomic structure','Smallest relative mass of subatomic particles','{}'::jsonb,'published'),
(1959,'mcq_option','B','Neutron',false,'relative_mass_confusion','Relative masses of subatomic particles',
 'Нейтрон имеет относительную массу около 1, намного больше массы электрона.','Neytronning nisbiy massasi taxminan 1 bo‘lib, elektron massasidan ancha katta.','A neutron has relative mass close to 1, much greater than an electron.',
 'Сравните массы нуклонов с массой электрона.','Nuklon massalarini elektron massasi bilan solishtiring.','Compare nucleon masses with electron mass.',
 'Atomic structure','Smallest relative mass of subatomic particles','{}'::jsonb,'published'),
(1959,'mcq_option','C','Electron',true,null,null,
 'Верно: электрон имеет намного меньшую относительную массу, чем перечисленные нуклоны.','To‘g‘ri: elektron sanab o‘tilgan subatom zarrachalar orasida eng kichik nisbiy massaga ega.','Correct: the electron has by far the smallest relative mass of the listed subatomic particles.',
 'Запомните: протон ≈ 1, нейтрон ≈ 1, электрон ≈ 1/1836.','Eslab qoling: proton ≈ 1, neytron ≈ 1, elektron ≈ 1/1836.','Remember proton ≈ 1, neutron ≈ 1, electron ≈ 1/1836.',
 'Atomic structure','Smallest relative mass of subatomic particles','{}'::jsonb,'published'),
(1959,'mcq_option','D','Ion',false,'ion_vs_subatomic_particle_confusion','Particle classification and relative mass',
 'Ион — это атом или группа атомов с суммарным зарядом, а не фундаментальная субатомная частица; его масса намного больше массы электрона.','Ion umumiy zaryadga ega atom yoki atomlar guruhi bo‘lib, fundamental subatom zarracha emas; uning massasi elektron massasidan ancha katta.','An ion is an atom or group of atoms with net charge, not a fundamental subatomic particle, and its mass is much larger than an electron’s.',
 'Отделяйте ионы от протона, нейтрона и электрона.','Ionlarni proton, neytron va elektrondan farqlang.','Distinguish ions from proton, neutron and electron.',
 'Atomic structure','Smallest relative mass of subatomic particles','{}'::jsonb,'published'),
(3041,'mcq_option','A','Because the atom is completely filled with electrons',false,'rutherford_empty_space_confusion','Interpretation of Rutherford scattering',
 'Большинство альфа-частиц проходило через фольгу прямо, показывая, что атом в основном состоит из пустого пространства, а не полностью заполнен электронами.','Alfa-zarrachalarning ko‘pchiligi folgadan to‘g‘ri o‘tgan, bu atom elektronlar bilan to‘liq to‘lgan emas, asosan bo‘sh fazodan iborat ekanini ko‘rsatadi.','Most alpha particles passed straight through the foil, showing that atoms are mostly empty space rather than completely filled with electrons.',
 'Для объяснения опыта учитывайте и частые прямые траектории, и редкие большие отклонения.','Tajriba izohida ko‘p uchraydigan to‘g‘ri yo‘llar va kam uchraydigan katta og‘ishlarning ikkalasini ham hisobga oling.','Use both the common straight paths and rare large deflections to interpret the experiment.',
 'Atomic structure','Rutherford scattering and the nucleus','{}'::jsonb,'published'),
(3041,'mcq_option','B','Because the positive charge and almost all the mass are concentrated in a very small nucleus',true,null,null,
 'Верно: редкие отклонения на большие углы показывают, что положительный заряд и почти вся масса атома сосредоточены в очень маленьком плотном ядре.','To‘g‘ri: katta burchakdagi kam uchraydigan og‘ishlar musbat zaryad va atom massasining deyarli barchasi juda kichik zich yadroda jamlanganini ko‘rsatadi.','Correct: rare large-angle deflections show that positive charge and almost all atomic mass are concentrated in a tiny dense nucleus.',
 'Свяжите большое отклонение с близким прохождением возле концентрированного положительного ядра.','Katta og‘ishni zich musbat yadroga yaqin o‘tish bilan bog‘lang.','Connect large deflection to close approach to a concentrated positive nucleus.',
 'Atomic structure','Rutherford scattering and the nucleus','{}'::jsonb,'published'),
(3041,'mcq_option','C','Because neutrons strongly repel alpha particles',false,'neutron_repulsion_error','Nuclear charge in Rutherford scattering',
 'Нейтроны имеют нулевой заряд и не создают сильного электростатического отталкивания положительных альфа-частиц. Отталкивание связано с положительным зарядом ядра.','Neytronlar zaryadsiz va musbat alfa-zarrachalarni kuchli elektrostatik itarmaydi. Itarilish yadroning musbat zaryadi bilan bog‘liq.','Neutrons have zero charge and do not strongly repel positively charged alpha particles. The repulsion comes from the positive nuclear charge.',
 'Повторите, какая частица ядра создаёт положительный заряд.','Yadroning qaysi zarrachasi musbat zaryad berishini takrorlang.','Review which nuclear particle creates positive charge.',
 'Atomic structure','Rutherford scattering and the nucleus','{}'::jsonb,'published'),
(3041,'mcq_option','D','Because electrons are heavier than alpha particles',false,'electron_mass_error','Relative particle masses in atomic structure',
 'Электроны намного легче альфа-частиц и не могут объяснить редкие отклонения на большие углы.','Elektronlar alfa-zarrachalardan ancha yengil va katta burchakdagi kam uchraydigan og‘ishlarni tushuntira olmaydi.','Electrons are much lighter than alpha particles and cannot explain the rare large-angle deflections.',
 'Сравните массу электрона с концентрированной массой ядра.','Elektron massasini yadroda jamlangan massa bilan solishtiring.','Compare electron mass with concentrated nuclear mass.',
 'Atomic structure','Rutherford scattering and the nucleus','{}'::jsonb,'published'),
(3044,'mcq_option','A','The nucleus contains almost all of the mass of the atom and has a positive charge',true,null,null,
 'Верно: ядро содержит протоны и нейтроны, поэтому имеет положительный заряд и почти всю массу атома.','To‘g‘ri: yadro proton va neytronlardan iborat, shuning uchun musbat zaryadga ega va atom massasining deyarli barchasini saqlaydi.','Correct: the nucleus contains protons and neutrons, so it has positive charge and contains almost all the atom’s mass.',
 'Свяжите протоны с зарядом ядра, а нуклоны — с его массой.','Protonlarni yadro zaryadi, nuklonlarni esa yadro massasi bilan bog‘lang.','Link protons to nuclear charge and nucleons to nuclear mass.',
 'Atomic structure','Mass and charge in the nucleus','{}'::jsonb,'published'),
(3044,'mcq_option','B','The nucleus contains only electrons and has no charge',false,'nucleus_electron_confusion','Composition of the nucleus',
 'Электроны находятся вне ядра. Ядро содержит протоны и нейтроны и имеет положительный заряд из-за протонов.','Elektronlar yadro tashqarisida joylashadi. Yadro proton va neytronlardan iborat va protonlar sababli musbat zaryadga ega.','Electrons occupy the space outside the nucleus. The nucleus contains protons and neutrons and is positively charged because of the protons.',
 'Повторите расположение протонов, нейтронов и электронов.','Proton, neytron va elektronlar qayerda joylashishini takrorlang.','Review where protons, neutrons and electrons are located.',
 'Atomic structure','Mass and charge in the nucleus','{}'::jsonb,'published'),
(3044,'mcq_option','C','The nucleus occupies almost all of the volume of the atom',false,'nucleus_volume_confusion','Scale of nucleus relative to atom',
 'Ядро содержит почти всю массу, но занимает лишь очень малую часть объёма атома. Большая часть объёма связана с электронной областью и пустым пространством.','Yadro deyarli barcha massani saqlaydi, lekin atom hajmining juda kichik qismini egallaydi. Atom hajmining katta qismi elektron sohasi va bo‘sh fazoga to‘g‘ri keladi.','The nucleus contains most of the mass but occupies only a tiny fraction of the atom’s volume. Most atomic volume is the electron region and empty space.',
 'Отделяйте область концентрации массы от области, занимающей объём атома.','Atom massasi jamlangan joyni atom hajmi egallagan sohadan farqlang.','Separate where atomic mass is concentrated from where atomic volume lies.',
 'Atomic structure','Mass and charge in the nucleus','{}'::jsonb,'published'),
(3044,'mcq_option','D','The nucleus contains only neutrons',false,'nucleus_neutron_only_confusion','Composition and charge of nucleus',
 'Ядро содержит и протоны, и нейтроны. Без протонов оно не имело бы характерного положительного заряда.','Yadro proton va neytronlarning ikkalasini ham o‘z ichiga oladi. Protonlarsiz u atom yadrosiga xos musbat zaryadga ega bo‘lmas edi.','The nucleus contains both protons and neutrons. Without protons it would not have the positive charge characteristic of an atomic nucleus.',
 'Повторите два типа нуклонов в обычных ядрах.','Oddiy yadrolardagi ikki tur nuklonni takrorlang.','Review the two nucleons present in ordinary nuclei.',
 'Atomic structure','Mass and charge in the nucleus','{}'::jsonb,'published'),
(1944,'input_exact',null,'18',true,null,null,
 'Верно: ответ 18.','To‘g‘ri: javob 18.','Correct: the answer is 18.',
 'Свяжите правильный результат с соответствующим правилом подсчёта.','To‘g‘ri natijani tegishli hisoblash qoidasi bilan bog‘lang.','Link the correct result to the relevant counting rule.',
 'Atomic structure','Electrons in Cl⁻','{"accepted":"18"}'::jsonb,'published'),
(1944,'fallback',null,null,false,'ion_electron_count_error','Electron count in negative ions',
 'Хлор имеет атомный номер 17, поэтому нейтральный атом содержит 17 электронов. Ион Cl- присоединил один электрон, поэтому содержит 18 электронов.','Xlorning atom raqami 17, shuning uchun neytral atomda 17 elektron bor. Cl- bitta elektron qabul qilgan, demak 18 elektron mavjud.','Chlorine has atomic number 17, so a neutral atom has 17 electrons. Cl- has gained one electron, giving 18 electrons.',
 'Для отрицательного иона прибавьте модуль отрицательного заряда к числу электронов нейтрального атома.','Manfiy ion uchun manfiy zaryad modulini neytral atom elektronlari soniga qo‘shing.','For a negative ion, add the magnitude of the negative charge to the neutral electron count.',
 'Atomic structure','Electrons in Cl⁻','{}'::jsonb,'published'),
(1954,'input_exact',null,'34',true,null,null,
 'Верно: ответ 34.','To‘g‘ri: javob 34.','Correct: the answer is 34.',
 'Свяжите правильный результат с соответствующим правилом подсчёта.','To‘g‘ri natijani tegishli hisoblash qoidasi bilan bog‘lang.','Link the correct result to the relevant counting rule.',
 'Atomic structure','Neutrons in copper isotope','{"accepted":"34"}'::jsonb,'published'),
(1954,'fallback',null,null,false,'neutron_count_error','Calculating neutrons from A and Z',
 'Число нейтронов равно массовому числу минус атомный номер: N = A - Z = 63 - 29 = 34.','Neytronlar soni massa sonidan atom raqamini ayirish orqali topiladi: N = A - Z = 63 - 29 = 34.','Neutron number equals mass number minus atomic number: N = A - Z = 63 - 29 = 34.',
 'Используйте N = A - Z и не смешивайте массовое число с атомным номером.','N = A - Z dan foydalaning va massa sonini atom raqami bilan aralashtirmang.','Use N = A - Z and keep mass number separate from atomic number.',
 'Atomic structure','Neutrons in copper isotope','{}'::jsonb,'published'),
(1964,'input_exact',null,'23',true,null,null,
 'Верно: ответ 23.','To‘g‘ri: javob 23.','Correct: the answer is 23.',
 'Свяжите правильный результат с соответствующим правилом подсчёта.','To‘g‘ri natijani tegishli hisoblash qoidasi bilan bog‘lang.','Link the correct result to the relevant counting rule.',
 'Atomic structure','Electrons in Fe³⁺','{"accepted":"23"}'::jsonb,'published'),
(1964,'fallback',null,null,false,'cation_electron_count_error','Electron count in positive ions',
 'Железо имеет атомный номер 26, поэтому нейтральный атом содержит 26 электронов. Fe3+ потерял три электрона, поэтому содержит 23.','Temirning atom raqami 26, shuning uchun neytral atomda 26 elektron bor. Fe3+ uchta elektron yo‘qotgan, demak 23 elektron qoladi.','Iron has atomic number 26, so a neutral atom has 26 electrons. Fe3+ has lost three electrons, so it contains 23.',
 'Для положительного иона вычитайте величину положительного заряда из числа электронов нейтрального атома.','Musbat ion uchun musbat zaryad qiymatini neytral atom elektronlari sonidan ayiring.','For a positive ion, subtract the positive charge from the neutral electron count.',
 'Atomic structure','Electrons in Fe³⁺','{}'::jsonb,'published'),
(3043,'input_exact',null,'10',true,null,null,
 'Верно: ответ 10.','To‘g‘ri: javob 10.','Correct: the answer is 10.',
 'Свяжите правильный результат с соответствующим правилом подсчёта.','To‘g‘ri natijani tegishli hisoblash qoidasi bilan bog‘lang.','Link the correct result to the relevant counting rule.',
 'Atomic structure','Electron count in aluminium ion','{"accepted":"10"}'::jsonb,'published'),
(3043,'fallback',null,null,false,'cation_electron_count_error','Electron count in positive ions',
 'Алюминий имеет атомный номер 13, поэтому нейтральный атом содержит 13 электронов. Al3+ потерял три электрона, поэтому содержит 10.','Alyuminiyning atom raqami 13, shuning uchun neytral atomda 13 elektron bor. Al3+ uchta elektron yo‘qotgan, demak 10 elektron qoladi.','Aluminium has atomic number 13, so a neutral atom has 13 electrons. Al3+ has lost three electrons, so it contains 10.',
 'Вычтите заряд катиона из числа электронов нейтрального атома.','Kation zaryadini neytral atom elektronlari sonidan ayiring.','Subtract the cation charge from the neutral electron count.',
 'Atomic structure','Electron count in aluminium ion','{}'::jsonb,'published');
