-- P1-02 P1 AW21-24 Integration core: INT-01/02/03.
-- Original iClub-authored content only; legacy questions remain draft + inactive.
begin;

insert into private.exam_prep_content_versions(program_version_id,content_version,component_code,release_label,status,source_policy)
select pv.id,'p1_aw21_24_integration_core_v1','P1','P1 AW21-24 Integration core','draft',
       'Original iClub content only; Cambridge 9709 official syllabus defines scope; Complete Pure Mathematics 1 is mapping/teaching reference only; no protected source wording copied.'
from private.exam_prep_program_versions pv
where pv.program_key='math_as_p1_p5' and pv.version_key='p1_p5_canonical_v1_0'
on conflict(program_version_id,content_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_core_v1' and component_code='P1' and status='draft'),
src(skill,k,role,diff,qen,qru,quz,o_en,o_ru,o_uz,ans,een,eru,euz,secs) as (values
('P1-INT-01','P1INT01-D01','diagnostic','medium','Find an antiderivative of 6x^2−4x+3.','Найдите первообразную для 6x^2−4x+3.','6x^2−4x+3 ning boshlang‘ich funksiyasini toping.','["2x^3−2x^2+3x+C","6x^3−4x^2+3x+C","2x^3−4x^2+3x+C","2x^3−2x^2+3+C"]','["2x^3−2x^2+3x+C","6x^3−4x^2+3x+C","2x^3−4x^2+3x+C","2x^3−2x^2+3+C"]','["2x^3−2x^2+3x+C","6x^3−4x^2+3x+C","2x^3−4x^2+3x+C","2x^3−2x^2+3+C"]','A','Increase each power by 1 and divide by the new power: 6x^2 -> 2x^3, −4x -> −2x^2, 3 -> 3x.','Увеличьте каждую степень на 1 и разделите на новую степень: 6x^2 -> 2x^3, −4x -> −2x^2, 3 -> 3x.','Har bir darajani 1 ga oshirib, yangi darajaga bo‘ling: 6x^2 -> 2x^3, −4x -> −2x^2, 3 -> 3x.',45),
('P1-INT-01','P1INT01-L01','learning','easy','Find ∫5x^4 dx.','Найдите ∫5x^4 dx.','∫5x^4 dx ni toping.','["x^5+C","5x^5+C","x^4+C","25x^5+C"]','["x^5+C","5x^5+C","x^4+C","25x^5+C"]','["x^5+C","5x^5+C","x^4+C","25x^5+C"]','A','∫5x^4 dx = 5x^5/5 = x^5+C.','∫5x^4 dx = x^5+C.','∫5x^4 dx = x^5+C.',25),
('P1-INT-01','P1INT01-L02','learning','medium','Find ∫(2x+3)^4 dx.','Найдите ∫(2x+3)^4 dx.','∫(2x+3)^4 dx ni toping.','["(2x+3)^5/10+C","(2x+3)^5/5+C","2(2x+3)^5/5+C","(2x+3)^3/6+C"]','["(2x+3)^5/10+C","(2x+3)^5/5+C","2(2x+3)^5/5+C","(2x+3)^3/6+C"]','["(2x+3)^5/10+C","(2x+3)^5/5+C","2(2x+3)^5/5+C","(2x+3)^3/6+C"]','A','Reverse the chain rule: divide by the new power 5 and by the inner derivative 2.','Используйте обратное правило цепочки: разделите на новую степень 5 и на внутреннюю производную 2.','Chain rule ni teskari qo‘llang: yangi daraja 5 ga va ichki hosila 2 ga bo‘ling.',40),
('P1-INT-01','P1INT01-L03','learning','medium','Find ∫(3x−1)^(−1/2) dx.','Найдите ∫(3x−1)^(−1/2) dx.','∫(3x−1)^(−1/2) dx ni toping.','["(2/3)(3x−1)^(1/2)+C","2(3x−1)^(1/2)+C","(3/2)(3x−1)^(1/2)+C","−2(3x−1)^(−3/2)+C"]','["(2/3)(3x−1)^(1/2)+C","2(3x−1)^(1/2)+C","(3/2)(3x−1)^(1/2)+C","−2(3x−1)^(−3/2)+C"]','["(2/3)(3x−1)^(1/2)+C","2(3x−1)^(1/2)+C","(3/2)(3x−1)^(1/2)+C","−2(3x−1)^(−3/2)+C"]','A','Raise −1/2 to 1/2, divide by 1/2 and by the inner derivative 3, giving 2/3.','Повышаем степень −1/2 до 1/2 и делим на 1/2 и на внутреннюю производную 3, получая 2/3.','−1/2 darajani 1/2 ga oshirib, 1/2 va ichki hosila 3 ga bo‘ling: 2/3.',45),
('P1-INT-01','P1INT01-R01','retest','easy','Find ∫4x^3 dx.','Найдите ∫4x^3 dx.','∫4x^3 dx ni toping.','["x^4+C","4x^4+C","x^3+C","12x^2+C"]','["x^4+C","4x^4+C","x^3+C","12x^2+C"]','["x^4+C","4x^4+C","x^3+C","12x^2+C"]','A','4x^4/4=x^4.','4x^4/4=x^4.','4x^4/4=x^4.',25),
('P1-INT-01','P1INT01-R02','retest','medium','Find ∫(5x+2)^2 dx.','Найдите ∫(5x+2)^2 dx.','∫(5x+2)^2 dx ni toping.','["(5x+2)^3/15+C","(5x+2)^3/3+C","5(5x+2)^3/3+C","(5x+2)/5+C"]','["(5x+2)^3/15+C","(5x+2)^3/3+C","5(5x+2)^3/3+C","(5x+2)/5+C"]','["(5x+2)^3/15+C","(5x+2)^3/3+C","5(5x+2)^3/3+C","(5x+2)/5+C"]','A','Divide by 3 for the new power and by 5 for the inner derivative.','Разделите на 3 и на внутреннюю производную 5.','Yangi daraja 3 ga va ichki hosila 5 ga bo‘ling.',35),
('P1-INT-01','P1INT01-M01','mixed','medium','Find ∫[4x^3+2(2x+1)^3] dx.','Найдите ∫[4x^3+2(2x+1)^3] dx.','∫[4x^3+2(2x+1)^3] dx ni toping.','["x^4+(2x+1)^4/4+C","x^4+(2x+1)^4/2+C","4x^4+(2x+1)^4/4+C","x^4+2(2x+1)^4+C"]','["x^4+(2x+1)^4/4+C","x^4+(2x+1)^4/2+C","4x^4+(2x+1)^4/4+C","x^4+2(2x+1)^4+C"]','["x^4+(2x+1)^4/4+C","x^4+(2x+1)^4/2+C","4x^4+(2x+1)^4/4+C","x^4+2(2x+1)^4+C"]','A','Integrate termwise. For the second term, u=2x+1 gives 2 dx=du, so ∫2u^3 dx=∫u^3 du=u^4/4.','Интегрируйте по членам. Для второго члена u=2x+1, 2dx=du, поэтому получаем u^4/4.','Hadma-had integrallang. Ikkinchi had uchun u=2x+1, 2dx=du, natija u^4/4.',50),

('P1-INT-02','P1INT02-D01','diagnostic','medium','A curve has dy/dx=6x−4 and passes through (2,5). Find its equation.','Кривая имеет dy/dx=6x−4 и проходит через (2,5). Найдите её уравнение.','Egri chiziq uchun dy/dx=6x−4 va u (2,5) dan o‘tadi. Tenglamani toping.','["y=3x^2−4x+1","y=3x^2−4x+5","y=6x^2−4x+1","y=3x^2−4x"]','["y=3x^2−4x+1","y=3x^2−4x+5","y=6x^2−4x+1","y=3x^2−4x"]','["y=3x^2−4x+1","y=3x^2−4x+5","y=6x^2−4x+1","y=3x^2−4x"]','A','Integrating gives y=3x^2−4x+C. Using (2,5): 5=12−8+C, so C=1.','После интегрирования y=3x^2−4x+C. Из точки (2,5): C=1.','Integrallashdan y=3x^2−4x+C. (2,5) nuqtadan C=1.',50),
('P1-INT-02','P1INT02-L01','learning','easy','Given dy/dx=2x+3 and y=4 when x=0, find y.','Дано dy/dx=2x+3 и y=4 при x=0. Найдите y.','dy/dx=2x+3 va x=0 da y=4. y ni toping.','["x^2+3x+4","x^2+3x","2x^2+3x+4","x^2+3x−4"]','["x^2+3x+4","x^2+3x","2x^2+3x+4","x^2+3x−4"]','["x^2+3x+4","x^2+3x","2x^2+3x+4","x^2+3x−4"]','A','Integrate to x^2+3x+C and use y(0)=4.','Интегрируем до x^2+3x+C и используем y(0)=4.','x^2+3x+C gacha integrallab, y(0)=4 ni ishlating.',35),
('P1-INT-02','P1INT02-L02','learning','easy','Given dy/dx=3x^2 and y(1)=5, find the constant of integration.','Дано dy/dx=3x^2 и y(1)=5. Найдите постоянную интегрирования.','dy/dx=3x^2 va y(1)=5. Integrallash doimiysini toping.','["4","5","1","−4"]','["4","5","1","−4"]','["4","5","1","−4"]','A','y=x^3+C; 5=1+C, so C=4.','y=x^3+C; 5=1+C, значит C=4.','y=x^3+C; 5=1+C, demak C=4.',30),
('P1-INT-02','P1INT02-L03','learning','medium','A curve has dy/dx=6x^2−2 and passes through (1,3). Find y.','Кривая имеет dy/dx=6x^2−2 и проходит через (1,3). Найдите y.','Egri chiziq dy/dx=6x^2−2 va (1,3) dan o‘tadi. y ni toping.','["2x^3−2x+3","2x^3−2x+1","6x^3−2x+3","2x^3−2x"]','["2x^3−2x+3","2x^3−2x+1","6x^3−2x+3","2x^3−2x"]','["2x^3−2x+3","2x^3−2x+1","6x^3−2x+3","2x^3−2x"]','A','y=2x^3−2x+C. At x=1 the polynomial part is 0, so C=3.','y=2x^3−2x+C. При x=1 полиномиальная часть равна 0, поэтому C=3.','y=2x^3−2x+C. x=1 da polinom qismi 0, demak C=3.',40),
('P1-INT-02','P1INT02-R01','retest','easy','Given dy/dx=4x+1 and y(0)=−2, find y.','Дано dy/dx=4x+1 и y(0)=−2. Найдите y.','dy/dx=4x+1 va y(0)=−2. y ni toping.','["2x^2+x−2","4x^2+x−2","2x^2+x+2","2x^2+x"]','["2x^2+x−2","4x^2+x−2","2x^2+x+2","2x^2+x"]','["2x^2+x−2","4x^2+x−2","2x^2+x+2","2x^2+x"]','A','y=2x^2+x+C and C=−2.','y=2x^2+x+C, C=−2.','y=2x^2+x+C, C=−2.',30),
('P1-INT-02','P1INT02-R02','retest','medium','A curve has dy/dx=(2x+1)^2 and y(0)=1. Find C in y=(2x+1)^3/6+C.','Кривая имеет dy/dx=(2x+1)^2 и y(0)=1. Найдите C в y=(2x+1)^3/6+C.','Egri chiziq dy/dx=(2x+1)^2 va y(0)=1. y=(2x+1)^3/6+C dagi C ni toping.','["5/6","1/6","1","−5/6"]','["5/6","1/6","1","−5/6"]','["5/6","1/6","1","−5/6"]','A','At x=0, 1=1/6+C, so C=5/6.','При x=0: 1=1/6+C, поэтому C=5/6.','x=0 da 1=1/6+C, demak C=5/6.',35),
('P1-INT-02','P1INT02-M01','mixed','medium','A curve has dy/dx=3x^2−4 and passes through (2,6). Find its equation.','Кривая имеет dy/dx=3x^2−4 и проходит через (2,6). Найдите её уравнение.','Egri chiziq dy/dx=3x^2−4 va (2,6) dan o‘tadi. Tenglamani toping.','["y=x^3−4x+6","y=x^3−4x","y=3x^3−4x+6","y=x^3−2x+6"]','["y=x^3−4x+6","y=x^3−4x","y=3x^3−4x+6","y=x^3−2x+6"]','["y=x^3−4x+6","y=x^3−4x","y=3x^3−4x+6","y=x^3−2x+6"]','A','y=x^3−4x+C. At x=2 the polynomial part is 0, so C=6.','y=x^3−4x+C. При x=2 полиномиальная часть равна 0, поэтому C=6.','y=x^3−4x+C. x=2 da polinom qismi 0, demak C=6.',40),

('P1-INT-03','P1INT03-D01','diagnostic','medium','Evaluate ∫ from 0 to 2 of (3x^2+1) dx.','Вычислите ∫ от 0 до 2 (3x^2+1) dx.','0 dan 2 gacha ∫(3x^2+1) dx ni hisoblang.','["10","8","13","5"]','["10","8","13","5"]','["10","8","13","5"]','A','An antiderivative is x^3+x. Evaluating gives (8+2)−0=10.','Первообразная x^3+x. Подстановка пределов даёт 10.','Boshlang‘ich funksiya x^3+x. Chegaralarda qiymat 10.',40),
('P1-INT-03','P1INT03-L01','learning','easy','Evaluate ∫ from 1 to 3 of 2x dx.','Вычислите ∫ от 1 до 3 2x dx.','1 dan 3 gacha ∫2x dx ni hisoblang.','["8","4","9","6"]','["8","4","9","6"]','["8","4","9","6"]','A','[x^2]_1^3=9−1=8.','[x^2]_1^3=8.','[x^2]_1^3=8.',25),
('P1-INT-03','P1INT03-L02','learning','medium','Evaluate ∫ from 0 to 1 of (4x^3−2x) dx.','Вычислите ∫ от 0 до 1 (4x^3−2x) dx.','0 dan 1 gacha ∫(4x^3−2x) dx ni hisoblang.','["0","1","−1","2"]','["0","1","−1","2"]','["0","1","−1","2"]','A','An antiderivative is x^4−x^2, which is 0 at both endpoints.','Первообразная x^4−x^2, она равна 0 на обоих концах.','Boshlang‘ich funksiya x^4−x^2, ikkala chegarada ham 0.',30),
('P1-INT-03','P1INT03-L03','learning','medium','Evaluate the convergent endpoint integral ∫ from 0 to 4 of x^(−1/2) dx.','Вычислите сходящийся интеграл с особой конечной точкой ∫ от 0 до 4 x^(−1/2) dx.','0 dan 4 gacha x^(−1/2) dx yaqinlashuvchi chegara integralini hisoblang.','["4","2","8","undefined/divergent"]','["4","2","8","не определён/расходится"]','["4","2","8","aniqlanmagan/uzoqlashadi"]','A','Use the limit at 0: ∫x^(−1/2)dx=2sqrt(x), so the value is 2sqrt(4)−lim_{a->0+}2sqrt(a)=4.','Используем предел при 0: первообразная 2sqrt(x), итог 4.','0 dagi limitdan foydalaning: boshlang‘ich funksiya 2sqrt(x), natija 4.',45),
('P1-INT-03','P1INT03-R01','retest','easy','Evaluate ∫ from 0 to 2 of 3x^2 dx.','Вычислите ∫ от 0 до 2 3x^2 dx.','0 dan 2 gacha ∫3x^2 dx ni hisoblang.','["8","6","12","4"]','["8","6","12","4"]','["8","6","12","4"]','A','[x^3]_0^2=8.','[x^3]_0^2=8.','[x^3]_0^2=8.',25),
('P1-INT-03','P1INT03-R02','retest','medium','Evaluate ∫ from 1 to 4 of x^(−1/2) dx.','Вычислите ∫ от 1 до 4 x^(−1/2) dx.','1 dan 4 gacha ∫x^(−1/2) dx ni hisoblang.','["2","4","1","3"]','["2","4","1","3"]','["2","4","1","3"]','A','[2sqrt(x)]_1^4=4−2=2.','[2sqrt(x)]_1^4=2.','[2sqrt(x)]_1^4=2.',30),
('P1-INT-03','P1INT03-M01','mixed','medium','Evaluate ∫ from −1 to 2 of (2x+3) dx.','Вычислите ∫ от −1 до 2 (2x+3) dx.','−1 dan 2 gacha ∫(2x+3) dx ni hisoblang.','["12","10","8","6"]','["12","10","8","6"]','["12","10","8","6"]','A','[x^2+3x]_{−1}^2=10−(−2)=12.','[x^2+3x]_{−1}^2=12.','[x^2+3x]_{−1}^2=12.',35)
)
insert into public.questions(subject_id,topic,subtopic,difficulty,qtype,question_text,options_text,correct_answer,explanation,image_url,is_active,question_text_ru,question_text_uz,question_text_en,options_text_ru,options_text_uz,options_text_en,explanation_ru,explanation_uz,explanation_en,book_ref,time_limit_sec,quality_flag,quality_status)
select 5,'P1 Integration',s.skill,s.diff,'mcq',s.qen,s.o_en,s.ans,s.een,null,false,s.qru,s.quz,s.qen,s.o_ru,s.o_uz,s.o_en,s.eru,s.euz,s.een,'ExamPrep:P1:p1_aw21_24_integration_core_v1:'||s.k,s.secs,null,'draft'
from cv cross join src s where not exists(select 1 from public.questions q where q.book_ref='ExamPrep:P1:p1_aw21_24_integration_core_v1:'||s.k);

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_core_v1' and status='draft'), keys(skill,k,role) as (values
('P1-INT-01','P1INT01-D01','diagnostic'),('P1-INT-01','P1INT01-L01','learning'),('P1-INT-01','P1INT01-L02','learning'),('P1-INT-01','P1INT01-L03','learning'),('P1-INT-01','P1INT01-R01','retest'),('P1-INT-01','P1INT01-R02','retest'),('P1-INT-01','P1INT01-M01','mixed'),
('P1-INT-02','P1INT02-D01','diagnostic'),('P1-INT-02','P1INT02-L01','learning'),('P1-INT-02','P1INT02-L02','learning'),('P1-INT-02','P1INT02-L03','learning'),('P1-INT-02','P1INT02-R01','retest'),('P1-INT-02','P1INT02-R02','retest'),('P1-INT-02','P1INT02-M01','mixed'),
('P1-INT-03','P1INT03-D01','diagnostic'),('P1-INT-03','P1INT03-L01','learning'),('P1-INT-03','P1INT03-L02','learning'),('P1-INT-03','P1INT03-L03','learning'),('P1-INT-03','P1INT03-R01','retest'),('P1-INT-03','P1INT03-R02','retest'),('P1-INT-03','P1INT03-M01','mixed'))
insert into private.exam_prep_question_content_meta(content_version_id,content_key,question_id,primary_skill_code,secondary_skill_codes,reserve_role,exposure_state,lifecycle_state,originality_attestation,provenance_note,official_scope_ref,coursebook_mapping_ref,copyright_status,qa_scope_status,qa_math_status,qa_language_status,qa_technical_status,diagnostic_rule_status,question_snapshot_md5)
select cv.id,k.k,q.id,k.skill,'{}'::text[],k.role,'withheld','draft','Original iClub-authored content; no protected source wording copied.','Authored for p1_aw21_24_integration_core_v1 from canonical integration skill intent.','Cambridge 9709 2026-2027 v4; P1 1.8 Integration','Complete Pure Mathematics 1; Integration (mapping only)','pending','pending','pending','pending','pending',case when k.role='diagnostic' then 'pending' else 'not_applicable' end,
md5(concat_ws(chr(31),q.id::text,q.subject_id::text,coalesce(q.topic,''),coalesce(q.subtopic,''),coalesce(q.difficulty,''),coalesce(q.qtype,''),coalesce(q.question_text,''),coalesce(q.options_text,''),coalesce(q.correct_answer,''),coalesce(q.explanation,''),coalesce(q.image_url,''),coalesce(q.is_active::text,''),coalesce(q.question_text_ru,''),coalesce(q.question_text_uz,''),coalesce(q.question_text_en,''),coalesce(q.options_text_ru,''),coalesce(q.options_text_uz,''),coalesce(q.options_text_en,''),coalesce(q.explanation_ru,''),coalesce(q.explanation_uz,''),coalesce(q.explanation_en,''),coalesce(q.book_ref,''),coalesce(q.time_limit_sec::text,''),coalesce(q.quality_flag,''),coalesce(q.quality_status,'')))
from cv cross join keys k join public.questions q on q.book_ref='ExamPrep:P1:p1_aw21_24_integration_core_v1:'||k.k
on conflict(content_version_id,content_key) do nothing;

with meta as (select m.id,m.content_key,m.primary_skill_code from private.exam_prep_question_content_meta m join private.exam_prep_content_versions cv on cv.id=m.content_version_id where cv.content_version='p1_aw21_24_integration_core_v1' and m.reserve_role='diagnostic'), r(ckey,match,dcode,mtype,fen,fru,fuz,nen,nru,nuz) as (values
('P1INT01-D01','B','does_not_divide_new_power','method','When integrating x^n, divide by n+1. Keeping the original coefficients after raising powers gives an antiderivative whose derivative is too large.','При интегрировании x^n нужно делить на n+1. Простое повышение степени без деления даёт слишком большую производную.','x^n ni integrallaganda n+1 ga bo‘lish kerak. Darajani oshirib koeffitsientni o‘zgartirmaslik noto‘g‘ri.','Differentiate your candidate to check it returns the original integrand.','Продifferенцируйте ответ и проверьте исходный интегранд.','Javobingizni hosila olib tekshiring.'),
('P1INT01-D01','C','linear_term_coefficient_error','method','∫−4x dx is −2x^2, not −4x^2; divide by the new power 2.','∫−4x dx = −2x^2, а не −4x^2; нужно разделить на 2.','∫−4x dx = −2x^2, −4x^2 emas; yangi daraja 2 ga bo‘ling.','Apply the power rule to each term separately.','Применяйте степенное правило к каждому члену отдельно.','Daraja qoidasini har bir hadga alohida qo‘llang.'),
('P1INT01-D01','D','constant_term_not_integrated','concept','The antiderivative of the constant 3 is 3x, not 3.','Первообразная постоянной 3 равна 3x, а не 3.','3 doimiyning integrali 3x, 3 emas.','Remember that differentiating 3x gives 3.','Помните: производная 3x равна 3.','3x ning hosilasi 3 ekanini eslang.'),
('P1INT02-D01','B','uses_point_y_as_C','method','The y-coordinate 5 is not automatically C; substitute both x=2 and y=5 into the integrated family.','Координата y=5 не является автоматически C; нужно подставить x=2 и y=5 в семейство первообразных.','y=5 avtomatik C emas; integrallangan oilaga x=2 va y=5 ni qo‘ying.','Solve for C only after substituting the full point.','C ni faqat to‘liq nuqtani qo‘ygandan keyin toping.','C ni to‘liq nuqtani qo‘ygandan keyin yeching.'),
('P1INT02-D01','C','antiderivative_coefficient_error','method','∫6x dx is 3x^2, not 6x^2.','∫6x dx = 3x^2, 6x^2 emas.','∫6x dx = 3x^2, 6x^2 emas.','Check the antiderivative by differentiation before using the point.','Перед использованием точки проверьте первообразную производной.','Nuqtani ishlatishdan oldin integralni hosila bilan tekshiring.'),
('P1INT02-D01','D','omits_constant','concept','Without C, the curve gives y=4 at x=2, but the stated point has y=5.','Без C при x=2 получается y=4, но задана точка с y=5.','C siz x=2 da y=4 chiqadi, lekin berilgan y=5.','A point condition selects one member of the antiderivative family.','Условие точки выбирает одну функцию из семейства первообразных.','Nuqta sharti integral oilasidan bitta funksiyani tanlaydi.'),
('P1INT03-D01','B','drops_constant_term_area','method','The 3x^2 part contributes 8, but the constant 1 contributes another interval length 2.','Часть 3x^2 даёт 8, но постоянная 1 даёт ещё 2 — длину интервала.','3x^2 qismi 8 beradi, lekin 1 doimiy yana interval uzunligi 2 ni beradi.','Integrate every term before applying limits.','Проинтегрируйте каждый член перед подстановкой пределов.','Chegaralarni qo‘yishdan oldin har bir hadni integrallang.'),
('P1INT03-D01','C','uses_endpoint_function_value','concept','13 is the integrand value at x=2, not the accumulated definite integral over 0≤x≤2.','13 — значение подынтегральной функции при x=2, а не определённого интеграла.','13 x=2 dagi integrand qiymati, 0≤x≤2 bo‘yicha integral emas.','Find an antiderivative and subtract lower-end value from upper-end value.','Найдите первообразную и вычтите значение на нижнем пределе из верхнего.','Boshlang‘ich funksiyani topib, yuqori qiymatdan pastki qiymatni ayiring.'),
('P1INT03-D01','D','averages_integral','concept','Dividing the definite integral by the interval length would give an average value, but the question asks for the integral itself.','Деление интеграла на длину интервала даёт среднее значение, но требуется сам интеграл.','Integralni interval uzunligiga bo‘lish o‘rtacha qiymat beradi, savol esa integralning o‘zini so‘raydi.','Keep definite integral and average value as different quantities.','Не смешивайте определённый интеграл и среднее значение функции.','Aniq integral va o‘rtacha qiymatni aralashtirmang.'))
insert into private.exam_prep_diagnostic_rules(content_meta_id,rule_version,answer_kind,answer_match,distractor_code,mistake_type,weak_skill_code,feedback_en,feedback_ru,feedback_uz,next_action_en,next_action_ru,next_action_uz,status,approved_at)
select meta.id,'drv1','mcq_option',r.match,r.dcode,r.mtype,meta.primary_skill_code,r.fen,r.fru,r.fuz,r.nen,r.nru,r.nuz,'approved',now() from r join meta on meta.content_key=r.ckey
on conflict(content_meta_id,rule_version,answer_kind,answer_match) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_core_v1' and status='draft'), defs(task_key,skill,en,ru,uz,rubric,sen,sru,suz) as (values
('P1INT01-W01','P1-INT-01','Find ∫[6x^2−4x+3(2x−1)^2] dx. Show the power-rule step for the polynomial and the reverse-chain-rule step for (2x−1)^2, then differentiate your final answer to verify it.','Найдите ∫[6x^2−4x+3(2x−1)^2] dx. Покажите степенное правило для полинома и обратное правило цепочки для (2x−1)^2, затем продифференцируйте ответ для проверки.','∫[6x^2−4x+3(2x−1)^2] dx ni toping. Polinom uchun daraja qoidasini va (2x−1)^2 uchun teskari chain rule ni ko‘rsating, so‘ng javobni hosila olib tekshiring.','{"max_marks":10,"criteria":[{"id":"poly","marks":3,"rule":"Gets 2x^3−2x^2 for first two terms."},{"id":"linear_power","marks":3,"rule":"Gets (2x−1)^3/2 from 3(2x−1)^2."},{"id":"constant","marks":1,"rule":"Includes +C."},{"id":"verification","marks":3,"rule":"Differentiates final expression back to the full integrand."}]}','Treat each term independently, but for (ax+b)^n also divide by the inner coefficient a.','Рассматривайте члены отдельно; для (ax+b)^n дополнительно делите на внутренний коэффициент a.','Har bir hadni alohida ko‘ring; (ax+b)^n uchun ichki a koeffitsientga ham bo‘ling.'),
('P1INT02-W01','P1-INT-02','A curve has gradient dy/dx=3x^2−4x+2 and passes through (1,7). Find its equation, then find y when x=3. Show how the point condition determines C.','Кривая имеет dy/dx=3x^2−4x+2 и проходит через (1,7). Найдите её уравнение, затем y при x=3. Покажите, как точка определяет C.','Egri chiziq dy/dx=3x^2−4x+2 va (1,7) dan o‘tadi. Tenglamasini, so‘ng x=3 dagi y ni toping. Nuqta C ni qanday aniqlashini ko‘rsating.','{"max_marks":10,"criteria":[{"id":"integral","marks":3,"rule":"Gets y=x^3−2x^2+2x+C."},{"id":"constant","marks":3,"rule":"Uses (1,7) to get C=6."},{"id":"equation","marks":1,"rule":"States y=x^3−2x^2+2x+6."},{"id":"evaluation","marks":2,"rule":"Gets y(3)=21."},{"id":"check","marks":1,"rule":"Point or derivative check is consistent."}]}','Do not substitute the point until the indefinite integration, including C, is complete.','Не подставляйте точку до завершения неопределённого интегрирования с C.','C bilan noaniq integral tugamaguncha nuqtani qo‘ymang.'),
('P1INT03-W01','P1-INT-03','Evaluate ∫ from 0 to 3 of (2x^2−4x+5) dx and the convergent endpoint integral ∫ from 0 to 9 of x^(−1/2) dx. For each, show the antiderivative and limit substitution; explain why the second integral is finite despite the integrand being undefined at x=0.','Вычислите ∫ от 0 до 3 (2x^2−4x+5) dx и сходящийся интеграл ∫ от 0 до 9 x^(−1/2) dx. Для каждого покажите первообразную и подстановку пределов; объясните, почему второй конечен, хотя функция не определена при x=0.','0 dan 3 gacha ∫(2x^2−4x+5) dx va 0 dan 9 gacha ∫x^(−1/2) dx yaqinlashuvchi integralni hisoblang. Har biri uchun boshlang‘ich funksiya va limitni ko‘rsating; ikkinchisi x=0 da aniqlanmagan bo‘lsa ham nega chekli ekanini tushuntiring.','{"max_marks":11,"criteria":[{"id":"poly_antiderivative","marks":2,"rule":"Uses (2/3)x^3−2x^2+5x."},{"id":"poly_value","marks":2,"rule":"Gets 15."},{"id":"endpoint_antiderivative","marks":2,"rule":"Uses 2sqrt(x)."},{"id":"endpoint_value","marks":2,"rule":"Gets 6 via limit a->0+."},{"id":"limit_reasoning","marks":3,"rule":"Explains the endpoint is improper but the antiderivative has finite limit 0 there."}]}','For the endpoint case replace 0 temporarily by a>0 and take the limit only after evaluating the antiderivative.','Для особой конечной точки временно замените 0 на a>0 и возьмите предел после подстановки в первообразную.','Chegara holatida 0 ni vaqtincha a>0 bilan almashtirib, boshlang‘ich funksiyani hisoblagach limit oling.'))
insert into private.exam_prep_written_tasks(content_version_id,task_key,component_code,primary_skill_code,task_version,prompt_en,prompt_ru,prompt_uz,rubric_json,self_review_en,self_review_ru,self_review_uz,lifecycle_state,copyright_status,qa_math_status,qa_language_status,qa_technical_status,approved_at)
select cv.id,d.task_key,'P1',d.skill,'wtv1',d.en,d.ru,d.uz,d.rubric::jsonb,d.sen,d.sru,d.suz,'approved','pass','pass','pass','pass',now() from defs d cross join cv
on conflict(content_version_id,task_key,task_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_core_v1' and status='draft'), defs(k,t,en,ru,uz) as (values
('p1_aw21_int_core_diagnostic','diagnostic','P1 AW21-24 Integration core diagnostic','Диагностика P1 AW21–24: основы интегрирования','P1 AW21–24 integrallash asoslari diagnostikasi'),
('p1_int01_learning','learning','Antiderivatives learning','Первообразные: обучение','Boshlang‘ich funksiyalar: o‘rganish'),('p1_int02_learning','learning','Boundary-condition integration learning','Интегрирование с условием точки: обучение','Nuqta sharti bilan integrallash: o‘rganish'),('p1_int03_learning','learning','Definite integrals learning','Определённые интегралы: обучение','Aniq integrallar: o‘rganish'),
('p1_int01_retest','retest','INT-01 delayed retest','INT-01 отложенный ретест','INT-01 kechiktirilgan retest'),('p1_int02_retest','retest','INT-02 delayed retest','INT-02 отложенный ретест','INT-02 kechiktirilgan retest'),('p1_int03_retest','retest','INT-03 delayed retest','INT-03 отложенный ретест','INT-03 kechiktirilgan retest'),
('p1_aw21_int_core_mixed','mixed','P1 AW21-24 Integration core mixed transfer','P1 AW21–24: смешанный перенос основ интегрирования','P1 AW21–24 integrallash mixed transfer'))
insert into private.exam_prep_assessments(content_version_id,assessment_key,assessment_version,component_code,assessment_type,status,title_en,title_ru,title_uz)
select cv.id,d.k,'av1','P1',d.t,'approved',d.en,d.ru,d.uz from defs d cross join cv
on conflict(content_version_id,assessment_key,assessment_version) do nothing;

with cv as (select id from private.exam_prep_content_versions where content_version='p1_aw21_24_integration_core_v1'), a as (select x.id,x.assessment_key from private.exam_prep_assessments x join cv on cv.id=x.content_version_id), m as (select x.content_key,x.question_id from private.exam_prep_question_content_meta x join cv on cv.id=x.content_version_id), w as (select x.id,x.task_key from private.exam_prep_written_tasks x join cv on cv.id=x.content_version_id), items(akey,ord,ckey,wkey,skill,role,holdout) as (values
('p1_aw21_int_core_diagnostic',1,'P1INT01-D01',null,'P1-INT-01','diagnostic',true),('p1_aw21_int_core_diagnostic',2,'P1INT02-D01',null,'P1-INT-02','diagnostic',true),('p1_aw21_int_core_diagnostic',3,'P1INT03-D01',null,'P1-INT-03','diagnostic',true),
('p1_int01_learning',1,'P1INT01-L01',null,'P1-INT-01','learning',false),('p1_int01_learning',2,'P1INT01-L02',null,'P1-INT-01','learning',false),('p1_int01_learning',3,'P1INT01-L03',null,'P1-INT-01','learning',false),('p1_int01_learning',4,null,'P1INT01-W01','P1-INT-01','written',false),
('p1_int02_learning',1,'P1INT02-L01',null,'P1-INT-02','learning',false),('p1_int02_learning',2,'P1INT02-L02',null,'P1-INT-02','learning',false),('p1_int02_learning',3,'P1INT02-L03',null,'P1-INT-02','learning',false),('p1_int02_learning',4,null,'P1INT02-W01','P1-INT-02','written',false),
('p1_int03_learning',1,'P1INT03-L01',null,'P1-INT-03','learning',false),('p1_int03_learning',2,'P1INT03-L02',null,'P1-INT-03','learning',false),('p1_int03_learning',3,'P1INT03-L03',null,'P1-INT-03','learning',false),('p1_int03_learning',4,null,'P1INT03-W01','P1-INT-03','written',false),
('p1_int01_retest',1,'P1INT01-R01',null,'P1-INT-01','retest',true),('p1_int02_retest',1,'P1INT02-R01',null,'P1-INT-02','retest',true),('p1_int03_retest',1,'P1INT03-R01',null,'P1-INT-03','retest',true),
('p1_aw21_int_core_mixed',1,'P1INT01-M01',null,'P1-INT-01','mixed',true),('p1_aw21_int_core_mixed',2,'P1INT02-M01',null,'P1-INT-02','mixed',true),('p1_aw21_int_core_mixed',3,'P1INT03-M01',null,'P1-INT-03','mixed',true))
insert into private.exam_prep_assessment_items(assessment_id,item_order,question_id,written_task_id,primary_skill_code,reserve_role,is_holdout)
select a.id,i.ord,m.question_id,w.id,i.skill,i.role,i.holdout from items i join a on a.assessment_key=i.akey left join m on m.content_key=i.ckey left join w on w.task_key=i.wkey
on conflict(assessment_id,item_order) do nothing;

update private.exam_prep_question_content_meta m set copyright_status='pass',qa_scope_status='pass',qa_math_status='pass',qa_language_status='pass',qa_technical_status='pass',diagnostic_rule_status=case when reserve_role='diagnostic' then 'approved' else 'not_applicable' end,lifecycle_state='approved',approved_at=now(),updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_integration_core_v1' and cv.status='draft';
update private.exam_prep_content_versions set status='approved',approved_at=now() where content_version='p1_aw21_24_integration_core_v1' and status='draft';
update private.exam_prep_question_content_meta m set lifecycle_state=case when reserve_role='learning' then 'published' else 'reserve' end,exposure_state=case when reserve_role='learning' then 'released' else 'withheld' end,published_at=case when reserve_role='learning' then now() else null end,updated_at=now() from private.exam_prep_content_versions cv where cv.id=m.content_version_id and cv.content_version='p1_aw21_24_integration_core_v1' and cv.status='approved';
update private.exam_prep_written_tasks w set lifecycle_state='published' from private.exam_prep_content_versions cv where cv.id=w.content_version_id and cv.content_version='p1_aw21_24_integration_core_v1' and cv.status='approved';
update private.exam_prep_assessments a set status='published',approved_at=coalesce(a.approved_at,now()) from private.exam_prep_content_versions cv where cv.id=a.content_version_id and cv.content_version='p1_aw21_24_integration_core_v1' and cv.status='approved';
update private.exam_prep_content_versions set status='published',published_at=now() where content_version='p1_aw21_24_integration_core_v1' and status='approved';

do $$ declare v_program bigint; v_skill text; begin
 select id into v_program from private.exam_prep_program_versions where program_key='math_as_p1_p5' and version_key='p1_p5_canonical_v1_0';
 foreach v_skill in array array['P1-INT-01','P1-INT-02','P1-INT-03'] loop
   if not private.exam_prep_skill_content_ready_v1(v_program,'P1',v_skill) then raise exception 'P1 integration core skill not ready %',v_skill; end if;
 end loop;
 if exists(select 1 from public.questions where book_ref like 'ExamPrep:P1:p1_aw21_24_integration_core_v1:%' and is_active) then raise exception 'P1 integration core legacy activation residue'; end if;
 if exists(select 1 from private.exam_prep_feature_config where program_key='math_as_p1_p5' and (rollout_state<>'off' or core_enabled or ai_enabled or mentor_enabled or not kill_switch)) then raise exception 'P1 integration core publication escaped fail-closed'; end if;
 if exists(select 1 from private.exam_prep_feature_entitlements where entitlement_status='active') then raise exception 'P1 integration core active entitlement residue'; end if;
end $$;
commit;
